### ISSUE TITLE
Qulice code checks are unclear

### ISSUE THREAD

**Issue by englishman** [yegor256/cactoos#10]
@yegor256 please, share somewhere `Qulice` static code rules (preferable in `README.md` file).
For me such errors are cryptic (at lease the first one)
```
[INFO] Checkstyle: src/main/java/org/cactoos/text/BlankText.java[63]: Using '++' is not allowed. (IllegalTokenCheck)
[INFO] Checkstyle: src/test/java/org/cactoos/text/BlankTextTest.java[47]: Indentation (20) must be same or less than previous line (12), or bigger by exactly 4 (CascadeIndentationCheck)
[INFO] Checkstyle: src/test/java/org/cactoos/text/BlankTextTest.java[61]: Indentation (20) must be same or less than previous line (12), or bigger by exactly 4 (CascadeIndentationCheck)
[INFO] Checkstyle: src/test/java/org/cactoos/text/BlankTextTest.java[75]: Indentation (20) must be same or less than previous line (12), or bigger by exactly 4 (CascadeIndentationCheck)
```

**Comment by 0crat** [comment]
@englishman I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by englishman** [comment]
@yegor256 it's unbelievable! WTH I have to use `pos = pos + 1` instead of `pos++`?!!

**Comment by yegor256** [comment]
@englishman you should use `++pos`

**Comment by yegor256** [comment]
@englishman I believe it's a question for Checkstyle, not to us. You can find that error messages in Google and first few links will lead you to Checkstyle pages, which will explain (hopefully).

**Comment by englishman** [comment]
@yegor256 I disagree. The link to `Checkstyle` checks has to be provided in `README.md`.

Also `Checkstyle` compatible java code format settings should be created for IntelliJ IDEA and/or Eclipse. So any new developers imply can pick up them and start write perfect code.
