### ISSUE TITLE
Mutable collections

### ISSUE THREAD

**Issue by Iprogrammerr** [yegor256/cactoos#1008]
We should create MutableCollectionEnvelope. Objects immutability is our core principle, but I think that mutability of collections is something different and it is often the case that we need them (#898).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by wladyan** [comment]
@Iprogrammerr I think envelopes must be orthogonal to immutability principle (#947).

**Comment by Iprogrammerr** [comment]
@wladyan I agree. I propose to refactor CollectionEnvelope so that it does not care about immutability as described in #947. We then could add ImmutableCollection decorator that will work in the same manner as CollectionEnvelope is right now. I am willing to do that. @llorllale  WDYT?

**Comment by llorllale** [comment]
@Iprogrammerr this is a duplicate of #947
