### ISSUE TITLE
FuncAsIterator

### ISSUE THREAD

**Issue by Timmeey** [yegor256/cactoos#101]
Let's build a FuncAsIterator.

Example, you want an Endless Iterator/Iterable of PrimeNumbers. You would do (pseudocode)
```java
new Iterable(
   new Iterator(
      new PrimeFunc()
   )
);
```
What should be the API of such a construct?

Should the Function that provides the next value take the last value as input, so the iterator would hold some state? Or should we have something new like a Provider<X> that does not take input and hold his own state? 

Once we get the API clear, i would like to contribute this.

**Comment by 0crat** [comment]
@timmeey I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@Timmeey good idea. I thought that `RepeatIterator` and `EndlessIterator` will both accept either a fixed element value of a `Func`, which returns it. But I didn't think about making this `Func` aware of the previous value. That's something we should think about.

**Comment by Timmeey** [comment]
Yeah, you gave me the idea when i saw your EndlessIterator and how great it would be to be able to treat the result of a sequential function as a list.

But i would not want it for only EndlessIterator since there might be functions that have a finite number of results.

Your endlessIess iterator could definitely accept a staticFunc/scalar as input. But i still think we would need FuncAsIterator.

I'll submit a PR in which we can discuss the API in a live setting.

**Comment by yegor256** [comment]
@Timmeey yes, please go ahead. Also, please start your messages with the name of the person you're talking to. That's how I will see them for sure.

**Comment by Timmeey** [comment]
@yegor256 a very very early draft of what i had in mind.
https://github.com/Timmeey/cactoos/commit/646b9ddec279540e36ed6a46e26c3d5fe437f958

Problems to discuss are:
What to do with more complex objects that get returned by the function, when the next element is not derivable from the last returned one?  Maybe in that case a `Provider<X>` would be useful, which holds internal state to calculate the next element?
Also we should generally think about trying to avoid the usage of LengthOfIterator because it breaks things if you are not careful (see the second FuncAsIterableTest)

Also there are several coding style issues in the FuncAsIterator, the usage of null and exceptions for flowcontrol, which i have to fix. But for a start how the API should look it should be okay.

**Comment by yegor256** [comment]
@Timmeey it seems that we need two classes. The first one will create an iterable from a `Func`:

```java
new FuncAsIterable(i -> Math.pow(i, 2));
```

Here `i` will be the position of the element. Thus, this iterable will produce `0, 1, 4, 9, 16, 25, ...`. 

Then, we need a `Func` that remembers previous response and passes it into the next one, as an argument. For example, this one will produce Fibonacci numbers:

```java
new FuncAsIterable(new AccumulatingFunc((x, p) -> x + p));
```

Make sense?

**Comment by Timmeey** [comment]
@yegor256 Yes, that is almost how i did it in the linked draft. It has a FuncAsIterable(Func<X,X>) and FuncAsIterator(Func<X,X>)

That works well for mathematical functions where the result contains all necessary information to calculate the next one. 

The questions remains. How to bootstrap such a function on the first call? just pass it NULL?

**Comment by yegor256** [comment]
@Timmeey it seems to me that you're combining two things into one object. I think that `FuncAsInterable` has to be declared like this:

```java
class FuncAsIterable<T> implements Iterable<T> {
  FuncAsIterable(Func<Integer, T>) {
    // ...
  }
}
```

The `Integer` will be generated, starting from `0`. See?

**Comment by yegor256** [comment]
@Timmeey or maybe even this design is wrong and we better need this:

```java
new TransformedIterable<>(
  new NaturalNumbers(),
  i -> Math.pow(i, 2)
);
```

**Comment by Timmeey** [comment]
@yegor256  But that only works for Functions that calculate the next value based on e.g. Integers.

Example: Deterministic RandomGenerators, they always take the last result to generate the next, which is not necessarily a Integer. (If the seed is the same, it will always generate the same sequence).

I want to have a general  purpose FuncAsIterable without limiting it to only work based on a fixed type of input. I still think that
```java
public FuncAsIterator<X>(Func<X,X> func, X initialValue){}
public X next(){
  return func.apply(lastReturnedValue);
}
```
would be the most general solution, which would also solve the bootstrapping problem, by letting the user supply the initalValue to feed into the function.

I think we should start from this easy usecase where it just takes the last result. If then the need arises for something not covered by this i will revisit this. 

WDYT?

**Comment by yegor256** [comment]
@Timmeey but this situation where a function needs its previous result is a corner case. In most cases, we don't need that. That's why I'm suggesting to break this problem down to pieces.

**Comment by Timmeey** [comment]
```java
public final class SequentialFuncAsIterable<X>{
  private final TransformedIterable<X> iterable;
  public SequentialFuncAsIterable(Func<Integer,X> func){
    this(new NaturalNumbers(), func);
  }

  public SequentialFuncAsIterable(Func<X,X> func, Iterable<X> input){
    this.iterable=new TransformedIterable(input,func);
  }

  public Iterator<X> iterator(){
    return this.iterator.iterator();
  }
}
  ```
@yegor256 you are completely right, the SequentialFuncAsIterable is exactly the same as the Transformed Iterable. wow. I would still want to have this class, just to make it obvious on how to deal with these kind of things. But we could discuss whether the Ctor with two arguments is useful or if the first one (with the naturalNumbers buildin) suffice.

But here the draft for a FeedbackFuncAsIterable
As an example you could use it to calculate Primes as an Iterable. Which gets MUCH more efficient, if you know the last returned Prime.
But i also see that this would blow up the Library with a class that might be rarely used. (But hey, i already came up with two applications for this, by just thinking about it during commute)
```java
public final class FeedbackFuncAsIterable<X>{
  private final Func<X,X> func;
  private X initial;

  public FeedbackFuncAsIterable(Func<X,X> func, X inital){}

  public Iterator<X> iterator(){
    return new FeedbackFuncAsIterator(funx,inital);
  }
}

public final class FeedbackFuncAsIterator<X>{
  private final Func<X,X> func;
  private X input;

  public FeedbackFuncAsIterator(Func<X,X> func, X inital){}

  public boolean hasNext(){
    //Or cache the next result, and if it is present return true, otherwise false
    return true;
  }

  public X next(){
    input= func.apply(input);
    return input;
}
```
This way we strictly separate the different types, so that everything is doing exactly one thing. unfortunately without any code reuse.I think there might be a way to reuse TransformedIterator but that would not be pretty.

**Comment by yegor256** [comment]
@Timmeey let's go step by step. Let's start with `NaturalNumbers`. Can you submit a PR for this class?

**Comment by llorllale** [comment]
@Timmeey can we close this?

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
