### ISSUE TITLE
Func.java:65-67: Move NoNulls implementations of Func,...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1015]
The puzzle `852-703228b2` from #852 has to be resolved: 

https://github.com/yegor256/cactoos/blob/de9031f0d59ec0f5405871c6080e445beacafde5/src/main/java/org/cactoos/Func.java#L65-L67

The puzzle was created by @rultor on 16-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
This puzzle inherited milestone `1.0` from issue #852.

**Comment by 0crat** [comment]
Job [#1015](https://github.com/yegor256/cactoos/issues/1015) is now in scope, role is `DEV`

**Comment by Iprogrammerr** [comment]
Func, BiFunc nad Proc implementations are all in func package. Moving their inner NoNulls classes can not be done without naming collisions or contradicting new classes naming convention. See #1016

**Comment by 0crat** [comment]
The job [#1015](https://github.com/yegor256/cactoos/issues/1015) assigned to @mazdack[/z](https://www.0crat.com/u/mazdack), here is [why](https://www.0crat.com/footprint/C63314D6Z/3ef80752-8d9c-4ac7-89a3-3deaded3f252); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by llorllale** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1015#issuecomment-474141438))

@llorllale The user @mazdack[/z](https://www.0crat.com/u/mazdack) resigned from [#1015](https://github.com/yegor256/cactoos/issues/1015), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#1015](https://github.com/yegor256/cactoos/issues/1015) assigned to @golyalpha[/z](https://www.0crat.com/u/golyalpha), here is [why](https://www.0crat.com/footprint/C63314D6Z/afdcc077-7d57-4d58-a684-72f28b472f26); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The job [#1015](https://github.com/yegor256/cactoos/issues/1015) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/62fe216d-2369-4d0b-b887-f15ef00ec73f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@llorllale the same happened here :)

**Comment by victornoel** [comment]
@llorllale ah but no PR exists for this one, so I can take care of it if you confirm :)

**Comment by llorllale** [comment]
@victornoel go ahead with this one

**Comment by victornoel** [comment]
@llorllale what about naming? There is going to be 4 new classes inside `func` package, should it be `NoNullsFunc`, `NoNullsBiFunc`, etc?

**Comment by victornoel** [comment]
@llorllale any idea on the above question?

**Comment by llorllale** [comment]
@victornoel let's use `NoNulls` as a suffix.

I think `Proc` and `BiProc` are decent candidates for removal once we get to #915.

**Comment by victornoel** [comment]
@0crat wait for #1090 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #1090 to be merged ([here](https://github.com/yegor256/cactoos/issues/1015#issuecomment-478236972))

@victornoel The impediment for [#1015](https://github.com/yegor256/cactoos/issues/1015) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0pdd** [comment]
The puzzle `852-703228b2` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#1015](https://github.com/yegor256/cactoos/issues/1015) is not in the agenda of @victornoel[/z](https://www.0crat.com/u/victornoel), can't inspect

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1015](https://github.com/yegor256/cactoos/issues/1015) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality acceptable

@Iprogrammerr please make sure that messages in a job always start with a name of a user they are addressed to: as written [here](http://www.zerocracy.com/policy.html#30) and [here](https://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#4-avoid-noiseaddress-your-comments)

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
