### ISSUE TITLE
Input.java:62-64: Move NoNulls implementations of Input,...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1016]
The puzzle `852-196f2f04` from #852 has to be resolved: 

https://github.com/yegor256/cactoos/blob/de9031f0d59ec0f5405871c6080e445beacafde5/src/main/java/org/cactoos/Input.java#L62-L64

The puzzle was created by rultor on 16-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
This puzzle inherited milestone `1.0` from issue #852.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1016](https://github.com/yegor256/cactoos/issues/1016) is now in scope, role is `DEV`

**Comment by Iprogrammerr** [comment]
It is impossible to move Input.NoNulls and Output.NoNulls to io package due to naming collision. Renaming them to InputNoNulls and OutputNoNulls will contradict #852. If we want to be consistent with new naming convention stated in #913, we have to split io package to input and output. @llorllale WDYT?

**Comment by fabriciofx** [comment]
@Iprogrammerr I like the idea. Look I think this refactoring detected a design problem: too much classes inside the same package. So, a solution is divide Input/Output classes in two packages: input and output. IMHO perfect!

**Comment by Iprogrammerr** [comment]
@fabriciofx Thanks, exactly. I would say that the same holds true for func package. There are func, bifunc and proc implementations. See #1015.

**Comment by 0crat** [comment]
The job [#1016](https://github.com/yegor256/cactoos/issues/1016) assigned to @mazdack[/z](https://www.0crat.com/u/mazdack), here is [why](https://www.0crat.com/footprint/C63314D6Z/907c8f0c-bf44-4d9a-92ab-635160dc5c09); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by llorllale** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1016#issuecomment-474141486))

@llorllale The user @mazdack[/z](https://www.0crat.com/u/mazdack) resigned from [#1016](https://github.com/yegor256/cactoos/issues/1016), please stop working. Reason for job resignation: Order was cancelled

**Comment by llorllale** [comment]
@0crat assign @mazdack

**Comment by 0crat** [comment]
> @0crat assign @mazdack ([here](https://github.com/yegor256/cactoos/issues/1016#issuecomment-475455526))

@llorllale The job [#1016](https://github.com/yegor256/cactoos/issues/1016) assigned to @mazdack[/z](https://www.0crat.com/u/mazdack), here is [why](https://www.0crat.com/footprint/C63314D6Z/e0fce523-d59c-4453-b2c1-106dfc5ba67b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
The puzzle `852-196f2f04` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#1016](https://github.com/yegor256/cactoos/issues/1016) is not in the agenda of @mazdack[/z](https://www.0crat.com/u/mazdack), can't inspect

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @mazdack[/z](https://www.0crat.com/u/mazdack), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1016](https://github.com/yegor256/cactoos/issues/1016) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality acceptable

@Iprogrammerr please make sure that messages in a job always start with a name of a user they are addressed to

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @mazdack[/z](https://www.0crat.com/u/mazdack)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
