### ISSUE TITLE
CollectionNoNulls.java:39-41: Rename XxxNoNulls...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1017]
The puzzle `852-72b3f84c` from #852 has to be resolved: 

https://github.com/yegor256/cactoos/blob/de9031f0d59ec0f5405871c6080e445beacafde5/src/main/java/org/cactoos/collection/CollectionNoNulls.java#L39-L41

The puzzle was created by rultor on 16-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
This puzzle inherited milestone `1.0` from issue #852.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1017](https://github.com/yegor256/cactoos/issues/1017) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `852-72b3f84c` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1017` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1017](https://github.com/yegor256/cactoos/issues/1017) is now out of scope
