### ISSUE TITLE
Temporary folder

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#1022]
Let's create a class that permits create a temporary folder. The idea is similar which `TempFile` does, but to a folder.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/1022#issuecomment-455588619))

@llorllale Job [#1022](https://github.com/yegor256/cactoos/issues/1022) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by Iprogrammerr** [comment]
@llorllale I would like to implement this. Could you assign me?

**Comment by llorllale** [comment]
@0crat assign @Iprogrammerr

**Comment by 0crat** [comment]
> @0crat assign @Iprogrammerr  ([here](https://github.com/yegor256/cactoos/issues/1022#issuecomment-457930847))

@llorllale The job [#1022](https://github.com/yegor256/cactoos/issues/1022) assigned to @iprogrammerr[/z](https://www.0crat.com/u/iprogrammerr), here is [why](https://www.0crat.com/footprint/C63314D6Z/90dd2aa5-9dd4-4566-9458-a337b4378062); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#1022](https://github.com/yegor256/cactoos/issues/1022) assigned to @longstone[/z](https://www.0crat.com/u/longstone), here is [why](https://www.0crat.com/footprint/C63314D6Z/38a4910a-450f-49f4-b1e6-8a6d519507b1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by longstone** [comment]
@0crat wait @llorllale  I assume this was forgotten to close? see https://github.com/yegor256/cactoos/pull/1049, I think its already resolved by @Iprogrammerr .

**Comment by 0crat** [comment]
> @0crat wait @llorllale I assume this was forgotten to close? see https://github.com/yegor256/cac... ([here](https://github.com/yegor256/cactoos/issues/1022#issuecomment-480489575))

@longstone The impediment for [#1022](https://github.com/yegor256/cactoos/issues/1022) was registered successfully by @longstone[/z](https://www.0crat.com/u/longstone)

**Comment by llorllale** [comment]
@longstone yes, you're right. You can claim the ZC points yourself.

**Comment by longstone** [comment]
@fabriciofx as the task is done, can you please close the ticket?

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @longstone[/z](https://www.0crat.com/u/longstone), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1022](https://github.com/yegor256/cactoos/issues/1022) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @longstone[/z](https://www.0crat.com/u/longstone)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
