### ISSUE TITLE
Replace use of "@Rule ExpectedException" with new Throws matcher introduced in cactoos-matchers 0.13

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#1023]
Let's update do cactoos-matchers 0.13. This update is necessary to use `Throws` class to avoid exception rule at tests.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by fabriciofx** [comment]
@llorllale done.

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/1023#issuecomment-455665920))

@llorllale Job [#1023](https://github.com/yegor256/cactoos/issues/1023) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by Iprogrammerr** [comment]
@llorllale Could you assign me?

**Comment by llorllale** [comment]
@0crat assign @Iprogrammerr

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
@fabriciofx the puzzle [#1039](https://github.com/yegor256/cactoos/issues/1039) is still not solved.

**Comment by fabriciofx** [comment]
Closed by #1027.

**Comment by 0crat** [comment]
The job [#1023](https://github.com/yegor256/cactoos/issues/1023) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @iprogrammerr[/z](https://www.0crat.com/u/iprogrammerr)

**Comment by 0pdd** [comment]
@fabriciofx the puzzle [#1106](https://github.com/yegor256/cactoos/issues/1106) is still not solved; solved: [#1039](https://github.com/yegor256/cactoos/issues/1039).

**Comment by 0pdd** [comment]
@fabriciofx all 2 puzzles are solved here: [#1039](https://github.com/yegor256/cactoos/issues/1039), [#1106](https://github.com/yegor256/cactoos/issues/1106).
