### ISSUE TITLE
ComparableText is not equal to the same text

### ISSUE THREAD

**Issue by ilyakharlamov** [yegor256/cactoos#1030]
```
Text text = new TextOf("abc");
final Text a = new ComparableText(
    text
);
final Text b = new ComparableText(
    text
);
System.out.format("a.equals(b)==%s", a.equals(b));
```

What's wrong:
a.equals(b)==false

Expected result:
a.equals(b)==true

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov)

**Comment by fabriciofx** [comment]
@llorllale Is there any DEV to address this issue?

**Comment by llorllale** [comment]
@fabriciofx ask @0crat :)

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/cactoos/issues/1030#issuecomment-457221902); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by llorllale** [comment]
@ilyakharlamov you fixed this in PR #1031

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1030` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#1030](https://github.com/yegor256/cactoos/issues/1030) is now out of scope
