### ISSUE TITLE
Replace use of MatcherAssert.assertThat with Assertion from cactoos-matchers

### ISSUE THREAD

**Issue by llorllale** [yegor256/cactoos#1033]
... and add the signature of `MatcherAssert.assertThat` to `forbidden-apis.txt`

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/1033#issuecomment-456233199))

@llorllale Job [#1033](https://github.com/yegor256/cactoos/issues/1033) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#1033](https://github.com/yegor256/cactoos/issues/1033) assigned to @longstone[/z](https://www.0crat.com/u/longstone), here is [why](https://www.0crat.com/footprint/C63314D6Z/cf79bfb4-6f3d-4d59-a5cd-6fc322fc423b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by llorllale** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1033#issuecomment-485246085))

@llorllale The user @longstone[/z](https://www.0crat.com/u/longstone) resigned from [#1033](https://github.com/yegor256/cactoos/issues/1033), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#1033](https://github.com/yegor256/cactoos/issues/1033) assigned to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), here is [why](https://www.0crat.com/footprint/C63314D6Z/d058c267-6331-4972-908f-e562f35fa3f3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by vzurauskas** [comment]
@0crat wait for #1111 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #1111 to be merged ([here](https://github.com/yegor256/cactoos/issues/1033#issuecomment-485269707))

@vzurauskas The impediment for [#1033](https://github.com/yegor256/cactoos/issues/1033) was registered successfully by @vzurauskas[/z](https://www.0crat.com/u/vzurauskas)

**Comment by 0pdd** [comment]
@llorllale the puzzle [#1117](https://github.com/yegor256/cactoos/issues/1117) is still not solved.

**Comment by vzurauskas** [comment]
@llorllale https://github.com/yegor256/cactoos/pull/1111 was merged, can this be closed now?

**Comment by llorllale** [comment]
@vzurauskas thanks

**Comment by 0crat** [comment]
Job [#1033](https://github.com/yegor256/cactoos/issues/1033) is not in the agenda of @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), can't inspect

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1033](https://github.com/yegor256/cactoos/issues/1033) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas)

**Comment by 0pdd** [comment]
@llorllale the puzzle [#1152](https://github.com/yegor256/cactoos/issues/1152) is still not solved; solved: [#1117](https://github.com/yegor256/cactoos/issues/1117).

**Comment by 0pdd** [comment]
@llorllale the puzzle [#1182](https://github.com/yegor256/cactoos/issues/1182) is still not solved; solved: [#1117](https://github.com/yegor256/cactoos/issues/1117), [#1152](https://github.com/yegor256/cactoos/issues/1152).

**Comment by 0pdd** [comment]
@llorllale the puzzle [#1228](https://github.com/yegor256/cactoos/issues/1228) is still not solved; solved: [#1117](https://github.com/yegor256/cactoos/issues/1117), [#1152](https://github.com/yegor256/cactoos/issues/1152), [#1182](https://github.com/yegor256/cactoos/issues/1182).

**Comment by 0pdd** [comment]
@llorllale the puzzle [#1235](https://github.com/yegor256/cactoos/issues/1235) is still not solved; solved: [#1117](https://github.com/yegor256/cactoos/issues/1117), [#1152](https://github.com/yegor256/cactoos/issues/1152), [#1182](https://github.com/yegor256/cactoos/issues/1182), [#1228](https://github.com/yegor256/cactoos/issues/1228).

**Comment by 0pdd** [comment]
@llorllale the puzzle [#1331](https://github.com/yegor256/cactoos/issues/1331) is still not solved; solved: [#1117](https://github.com/yegor256/cactoos/issues/1117), [#1152](https://github.com/yegor256/cactoos/issues/1152), [#1182](https://github.com/yegor256/cactoos/issues/1182), [#1228](https://github.com/yegor256/cactoos/issues/1228), [#1235](https://github.com/yegor256/cactoos/issues/1235).

**Comment by 0pdd** [comment]
@llorllale 2 puzzles [#1340](https://github.com/yegor256/cactoos/issues/1340), [#1341](https://github.com/yegor256/cactoos/issues/1341) are still not solved; solved: [#1117](https://github.com/yegor256/cactoos/issues/1117), [#1152](https://github.com/yegor256/cactoos/issues/1152), [#1182](https://github.com/yegor256/cactoos/issues/1182), [#1228](https://github.com/yegor256/cactoos/issues/1228), [#1235](https://github.com/yegor256/cactoos/issues/1235), [#1331](https://github.com/yegor256/cactoos/issues/1331).

**Comment by 0pdd** [comment]
@llorllale 2 puzzles [#1341](https://github.com/yegor256/cactoos/issues/1341), [#1343](https://github.com/yegor256/cactoos/issues/1343) are still not solved; solved: [#1117](https://github.com/yegor256/cactoos/issues/1117), [#1152](https://github.com/yegor256/cactoos/issues/1152), [#1182](https://github.com/yegor256/cactoos/issues/1182), [#1228](https://github.com/yegor256/cactoos/issues/1228), [#1235](https://github.com/yegor256/cactoos/issues/1235), [#1331](https://github.com/yegor256/cactoos/issues/1331), [#1340](https://github.com/yegor256/cactoos/issues/1340).

**Comment by 0pdd** [comment]
@llorllale 2 puzzles [#1343](https://github.com/yegor256/cactoos/issues/1343), [#1360](https://github.com/yegor256/cactoos/issues/1360) are still not solved; solved: [#1117](https://github.com/yegor256/cactoos/issues/1117), [#1152](https://github.com/yegor256/cactoos/issues/1152), [#1182](https://github.com/yegor256/cactoos/issues/1182), [#1228](https://github.com/yegor256/cactoos/issues/1228), [#1235](https://github.com/yegor256/cactoos/issues/1235), [#1331](https://github.com/yegor256/cactoos/issues/1331), [#1340](https://github.com/yegor256/cactoos/issues/1340), [#1341](https://github.com/yegor256/cactoos/issues/1341).

**Comment by 0pdd** [comment]
@llorllale 2 puzzles [#1360](https://github.com/yegor256/cactoos/issues/1360), [#1362](https://github.com/yegor256/cactoos/issues/1362) are still not solved; solved: [#1117](https://github.com/yegor256/cactoos/issues/1117), [#1152](https://github.com/yegor256/cactoos/issues/1152), [#1182](https://github.com/yegor256/cactoos/issues/1182), [#1228](https://github.com/yegor256/cactoos/issues/1228), [#1235](https://github.com/yegor256/cactoos/issues/1235), [#1331](https://github.com/yegor256/cactoos/issues/1331), [#1340](https://github.com/yegor256/cactoos/issues/1340), [#1341](https://github.com/yegor256/cactoos/issues/1341), [#1343](https://github.com/yegor256/cactoos/issues/1343).

**Comment by 0pdd** [comment]
@llorllale 2 puzzles [#1360](https://github.com/yegor256/cactoos/issues/1360), [#1367](https://github.com/yegor256/cactoos/issues/1367) are still not solved; solved: [#1117](https://github.com/yegor256/cactoos/issues/1117), [#1152](https://github.com/yegor256/cactoos/issues/1152), [#1182](https://github.com/yegor256/cactoos/issues/1182), [#1228](https://github.com/yegor256/cactoos/issues/1228), [#1235](https://github.com/yegor256/cactoos/issues/1235), [#1331](https://github.com/yegor256/cactoos/issues/1331), [#1340](https://github.com/yegor256/cactoos/issues/1340), [#1341](https://github.com/yegor256/cactoos/issues/1341), [#1343](https://github.com/yegor256/cactoos/issues/1343), [#1362](https://github.com/yegor256/cactoos/issues/1362).

**Comment by 0pdd** [comment]
@llorllale 2 puzzles [#1367](https://github.com/yegor256/cactoos/issues/1367), [#1372](https://github.com/yegor256/cactoos/issues/1372) are still not solved; solved: [#1117](https://github.com/yegor256/cactoos/issues/1117), [#1152](https://github.com/yegor256/cactoos/issues/1152), [#1182](https://github.com/yegor256/cactoos/issues/1182), [#1228](https://github.com/yegor256/cactoos/issues/1228), [#1235](https://github.com/yegor256/cactoos/issues/1235), [#1331](https://github.com/yegor256/cactoos/issues/1331), [#1340](https://github.com/yegor256/cactoos/issues/1340), [#1341](https://github.com/yegor256/cactoos/issues/1341), [#1343](https://github.com/yegor256/cactoos/issues/1343), [#1360](https://github.com/yegor256/cactoos/issues/1360), [#1362](https://github.com/yegor256/cactoos/issues/1362).

**Comment by 0pdd** [comment]
@llorllale 3 puzzles [#1372](https://github.com/yegor256/cactoos/issues/1372), [#1375](https://github.com/yegor256/cactoos/issues/1375), [#1376](https://github.com/yegor256/cactoos/issues/1376) are still not solved; solved: [#1117](https://github.com/yegor256/cactoos/issues/1117), [#1152](https://github.com/yegor256/cactoos/issues/1152), [#1182](https://github.com/yegor256/cactoos/issues/1182), [#1228](https://github.com/yegor256/cactoos/issues/1228), [#1235](https://github.com/yegor256/cactoos/issues/1235), [#1331](https://github.com/yegor256/cactoos/issues/1331), [#1340](https://github.com/yegor256/cactoos/issues/1340), [#1341](https://github.com/yegor256/cactoos/issues/1341), [#1343](https://github.com/yegor256/cactoos/issues/1343), [#1360](https://github.com/yegor256/cactoos/issues/1360), [#1362](https://github.com/yegor256/cactoos/issues/1362), [#1367](https://github.com/yegor256/cactoos/issues/1367).

**Comment by 0pdd** [comment]
@llorllale 3 puzzles [#1375](https://github.com/yegor256/cactoos/issues/1375), [#1376](https://github.com/yegor256/cactoos/issues/1376), [#1381](https://github.com/yegor256/cactoos/issues/1381) are still not solved; solved: [#1117](https://github.com/yegor256/cactoos/issues/1117), [#1152](https://github.com/yegor256/cactoos/issues/1152), [#1182](https://github.com/yegor256/cactoos/issues/1182), [#1228](https://github.com/yegor256/cactoos/issues/1228), [#1235](https://github.com/yegor256/cactoos/issues/1235), [#1331](https://github.com/yegor256/cactoos/issues/1331), [#1340](https://github.com/yegor256/cactoos/issues/1340), [#1341](https://github.com/yegor256/cactoos/issues/1341), [#1343](https://github.com/yegor256/cactoos/issues/1343), [#1360](https://github.com/yegor256/cactoos/issues/1360), [#1362](https://github.com/yegor256/cactoos/issues/1362), [#1367](https://github.com/yegor256/cactoos/issues/1367), [#1372](https://github.com/yegor256/cactoos/issues/1372).

**Comment by 0pdd** [comment]
@llorllale 2 puzzles [#1375](https://github.com/yegor256/cactoos/issues/1375), [#1381](https://github.com/yegor256/cactoos/issues/1381) are still not solved; solved: [#1117](https://github.com/yegor256/cactoos/issues/1117), [#1152](https://github.com/yegor256/cactoos/issues/1152), [#1182](https://github.com/yegor256/cactoos/issues/1182), [#1228](https://github.com/yegor256/cactoos/issues/1228), [#1235](https://github.com/yegor256/cactoos/issues/1235), [#1331](https://github.com/yegor256/cactoos/issues/1331), [#1340](https://github.com/yegor256/cactoos/issues/1340), [#1341](https://github.com/yegor256/cactoos/issues/1341), [#1343](https://github.com/yegor256/cactoos/issues/1343), [#1360](https://github.com/yegor256/cactoos/issues/1360), [#1362](https://github.com/yegor256/cactoos/issues/1362), [#1367](https://github.com/yegor256/cactoos/issues/1367), [#1372](https://github.com/yegor256/cactoos/issues/1372), [#1376](https://github.com/yegor256/cactoos/issues/1376).

**Comment by 0pdd** [comment]
@llorllale 2 puzzles [#1381](https://github.com/yegor256/cactoos/issues/1381), [#1389](https://github.com/yegor256/cactoos/issues/1389) are still not solved; solved: [#1117](https://github.com/yegor256/cactoos/issues/1117), [#1152](https://github.com/yegor256/cactoos/issues/1152), [#1182](https://github.com/yegor256/cactoos/issues/1182), [#1228](https://github.com/yegor256/cactoos/issues/1228), [#1235](https://github.com/yegor256/cactoos/issues/1235), [#1331](https://github.com/yegor256/cactoos/issues/1331), [#1340](https://github.com/yegor256/cactoos/issues/1340), [#1341](https://github.com/yegor256/cactoos/issues/1341), [#1343](https://github.com/yegor256/cactoos/issues/1343), [#1360](https://github.com/yegor256/cactoos/issues/1360), [#1362](https://github.com/yegor256/cactoos/issues/1362), [#1367](https://github.com/yegor256/cactoos/issues/1367), [#1372](https://github.com/yegor256/cactoos/issues/1372), [#1375](https://github.com/yegor256/cactoos/issues/1375), [#1376](https://github.com/yegor256/cactoos/issues/1376).

**Comment by 0pdd** [comment]
@llorllale 2 puzzles [#1381](https://github.com/yegor256/cactoos/issues/1381), [#1391](https://github.com/yegor256/cactoos/issues/1391) are still not solved; solved: [#1117](https://github.com/yegor256/cactoos/issues/1117), [#1152](https://github.com/yegor256/cactoos/issues/1152), [#1182](https://github.com/yegor256/cactoos/issues/1182), [#1228](https://github.com/yegor256/cactoos/issues/1228), [#1235](https://github.com/yegor256/cactoos/issues/1235), [#1331](https://github.com/yegor256/cactoos/issues/1331), [#1340](https://github.com/yegor256/cactoos/issues/1340), [#1341](https://github.com/yegor256/cactoos/issues/1341), [#1343](https://github.com/yegor256/cactoos/issues/1343), [#1360](https://github.com/yegor256/cactoos/issues/1360), [#1362](https://github.com/yegor256/cactoos/issues/1362), [#1367](https://github.com/yegor256/cactoos/issues/1367), [#1372](https://github.com/yegor256/cactoos/issues/1372), [#1375](https://github.com/yegor256/cactoos/issues/1375), [#1376](https://github.com/yegor256/cactoos/issues/1376), [#1389](https://github.com/yegor256/cactoos/issues/1389).

**Comment by 0pdd** [comment]
@llorllale 2 puzzles [#1391](https://github.com/yegor256/cactoos/issues/1391), [#1392](https://github.com/yegor256/cactoos/issues/1392) are still not solved; solved: [#1117](https://github.com/yegor256/cactoos/issues/1117), [#1152](https://github.com/yegor256/cactoos/issues/1152), [#1182](https://github.com/yegor256/cactoos/issues/1182), [#1228](https://github.com/yegor256/cactoos/issues/1228), [#1235](https://github.com/yegor256/cactoos/issues/1235), [#1331](https://github.com/yegor256/cactoos/issues/1331), [#1340](https://github.com/yegor256/cactoos/issues/1340), [#1341](https://github.com/yegor256/cactoos/issues/1341), [#1343](https://github.com/yegor256/cactoos/issues/1343), [#1360](https://github.com/yegor256/cactoos/issues/1360), [#1362](https://github.com/yegor256/cactoos/issues/1362), [#1367](https://github.com/yegor256/cactoos/issues/1367), [#1372](https://github.com/yegor256/cactoos/issues/1372), [#1375](https://github.com/yegor256/cactoos/issues/1375), [#1376](https://github.com/yegor256/cactoos/issues/1376), [#1381](https://github.com/yegor256/cactoos/issues/1381), [#1389](https://github.com/yegor256/cactoos/issues/1389).

**Comment by 0pdd** [comment]
@llorllale 2 puzzles [#1391](https://github.com/yegor256/cactoos/issues/1391), [#1395](https://github.com/yegor256/cactoos/issues/1395) are still not solved; solved: [#1117](https://github.com/yegor256/cactoos/issues/1117), [#1152](https://github.com/yegor256/cactoos/issues/1152), [#1182](https://github.com/yegor256/cactoos/issues/1182), [#1228](https://github.com/yegor256/cactoos/issues/1228), [#1235](https://github.com/yegor256/cactoos/issues/1235), [#1331](https://github.com/yegor256/cactoos/issues/1331), [#1340](https://github.com/yegor256/cactoos/issues/1340), [#1341](https://github.com/yegor256/cactoos/issues/1341), [#1343](https://github.com/yegor256/cactoos/issues/1343), [#1360](https://github.com/yegor256/cactoos/issues/1360), [#1362](https://github.com/yegor256/cactoos/issues/1362), [#1367](https://github.com/yegor256/cactoos/issues/1367), [#1372](https://github.com/yegor256/cactoos/issues/1372), [#1375](https://github.com/yegor256/cactoos/issues/1375), [#1376](https://github.com/yegor256/cactoos/issues/1376), [#1381](https://github.com/yegor256/cactoos/issues/1381), [#1389](https://github.com/yegor256/cactoos/issues/1389), [#1392](https://github.com/yegor256/cactoos/issues/1392).

**Comment by 0pdd** [comment]
@llorllale 2 puzzles [#1395](https://github.com/yegor256/cactoos/issues/1395), [#1396](https://github.com/yegor256/cactoos/issues/1396) are still not solved; solved: [#1117](https://github.com/yegor256/cactoos/issues/1117), [#1152](https://github.com/yegor256/cactoos/issues/1152), [#1182](https://github.com/yegor256/cactoos/issues/1182), [#1228](https://github.com/yegor256/cactoos/issues/1228), [#1235](https://github.com/yegor256/cactoos/issues/1235), [#1331](https://github.com/yegor256/cactoos/issues/1331), [#1340](https://github.com/yegor256/cactoos/issues/1340), [#1341](https://github.com/yegor256/cactoos/issues/1341), [#1343](https://github.com/yegor256/cactoos/issues/1343), [#1360](https://github.com/yegor256/cactoos/issues/1360), [#1362](https://github.com/yegor256/cactoos/issues/1362), [#1367](https://github.com/yegor256/cactoos/issues/1367), [#1372](https://github.com/yegor256/cactoos/issues/1372), [#1375](https://github.com/yegor256/cactoos/issues/1375), [#1376](https://github.com/yegor256/cactoos/issues/1376), [#1381](https://github.com/yegor256/cactoos/issues/1381), [#1389](https://github.com/yegor256/cactoos/issues/1389), [#1391](https://github.com/yegor256/cactoos/issues/1391), [#1392](https://github.com/yegor256/cactoos/issues/1392).

**Comment by 0pdd** [comment]
@llorllale 2 puzzles [#1395](https://github.com/yegor256/cactoos/issues/1395), [#1420](https://github.com/yegor256/cactoos/issues/1420) are still not solved; solved: [#1117](https://github.com/yegor256/cactoos/issues/1117), [#1152](https://github.com/yegor256/cactoos/issues/1152), [#1182](https://github.com/yegor256/cactoos/issues/1182), [#1228](https://github.com/yegor256/cactoos/issues/1228), [#1235](https://github.com/yegor256/cactoos/issues/1235), [#1331](https://github.com/yegor256/cactoos/issues/1331), [#1340](https://github.com/yegor256/cactoos/issues/1340), [#1341](https://github.com/yegor256/cactoos/issues/1341), [#1343](https://github.com/yegor256/cactoos/issues/1343), [#1360](https://github.com/yegor256/cactoos/issues/1360), [#1362](https://github.com/yegor256/cactoos/issues/1362), [#1367](https://github.com/yegor256/cactoos/issues/1367), [#1372](https://github.com/yegor256/cactoos/issues/1372), [#1375](https://github.com/yegor256/cactoos/issues/1375), [#1376](https://github.com/yegor256/cactoos/issues/1376), [#1381](https://github.com/yegor256/cactoos/issues/1381), [#1389](https://github.com/yegor256/cactoos/issues/1389), [#1391](https://github.com/yegor256/cactoos/issues/1391), [#1392](https://github.com/yegor256/cactoos/issues/1392), [#1396](https://github.com/yegor256/cactoos/issues/1396).

**Comment by 0pdd** [comment]
@llorllale 2 puzzles [#1395](https://github.com/yegor256/cactoos/issues/1395), [#1425](https://github.com/yegor256/cactoos/issues/1425) are still not solved; solved: [#1117](https://github.com/yegor256/cactoos/issues/1117), [#1152](https://github.com/yegor256/cactoos/issues/1152), [#1182](https://github.com/yegor256/cactoos/issues/1182), [#1228](https://github.com/yegor256/cactoos/issues/1228), [#1235](https://github.com/yegor256/cactoos/issues/1235), [#1331](https://github.com/yegor256/cactoos/issues/1331), [#1340](https://github.com/yegor256/cactoos/issues/1340), [#1341](https://github.com/yegor256/cactoos/issues/1341), [#1343](https://github.com/yegor256/cactoos/issues/1343), [#1360](https://github.com/yegor256/cactoos/issues/1360), [#1362](https://github.com/yegor256/cactoos/issues/1362), [#1367](https://github.com/yegor256/cactoos/issues/1367), [#1372](https://github.com/yegor256/cactoos/issues/1372), [#1375](https://github.com/yegor256/cactoos/issues/1375), [#1376](https://github.com/yegor256/cactoos/issues/1376), [#1381](https://github.com/yegor256/cactoos/issues/1381), [#1389](https://github.com/yegor256/cactoos/issues/1389), [#1391](https://github.com/yegor256/cactoos/issues/1391), [#1392](https://github.com/yegor256/cactoos/issues/1392), [#1396](https://github.com/yegor256/cactoos/issues/1396), [#1420](https://github.com/yegor256/cactoos/issues/1420).

**Comment by 0pdd** [comment]
@llorllale the puzzle [#1425](https://github.com/yegor256/cactoos/issues/1425) is still not solved; solved: [#1117](https://github.com/yegor256/cactoos/issues/1117), [#1152](https://github.com/yegor256/cactoos/issues/1152), [#1182](https://github.com/yegor256/cactoos/issues/1182), [#1228](https://github.com/yegor256/cactoos/issues/1228), [#1235](https://github.com/yegor256/cactoos/issues/1235), [#1331](https://github.com/yegor256/cactoos/issues/1331), [#1340](https://github.com/yegor256/cactoos/issues/1340), [#1341](https://github.com/yegor256/cactoos/issues/1341), [#1343](https://github.com/yegor256/cactoos/issues/1343), [#1360](https://github.com/yegor256/cactoos/issues/1360), [#1362](https://github.com/yegor256/cactoos/issues/1362), [#1367](https://github.com/yegor256/cactoos/issues/1367), [#1372](https://github.com/yegor256/cactoos/issues/1372), [#1375](https://github.com/yegor256/cactoos/issues/1375), [#1376](https://github.com/yegor256/cactoos/issues/1376), [#1381](https://github.com/yegor256/cactoos/issues/1381), [#1389](https://github.com/yegor256/cactoos/issues/1389), [#1391](https://github.com/yegor256/cactoos/issues/1391), [#1392](https://github.com/yegor256/cactoos/issues/1392), [#1395](https://github.com/yegor256/cactoos/issues/1395), [#1396](https://github.com/yegor256/cactoos/issues/1396), [#1420](https://github.com/yegor256/cactoos/issues/1420).

**Comment by 0pdd** [comment]
@llorllale the puzzle [#1559](https://github.com/yegor256/cactoos/issues/1559) is still not solved; solved: [#1117](https://github.com/yegor256/cactoos/issues/1117), [#1152](https://github.com/yegor256/cactoos/issues/1152), [#1182](https://github.com/yegor256/cactoos/issues/1182), [#1228](https://github.com/yegor256/cactoos/issues/1228), [#1235](https://github.com/yegor256/cactoos/issues/1235), [#1331](https://github.com/yegor256/cactoos/issues/1331), [#1340](https://github.com/yegor256/cactoos/issues/1340), [#1341](https://github.com/yegor256/cactoos/issues/1341), [#1343](https://github.com/yegor256/cactoos/issues/1343), [#1360](https://github.com/yegor256/cactoos/issues/1360), [#1362](https://github.com/yegor256/cactoos/issues/1362), [#1367](https://github.com/yegor256/cactoos/issues/1367), [#1372](https://github.com/yegor256/cactoos/issues/1372), [#1375](https://github.com/yegor256/cactoos/issues/1375), [#1376](https://github.com/yegor256/cactoos/issues/1376), [#1381](https://github.com/yegor256/cactoos/issues/1381), [#1389](https://github.com/yegor256/cactoos/issues/1389), [#1391](https://github.com/yegor256/cactoos/issues/1391), [#1392](https://github.com/yegor256/cactoos/issues/1392), [#1395](https://github.com/yegor256/cactoos/issues/1395), [#1396](https://github.com/yegor256/cactoos/issues/1396), [#1420](https://github.com/yegor256/cactoos/issues/1420), [#1425](https://github.com/yegor256/cactoos/issues/1425).
