### ISSUE TITLE
org.cactoos.io.Joined: add a Ctor of Iterable<Input>

### ISSUE THREAD

**Issue by ilyakharlamov** [yegor256/cactoos#1035]
org.cactoos.io.Joined in a constructor uses `new ..`.
```
private final Iterable<Input> inputs;

public Joined(final Input first, final Input... rest) {
    this.inputs = new org.cactoos.iterable.Joined<>(
        first,
        new IterableOf<>(rest)
    );
}
// there are no other constructors
```

This is valid but calling `new ` in a Ctor have a sign of a code smell.
I suggest adding a constructor that only takes `Iterable<Input>`

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@ilyakharlamov 

> calling new in a Ctor have a sign of a code smell.

I disagree. What makes you think this? We do this constantly in secondary constructors. You can think of them as "adapter constructors".

> I suggest adding a constructor that only takes Iterable<Input>

If that's something you *need*, we can surely implement it.

**Comment by ilyakharlamov** [comment]
@llorllale There is more than one way to look at this. 
For example
```
class A {
  private final List<String> list;
  A() {
     this.list = new ArrayList<String>;
  }
}
```

Using new in a constructor, relying on a concrete implementation rather than interface violates the D in SOLID  principles.
Some people find it appropriate, some are not. At some point somewhere, `new` has to be called. Just need to be very careful about calling new inside a class that a lot of other classes depend on.

**Comment by llorllale** [comment]
@ilyakharlamov the implementation of the class itself can depend just on the highest abstraction, while having secondary ctors for usability ("user experience")

**Comment by victornoel** [comment]
@llorllale can we get a new release of cactoos? The work done for this issue is needed in https://github.com/yegor256/cactoos-http/pull/69

**Comment by llorllale** [comment]
@rultor release, tag is `0.39`

**Comment by victornoel** [comment]
@llorllale thx

**Comment by llorllale** [comment]
@ilyakharlamov this was done by you in PR #1038

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1035` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
