### ISSUE TITLE
IterableOfTest.java:84-87: Implement equals() and...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1037]
The puzzle `971-205df100` from #971 has to be resolved: 

https://github.com/yegor256/cactoos/blob/ed05eb27d4a1ebe2fc36e49773fffc03682ce888/src/test/java/org/cactoos/iterable/IterableOfTest.java#L84-L87

The puzzle was created by rultor on 22-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job [#1037](https://github.com/yegor256/cactoos/issues/1037) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1037](https://github.com/yegor256/cactoos/issues/1037) assigned to @sereshqua[/z](https://www.0crat.com/u/sereshqua), here is [why](https://www.0crat.com/footprint/C63314D6Z/de8111d5-0a16-4d6c-812d-064bdad9ed31); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by llorllale** [comment]
@0crat refuse

**Comment by sereshqua** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1037#issuecomment-475590403))

@sereshqua The user @sereshqua[/z](https://www.0crat.com/u/sereshqua) resigned from [#1037](https://github.com/yegor256/cactoos/issues/1037), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1037#issuecomment-474140169))

@llorllale Job `gh:yegor256/cactoos#1037` is not assigned, can't get performer

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by sereshqua** [comment]
@llorllale My role was previously wrongly assigned, because the TG bot has wrong format `apply` command and I did not I would have to specify role in there, please see:

<img width="422" alt="Screenshot 2019-03-22 at 14 49 59" src="https://user-images.githubusercontent.com/10097808/54824045-73129c80-4cb2-11e9-802b-0826a3ace0e7.png">

Would it be possible to receive points back?

**Comment by llorllale** [comment]
@llorllale sorry, no, can't recover those points. You should have asked me :) `ARC` can `refuse` a task with no penalties to the parties involved.

**Comment by sereshqua** [comment]
@llorllale Kirill @g4s8 told me that it is possible to add points manually, isn't it?

**Comment by llorllale** [comment]
@sereshqua I could, but unfortunately I'll be then [penalized](http://www.zerocracy.com/policy.html#49) myself :)

**Comment by 0crat** [comment]
The job [#1037](https://github.com/yegor256/cactoos/issues/1037) assigned to @umbrah[/z](https://www.0crat.com/u/umbrah), here is [why](https://www.0crat.com/footprint/C63314D6Z/1a57f302-8c75-497c-875c-87c058996644); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `971-205df100` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @umbrah[/z](https://www.0crat.com/u/umbrah), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1037](https://github.com/yegor256/cactoos/issues/1037) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @umbrah[/z](https://www.0crat.com/u/umbrah)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
