### ISSUE TITLE
TextTest.java:37-39: Replace all occurrences of @Rule...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1039]
The puzzle `1023-be859eed` from #1023 has to be resolved: 

https://github.com/yegor256/cactoos/blob/fb6a875013688413374f0c15ebbfe2d0753013b4/src/test/java/org/cactoos/TextTest.java#L37-L39

The puzzle was created by @rultor on 23-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job [#1039](https://github.com/yegor256/cactoos/issues/1039) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1039](https://github.com/yegor256/cactoos/issues/1039) assigned to @sereshqua[/z](https://www.0crat.com/u/sereshqua), here is [why](https://www.0crat.com/footprint/C63314D6Z/42a48e2b-2448-4ddf-8d10-7ede6db7f44e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by llorllale** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1039#issuecomment-474140139))

@llorllale The user @sereshqua[/z](https://www.0crat.com/u/sereshqua) resigned from [#1039](https://github.com/yegor256/cactoos/issues/1039), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#1039](https://github.com/yegor256/cactoos/issues/1039) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/a0b1d9e4-34f8-4fe1-aefd-b493d89de7e6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1039` already assigned to @victornoel, can't assign to @victornoel

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1039#issuecomment-480494870))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#1039](https://github.com/yegor256/cactoos/issues/1039), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
The job [#1039](https://github.com/yegor256/cactoos/issues/1039) assigned to @atapin[/z](https://www.0crat.com/u/atapin), here is [why](https://www.0crat.com/footprint/C63314D6Z/4721a601-85b1-4539-9fba-9255e15c8cd4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `1023-be859eed` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1106](https://github.com/yegor256/cactoos/issues/1106) is still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @atapin[/z](https://www.0crat.com/u/atapin), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1039](https://github.com/yegor256/cactoos/issues/1039) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @atapin[/z](https://www.0crat.com/u/atapin)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#1106](https://github.com/yegor256/cactoos/issues/1106) is solved here.
