### ISSUE TITLE
Disable gitlint in .rultor

### ISSUE THREAD

**Issue by llorllale** [yegor256/cactoos#1041]
Let's disable gitlint in `.rultor.yml`:

* We plan on replacing it anyway due to incompatibility with Windows (see #992)
* [Character decoding issues](https://github.com/yegor256/cactoos/pull/1029#issuecomment-456619522)
* If the gitlint check passes the travis build then the whole process should manage to capture 99% of git log issues (the remaining 1% would lie in the ARC and PO's hands :)

**Comment by llorllale** [comment]
Fixed in 0143b2d619a40df0b4b483ea43a4a9f1cdd6c694

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1041` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
