### ISSUE TITLE
Pull Request Template

### ISSUE THREAD

**Issue by llorllale** [yegor256/cactoos#1043]
Update `PULL_REQUEST_TEMPLATE.md` with all applicable rules from `cactoos-matchers`.

Also, add rule about not using GitHub [keywords](https://help.github.com/articles/closing-issues-using-keywords) in the PR's description.

**Comment by llorllale** [comment]
@llorllale Fixed in b8bf44e4ddbe0b5a9b13e006208327358931c0cd

**Comment by llorllale** [comment]
@borysfan @dgroup @fabriciofx @ilyakharlamov @iprogrammerr @marceloamadeu @scratchboom @verkhovin @victornoel 

I've updated the PR guidelines

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1043` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
