### ISSUE TITLE
Commit log linting not checking all PR commits

### ISSUE THREAD

**Issue by llorllale** [yegor256/cactoos#1045]
This is due to an erroneous assumption: the linter would be run in the feature branch. The problem is that both rultor and travis run scripts after merging the feature and master branches together.

In this context, the `--not master` predicate passed to `git log` does not produce the expected output.

I thought about using git's `--author` filter but neither travis nor rultor expose the PR's author. (Regarding rultor, let's keep in mind that there are sometimes [unicode decoding issues](https://github.com/yegor256/cactoos/pull/1029#issuecomment-456619522), so we'll keep `gitlint` disabled in `rultor` for now).

Since there are many dirty messages in our commit history, we should just lint all commit logs since a last known good revision. I would choose d0b2b05d977b43d705f89f1c286a4262b534c6b4 but `git log d0b2b05d977b43d705f89f1c286a4262b534c6b4..` includes many commits I did not expect and I don't know yet why it does that.

So for now `git log --since="2019-01-21"` produces an output that we can work on, so we'll use that.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1045` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
