### ISSUE TITLE
package-info.java:29-33: Classes from package {@link...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1046]
The puzzle `1006-0071ae30` from #1006 has to be resolved: 

https://github.com/yegor256/cactoos/blob/6b4a6b9a2b0eeb8b7ab7e9c0e7d1e57bfda91784/src/main/java/org/cactoos/time/package-info.java#L29-L33

The puzzle was created by @rultor on 27-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
This puzzle inherited milestone `1.0` from issue #1006.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#1046](https://github.com/yegor256/cactoos/issues/1046) assigned to @atapin[/z](https://www.0crat.com/u/atapin), here is [why](https://www.0crat.com/footprint/C63314D6Z/68bf87a0-543e-4b53-a771-58a6d20b30ab); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The job [#1046](https://github.com/yegor256/cactoos/issues/1046) assigned to @umbrah[/z](https://www.0crat.com/u/umbrah), here is [why](https://www.0crat.com/footprint/C63314D6Z/0020ac8d-d2bb-41a8-8a26-38912dbfa5b1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by Umbrah** [comment]
@0crat wait #1123

**Comment by 0crat** [comment]
> @0crat wait #1123  ([here](https://github.com/yegor256/cactoos/issues/1046#issuecomment-489048346))

@Umbrah The impediment for [#1046](https://github.com/yegor256/cactoos/issues/1046) was registered successfully by @umbrah[/z](https://www.0crat.com/u/umbrah)

**Comment by 0pdd** [comment]
The puzzle `1006-0071ae30` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#1046](https://github.com/yegor256/cactoos/issues/1046) is not in the agenda of @umbrah[/z](https://www.0crat.com/u/umbrah), can't inspect

**Comment by 0crat** [comment]
The job [#1046](https://github.com/yegor256/cactoos/issues/1046) is now out of scope

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @umbrah[/z](https://www.0crat.com/u/umbrah), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @umbrah[/z](https://www.0crat.com/u/umbrah)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
