### ISSUE TITLE
Refactor GzipInput and GzipOutput tests to be more readable

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#1048]
There're a lot of "data bytes" in GzipInput and GzipOutput tests which difficult them to read. Let's refactor them to be more readable.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
The job [#1048](https://github.com/yegor256/cactoos/issues/1048) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/a6475aed-05ad-401f-bf88-ee14c40dfa4b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1048#issuecomment-484923731))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#1048](https://github.com/yegor256/cactoos/issues/1048), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
The job [#1048](https://github.com/yegor256/cactoos/issues/1048) assigned to @umbrah[/z](https://www.0crat.com/u/umbrah), here is [why](https://www.0crat.com/footprint/C63314D6Z/83a1aa9b-e486-4617-ac18-0b44fecdeec7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by Umbrah** [comment]
@fabriciofx Can we close it? PR was merged.

**Comment by Umbrah** [comment]
@0crat wait #1118

**Comment by Umbrah** [comment]
@fabriciofx ping

**Comment by Umbrah** [comment]
@fabriciofx ping

**Comment by llorllale** [comment]
@fabriciofx closed due to unresponsiveness (PR #1118 merged for this)

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @umbrah[/z](https://www.0crat.com/u/umbrah), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1048](https://github.com/yegor256/cactoos/issues/1048) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @umbrah[/z](https://www.0crat.com/u/umbrah)
