### ISSUE TITLE
Concatenated as an alternative to StringBuilder

### ISSUE THREAD

**Issue by Iprogrammerr** [yegor256/cactoos#1051]
Currently, we do not have Text implementation that works like StringBuilder. There is a Joined, but he concatenates strings/texts with a given delimit. I propose to create Concatenated that will work like this:
`new Concatenated(
    "SELECT * FROM A ",
    "WHERE id = 1"
).asString()`
He should accept both Strings and Texts.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by fabriciofx** [comment]
@Iprogrammerr What's the problem with `JoinedText`? It does exactly the same thing.

**Comment by Iprogrammerr** [comment]
@fabriciofx No, it does not. To have concatenated without delimit strings, I have to do
`new Joined("", "a",b","c)` which will result in `"a" + "" + "b" + "" + "c"`. I am suggesting replacement for StringBuilder, so that  `new Concatenated("a", "b", "c")` will result in `"a" + "b" + "c"`.

**Comment by fabriciofx** [comment]
@Iprogrammerr I see now. Thanks!

**Comment by llorllale** [comment]
@Iprogrammerr is this extra class really worth the trouble of not having to specify a delimiter for `org.cactoos.text.Joined`? I'm having trouble believing it.

**Comment by llorllale** [comment]
@Iprogrammerr ping

How about we use the empty string as a default delimiter?

**Comment by kokodyn** [comment]
Hi
I see i has been partly covered in PR #1480. Adding ctor which accepts String vargs in ctor it is what need to be implement.

**Comment by victornoel** [comment]
@Iprogrammerr it seems to be implemented now

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1051` is not assigned, can't get performer
