### ISSUE TITLE
Need to improve unit tests

### ISSUE THREAD

**Issue by dusan-rychnovsky** [yegor256/cactoos#106]
We need to improve unit tests - add missing cases.

**Comment by 0crat** [comment]
@dusan-rychnovsky I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by dusan-rychnovsky** [comment]
I have this ready, will send a PR.

**Comment by dusan-rychnovsky** [comment]
fixed in #107
