### ISSUE TITLE
DefaultOf scalar in case if origin can't be evaluated

### ISSUE THREAD

**Issue by dgroup** [yegor256/cactoos#1060]
```java
new Assertion<>(
    "The default value was returned",
    new DefaultOf(
        () -> {
            throw new IllegalStateException("something went wrong");
        },
        5
    )
   , new IsEqual<>(5)
).affirm();
```
The default shouldn't throw any exception.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@dgroup see if `ScalarWithFallback` is sufficient solution for your use case

**Comment by llorllale** [comment]
@dgroup can we close this?

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1060` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
