### ISSUE TITLE
README: add example of flattening iterables

### ISSUE THREAD

**Issue by llorllale** [yegor256/cactoos#1061]
Let's add an example how to [flatten iterables](https://stackoverflow.com/a/54465910/1623885) to the `README`.

**Comment by llorllale** [comment]
@g4s8 done in dc4dc2304f9e14cb2d324f196983aacf5f24b1ea

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1061` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
