### ISSUE TITLE
Abbreviated.java:34-36: All classes implementing Text...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1063]
The puzzle `897-f060f15b` from #897 has to be resolved: 

https://github.com/yegor256/cactoos/blob/39301459b873ecfb33b51669567cd900fd3ff1c9/src/main/java/org/cactoos/text/Abbreviated.java#L34-L36

The puzzle was created by igor on 02-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1063](https://github.com/yegor256/cactoos/issues/1063) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1063](https://github.com/yegor256/cactoos/issues/1063) assigned to @umbrah[/z](https://www.0crat.com/u/umbrah), here is [why](https://www.0crat.com/footprint/C63314D6Z/6977f446-b0fa-45e4-aeaa-0347c2a07c61); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by Umbrah** [comment]
@0crat waiting #1108

**Comment by 0crat** [comment]
> @0crat waiting #1108  ([here](https://github.com/yegor256/cactoos/issues/1063#issuecomment-485779527))

@Umbrah The impediment for [#1063](https://github.com/yegor256/cactoos/issues/1063) was registered successfully by @umbrah[/z](https://www.0crat.com/u/umbrah)

**Comment by 0pdd** [comment]
The puzzle `897-f060f15b` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1116](https://github.com/yegor256/cactoos/issues/1116) is still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @umbrah[/z](https://www.0crat.com/u/umbrah), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1063](https://github.com/yegor256/cactoos/issues/1063) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @umbrah[/z](https://www.0crat.com/u/umbrah)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1135](https://github.com/yegor256/cactoos/issues/1135) is still not solved; solved: [#1116](https://github.com/yegor256/cactoos/issues/1116).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1135](https://github.com/yegor256/cactoos/issues/1135), [#1261](https://github.com/yegor256/cactoos/issues/1261) are still not solved; solved: [#1116](https://github.com/yegor256/cactoos/issues/1116).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1261](https://github.com/yegor256/cactoos/issues/1261) is still not solved; solved: [#1116](https://github.com/yegor256/cactoos/issues/1116), [#1135](https://github.com/yegor256/cactoos/issues/1135).

**Comment by 0pdd** [comment]
@0pdd all 3 puzzles are solved here: [#1116](https://github.com/yegor256/cactoos/issues/1116), [#1135](https://github.com/yegor256/cactoos/issues/1135), [#1261](https://github.com/yegor256/cactoos/issues/1261).
