### ISSUE TITLE
package-info.java:29-33: Remove Sticky decorators from...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1064]
The puzzle `1005-58ab3a1d` from #1005 has to be resolved: 

https://github.com/yegor256/cactoos/blob/39301459b873ecfb33b51669567cd900fd3ff1c9/src/test/java/org/cactoos/io/package-info.java#L29-L33

The puzzle was created by igor on 25-Jan-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
This puzzle inherited milestone `1.0` from issue #1005.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1064](https://github.com/yegor256/cactoos/issues/1064) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1064](https://github.com/yegor256/cactoos/issues/1064) assigned to @iprogrammerr[/z](https://www.0crat.com/u/iprogrammerr), here is [why](https://www.0crat.com/footprint/C63314D6Z/63c6369b-c7f4-4da1-8554-b9a6748f6a5f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by Iprogrammerr** [comment]
@llorllale To do this need new release of cactoos-matchers and then separate issue to update it as a dependency. How can I register impediment like this?

**Comment by llorllale** [comment]
@Iprogrammerr releasing [cactoos-matchers:0.14](https://github.com/llorllale/cactoos-matchers/pull/71#issuecomment-462047062)

**Comment by Iprogrammerr** [comment]
@0crat wait #1069

**Comment by 0crat** [comment]
> @0crat wait #1069  ([here](https://github.com/yegor256/cactoos/issues/1064#issuecomment-462086702))

@Iprogrammerr The impediment for [#1064](https://github.com/yegor256/cactoos/issues/1064) was registered successfully by @iprogrammerr[/z](https://www.0crat.com/u/iprogrammerr)

**Comment by 0pdd** [comment]
The puzzle `1005-58ab3a1d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#1064](https://github.com/yegor256/cactoos/issues/1064) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @iprogrammerr[/z](https://www.0crat.com/u/iprogrammerr)
