### ISSUE TITLE
Update cactoos-matchers to 0.14

### ISSUE THREAD

**Issue by Iprogrammerr** [yegor256/cactoos#1069]
Let's update cactoos-matchers dependency. Assertion doesn't call a test twice there, so it will be possible to complete #1064.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@Iprogrammerr I think we'd move faster if you just upgrade while completing #1064...

**Comment by Iprogrammerr** [comment]
@llorllale Agreed, we can close this then.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1069` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
