### ISSUE TITLE
CollectionEnvelope#equals is broken

### ISSUE THREAD

**Issue by grzechol** [yegor256/cactoos#1075]
Please see the following code:
```
public static void main(final String[] args) {
    final List<Object> cactoos = new org.cactoos.list.ListOf<>("a", 1.0, 5);
    final List<Object> google = com.google.common.collect.ImmutableList.of("a", 1.0, 5);
    final List<Object> java = Arrays.asList("a", 1.0, 5);
    System.out.format("cactoos equals google ? %b%n", cactoos.equals(google));
    System.out.format("cactoos equals java ? %b%n", cactoos.equals(java));
    System.out.format("google equals cactoos ? %b%n", google.equals(cactoos));
    System.out.format("java equals cactoos ? %b%n", java.equals(cactoos));
    System.out.format("java equals google ? %b%n", java.equals(google));
    System.out.format("google equals java ? %b%n", google.equals(java));
}
```
As you can see, every list contains equal elements, but the code prints:
```
cactoos equals google ? false
cactoos equals java ? false
google equals cactoos ? true
java equals cactoos ? true
java equals google ? true
google equals java ? true
```
Which is not true since all of the lists are equal.

cactoos version 0.39, Google Guava version 27.0.1-jre, OpenJDK 1.8.0_191

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@grzechol[/z](https://www.0crat.com/u/grzechol) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by svendiedrichsen** [comment]
Probably fixed by #1057

**Comment by llorllale** [comment]
@grzechol yeah, this may be a duplicate of #904. Can you confirm?

**Comment by llorllale** [comment]
@grzechol please test with `0.40` and let us know

**Comment by grzechol** [comment]
Thanks @llorllale and @svendiedrichsen, I've checked and it's fixed in 0.40

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1075` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
