### ISSUE TITLE
BytesOf doesn accept ByteBuffer as constructor argument

### ISSUE THREAD

**Issue by g4s8** [yegor256/cactoos#1076]
`BytesOf` class doesn support `java.nio.ByteBuffer` argument, so the user needs to construct `Bytes` via
```java
new BytesOf(buffer.array());
```
I think `BytesOf` can also accept `ByteBuffer` as ctor parameter, because `ByteBuffer` is standard class to store bytes in java.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@g4s8 sure, but I'm not sure it's OK to read the ByteBuffer's whole array (which is an optional operation). The ByteBuffer's position may not equal `0` and its limit may not equal its capacity, so I think it's best to use the relative *get* operations to work within the buffer's position and limit.

**Comment by llorllale** [comment]
@g4s8 ping 

Do you agree?

**Comment by g4s8** [comment]
@llorllale yes, it makes sense

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1076` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by llorllale** [comment]
@g4s8 actually, I was not objecting to the requirement *per se*, just clarifying some implementation details. I think this is a valid request - just wanted to refine it a bit with you.

**Comment by g4s8** [comment]
@llorllale but you're right here - `ByteBuffer` may have non-zero position and `BytesOf` will return inconsistent result e.g. if `value()` will be called after some write operations to buffer, or from another thread. Therefore, `buffer.array()` should be called before `BytesOf` construtor to avoid that situation, because the result of `array()` depends on method execution order.
