### ISSUE TITLE
Merged/Joined - allows to merge/join several java.util.Properties 

### ISSUE THREAD

**Issue by dgroup** [yegor256/cactoos#1084]
When you are working with `java.util.Properties` you may need to merge/join several properties or merge existing `Properties` object with a `Map` or 2x dimension array.
`PropertiesOf` allows you to instantiate a new instance based on different sources like Text, String, etc, but it doesn't provide any `ctor(s)` which allows joining properties.

Potentially we can create a few `ctors` to `PropertiesOf` instead of creating a separate class.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@dgroup maybe we could add a `org.cactoos.map.Merged` that could be reused for properties (because they are `Map<Object,Object>`).

Name would be `Merged` instead of `Joined` because you don't concatenate maps - you merge them (keys may be overwritten).

**Comment by dgroup** [comment]
@llorllale agree, the way with `org.cactoos.map.Merged` is more general and can be reused in other cases.

**Comment by llorllale** [comment]
@dgroup let's start with `org.cactoos.map.Merged` that will merge two or more maps

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/1084#issuecomment-475454233))

@llorllale Job [#1084](https://github.com/yegor256/cactoos/issues/1084) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @dgroup[/z](https://www.0crat.com/u/dgroup)

**Comment by 0crat** [comment]
The job [#1084](https://github.com/yegor256/cactoos/issues/1084) assigned to @umbrah[/z](https://www.0crat.com/u/umbrah), here is [why](https://www.0crat.com/footprint/C63314D6Z/2dead438-e256-455b-b79b-825d3ec1d299); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by Umbrah** [comment]
@dgroup Can we close it? PR was merged.

**Comment by dgroup** [comment]
@Umbrah , thanks

**Comment by 0crat** [comment]
Job [#1084](https://github.com/yegor256/cactoos/issues/1084) is not in the agenda of @umbrah[/z](https://www.0crat.com/u/umbrah), can't inspect

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @umbrah[/z](https://www.0crat.com/u/umbrah), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1084](https://github.com/yegor256/cactoos/issues/1084) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @umbrah[/z](https://www.0crat.com/u/umbrah)
