### ISSUE TITLE
UncheckedScalar.java:36-38: Remove once the dependency...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1086]
The puzzle `1081-f3313fb1` from #1081 has to be resolved: 

https://github.com/yegor256/cactoos/blob/7e57623842b710483cbefc3d59b984c86d712b67/src/main/java/org/cactoos/scalar/UncheckedScalar.java#L36-L38

The puzzle was created by Victor Noël on 13-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1086](https://github.com/yegor256/cactoos/issues/1086) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1086](https://github.com/yegor256/cactoos/issues/1086) assigned to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), here is [why](https://www.0crat.com/footprint/C63314D6Z/561aa7a9-502c-403e-8b80-94f278b44939); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by vzurauskas** [comment]
@0crat refuse - cactoos-matchers isn't ready yet.

**Comment by 0crat** [comment]
> @0crat refuse - cactoos-matchers isn't ready yet. ([here](https://github.com/yegor256/cactoos/issues/1086#issuecomment-485724988))

@vzurauskas The user @vzurauskas[/z](https://www.0crat.com/u/vzurauskas) resigned from [#1086](https://github.com/yegor256/cactoos/issues/1086), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas)

**Comment by 0crat** [comment]
The job [#1086](https://github.com/yegor256/cactoos/issues/1086) assigned to @umbrah[/z](https://www.0crat.com/u/umbrah), here is [why](https://www.0crat.com/footprint/C63314D6Z/d1580d4c-93dc-4909-bb64-7d0120e12c12); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by Umbrah** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1086#issuecomment-486203279))

@Umbrah The user @umbrah[/z](https://www.0crat.com/u/umbrah) resigned from [#1086](https://github.com/yegor256/cactoos/issues/1086), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @umbrah[/z](https://www.0crat.com/u/umbrah)

**Comment by 0crat** [comment]
The job [#1086](https://github.com/yegor256/cactoos/issues/1086) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/2f2f85bc-0d88-4a01-a784-9b7a0f4bb23b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat waiting for llorllale/cactoos-matchers#103

**Comment by 0crat** [comment]
> @0crat waiting for llorllale/cactoos-matchers#103 ([here](https://github.com/yegor256/cactoos/issues/1086#issuecomment-490446277))

@victornoel The impediment for [#1086](https://github.com/yegor256/cactoos/issues/1086) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@0crat wait for #1139 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #1139 to be merged ([here](https://github.com/yegor256/cactoos/issues/1086#issuecomment-500120567))

@victornoel Job [#1086](https://github.com/yegor256/cactoos/issues/1086) is already on hold

**Comment by victornoel** [comment]
@llorllale any way to increase the boost factor here? Because of the nature of the change, the number of modifications was very high and it wasn't possible to avoid it. See #1139 for details.

**Comment by llorllale** [comment]
@0crat boost 4x

**Comment by 0crat** [comment]
> @0crat boost 4x ([here](https://github.com/yegor256/cactoos/issues/1086#issuecomment-500543785))

@llorllale Boost 4x was set for [#1086](https://github.com/yegor256/cactoos/issues/1086)

**Comment by 0crat** [comment]
Boosting tasks is against our principles, see [§15](http://www.zerocracy.com/policy.html#15): -10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
The puzzle `1081-f3313fb1` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1144](https://github.com/yegor256/cactoos/issues/1144) is still not solved.

**Comment by 0crat** [comment]
Job [#1086](https://github.com/yegor256/cactoos/issues/1086) is not in the agenda of @victornoel[/z](https://www.0crat.com/u/victornoel), can't retrieve data and time of add

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#1086](https://github.com/yegor256/cactoos/issues/1086) is not in the agenda of @victornoel[/z](https://www.0crat.com/u/victornoel), can't inspect

**Comment by 0crat** [comment]
The job [#1086](https://github.com/yegor256/cactoos/issues/1086) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +65 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#1144](https://github.com/yegor256/cactoos/issues/1144) is solved here.
