### ISSUE TITLE
RetryTest.java:37-39: add a test to where an interrupt...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1088]
The puzzle `909-fb64001d` from #909 has to be resolved: 

https://github.com/yegor256/cactoos/blob/fc1cbb20b6fea317c4919a8e2b9d46b788685507/src/test/java/org/cactoos/func/RetryTest.java#L37-L39

The puzzle was created by longstone on 21-Mar-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1088](https://github.com/yegor256/cactoos/issues/1088) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1088](https://github.com/yegor256/cactoos/issues/1088) assigned to @umbrah[/z](https://www.0crat.com/u/umbrah), here is [why](https://www.0crat.com/footprint/C63314D6Z/52b725b2-9a3a-48f2-a109-00cab9db542b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by Umbrah** [comment]
@0crat wait #1124

**Comment by 0crat** [comment]
> @0crat wait #1124  ([here](https://github.com/yegor256/cactoos/issues/1088#issuecomment-493900113))

@Umbrah The impediment for [#1088](https://github.com/yegor256/cactoos/issues/1088) was registered successfully by @umbrah[/z](https://www.0crat.com/u/umbrah)

**Comment by 0pdd** [comment]
The puzzle `909-fb64001d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @umbrah[/z](https://www.0crat.com/u/umbrah), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1088](https://github.com/yegor256/cactoos/issues/1088) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @umbrah[/z](https://www.0crat.com/u/umbrah)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
