### ISSUE TITLE
throw checked CactoosException instead of raw java.lang.Exception from Scalar, Func, Proc, Text, etc

### ISSUE THREAD

**Issue by dgroup** [yegor256/cactoos#1089]
It's too verbose to operate with scalars, functions, text, etc when they are throws raw `java.lang.Exception`.

Yes, we do have the `UncheckedXxx` implementations but we can't use them very often due to `ClassDataAbstractionCouplingCheck` which equal to 7 classes.  
For example, we have few instances of `Scalar` and `Text`, so in order to do not throw the raw exception, you need `Scalar`, `UncheckedScalar`, `Text` and `UncheckedText`. These 4 classes are using ~60% of classes quote. 

Why cactoos primitives can't throw the `CactoosException` instead of raw `java.lang.Exception`?

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@dgroup by "throw CactoosException", you mean "throw a runtime (aka non-checked) exception"? If so, this is a duplicate of #944

**Comment by dgroup** [comment]
@llorllale, no, the Cactoos Exception is a checked exception:
```java
public final class CactoosException extends Exception {
    ....
}
``` 
I'm disagree with #944.

**Comment by llorllale** [comment]
@dgroup I don't understand how having a checked `CactoosException` will fix the problem of "class data abstraction coupling increases 4x

**Comment by dgroup** [comment]
@llorllale, the `Scalar`, `Func`, `Proc`, `Text` are throwing the raw `java.lang.Exception`. 
As a result, you have to 
1. handle the Exception 
2. throw again Exception from the current method 
    (and suppress `PMD.AvoidCatchingGenericException`, `// @checkstyle IllegalCatchCheck (3 lines)` violations)

In the first case, we may use unchecked wrappers so we'll need their unchecked implementations.
In accordance with `qulice` we should use only 7 classes (otherwise we'll get `ClassDataAbstractionCouplingCheck` violation). In case if we have `Scalar` and `Text` variables we'll need the `UncheckedScalar`, `UncheckText`, `Scalr`, `Text` just to access to necessary data. For example, `Scalar` may have an object which operates with `String`, thus the code may be like
```java
public void method() throws ExpectedAppException {
  ... // some logic before where ExpectedAppException might be thrown
  final Scalar<3rd.party.library.User> user = ... ;
  final Text id = ...;
  return new UncheckedScalar<>(user).value().hasId(new UncheckedText(id).asString());
}
```
and that's it, we've used 4 classes of 7 classes quote. 
If we'll try to catch the raw `java.lang.Exception` we will have to suppress `PMD.AvoidCatchingGenericException`, `// @checkstyle IllegalCatchCheck (3 lines)` violations, and it increases the verbosity of the code in all cases where `Cactoos` primitives throws the `java.lang.Exception`
```java
@SuppressWarnings("PMD.AvoidCatchingGenericException")
public void method() throws ExpectedAppException {
  ... // some logic before where ExpectedAppException might be thrown
  final Scalar<3rd.party.library.User> user = ... ;
  final Text id = ...;
  try {
    return user.value().hasId(id.asString());
    `// @checkstyle IllegalCatchCheck (3 lines)`
  } catch (final Exception cause) {
    throw new ExpectedAppException(cause);
  }
}
```

In the second case, you don't need to catch raw `java.lang.Exception` (and suppress the PMD/checkstyle violations) due to this case.
```java
public void method() throws ExpectedAppException {
  ...
  try {
    final Scalar<3rd.party.library.User> user = ... ;
    final Text id = ...;
    return user.value().hasId(id.asString());
  } catch (final CactoosException cause) {
    throw new ExpectedAppException(cause);
  }
}

**Comment by llorllale** [comment]
@dgroup ok, gotcha. The problem you describe is that the current APIs tend to force you "sweep problems under the rug" by either suppressing one linting warning or suppressing another.

Throwing `CactoosException` is just tricking the system - it's just a facade for `Exception` that we would come up with for no other reason than not having to suppress warnings. It also lacks any semantic value for the user - it is no different than regular `Exception`.

We should wait for #944. And to be honest - I am leaning in favor of removing checked exceptions.

**Comment by dgroup** [comment]
@llorllale thank you for the clarification.

Perhaps, if we considering to remove the `checked` exception then we might need to throw `unchecked` and it should not be a RuntimeException, maybe `CactoosException`? :)

**Comment by llorllale** [comment]
@dgroup that remains to be determined

Can we close this issue?

**Comment by dgroup** [comment]
@llorllale , yes, thank you.
I'll subscribe on #944 .

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1089` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
