### ISSUE TITLE
Remove iterator constructor from org.cactoos.scalar.ItemAt

### ISSUE THREAD

**Issue by mazdack** [yegor256/cactoos#1094]
Continue removing iterator from constructors.
Started in https://github.com/yegor256/cactoos/issues/911

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@mazdack aren't you leaving a todo in #1059 ?

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1094` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
