### ISSUE TITLE
Keep PRs small

### ISSUE THREAD

**Issue by llorllale** [yegor256/cactoos#1103]
@atapin, @borysfan, @dgroup, @golyalpha, @ilyakharlamov, @llorllale, @longstone, @mazdack, @scratchboom, @umbrah, @verkhovin, @victornoel

Hi guys,

Remember to aim to keep PRs small as it says so right in the [template](https://github.com/yegor256/cactoos/blob/master/.github/PULL_REQUEST_TEMPLATE.md).

This goes for REVs as well: block or reject a PR if it's too big.

Sometimes, and only *sometimes*, we can make exceptions if the change truly requires touching many more files or lines.

Thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1103` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
