### ISSUE TITLE
ItemAt.java:175-178: Remove iterator constructor from...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1104]
The puzzle `911-b9a58d58` from #911 has to be resolved: 

https://github.com/yegor256/cactoos/blob/341af0d58d1845cdc8eb31b5ea9987496ceeea87/src/main/java/org/cactoos/scalar/ItemAt.java#L175-L178

The puzzle was created by @rultor on 13-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
This puzzle inherited milestone `1.0` from issue #911.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1104](https://github.com/yegor256/cactoos/issues/1104) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1104](https://github.com/yegor256/cactoos/issues/1104) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/c27ba756-b16e-482b-b00f-14f00926de94); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `911-b9a58d58` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#1104](https://github.com/yegor256/cactoos/issues/1104) is not in the agenda of @victornoel[/z](https://www.0crat.com/u/victornoel), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job [#1104](https://github.com/yegor256/cactoos/issues/1104) is not in the agenda of @victornoel[/z](https://www.0crat.com/u/victornoel), can't inspect

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1104](https://github.com/yegor256/cactoos/issues/1104) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
