### ISSUE TITLE
Iterable of Optional has usability issues

### ISSUE THREAD

**Issue by korthout** [yegor256/cactoos#1105]
Sometimes we map some Iterable where the mapping method may or may not provide an answer. In java represented by return type `java.util.Optional`. Such a mapping requires both a filter and a map function on top of the original map to get back to an Iterable of the mapped objects for which an answer was available. For example:

```java
new Mapped<>(
    Optional::get,
    new Filtered<>(
        Optional::isPresent,
        new Mapped<>(
            Optional::of, 
            new IterableOf("a", null, "b")
        )
    )
); // results in: Iterable("a", "b")
```
Using streams, we have a shorthand method available on Optional called `stream`:
```java
Stream.of("a", null, "b")
    .map(Optional::of)
    .flatMap(Optional::stream);
```
In #1055, `Joined` was noted as the flatMap equivalent for Iterables in cactoos, making the case there is no need for a Flatted or FlatMapped. However, such pre-composed objects make life easier. Perhaps FlatMapped should be reconsidered or Cactoos needs to provide its own Optional that works better with Mapped, Filtered and Joined.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@korthout[/z](https://www.0crat.com/u/korthout) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@korthout I am confused - you mention `Optional` yet your example implies you want an `Iterable`. Your example is not about flattening - it's about filtering. Thus your example can be short-circuited with `new Filtered<>(e -> e != null, "a", null, "b")`.

There are several options available in cactoos for taking action when this iterable is empty, or has N elements.

Maybe if you can explain more...

**Comment by llorllale** [comment]
@korthout ping

**Comment by korthout** [comment]
@llorllale Sorry for taking so long to reply, but you are absolutely right. I was trying to use the Optional type to achieve this, but simply checking for null is enough if null values need to be filtered out. Thank you for the clear example. It makes sense. I think I can close the issue.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1105` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
