### ISSUE TITLE
NoNullsTest.java:79-82: Currently it's impossible to...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1106]
The puzzle `1039-dc7f8b11` from #1039 has to be resolved: 

https://github.com/yegor256/cactoos/blob/55c2421e9e8b99c2f912f0838d36dc65ef629fe5/src/test/java/org/cactoos/iterator/NoNullsTest.java#L79-L82

The puzzle was created by Andrey Atapin on 15-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1106](https://github.com/yegor256/cactoos/issues/1106) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1106](https://github.com/yegor256/cactoos/issues/1106) assigned to @umbrah[/z](https://www.0crat.com/u/umbrah), here is [why](https://www.0crat.com/footprint/C63314D6Z/2564eca4-91a6-4260-9ebd-6e1988580246); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by Umbrah** [comment]
@0crat refuse

**Comment by Umbrah** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1106#issuecomment-493781164))

@Umbrah The user @umbrah[/z](https://www.0crat.com/u/umbrah) resigned from [#1106](https://github.com/yegor256/cactoos/issues/1106), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1106#issuecomment-493791032))

@Umbrah Job `gh:yegor256/cactoos#1106` is not assigned, can't get performer

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @umbrah[/z](https://www.0crat.com/u/umbrah)

**Comment by 0crat** [comment]
The job [#1106](https://github.com/yegor256/cactoos/issues/1106) assigned to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), here is [why](https://www.0crat.com/footprint/C63314D6Z/e8ff997a-b785-460f-86a2-4a266fa7f067); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by vzurauskas** [comment]
@0crat Wait for https://github.com/llorllale/cactoos-matchers/issues/108 to be released.

**Comment by 0crat** [comment]
> @0crat Wait for https://github.com/llorllale/cactoos-matchers/issues/108 to be released. ([here](https://github.com/yegor256/cactoos/issues/1106#issuecomment-497951202))

@vzurauskas The impediment for [#1106](https://github.com/yegor256/cactoos/issues/1106) was registered successfully by @vzurauskas[/z](https://www.0crat.com/u/vzurauskas)

**Comment by 0crat** [comment]
The job [#1106](https://github.com/yegor256/cactoos/issues/1106) assigned to @iakunin[/z](https://www.0crat.com/u/iakunin), here is [why](https://www.0crat.com/footprint/C63314D6Z/fa28290b-fbae-4295-91c6-13e8e683088a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by iakunin** [comment]
@0crat waiting for review https://github.com/yegor256/cactoos/pull/1187

**Comment by 0crat** [comment]
> @0crat waiting for review https://github.com/yegor256/cactoos/pull/1187 ([here](https://github.com/yegor256/cactoos/issues/1106#issuecomment-531722577))

@iakunin The impediment for [#1106](https://github.com/yegor256/cactoos/issues/1106) was registered successfully by @iakunin[/z](https://www.0crat.com/u/iakunin)

**Comment by 0pdd** [comment]
The puzzle `1039-dc7f8b11` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @iakunin[/z](https://www.0crat.com/u/iakunin), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1106](https://github.com/yegor256/cactoos/issues/1106) is now out of scope

**Comment by WhimsySoftware** [comment]
@0crat quality good

**Comment by 0crat** [comment]
You must be invited in order to do that, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @iakunin[/z](https://www.0crat.com/u/iakunin)
