### ISSUE TITLE
CollectionEnvelope.java:42-44: Make the toString() method...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1109]
The puzzle `996-e264dc0b` from #996 has to be resolved: 

https://github.com/yegor256/cactoos/blob/f71ae47a514670e67ae3c8d9696f4f5070a97955/src/main/java/org/cactoos/collection/CollectionEnvelope.java#L42-L44

The puzzle was created by Victor Noël on 06-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1109](https://github.com/yegor256/cactoos/issues/1109) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1109](https://github.com/yegor256/cactoos/issues/1109) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/18544ec5-ee59-4e83-a203-4109d226f5ee); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #1130 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #1130 to be merged ([here](https://github.com/yegor256/cactoos/issues/1109#issuecomment-495922311))

@victornoel The impediment for [#1109](https://github.com/yegor256/cactoos/issues/1109) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@0crat wait for #1136 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #1136 to be merged ([here](https://github.com/yegor256/cactoos/issues/1109#issuecomment-499160035))

@victornoel Job [#1109](https://github.com/yegor256/cactoos/issues/1109) is already on hold

**Comment by 0pdd** [comment]
The puzzle `996-e264dc0b` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job [#1109](https://github.com/yegor256/cactoos/issues/1109) is not in the agenda of @victornoel[/z](https://www.0crat.com/u/victornoel), can't inspect

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1109](https://github.com/yegor256/cactoos/issues/1109) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
