### ISSUE TITLE
Unit tests are too slow

### ISSUE THREAD

**Issue by vzurauskas** [yegor256/cactoos#1112]
For [TDD](https://blog.cleancoder.com/uncle-bob/2014/12/17/TheCyclesOfTDD.html) to be possible, the whole unit test suite [must not take longer than 10 seconds to run](https://blog.ploeh.dk/2012/05/24/TDDtestsuitesshouldrunin10secondsorless/), from click to finish. TDD works by constantly switching from unit test to production code and back again, often several times per minute. That means tests need to be run several times per minute. That means tests have to be fast.

There are a few tests that take seconds, even tens of seconds to run, i.e. `ThreadsTest`. Perhaps they could be refactored to take no more than a few hundred milliseconds? Or maybe they could be run in the integration test phase instead?

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@vzurauskas it's worth noting that running the tests with `mvn test` involves a lot more than just execution of the test suite

**Comment by llorllale** [comment]
@0crat assign me

**Comment by llorllale** [comment]
@vzurauskas given what I said [here](https://github.com/yegor256/cactoos/issues/1112#issuecomment-485607497), it might not be possible to have `mvn test` execute in less than ten seconds on your average laptop. 

However, the current situation is definitely not acceptable, so we'll do our best to fix it.

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/cactoos/issues/1112#issuecomment-485607515))

@llorllale The job [#1112](https://github.com/yegor256/cactoos/issues/1112) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C63314D6Z/59a7d260-0bd8-4876-92a6-addfea96ac9c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @llorllale[/z](https://www.0crat.com/u/llorllale) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas)

**Comment by llorllale** [comment]
@0crat wait I submitted PR #1113 for this

**Comment by 0crat** [comment]
> @0crat wait I submitted PR #1113 for this ([here](https://github.com/yegor256/cactoos/issues/1112#issuecomment-485611071))

@llorllale The impediment for [#1112](https://github.com/yegor256/cactoos/issues/1112) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
@vzurauskas the puzzle [#1115](https://github.com/yegor256/cactoos/issues/1115) is still not solved.

**Comment by llorllale** [comment]
@vzurauskas work to speed up `mvn test` started in PR #1113 (which was merged). Can we close this?

**Comment by llorllale** [comment]
@vzurauskas ping

**Comment by vzurauskas** [comment]
@llorllale Oh right, sorry. :) Closing.

**Comment by 0crat** [comment]
The job [#1112](https://github.com/yegor256/cactoos/issues/1112) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
@vzurauskas the puzzle [#1141](https://github.com/yegor256/cactoos/issues/1141) is still not solved; solved: [#1115](https://github.com/yegor256/cactoos/issues/1115).

**Comment by 0pdd** [comment]
@vzurauskas all 2 puzzles are solved here: [#1115](https://github.com/yegor256/cactoos/issues/1115), [#1141](https://github.com/yegor256/cactoos/issues/1141).
