### ISSUE TITLE
FormattedText.java:39-42: All classes implementing Text...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1116]
The puzzle `1063-eb6fd66d` from #1063 has to be resolved: 

https://github.com/yegor256/cactoos/blob/d70339deda0a06d64ca732b7eadb85e3ad7e7be5/src/main/java/org/cactoos/text/FormattedText.java#L39-L42

The puzzle was created by @rultor on 23-Apr-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1116](https://github.com/yegor256/cactoos/issues/1116) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1116](https://github.com/yegor256/cactoos/issues/1116) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/d49506ca-b6bd-4ab9-9b12-6b6af6ca7e67); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #1131 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #1131 to be merged ([here](https://github.com/yegor256/cactoos/issues/1116#issuecomment-495923844))

@victornoel The impediment for [#1116](https://github.com/yegor256/cactoos/issues/1116) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0pdd** [comment]
The puzzle `1063-eb6fd66d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1135](https://github.com/yegor256/cactoos/issues/1135) is still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1116](https://github.com/yegor256/cactoos/issues/1116) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1135](https://github.com/yegor256/cactoos/issues/1135), [#1261](https://github.com/yegor256/cactoos/issues/1261) are still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1261](https://github.com/yegor256/cactoos/issues/1261) is still not solved; solved: [#1135](https://github.com/yegor256/cactoos/issues/1135).

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#1135](https://github.com/yegor256/cactoos/issues/1135), [#1261](https://github.com/yegor256/cactoos/issues/1261).
