### ISSUE TITLE
FirstOf rename to ItemOfIterable

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#112]
Let's modify `FirstOf`:

  * rename it to `ItemOfIterable`
  * created `ItemOfIterator`
  * let it find any element, but the position provided (not only the first one)

Similar to [Iterables.get()](https://google.github.io/guava/releases/21.0/api/docs/com/google/common/collect/Iterables.html#get-java.lang.Iterable-int-T-)

**Comment by smallcreep** [comment]
done in #156
@yegor256 close issue, please.

**Comment by yegor256** [comment]
@smallcreep thanks!
