### ISSUE TITLE
Getting a new list that has different type of the list

### ISSUE THREAD

**Issue by portlek** [yegor256/cactoos#1120]
https://hastebin.com/vebemesifa.java
How can I convert this code as i can you in with cactoos?

Also I need to make this:
https://hastebin.com/layewocetu.php

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@utsukushihito[/z](https://www.0crat.com/u/utsukushihito) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1120` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
