### ISSUE TITLE
Inconsistent 'toString' overriding in 'Text' implementations

### ISSUE THREAD

**Issue by vzurauskas** [yegor256/cactoos#1121]
Some `Text` implementations like `TextOf` override `toString()`, while others, like `JoinedText`, don't. This behaviour is confusing, as sometimes invoking `toString` on a `Text` instance gives you a nice text representation, and sometimes you get the default one from `Object`. We should make it consistent.

I would prefer it if all of them overrode `toString`, because getting an actual text representation is what I would expect from a `toString` invoked on a `Text` instance. Also, it would be more convenient than `asString` because I wouldn't need to wrap it in `UncheckedText`. However, keep in mind that debugging becomes more difficult in case there are bugs in the `Text` implementations themselves, because the debuggers will usually invoke `toString` on watched objects to display their value on breakpoints. So I guess this is for ARC to decide, @llorllale

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@vzurauskas we have an open puzzle for this - see #1116

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1121` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
