### ISSUE TITLE
Ordered - the java.uti.Set which supports the ordering

### ISSUE THREAD

**Issue by dgroup** [yegor256/cactoos#1126]
Now the `org.cactoos.set` package contains only SetOf, SetEnvelope.
Let's add a new object - ordered set.
```java
final Set<String> ordered = new Ordered<>("one", "two", "three");
```

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by svendiedrichsen** [comment]
@dgroup Maybe implement java.util.SortedSet instead of only ja.util.Set?

**Comment by llorllale** [comment]
@dgroup 

```java
    new Sorted<>(new SetOf<>(/* elemengs */))
```

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1126` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
