### ISSUE TITLE
Warning in qulice:check - Exception applying rule UseStringIsEmptyRule ...

### ISSUE THREAD

**Issue by zCRUSADERz** [yegor256/cactoos#1127]
`mvn -Pqulice qulice:check` return:
`WARNING: Exception applying rule UseStringIsEmptyRule on file/home/aleksandr/projects/cactoos/src/test/java/org/cactoos/text/RandomizedTest.java, continuing with next rule java.lang.NullPointerException`
In qulice 0.18.18 this [issue](https://github.com/teamed/qulice/issues/1033) is fixed. 
Let's update the quliсe version?

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@zcrusaderz[/z](https://www.0crat.com/u/zcrusaderz) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@zCRUSADERz I'm delaying the qulice upgrade (see #946). I'm also not too concerned about this rule.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1127` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
