### ISSUE TITLE
Add new ctor to PropertiesOf(final MapEntry<?, ?>... entries)

### ISSUE THREAD

**Issue by dgroup** [yegor256/cactoos#1129]
New ctor `org.cactoos.scalar.PropertiesOf` is required which supports the `org.cactoos.map.MapEntry`:
```java
    /**
     * Ctor.
     * @param entries The map with properties
     */
    public PropertiesOf(final MapEntry<?, ?>... entries) {
        this(new IterableOf<>(entries));
    }
```

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@dgroup this ctor already accepts map entries:

https://github.com/yegor256/cactoos/blob/0740f67753c0018894f98df2e39d9137520a4047/src/main/java/org/cactoos/scalar/PropertiesOf.java#L91

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1129` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
