### ISSUE TITLE
Representation data bug in the SlowInputStream's read() method

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#1132]
In the file `SlowInputStream` (used in tests) there is a representation byte data bug in the method `read()`, here:
```
if (this.read(buf) < 0) {
    result = -1;
} else {
    result = buf[0];  // The bug goes here
}
```
The solution is use the `Byte.toUnsignedInt()` method on `buf[0]` or mask the value with `0xff` value.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@fabriciofx can you provide a test case?

**Comment by victornoel** [comment]
@fabriciofx yes, please provide a test case or more explanation, I'm not clear what is the problem exactly :)

**Comment by fabriciofx** [comment]
@victornoel `byte` in Java is signed, but if you're reading a unsigned value, you will got problems. See this [example](https://stackoverflow.com/a/9581563/3342479) to get more details:

*If you were thinking of the byte as unsigned (156) rather than signed (-100), as of Java 8 there's Byte.toUnsignedInt:*
```
byte b2 = -100; // Or `= (byte)156;`
int = Byte.toUnsignedInt(b2);
System.out.println(i2); // 156

```

**Comment by victornoel** [comment]
@fabriciofx thank you, so I think most of the work here is to produce a negative test that show the bug and then to fix it I think

**Comment by victornoel** [comment]
@0crat in

**Comment by victornoel** [comment]
@0crat in

**Comment by victornoel** [comment]
@fabriciofx can we close this now?

**Comment by fabriciofx** [comment]
@victornoel yep!

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @andreoss[/z](https://www.0crat.com/u/andreoss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/cactoos/issues/1132#issuecomment-700531881))

@sereshqua There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@4a7cee4c-9ee4-407c-adfe-acdeb04f607d, thread: PQ-C63314D6Z
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1359] com.amazonaws.ResetException: Failed to reset the request input stream;  If the request involves an input stream, the maximum stream buffer size can be configured via request.getRequestClientOptions().setReadLimit(int)
java.io.BufferedInputStream[170] java.io.IOException: Stream closed
```

[0.54.5](https://github.com/zerocracy/farm): CID: [190f2a34-bf35-4bc1-9c3d-2396bb91da56](https://www.0crat.com/footprint/C63314D6Z/190f2a34-bf35-4bc1-9c3d-2396bb91da56), Type: "Award points were added"
