### ISSUE TITLE
MaxOf doesn't work with negative numbers

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#1133]
`MaxOf` uses the values `Float.MIN_VALUE` and `Double.MIN_VALUE` to represent the minor possible value, but they don't represent because negative part is forgotten. See [here](https://stackoverflow.com/questions/3884793/why-is-double-min-value-in-not-negative) to see more details.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@fabriciofx can you provide a test case? I don't understand where exactly is the issue...

**Comment by fabriciofx** [comment]
@llorllale If a make this test:
```
        MatcherAssert.assertThat(
            new MaxOf(
                new ListOf<>(-1.0d, -2.0d, -3.0d, -4.0d).toArray(new Double[4])
            ).doubleValue(),
            Matchers.equalTo(-1.0d)
        );
```
The result will be:
```
java.lang.AssertionError: 
Expected: <-1.0>
     but: was <4.9E-324>
Expected :<-1.0>
Actual   :<4.9E-324>
```
The same bug is valid do `MaxOf` and `MinOf`.

**Comment by fabriciofx** [comment]
@llorllale Is it possible to assign this issue to me?

**Comment by fabriciofx** [comment]
@llorllale ping

**Comment by llorllale** [comment]
@0crat assign @fabriciofx

**Comment by 0crat** [comment]
> @0crat assign @fabriciofx  ([here](https://github.com/yegor256/cactoos/issues/1133#issuecomment-506980838))

@llorllale The job [#1133](https://github.com/yegor256/cactoos/issues/1133) assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C63314D6Z/579f3ddd-ea41-40d7-9468-b3e106fb54e0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by fabriciofx** [comment]
@0crat wait for `REV`.

**Comment by 0crat** [comment]
> @0crat wait for `REV`. ([here](https://github.com/yegor256/cactoos/issues/1133#issuecomment-508919525))

@fabriciofx The impediment for [#1133](https://github.com/yegor256/cactoos/issues/1133) was registered successfully by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
> @0crat wait for `REV`. ([here](https://github.com/yegor256/cactoos/issues/1133#issuecomment-508919525))

@fabriciofx Job [#1133](https://github.com/yegor256/cactoos/issues/1133) is not in the agenda of @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), can't set impediment

**Comment by fabriciofx** [comment]
@llorllale zerocrat bot removed this task from my agenda. Do you know why?

**Comment by llorllale** [comment]
@fabriciofx nope

**Comment by llorllale** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1133#issuecomment-512066498))

@llorllale This is what I know about this job in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1133](https://github.com/yegor256/cactoos/issues/1133) is [in scope](http://www.zerocracy.com/policy.html#14) for 17days
  * The role is `DEV`
  * The job is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) for [17days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @fabriciofx[/z](https://www.0crat.com/u/fabriciofx): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231133%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by fabriciofx** [comment]
@llorllale Thanks. As the code was merge, I'll close this PR now.

**Comment by 0crat** [comment]
Job [#1133](https://github.com/yegor256/cactoos/issues/1133) is not in the agenda of @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), can't retrieve data and time of add

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#1133](https://github.com/yegor256/cactoos/issues/1133) is not in the agenda of @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), can't inspect

**Comment by 0crat** [comment]
The job [#1133](https://github.com/yegor256/cactoos/issues/1133) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
