### ISSUE TITLE
Randomized.java:40-43: All classes implementing Text need...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1135]
The puzzle `1116-eb6fd66d` from #1116 has to be resolved: 

https://github.com/yegor256/cactoos/blob/4a301a9d19b0de45749c112a982aec2ece880fb3/src/main/java/org/cactoos/text/Randomized.java#L40-L43

The puzzle was created by Victor Noël on 25-May-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1135](https://github.com/yegor256/cactoos/issues/1135) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1135](https://github.com/yegor256/cactoos/issues/1135) assigned to @longstone[/z](https://www.0crat.com/u/longstone), here is [why](https://www.0crat.com/footprint/C63314D6Z/c4239e5c-5ea5-445f-b2b8-1ec9cd6fcf1d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The architect of the project has changed; @llorllale[/z](https://www.0crat.com/u/llorllale) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by 0crat** [comment]
The architect of the project has changed; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is not at this role anymore; @victornoel[/z](https://www.0crat.com/u/victornoel) is the architect now

**Comment by victornoel** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#1135](https://github.com/yegor256/cactoos/issues/1135) assigned to @englishman[/z](https://www.0crat.com/u/englishman), here is [why](https://www.0crat.com/footprint/C63314D6Z/b1c487eb-3ab8-4531-9f66-cfe9233b5b24); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1135#issuecomment-658881844))

@victornoel The user @englishman[/z](https://www.0crat.com/u/englishman) resigned from [#1135](https://github.com/yegor256/cactoos/issues/1135), please stop working. Reason for job resignation: Order was cancelled

**Comment by marceloamadeu** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1135#issuecomment-665030035))

@marceloamadeu The user @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) resigned from [#1135](https://github.com/yegor256/cactoos/issues/1135), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#1135](https://github.com/yegor256/cactoos/issues/1135) assigned to @mazdack[/z](https://www.0crat.com/u/mazdack), here is [why](https://www.0crat.com/footprint/C63314D6Z/0be503c7-7131-468a-936d-88233a5e99a6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `1116-eb6fd66d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 7 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @mazdack[/z](https://www.0crat.com/u/mazdack), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by victornoel** [comment]
@sereshqua not very important but actually it wasn't @mazdack who did the work :)

**Comment by sereshqua** [comment]
@victornoel hmmm true, I've just realised that't my mistake. I had to treat @mazdack as performer, and as performer he did not provide any solution to the job. Sorry about this

at least I can write comment in issues and in PRs in your project :)
