### ISSUE TITLE
Maven dependency problem, artifact not found.

### ISSUE THREAD

**Issue by utsukushihito** [yegor256/cactoos#1140]
```
<dependencies>
    <dependency>
        <groupId>org.cactoos</groupId>
        <artifactId>cactoos</artifactId>
        <version>0.41</version>
    </dependency>
</dependencies>
```
It can't find the artifact of cactoos.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@utsukushihito[/z](https://www.0crat.com/u/utsukushihito) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1140` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
