### ISSUE TITLE
Let's use go-gitlint instead of gitlint (python)

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#1142]
Gitlint addrees two problems:

1. It doesn't work with Windows
2. Needs python to run

Because of them, I've developed a tool called [glint](https://github.com/fabriciofx/glint). It runs in all OS (in Windows it will require git-bash) and doesn't require python or other development environment, just bash.

So, I propose use glint instead of gitlint. WDYT?

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@fabriciofx[/z](https://www.0crat.com/u/fabriciofx) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@fabriciofx does it run on windows?

You know, I made [this](https://github.com/llorllale/go-gitlint) a few months ago but never bothered to hook it into our CI. It can be ran on windows, linux, and mac.

**Comment by fabriciofx** [comment]
@llorllale I'm sorry, I didn't know you've made a tool too. So, I'll change this issue title to use your go-gitlint. WDYT?

**Comment by llorllale** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/cactoos/issues/1142#issuecomment-503351028))

@llorllale The job [#1142](https://github.com/yegor256/cactoos/issues/1142) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C63314D6Z/ba81f72c-8d71-4859-9bb1-00347822525c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @llorllale[/z](https://www.0crat.com/u/llorllale) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by llorllale** [comment]
@fabriciofx done in e787511b7bc4a8904c86815bb0281cd6395524fa

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#1142](https://github.com/yegor256/cactoos/issues/1142) is now out of scope
