### ISSUE TITLE
OutputOf(File) fails on mkdirs on relative file without parent directories (in relative path)

### ISSUE THREAD

**Issue by cocsackie** [yegor256/cactoos#1143]
# Minimal code to reproduce:
`new OutputTo(new File("a.txt")).stream();`
## Unexpected behaviour
> Exception in thread "main" java.lang.NullPointerException
> 	at org.cactoos.io.OutputTo.lambda$new$0(OutputTo.java:67)
> 	at org.cactoos.io.OutputTo.stream(OutputTo.java:187)
> 	at test.Cactoos.main(Cactoos.java:19)
> 
## Expected behaviour
Should work in the same way as when:
- file is `new File("a.txt").getAbsoluteFile()`
- file is `new File("a.txt").getCanonicalFile()`
# Remarks:

Relative files work:

`new OutputTo(new File("test/a.txt")).stream();`

The problem is in(notice no null check on File.getParentFile()):

```java
if (mkdirs) {
	file.getParentFile().mkdirs();
}
```

When the path is relative and it's just a name of a file, File.getParentFile() returns null.
It seems that it could be changed to (since passing `new File("a.txt").getAbsoluteFile()` works):

```java
if (mkdirs) {
	file.getAbsoluteFile().getParentFile().mkdirs();
}
```
It seems that `File.getAbsoluteFile()` is preferred to `File.getCanonicalFile()` due to `File.getCanonicalFile()` throwing `IOException`.

I didn't test this on Linux/MacOS and this might be system dependent.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@cocsackie[/z](https://www.0crat.com/u/cocsackie) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/1143#issuecomment-503350075))

@llorllale Job [#1143](https://github.com/yegor256/cactoos/issues/1143) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/1143#issuecomment-503350075))

@llorllale Thanks for your contribution, @cocsackie[/z](https://www.0crat.com/u/cocsackie)! If you would be a member of [the project](https://www.0crat.com/p/C63314D6Z), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
The job [#1143](https://github.com/yegor256/cactoos/issues/1143) assigned to @scristalli[/z](https://www.0crat.com/u/scristalli), here is [why](https://www.0crat.com/footprint/C63314D6Z/d5347fd7-5627-4a5d-ba4d-c6ebed3fe66d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by scristalli** [comment]
@0crat waiting for review of PR #1155.

**Comment by 0crat** [comment]
> @0crat waiting for review of PR #1155. ([here](https://github.com/yegor256/cactoos/issues/1143#issuecomment-507290458))

@scristalli The impediment for [#1143](https://github.com/yegor256/cactoos/issues/1143) was registered successfully by @scristalli[/z](https://www.0crat.com/u/scristalli)

**Comment by scristalli** [comment]
@cocsackie PR #1155 has been merged; could you please confirm that the issue is solved, and in case close it afterwards? Thank you.

**Comment by scristalli** [comment]
@llorllale the reporter of the issue is not responding, and is not a member of Zerocracy. Could you close the issue?

**Comment by cocsackie** [comment]
@scristalli Sorry. I confirm that issue is solved.

**Comment by 0crat** [comment]
Job [#1143](https://github.com/yegor256/cactoos/issues/1143) is not in the agenda of @scristalli[/z](https://www.0crat.com/u/scristalli), can't inspect

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @scristalli[/z](https://www.0crat.com/u/scristalli), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1143](https://github.com/yegor256/cactoos/issues/1143) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @scristalli[/z](https://www.0crat.com/u/scristalli)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
