### ISSUE TITLE
TeeInputHasResult.java:42-44: Replace the usage of the...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1144]
The puzzle `1086-77b05812` from #1086 has to be resolved: 

https://github.com/yegor256/cactoos/blob/fe264a47b70d371efe89f40708735e852acded0b/src/test/java/org/cactoos/io/TeeInputHasResult.java#L42-L44

The puzzle was created by Victor Noël on 08-Jun-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1144](https://github.com/yegor256/cactoos/issues/1144) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1144](https://github.com/yegor256/cactoos/issues/1144) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/0ed7b130-9acc-4b48-b223-39ec9256ad8d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1144#issuecomment-507024029))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#1144](https://github.com/yegor256/cactoos/issues/1144), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
The job [#1144](https://github.com/yegor256/cactoos/issues/1144) assigned to @aivinog1[/z](https://www.0crat.com/u/aivinog1), here is [why](https://www.0crat.com/footprint/C63314D6Z/e854fdfe-0d24-4987-a1cf-a5dd64049d8b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by aivinog1** [comment]
@0crat wait #1157

**Comment by 0crat** [comment]
> @0crat wait #1157 ([here](https://github.com/yegor256/cactoos/issues/1144#issuecomment-508892538))

@aivinog1 The impediment for [#1144](https://github.com/yegor256/cactoos/issues/1144) was registered successfully by @aivinog1[/z](https://www.0crat.com/u/aivinog1)

**Comment by 0crat** [comment]
The job [#1144](https://github.com/yegor256/cactoos/issues/1144) assigned to @umbrah[/z](https://www.0crat.com/u/umbrah), here is [why](https://www.0crat.com/footprint/C63314D6Z/80f10e78-6a4b-4fd1-838b-79929702fb9a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The architect of the project has changed; @llorllale[/z](https://www.0crat.com/u/llorllale) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by 0pdd** [comment]
The puzzle `1086-77b05812` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) all `QA`s are on vacation. Please handle that.

**Comment by 0crat** [comment]
The job [#1144](https://github.com/yegor256/cactoos/issues/1144) is now out of scope
