### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by aivinog1** [yegor256/cactoos#1148]
See this: https://travis-ci.org/yegor256/cactoos/builds/549901512?utm_source=github_status&utm_medium=notification

Build is broken because @yegor256 commits: 3410ff4f5bba1abd5a6b96f5d96055c8a26641a7 and b3b86009507790e4bb6e7c612a6eb5cbdf63042b. 

Needs to fix build.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@aivinog1 fixed in a1de4e68222cc1fe521c7a328236006b50498b71

@yegor256 has been notified

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1148` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by aivinog1** [comment]
@llorllale was this a valid bug? Can I get my reputation points for reporting a valid bug?

**Comment by llorllale** [comment]
@aivinog1 remind me on the next issue you work on

**Comment by yegor256** [comment]
@llorllale my bad, sorry
