### ISSUE TITLE
Let's fix build errors according to qulice.

### ISSUE THREAD

**Issue by aivinog1** [yegor256/cactoos#1151]
Now we have errors in build connected to qulice:
```
WARNING: Exception applying rule UseStringIsEmptyRule on file /home/travis/build/yegor256/cactoos/src/test/java/org/cactoos/io/LSInputOfTest.java, continuing with next rule
java.lang.NullPointerException
	at com.qulice.pmd.rules.UseStringIsEmptyRule.visit(UseStringIsEmptyRule.java:101)
```

See this: https://travis-ci.org/yegor256/cactoos/builds/550654280?utm_source=github_status&utm_medium=notification

I found that a solution may be to upgrade a qulice to newer version. I found out that in this ticket: https://github.com/teamed/qulice/issues/1033

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@aivinog1 *sigh* - I didn't want to upgrade qulice since that will bring with it a whole bunch of linting errors, but we probably should for other reasons (such as upgrading Java version)

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/1151#issuecomment-506985694))

@llorllale Job [#1151](https://github.com/yegor256/cactoos/issues/1151) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @aivinog1[/z](https://www.0crat.com/u/aivinog1)

**Comment by 0crat** [comment]
The job [#1151](https://github.com/yegor256/cactoos/issues/1151) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/87518825-d42b-4704-8e55-43786fa3c22a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1151#issuecomment-513476555))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#1151](https://github.com/yegor256/cactoos/issues/1151), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
The job [#1151](https://github.com/yegor256/cactoos/issues/1151) assigned to @umbrah[/z](https://www.0crat.com/u/umbrah), here is [why](https://www.0crat.com/footprint/C63314D6Z/2b7e99c4-1523-4919-8972-261dcbd6bd64); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The architect of the project has changed; @llorllale[/z](https://www.0crat.com/u/llorllale) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by paulodamaso** [comment]
@0crat assign @fabriciofx

**Comment by 0crat** [comment]
> @0crat assign @fabriciofx  ([here](https://github.com/yegor256/cactoos/issues/1151#issuecomment-537759749))

@paulodamaso The job [#1151](https://github.com/yegor256/cactoos/issues/1151) assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C63314D6Z/585ecbd3-a9d9-4bb7-9267-4cc66bbfecc8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
> @0crat assign @fabriciofx  ([here](https://github.com/yegor256/cactoos/issues/1151#issuecomment-537759749))

@paulodamaso There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@7e4557ac-9cb4-4759-bed3-946dd09657ea, thread: pool-5-thread-8
com.zerocracy.claims.ClaimIn[198] java.lang.IllegalArgumentException: Parameter "age" not found in "Order was canceled" among: [comment, job, issue, repo, cause, _parent_sig, flow, login]
```

[0.49.14](https://github.com/zerocracy/farm): CID: [d0e1539e-394d-4129-876c-bd97622de0c5](https://www.0crat.com/footprint/C63314D6Z/d0e1539e-394d-4129-876c-bd97622de0c5), Type: "Order was canceled"

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by fabriciofx** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1151#issuecomment-537763807))

@fabriciofx This is what I know about this job in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1151](https://github.com/yegor256/cactoos/issues/1151) is [in scope](http://www.zerocracy.com/policy.html#14) for 3mon
  * The role is `DEV`
  * The job is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) for [23min](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @aivinog1[/z](https://www.0crat.com/u/aivinog1): This user reported the ticket
    * @victornoel[/z](https://www.0crat.com/u/victornoel): User was resigned from the ticket
    * @umbrah[/z](https://www.0crat.com/u/umbrah): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231151%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by fabriciofx** [comment]
@aivinog1 can you close this issue?

**Comment by aivinog1** [comment]
@fabriciofx sure, closing it.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1151](https://github.com/yegor256/cactoos/issues/1151) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0pdd** [comment]
@aivinog1 the only puzzle [#1205](https://github.com/yegor256/cactoos/issues/1205) is solved here.
