### ISSUE TITLE
Release build broken: go-gitlint complains about rultor's commit msg

### ISSUE THREAD

**Issue by llorllale** [yegor256/cactoos#1159]
See [rultor log](http://www.rultor.com/t/19088-508305225).

**Comment by llorllale** [comment]
Fixed in 7ea75c8ab6b24b1ef2afc20f52d680fa944ace1b, see [rultor build](http://www.rultor.com/t/19088-509003982)

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1159` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
