### ISSUE TITLE
Provide clear contributing guidelines about rebasing in PRs

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#1163]
Following some discussions:
- https://github.com/llorllale/cactoos-matchers/pull/131#discussion_r303223445
- https://github.com/yegor256/cactoos/pull/1154#discussion_r303207902
- https://t.me/zerocracy/7175

I think we need clear guideline about what is expected of DEV concerning changes made after REV comments as well as about merging vs rebasing w.r.t. master branch in case of conflicts.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by victornoel** [comment]
For the record, until now I was more for rebasing all the time, but I kind of had my mind changed (not 100%) so I would like to have a clear guideline so as not to think anymore about it :)

/cc @scristalli

**Comment by victornoel** [comment]
@llorllale I wasn't aware of it, but it seems that I am not the only one bothered by this kind of questions: https://github.com/zerocracy/zerocracy.github.io/pull/103#issuecomment-509644947

**Comment by llorllale** [comment]
@victornoel it's certainly cleaner for the project as a whole if each commit corresponds to exactly one issue.

On the other hand, it would make it difficult for a DEV to revert changes as he is working to have his PR merged (he may be asked to revert a subset of the change). But then again - these are microtasks we're talking about, so perhaps this shouldn't be a big issue.

I think I lean more towards a single commit per PR, but how can we reliably enforce that? One step would be to add that check in the Zerocracy QA policy, but it would be even better if there were some github app that does it.

Note: I don't care much for rebasing per se - all I'd like is a single commit per PR.

**Comment by victornoel** [comment]
@llorllale I don't think we need to enforce it (and there always will be some special cases), but at least a clear ruling and guidelines would be helpful to not spend time discussing this between DEV and REV.

In the ghman project, the guidelines are in the README for example, so that DEV and REV can refer to it.

**Comment by llorllale** [comment]
@victornoel Am I missing something? There is nothing related to commits in neither https://github.com/g4s8/ghman/blob/master/README.md nor https://github.com/g4s8/ghman/tree/master/.github

**Comment by llorllale** [comment]
@victornoel I'm assuming the default rules of Zerocracy apply

**Comment by victornoel** [comment]
@llorllale it's not yet merged: https://github.com/g4s8/ghman/pull/67

Which default rules are you referring to? I may have missed something there!

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1163` is not assigned, can't get performer
