### ISSUE TITLE
All collections/iterable/etc constructor should accept wildcarded values

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#1169]
The following code has two problems with typing:
```java
List<Socket> sockets = new ListOf(new Socket());
// here Java can't infer the type Closeable
new Joined<>(new ServerSocket(), sockets);
// here java refuse to compile with the type Closeable
new Joined<>(new ServerSocket(), sockets);
```

The problem is that collections are covariant with their parameter (at least) but the current declaration of the constructors of classes like `Joined`, or even `ListOf` and `IterableOf`fail to capture that:
```java
Joined(final T item, final Iterable<T> items)
```

If they were declared as:
```java
Joined(final T item, final Iterable<? extends T> items)
```

Then they could be usable more generally and without incurring any problem.

The same problem can happen with say `And`:
```java
List<Socket> sockets = new ListOf(new Socket());
// this could be a reusable Proc in the codebase
Proc<Closeable> close = Closeable::close;
// this does not compile because the type of the generic of close is not exactly the same as the type of the genric of sockets.
new And(close, sockets);
```

I believe all of our constructors should accept covariant version of the collection they take, especially those that mixes collections with a single item (as in `Joined`) so as to help Java inference, and those that mixes collection with say a `Scalar` or a `Proc` (as in `And`) to ease composition.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by victornoel** [comment]
@0crat in

Let's do that, first for iterable and iterator.

**Comment by 0crat** [comment]
> @0crat in Let's do that, first for iterable and iterator. ([here](https://github.com/yegor256/cactoos/issues/1169#issuecomment-653789378))

@victornoel Argument "Let's" doesn't match regex `[A-Z]{2,3}`

**Comment by victornoel** [comment]
@0crat in

**Comment by victornoel** [comment]
@0crat in

**Comment by fabriciofx** [comment]
@0crat refuse

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1169#issuecomment-694808579))

@fabriciofx The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#1169](https://github.com/yegor256/cactoos/issues/1169), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1169#issuecomment-694812591))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1169](https://github.com/yegor256/cactoos/issues/1169) is [in scope](http://www.zerocracy.com/policy.html#14) for 5days
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @victornoel[/z](https://www.0crat.com/u/victornoel): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231169%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1169#issuecomment-694808579))

@fabriciofx Job refused in 5 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by victornoel** [comment]
@0crat status

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1169#issuecomment-701520599))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1169](https://github.com/yegor256/cactoos/issues/1169) is [in scope](http://www.zerocracy.com/policy.html#14) for 18days
  * The role is `DEV`
  * The job is assigned to @andreoss[/z](https://www.0crat.com/u/andreoss) for [9days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @victornoel[/z](https://www.0crat.com/u/victornoel): This user reported the ticket
    * @fabriciofx[/z](https://www.0crat.com/u/fabriciofx): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231169%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1169#issuecomment-701612216))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1169](https://github.com/yegor256/cactoos/issues/1169) is [in scope](http://www.zerocracy.com/policy.html#14) for 18days
  * The role is `DEV`
  * The job is assigned to @andreoss[/z](https://www.0crat.com/u/andreoss) for [9days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @victornoel[/z](https://www.0crat.com/u/victornoel): This user reported the ticket
    * @fabriciofx[/z](https://www.0crat.com/u/fabriciofx): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231169%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @andreoss[/z](https://www.0crat.com/u/andreoss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by victornoel** [comment]
@rultor release, tag is `0.47`

**Comment by victornoel** [comment]
@yegor256 it seems rultor in cactoos was setup to execute the build with sonar but I get the error above. I suppose it has worked in the past because I don't remember changing anything about this... do you know if this is expected and what should be done to solve it, either:
- have this experted sonarqube server running again or (I can't do it)
- remove sonar reporting from the build (I can do it :)

**Comment by victornoel** [comment]
@yegor256 actually it seems it was meant to send the reports to https://sonarcloud.io/dashboard?id=org.cactoos%3Acactoos (according to the previous working release: https://www.rultor.com/t/21864-624598768) but it is not doing that anymore, so I will investigate a bit first.

**Comment by victornoel** [comment]
@paulodamaso it seems you removed the sonar configuration in the commit 1e8f4d0971aea1d8716bc87d14650ba6857cbe5d, do you know why?

**Comment by victornoel** [comment]
@rultor release, tag is `0.47`

**Comment by victornoel** [comment]
@paulodamaso @yegor256 I've tried to fix this with 51f86863

**Comment by victornoel** [comment]
@rultor release, tag is `0.47`

**Comment by victornoel** [comment]
@yegor256 it seems the `settings.xml` file used by rultor in cactoos does not contain the property `gpg.keyname` and thus the artefacts aren't signed, which prevent them being deployed to sonatype. Can you do something about that?

**Comment by andreoss** [comment]
@victornoel @yegor256 The problem seems to be similar to https://github.com/jcabi/jcabi-jdbc/issues/86

**Comment by victornoel** [comment]
@andreoss yes, totally, thx

**Comment by victornoel** [comment]
@andreoss anyway I have continued to try to release in #1490, almost there ^^
