### ISSUE TITLE
FallbackFrom should be an interface

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#1170]
It is not possible to implement my own `FallbackFrom`.

For example I would like to define an implementation of `FallbackFrom` that wraps an `Exception` and and calls `addSupressed` on it every time it is called.

For now the only solution is to do this in my own implementation of `Func` and to compose it with `FallbackFrom` but I don't see why I have to bother with this extra layer of objects.

The interface should be declared in `ScalarWithFallback` and a new name should be proposed for either the interface or the default implementation.

See also #895

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by victornoel** [comment]
@0crat in

**Comment by victornoel** [comment]
@0crat in

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1170#issuecomment-699654992))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1170](https://github.com/yegor256/cactoos/issues/1170) is [in scope](http://www.zerocracy.com/policy.html#14) for 14days
  * The role is `DEV`
  * The job is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) for [9days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @victornoel[/z](https://www.0crat.com/u/victornoel): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231170%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by fabriciofx** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1170#issuecomment-701663995))

@fabriciofx This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1170](https://github.com/yegor256/cactoos/issues/1170) is [in scope](http://www.zerocracy.com/policy.html#14) for 18days
  * The role is `DEV`
  * The job is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) for [13days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @victornoel[/z](https://www.0crat.com/u/victornoel): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231170%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@fabriciofx are you going to solve this ticket?

**Comment by fabriciofx** [comment]
@victornoel yeah. I should something done tomorrow. Sorry for late.

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1170#issuecomment-751455420))

@victornoel The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#1170](https://github.com/yegor256/cactoos/issues/1170), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#1170](https://github.com/yegor256/cactoos/issues/1170) assigned to @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), here is [why](https://www.0crat.com/footprint/C63314D6Z/1c102031-e9c9-4981-9f9f-6929ab8088f6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by baudoliver7** [comment]
@victornoel, resolving this issue will resolve also #895. Can I submit only one PR for both issues ?

**Comment by victornoel** [comment]
@baudoliver7 yes of course, great idea :)

**Comment by baudoliver7** [comment]
Thanks!

**Comment by baudoliver7** [comment]
@victornoel, I want to remove this PR and resend it again.

**Comment by victornoel** [comment]
@baudoliver7 just close it and create a new one, or force push on your branch if you want

**Comment by baudoliver7** [comment]
Ok

**Comment by victornoel** [comment]
@baudoliver7 thx

**Comment by baudoliver7** [comment]
@victornoel Happy to contribute !

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@baudoliver7 please make sure you start all your comments with the name of the user they are referred to, [see](https://github.com/yegor256/cactoos/issues/1170#issuecomment-756623095)

**Comment by baudoliver7** [comment]
@sereshqua, I get it.

**Comment by sereshqua** [comment]
@0crat quality acceptable
