### ISSUE TITLE
Equals<T extends Comparable<T>> contains a circular reference

### ISSUE THREAD

**Issue by StuporHero** [yegor256/cactoos#1174]
You can't use `ComparableText` with `Equals` because `ComparableText` doesn't implement `Comparable<ComparableText>` as the circular generic parameter requires on `Equals`. You could use `<T extends Comparable<R>>` and use the `R` parameter with the raw constructor requested in #1173.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@stuporhero[/z](https://www.0crat.com/u/stuporhero) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by victornoel** [comment]
@StuporHero  I'm closing it as it is going to be done as part of #1173.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1174` is not assigned, can't get performer
