### ISSUE TITLE
TrueOrThrow class

### ISSUE THREAD

**Issue by StuporHero** [yegor256/cactoos#1175]
I have a use case that I think might be common enough to warrant creating a dedicated class in this library to handling. I need to evaluate a `Boolean` expression and throw an `Exception` if that expression is false. It should probably implement `Scalar<Boolean>` and have a signature of `TrueOrThrow(expression, exceptionMessage)`.

```java
new TrueOrThrow(
    () -> 1 == 0,    
    "1 does not equal 0."
).value();
```

For completeness, its counterpart would be:

```java
new FalseOrThrow(
    () -> 1 == 1,
    "1 does equal 1, but we need it not to for some reason."
).value();
```

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@stuporhero[/z](https://www.0crat.com/u/stuporhero) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1175` is not assigned, can't get performer
