### ISSUE TITLE
Change oraclejdk8 to openjdk8 on Travis CI

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#1177]
@paulodamaso Travis CI hasn't working because `oraclejdk8` license is not valid anymore. So, let's change it to `openjdk8`. I refactoring of this configuration file `.travis.yml` can be a possibility too.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@fabriciofx We'll use `trusty` distro instead using `openjdk8` for now

**Comment by iakunin** [comment]
@fabriciofx, see #1176

**Comment by fabriciofx** [comment]
Closed by #1176 .

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1177` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
