### ISSUE TITLE
Rultor merge failure, but CI-builds are OK

### ISSUE THREAD

**Issue by iakunin** [yegor256/cactoos#1178]
## Problem
You can see the rultor-megre problem in https://github.com/yegor256/cactoos/pull/1176#issuecomment-530923097.

## What's happened?
Rultor merge has failed because of `gitlint` failure:
```
937c047: subject does not match regex [^\(#[0-9]+\) [^\s].{13,50}]
```

`Gitlint` failure happened because subject of [this commit](https://github.com/yegor256/cactoos/commit/937c04738020fb9385d828db58660dacf60e6b13) does not match to the expected regexp.

Subject of [this commit](https://github.com/yegor256/cactoos/commit/937c04738020fb9385d828db58660dacf60e6b13) does not match to the expected regexp _potentially_ because it was committed without a PR.

## How can we prevent this in the future?
I see two solutions here:

#### First one
NOBODY can commit into `master` branch without a PR.
This solution doesn't require any code changes: only the settings in the github-repo.

#### Second one
We can add an extra-step in out CI pipelines. This step should check if the destination branch of the PR (usually `master`) is fully merged into the source branch. If it's not the build fails.

Furthermore, both of these solutions can be implemented simultaneously.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/cactoos/issues/1178#issuecomment-531432930))

@paulodamaso The job [#1178](https://github.com/yegor256/cactoos/issues/1178) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C63314D6Z/7985eb7b-0e59-4b9e-9fe4-e1c5a210aa67); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @iakunin[/z](https://www.0crat.com/u/iakunin)

**Comment by paulodamaso** [comment]
@iakunin updated gitlint date, build is ok in rultor now

**Comment by iakunin** [comment]
@paulodamaso, thank you. 

And what’s about preventing this kind of problem in future? Should we do something about it?

**Comment by paulodamaso** [comment]
@iakunin I don't think we should bother with this for now; anyway I've asked @llorllale to implement a feature that allows us to ignore gitlinting from some users

**Comment by iakunin** [comment]
https://github.com/paulodamaso, thank you so much!

**Comment by 0crat** [comment]
Job was finished in 20 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#1178](https://github.com/yegor256/cactoos/issues/1178) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)
