### ISSUE TITLE
Examples from README.md doesn't work

### ISSUE THREAD

**Issue by emfataliev** [yegor256/cactoos#1180]
Below is a list of examples that have compilation errors:
```
List<String> sorted = new ListOf<>(
  new Sorted<>(
    new Split(
      new TextOf(
        new File("/tmp/names.txt")
      ),
      new TextOf("\\s+")
    )
  )
);
```
```
int total = new LengthOf(
  "how", "are", "you"
).intValue();
```
```
new And(
  names,
  n -> {
    System.out.printf("Hello, %s!\n", n);
  }
).value();
```
```
new And(
  new Endless<>(ready),
  ready -> {
    System.out.println("Still waiting...");
    return !ready;
  }
).value();
```
```
final OffsetDateTime date = ...;
final OffsetDateTimeAsText text = new OffsetDateTimeAsText(date);
```

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
@emfataliev[/z](https://www.0crat.com/u/emfataliev) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by fabriciofx** [comment]
@emfataliev I'm sorry, but you can't open an issue and submit the PR to fix it without at least the `ARC` explicitly said you can do it.

**Comment by emfataliev** [comment]
I can create issue and just wait until you solve it? It sounds sad... I thought I could participate in the development

**Comment by fabriciofx** [comment]
@emfataliev you create an issue. If it'll be accepted (scope in) you'll receive points for it. The Zerocracy plataform will pick a developer (`DEV`) to fix the issue and a revisor (`REV`) to this submitted PR. It's how the system works.

**Comment by emfataliev** [comment]
@fabriciofx and what can I do with the received points? Where are all these rules described?

**Comment by fabriciofx** [comment]
@emfataliev please, read the [policy](http://www.zerocracy.com/policy.html).

**Comment by victornoel** [comment]
@emfataliev it is ok to make a PR for a ticket that is not accepted by ARC, I think in this case it would be accepted, but you have to be prepared to have it refused if ARC doesn't want it of course :)

Is the problem still present?

**Comment by emfataliev** [comment]
The problem is no longer present)

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1180` is not assigned, can't get performer
