### ISSUE TITLE
IterableOf.java:93-95: Move this constructor in its own...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1183]
The puzzle `947-0e04e40a` from #947 has to be resolved: 

https://github.com/yegor256/cactoos/blob/b092754a6e18a39951e27733490be1961dadfeb0/src/main/java/org/cactoos/iterable/IterableOf.java#L93-L95

The puzzle was created by Victor Noël on 30-Jun-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1183](https://github.com/yegor256/cactoos/issues/1183) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1183](https://github.com/yegor256/cactoos/issues/1183) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/C63314D6Z/f838d3ec-809d-4d1d-a34b-0aa50847ccff); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The job [#1183](https://github.com/yegor256/cactoos/issues/1183) assigned to @roman-kuvaldin[/z](https://www.0crat.com/u/roman-kuvaldin), here is [why](https://www.0crat.com/footprint/C63314D6Z/4267e98d-cb2a-4306-a076-ce94d055c51d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The architect of the project has changed; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is not at this role anymore; @victornoel[/z](https://www.0crat.com/u/victornoel) is the architect now

**Comment by victornoel** [comment]
@0crat in

**Comment by victornoel** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/1183#issuecomment-653901629))

@victornoel Job [#1183](https://github.com/yegor256/cactoos/issues/1183) is already in scope

**Comment by 0crat** [comment]
The job [#1183](https://github.com/yegor256/cactoos/issues/1183) assigned to @lavinj87[/z](https://www.0crat.com/u/lavinj87), here is [why](https://www.0crat.com/footprint/C63314D6Z/5365ff6a-bf91-47e6-bac5-4d3214646e89); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1183#issuecomment-658882071))

@victornoel The user @lavinj87[/z](https://www.0crat.com/u/lavinj87) resigned from [#1183](https://github.com/yegor256/cactoos/issues/1183), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#1183](https://github.com/yegor256/cactoos/issues/1183) assigned to @andreoss[/z](https://www.0crat.com/u/andreoss), here is [why](https://www.0crat.com/footprint/C63314D6Z/ff39d76a-f855-4121-84fa-a39131ca6ade); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `947-0e04e40a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1464](https://github.com/yegor256/cactoos/issues/1464) is still not solved.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1537](https://github.com/yegor256/cactoos/issues/1537), [#1538](https://github.com/yegor256/cactoos/issues/1538) are still not solved; solved: [#1464](https://github.com/yegor256/cactoos/issues/1464).

**Comment by 0pdd** [comment]
@0pdd all 3 puzzles are solved here: [#1464](https://github.com/yegor256/cactoos/issues/1464), [#1537](https://github.com/yegor256/cactoos/issues/1537), [#1538](https://github.com/yegor256/cactoos/issues/1538).
