### ISSUE TITLE
ListEnvelope.java:41-45: ListEnvelope should only...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1185]
The puzzle `947-4efcb5fb` from #947 has to be resolved: 

https://github.com/yegor256/cactoos/blob/b092754a6e18a39951e27733490be1961dadfeb0/src/main/java/org/cactoos/list/ListEnvelope.java#L41-L45

The puzzle was created by Victor Noël on 30-Jun-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1185](https://github.com/yegor256/cactoos/issues/1185) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1185](https://github.com/yegor256/cactoos/issues/1185) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/9bf1814e-d5b4-4115-aa33-6ca550c63eb6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #1184 to be fixed first as it is the superclass of `ListEnvelope`

**Comment by 0crat** [comment]
> @0crat wait for #1184 to be fixed first as it is the superclass of `ListEnvelope` ([here](https://github.com/yegor256/cactoos/issues/1185#issuecomment-533810162))

@victornoel The impediment for [#1185](https://github.com/yegor256/cactoos/issues/1185) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@0crat wait for #1255 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #1255 to be merged ([here](https://github.com/yegor256/cactoos/issues/1185#issuecomment-560095352))

@victornoel Job [#1185](https://github.com/yegor256/cactoos/issues/1185) is already on hold

**Comment by 0pdd** [comment]
The puzzle `947-4efcb5fb` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
