### ISSUE TITLE
Wrap local build in docker (for DEV)

### ISSUE THREAD

**Issue by iakunin** [yegor256/cactoos#1186]
### Idea
I think it's a good idea to have an opportunity to run build (`mvn clean install -Pqulice`) inside docker-container. And than docker-container should be the same as in CI (`yegor256/java8`).

### Why?
I think, It's obvious enough: to reproduce the same canonical env as in CI and don't bother about `java` and `maven` versions installed on your host-OS.

### How to implement
I've already written some Makefile. It looks like that:

```
test:
	docker run \
	--tty \
	--workdir=/main \
	--volume=$(shell pwd):/main \
	--volume=/var/run/docker.sock:/var/run/docker.sock \
	--volume=cactoos-mvn-cache:/root/.m2 \
	--rm \
	--hostname=docker \
	--privileged \
	--memory=6g \
	--oom-kill-disable \
	yegor256/java8 \
	"mvn clean install -Pqulice && mvn clean site -Psite"

clean:
	docker volume rm cactoos-mvn-cache
```

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by iakunin** [comment]
@paulodamaso, what do you think? It's very helpful for me. Would it be helpful for all the developers?

**Comment by iakunin** [comment]
@paulodamaso, sorry for being impatient, what do you think about this issue?

**Comment by paulodamaso** [comment]
@iakunin Okay, let's add this configuration and how to run it using a docker container as an alternative in readme

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/1186#issuecomment-534142264))

@paulodamaso Job [#1186](https://github.com/yegor256/cactoos/issues/1186) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @iakunin[/z](https://www.0crat.com/u/iakunin)

**Comment by 0crat** [comment]
The job [#1186](https://github.com/yegor256/cactoos/issues/1186) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/da54a419-2000-4bba-8078-17d9ea54878c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #1196 to be merged

@iakunin don't hesitate to chip in the PR if things are not to your liking

**Comment by 0crat** [comment]
> @0crat wait for #1196 to be merged @iakunin don't hesitate to chip in the PR if things are not... ([here](https://github.com/yegor256/cactoos/issues/1186#issuecomment-536199517))

@victornoel The impediment for [#1186](https://github.com/yegor256/cactoos/issues/1186) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@iakunin can you close this? The PR has been merged

**Comment by iakunin** [comment]
@victornoel great work! Thank you so much =)

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1186](https://github.com/yegor256/cactoos/issues/1186) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
