### ISSUE TITLE
Create IteratorEnvelope iterator

### ISSUE THREAD

**Issue by fanifieiev** [yegor256/cactoos#1190]
It was suggested by @victornoel that there is new class `IteratorEnvelope` as stated here
https://github.com/yegor256/cactoos/pull/1189#discussion_r326864052

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
@fanifieiev[/z](https://www.0crat.com/u/fanifieiev) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by fanifieiev** [comment]
Not relevant

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1190` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
