### ISSUE TITLE
Sliced.java:40-42: This class to be refactored by...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1193]
The puzzle `1188-ace6cee0` from #1188 has to be resolved: 

https://github.com/yegor256/cactoos/blob/903dd2f6b3e23ca8b362e8092ff59f2c8c9a84c3/src/main/java/org/cactoos/iterator/Sliced.java#L40-L42

The puzzle was created by @rultor on 25-Sep-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1193](https://github.com/yegor256/cactoos/issues/1193) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1193](https://github.com/yegor256/cactoos/issues/1193) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/90aca4e0-0ec7-4312-88c3-a7713ef46317); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@paulodamaso it's not possible to extend `IteratorEnvelope` here: I think the original point was to implement `Sliced`-based classes by extending `IteratorEnvelope`.
I propose to introduce `IteratorEnvelope` here so that it can be used for #1191 #1192 #1194. WDYT?

**Comment by victornoel** [comment]
@0crat wait for ARC to answer

**Comment by 0crat** [comment]
> @0crat wait for ARC to answer ([here](https://github.com/yegor256/cactoos/issues/1193#issuecomment-536208113))

@victornoel The impediment for [#1193](https://github.com/yegor256/cactoos/issues/1193) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@paulodamaso ping

**Comment by paulodamaso** [comment]
@victornoel That's perfect, please go on

**Comment by victornoel** [comment]
@0crat wait for #1204 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #1204 to be merged ([here](https://github.com/yegor256/cactoos/issues/1193#issuecomment-538748583))

@victornoel Job [#1193](https://github.com/yegor256/cactoos/issues/1193) is already on hold

**Comment by 0pdd** [comment]
The puzzle `1188-ace6cee0` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#1193](https://github.com/yegor256/cactoos/issues/1193) is now out of scope

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)
