### ISSUE TITLE
Let's move classes that implements Bytes in io package to bytes package

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#1199]
There're a lot of classes in `org.cactoos.io` package that implements `Bytes`. IMHO, there're in the wrong package and should moved to `org.cactoos.bytes` package. @paulodamaso make sense to you?

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by victornoel** [comment]
@0crat in

**Comment by victornoel** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#1199](https://github.com/yegor256/cactoos/issues/1199) assigned to @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), here is [why](https://www.0crat.com/footprint/C63314D6Z/28b4a321-e6a3-40bc-ad4b-9ffac931cf21); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by baudoliver7** [comment]
@victornoel the work has been for 2 days. Just to prevent you. :)

**Comment by victornoel** [comment]
@0crat refuse

**Comment by victornoel** [comment]
@baudoliver7 sorry I made a mistake

**Comment by victornoel** [comment]
@0crat assign @baudoliver7

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1199#issuecomment-759976926))

@victornoel The user @baudoliver7[/z](https://www.0crat.com/u/baudoliver7) resigned from [#1199](https://github.com/yegor256/cactoos/issues/1199), please stop working. Reason for job resignation: Order was cancelled

**Comment by victornoel** [comment]
@baudoliver7 I thought it was the PR and wanted zerocrat to assign someone ^^ I will do that later when I'm really awake :) I will make thing go forward

**Comment by 0crat** [comment]
> @0crat assign @baudoliver7  ([here](https://github.com/yegor256/cactoos/issues/1199#issuecomment-759977161))

@victornoel The job [#1199](https://github.com/yegor256/cactoos/issues/1199) assigned to @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), here is [why](https://www.0crat.com/footprint/C63314D6Z/777213b0-381c-4cb4-bfbd-da9fe9eb891d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by baudoliver7** [comment]
@victornoel Great !

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@b40c505f-5cb0-4cae-88ec-eec5fb70b484, thread: PQ-C63314D6Z
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:yegor256/cactoos#1199] declared for identity constraint of element "speed".
```

[0.55](https://github.com/zerocracy/farm): CID: [3318fa3f-6d5b-42c5-aef4-fc9cdbc4a658](https://www.0crat.com/footprint/C63314D6Z/3318fa3f-6d5b-42c5-aef4-fc9cdbc4a658), Type: "Order was finished"

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
