### ISSUE TITLE
pom.xml:166-168: After updated qulice-maven-plugin...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1205]
The puzzle `1151-07534af5` from #1151 has to be resolved: 

https://github.com/yegor256/cactoos/blob/671b55d9672c752971742781d258c37d06ed38a0/pom.xml#L166-L168

The puzzle was created by Fabricio Cabral on 08-Oct-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job [#1205](https://github.com/yegor256/cactoos/issues/1205) is now in scope, role is `DEV`

**Comment by fanifieiev** [comment]
@paulodamaso, @fabriciofx 
I have almost fixed everything related to this ticket, but there are some uncertain leftovers, specifically raised by FindBugs.
Examples:

1. http://findbugs.sourceforge.net/bugDescriptions.html#EQ_UNUSUAL
`[INFO] >> M D Eq: org.cactoos.map.MapEnvelope.equals(Object) is unusual  At MapEnvelope.java:[line 151]
[INFO] >> M D Eq: org.cactoos.iterable.IterableOf.equals(Object) is unusual  At IterableOf.java:[line 149]
[INFO] >> M D Eq: org.cactoos.text.TextEnvelope.equals(Object) is unusual  At TextEnvelope.java:[line 80]
[INFO] >> M D Eq: org.cactoos.collection.CollectionEnvelope.equals(Object) is unusual  At CollectionEnvelope.java:[line 155]`

**Comment by fanifieiev** [comment]
I have almost fixed everything related to this ticket, but there are some uncertain leftovers, specifically raised by FindBugs.
Examples:

http://findbugs.sourceforge.net/bugDescriptions.html#EQ_UNUSUAL
`[INFO] >> M D Eq: org.cactoos.map.MapEnvelope.equals(Object) is unusual At MapEnvelope.java:[line 151] [INFO] >> M D Eq: org.cactoos.iterable.IterableOf.equals(Object) is unusual At IterableOf.java:[line 149] [INFO] >> M D Eq: org.cactoos.text.TextEnvelope.equals(Object) is unusual At TextEnvelope.java:[line 80] [INFO] >> M D Eq: org.cactoos.collection.CollectionEnvelope.equals(Object) is unusual At CollectionEnvelope.java:[line 155]`

That seems to be false positive as the implementation looks good, but unusual, need a way to suppress check.

Any suggestions?

**Comment by paulodamaso** [comment]
@fanifieiev Have you tried https://dzone.com/articles/suppressing-findbugs-warnings ?

**Comment by fanifieiev** [comment]
> @fanifieiev Have you tried https://dzone.com/articles/suppressing-findbugs-warnings ?

Yes, I did,
It requires adding new library  `com.google.code.findbugs:annotations` into the project 
and use annotation `@edu.umd.cs.findbugs.annotations.SuppressWarnings`, 
which I would not like to.

**Comment by fanifieiev** [comment]
@fabriciofx, @paulodamaso 
I added finbugs com.google.code.findbugs:annotations dependency to use @edu.umd.cs.findbugs.annotations.SuppressFBWarnings as that is the only option to suppress EQ_UNUSUAL findbug violation.

**Comment by paulodamaso** [comment]
@fanifieiev Sorry for the delay. Which is the PR?

**Comment by fanifieiev** [comment]
> @fanifieiev Sorry for the delay. Which is the PR?

https://github.com/yegor256/cactoos/pull/1208

**Comment by fanifieiev** [comment]
@paulodamaso The PR  [1208](https://github.com/yegor256/cactoos/pull/1208) has been merged but this issues is still open. 
Who is supposed to close the issue?

**Comment by fanifieiev** [comment]
@0crat status

**Comment by paulodamaso** [comment]
@fanifieiev 0pdd is supposed to close it, let's wait for the next merge operation to see if it'll clean the code of the stall puzzles

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1205#issuecomment-548789327))

@fanifieiev This is what I know about this job in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1205](https://github.com/yegor256/cactoos/issues/1205) is [in scope](http://www.zerocracy.com/policy.html#14) for 24days
  * The role is `DEV`
  * The job is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev) for [24days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231205%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by fanifieiev** [comment]
> @fanifieiev 0pdd is supposed to close it, let's wait for the next merge operation to see if it'll clean the code of the stall puzzles

ok, thx

**Comment by 0pdd** [comment]
The puzzle `1151-07534af5` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1205](https://github.com/yegor256/cactoos/issues/1205) is now out of scope

**Comment by sereshqua** [comment]
@fanifieiev please make sure you start all the comments with the name of the user you are referring to, see: [1](https://github.com/yegor256/cactoos/issues/1205#issuecomment-543874062), [2](https://github.com/yegor256/cactoos/issues/1205#issuecomment-548821213)

**Comment by fanifieiev** [comment]
> @fanifieiev please make sure you start all the comments with the name of the user you are referring to, see: [1](https://github.com/yegor256/cactoos/issues/1205#issuecomment-543874062), [2](https://github.com/yegor256/cactoos/issues/1205#issuecomment-548821213)

@sereshqua sure, will do that.
BTW: I updated the mentioned  [1](https://github.com/yegor256/cactoos/issues/1205#issuecomment-543874062), [2](https://github.com/yegor256/cactoos/issues/1205#issuecomment-548821213)
sections.

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)
