### ISSUE TITLE
SetOf discards non-duplicate elements

### ISSUE THREAD

**Issue by golszewski86** [yegor256/cactoos#1212]
This code:
```java
import java.util.Set;
import org.cactoos.iterable.IterableOf;
import org.cactoos.iterable.Joined;
import org.cactoos.set.SetOf;

public class SetTest {
    public static void main(final String[] args) {
        final Iterable<String> first = new IterableOf<>("cc");
        final Iterable<String> second = new IterableOf<>("aa", "bb", "cc", "dd");
        final Set<String> set = new SetOf<>(new Joined<>(first, second));
        for (final String str : set) {
            System.out.println(str);
        }
        System.out.println(set.contains("cc"));
        System.out.println(set.contains("dd"));
    }
}
```
Produces the following output:
```
cc
aa
bb
true
false
```

As you can see, element "dd" is discarded upon creation of SetOf instance.

**EDIT:** The issue can be also replicated with much simpler code:
```java
new SetOf<>("a", "a", "b", "c", "b", "d", "e");
```
This set will contain **only** "a"...

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
@golszewski86[/z](https://www.0crat.com/u/golszewski86) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by paulodamaso** [comment]
@golszewski86 Thanks for the but report!

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/1212#issuecomment-548594232))

@paulodamaso Job [#1212](https://github.com/yegor256/cactoos/issues/1212) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/1212#issuecomment-548594232))

@paulodamaso Thanks for your contribution, @golszewski86[/z](https://www.0crat.com/u/golszewski86)! If you would be a member of [the project](https://www.0crat.com/p/C63314D6Z), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
The job [#1212](https://github.com/yegor256/cactoos/issues/1212) assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/C63314D6Z/438bae49-eb00-45b9-947f-27df77cccbfd); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by fanifieiev** [comment]
@0crat status

**Comment by fanifieiev** [comment]
@0crat wait for [#1215](https://github.com/yegor256/cactoos/pull/1215) to be merged

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1212#issuecomment-552491833))

@fanifieiev This is what I know about this job in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1212](https://github.com/yegor256/cactoos/issues/1212) is [in scope](http://www.zerocracy.com/policy.html#14) for 11days
  * The role is `DEV`
  * The job is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev) for [11days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @golszewski86[/z](https://www.0crat.com/u/golszewski86): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231212%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat wait for [#1215](https://github.com/yegor256/cactoos/pull/1215) to be merged ([here](https://github.com/yegor256/cactoos/issues/1212#issuecomment-552512948))

@fanifieiev The impediment for [#1212](https://github.com/yegor256/cactoos/issues/1212) was registered successfully by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Comment by 0crat** [comment]
> @0crat status  ([here](https://github.com/yegor256/cactoos/issues/1212#issuecomment-555548693))

@fanifieiev This is what I know about this job in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1212](https://github.com/yegor256/cactoos/issues/1212) is [in scope](http://www.zerocracy.com/policy.html#14) for 19days
  * The role is `DEV`
  * The job is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev) for [19days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @golszewski86[/z](https://www.0crat.com/u/golszewski86): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231212%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by fanifieiev** [comment]
@0crat continue

**Comment by 0crat** [comment]
> @0crat continue ([here](https://github.com/yegor256/cactoos/issues/1212#issuecomment-555550627))

@fanifieiev @fanifieiev[/z](https://www.0crat.com/u/fanifieiev) continued working on job [#1212](https://github.com/yegor256/cactoos/issues/1212)

**Comment by fanifieiev** [comment]
@sereshqua @paulodamaso  The corresponding [PR ](https://github.com/yegor256/cactoos/pull/1215) has been merged.
What is the next step here for the issue to be closed?

**Comment by sereshqua** [comment]
@fanifieiev you would need to ask @golszewski86 to close the issue

**Comment by fanifieiev** [comment]
@golszewski86 Could you please react to the this issue? The corresponding [pull request](https://github.com/yegor256/cactoos/pull/1215) has been merged.

**Comment by golszewski86** [comment]
Sure, I didn't know I have to close it.

**Comment by fanifieiev** [comment]
@0crat status

**Comment by fanifieiev** [comment]
@sereshqua Is it your turn to review?

**Comment by sereshqua** [comment]
@fanifieiev not yet, now 0crat will assign a reviewer

**Comment by fanifieiev** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1212#issuecomment-555726502))

@fanifieiev This is what I know about this job in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1212](https://github.com/yegor256/cactoos/issues/1212) is [in scope](http://www.zerocracy.com/policy.html#14) for 20days
  * The role is `DEV`
  * The job is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev) for [20days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @golszewski86[/z](https://www.0crat.com/u/golszewski86): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231212%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1212#issuecomment-556029189))

@fanifieiev This is what I know about this job in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1212](https://github.com/yegor256/cactoos/issues/1212) is [in scope](http://www.zerocracy.com/policy.html#14) for 20days
  * The role is `DEV`
  * The job is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev) for [20days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @golszewski86[/z](https://www.0crat.com/u/golszewski86): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231212%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by fanifieiev** [comment]
> @fanifieiev not yet, now 0crat will assign a reviewer

@sereshqua @paulodamaso @g4s8 Do you know by chance why @0crat is not assigning for "Quality review" ?

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/cactoos/issues/1212#issuecomment-556331224); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by paulodamaso** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/cactoos/issues/1212#issuecomment-556850853))

@paulodamaso There is no quality review for [#1212](https://github.com/yegor256/cactoos/issues/1212), no performer

**Comment by fanifieiev** [comment]
@paulodamaso @sereshqua I think there is sth wrong with `0crat`. 
Or does [this](https://github.com/yegor256/cactoos/issues/1212#issuecomment-556911110) message from `0crat` mean there is not performer to review?

**Comment by sereshqua** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1212#issuecomment-557201945))

@sereshqua This is what I know about this job in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1212](https://github.com/yegor256/cactoos/issues/1212) is [in scope](http://www.zerocracy.com/policy.html#14) for 21days
  * The role is `DEV`
  * The job is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev) for [21days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @golszewski86[/z](https://www.0crat.com/u/golszewski86): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231212%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by sereshqua** [comment]
@fanifieiev i don't know what's wrong, may be @g4s8 knows?

**Comment by g4s8** [comment]
@sereshqua the problem is that 0crat didn't remove this job from WBS, @paulodamaso you need to use `0crat out` command to remove it manually

**Comment by paulodamaso** [comment]
@0crat out

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/1212#issuecomment-557369668))

@paulodamaso The job [#1212](https://github.com/yegor256/cactoos/issues/1212) is now out of scope

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)
