### ISSUE TITLE
ListEnvelopeTest.java:43-45: Get rid of the Immutable in...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1217]
The puzzle `898-0bea8a51` from #898 has to be resolved: 

https://github.com/yegor256/cactoos/blob/5e0da3093e75d4e583f88a137140e14cb505d652/src/test/java/org/cactoos/list/ListEnvelopeTest.java#L43-L45

The puzzle was created by @fanifieiev on 28-Oct-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1217](https://github.com/yegor256/cactoos/issues/1217) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1217](https://github.com/yegor256/cactoos/issues/1217) assigned to @lavinj87[/z](https://www.0crat.com/u/lavinj87), here is [why](https://www.0crat.com/footprint/C63314D6Z/fd827a7e-4ee2-441b-8352-a16248cac461); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The architect of the project has changed; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is not at this role anymore; @victornoel[/z](https://www.0crat.com/u/victornoel) is the architect now

**Comment by victornoel** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#1217](https://github.com/yegor256/cactoos/issues/1217) assigned to @roman-kuvaldin[/z](https://www.0crat.com/u/roman-kuvaldin), here is [why](https://www.0crat.com/footprint/C63314D6Z/462e13f6-b3aa-4c45-9e04-6c2e5fdc341b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1217#issuecomment-658907704))

@victornoel Job `gh:yegor256/cactoos#1217` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1217#issuecomment-658881983))

@victornoel The user @roman-kuvaldin[/z](https://www.0crat.com/u/roman-kuvaldin) resigned from [#1217](https://github.com/yegor256/cactoos/issues/1217), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#1217](https://github.com/yegor256/cactoos/issues/1217) assigned to @mazdack[/z](https://www.0crat.com/u/mazdack), here is [why](https://www.0crat.com/footprint/C63314D6Z/90c3942c-cac1-4fec-b1fd-b24087744ee4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The job [#1217](https://github.com/yegor256/cactoos/issues/1217) assigned to @andreoss[/z](https://www.0crat.com/u/andreoss), here is [why](https://www.0crat.com/footprint/C63314D6Z/2692d892-6168-4037-96dc-c55dc323010f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `898-0bea8a51` has disappeared from the source code, that's why I closed this issue.
