### ISSUE TITLE
Immutable.java:38-40: Introduce an Immutable wrapper for...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1219]
The puzzle `898-fb66ac0b` from #898 has to be resolved: 

https://github.com/yegor256/cactoos/blob/5e0da3093e75d4e583f88a137140e14cb505d652/src/main/java/org/cactoos/list/Immutable.java#L38-L40

The puzzle was created by @fanifieiev on 28-Oct-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1219](https://github.com/yegor256/cactoos/issues/1219) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1219](https://github.com/yegor256/cactoos/issues/1219) assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/C63314D6Z/0d4d2622-aa87-4a8c-963e-ed3b32c741f4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by fanifieiev** [comment]
@victornoel @iakunin @paulodamaso 
Guys, I have a question to you:
The test class [ListEnvelopeTest](https://github.com/yegor256/cactoos/blob/master/src/test/java/org/cactoos/list/ListEnvelopeTest.java) contains some tests: 
1. [ListEnvelopeTest.java#L142](https://github.com/yegor256/cactoos/blob/5e0da3093e75d4e583f88a137140e14cb505d652/src/test/java/org/cactoos/list/ListEnvelopeTest.java#L142)
2. [ListEnvelopeTest.java#L59](https://github.com/yegor256/cactoos/blob/5e0da3093e75d4e583f88a137140e14cb505d652/src/test/java/org/cactoos/list/ListEnvelopeTest.java#L59)
3. [ListEnvelopeTest.java#L92](https://github.com/yegor256/cactoos/blob/5e0da3093e75d4e583f88a137140e14cb505d652/src/test/java/org/cactoos/list/ListEnvelopeTest.java#L92)
The all use `ListIterator.set` method, but the [StringList](https://github.com/yegor256/cactoos/blob/5e0da3093e75d4e583f88a137140e14cb505d652/src/test/java/org/cactoos/list/ListEnvelopeTest.java#L206) is based on [Immutable](https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/list/Immutable.java) list.
My question is: why do those tests were written in a way to accept the `ListIterator.set` operation?

**Comment by iakunin** [comment]
@fanifieiev there is a todo just above the class and there is a corresponding issue: https://github.com/yegor256/cactoos/issues/1217

This test should be rewritten without using Immutable decorator.

By the way:
* https://github.com/yegor256/cactoos/blob/5e0da3093e75d4e583f88a137140e14cb505d652/src/test/java/org/cactoos/list/ListEnvelopeTest.java#L63
* https://github.com/yegor256/cactoos/blob/5e0da3093e75d4e583f88a137140e14cb505d652/src/test/java/org/cactoos/list/ListEnvelopeTest.java#L97

in these cases `set()` called on the iterator not on the `ListEnvelope` (Immutable decorator).

Also there is a test exactly about immutability of Immutable decorator: https://github.com/yegor256/cactoos/blob/5e0da3093e75d4e583f88a137140e14cb505d652/src/test/java/org/cactoos/list/ListEnvelopeTest.java#L126

**Comment by iakunin** [comment]
@fanifieiev there is a todo just above the class and there is a corresponding issue: https://github.com/yegor256/cactoos/issues/1217

This test should be rewritten without using Immutable decorator.

By the way:
* https://github.com/yegor256/cactoos/blob/5e0da3093e75d4e583f88a137140e14cb505d652/src/test/java/org/cactoos/list/ListEnvelopeTest.java#L63
* https://github.com/yegor256/cactoos/blob/5e0da3093e75d4e583f88a137140e14cb505d652/src/test/java/org/cactoos/list/ListEnvelopeTest.java#L97

in these cases `set()` called on the iterator not on the `ListEnvelope` (Immutable decorator).

Also there is a test exactly about immutability of Immutable decorator: https://github.com/yegor256/cactoos/blob/5e0da3093e75d4e583f88a137140e14cb505d652/src/test/java/org/cactoos/list/ListEnvelopeTest.java#L126

**Comment by fanifieiev** [comment]
> @fanifieiev there is a todo just above the class and there is a corresponding issue: #1217
> 
> This test should be rewritten without using Immutable decorator.
> 
> By the way:
> 
> * https://github.com/yegor256/cactoos/blob/5e0da3093e75d4e583f88a137140e14cb505d652/src/test/java/org/cactoos/list/ListEnvelopeTest.java#L63
> * https://github.com/yegor256/cactoos/blob/5e0da3093e75d4e583f88a137140e14cb505d652/src/test/java/org/cactoos/list/ListEnvelopeTest.java#L97
> 
> in these cases `set()` called on the iterator not on the `ListEnvelope` (Immutable decorator).
> 
> Also there is a test exactly about immutability of Immutable decorator:
> 
> https://github.com/yegor256/cactoos/blob/5e0da3093e75d4e583f88a137140e14cb505d652/src/test/java/org/cactoos/list/ListEnvelopeTest.java#L126

@iakunin,
IMHO, the [org.cactoos.list.Immutable](https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/list/Immutable.java)
is broken, it is not completely immutable. It looks more like a decorator to restrict mutable methods.
For instance, 
1. The [subList](https://github.com/yegor256/cactoos/blob/5e0da3093e75d4e583f88a137140e14cb505d652/src/main/java/org/cactoos/list/Immutable.java#L199) method should result in returning a immutable list as well;
2. Also, please have a look at the issue
   [Immutable list is not really immutable](https://github.com/yegor256/cactoos/issues/1224)

**Comment by fanifieiev** [comment]
@iakunin 
I was actually more concerned about the following test:
1. [ListEnvelopeTest.java#L142](https://github.com/yegor256/cactoos/blob/5e0da3093e75d4e583f88a137140e14cb505d652/src/test/java/org/cactoos/list/ListEnvelopeTest.java#L142)
2. [ListEnvelopeTest.java#L59](https://github.com/yegor256/cactoos/blob/5e0da3093e75d4e583f88a137140e14cb505d652/src/test/java/org/cactoos/list/ListEnvelopeTest.java#L59)
3. [ListEnvelopeTest.java#L92](https://github.com/yegor256/cactoos/blob/5e0da3093e75d4e583f88a137140e14cb505d652/src/test/java/org/cactoos/list/ListEnvelopeTest.java#L92)

Why do the TESTS allow mutations for listIterator returned from immutable list? 
The test IMHO are broken, they are invalid.

**Comment by iakunin** [comment]
@fanifieiev you can always create an issue and suggest your changes in it.

**Comment by victornoel** [comment]
@fanifieiev don't bother too much about `ListEnvelope` because #1185 is going to clean this up :)

**Comment by 0pdd** [comment]
The puzzle `898-fb66ac0b` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1230](https://github.com/yegor256/cactoos/issues/1230) is still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1219](https://github.com/yegor256/cactoos/issues/1219) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1233](https://github.com/yegor256/cactoos/issues/1233) is still not solved; solved: [#1230](https://github.com/yegor256/cactoos/issues/1230).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1291](https://github.com/yegor256/cactoos/issues/1291) is still not solved; solved: [#1230](https://github.com/yegor256/cactoos/issues/1230), [#1233](https://github.com/yegor256/cactoos/issues/1233).

**Comment by 0pdd** [comment]
@0pdd all 3 puzzles are solved here: [#1230](https://github.com/yegor256/cactoos/issues/1230), [#1233](https://github.com/yegor256/cactoos/issues/1233), [#1291](https://github.com/yegor256/cactoos/issues/1291).
