### ISSUE TITLE
Delete And(Proc, ...) and introduce ForEach(Proc, ...)

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#1226]
The `And` class has a constructor taking a `Proc` and behaving in:
- a specific manner: it's not about a logical and
- and an obscure manner: if you pass a lambda that returns `true` you can get an unexpected behaviour thinking you are getting the `Proc` one while you get the `Scalar` one

This makes bugs happens, such as #1212. 

I think we should:
- just delete it to avoid problems
- introduce a class `ForEach(Proc, Iterable)` that implements `Proc` if one wants to execute something on all elements of an `Iterable`.

See also https://github.com/yegor256/cactoos/pull/1215#discussion_r341816341 for a discussion on this.

**Comment by paulodamaso** [comment]
@victornoel This bug shows us that `And` is bloated with more than one behavior. But if we are removing this behavior from `And`, we should provide it somewhere else.

**Comment by paulodamaso** [comment]
@yegor256 What do you think about this? How about leaving `And` just for logical conjunctions and implement another class for `foreach` behavior?

**Comment by victornoel** [comment]
@paulodamaso I believe `Iterable` already introduces the behaviour of `forEach`: indeed it is its "raison d'être" :)

**Comment by paulodamaso** [comment]
@victornoel I'm talking about an declarative way of iterating through the collection, just like `And(Proc, Iterable)` behaves

**Comment by victornoel** [comment]
@paulodamaso I understand, here is my thinking:
1. `foreach` behaviour is a procedural behaviour
2. declarative abstractions exists to be composed (if not you don't need an abstraction)
3. `Proc` is the abstraction for composing procedural behaviour
4. `() -> iterable.forEach(xxx)` is an instance of `Proc` structurally

So the only thing we can do is introduce a `ForEach` class that implements `Proc` and that takes an `Iterable` and a `Proc` and call `iterable.forEach(proc::exec)`.

Why not, but is it really necessary?

**Comment by paulodamaso** [comment]
@victornoel With this, we could remove the side effect from `And` and keep the declarative `forEach` construct in cactoos

**Comment by victornoel** [comment]
@paulodamaso by "with this", do you mean "introducing `ForEach` class"?

If yes I think it's answering the original needs in this ticket, I can update the description if you want.

**Comment by paulodamaso** [comment]
@victornoel Yes, I think that we should implement something like you proposed

**Comment by victornoel** [comment]
@paulodamaso I've updated the description

**Comment by paulodamaso** [comment]
@victornoel Thank you

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/1226#issuecomment-561937505))

@paulodamaso Job [#1226](https://github.com/yegor256/cactoos/issues/1226) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
The job [#1226](https://github.com/yegor256/cactoos/issues/1226) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/C63314D6Z/22bc3d0d-9684-4932-9045-2f63ee22a036); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by yegor256** [comment]
@paulodamaso yes, I agree, let's create `Foreach` class.

**Comment by yegor256** [comment]
@paulodamaso but I think it should just be a wrapper for `And`

**Comment by victornoel** [comment]
@yegor256 but do we agree we should still remove the `Proc` based constructor from `And`? It's too ambiguous to use I think.

**Comment by yegor256** [comment]
@victornoel yes, I agree to remove

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/1226#issuecomment-569341915))

@paulodamaso Job [#1226](https://github.com/yegor256/cactoos/issues/1226) is already in scope

**Comment by 0crat** [comment]
The job [#1226](https://github.com/yegor256/cactoos/issues/1226) assigned to @roman-kuvaldin[/z](https://www.0crat.com/u/roman-kuvaldin), here is [why](https://www.0crat.com/footprint/C63314D6Z/56afd640-a8a3-455b-bd8b-5ad0ed2f25c6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The architect of the project has changed; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is not at this role anymore; @victornoel[/z](https://www.0crat.com/u/victornoel) is the architect now

**Comment by victornoel** [comment]
@ryoku thank you for the PR

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1226` is not assigned, can't get performer
