### ISSUE TITLE
package-info.java:29-34: The following list...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1233]
The puzzle `1230-147999cb` from #1230 has to be resolved: 

https://github.com/yegor256/cactoos/blob/9a4929cf2f8e64eb6a56ae25a31b781894f170bc/src/main/java/org/cactoos/list/package-info.java#L29-L34

The puzzle was created by @fanifieiev on 11-Nov-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1233](https://github.com/yegor256/cactoos/issues/1233) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1233](https://github.com/yegor256/cactoos/issues/1233) assigned to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar), here is [why](https://www.0crat.com/footprint/C63314D6Z/c847dc65-4211-4308-92a9-7c32a493fe30); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by mohamednizar** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/yegor256/cactoos/issues/1233#issuecomment-555567000))

@mohamednizar The impediment for [#1233](https://github.com/yegor256/cactoos/issues/1233) was registered successfully by @mohamednizar[/z](https://www.0crat.com/u/mohamednizar)

**Comment by 0pdd** [comment]
The puzzle `1230-147999cb` has disappeared from the source code, that's why I closed this issue.

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @mohamednizar[/z](https://www.0crat.com/u/mohamednizar), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar)
