### ISSUE TITLE
HeadOf to show only first N bytes of an Input stream

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#1239]
Let's implement `HeadOf` which will show only first N bytes of an Input stream.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/1239#issuecomment-556869606))

@paulodamaso Job [#1239](https://github.com/yegor256/cactoos/issues/1239) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
The job [#1239](https://github.com/yegor256/cactoos/issues/1239) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/b78f1062-29d1-45f0-b1b0-27cfe6d4bf59); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@fabriciofx @paulodamaso would that be an implementation of `Bytes` or of `Input`?

**Comment by victornoel** [comment]
@0crat wait for details

**Comment by fabriciofx** [comment]
@victornoel `Input`.

**Comment by 0crat** [comment]
> @0crat wait for details ([here](https://github.com/yegor256/cactoos/issues/1239#issuecomment-557902693))

@victornoel The impediment for [#1239](https://github.com/yegor256/cactoos/issues/1239) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@fabriciofx you can use [HeadInput](https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/io/HeadInput.java) for that, no?

**Comment by victornoel** [comment]
@fabriciofx ping?

**Comment by victornoel** [comment]
@fabriciofx ping :)

**Comment by victornoel** [comment]
@fabriciofx ?
@paulodamaso I think this issue is not needed, WDYT? or should I renamed `HeadInput` into `HeadOf` maybe at least?

**Comment by paulodamaso** [comment]
@victornoel I think you could make `HeadInput` into `HeadOf`

**Comment by victornoel** [comment]
@fabriciofx see #1278

**Comment by victornoel** [comment]
@fabriciofx you can close the issue now, the PR has been merged :)

**Comment by victornoel** [comment]
@paulodamaso could you close the issue? The reporter does not seem to answer. Thx

**Comment by paulodamaso** [comment]
@victornoel Thank you !

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
