### ISSUE TITLE
`org.cactoos.scalar.Equals` is confusing, its name is intended to test equality, but in reality it tests the comparison 

### ISSUE THREAD

**Issue by fanifieiev** [yegor256/cactoos#1243]
`org.cactoos.scalar.Equals` scalar's name is intended to test equality, but it tests the comparison.
I suggest to rename this class and use the 'Equals' name for another equality class.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by fanifieiev** [comment]
@paulodamaso Closing the issue as the implementation is fair enough

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1243` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
