### ISSUE TITLE
Unique

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#1246]
Is it possible to leave only unique elements in a collection/iterable/list? I can't find this functionality in Cactoos. Would be great to add it or document in README, if it exists.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@yegor256 This behavior is provided by the `SetOf` decorator, but the documentation in README is missing.

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/1246#issuecomment-558161439))

@paulodamaso Job [#1246](https://github.com/yegor256/cactoos/issues/1246) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#1246](https://github.com/yegor256/cactoos/issues/1246) assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/C63314D6Z/98e9d93e-788f-4c3b-b263-9420509c5f77); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by fanifieiev** [comment]
@sereshqua Is it up to @yegor256 to close this issue?

**Comment by sereshqua** [comment]
@fanifieiev correct

**Comment by fanifieiev** [comment]
@yegor256  please have a look at the completed work.

**Comment by fanifieiev** [comment]
@0crat wait for merge

**Comment by 0crat** [comment]
> @0crat wait for merge ([here](https://github.com/yegor256/cactoos/issues/1246#issuecomment-562318968))

@fanifieiev The impediment for [#1246](https://github.com/yegor256/cactoos/issues/1246) was registered successfully by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Comment by fanifieiev** [comment]
@paulodamaso I think it may take long time for Yegor to have a look.
Is there any way for you take the decision for merging???

**Comment by paulodamaso** [comment]
@fanifieiev it was already merged ) I'll close it

**Comment by fanifieiev** [comment]
@paulodamaso should it not be reviewed by qa first?

**Comment by fanifieiev** [comment]
> @paulodamaso should it not be reviewed by qa first?

@paulodamaso ignore the above message. It is fine.

**Comment by fanifieiev** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1246#issuecomment-562405535))

@fanifieiev This is what I know about this job in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1246](https://github.com/yegor256/cactoos/issues/1246) is [in scope](http://www.zerocracy.com/policy.html#14) for 11days
  * The role is `DEV`
  * The job is assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev) for [11days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231246%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#1246](https://github.com/yegor256/cactoos/issues/1246) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
