### ISSUE TITLE
Package list decorators should not wrap the list as unmodifiable

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#1248]
Most of the decorators of `List` as well as `ListOf` in the `list` package wraps the constructed list with `Collections.unmodifiableList`.

I think they should not be unmodifiable anymore because now one can compose those decorators with `Immutable` for this only when desired.

See also https://github.com/yegor256/cactoos/issues/1236#issuecomment-553560425 for a similar discussion but with `collection`.

(edited for clarification)

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by fanifieiev** [comment]
@victornoel Similar issue is already registered [here](https://github.com/yegor256/cactoos/issues/1221).
Please have a look and if does not fit your requirement then ignore my message.

**Comment by victornoel** [comment]
@fanifieiev this is not the same thing, the issue you are referecing is about using `Immutable`, I'm proposing NOT to use it at all in most implementation of the `list` and `collection` immutable.

Thanks for the feedback, I didn't realise my request was ambiguous, I will edit the description.

**Comment by victornoel** [comment]
@fanifieiev for the record, here are some comment from @paulodamaso that goes in the same direction as the proposal in the description of this issue: https://github.com/yegor256/cactoos/issues/1242#issuecomment-558174970

**Comment by victornoel** [comment]
@paulodamaso actually, this is already covered by #1233

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1248` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
