### ISSUE TITLE
`org.cactoos.text.Split` should support limit parameter similar to `String.split(String regexp, int limit)`

### ISSUE THREAD

**Issue by fanifieiev** [yegor256/cactoos#1251]
There are several usages of `String.split(regexp, limit)` in [Takes ](https://github.com/yegor256/takes) project and would be great to replace those with [Split](https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/text/Split.java), but [Split](https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/text/Split.java) does not support `limit`.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/1251#issuecomment-560958396))

@paulodamaso Job [#1251](https://github.com/yegor256/cactoos/issues/1251) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Comment by 0crat** [comment]
The job [#1251](https://github.com/yegor256/cactoos/issues/1251) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/4e503ec6-94cb-4c2b-bccc-fd0593e7709d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #1263 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #1263 to be merged ([here](https://github.com/yegor256/cactoos/issues/1251#issuecomment-568184730))

@victornoel The impediment for [#1251](https://github.com/yegor256/cactoos/issues/1251) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@fanifieiev you can close the issue now, the PR has been merged

**Comment by victornoel** [comment]
@fanifieiev oh wait sorry, it hasn't yet ^^

**Comment by victornoel** [comment]
@fanifieiev this time it is good, the PR has been merged :)

**Comment by fanifieiev** [comment]
@victornoel thanks

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
