### ISSUE TITLE
CollectionOf should be deleted

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#1252]
In the Java `Collection` hierarchy, `Collection` is not a concrete class.

I believe it makes no sense to have a class `CollectionOf`, its behaviour is actually just a duplicate of `ListOf` in practice.

I propose we simply delete it and let user choose a concrete implementation via `ListOf`, `SetOf` or other collections if there are.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@victornoel makes sense.

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/1252#issuecomment-560958621))

@paulodamaso Job [#1252](https://github.com/yegor256/cactoos/issues/1252) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
The job [#1252](https://github.com/yegor256/cactoos/issues/1252) assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/C63314D6Z/574b0a0f-4d7f-441b-b095-33be6d85ab03); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by fanifieiev** [comment]
@paulodamaso, @victornoel 
I think this class [CollectionOf](https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/collection/CollectionOf.java) should be marked as deprecated for a while until [Cactoos-Matchers](https://github.com/llorllale/cactoos-matchers) project removes it from usage within this issue [148](https://github.com/llorllale/cactoos-matchers/issues/148)
By removing the `CollectionOf` class right now the build/tests fail as can be seen [here](https://travis-ci.org/yegor256/cactoos/builds/620429915?utm_source=github_status&utm_medium=notification).

**Comment by victornoel** [comment]
@fanifieiev indeed, good point

**Comment by paulodamaso** [comment]
@fanifieiev We're using version `0.41` in `cactoos-matchers`, so changing `cactoos` master branch should not mess things there. That's why I've chosen to first fix this on `cacttos` and then update `cactoos-matchers`.

Also, the tests fail because they use the `Collection` implementation, which has been removed. These tests should be fixed too. Actually, I think that the PR for this issue should start with the removal of the `Collection` things from all code and tests before we try to delete the files.

**Comment by fanifieiev** [comment]
> @fanifieiev We're using version `0.41` in `cactoos-matchers`, so changing `cactoos` master branch should not mess things there. That's why I've chosen to first fix this on `cacttos` and then update `cactoos-matchers`.
> 
> Also, the tests fail because they use the `Collection` implementation, which has been removed. These tests should be fixed too. Actually, I think that the PR for this issue should start with the removal of the `Collection` things from all code and tests before we try to delete the files.

@paulodamaso If I remove the `CollectionOf` from Cactoos then build fails on `Travis`([details](https://travis-ci.org/yegor256/cactoos/builds/620429915?utm_source=github_status&utm_medium=notification) here). It actually builds because Cactoos-matcher `HasSize` uses the `CollectionOf`.

**Comment by paulodamaso** [comment]
@fanifieiev So, on top of it all we have a nasty circular dependency between those projects. Let's first remove all `CollectionOf` usage in the tests, then we take cara bout the rest OK?

**Comment by fanifieiev** [comment]
> @fanifieiev So, on top of it all we have a nasty circular dependency between those projects. Let's first remove all `CollectionOf` usage in the tests, then we take cara bout the rest OK?

@paulodamaso I have already removed all usages of `CollectionOf` in `Cactoos`(except its test only, which tests `CollectionOf` just for the sake of test coverage). I just marked them as `@Deprecated`

**Comment by fanifieiev** [comment]
@0crat wiat for #1256 to be merged

**Comment by 0crat** [comment]
> @0crat wiat for #1256 to be merged ([here](https://github.com/yegor256/cactoos/issues/1252#issuecomment-562605789))

@fanifieiev Can't understand "wiat", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by llorllale** [comment]
I'm not strongly for nor against this proposal, but would just like to note that forcing `java.util.List` on users would be against the interface segregation principle.

Also:

> So, on top of it all we have a nasty circular dependency between those projects. 

This was first pointed out by @victornoel. Can anyone quantify the magnitude of the problem?

**Comment by victornoel** [comment]
@llorllale can you elaborate on
> forcing java.util.List on users would be against the interface segregation principle

What do you mean forcing `List`? What does it mean to create a new `Collection` when the raison d'être of `Collection` is to be an abstract super class for all the Java collections?

If you meant that `List` shouldn't be the default used when someone wants a `Collection`, then I agree: this is the problem with the current classes in the `collection` package IMHO: they actually are just `List`-based implementations. Apart for some of the decorators that actually makes sense such as `Synced` or `Immutable` for example.

**Comment by llorllale** [comment]
@victornoel 

> can you elaborate on
> 
> >   forcing java.util.List on users would be against the interface segregation principle

Not much to elaborate on: `java.util.List` is a more expansive set of methods than `java.util.Collection`. A consumer shouldn't be forced to depend on the method set of `List` if all they need is `Collection.

> What does it mean to create a new Collection when the raison d'être of Collection is to be an abstract super class for all the Java collections?

This is plain false. [`java.util.Collection`](https://docs.oracle.com/javase/8/docs/api/java/util/Collection.html) is "the root interface in the collection hierarchy". It is not a class, and it's not mean to be merely an abstract type to be extended by subtypes.

> If you meant that List shouldn't be the default used when someone wants a Collection, then I agree

We're in agreement, although I'd like to point out again that I'm not strongly arguing one way or the other.

>  this is the problem with the current classes in the collection package IMHO: they actually are just List-based implementations.

This point does not follow from the previous: no `List` are being exported from the `collection` package. Their implementation should generally not matter at all.

**Comment by victornoel** [comment]
> This is plain false. `java.util.Collection` is "the root interface in the collection hierarchy". It is not a class, and it's not mean to be merely an abstract type to be extended by subtypes.

Let's not be exaggerate ^^ yes, it's not a class, it's an interface, this doesn't change the bottom of what I'm saying. Let me cite the javadoc to clarify what I meant:
>  The JDK does not provide any direct implementations of this interface: it provides implementations of more specific subinterfaces like Set and List. This interface is typically used to pass collections around and manipulate them where maximum generality is desired. 

That's all I meant, I believe it's better to respect the whole precepts of the domain we are trying to fit with. I get your point that yes, you can get a collection without knowing if it's a list or a set, but... when you create it: what is it that you are creating? a list or a set?

I believe it's better to make that decision clearly instead of relying on implicit. Today `CollectionOf` is implemented with a list, tomorrow it's implemented with a set, and your program does not work anymore.

**Comment by fanifieiev** [comment]
@victornoel This issue has been completed, [PR ](https://github.com/yegor256/cactoos/pull/1256)has been merged. Please take the action.

**Comment by llorllale** [comment]
> I believe it's better to make that decision clearly instead of relying on implicit. Today `CollectionOf` is implemented with a list, tomorrow it's implemented with a set, and your program does not work anymore.

Point taken.

**Comment by llorllale** [comment]
With the above said, what I'm *really* interested in is the following:

> This was first pointed out by @victornoel. Can anyone quantify the magnitude of the problem?

**Comment by fanifieiev** [comment]
@victornoel Please take the action. This task has been finalized, we need you close the issue.

**Comment by victornoel** [comment]
> @victornoel This issue has been completed, [PR ](https://github.com/yegor256/cactoos/pull/1256)has been merged. Please take the action.

@fanifieiev sorry for the delay, I was away. For the record, if you can, please tell issue reporter as soon as the PR is merged if you want the issue closed fast, I don't follow each and every PR related to issues I opened personally.

**Comment by 0crat** [comment]
The job [#1252](https://github.com/yegor256/cactoos/issues/1252) is now out of scope

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@llorllale & @victornoel please make sure you start all your messages with the name of the users they are related to, see: [1](https://github.com/yegor256/cactoos/issues/1252#issuecomment-562970357), [2](https://github.com/yegor256/cactoos/issues/1252#issuecomment-565742830), [3](https://github.com/yegor256/cactoos/issues/1252#issuecomment-569529731), [4](https://github.com/yegor256/cactoos/issues/1252#issuecomment-569529988)

**Comment by victornoel** [comment]
@sereshqua good points, thanks for the reminder

**Comment by llorllale** [comment]
@sereshqua fixed mine

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
