### ISSUE TITLE
list.Joined is uselessly copying data instead of being lazy

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#1254]
I believe `list.Joined` could be implemented by storing the underlying `List`s and delegating to them in each of the methods of `List`.

This would in particular be done by storing as a state of `Joined` an ordered collection (i.e., a list) of the underlying lists and computing the corresponding indexes of the elements dynamically.

There would be the need to introduce maybe some implementations for the iterators to do the same.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@victornoel Let's first decide about cactoos lists fate in https://github.com/yegor256/cactoos/issues/1242 right?

**Comment by victornoel** [comment]
@0crat in

**Comment by baudoliver7** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1254#issuecomment-772080756))

@baudoliver7 This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1254](https://github.com/yegor256/cactoos/issues/1254) is [in scope](http://www.zerocracy.com/policy.html#14) for 7mon
  * The role is `DEV`
  * The job is assigned to @baudoliver7[/z](https://www.0crat.com/u/baudoliver7) for [2days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @victornoel[/z](https://www.0crat.com/u/victornoel): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231254%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by baudoliver7** [comment]
@victornoel I dont catch very well what you mean. Could you give me more explanations ?

**Comment by victornoel** [comment]
@baudoliver7 currently, when you call the constructor of `list.Joined`, it will build a new list by copying the arguments. Instead, we should implement the `List` interface (and most certainly `ListIterator`) to wrap the lists passed as arguments and delegate to them as if they were one list.

**Comment by victornoel** [comment]
@baudoliver7 thx

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@victornoel 2 puzzles [#1561](https://github.com/yegor256/cactoos/issues/1561), [#1562](https://github.com/yegor256/cactoos/issues/1562) are still not solved.

**Comment by 0pdd** [comment]
@victornoel 2 puzzles [#unknown](), [#unknown]() are still not solved.
