### ISSUE TITLE
org.cactoos.text.Joined is missing extra constructor

### ISSUE THREAD

**Issue by fanifieiev** [yegor256/cactoos#1258]
I would like to use `org.cactoos.text.Joined` within a constructor, that would except delimiter as String and values as `org.cactoos.text.Text` types.

There is a constructor:
```
public Joined(final Text delimit, final Text... txts) {..}
```

but I need extra one:
```
public Joined(final String delimit, final Text... txts) {..}
```

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Comment by paulodamaso** [comment]
@fanifieiev Why don't use
```
new Joined(new TextOf(delimit), txts) 
```
for this?

**Comment by fanifieiev** [comment]
> @fanifieiev Why don't use
> 
> ```
> new Joined(new TextOf(delimit), txts) 
> ```
> 
> for this?

@paulodamaso Because sometime you just have `String `value and you need to wrap that into `Text ` just to match the existing constructor.
Please take a look at: [PaddedStart](https://github.com/yegor256/cactoos/blob/cdf2dec4f1f93de6dd9d5fb295fdf152c6786f52/src/main/java/org/cactoos/text/PaddedStart.java#L49)

I would actually create more constructors:
So, delimiter can be of type `String `or `Text `. For each of them it is nice to have all the combinations with `Iterable<String>`, `Iterable<Text>`, `String[]`, `Text[]`. That would make 8 constructors in total.

For now we have the following constructors in [Joined](https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/text/Joined.java):
 

- (**String** delimit, **String**... strs)
-  (**String** delimit, **Iterable**< String> strs)
-  (**Text** delimit, **Text**... txts)
-  (**Text** delimit, **Iterable**<? extends Text> txts)

I would add 4 more constructors:

- (**String** delimit, **Text**... txts)
- (**String** delimit, **Iterable**<? extends Text> strs)
- (**Text** delimit, **String**... txts)
- (**Text** delimit, **Iterable**< String> txts)

**Comment by paulodamaso** [comment]
@fanifieiev I understand your point. But don't you think that it will allow us to have two classes for representing a sequence of characters in `cactoos`: `Text` and `String`? I think it is very strange, like, if we put `String` constructors in all of our `Text` decorators having a `Text` interface will be of no meaning, since we will have no reason to use it in favor of `String`.

My point is that maybe instead of adding `String` constructor to our `Text` decorators we should actually work in the opposite way and remove all `String` from these decorators and force that `cactoos` consumers use only `Text`, which is our official way of representing it.

Does it make any sense?

**Comment by fanifieiev** [comment]
> @fanifieiev I understand your point. But don't you think that it will allow us to have two classes for representing a sequence of characters in `cactoos`: `Text` and `String`? I think it is very strange, like, if we put `String` constructors in all of our `Text` decorators having a `Text` interface will be of no meaning, since we will have no reason to use it in favor of `String`.
> 
> My point is that maybe instead of adding `String` constructor to our `Text` decorators we should actually work in the opposite way and remove all `String` from these decorators and force that `cactoos` consumers use only `Text`, which is our official way of representing a `String`.
> 
> Does it make any sense?

@paulodamaso Well, your point  makes sense, but it raises another issue: Do we need to replace `String `with `Text` in all occurences of `Cactoos `primitives? 
It does not force us to use `String `constructors in all of our `Text `decorators.
I would then rephrase myself: I would just leave the following constructors only:

- (**Text** delimit, **Iterable< Text>** txts)
- (**String** delimit, **Iterable< Text>** txts)

Those ones with varargs are error prone:
- (**Text** delimit, **Text**... txts)
- (**String** delimit, **String**... strs)
because if you pass one Text only in the following way, it does not become joined(logically):
`new Joined(",", new TextOf("Hello)) `// it will still be "Helllo"
or
`new Joined(new TextOf(","), new TextOf("Hello))` // it will still be "Helllo"

**Comment by 0crat** [comment]
The job [#1258](https://github.com/yegor256/cactoos/issues/1258) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/d9085e7c-0172-4d33-aa17-51032d084d61); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1258#issuecomment-587115455))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#1258](https://github.com/yegor256/cactoos/issues/1258), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1258#issuecomment-587115455))

@victornoel Job refused in 0 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#1258](https://github.com/yegor256/cactoos/issues/1258) assigned to @dgarus[/z](https://www.0crat.com/u/dgarus), here is [why](https://www.0crat.com/footprint/C63314D6Z/9e39c0c5-8843-464b-9b62-5dfbeda2230b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by dgarus** [comment]
@fanifieiev Hello!
Could you please close the ticket?
Thx
