### ISSUE TITLE
SetOf with custom comparator

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#1259]
Would be great to have an ability to use a custom `Comparator` with `SetOf`.

See: https://stackoverflow.com/questions/14880450/java-hashset-with-a-custom-equality-criteria

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#1259](https://github.com/yegor256/cactoos/issues/1259) assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/C63314D6Z/0ecfb1d0-d429-4a87-9708-dc514d8f723c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by fanifieiev** [comment]
@yegor256 @paulodamaso Currently `SetOf` is based on the `HashSet`. So the responsibility of `SetOf` is to provide just a hash-based set with no ordering. 
So:
1) By means of adding `Comparator ` we put more responsibility to the `SetOf`(now it needs to take care of ordering as well).
2) For now `SetOf  ` is mutable and we probably need to make it immutable so that it can take care of ordering when you add an element, so we will need to change the implementation to use `TreeSet` which in some cases might be redundant(TreeSet performance is poor compared to HashSet).
3) Why not just leave it as it is and use `new Sorted(new SetOf(...))` when you need ordering ?
WDYT ?????

**Comment by paulodamaso** [comment]
@yegor256 please take a look at @fanifieiev arguments

**Comment by fanifieiev** [comment]
> @yegor256 please take a look at @fanifieiev arguments. My opinion about them:
> 
> 1. I agree. `SetOf` implements `Set`, not `SortedSet`. It does not seems right add this sorting responsibility to it
> 2. Putting this comparator in `SetOf` will force us to use a lousy code to choose which collection we will use to base out `Set` on: `TreeSet` or `HashSet`, and it would be prone to performance issues as stated
> 3. I think that this snippet would make using sorted sets too verbose. But it seems ok taking into account how we cmpose objetcs and decorate them in EO
> 
> I think that we could create a `Sorted` decorator for `org.cactoos.set` package, and this decorator would be implemeted using a `TreeSet`. And for making it not so verbose, we could create a class called `SortedSetOf` which encapsulates this logic.
> 
> How about that?

@paulodamaso @yegor256 
So, decided to give a try with a `Sorted` set.
PR is here.
Feel free to argue.

**Comment by fanifieiev** [comment]
@yegor256 The pull request for this issue has bee n merged.
Please review the work done and close the issue if applicable.

**Comment by fanifieiev** [comment]
@0crat wait for @yegor256 to close

**Comment by 0crat** [comment]
> @0crat wait for @yegor256 to close ([here](https://github.com/yegor256/cactoos/issues/1259#issuecomment-584375189))

@fanifieiev The impediment for [#1259](https://github.com/yegor256/cactoos/issues/1259) was registered successfully by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Comment by yegor256** [comment]
@fanifieiev thanks!

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)
