### ISSUE TITLE
CollectionOf.java:53-57: Remove this deprecated class...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1261]
The puzzle `1116-ec0ce41a` from #1116 has to be resolved: 

https://github.com/yegor256/cactoos/blob/542dc574730f6b3391a3714cfaca54a00a9f4ae6/src/main/java/org/cactoos/collection/CollectionOf.java#L53-L57

The puzzle was created by rultor on 17-Dec-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1261](https://github.com/yegor256/cactoos/issues/1261) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1261](https://github.com/yegor256/cactoos/issues/1261) assigned to @golyalpha[/z](https://www.0crat.com/u/golyalpha), here is [why](https://www.0crat.com/footprint/C63314D6Z/31a764a5-e624-4b65-a759-c04316c5ceb1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1261` already assigned to @golyalpha, can't assign to @golyalpha

**Comment by victornoel** [comment]
@0pdd for the record, CollectionOf has been fully removed from cactoos-matcher, it seems safe to remove it from cactoos now as well as bump cactoos-matchers to the latest version.

**Comment by 0pdd** [comment]
> @0pdd for the record, CollectionOf has been fully removed from cactoos-matcher, it seems safe to rem...

  I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by 0crat** [comment]
The architect of the project has changed; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is not at this role anymore; @victornoel[/z](https://www.0crat.com/u/victornoel) is the architect now

**Comment by victornoel** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#1261](https://github.com/yegor256/cactoos/issues/1261) assigned to @lavinj87[/z](https://www.0crat.com/u/lavinj87), here is [why](https://www.0crat.com/footprint/C63314D6Z/f22c3c9d-2c8b-4e4a-9410-7b6236b62a0d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1261#issuecomment-658882034))

@victornoel The user @lavinj87[/z](https://www.0crat.com/u/lavinj87) resigned from [#1261](https://github.com/yegor256/cactoos/issues/1261), please stop working. Reason for job resignation: Order was cancelled

**Comment by marceloamadeu** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1261#issuecomment-680949521))

@marceloamadeu The user @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) resigned from [#1261](https://github.com/yegor256/cactoos/issues/1261), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#1261](https://github.com/yegor256/cactoos/issues/1261) assigned to @andreoss[/z](https://www.0crat.com/u/andreoss), here is [why](https://www.0crat.com/footprint/C63314D6Z/50bb1626-4eba-451e-a8a6-3f9029e53ab1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by andreoss** [comment]
@0crat wait for https://github.com/llorllale/cactoos-matchers/issues/167

**Comment by 0pdd** [comment]
The puzzle `1116-ec0ce41a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 37 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
