### ISSUE TITLE
StartsWith for Text

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#1265]
Let's implements a `StartsWith` class which check if a `String` starts with another string (the behaviour is similar to `String.startsWith()` method.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/1265#issuecomment-569343374))

@paulodamaso Job [#1265](https://github.com/yegor256/cactoos/issues/1265) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
The job [#1265](https://github.com/yegor256/cactoos/issues/1265) assigned to @iakunin[/z](https://www.0crat.com/u/iakunin), here is [why](https://www.0crat.com/footprint/C63314D6Z/80f98105-1270-4d56-98fc-ba84eebbbfd8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by iakunin** [comment]
@0crat wait for https://github.com/yegor256/cactoos/pull/1268 to be merged

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/yegor256/cactoos/pull/1268 to be merged ([here](https://github.com/yegor256/cactoos/issues/1265#issuecomment-569673842))

@iakunin The impediment for [#1265](https://github.com/yegor256/cactoos/issues/1265) was registered successfully by @iakunin[/z](https://www.0crat.com/u/iakunin)

**Comment by paulodamaso** [comment]
@iakunin thanks

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @iakunin[/z](https://www.0crat.com/u/iakunin), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#1265](https://github.com/yegor256/cactoos/issues/1265) is not in the agenda of @iakunin[/z](https://www.0crat.com/u/iakunin), can't inspect

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Job [#1265](https://github.com/yegor256/cactoos/issues/1265) is not in the agenda of @iakunin[/z](https://www.0crat.com/u/iakunin), can't retrieve data and time of add

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @iakunin[/z](https://www.0crat.com/u/iakunin)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
