### ISSUE TITLE
EndsWith for Text

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#1266]
Let's implements a `EndsWith` class which check if a `String` ends with another string (the behaviour is similar to `String.endsWith()` method.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/1266#issuecomment-569343411))

@paulodamaso Job [#1266](https://github.com/yegor256/cactoos/issues/1266) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
The job [#1266](https://github.com/yegor256/cactoos/issues/1266) assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/C63314D6Z/8b2b697b-cc4b-4ef7-b47d-1479c66ae0ac); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by fanifieiev** [comment]
@0crat wait for #1269 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #1269 to be merged ([here](https://github.com/yegor256/cactoos/issues/1266#issuecomment-569811691))

@fanifieiev The impediment for [#1266](https://github.com/yegor256/cactoos/issues/1266) was registered successfully by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Comment by fanifieiev** [comment]
@fabriciofx please review

**Comment by paulodamaso** [comment]
@fanifieiev thanks!

**Comment by fanifieiev** [comment]
> @fanifieiev thanks!

@paulodamaso Thank you too

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
