### ISSUE TITLE
Collection NoNulls.addAll internally calls removeAll

### ISSUE THREAD

**Issue by strattonw** [yegor256/cactoos#1274]
From the snippet below, the `addAll` calls `removeAll` on the internal collection
https://github.com/yegor256/cactoos/blob/b11523609fc3b7ed1ce14b8e9c84aafad7c5f5aa/src/main/java/org/cactoos/collection/NoNulls.java#L140-L143

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
@strattonw[/z](https://www.0crat.com/u/strattonw) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by fanifieiev** [comment]
@strattonw Please close this issue as it was originated by you.

**Comment by 0crat** [comment]
This job is not in scope
