### ISSUE TITLE
Incorrect usage of the fallback function in the FirstOf class

### ISSUE THREAD

**Issue by riccisi** [yegor256/cactoos#1276]
After updating to the last version of Cactoos (from 0.36 to 0.43), the following code no longer works:
```java
new FirstOf<>(
       element -> element.id().equals(id),
       elements,
       () -> {
           throw new IllegalArgumentException(
               String.format("Unable to found element with id %s", id)
           );
       }
);
```
Because the Func is evaluated in imperative way:
```java
public T value() throws Exception {
    return new ItemAt<>(
        0,
        this.fallback.value(),
        new Filtered<>(this.condition, this.source)
     ).value();
 }
```
instead it should be like this:
```java
public T value() throws Exception {
    return new ItemAt<>(
        0,
        this.fallback,
        new Filtered<>(this.condition, this.source)
     ).value();
 }
```
as ItemAt accepts and evaluates a Func at the correct time (when it does not find the element)

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
@riccisi[/z](https://www.0crat.com/u/riccisi) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/1276#issuecomment-580248490))

@paulodamaso Thanks for your contribution, @riccisi[/z](https://www.0crat.com/u/riccisi)! If you would be a member of [the project](https://www.0crat.com/p/C63314D6Z), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
The job [#1276](https://github.com/yegor256/cactoos/issues/1276) assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/C63314D6Z/df4111b8-33c5-4081-8aa3-d017e8494b9e); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by fanifieiev** [comment]
@riccisi The issue has been fixed and the PR has been merged.
Please have a look and close the issue accordingly.

**Comment by fanifieiev** [comment]
@0crat wait for the issue to be closed

**Comment by 0crat** [comment]
> @0crat wait for the issue to be closed ([here](https://github.com/yegor256/cactoos/issues/1276#issuecomment-587775141))

@fanifieiev The impediment for [#1276](https://github.com/yegor256/cactoos/issues/1276) was registered successfully by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
