### ISSUE TITLE
TimedTest.java:262-267: Create RepeatedProc decorator in...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1277]
The puzzle `1000-1e922fa0` from #1000 has to be resolved: 

https://github.com/yegor256/cactoos/blob/506a5749c7583499a3fca0867cb7c2a7a4f4f64e/src/test/java/org/cactoos/experimental/TimedTest.java#L262-L267

The puzzle was created by iakunin on 31-Jan-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
The puzzle `1000-1e922fa0` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1406](https://github.com/yegor256/cactoos/issues/1406), [#1407](https://github.com/yegor256/cactoos/issues/1407) are still not solved.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1277` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1406](https://github.com/yegor256/cactoos/issues/1406) is still not solved; solved: [#1407](https://github.com/yegor256/cactoos/issues/1407).

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#1406](https://github.com/yegor256/cactoos/issues/1406), [#1407](https://github.com/yegor256/cactoos/issues/1407).
