### ISSUE TITLE
UncheckedText should implement toString()

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#1280]
`UncheckedText` should implement `toString()`.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by victornoel** [comment]
@paulodamaso because lots of code relies on the fact that `toString()` returns something meaningful and in the case of `UncheckedText`, we get a useless object hash coming from the default implementation in `Object.toString()`.

Other `Text` implementation have `toString()` implemented. It especially makes sense for something called text by the way…

**Comment by fanifieiev** [comment]
> @paulodamaso because lots of code relies on the fact that `toString()` returns something meaningful and in the case of `UncheckedText`, we get a useless object hash coming from the default implementation in `Object.toString()`.
> 
> Other `Text` implementation have `toString()` implemented. It especially makes sense for something called text by the way…

@paulodamaso I completely agree with @victornoel

**Comment by fanifieiev** [comment]
@victornoel @paulodamaso I would better force all `Text `implementations extend `TextEnvelope`, which already supports `toString()`.

**Comment by victornoel** [comment]
> I would better force all Text implementations extend TextEnvelope, which already supports toString().

@fanifieiev this is an implementation detail, in the end what matters is that all implementations respect the contract.

But I don't like this approach, it really depends on the `Text` being implemented, sometimes it makes sense to use an envelope, when the text is static for example or when it can be expressed in terms of another implementation of `Text`, but sometimes it's better not to. And `UncheckedText` falls in that last category IMHO: it is totally dependent on another text instance, but redefining the `asString()` implementation. Envelopes delegates to the wrapped `Text` on the other hand.

This confusion comes IMHO from the fact that the current `TextEnvelope` implementation, like many of the other envelopes in cactoos are plain wrong (see for example #1185 and other like that).
If `TextEnvelope` takes a `Scalar`, it is NOT an envelope, it's an implementation of `Text` based on a `Scalar`, and making it abstract is a mistake because 1) it promotes (bad) inheritance and 2) it can't be used directly.

I created #1287 to discuss that.

**Comment by victornoel** [comment]
@0crat in

**Comment by victornoel** [comment]
@0crat assign @fabriciofx

**Comment by victornoel** [comment]
@fabriciofx I'm starting to assign manually because if not 0crat always assign latest issues and I would like to advance on those. I hope it's ok with you :) no rush anyway

**Comment by 0crat** [comment]
> @0crat assign @fabriciofx  ([here](https://github.com/yegor256/cactoos/issues/1280#issuecomment-691655684))

@victornoel The job [#1280](https://github.com/yegor256/cactoos/issues/1280) assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C63314D6Z/5dee9d09-cf07-44f8-a5b4-79756c77ea55); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by fabriciofx** [comment]
@victornoel This issue has been merged but it stiil in my agenda. Do you know why?

**Comment by victornoel** [comment]
@fabriciofx it is because you never asked me (the ticket reporter) to close it now that it is solved? :)

**Comment by victornoel** [comment]
@fabriciofx for the record 0crat does not know about PRs when you do a job (because sometimes the job is not about PRs), you have to explicitly ask the reporter to close it. Except if it's 0pdd because it's a bot and detects the puzzle disappearance automatically of course.

**Comment by fabriciofx** [comment]
@victornoel ah, thanks! I thought 0crat closed the issue after merge.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
