### ISSUE TITLE
Closing TempFolder is broken

### ISSUE THREAD

**Issue by piotrkot** [yegor256/cactoos#1284]
I believe when someone creates a temporary folder, it is for some files or directories to put inside.
As least this is why I create such folders.
Now, when you are done, and you close the temporary folder, it is a good idea to delete that folder with all the content inside.

In the current implementation, however, you call `Files.delete(path)` in the `close()` method, which will throw `DirectoryNotEmptyException` whenever the directory is not empty. Of course, removing all the files and directories inside the temporary folder before closing the temporary folder will make it work but I believe a better approach would be to automatically remove all the content inside during its `close()` method.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
@piotrkot[/z](https://www.0crat.com/u/piotrkot) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @piotrkot[/z](https://www.0crat.com/u/piotrkot)

**Comment by 0crat** [comment]
The job [#1284](https://github.com/yegor256/cactoos/issues/1284) assigned to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), here is [why](https://www.0crat.com/footprint/C63314D6Z/bf1c9541-bd28-4c3e-9b97-4b8e66b542ac); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by fanifieiev** [comment]
@piotrkot The issue has been fixed and merged.
Please have a look at close the issue respectively.

**Comment by piotrkot** [comment]
@fanifieiev Thank you.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fanifieiev[/z](https://www.0crat.com/u/fanifieiev), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)
