### ISSUE TITLE
Filtered should support extra constructors accepting Func<X, Scalar<Boolean>>

### ISSUE THREAD

**Issue by fanifieiev** [yegor256/cactoos#1313]
The following Filtered classes should have constructor accepting `Func<X, Scalar<Boolean>>`:

```
- org.cactoos.collection.Filtered
- org.cactoos.iterator.Filtered
- org.cactoos.iterable.Filtered
```

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fanifieiev[/z](https://www.0crat.com/u/fanifieiev)

**Comment by 0crat** [comment]
The job [#1313](https://github.com/yegor256/cactoos/issues/1313) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/a0e62a6a-a235-4641-8666-c2c8601ce0bc); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1313#issuecomment-606126702))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#1313](https://github.com/yegor256/cactoos/issues/1313), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1313#issuecomment-606126702))

@victornoel Job refused in 0 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#1313](https://github.com/yegor256/cactoos/issues/1313) assigned to @englishman[/z](https://www.0crat.com/u/englishman), here is [why](https://www.0crat.com/footprint/C63314D6Z/309f67cd-0eac-40d3-9f49-3ae87937aab0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The architect of the project has changed; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is not at this role anymore; @victornoel[/z](https://www.0crat.com/u/victornoel) is the architect now

**Comment by victornoel** [comment]
@fanifieiev apparently this was solved in #1402, if that's good for you you can close this issue

**Comment by victornoel** [comment]
@fanifieiev I've verified that it was correctly solved, let me close this

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1313` is not assigned, can't get performer
