### ISSUE TITLE
Sorted.java:38-40: This class should also implements...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1325]
The puzzle `1292-c2a188c0` from #1292 has to be resolved: 

https://github.com/yegor256/cactoos/blob/90ff77d9093ebbe29076b977f445f21897c22b75/src/main/java/org/cactoos/set/Sorted.java#L38-L40

The puzzle was created by Victor Noël on 29-Feb-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#1325](https://github.com/yegor256/cactoos/issues/1325) assigned to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), here is [why](https://www.0crat.com/footprint/C63314D6Z/77b74c28-3f53-4193-8213-78eb8d5ca1f2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by vzurauskas** [comment]
@0crat wait for https://github.com/yegor256/cactoos/pull/1329

**Comment by 0pdd** [comment]
The puzzle `1292-c2a188c0` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/cactoos/issues/1325#issuecomment-605949629))

@sereshqua There is no quality review for [#1325](https://github.com/yegor256/cactoos/issues/1325), no performer
