### ISSUE TITLE
Principles violation 

### ISSUE THREAD

**Issue by Guseyn** [yegor256/cactoos#1327]
As it's known from the principles it's prohibited to use getters and setters: https://www.yegor256.com/2014/09/16/getters-and-setters-are-evil.html

But as I see here https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/map/MapEntry.java it's used:

```java
    @Override
    public K getKey() {
        return this.key;
    }

    @Override
    public V getValue() {
        return this.value;
    }
```

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@Guseyn In this case we are implementing a java interface here, `Map.Entry`, which forces us to use these evil names. Is there any proposal on how solving this?

**Comment by Guseyn** [comment]
@paulodamaso Nah, I am just pointing to a weak place(one of many) of your theory that cannot be practically and theoretically implemented. Because, see.. You're using getters here not only because some java interface forces you, but because you cannot do data structures like `List`, `Map`, `Tree` without getters and setters, because... well, they are data structures.  

You can use no "evil" names, but the point is that they are still getters. Or maybe you can create data structures via "elegant objects" that are not supposed to expose internal data outside of them. But it's obviously impossible(or you can surprise me).

Just face the fact that you're lying to people  by saying that you are not using `getters`(https://www.elegantobjects.org/#principles). It's just a lie, why do you do that? Do you really think that people are so stupid and naive? Or maybe you are confused?

Let me explain you something, if you are telling that your library follows principles like `no getters` and you are using them there, it means that you're just not following them, it means that your theory is not practically possible. Of course you're trying to follow your principles, but then you should emphasize such fact, because it's not possible to follow them to full extend.

But again even in the places where your following them, you provide no alternative what so ever. You're still writing procedural code. Because OOP does not allow you to write fully composable code as I explained it here https://guseyn.com/posts/eo-is-wrong?v=1.0.201

**Comment by victornoel** [comment]
@Guseyn I'm going to close this as wontfix

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1327` is not assigned, can't get performer
