### ISSUE TITLE
NumberEnvelope should be named NumberOf

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#1335]
I noticed that `NumberEnvelope` wasn't a real envelope but just a given implementation of `Number` relying on `Scalar`.

I propose the following:
- Rename current `NumberEnvelope` to `NumberOf`
- Introduce `NumberEnvelope` as a real envelope wrapping any  `Number` and delegating all methods including `equals`, `hashCode` and `toString`
- Keep extending `NumberEnvelope` for existing subclasses but delegates to `NumberOf` (or directly to any other `Number` if possible)
- Add the missing methods `equals`, `hashCode` and `toString` to `NumberOf`
  - this can be done as a second step with a `todo` not to do too much things at once

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@victornoel I agree, this will make `Number` implementation tree to be consistent with the other interface in cactoos

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#1335](https://github.com/yegor256/cactoos/issues/1335) assigned to @englishman[/z](https://www.0crat.com/u/englishman), here is [why](https://www.0crat.com/footprint/C63314D6Z/22f13385-5a4d-472e-88ef-4d2307f3c6d0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The architect of the project has changed; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is not at this role anymore; @victornoel[/z](https://www.0crat.com/u/victornoel) is the architect now

**Comment by victornoel** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#1335](https://github.com/yegor256/cactoos/issues/1335) assigned to @lavinj87[/z](https://www.0crat.com/u/lavinj87), here is [why](https://www.0crat.com/footprint/C63314D6Z/49874644-d184-49e1-9a96-d614b0a761e2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1335#issuecomment-658907634))

@victornoel Job `gh:yegor256/cactoos#1335` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1335#issuecomment-658882112))

@victornoel The user @lavinj87[/z](https://www.0crat.com/u/lavinj87) resigned from [#1335](https://github.com/yegor256/cactoos/issues/1335), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#1335](https://github.com/yegor256/cactoos/issues/1335) assigned to @aivinog1[/z](https://www.0crat.com/u/aivinog1), here is [why](https://www.0crat.com/footprint/C63314D6Z/967a9002-d758-4d34-950c-2c31e42158a1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@aivinog1 I see you are new around here, welcome. If you have questions don't hesitate to ask here, there are no incorrect questions :)

And also, if a task seems too much as a starter or you don't want to do it, don't hesitate to simply refuse it with `@0crat refuse`.

If you are inactive for too long (~10 days) on a task, I may remove it from you, so don't hesitate to ask questions :)

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/cactoos/issues/1335#issuecomment-692887242); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by aivinog1** [comment]
@victornoel Hi, thanks! I have a question: what we should do with an existing: `org.cactoos.scalar.NumberOf`? :)

**Comment by victornoel** [comment]
@aivinog1 indeed, I see the situation is worst that what I imagined.

So we should try to have `NumberOf` exposing the same constructors as before, but the internal implementation to be the same as the class `Sealed` (which should then be deleted).

`NumberEnvelope` should be an abstract class extending `Number` (frankly I don't get why the Java std lib made Number a class instead of an interface… so we use it as if it was an interface) and delegating ALL methods to a wrapped `Number`.

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1335#issuecomment-699608716))

@victornoel The user @aivinog1[/z](https://www.0crat.com/u/aivinog1) resigned from [#1335](https://github.com/yegor256/cactoos/issues/1335), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#1335](https://github.com/yegor256/cactoos/issues/1335) assigned to @ruca905[/z](https://www.0crat.com/u/ruca905), here is [why](https://www.0crat.com/footprint/C63314D6Z/421113f2-c4cf-44fb-abae-bf1431b0b25c); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by ruca905** [comment]
@victornoel, Hello, now `NumberOf` and `NumberEnvelope` is very similar. So i can not exactly understand difference. Is it right, that `Numbe Envelope` class wraps
`Number` class and implements all of method of `Number` class .
On the other hand, `NumberOf` is class, which construct `NumberEnvelope` from different types(as `TextOf`) and didnot have to implement all of methods of `Number`.

**Comment by victornoel** [comment]
@ruca905 yes, you analysis is correct. Most of the work here is improving the naming of things, in the end we should have:
- `NumberEnvelope` that only delegates to a wrapped `Number` (similarly to all other envelopes of cactoos)
- `NumberOf` responsible of providing some constructors to define numbers using scalars
  - the current implementation should be transformed to be similar to current `NumberEnvelope`
  - maybe it is not needed to reimplement equals/hashCode/toString if they already are defined in the `Number` super class.
- For all the current subclass of `NumberEnvelope`, instead of passing the scalars to super, it should pass them to a new `NumberOf` itself passed to super

I hope it is more clear.

**Comment by victornoel** [comment]
@ruca905 are you going to be solving this ticket?

**Comment by ruca905** [comment]
It's a pity, I thought that I was removed from this task due to the fact that I did not have time in accordance with the rule of 10 days and the zerocracy policy. I'll post a commit in a few hours.

**Comment by victornoel** [comment]
@ruca905 you can check the list of tasks assigned to you on 0crat.com btw.

**Comment by ruca905** [comment]
@victornoel, I have a problem. `NumberEnvelope` must wrap `Number`, so it should only have one `NumberEnvelope (final Number num)` constructor, but many project classes call `NumberEnvelope (final Scalar <Long> lnm, final Scalar <Integer> inm,
        final Scalar <Float> fnm, final Scalar <Double> dnm)`. Do I need to leave this constructor or create a todo task to remove it?

**Comment by victornoel** [comment]
@ruca905 all those calls to `NumberEnvelope` super constructor taking a `Scalar` should be replaced by passing a new `NumberOf` to the `NumberEnvelope` super constructor.

This is why in the ticket it is proposed that the current code of `NumberEnvelope` be renamed `NumberOf`.

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1335#issuecomment-751454946))

@victornoel The user @ruca905[/z](https://www.0crat.com/u/ruca905) resigned from [#1335](https://github.com/yegor256/cactoos/issues/1335), please stop working. Reason for job resignation: Order was cancelled

**Comment by victornoel** [comment]
@0crat assign me

**Comment by victornoel** [comment]
@0crat wait for llorllale/cactoos-matchers#220 to be fixed first

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1335#issuecomment-858763965))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1335](https://github.com/yegor256/cactoos/issues/1335) is [in scope](http://www.zerocracy.com/policy.html#14) for 11mon
  * The role is `DEV`
  * The job is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel) for [6mon](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job has an [impediment](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @victornoel[/z](https://www.0crat.com/u/victornoel): This user reported the ticket
    * @lavinj87[/z](https://www.0crat.com/u/lavinj87): User was resigned from the ticket
    * @aivinog1[/z](https://www.0crat.com/u/aivinog1): User was resigned from the ticket
    * @ruca905[/z](https://www.0crat.com/u/ruca905): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231335%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0pdd** [comment]
@victornoel the puzzle [#1617](https://github.com/yegor256/cactoos/issues/1617) is still not solved.

**Comment by 0pdd** [comment]
@victornoel the puzzle [#1640](https://github.com/yegor256/cactoos/issues/1640) is still not solved.

**Comment by 0pdd** [comment]
@victornoel the puzzle [#unknown]() is still not solved; solved: [#1640](https://github.com/yegor256/cactoos/issues/1640).
