### ISSUE TITLE
TeeInputFromBytesTest.java:38-41: This test is incorrect....

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1341]
The puzzle `1331-806191f6` from #1331 has to be resolved: 

https://github.com/yegor256/cactoos/blob/3ab952eeb2e7151d0ba4e435c4c12cf7c7eed8bb/src/test/java/org/cactoos/io/TeeInputFromBytesTest.java#L38-L41

The puzzle was created by marceloamadeu on 07-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#1341](https://github.com/yegor256/cactoos/issues/1341) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/03ecb661-abf6-4b6f-9864-9e487067b8d0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1341#issuecomment-613443284))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#1341](https://github.com/yegor256/cactoos/issues/1341), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1341#issuecomment-613443284))

@victornoel Job refused in 18 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#1341](https://github.com/yegor256/cactoos/issues/1341) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/C63314D6Z/7a01e333-8dd9-4200-9857-52231dd16e56); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `1331-806191f6` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1360](https://github.com/yegor256/cactoos/issues/1360) is still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1372](https://github.com/yegor256/cactoos/issues/1372) is still not solved; solved: [#1360](https://github.com/yegor256/cactoos/issues/1360).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1381](https://github.com/yegor256/cactoos/issues/1381) is still not solved; solved: [#1360](https://github.com/yegor256/cactoos/issues/1360), [#1372](https://github.com/yegor256/cactoos/issues/1372).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1392](https://github.com/yegor256/cactoos/issues/1392) is still not solved; solved: [#1360](https://github.com/yegor256/cactoos/issues/1360), [#1372](https://github.com/yegor256/cactoos/issues/1372), [#1381](https://github.com/yegor256/cactoos/issues/1381).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1395](https://github.com/yegor256/cactoos/issues/1395) is still not solved; solved: [#1360](https://github.com/yegor256/cactoos/issues/1360), [#1372](https://github.com/yegor256/cactoos/issues/1372), [#1381](https://github.com/yegor256/cactoos/issues/1381), [#1392](https://github.com/yegor256/cactoos/issues/1392).

**Comment by 0pdd** [comment]
@0pdd all 5 puzzles are solved here: [#1360](https://github.com/yegor256/cactoos/issues/1360), [#1372](https://github.com/yegor256/cactoos/issues/1372), [#1381](https://github.com/yegor256/cactoos/issues/1381), [#1392](https://github.com/yegor256/cactoos/issues/1392), [#1395](https://github.com/yegor256/cactoos/issues/1395).
