### ISSUE TITLE
Release version 0.45

### ISSUE THREAD

**Issue by paulodamaso** [yegor256/cactoos#1346]
Release version 0.45

**Comment by paulodamaso** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/cactoos/issues/1346#issuecomment-618421255))

@paulodamaso The job [#1346](https://github.com/yegor256/cactoos/issues/1346) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C63314D6Z/c8ae9caa-d735-4066-a9d0-f49357ff55df); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by paulodamaso** [comment]
@rultor release tag is `0.44`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.45`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.45`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.45`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.45`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.45`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.45`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.45`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.45`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.45`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.45`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.45`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.45`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.45`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.45`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.45`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.45`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.45`

**Comment by paulodamaso** [comment]
@rultor release tag is `0.46`

**Comment by paulodamaso** [comment]
@0crat out
