### ISSUE TITLE
ScalarOf.java:33-36: Continue implement class ScalarOf...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1349]
The puzzle `1320-62e15acb` from #1320 has to be resolved: 

https://github.com/yegor256/cactoos/blob/1ef744ecf8daef1a50209d88676ff6f0e7ba13eb/src/main/java/org/cactoos/scalar/ScalarOf.java#L33-L36

The puzzle was created by marceloamadeu on 17-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#1349](https://github.com/yegor256/cactoos/issues/1349) assigned to @englishman[/z](https://www.0crat.com/u/englishman), here is [why](https://www.0crat.com/footprint/C63314D6Z/5cf2c872-d17d-42a5-88d1-4aa3cc5b2a82); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by andreoss** [comment]
If implemented this will make `new ScalarOf(() -> value)` syntax ambiguous, and will require explicit cast to either of `Supplier`, `Callable` or `Scalar`.

**Comment by 0crat** [comment]
The architect of the project has changed; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is not at this role anymore; @victornoel[/z](https://www.0crat.com/u/victornoel) is the architect now

**Comment by victornoel** [comment]
@0crat in

**Comment by victornoel** [comment]
@andreoss no, this is not intended, a solution would be to introduce various classes `OfCallable`, `OfSupplier` and `Of` would then take a `Scalar` I suppose.

**Comment by 0crat** [comment]
The job [#1349](https://github.com/yegor256/cactoos/issues/1349) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C63314D6Z/e23c9046-1fd8-4cc6-99b5-4f1fc84f0ac2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by paulodamaso** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1349#issuecomment-657273947))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#1349](https://github.com/yegor256/cactoos/issues/1349), please stop working. Reason for job resignation: Order was cancelled

**Comment by marceloamadeu** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1349#issuecomment-657647004))

@marceloamadeu The user @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) resigned from [#1349](https://github.com/yegor256/cactoos/issues/1349), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1349#issuecomment-657647004))

@marceloamadeu Job refused in 0 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment]
The job [#1349](https://github.com/yegor256/cactoos/issues/1349) assigned to @longstone[/z](https://www.0crat.com/u/longstone), here is [why](https://www.0crat.com/footprint/C63314D6Z/480f12bc-ce48-4e21-b523-f4097df57e89); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
The job [#1349](https://github.com/yegor256/cactoos/issues/1349) assigned to @mazdack[/z](https://www.0crat.com/u/mazdack), here is [why](https://www.0crat.com/footprint/C63314D6Z/169cd03f-c8fe-449e-ac8c-267bd594fd44); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The job [#1349](https://github.com/yegor256/cactoos/issues/1349) assigned to @andreoss[/z](https://www.0crat.com/u/andreoss), here is [why](https://www.0crat.com/footprint/C63314D6Z/1daf8050-d8fe-4ecc-8922-a1a55e805c28); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by andreoss** [comment]
@victornoel 
Why `ScalarOf` should accept `Callable` and `Supplier`?
As a functional interface `Scalar` matches both of them, it will make lambda notation unambiguous and requiring explicit casting.

Can we have `ScalarOfCallable` instead?

**Comment by victornoel** [comment]
@andreoss yes, very good point. The name you propose is good to me, let's go with that.

**Comment by victornoel** [comment]
@andreoss ha, you forgot to remove the todo when you put `ScalarOf` back. Please make another PR.

**Comment by 0pdd** [comment]
The puzzle `1320-62e15acb` has disappeared from the source code, that's why I closed this issue.
