### ISSUE TITLE
iterable.Matched shouldn't create an in-memory list but lazily iterate 

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#1359]
I noticed that `iterable.Matched` is creating a list in memory and then return it as an `Iterator`.

For performance reasons and stick closer to the lazy behavioural contract of `Iterable`, I think we should:
- create `iterator.Matched` that lazily returns the matched elements instead of storing them in a list
- have `iterable.Matched` simply delegate to `iterator.Matched`

This is important for example because `IterableOf.equals` is going (see #1358) to use `Matched` for its behaviour and this would be a bad idea to build the whole `Matched` `Iterable` if we detect at the first element that they are not equals.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by paulodamaso** [comment]
@victornoel Good catch!

**Comment by paulodamaso** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#1359](https://github.com/yegor256/cactoos/issues/1359) assigned to @a-korzhov[/z](https://www.0crat.com/u/a-korzhov), here is [why](https://www.0crat.com/footprint/C63314D6Z/1f00e0fc-eec8-4d8e-a4f0-33145a285481); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by a-korzhov** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1359#issuecomment-622011405))

@a-korzhov The user @a-korzhov[/z](https://www.0crat.com/u/a-korzhov) resigned from [#1359](https://github.com/yegor256/cactoos/issues/1359), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#1359](https://github.com/yegor256/cactoos/issues/1359) assigned to @iiylll[/z](https://www.0crat.com/u/iiylll), here is [why](https://www.0crat.com/footprint/C63314D6Z/63e7c468-199d-4f66-a625-c2f6ba6467b9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The architect of the project has changed; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is not at this role anymore; @victornoel[/z](https://www.0crat.com/u/victornoel) is the architect now

**Comment by victornoel** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#1359](https://github.com/yegor256/cactoos/issues/1359) assigned to @borysfan[/z](https://www.0crat.com/u/borysfan), here is [why](https://www.0crat.com/footprint/C63314D6Z/83252149-94fa-4f90-9ef0-3b04b7f10fdf); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by baudoliver7** [comment]
@victornoel I think it's already resolved in PR #1492

**Comment by victornoel** [comment]
@baudoliver7 indeed it seems it does! Thanks

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
