### ISSUE TITLE
package-info.java:32-34: Replace all the IsEqual with...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1376]
The puzzle `1367-e974cc79` from #1367 has to be resolved: 

https://github.com/yegor256/cactoos/blob/b0bae7b7d5681b5994335957e0d7286e11e6deb0/src/test/java/org/cactoos/scalar/package-info.java#L32-L34

The puzzle was created by marceloamadeu on 05-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#1376](https://github.com/yegor256/cactoos/issues/1376) assigned to @a-korzhov[/z](https://www.0crat.com/u/a-korzhov), here is [why](https://www.0crat.com/footprint/C63314D6Z/3c5d7d2d-4954-48fb-939a-747611ef905a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by a-korzhov** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1376#issuecomment-625819970))

@a-korzhov The user @a-korzhov[/z](https://www.0crat.com/u/a-korzhov) resigned from [#1376](https://github.com/yegor256/cactoos/issues/1376), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#1376](https://github.com/yegor256/cactoos/issues/1376) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/C63314D6Z/a1ee21a1-f7d0-4ec0-9a05-c4f4ab6823d7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `1367-e974cc79` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
