### ISSUE TITLE
MapEnvelope should be a real envelope and the behaviour moved to MapOf

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#1384]
In the same way we improved the cactoos API by making `ListEnvelope`, `SetEnvelope` and so on real envelopes with actual behaviour such as `equals`, `toString`, `hashcode`, etc, moved to the `ListOf`, `SetOf`, etc classes. I believe we should continue and do the same for `MapEnvelope` and `MapOf`.

The final objective is to have `MapOf` as the main entry point to build instances of `Map` in cactoos (based on a `HashMap`), and have `Sticky` and `Solid` removed.

The existing `Grouped` and `Merged` classes seems to be coherent with this desired design, so that's good.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by victornoel** [comment]
@0crat in

**Comment by victornoel** [comment]
@0crat assign @andreoss

**Comment by victornoel** [comment]
@andreoss I'm starting to assign manually because if not 0crat always assign latest issues and I would like to advance on those. I hope it's ok with you :) no rush anyway

**Comment by victornoel** [comment]
@andreoss thx :)

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @andreoss[/z](https://www.0crat.com/u/andreoss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
