### ISSUE TITLE
Join two lists

### ISSUE THREAD

**Issue by vzurauskas** [yegor256/cactoos#1385]
We need a way to join two lists. I'd like to be able to write it something like this:

```java
List<> joined = new Joined<>(list1, list2);
```

Currently there is no such constructor in `Joined`.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by fabriciofx** [comment]
@vzurauskas Really? This [constructor](https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/list/Joined.java#L45} doesn't what do you want?

**Comment by victornoel** [comment]
@vzurauskas you are meant to use `new ListOf<>(new iterable.Joined<>(list1, list2));` for this, WDYT?

**Comment by victornoel** [comment]
@vzurauskas see also #1254

**Comment by vzurauskas** [comment]
@fabriciofx Yes, that constructor actually does what I want. Not sure how I missed it. Thanks.
