### ISSUE TITLE
TextEnvelope should be sticky when constructed from `Scalar<String>`

### ISSUE THREAD

**Issue by andreoss** [yegor256/cactoos#1403]
Or probably `TextOf` (https://github.com/yegor256/cactoos/issues/1287).
```java
    @Test
    public void scalarIsComputedOnlyOnce() {
        final Text text = new TextEnvelope(
            (Scalar<String>) () -> new Object().toString()
        ) {
        };
        MatcherAssert.assertThat(
            text,
            Matchers.allOf(
                new TextIs(text),
                new TextIs(text)
            )
        );
    }

```

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by victornoel** [comment]
@andreoss no, this is not the responsibility of `TextOf`. If you need this, you either introduce a `Sticky` decorator for `Text` or you pass the `Sticky` implementation of `Scalar` to `TextOf` constructor.

**Comment by andreoss** [comment]
@victornoel Understood. I've found this behavior counter-intuitive, because having `Text` as a `String` substitute, makes one expect the same qualities from `Text` as `String` has (i.e immutability, it always evaluates to the same value)

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1403` is not assigned, can't get performer
