### ISSUE TITLE
RepeatedProc.java:34-37: Split the entire...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1406]
The puzzle `1277-9cbed564` from #1277 has to be resolved: 

https://github.com/yegor256/cactoos/blob/9612f2a56c71f73952ed3c6fb6212d06aa901c7c/src/main/java/org/cactoos/RepeatedProc.java#L34-L37

The puzzle was created by andreoss on 18-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso), @victornoel[/z](https://www.0crat.com/u/victornoel) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#1406](https://github.com/yegor256/cactoos/issues/1406) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/C63314D6Z/835a97c8-1c32-4e3e-8fae-15eb6e6719b3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by fabriciofx** [comment]
@marceloamadeu @victornoel I think these interfaces must stay in `org.cactoos`. WDYT?

**Comment by victornoel** [comment]
@fabriciofx yes totally.

@marceloamadeu can you also at the same time take care of moving `RepeatedProc` as `Repeated` in the `proc` package as proposed in #1409?

I let those two points passes by mistake

**Comment by 0crat** [comment]
The architect of the project has changed; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is not at this role anymore; @victornoel[/z](https://www.0crat.com/u/victornoel) is the architect now

**Comment by victornoel** [comment]
@0crat in

**Comment by victornoel** [comment]
@0crat assign @marceloamadeu

**Comment by 0crat** [comment]
> @0crat assign @marceloamadeu ([here](https://github.com/yegor256/cactoos/issues/1406#issuecomment-653899431))

@victornoel The job [#1406](https://github.com/yegor256/cactoos/issues/1406) assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu), here is [why](https://www.0crat.com/footprint/C63314D6Z/652f9361-f38e-4983-90a5-c137eeade0e1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
> @0crat assign @marceloamadeu ([here](https://github.com/yegor256/cactoos/issues/1406#issuecomment-653899431))

@victornoel There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@d30d334c-b8f5-4e54-8f5c-30e1e363cf4f, thread: PQ-C63314D6Z
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:yegor256/cactoos#1406] declared for identity constraint of element "agenda".
```

[0.53.15](https://github.com/zerocracy/farm): CID: [51421259-0de3-4059-99ea-d56437f94906](https://www.0crat.com/footprint/C63314D6Z/51421259-0de3-4059-99ea-d56437f94906), Type: "Order was given"

**Comment by marceloamadeu** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse  ([here](https://github.com/yegor256/cactoos/issues/1406#issuecomment-657597705))

@marceloamadeu The user @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) resigned from [#1406](https://github.com/yegor256/cactoos/issues/1406), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#1406](https://github.com/yegor256/cactoos/issues/1406) assigned to @andreoss[/z](https://www.0crat.com/u/andreoss), here is [why](https://www.0crat.com/footprint/C63314D6Z/8f9bf172-fbdc-4039-9846-4678c0004ce3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `1277-9cbed564` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job was finished in 43 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
