### ISSUE TITLE
TimedTest.java:265-266: Create RepeatedCallable decorator...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1407]
The puzzle `1277-1f8d2dd2` from #1277 has to be resolved: 

https://github.com/yegor256/cactoos/blob/9612f2a56c71f73952ed3c6fb6212d06aa901c7c/src/test/java/org/cactoos/experimental/TimedTest.java#L265-L266

The puzzle was created by andreoss on 15-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso), @victornoel[/z](https://www.0crat.com/u/victornoel) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#1407](https://github.com/yegor256/cactoos/issues/1407) assigned to @borysfan[/z](https://www.0crat.com/u/borysfan), here is [why](https://www.0crat.com/footprint/C63314D6Z/f2c17788-8f72-4ddf-86a3-50607dfeafcf); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The architect of the project has changed; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is not at this role anymore; @victornoel[/z](https://www.0crat.com/u/victornoel) is the architect now

**Comment by victornoel** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#1407](https://github.com/yegor256/cactoos/issues/1407) assigned to @roman-kuvaldin[/z](https://www.0crat.com/u/roman-kuvaldin), here is [why](https://www.0crat.com/footprint/C63314D6Z/788e6a6f-6cd3-498d-bd7c-317060e50317); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1407#issuecomment-658881955))

@victornoel The user @roman-kuvaldin[/z](https://www.0crat.com/u/roman-kuvaldin) resigned from [#1407](https://github.com/yegor256/cactoos/issues/1407), please stop working. Reason for job resignation: Order was cancelled

**Comment by marceloamadeu** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1407#issuecomment-674145894))

@marceloamadeu The user @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) resigned from [#1407](https://github.com/yegor256/cactoos/issues/1407), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#1407](https://github.com/yegor256/cactoos/issues/1407) assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C63314D6Z/dd15d7b2-0e8b-4648-abca-9a7a380923b1); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `1277-1f8d2dd2` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
