### ISSUE TITLE
File 'stale_outputs_checked' was included by mistake

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#1408]
The file `stale_outputs_checked` was included by mistake. Please, remove it.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso), @victornoel[/z](https://www.0crat.com/u/victornoel) please, pay attention to this issue

**Comment by victornoel** [comment]
@fabriciofx thx

@andreoss please be careful not to include undesired file in your PRs in the future, I've completely missed it before merging.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1408` is not assigned, can't get performer
