### ISSUE TITLE
Rename RepeatedProc to Repeated and move to func or proc package

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#1409]
To me seems `RepeatedProc` has two problems:

1. It's in the wrong package (`org.cactoos`). and it should be in `org.cactoos.func` or `org.cactoos.proc` package

2. It's a decorator, so should be renamed to `Repeated`

@victornoel WDYT?

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso), @victornoel[/z](https://www.0crat.com/u/victornoel) please, pay attention to this issue

**Comment by victornoel** [comment]
@fabriciofx yes, let's tackle that simply as part of #1406

**Comment by fabriciofx** [comment]
@victornoel I'll wait for finish #1406 to close this ticket, ok?

**Comment by victornoel** [comment]
@fabriciofx I think it's ok to close it right now, but feel free to track it and close it when it is actually fixed if you want :)

**Comment by fabriciofx** [comment]
@victornoel I agree. I'll close it now. Thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1409` is not assigned, can't get performer
