### ISSUE TITLE
Let's remove non-decorator from list package

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#1413]
In cactoos' collections classes, there is one one side iterable/iterator that provide iteration on collections of data, and on the other side the packages `list`, `set`, `map` and `collection` that concerns stateful data containers aka collections.

The current direction of Cactoos is to provide the maximum of functionality concerning iterable/iterator, and just the basic functionality concerning collections.

Let's remove from the `list` package the following classes: `Sorted`, `Shuffled`, `Mapped`.

Note that  `Joined` will be transformed to a real lazy decorator in #1254. the `map` package will be taken care of via #1384, the `set` package is already ok and the `collection` package is just missing #1261.

**Comment by victornoel** [comment]
@0crat in

**Comment by victornoel** [comment]
@0crat assign @fabriciofx

**Comment by victornoel** [comment]
@fabriciofx I'm starting to assign manually because if not 0crat always assign latest issues and I would like to advance on those. I hope it's ok with you :) no rush anyway

**Comment by fabriciofx** [comment]
@victornoel right, no problem! :)

**Comment by 0crat** [comment]
> @0crat assign @fabriciofx  ([here](https://github.com/yegor256/cactoos/issues/1413#issuecomment-691655257))

@victornoel The job [#1413](https://github.com/yegor256/cactoos/issues/1413) assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C63314D6Z/a96a84bb-3c8b-4825-a8b4-2a59b54c2bd4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by fabriciofx** [comment]
@victornoel How about `list.Synced`? Should I keep it?

**Comment by victornoel** [comment]
@fabriciofx yes, we should keep it because its functionality cannot be provided just by delegating to one of the iterable decorator.

**Comment by fabriciofx** [comment]
@victornoel right! Thanks!

**Comment by fabriciofx** [comment]
@victornoel Can you close this issue too?

**Comment by victornoel** [comment]
@fabriciofx yep, thx!

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
