### ISSUE TITLE
Move to github actions

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#1417]
Let's replace travis with github actions, once this is done, we can continue with also running tests on windows.

See also https://github.com/llorllale/cactoos-matchers/issues/83 for some similar issue.

**Comment by victornoel** [comment]
@0crat in

**Comment by andreoss** [comment]
@victornoel Why you even need running tests on other platforms? Doesn't it betray WORA?

**Comment by victornoel** [comment]
@andreoss that's the point, I don't know if everything runs well on Windows for example. Cactoos being a library handling a lot of low level stuffs, io, etc, from experience, I know that Windows always has strange problems and we want to be confident cactoos doesn't have those problems.

**Comment by victornoel** [comment]
@0crat assign me

**Comment by victornoel** [comment]
@0crat wait for #1486.

**Comment by 0crat** [comment]
Job was finished in 1 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))
