### ISSUE TITLE
Sticky decorator for Text

### ISSUE THREAD

**Issue by andreoss** [yegor256/cactoos#1423]
A caching decorator for `Text` would be useful in `takes`.
https://github.com/yegor256/takes/issues/1062

Can it be implemented as part of `cactoos`? 

Example of usage, `Text`is a parameter and passed though ctor:
```
final Text text = new Sticky((Text) () -> ...);
MatcherAssert.assertThat(
    text,
    Matchers.allOf(
        new TextIs(text),
        new TextIs(text)
    )
);

```

**Comment by andreoss** [comment]
@victornoel Yes, it should take only `Text` (clarified above). I plan to solve https://github.com/yegor256/takes/issues/1062, as soon as this feature released. 
An implementation proposed in #1429

**Comment by victornoel** [comment]
@andreoss feel free to close this now that the PR was merged :) thank you

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1423` is not assigned, can't get performer
