### ISSUE TITLE
CallableWithFallback

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#143]
Let's create `CallableWithFallback`, similar to `RunnableWithFallback` we introduced in #141

**Comment by cheparinV** [comment]
@yegor256 i'll handle this issue.

**Comment by ashtonhogan** [comment]
@cheparinV seems this was merged, can you please close this issue?

**Comment by yegor256** [comment]
@cheparinV @ashtonhogan thanks

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
