### ISSUE TITLE
Cactoos isn't building (on Windows) due FindBugs errors?

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#1430]
Seems cactoos isn't building due FindBugs errors:
```
[WARNING] FindBugs: M C RCN: Nullcheck of stream at line 92 of value previously dereferenced in org.cactoos.io.DigestEnvelope.asBytes()  At DigestEnvelope.java:[line 92]
[WARNING] FindBugs: M C RCN: Nullcheck of files at line 67 of value previously dereferenced in org.cactoos.io.Directory.iterator()  At Directory.java:[line 67]
[WARNING] FindBugs: L D RCN: Redundant nullcheck of stream, which is known to be non-null in org.cactoos.io.InputAsBytes.asBytes()  Redundant null check at InputAsBytes.java:[line 72]
[INFO] Read our quality policy: http://www.qulice.com/quality.html
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:51 min
[INFO] Finished at: 2020-08-30T19:39:23-03:00
[INFO] ------------------------------------------------------------------------
```
@victornoel can you check it, please?

**Comment by fabriciofx** [comment]
More information about this issue: it seems just happens in Windows (I'm using Windows 10).

**Comment by andreoss** [comment]
@fabriciofx Are you using JDK11? I believe you are experiencing https://github.com/spotbugs/spotbugs/issues/756

**Comment by victornoel** [comment]
@andreoss good find
@fabriciofx can you confirm you are using Java 11? Please build cactoos with Java 8 if it is the case :)

**Comment by fabriciofx** [comment]
@andreoss @victornoel Yeah, by my mistake I was using OpenJDK 11 instead of OpenJDK 8. Sorry about that. I'll close this issue now. Thanks for your information!

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1430` is not assigned, can't get performer

**Comment by victornoel** [comment]
@fabriciofx no worries, it's good to know this can happen if later we move to supporting Java 11 more thoroughly.
