### ISSUE TITLE
Predicate

### ISSUE THREAD

**Issue by VsSekorin** [yegor256/cactoos#144]
Why was Pred (Predicate, https://github.com/yegor256/cactoos/pull/35) removed? (https://github.com/yegor256/cactoos/pull/72/commits/f1fe71b7bb3f884b8c69aaa930bfb34659a19f54)
Let's restore it (https://github.com/yegor256/cactoos/issues/36).

**Comment by 0crat** [comment]
@vssekorin I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@VsSekorin right, let's add it as `org.cactoos.Pred`
