### ISSUE TITLE
Remove unnecessary anonymous code in favor or lambda code

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#1441]
A lot of classes as `Upper`, `Trimmed Right`, `Trimmed Left` and etc uses unnecessary anonymous code. So, let's replace them using lambdas.

**Comment by victornoel** [comment]
@fabriciofx I think it's alright to wait for issues such as #1287 to be done and cleanup those anonymous while doing them because they will impact all those classes I think. I would keep this ticket open for now anyway, and come back to it later maybe.

**Comment by victornoel** [comment]
@fabriciofx I'm closing this, please don't hesitate to comment if you see good reasons to reopen it :)

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1441` is not assigned, can't get performer
