### ISSUE TITLE
Remove unnecessary code to create SSL conection in InputOfTest

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#1443]
`InputOfTest#readsSecureUrlContent()` uses the code bellow to create a SSL conection but isn't necessary and can be deleted.

```
        final TrustManager[] managers = {
            new X509TrustManager() {
                @Override
                public X509Certificate[] getAcceptedIssuers() {
                    return new X509Certificate[0];
                }

                @Override
                public void checkClientTrusted(
                    final X509Certificate[] cert, final String arg) {
                    // nothing to do
                }

                @Override
                public void checkServerTrusted(
                    final X509Certificate[] cert, final String arg) {
                    // nothing to do
                }
            },
        };
        final SSLContext context = SSLContext.getInstance("TLS");
        context.init(null, managers, new SecureRandom());
        HttpsURLConnection.setDefaultSSLSocketFactory(
            context.getSocketFactory()
        );
```

**Comment by victornoel** [comment]
@fabriciofx indeed, I'm not sure why it was setup like that...

**Comment by victornoel** [comment]
@0crat in

**Comment by victornoel** [comment]
@fabriciofx let's use takes here to serve an https file without relying on an external web resource that requires internet connectivity to work.

**Comment by fabriciofx** [comment]
@victornoel as I said [here](https://github.com/yegor256/cactoos/issues/1444#issuecomment-687765654) we can do it the same thing just using socket classes in JDK. Takes isn't necessary.

**Comment by victornoel** [comment]
@fabriciofx as concluded in #1444, since we will keep takes, let's try to use it ro replace calls to external urls. In `InputOfTest` but also in any other test that do such http request.

**Comment by fabriciofx** [comment]
@victornoel ok

**Comment by victornoel** [comment]
@andreoss sorry, I missed that the goal of the story was also to get rid of any call to external URLs by replacing them with using takes (or deleting them when unneeded as you did for HTTPS) as in the comment above (from me ^^). Could you check that there are no more of those or if there are, to fix them before we close this issue?

**Comment by andreoss** [comment]
@andreoss It was the only one

**Comment by victornoel** [comment]
@andreoss excellent, thx

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1443` is not assigned, can't get performer
