### ISSUE TITLE
Drop takes dependency

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#1444]
Takes is used only once in Cactoos, to be more precise, in one single test in `InputOfTest` which it can ben perfectly replaced for something using `URL` object or sockets. So, let's change this test and drop takes dependency.

**Comment by victornoel** [comment]
@fabriciofx actually, I think it's better than relying on some external web resource for running the test. I don't see a problem with it, and I suppose we could even try to solve #1443 with take instead of relying from an external resource.

**Comment by fabriciofx** [comment]
@victornoel we can do the same test wich takes does, without using it or any external resources, just using `ServerSocket` and `Socket` JDK classes. WDYT?

**Comment by victornoel** [comment]
@fabriciofx why reinvent the wheel? it's for tests and it's not really cactoos domain to implement such things

**Comment by fabriciofx** [comment]
@victornoel which you call "reinvent the wheel" I call "avoid uncessary dependencies" just to do two single/simple tests which sockets solve the problem. But you're the boss :)

**Comment by victornoel** [comment]
@fabriciofx those are just test dependencies, so it's not critical, so we will keep takes, it's not a risk for the project to do so :) thx anyway for looking into it!

**Comment by victornoel** [comment]
@fabriciofx I will close this now :)

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1444` is not assigned, can't get performer
