### ISSUE TITLE
Reorganise classes around Scalar and Callable

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#1445]
Lets:
- Transform `RepeatedCallable` to `scalar.Repeated`
- Remove usage of `CallableOf` that can be replaced by a `Scalar` with `ScalarOf` or similar
- Move all the constructor (except the one taking a `Scalar`) from `CallableOf` to `ScalarOf`.
- Make `ScalarOf` extends `ScalarEnvelope` instead of wrapping a `Scalar`.

**Comment by victornoel** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#1445](https://github.com/yegor256/cactoos/issues/1445) assigned to @aivinog1[/z](https://www.0crat.com/u/aivinog1), here is [why](https://www.0crat.com/footprint/C63314D6Z/58ee6eb4-5a8f-4800-911c-80865275406b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1445#issuecomment-699654926))

@victornoel The user @aivinog1[/z](https://www.0crat.com/u/aivinog1) resigned from [#1445](https://github.com/yegor256/cactoos/issues/1445), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1445#issuecomment-699608722))

@victornoel Job `gh:yegor256/cactoos#1445` is not assigned, can't get performer

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1445#issuecomment-711167076))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1445](https://github.com/yegor256/cactoos/issues/1445) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) for [17days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @victornoel[/z](https://www.0crat.com/u/victornoel): This user reported the ticket
    * @aivinog1[/z](https://www.0crat.com/u/aivinog1): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231445%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@0crat assign me

**Comment by victornoel** [comment]
@0crat wait for #1522

**Comment by 0pdd** [comment]
@victornoel 2 puzzles [#1526](https://github.com/yegor256/cactoos/issues/1526), [#1527](https://github.com/yegor256/cactoos/issues/1527) are still not solved.

**Comment by 0pdd** [comment]
@victornoel 3 puzzles [#1526](https://github.com/yegor256/cactoos/issues/1526), [#1527](https://github.com/yegor256/cactoos/issues/1527), [#1532](https://github.com/yegor256/cactoos/issues/1532) are still not solved.

**Comment by 0pdd** [comment]
@victornoel 2 puzzles [#1527](https://github.com/yegor256/cactoos/issues/1527), [#1532](https://github.com/yegor256/cactoos/issues/1532) are still not solved; solved: [#1526](https://github.com/yegor256/cactoos/issues/1526).

**Comment by 0pdd** [comment]
@victornoel the puzzle [#1527](https://github.com/yegor256/cactoos/issues/1527) is still not solved; solved: [#1526](https://github.com/yegor256/cactoos/issues/1526), [#1532](https://github.com/yegor256/cactoos/issues/1532).

**Comment by 0pdd** [comment]
@victornoel all 3 puzzles are solved here: [#1526](https://github.com/yegor256/cactoos/issues/1526), [#1527](https://github.com/yegor256/cactoos/issues/1527), [#1532](https://github.com/yegor256/cactoos/issues/1532).
