### ISSUE TITLE
Improve documentation about IO classes that close streams after performed the operation

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#1450]
Some classes as `LengthOf`closes the stream after performed the operation but the documentation says **nothing** about it. So, let's improve the documentation to warn the developers about it.

*I lost a lot of time today because I didn't know this "detail"* :(

**Comment by victornoel** [comment]
@fabriciofx let's clarify #1449 and if possible, we will clarify doc as part of it

**Comment by fabriciofx** [comment]
@victornoel I agree

**Comment by victornoel** [comment]
@fabriciofx  I'm closing this as I included this job in the scope of #1449. Thx!

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1450` is not assigned, can't get performer
