### ISSUE TITLE
pom.xml:114-116: Migrate the rest of tests to JUnit 5...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1453]
The puzzle `1416-3379c7cc` from #1416 has to be resolved: 

https://github.com/yegor256/cactoos/blob/171c9aef7fc8248df87335d1640ee93cde92307d/pom.xml#L114-L116

The puzzle was created by andreoss on 12-Sep-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1453#issuecomment-761099965))

@victornoel The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#1453](https://github.com/yegor256/cactoos/issues/1453), please stop working. Reason for job resignation: Order was cancelled

**Comment by victornoel** [comment]
@0crat status

**Comment by 0pdd** [comment]
The puzzle `1416-3379c7cc` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1586](https://github.com/yegor256/cactoos/issues/1586) is still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by baudoliver7** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1453#issuecomment-822783495))

@baudoliver7 This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1453](https://github.com/yegor256/cactoos/issues/1453) is not in scope
  * The job is waiting quality review verdict by @sereshqua[/z](https://www.0crat.com/u/sereshqua) for 7hr
  * @baudoliver7[/z](https://www.0crat.com/u/baudoliver7) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231453%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@0crat quality good

**Comment by victornoel** [comment]
@sereshqua huhu, I stole your thunder, I wanted to know if I could do it and apparently yes ^^

**Comment by sereshqua** [comment]
@victornoel no worries :)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1637](https://github.com/yegor256/cactoos/issues/1637) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1641](https://github.com/yegor256/cactoos/issues/1641) is still not solved; solved: [#1637](https://github.com/yegor256/cactoos/issues/1637).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1642](https://github.com/yegor256/cactoos/issues/1642) is still not solved; solved: [#1637](https://github.com/yegor256/cactoos/issues/1637), [#1641](https://github.com/yegor256/cactoos/issues/1641).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#unknown]() is still not solved; solved: [#1637](https://github.com/yegor256/cactoos/issues/1637), [#1641](https://github.com/yegor256/cactoos/issues/1641), [#1642](https://github.com/yegor256/cactoos/issues/1642).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1714](https://github.com/yegor256/cactoos/issues/1714) is still not solved; solved: [#1586](https://github.com/yegor256/cactoos/issues/1586).
