### ISSUE TITLE
ListIteratorNoNulls.java:36-37: Add also some null checks...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1459]
The puzzle `1247-25d91c9c` from #1247 has to be resolved: 

https://github.com/yegor256/cactoos/blob/07b063e6af19ca733fd9b7afd38c8506f1c816f8/src/main/java/org/cactoos/list/ListIteratorNoNulls.java#L36-L37

The puzzle was created by Victor Noël on 13-Sep-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
This puzzle inherited milestone `1.0` from issue #1247.

**Comment by 0pdd** [comment]
The puzzle `1247-25d91c9c` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
