### ISSUE TITLE
Abbreviated.java:83-87: Introduce `text.Flatten` that...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1460]
The puzzle `1287-014a5155` from #1287 has to be resolved: 

https://github.com/yegor256/cactoos/blob/47aff6e4c70f6f53d24bdccb7c1f6c12abfe60d2/src/main/java/org/cactoos/text/Abbreviated.java#L83-L87

The puzzle was created by Victor Noël on 13-Sep-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
This puzzle inherited milestone `1.0` from issue #1287.

**Comment by victornoel** [comment]
@0crat assign me

**Comment by victornoel** [comment]
@0crat wait for #1475 to be done first.

**Comment by victornoel** [comment]
@0crat wait for #1515

**Comment by 0crat** [comment]
> @0crat wait for #1515 ([here](https://github.com/yegor256/cactoos/issues/1460#issuecomment-751481751))

@victornoel Job [#1460](https://github.com/yegor256/cactoos/issues/1460) is already on hold

**Comment by andreoss** [comment]
@victornoel It's not quite clear why calling `.value()` directly in order to get `Text` is undesirable.

**Comment by victornoel** [comment]
@andreoss I don't understand the question, can you clarify?

**Comment by 0pdd** [comment]
The puzzle `1287-014a5155` has disappeared from the source code, that's why I closed this issue.

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1460#issuecomment-757498509))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1460](https://github.com/yegor256/cactoos/issues/1460) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231460%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)
