### ISSUE TITLE
TextOf.java:63-67: Introduce `Text` implementations...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1461]
The puzzle `1287-48d7a962` from #1287 has to be resolved: 

https://github.com/yegor256/cactoos/blob/47aff6e4c70f6f53d24bdccb7c1f6c12abfe60d2/src/main/java/org/cactoos/text/TextOf.java#L63-L67

The puzzle was created by Victor Noël on 13-Sep-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
This puzzle inherited milestone `1.0` from issue #1287.

**Comment by 0crat** [comment]
The job [#1461](https://github.com/yegor256/cactoos/issues/1461) assigned to @ruca905[/z](https://www.0crat.com/u/ruca905), here is [why](https://www.0crat.com/footprint/C63314D6Z/13f1d1d1-4d54-4c57-b002-dd5fd7c730f9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1461#issuecomment-778824319))

@victornoel The user @ruca905[/z](https://www.0crat.com/u/ruca905) resigned from [#1461](https://github.com/yegor256/cactoos/issues/1461), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0pdd** [comment]
The puzzle `1287-48d7a962` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/cactoos/issues/1461#issuecomment-791190703))

@sereshqua There is no quality review for [#1461](https://github.com/yegor256/cactoos/issues/1461), no performer

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1560](https://github.com/yegor256/cactoos/issues/1560) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#1560](https://github.com/yegor256/cactoos/issues/1560) is solved here.
