### ISSUE TITLE
Lowered.java:58-62: Introduce `text.Mapped` that takes a...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1462]
The puzzle `1287-1c7c8289` from #1287 has to be resolved: 

https://github.com/yegor256/cactoos/blob/47aff6e4c70f6f53d24bdccb7c1f6c12abfe60d2/src/main/java/org/cactoos/text/Lowered.java#L58-L62

The puzzle was created by Victor Noël on 13-Sep-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
This puzzle inherited milestone `1.0` from issue #1287.

**Comment by 0pdd** [comment]
The puzzle `1287-1c7c8289` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @andreoss[/z](https://www.0crat.com/u/andreoss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
