### ISSUE TITLE
Paged.java:44-46: Continue refactoring and add...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1464]
The puzzle `1183-64533d21` from #1183 has to be resolved: 

https://github.com/yegor256/cactoos/blob/af979def342f0bfe75e31912588681cd090c8c6c/src/main/java/org/cactoos/iterable/Paged.java#L44-L46

The puzzle was created by andreoss on 09-Sep-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
The job [#1464](https://github.com/yegor256/cactoos/issues/1464) assigned to @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), here is [why](https://www.0crat.com/footprint/C63314D6Z/a7398e5c-ec73-4e8d-96cf-9a3e56933bb6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `1183-64533d21` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1537](https://github.com/yegor256/cactoos/issues/1537), [#1538](https://github.com/yegor256/cactoos/issues/1538) are still not solved.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0pdd** [comment]
@0pdd all 2 puzzles are solved here: [#1537](https://github.com/yegor256/cactoos/issues/1537), [#1538](https://github.com/yegor256/cactoos/issues/1538).
