### ISSUE TITLE
org.cactoos.collection.ImmutableTest.size() does not call Immutable.size()

### ISSUE THREAD

**Issue by StuporHero** [yegor256/cactoos#1470]
[`org.llorllale.cactoos.matchers.HasSize`](https://github.com/llorllale/cactoos-matchers/blob/master/src/main/java/org/llorllale/cactoos/matchers/HasSize.java) iterates the collection and counts the elements rather than calling the `size()` method, so [this test](https://github.com/yegor256/cactoos/blob/2305514a32edde79f55130f6b040ef316ee8f400/src/test/java/org/cactoos/collection/ImmutableTest.java#L46) is not testing what it is supposed to be testing. Correcting this will improve test coverage numbers.

**Comment by andreoss** [comment]
@0crat  assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/cactoos/issues/1470#issuecomment-727831352))

@andreoss You can't do "Request order start", unless you have one of these roles: `ARC`, `PO`; current roles of @andreoss[/z](https://www.0crat.com/u/andreoss) are: `DEV`, `REV`

**Comment by victornoel** [comment]
@0crat assign @andreoss

**Comment by victornoel** [comment]
@andreoss thx

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @andreoss[/z](https://www.0crat.com/u/andreoss), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
