### ISSUE TITLE
map.NoNulls and ListIteratorNoNulls don't check if the origin is null

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#1471]
The classes `map.NoNulls` and `ListIteratorNoNulls` don't check if the original `Map` and `ListIterator` used in the constructor is `null` as their `*NoNulls` "coursins".

**Comment by victornoel** [comment]
@fabriciofx can we add this to the description of #1469? (also, what's a "coursin"? do you mean "cousin"?)

**Comment by fabriciofx** [comment]
> @fabriciofx can we add this to the description of #1469?

@victornoel I don't think so, because they're different things.

> (also, what's a "coursin"? do you mean "cousin"?)

Yeah, you're completely right! My bad! Thanks for correct me! :)

**Comment by victornoel** [comment]
@fabriciofx ah yes, sorry, I read too fast. So yes, let's fix that. Are there other places where NoNulls are incomplete? Let's consider that the job is also to check verify it!

**Comment by victornoel** [comment]
@0crat in

**Comment by fabriciofx** [comment]
@victornoel I don't think so. I've been checked all and I *hope* there aren't more issues with them. :)

**Comment by 0crat** [comment]
The job [#1471](https://github.com/yegor256/cactoos/issues/1471) assigned to @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), here is [why](https://www.0crat.com/footprint/C63314D6Z/7e40a8c3-3da1-4eef-9324-a0f294a618c7); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by baudoliver7** [comment]
@fabriciofx I know that constructor must be code free. But in this case, because of immutability, I think that we can make an exception to check if origin is null in constructor. For example, `map.NoNulls` have dozen methods that use this.map. WDYT ?

**Comment by victornoel** [comment]
@baudoliver7 hmm, to be honest, it's not exactly clear what's the best here… it's useless to test for null in the methods because anyway it will already fail with a NPE. So checking in the constructor sounds to be the less bad solution… but I wonder if it's really useful to do so actually (since anyway, we will get a NPE in the methods…).

I should have thought more about it before putting this ticket in scope. What is your opinion after looking at the code?

**Comment by baudoliver7** [comment]
@victornoel I suggest to do it in constructor since we are too many methods (about ten methods in map.NoNulls and ListIteratorNoNulls) that use origin. And I think also that the very suffix NoNulls should not allow someone to go further with a null origin. This is my opinion.

**Comment by victornoel** [comment]
@baudoliver7 in that case, it means we should also do it for all the other NoNull classes, right?

**Comment by baudoliver7** [comment]
@victornoel I propose to do it for NoNull classes that have at least two functions that depends on origin. I said it not to be blame by QA. :)

**Comment by victornoel** [comment]
@baudoliver7 @fabriciofx after some thoughts, I believe it was a mistake to put this ticket in scope.

While it's not a problem to raise an exception in the classes with one or two methods when the `origin` object is null, I don't think there are any advantage to actually do it.

In cactoos, we consider we have real objects that are not nulls and if we wrap such object in their `NoNulls` variant, it is to check for nulls on the input and output of their method, not to check for nulls on the objects themselves.

So I will close this, @sereshqua please consider this work as acceptable as the investigation was done by @baudoliver7 :)

**Comment by sereshqua** [comment]
@victornoel 0crat is not that fast to assign tickets to me than I reply :D

**Comment by 0crat** [comment]
Job was finished in 3 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/cactoos/issues/1471#issuecomment-758109167))

@sereshqua There is no quality review for [#1471](https://github.com/yegor256/cactoos/issues/1471), no performer
