### ISSUE TITLE
text.NoNulls has been created an unnecessary Text object

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#1472]
`text.NoNulls` has been created an unnecessary `Text`object. Take a look (pay attention in the `new TextOf`):

Actually:

```
    public NoNulls(final Text text) {
        super(
            new TextOf(
                () -> {
                    if (text == null) {
                        throw new IllegalArgumentException(
                            "NULL instead of a valid text"
                        );
                    }
                    final String string = text.asString();
                    if (string == null) {
                        throw new IllegalStateException(
                            "NULL instead of a valid result string"
                        );
                    }
                    return string;
                }
            )
        );
    }
```

As should be:

```
    public NoNulls(final Text text) {
        super(
            () -> {
                if (text == null) {
                    throw new IllegalArgumentException(
                        "NULL instead of a valid text"
                    );
                }
                final String string = text.asString();
                if (string == null) {
                    throw new IllegalStateException(
                        "NULL instead of a valid result string"
                    );
                }
                return string;
            }
        );
    }
```

**Comment by victornoel** [comment]
@fabriciofx actually, the later is incorrect because we want to take advantage of the full implementation of `TextOf`, including equals, hashcode and tostring!

**Comment by victornoel** [comment]
@fabriciofx this is interesting because maybe it means we should add more tests to the text decorators to ensure they do have the correct implementation for those 3 methods!

**Comment by fabriciofx** [comment]
@victornoel Should I change this title to improve text decorators to test these 3 methods?

**Comment by victornoel** [comment]
@fabriciofx let's create a new ticket not to confuse the DEV that will do it! If you can create it and also include testing this for other text decorators... Maybe adding a BehaveAsText matcher like the one for list that validate that at least equals and tostring are correctly implement? WDYT?

**Comment by fabriciofx** [comment]
> @fabriciofx let's create a new ticket not to confuse the DEV that will do it!

@victornoel Right!

> If you can create it and also include testing this for other text decorators... Maybe adding a BehaveAsText matcher like the one for list that validate that at least equals and tostring are correctly implement? WDYT?

I don't like this idea so much. Look, `cactoos-matchers` already has `TextHasString` and `TextIs` matchers, right? `TextIs` checks if `asString()` of two `Text` are equals. IMHO, if `asString()` of two `Text` are equals, so `toString()` must be equals too. As `hashCode` is closely linked to `equals()` they must equals too. In resume: I think we should change `TextIs` matcher in `cactoos-matchers` to check `asString()`, `equals()`, `toString()` and `hashCode()`. WDYT?

**Comment by victornoel** [comment]
@fabriciofx yes, of course, that would be best indeed. If you could create a ticket in cactoos-matchers also then, we will discuss the details there!

**Comment by fabriciofx** [comment]
@victornoel Right! I'll close this issue and open another there. Thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1472` is not assigned, can't get performer
