### ISSUE TITLE
Reimplement iterable.Matched to lazily iterate

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#1481]
Currently `iterable.Matched` creates a new list everytime an iterator is needed.

Instead rewrite `iterable.Matched` to simply return an Iterator that lazily iterates over the two contained iterables. The simplest would be to introduce such iterator named `Matched` and delegate to it in `iterable.Matched`.

**Comment by victornoel** [comment]
@0crat in

**Comment by victornoel** [comment]
@andreoss thx

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1481` is not assigned, can't get performer
