### ISSUE TITLE
LengthOf must represents Text length

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#1489]
`LengthOf` must represents the length of a `Text`, performing a `#asString().length()`.

**Comment by victornoel** [comment]
@fabriciofx do you mean adding a constructor to the existing `LengthOf`?

**Comment by fabriciofx** [comment]
@victornoel Yeah. Do you think better change the title issue to reflects it?

**Comment by victornoel** [comment]
@fabriciofx now that it is clarified I think it's ok :)

**Comment by victornoel** [comment]
@0crat in

**Comment by victornoel** [comment]
@fabriciofx apparently it has been done, closing this.

@andreoss in the future, when you tackle jobs, can you ping the reporter or me to close the ticket after the PR is merged?

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1489` is not assigned, can't get performer
