### ISSUE TITLE
Restore Sonarcloud.io integration

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#1490]
Sonarcloud.io seems to be broken, it is not exactly clear why (see failure here: https://www.rultor.com/t/23594-716148825), but we can decide to make it work again or abandon it.

See also https://github.com/yegor256/cactoos/issues/1169#issuecomment-716143634 and following comments.

@yegor256 I think you should decide whichever is best, I will disable it for now.

**Comment by victornoel** [comment]
@paulodamaso if you know why it doesn't work and how it is related to previous changes you did to those settings, can you share it here? :)

**Comment by paulodamaso** [comment]
@victornoel I had a lot of problems with sonarcloud due to some secret values that are being used from @yegor256  private repositories. I don't remember exactly how we fixed it, sorry. I think that we should consider replacing it with another similar tool.

**Comment by victornoel** [comment]
@rultor release, tag is `0.47`

**Comment by victornoel** [comment]
@paulodamaso indeed, as we discussed, adding the `cactoos` profile to the mvn command (see b4b6163) seems to solve the issue both with sonar and gpg

**Comment by victornoel** [comment]
@0crat assign me

**Comment by victornoel** [comment]
@rultor release, tag is `0.47`

**Comment by victornoel** [comment]
@paulodamaso and the last error is a timeout on the side of sonatype

**Comment by victornoel** [comment]
@rultor release, tag is `0.47`

**Comment by victornoel** [comment]
@rultor release, tag is `0.48`

**Comment by andreoss** [comment]
@victornoel How did you fix it? Asking for https://github.com/jcabi/jcabi-jdbc/issues/86

**Comment by victornoel** [comment]
@andreoss as explained above to Paulo, by adding the cactoos profile which must be declared in the secret settings.xml
