### ISSUE TITLE
NumberEnvelope should not implement Scalar<Double>

### ISSUE THREAD

**Issue by andreoss** [yegor256/cactoos#1496]
There is no reason for `NumberEnvelope` to have extra method for `double` value. 

https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/scalar/NumberEnvelope.java#L115

**Comment by victornoel** [comment]
@andreoss please see #1335: once it is fine, number envelope will simply delegate all the public methods of number to the wrapped number I believe

**Comment by victornoel** [comment]
@0crat assign me

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1496#issuecomment-858763534))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1496](https://github.com/yegor256/cactoos/issues/1496) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is assigned to @victornoel[/z](https://www.0crat.com/u/victornoel) for [1mon](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @andreoss[/z](https://www.0crat.com/u/andreoss): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231496%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)
