### ISSUE TITLE
Newline for cactoos (System.lineSeparator())

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#1498]
Let's implements a `Newline` for cactoos, to encapsulate the `System.lineSeparator()` method.

**Comment by victornoel** [comment]
@fabriciofx do you mean as a `Text` implementation?

**Comment by fabriciofx** [comment]
@victornoel yep. WDYT?

**Comment by victornoel** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#1498](https://github.com/yegor256/cactoos/issues/1498) assigned to @dearrudam[/z](https://www.0crat.com/u/dearrudam), here is [why](https://www.0crat.com/footprint/C63314D6Z/45542f04-a3e1-4596-92f5-f545742e35cc); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by dearrudam** [comment]
@fabriciofx could you close this issue because it was solved in #1551?

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @dearrudam[/z](https://www.0crat.com/u/dearrudam), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
