### ISSUE TITLE
Travis CI and AppVeyor question

### ISSUE THREAD

**Issue by englishman** [yegor256/cactoos#150]
@yegor256 why to CIs are used in the project?

**Comment by 0crat** [comment]
@englishman I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@englishman to make sure the project is buildable on both Linux and Windows platforms.

**Comment by englishman** [comment]
@yegor256 I see. Thanks you.
