### ISSUE TITLE
Why Scalar is not annotated with @FunctionalInterface?

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#1502]
Why don't we use [`@FunctionalInterface`](https://docs.oracle.com/javase/8/docs/api/java/lang/FunctionalInterface.html) in `Scalar`? I suggest we add this annotation.

**Comment by victornoel** [comment]
@yegor256 what is it for? I'm curious about what problem it could solve to have it

**Comment by victornoel** [comment]
@yegor256 what is it for? I'm curious about what problem it could solve to have it

**Comment by yegor256** [comment]
@victornoel I don't know... maybe just in order to be in line with Java spec?

**Comment by andreoss** [comment]
@yegor256 @victornoel 

`@FI`-annotated interfaces are extra-checked by compiler, compilation will fail if there's more than one abstract  method available, besides that it's just documentation. [1]

But `Scalar` is not the only SAM interface here, pretty much all cactoos' interfaces can be annotated with `@FunctionalInterface`.
`@FI` perhaps could imply that implementation should be pure/stateless, which is not always the case (i.e `text.Randomized`), but makes sense for interfaces like `Comparator`. 

1: https://docs.oracle.com/javase/specs/jls/se14/html/jls-9.html#jls-9.8

**Comment by victornoel** [comment]
@yegor256 @andreoss from what I read, the only really good reason to use this is the following I read on the [internet](https://stackoverflow.com/a/50892176/9046139):
> If you have one abstract method you can use lambda expressions.
> If you see the @FunctionalInterface annotation you know that you shouldn't add any new methods, because it will break design.

All the rest is not very architecturally important IMHO.

Concerning purity, I'm not sure it is something really expected in Java, I didn't read much about it while researching about functional interfaces, so I don't think it is a problem. They are called like that only because they allows for lambda expressions to be used.

So let's do it, but for all the cactoos interfaces actually.

**Comment by victornoel** [comment]
@0crat in

**Comment by yegor256** [comment]
@victornoel good decision!

**Comment by victornoel** [comment]
@yegor256 but it won't happen until 0crat is fixed, it has been ignoring everything happening on this repository for some time…

**Comment by 0crat** [comment]
The job [#1502](https://github.com/yegor256/cactoos/issues/1502) assigned to @dearrudam[/z](https://www.0crat.com/u/dearrudam), here is [why](https://www.0crat.com/footprint/C63314D6Z/9b543b39-b563-4c0d-a3ae-8d8cdaef2e6a); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by dearrudam** [comment]
@yegor256 could you close this issue because it was solved in #1552?

**Comment by yegor256** [comment]
@dearrudam thanks!

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @dearrudam[/z](https://www.0crat.com/u/dearrudam), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by dearrudam** [comment]
@sereshqua thanks!
