### ISSUE TITLE
MappedWithIndex would be nice to have

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#1507]
The functionality of `Mapped` is not enough, since it doesn't provide the index of the element into the `Func`. I'm suggesting to create `MappedWithIndex(BiFunc, items)`.

**Comment by victornoel** [comment]
@yegor256 good idea, let's add it to iterator and iterable (delegating to the iterator one) then.

**Comment by victornoel** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#1507](https://github.com/yegor256/cactoos/issues/1507) assigned to @dearrudam[/z](https://www.0crat.com/u/dearrudam), here is [why](https://www.0crat.com/footprint/C63314D6Z/fbe91dbc-a674-4836-85f3-7badd45fc778); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by dearrudam** [comment]
@yegor256 could you close this issue because it was solved with #1554?

**Comment by yegor256** [comment]
@dearrudam thanks!

**Comment by sereshqua** [comment]
@0crat quality good
