### ISSUE TITLE
Joined(items, item) ctor is missing

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#1508]
We have `Joined(item, items)` ctor, which makes a list with the first element `item`, but we don't have a ctor to put the item at the end of the new list. How about creating one?

**Comment by victornoel** [comment]
@yegor256 would it be:  `Joined(Iterable<T> items, T item)`?

**Comment by yegor256** [comment]
@victornoel yes, I think so

**Comment by victornoel** [comment]
@yegor256 ok, then let's add it for list, iterator and iterable. Btw note the following issue about list: #1254

**Comment by victornoel** [comment]
@0crat in

**Comment by victornoel** [comment]
@yegor256 looks like it has been fixed in #1523

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1508` is not assigned, can't get performer
