### ISSUE TITLE
Web url based resource links bring to test failure

### ISSUE THREAD

**Issue by englishman** [yegor256/cactoos#151]
If network environment is restricted or development is going on offline then some tests are failed.
E.g. such links
```
new UrlAsInput(
    "https://raw.githubusercontent.com/yegor256/cactoos/0.5/pom.xml"
)
```
have to be changed to local files with `"file:///<relative path here>/pom.xml"`

**Comment by 0crat** [comment]
@englishman I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@englishman indeed it's a bug, thanks.

**Comment by englishman** [comment]
Will take care of it

**Comment by yegor256** [comment]
@englishman I would not change them to `file://...` It's important to have real tests that actually go to real URLs. In order to see how we behave with content that is not available immediately, but takes some time to read. I would rather add some gate keepers in front of the tests, which will check whether we're online now or not. But I'm not sure... :)

**Comment by englishman** [comment]
Set of broken tests
![6-16-2017 11-04-06 am](https://user-images.githubusercontent.com/1883572/27232348-bde8e8f2-5283-11e7-8eda-ae36158acca5.png)

**Comment by englishman** [comment]
@yegor256 
> It's important to have real tests that actually go to real URLs.

Even with `file://...` it'll go through real `URL` java class. And we don't want to test it behavior.

> In order to see how we behave with content that is not available immediately, but takes some time to read.

Honestly, I can't see any reason for this testing primitive utility classes. But if you see, please, explain.

> But I'm not sure... :)

Will provide `file://...` bases fix and if we really need slow `org.cactoos.Input` implementation we'll create it for such testing purposes later.

**Comment by englishman** [comment]
Fixed
