### ISSUE TITLE
Eclipse cannot infer type arguments for IterableAsMap error

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#152]
Apparently, Eclipse IDE can not infer type arguments for Iterable Map in IterableAsMapTest, imply an error in the project. I'm using Eclipse Neon.3 (4.6.3).

**Comment by 0crat** [comment]
@fabriciofx I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by fabriciofx** [comment]
Fixed in #153.
