### ISSUE TITLE
Release 0.49

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#1530]
We had a bunch of stuffs merged lately.

As soon as #1528 is merged, let's release 0.49.

**Comment by victornoel** [comment]
@rultor release, tag is `0.49`

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#1530](https://github.com/yegor256/cactoos/issues/1530), since the job is not in scope anymore

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@b40c505f-5cb0-4cae-88ec-eec5fb70b484, thread: PQ-C63314D6Z
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:yegor256/cactoos#1530] declared for identity constraint of element "speed".
```

[0.55](https://github.com/zerocracy/farm): CID: [b781ea85-52d6-4450-afff-49056b2ec53f](https://www.0crat.com/footprint/C63314D6Z/b781ea85-52d6-4450-afff-49056b2ec53f), Type: "Order was canceled"
