### ISSUE TITLE
Update cactoos-matchers to latest version

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#1531]
cactoos-matchers got some nice improvement lately, such as consistent naming of matchers, so updating to the latest version needs a bit of work.

Let's:
- ~~update cactoos to the latest version in cactoos-matchers repository (as soon as 0.49 is released, see #1530)~~ done in https://github.com/llorllale/cactoos-matchers/pull/222
- ~~ask for releasing a new version of cactoos-matchers once it's done~~ done in https://github.com/llorllale/cactoos-matchers/pull/222
- update cactoos-matchers to this new version in cactoos

**Comment by victornoel** [comment]
@0crat in

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1531#issuecomment-761589347))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1531](https://github.com/yegor256/cactoos/issues/1531) is [in scope](http://www.zerocracy.com/policy.html#14) for 5hr
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @victornoel[/z](https://www.0crat.com/u/victornoel): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231531%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@baudoliver7 would you like to tackle this? :)

**Comment by baudoliver7** [comment]
@victornoel Yes, of course :)

**Comment by victornoel** [comment]
@0crat assign @baudoliver7

**Comment by victornoel** [comment]
@baudoliver7 cool, like this it will unblock other things :)

**Comment by victornoel** [comment]
@baudoliver7 thank you

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job was finished in 32 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by sereshqua** [comment]
@0crat quality good
