### ISSUE TITLE
BiProc.java:42-45: Introduce BiProcOf on the model of...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1532]
The puzzle `1445-c6a75ced` from #1445 has to be resolved: 

https://github.com/yegor256/cactoos/blob/865f249032e7ba30584d1c25e9d04f3a2bb37e62/src/main/java/org/cactoos/BiProc.java#L42-L45

The puzzle was created by Victor Noël on 10-Jan-21. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
This puzzle inherited milestone `1.0` from issue #1445.

**Comment by 0pdd** [comment]
The puzzle `1445-c6a75ced` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
