### ISSUE TITLE
Paged.java:42-45: We want to use {@code Iterator<X>}...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1537]
The puzzle `1464-68f0eee6` from #1464 has to be resolved: 

https://github.com/yegor256/cactoos/blob/86ad37b671edb86a5d92d00c1005cc6c62f2c825/src/main/java/org/cactoos/iterator/Paged.java#L42-L45

The puzzle was created by @baudoliver7 on 19-Jan-21. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
This puzzle inherited milestone `1.0` from issue #1464.

**Comment by victornoel** [comment]
@0crat refuse

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1537#issuecomment-830836111))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1537](https://github.com/yegor256/cactoos/issues/1537) is [in scope](http://www.zerocracy.com/policy.html#14) for 3mon
  * The role is `DEV`
  * The job is assigned to @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) for [1mon](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231537%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1537#issuecomment-830819713))

@victornoel The user @marceloamadeu[/z](https://www.0crat.com/u/marceloamadeu) resigned from [#1537](https://github.com/yegor256/cactoos/issues/1537), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#1537](https://github.com/yegor256/cactoos/issues/1537) assigned to @dmitrybarskov[/z](https://www.0crat.com/u/dmitrybarskov), here is [why](https://www.0crat.com/footprint/C63314D6Z/9b43070b-1220-41fb-9ebf-f2584db97691); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat assign @sergiusac

**Comment by 0crat** [comment]
> @0crat assign @sergiusac ([here](https://github.com/yegor256/cactoos/issues/1537#issuecomment-831360448))

@victornoel The job [#1537](https://github.com/yegor256/cactoos/issues/1537) assigned to @sergiusac[/z](https://www.0crat.com/u/sergiusac), here is [why](https://www.0crat.com/footprint/C63314D6Z/8b18f372-b87e-4af8-873d-fc4a983c4f50); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `1464-68f0eee6` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @sergiusac[/z](https://www.0crat.com/u/sergiusac), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
