### ISSUE TITLE
Paged.java:38-40: Replace the constructor so that instead...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1538]
The puzzle `1464-a8b18c11` from #1464 has to be resolved: 

https://github.com/yegor256/cactoos/blob/86ad37b671edb86a5d92d00c1005cc6c62f2c825/src/main/java/org/cactoos/iterable/Paged.java#L38-L40

The puzzle was created by @baudoliver7 on 19-Jan-21. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html). 

Edit from ARC: see also https://github.com/yegor256/cactoos/issues/1595 for some more details on this task.

**Comment by 0pdd** [comment]
This puzzle inherited milestone `1.0` from issue #1464.

**Comment by 0crat** [comment]
The job [#1538](https://github.com/yegor256/cactoos/issues/1538) assigned to @sergiusac[/z](https://www.0crat.com/u/sergiusac), here is [why](https://www.0crat.com/footprint/C63314D6Z/294e7a7f-5246-4fa0-838d-a99b5dbd42d6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by SergiusAC** [comment]
@0crat refuse

**Comment by SergiusAC** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1538#issuecomment-831206992))

@SergiusAC The user @sergiusac[/z](https://www.0crat.com/u/sergiusac) resigned from [#1538](https://github.com/yegor256/cactoos/issues/1538), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1538#issuecomment-831218443))

@SergiusAC This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1538](https://github.com/yegor256/cactoos/issues/1538) is [in scope](http://www.zerocracy.com/policy.html#14) for 3mon
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @0pdd[/z](https://www.0crat.com/u/0pdd): This user reported the ticket
    * @sergiusac[/z](https://www.0crat.com/u/sergiusac): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231538%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/1538#issuecomment-831206992))

@SergiusAC Job refused in 20 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by victornoel** [comment]
@0crat assign @SergiusAC

**Comment by 0crat** [comment]
> @0crat assign @SergiusAC  ([here](https://github.com/yegor256/cactoos/issues/1538#issuecomment-831318117))

@victornoel The job [#1538](https://github.com/yegor256/cactoos/issues/1538) assigned to @sergiusac[/z](https://www.0crat.com/u/sergiusac), here is [why](https://www.0crat.com/footprint/C63314D6Z/09bbc2eb-c361-4b69-94bb-b41340a094bd); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `1464-a8b18c11` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@e9e4b655-9073-4bf2-b156-3422abacb233, thread: PQ-C63314D6Z
com.jcabi.xml.StrictXML[124] java.lang.IllegalArgumentException: 1 error(s) in XML document: -1:-1: Duplicate unique value [gh:yegor256/cactoos#1538] declared for identity constraint of element "speed".
```

[0.55.1](https://github.com/zerocracy/farm): CID: [5f66501b-3db2-4e89-95b5-a732edc68afc](https://www.0crat.com/footprint/C63314D6Z/5f66501b-3db2-4e89-95b5-a732edc68afc), Type: "Order was finished"

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @sergiusac[/z](https://www.0crat.com/u/sergiusac), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
