### ISSUE TITLE
Let's create BooleanAsScalar, IntegerAsScalar, LongAsScalar, FloatAsScalar and DoubleAsScalar

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#154]
Let's encapsule `boolean`, `int`, `long`, `float` and `double` as `Scalar`.

**Comment by 0crat** [comment]
@fabriciofx I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by Timmeey** [comment]
@fabriciofx why do you suppose this is needed?

The Scalar Interface is already generic which allows you to encapsulate all those values.

Maybe you can give an example where the Generic scalar would not suffice

**Comment by fabriciofx** [comment]
@Timmeey As @yegor256 have said, we can use lambda instead of these classes. I didn't know it, because I don't know lambda very well. So, I agreed with Yegor, and I'll close this issue. Thanks for your attention!
