### ISSUE TITLE
TextOf.java:320-325: We want constructors with {@code...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1560]
The puzzle `1461-42d3dd73` from #1461 has to be resolved: 

https://github.com/yegor256/cactoos/blob/62345fc1ba3db7fdfd562ba1a7ad32fab3cbb5e1/src/main/java/org/cactoos/text/TextOf.java#L320-L325

The puzzle was created by @baudoliver7 on 04-Mar-21. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
This puzzle inherited milestone `1.0` from issue #1461.

**Comment by 0crat** [comment]
The job [#1560](https://github.com/yegor256/cactoos/issues/1560) assigned to @dmitrybarskov[/z](https://www.0crat.com/u/dmitrybarskov), here is [why](https://www.0crat.com/footprint/C63314D6Z/14380c13-1e1a-4116-91b8-7d7deacf62f5); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `1461-42d3dd73` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @dmitrybarskov[/z](https://www.0crat.com/u/dmitrybarskov), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by sereshqua** [comment]
@0crat quality good
