### ISSUE TITLE
IterableAsList is very ineffective

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#157]
The implementation of `IterableAsList` is very wrong, performance wise. Let's implement it similar to what `IterableAsMap` is doing.

**Comment by Timmeey** [comment]
@yegor256 how would you change it, if it should still be able to reflect changes in the underlying Iterable?

From what i can see, IterableAsMap suffers from the same problem, changes in the underlying iterable are not reflected.

**Comment by englishman** [comment]
Currently `IterableAsMap` is immutable. Was this design done intentionally?

**Comment by yegor256** [comment]
@Timmeey yes, this is how it should be -- they must be immutable.

**Comment by Timmeey** [comment]
@yegor256 are you really arguing now that you should not be able to add/remove elements from lists, but only create new lists? 

From what i see here, the underlying list is not part of the state of the IterableAsList but rather part of its behaviour.

**Comment by yegor256** [comment]
fixed in #175

**Comment by yegor256** [comment]
@Timmeey you were right, see https://github.com/yegor256/cactoos/issues/180
