### ISSUE TITLE
Fix Github Checks

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#1578]
Currently, we are using Github Actions to run the CI:
- build on multiple platforms (windows, mac, linux)
- build on multiple Java version
- run codecov
- run qulice

A few weeks ago there were no problems but for an unknown reason, there are now two problems with the in-PR checks:
- there is a failing check about appveyor: we don't use it and already have corresponding github action for it
- there is no checks about codecov: the integration seems to be disabled according to https://app.codecov.io/gh/yegor256/cactoos/settings ![image](https://user-images.githubusercontent.com/160975/112001148-f9228180-8b1e-11eb-985a-0d9fc67b2a7e.png)

**Comment by victornoel** [comment]
@0crat assign @yegor256

**Comment by yegor256** [comment]
@victornoel I removed Appveyor from the project (deleted the webook)

**Comment by victornoel** [comment]
@yegor256 yep, it seems to work as expected. Still no codecov though

**Comment by victornoel** [comment]
@yegor256 if you look at a commit in codecov, for example https://codecov.io/gh/yegor256/cactoos/commit/ed23927c7525691b15bec16344ce6aec698b3bea/, for #1582, it says: "Waiting for CI to complete".

I found a codecov community discussion on the matter, https://community.codecov.io/t/all-repos-in-organization-are-stuck-on-waiting-for-ci-to-complete-for-week/1049, and it looks like to be related to a permission issue…

**Comment by victornoel** [comment]
@yegor256 it is working now, thank you.

Example: in  https://github.com/yegor256/cactoos/pull/1587 the codecov checks appear (and fail in that case)

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/1578#issuecomment-858763828))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#1578](https://github.com/yegor256/cactoos/issues/1578) is [in scope](http://www.zerocracy.com/policy.html#14) for 2mon
  * The role is `DEV`
  * The job is assigned to @yegor256[/z](https://www.0crat.com/u/yegor256) for [2mon](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @victornoel[/z](https://www.0crat.com/u/victornoel): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%231578%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@0crat out
