### ISSUE TITLE
String vs CharSequence inconsitencies 

### ISSUE THREAD

**Issue by andreoss** [yegor256/cactoos#1579]
`TextOf` uses `CharSequence` as parameter, but many other implementations of `Text` use only `String`.

Proposal:
Interface `CharSequence` should be favored as a parameter type instead of final class `String`.

**Comment by victornoel** [comment]
@andreoss that's a great idea

**Comment by victornoel** [comment]
@0crat in

**Comment by andreoss** [comment]
Don in #1582

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1579` is not assigned, can't get performer
