### ISSUE TITLE
StickyInputTest bug doesn't allow Travis CI to build

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#159]
Apparently we have some problem with StickyInputTest that doesn't allow Travis CI to build. Follow the error log:
```
[ERROR] /home/travis/build/yegor256/cactoos/src/test/java/org/cactoos/io/StickyInputTest.java:[46,33] incompatible types: cannot infer type-variable(s) T,X,Y
    (argument mismatch; org.cactoos.func.RepeatedFunc<org.cactoos.io.StickyInput,Y> cannot be converted to org.cactoos.Func<org.cactoos.io.StickyInput,java.lang.Boolean>)
```

**Comment by 0crat** [comment]
@fabriciofx I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@fabriciofx I believe it's fixed in https://github.com/yegor256/cactoos/commit/4826cc44d099d2f6e525edb61f6771e9299dbed8

**Comment by fabriciofx** [comment]
@yegor256 Yeah, I'll close this PR. Thanks!
