### ISSUE TITLE
MapOf(map, X, Y)

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#1618]
How about we introduce a new ctor for `MapOf`, which will accept the existing `Map`, a new key `X`, and a new value `Y`. This will be much more convenient than creating an instance of `Map.Entry` for a single entry.

**Comment by victornoel** [comment]
@yegor256 ok let's do that as well a introduce `MapOf(X, Y)` (directly delegating to `super` I think). And also update the javadoc of the class because it's clearly incorrect.

**Comment by victornoel** [comment]
@0crat in

**Comment by victornoel** [comment]
@yegor256 this was implemented in #1625

**Comment by yegor256** [comment]
@victornoel thanks!

**Comment by victornoel** [comment]
@0crat status

**Comment by victornoel** [comment]
@0crat status
