### ISSUE TITLE
Bad formatting

### ISSUE THREAD

**Issue by kerelape** [yegor256/cactoos#1681]
https://github.com/yegor256/cactoos/blob/3deef00262356738434a4e04e93945507756ce38/src/main/java/org/cactoos/Func.java#L38

The `<p>` tag is not closed.

**Comment by victornoel** [comment]
Hello @kerelape, I believe this is correct formatting for javadoc.

See https://stackoverflow.com/questions/5260368/which-tag-should-be-used-as-paragraph-separator-in-javadoc for example for an explanation.
