### ISSUE TITLE
Test matchers location

### ISSUE THREAD

**Issue by englishman** [yegor256/cactoos#169]
At this moment some successors of `org.hamcrest.TypeSafeMatcher` are located at root `org.cactoos` package among important high level interfaces. I think the new matchers should be removed from this place somewhere.

1. The best options is to put them into a new library e.g. **cactoos-test** is dependent from **cactoos**. In this case these classes will not be located in client prod code if it's used prod **cactoos** lib. The client has to use **cactoos-test** only for it's tests via test scope dependency (`<scope>test</scope>` in Maven). This idea is used e.g. Spring Framework: it has 'spring-core' and 'spring-test'.

2. The easiest option is to move them at least into specialized `org.cactoos.match` package don't to pollute the root package.

WDYT?

**Comment by 0crat** [comment]
@englishman I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by fabriciofx** [comment]
@englishman At the moment, we have only two matchers, right? So, I think we can follow the 2nd option, move them to a `org.cactoos.math` for a while. When the classes number grow up, we can think in move them to another library. WDYT?

**Comment by englishman** [comment]
@fabriciofx 3 of them. But there is another problem: dependencies. Marchers use some entities from prod **cactoos** code but tests for prod lib code need matchers. So...

**Comment by fabriciofx** [comment]
@englishman Well, so the simplest solution is just create a new package and put the matchers there. WDYT?

**Comment by yegor256** [comment]
@englishman looks like `cactoos-test` is the best option. Maybe we can create our own alternative to Hamcrest there?

**Comment by englishman** [comment]
@yegor256 let me think about `cactoos-test` more... As I wrote earlier the main problem here is cyclic dependency. BTW why do we use Hamcrest but not [AssertJ](http://joel-costigliola.github.io/assertj/)?

**Comment by yegor256** [comment]
@englishman didn't know about AssertJ :( Will take a look now.

**Comment by yegor256** [comment]
@englishman AssertJ syntax looks nicer that Hamcrest, but it's less object-oriented :) We need something that will be more declarations and less about procedures/instructions/commands.

**Comment by llorllale** [comment]
@englishman we're going to separate the matchers into their own project as discussed in #751 

Please close this issue

**Comment by llorllale** [comment]
@englishman closing

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
