### ISSUE TITLE
build failed on java 21+

### ISSUE THREAD

**Issue by h1alexbel** [yegor256/cactoos#1690]
`URL(java.lang.String) in java.net.URL has been deprecated`

**Comment by victornoel** [comment]
Hi @h1alexbel, can you point me to the deprecation notice? I cannot find it

**Comment by william7b7d** [comment]
FWIW I am able to build with JDK 17 and don't see any indication in that version of the java.net.URL class that the URL(String) constructor is deprecated.  It does however look like the constructors in that class are deprecated in JDK 21, so it might be worth moving away from regardless.  I'm guessing your IDE was using a JDK newer than 17 with that particular build you attempted @h1alexbel

**Comment by h1alexbel** [comment]
@william7b7d Yes, you are right on this, issue updated
