### ISSUE TITLE
EmptyIterator and EmptyIterable

### ISSUE THREAD

**Issue by VsSekorin** [yegor256/cactoos#170]
Let's introduce `EmptyIterator` and `EmptyIterable` similar to `DeadInput`, `DeadOutput`.

**Comment by 0crat** [comment]
@vssekorin I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256
