### ISSUE TITLE
Max and Min

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#172]
Let's implement Max and Min. Max returns the greater and Min returns smaller among numbers.

**Comment by 0crat** [comment]
@fabriciofx I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by fabriciofx** [comment]
Closed #263
