### ISSUE TITLE
Update description of the PDD #1425

### ISSUE THREAD

**Issue by andrewlevada** [yegor256/cactoos#1756]
Hello. I have tried to complete the [todo task #1425](https://github.com/yegor256/cactoos/issues/1559) but a couple of things in the description confused me:
1. "Keep PR short and limit the changes to a single package." — most classes in all packages have already been migrated to cactoos-matchers, leaving ~15 files that still use MatcherAssert.assertThat spread out between a couple packages. So is it ok to submit a PR that includes changes in all remaining files at once?
2. "After all packages are done, add MatcherAssert to forbidden-apis.txt" — MatcherAssert is already in the [forbidden-apis.txt](https://github.com/yegor256/cactoos/blob/master/src/test/resources/forbidden-apis.txt). Should the task description be updated perhaps?

**Comment by yegor256** [comment]
@andrewlevada it's better to ask clarifying questions right where the task is defined, in its ticket
