### ISSUE TITLE
HeadOf and TailOf

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#185]
We have `SkippedIterable` now. I'm suggesting to rename it to `HeadOf` and introduce a new one: `TailOf`. `HeadOf` will make an iterable of a certain head portion of the iterable, while `TailOf` will do the same with the tail of it.

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/185#issuecomment-382105389))

@llorllale Job [#185](https://github.com/yegor256/cactoos/issues/185) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#185](https://github.com/yegor256/cactoos/issues/185) assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/C63314D6Z/1222150284); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by Vatavuk** [comment]
@yegor256 Please close this issue, it was solved in #808

**Comment by yegor256** [comment]
@Vatavuk thanks

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#185](https://github.com/yegor256/cactoos/issues/185) is now out of scope

**Comment by llorllale** [comment]
@rultor release, tag is `0.31`

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Comment by jimkast** [comment]
HeadOf is not the same with Skipped now, it is actually identical to Limited iterable. Can you restore Skipped iterable?

**Comment by llorllale** [comment]
@jimkast you should use `HeadOf`/`TailOf` now.

And yes, we forgot to remove `Limited`.

**Comment by jimkast** [comment]
Thank you very much for your reply. However, if I am not misunderstood, there is no Skipped alternative now. HeadOf **selects** first elements, TailOf **selects** last elements, while Skipped **omits** the first elements.

**Comment by jimkast** [comment]
No it is not the same. For example:

`List<Integer> list = Arrays.asList(5,6,7,8,9,10);`
`new HeadOf<>(2, list)` gives  [5,6]
`new TailOf<>(2, list) gives`  [9,10]
`new Skipped<>(2, list) `gives  [7,8,9,10]


If you know the size then yes, it is the same, you can use:
new HeadOf<>(size - 2, list)
but we we don't then there is no alternative to Skipped now.

**Comment by llorllale** [comment]
@jimkast perhaps if we add this ctor... what do you think?

```java
public TailOf(Func<Collection<T>, Integer> num, Iterable<T> src)
```

you could then do 

```java
new TailOf(
    col -> col.size() -2,
    collection
);
```

**Comment by jimkast** [comment]
Func would be a solution but this ctor is not intention revealing and would make the class more complicated. I think implementing (restoring) the Skipped (or Omitted) class would be clearer in my opinion.

**Comment by llorllale** [comment]
@jimkast alright. Can you please open a new ticket to resurrect `Skipped`?

**Comment by jimkast** [comment]
@llorllale Of course! Thank you very much.
