### ISSUE TITLE
SplitText

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#193]
Let's create `SplitText`, which will do what `String.split()` is doing:

```java
Iterable<String> lines = new SplitText("hello, world!", "\s+");
```

**Comment by fabriciofx** [comment]
@yegor256 I'll handle it. I'll submit a PR in few minutes.

**Comment by alex-semenyuk** [comment]
Sorry @fabriciofx. Already submitted PR, but will be appreciate your review on PR.

**Comment by fabriciofx** [comment]
@alex-semenyuk Not problem! :)

**Comment by fabriciofx** [comment]
@alex-semenyuk @yegor256 I'm sorry, but should not `SplitText` return an `Iterable<Text>` instead of `Iterable<String>`?

**Comment by yegor256** [comment]
@alex-semenyuk thanks!
