### ISSUE TITLE
SubText

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#194]
Let's create `SubText`, which will do what String.substring() is doing:

```java
String line = new SubText("hello world", 2, 9).asString();
```
And `line`will be equal to `llo wor`

**Comment by 0crat** [comment]
@fabriciofx I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by fabriciofx** [comment]
Closed #195.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#194` was not in scope
