### ISSUE TITLE
AbbreviatedText

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#198]
Let's create `AbbreviatedText`, which will do what StringUtils.abbreviate() in [Apache Commons](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#abbreviate-java.lang.String-int-int-) doing:
```java
String abbreviated = new AbbreviatedText("hello world", 8).asString();
```
And `abbreviated` will be equal to `hello wo...`

**Comment by 0crat** [comment]
@fabriciofx I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by fabriciofx** [comment]
@yegor256 Could you assing this issue to me? Thanks!

**Comment by yegor256** [comment]
@0crat assign @fabriciofx

**Comment by 0crat** [comment]
> @0crat assign @fabriciofx  ([here](https://github.com/yegor256/cactoos/issues/198#issuecomment-356597462))

@yegor256 The job [#198](https://github.com/yegor256/cactoos/issues/198) assigned to fabriciofx. The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to [@fabriciofx](http://www.0crat.com/u/fabriciofx), total is [+135](http://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to [@yegor256](http://www.0crat.com/u/yegor256), total is [+6710](http://www.0crat.com/u/yegor256)

**Comment by fabriciofx** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/198#issuecomment-356790631))

@fabriciofx This is what I know about this job, as in §32:

  * The job [#198](https://github.com/yegor256/cactoos/issues/198) is in scope
  * The job is assigned to [@fabriciofx](http://www.0crat.com/u/fabriciofx)
  * These users are banned: [@fabriciofx](http://www.0crat.com/u/fabriciofx): This user reported the ticket

**Comment by 0crat** [comment]
[@fabriciofx](http://www.0crat.com/u/fabriciofx) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@fabriciofx[/z](http://www.0crat.com/u/fabriciofx) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#198](https://github.com/yegor256/cactoos/issues/198), please stop working

**Comment by amihaiemil** [comment]
@yegor256 Can you assign Fabricio back here? I just reviewed the PR, I think it's ok :)

**Comment by yegor256** [comment]
@0crat assign @fabriciofx

**Comment by 0crat** [comment]
> @0crat assign @fabriciofx  ([here](https://github.com/yegor256/cactoos/issues/198#issuecomment-359787238))

@yegor256 The job [#198](https://github.com/yegor256/cactoos/issues/198) assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+7870](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -15 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+7870](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#198](https://github.com/yegor256/cactoos/issues/198), please stop working

**Comment by 0crat** [comment]
The job [#198](https://github.com/yegor256/cactoos/issues/198) assigned to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by flslkxtc** [comment]
@yegor256 This issue has been resolved in merged pull request https://github.com/yegor256/cactoos/pull/200

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/198#issuecomment-363075629))

@yegor256 The user @flslkxtc[/z](https://www.0crat.com/u/flslkxtc) resigned from [#198](https://github.com/yegor256/cactoos/issues/198), please stop working

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#198` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#198](https://github.com/yegor256/cactoos/issues/198) is now out of scope
