### ISSUE TITLE
README file code examples to project moving

### ISSUE THREAD

**Issue by englishman** [yegor256/cactoos#2]
@yegor256 are you gonna put `README.md` code examples into the project source code?

**Comment by 0crat** [comment]
@englishman I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@englishman yes, will try to

**Comment by yegor256** [comment]
@englishman I think we can close this ticket. We just need to open other tickets, demanding more/better documentation for specific classes, when needed.

**Comment by englishman** [comment]
@yegor256 agreed

**Comment by yegor256** [comment]
@englishman please, close the ticket
