### ISSUE TITLE
RepeatedText

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#203]
Let's create `RepeatedText`, which will do what StringUtils.normalize() in [Apache Commons](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#repeat-java.lang.String-int-) doing:
```java
String repeated = new RepeatedText("hello");
```
And `repeated` will be equal to `hellohello`

**Comment by 0crat** [comment]
@fabriciofx I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by fabriciofx** [comment]
Closed by #204
