### ISSUE TITLE
NoNulls

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#209]
We have `NotNullInput` and `NotNullOutput` now. I don't find this design sufficient enough. Let's introduce embedded classes for all interfaces and call them `NoNulls`. For example, `Func.NoNulls`. It will wrap a `Func` and throw NPE every time a `null` is coming in to any method or going out from any method.

Let's move `NotNullInput` to `Input.NoNulls` and `NotNullOutput` to `Output.NoNulls`.

**Comment by fabriciofx** [comment]
@yegor256 I'm sorry, but why put them into interfaces? Why not just create classes outside called `InputNoNulls` and `OutputNoNulls`? I belive interfaces must be simplest possible, without any classes inside them.

**Comment by memoyil** [comment]
Ok I'll do it

**Comment by fabriciofx** [comment]
@memoyil Please, could you wait for @yegor256 comment about put the classes inside or outside the interfaces? Thanks in advance!

**Comment by memoyil** [comment]
@fabriciofx Sure

**Comment by memoyil** [comment]
@fabriciofx Hello I thought that your comment about making different class named InputNoNulls etc. has not any difference than current attitude except name difference. But making them inside an interface much more better behavior i think.

**Comment by fabriciofx** [comment]
@memoyil I belive interfaces are a core concept in true OO, so they should be the simplest possible. By "most simplest" I mean only method signatures and (if necessary) some constants. The reason it's because interfaces are types, so they should be more stable than classes. When you put classes inside them, you increase the risk to change this interface. Yeah, I know problem is change the interfaces' signatures, but I'm "radical" about it. :) Another good reason is about organization. I think more organized interfaces (with only signatures) in one side and classes (implementation) in another side. WDYT?

**Comment by memoyil** [comment]
@fabriciofx  We should discuss this interface attitude in the problem level. Because of not nulling have to span all methods inputs and outputs, I think we should put them into interface because the problem is at type level. So the solution should be at type level.

**Comment by yegor256** [comment]
@fabriciofx I agree with @memoyil This `NoNulls` thing/class is more like a "type invariant", which, if Java would be smarter, would stay more organically closer to the interface. In other words, it's not a class by itself, but a feature of the interface. I still think we need to put them inside the interface.

**Comment by memoyil** [comment]
Ok, I'll do it

**Comment by fabriciofx** [comment]
@yegor256 Ok. Thanks for your explanation.

**Comment by mdbs99** [comment]
I agree with @fabriciofx, ie, interfaces should be as simple as possible.
However, I like this syntax `Input.NoNulls` because is elegant and gives to the programmer some tips using code completion.
In other hand, what the limit? May I put all "cool" classes inside the interface? Some classes won't part of the interface but others will.
So I see two ways to write code and, IMHO, this is not good.

**Comment by fabriciofx** [comment]
@mdbs99 I agree with you. The syntax is ok, but what I put or not put in a interface? I follow the approach "less is more", especially to interfaces. Other point of view: `InputNoNulls` is a kind of `Input` implementation and it checks if an `Input` is `null` or not. And IMHO, implementation must be outside interfaces. @yegor256 Makes sense?

**Comment by mdbs99** [comment]
Could `NoNull` be a generic to work with all classes?

**Comment by fabriciofx** [comment]
@mdbs99 I don't think so, because `Input`, `Output` and others have different types and numbers of parameters and the goal of `NoNulls` is check their parameters.

**Comment by mdbs99** [comment]
Ahh not only the instance itself, but its state. I got it.

Well could be `NotNullInput` which already exists or — as I like to maintain the same prefix to use IDE code completion — `InputWithNoNulls`.

**Comment by fabriciofx** [comment]
@mdbs99 I liked `InputNoNulls` is shorter than `InputWithNoNulls`... 😄

**Comment by mdbs99** [comment]
@fabriciofx yeah, but semantically it's wrong.
`SafeInput` is another option, but the prefix was changed again.

**Comment by fabriciofx** [comment]
@mdbs99 Yeah, but the initial proposal was name it to `Input.NoNulls`, so a class called `InputNoNulls` IMHO, it's the same thing. But `SafeInput` it's an another option too.

**Comment by mdbs99** [comment]
@fabriciofx not the same thing. The name `Input.NoNulls` is a kind of namespace, meanwhile `InputNoNulls` is just a name.

**Comment by fabriciofx** [comment]
@mdbs99 You're right. `Input.NoNulls` denotes a kind of namespace. So, it's a more one argument against `Input.NoNulls`. Create objects using the fully qualified name should be avoid to all cost, IMHO.

**Comment by yegor256** [comment]
My final decision: `Input.NoNulls` :) Let's do it.

**Comment by fabriciofx** [comment]
Closed #258.

**Comment by fabriciofx** [comment]
@yegor256 Could you review it now? Thanks in advance!

**Comment by fabriciofx** [comment]
@yegor256 This code was merged. Could you close it? Thanks in advance!

**Comment by yegor256** [comment]
@fabriciofx thanks!
