### ISSUE TITLE
Use .value () instead of .asValue ()

### ISSUE THREAD

**Issue by ixmanuel** [yegor256/cactoos#211]
Why not use .value () instead of .asValue ()

new BytesAsInput().value() 
new TextAsBytes().value()
new StringAsText().value()

Why the suggestion? Because TextAsBytes is clearly described, you are not going to add more functionality to that object. This object is precise and thus, the only way to express by itself is by its value. It doesn't need to be converted .asValue(), it is the value per se.

**Comment by 0crat** [comment]
@ixmanuel I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@ixmanuel I agree, let's do it.
