### ISSUE TITLE
org.cactoos.text.FormattedText#asString contains IOException in the signature

### ISSUE THREAD

**Issue by dgroup** [yegor256/cactoos#215]
Hello team,

Could you please clarify why `org.cactoos.text.FormattedText#asString` method contains IOException in the signature?

Let's have a look into example from `readme.md`
```java
String text = new FormattedText(
  "How are you, %s?",
  name
).asString();
```
That's looks very pretty and elegant, but, when we are trying to use it we have to handle exception
```java
try {
    String text = new FormattedText(
      "How are you, %s?",
       name
    ).asString();
} catch (IOException e){
   ...
}
```

**Comment by 0crat** [comment]
@dgroup I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by fabriciofx** [comment]
@dgroup Imagine you will implements a class that read/write in a socket or a file. If you can not do it, an IOException will be throw. Anyway, you can use `UncheckedText`, like:
```java
String text = new UnchekcedText(
  new FormattedText(
    "How are you, %s?",
     name
  )
).asString();
```
and you won't need `catch` the `IOException`.

If you're satisfied with this explaination, please consider close this ticket.

**Comment by dgroup** [comment]
@fabriciofx, thank you!
