### ISSUE TITLE
Abs

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#221]
Let's implements `Abs`, that returns the same of `Math.abs()`.

**Comment by 0crat** [comment]
@fabriciofx I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by memoyil** [comment]
ok i'll do it

**Comment by fabriciofx** [comment]
@memoyil I'm sorry, but I've finished it. Bu I'll appreciate your review! :)

**Comment by fabriciofx** [comment]
@yegor256 Could you assign this issue to me and review my PR? Thanks in advance!

**Comment by fabriciofx** [comment]
@yegor256 ping!

**Comment by yegor256** [comment]
@fabriciofx I don't see a big value of replacing `Math.abs()` with a class. It's a very very primitive procedure, no need to re-write it.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#221` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#221](https://github.com/yegor256/cactoos/issues/221) was not in scope
