### ISSUE TITLE
Porting Takes codecs to Cactoos

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#225]
Let's port [Takes](http://www.takes.org) [codecs](https://github.com/yegor256/takes/tree/master/src/main/java/org/takes/facets/auth/codecs) to Cactoos. @yegor256 WDYT?

**Comment by 0crat** [comment]
@fabriciofx I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by memoyil** [comment]
Great Idea !

**Comment by fabriciofx** [comment]
@memoyil This idea was inspired by your work in `Base64DecodedText`. Do you like to do this port? If yes, I suggest you to create a pair of issue/PR to each codec. WDYT?

**Comment by memoyil** [comment]
@fabriciofx  I am OK but I think we should wait @yegor256 ideas about this issue.

**Comment by fabriciofx** [comment]
@memoyil Yeah, I agree. Let's wait.

**Comment by yegor256** [comment]
@fabriciofx yes, definitely, let's move them in here.

**Comment by fabriciofx** [comment]
@yegor256 Ok. @memoyil Would you like implement this porting? :)

**Comment by memoyil** [comment]
@fabriciofx OK, I will move them here

**Comment by fabriciofx** [comment]
@memoyil Any news about this issue?

**Comment by memoyil** [comment]
@fabriciofx I will have a commit today.

**Comment by fabriciofx** [comment]
@memoyil Ok. Thanks!

**Comment by memoyil** [comment]
@fabriciofx Hello I created a pull request. I put 2 implementations. When we made a compromise on these I can implement all of them.

**Comment by memoyil** [comment]
@fabriciofx @yegor256 We should close this issue.

**Comment by fabriciofx** [comment]
@memoyil @yegor256 WDYT close this issue? And who will earn the points?

**Comment by llorllale** [comment]
@fabriciofx Has this been done? I could not quite follow which (or all?) of the codecs you wanted ported. Can this issue be closed?

**Comment by llorllale** [comment]
@fabriciofx can we close this?

**Comment by llorllale** [comment]
@fabriciofx ping

**Comment by llorllale** [comment]
@fabriciofx closed due to inactivity. Feel free to request this feature in another ticket.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
