### ISSUE TITLE
Question: Could anyone explain me Codecov?

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#228]
Could anyone explain me Codecov? Sometimes I don't understand how it works. For example, the PR #218, I just renamed `asValue()` method to `value()` and this change don't pass in Codecov coverage tests. Thanks in advance.

**Comment by 0crat** [comment]
@fabriciofx I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by fabriciofx** [comment]
@yegor256 This issue is a question doesn't import any more. I'll close it.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#228` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#228](https://github.com/yegor256/cactoos/issues/228) was not in scope
