### ISSUE TITLE
PathAsInput, PathAsOutput

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#24]
Let's introduce two new classes `PathAsInput` and `PathAsOutput`, together with tests.

**Comment by englishman** [comment]
@yegor256 do you mean `java.nio.file.Path` interface here?

**Comment by yegor256** [comment]
@englishman yes

**Comment by yegor256** [comment]
@englishman we have `FileAsInput` and `FileAsOutput` already, these classes will be very similar

**Comment by yegor256** [comment]
fixed in #75
