### ISSUE TITLE
SplitText as Iterable<Text>

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#243]
Let's do `SplitText` implements an `Iterable<Text>` instead of `Iterable<String>`. It's more logical a `Text` splited in several `Text`s than `String`s. I'll handle it.

**Comment by 0crat** [comment]
@fabriciofx I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by fabriciofx** [comment]
@yegor256 As the commit [81d0ead4](https://github.com/fabriciofx/cactoos/commit/81d0ead4) solve this issue, I'll close this issue.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#243` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#243](https://github.com/yegor256/cactoos/issues/243) was not in scope
