### ISSUE TITLE
Equals

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#245]
Let's implement `Equals`, that compares if two objects are equals or not. I'll do it.

**Comment by 0crat** [comment]
@fabriciofx I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by fabriciofx** [comment]
Closed #246
