### ISSUE TITLE
JoinedText ctors more useful

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#248]
Let's do `JoinedText` ctors more useful, especially when working with strings. I'll handle it.

**Comment by 0crat** [comment]
@fabriciofx I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by fabriciofx** [comment]
Closed #249
