### ISSUE TITLE
Non Latin chars in test string constants 

### ISSUE THREAD

**Issue by englishman** [yegor256/cactoos#25]
I can see some [non Latin (Cyrillic) chars in test string constants](https://github.com/yegor256/cactoos/blob/master/src/test/java/org/cactoos/list/TransformedIterableTest.java#L52). 

Can we avoid usage of the such chars without significant reason? E.g. I can see some `????` chars instead of Cyrillic chars in terminal while tests are running.

**Comment by 0crat** [comment]
@englishman I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@englishman we need that for the better fragility of tests. If you only use ASCII chars, encoding problems won't be discovered. We definitely need to fix the log if you don't like it, but we can't get rid of non-ASCII chars. You should use them in your tests too.

**Comment by englishman** [comment]
@yegor256 right, that's I wrote 'usage of the such chars without significant reason'. In `TransformedIterableTest` the purpose of test isn't string manipulation at all. So usage of non Latin chars isn't justified at all.

Moreover, the test has another issue: it tests `TransformedIterable` with a help of `ArrayAsIterable`. I would prefer use here some standard JDK `Iterator` implementer.

**Comment by yegor256** [comment]
@englishman feel free to submit a PR

**Comment by llorllale** [comment]
@englishman the test you referenced no longer exists. Can we close this issue?

**Comment by llorllale** [comment]
@englishman can we close this?

**Comment by llorllale** [comment]
@englishman closing

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
