### ISSUE TITLE
Let's Jacoco enforces minimum code coverage

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#250]
It's a common problem submit PRs and them not pass in Codecov. I think this problem could be minimized if Jacoco enforces minimum code coverage, as you can check [here](http://choudhury.com/blog/2014/02/25/enforcing-minimum-code-coverage/). Thus, you can check if the minimum code coverage is reach before submit your PR.

@yegor256 WDYT?

**Comment by 0crat** [comment]
@fabriciofx I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@fabriciofx not a bad idea. Can you submit a PR?

**Comment by fabriciofx** [comment]
@yegor256 Ok, I can do it, but I need know what your minimum limit for code coverage. What do you think 80%?

**Comment by fabriciofx** [comment]
@yegor256 I've set the minimum code coverage limits to actual limits (the minimal values to pass without any warnings). These values can be checked in the PR. What do you think? We should increase/decrease some value?

**Comment by fabriciofx** [comment]
@englishman @Timmeey Yours comments will be appreciated in this issue!

**Comment by VsSekorin** [comment]
@fabriciofx Yes, it is a good idea. Thanks.

**Comment by fabriciofx** [comment]
@VsSekorin Thanks, but do you have any suggestions about the code coverage limits?

**Comment by yegor256** [comment]
@fabriciofx just use the current values

**Comment by fabriciofx** [comment]
@yegor256 Ok. So I'll close this issue.
