### ISSUE TITLE
Let's do StickyIteratorTest use JoinedText

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#253]
Let's do `StickyIteratorTest` use `JoinedText` instead String.join(). I'll do it.

**Comment by 0crat** [comment]
@fabriciofx I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@0crat assign @fabriciofx

**Comment by fabriciofx** [comment]
Closed #307.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#253` was not in scope
