### ISSUE TITLE
ReplacedAllText

### ISSUE THREAD

**Issue by ixmanuel** [yegor256/cactoos#257]
What do you think about?
```java
Text text = new ReplacedAllText(text, "\\s+", " ");
Text text = new ReplacedAllText(text, new String[]{" ","_"}, "-");
```

If approved, it is already implemented and tested in #236, if not, I'll be removing it from the AsciiText.

**Comment by 0crat** [comment]
@ixmanuel I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by ixmanuel** [comment]
Done: https://github.com/yegor256/cactoos/pull/264

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by ixmanuel** [comment]
@fabriciofx I integrated ReplacedText into ReplacedAllText in order to manage any case with the same object:
```java
// use ReplacedText
Text slug = new ReplacedAllText(
    new ReplacedAllText(text, " ", "-"), 
    "_", 
    "-")
);

// use ReplacedArrayText
Text slug = new ReplacedAllText(text, new String[]{" ","_"}, "-");

// use ReplacedRegexText
Text slug = new ReplacedAllText(text, new RegexText(" |_"), "-");
```

WDYT? 
- I'll be applying it to AsciiText as @alex-semenyuk and @memoyil recommended.
- Also, I need it for SluggedText.

The proposal is in #264

**Comment by fabriciofx** [comment]
@ixmanuel It seems fine to me. Good job! :)

**Comment by memoyil** [comment]
Seems good

**Comment by ixmanuel** [comment]
Good. I added new constructors for iterable and collections integrated:

```java
// use ReplacedText
Text slug = new ReplacedAllText(
    new ReplacedAllText(text, " ", "-"), 
    "_", 
    "-")
);

// use ReplacedItemsText (before ReplacedArrayText)
Text slug = new ReplacedAllText(text, new String[]{" ","_"}, "-");

// use ReplacedItemsText
Text slug = new ReplacedAllText(text, ArrayAsIterable<>(" ","_"), "-");

// use ReplacedItemsText
Text slug = new ReplacedAllText(text, IterableAsList<>(" ","_"), "-");

// use ReplacedRegexText
Text slug = new ReplacedAllText(text, new RegexText(" |_"), "-");
```

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/cactoos#257`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#257` was not in scope
