### ISSUE TITLE
Ternary ctor is ineffective

### ISSUE THREAD

**Issue by VsSekorin** [yegor256/cactoos#260]
Ternary ctor `public <X> Ternary(final X input, final Func<X, Boolean> cnd, final Func<X, T> cons, final Func<X, T> alter)` is ineffective. Because we calculate the value for both cases, but we only need one. I once created a Result #45  to solve this problem. If there are no contradictions, then I'll create a class representing the result of the function calculation.

**Comment by 0crat** [comment]
@vssekorin I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@VsSekorin I'm not sure I got the problem. What exactly we calculate twice?

**Comment by VsSekorin** [comment]
@yegor256 Now
```
() -> cons.apply(input),
() -> alter.apply(input)
```
But only one of these values will be used.

**Comment by VsSekorin** [comment]
My bad. I misunderstood one lambda expression.
