### ISSUE TITLE
LoggingInput and LoggingOutput

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#262]
Let's introduce two new classes `LoggingInput` and `LoggingOutput`, to send messages to logs after reading and writing is done. Let's discuss a bit more, before implementing.

**Comment by fabriciofx** [comment]
@yegor256 "To send messages to logs" you means send messages to a [Logger](https://docs.oracle.com/javase/7/docs/api/java/util/logging/Logger.html)? And what kind information do you think important to send?

**Comment by yegor256** [comment]
@fabriciofx yes, I was thinking about JUL logging. I would be interested to see something like this:

```
Read 45,030 bytes from my favorite data source in 43ms.
```

After this:

```java
new LoggingInput(
  new ResourceInput("hehe.txt"),
  "my favorite data source"
);
```

**Comment by fabriciofx** [comment]
@yegor256 Ok. I'll handle it.

**Comment by Timmeey** [comment]
@fabriciofx what do you think about trying to make this logging kind of generic by using functions to supply values for the log string? or maybe even supply the whole log string by a function. Not sure how that would look like. But maybe we could use something similar to this idea (pseudocode)
```java
FormattedString(FuncAsText(), FuncAsText... values)
```

That way we could easily specify how the logging should work.

But i guess that might even be a higher level construct to completely generalize logging. Don't know. just throwing out ideas here.

**Comment by fabriciofx** [comment]
@Timmeey Your idea seems very interesting. Let's discuss it around the proposed PR code. So, if I got the ideia, you would like change the logging message dynamiclly. It's seems to change `LoggerInputStream` in `this.logger.info()`, right? But the problem is how I can pass the parameters to build the log message. WDYT?

**Comment by yegor256** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/262#issuecomment-312696518))

Job `gh:yegor256/cactoos#262` is in scope.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#262` assigned to @fabriciofx, please go ahead.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#262` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@kkamkou resigned from `gh:yegor256/cactoos#262`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#262` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@kkamkou resigned from `gh:yegor256/cactoos#262`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#262` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@kkamkou resigned from `gh:yegor256/cactoos#262`, please stop working.

**Comment by fabriciofx** [comment]
@yegor256 Could you reassigned this job to me? I've almost done it.

**Comment by yegor256** [comment]
@0crat assign @fabriciofx

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at sun.net.www.http.KeepAliveCache$1.run(KeepAliveCache.java:112)
	at sun.net.www.http.KeepAliveCache$1.run(KeepAliveCache.java:96)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.http.KeepAliveCache.put(KeepAliveCache.java:95)
	at sun.net.www.http.HttpClient.putInKeepAliveCache(HttpClient.java:438)
	at sun.net.www.http.HttpClient.finished(HttpClient.java:395)
	at sun.net.www.http.KeepAliveStream.close(KeepAliveStream.java:97)
	at sun.net.www.MeteredStream.justRead(MeteredStream.java:93)
	at sun.net.www.MeteredStream.read(MeteredStream.java:135)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3375)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager$RewindableInputStream.read(XMLEntityManag...
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1367)
	at io.sentry.connection.AsyncConnection.send(AsyncConnection.java:93)
	at io.sentry.SentryClient.sendEvent(SentryClient.java:134)
	at io.sentry.SentryClient.sendEvent(SentryClient.java:175)
	at io.sentry.SentryClient.sendException(SentryClient.java:202)
	at io.sentry.Sentry.capture(Sentry.java:156)
	at com.zerocracy.radars.github.ReSafe.lambda$react$1(ReSafe.java:74)
	at org.cactoos.func.FuncOf.lambda$new$3(FuncOf.java:88)
	at org.cactoos.func.FuncOf.apply(FuncOf.java:104)
	at org.cactoos.func.FuncWithFallback.apply(FuncWithFallback.java:305)
	at org.cactoos.func.IoCheckedFunc.lambda$apply$0(IoCheckedFunc.java:60)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc....
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#262` assigned to [@t-izbassar](http://www.0crat.com/u/t-izbassar}). The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read [§4](http://datum.zerocracy.com/pages/policy.html#4), [§8](http://datum.zerocracy.com/pages/policy.html#8), and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by fabriciofx** [comment]
@yegor256 What's the 0crat deadline? 10 days, right? Because has passed only 8 days... In time: I've found some bugs in my PR, and I was solving them and I'm ready to push the PR.

**Comment by yegor256** [comment]
@0crat assign @fabriciofx

**Comment by 0crat** [comment]
> @0crat assign @fabriciofx  ([here](https://github.com/yegor256/cactoos/issues/262#issuecomment-356366289))

@yegor256 The job [#262](https://github.com/yegor256/cactoos/issues/262) assigned to fabriciofx. The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256, total is [+6720](http://www.0crat.com/u/yegor256).

**Comment by fabriciofx** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/262#issuecomment-356784171))

@fabriciofx This is what I know about this job, as in §32:

  * The job [#262](https://github.com/yegor256/cactoos/issues/262) is in scope
  * The job is assigned to [@fabriciofx](http://www.0crat.com/u/fabriciofx)
  * These users are banned: [@t-izbassar](http://www.0crat.com/u/t-izbassar): User was resigned from the ticket

**Comment by fabriciofx** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/262#issuecomment-359025633))

@fabriciofx The impediment was registered successfully

**Comment by fabriciofx** [comment]
@yegor256 This PR was merged. Could I close this issue?

**Comment by yegor256** [comment]
@fabriciofx which PR?

**Comment by llorllale** [comment]
@yegor256 PR #275 was merged for this. Can we close this issue?

**Comment by llorllale** [comment]
@yegor256 can we close this?

**Comment by yegor256** [comment]
@llorllale @fabriciofx thanks

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#262](https://github.com/yegor256/cactoos/issues/262) is now out of scope

**Comment by elenavolokhova** [comment]
@fabriciofx According to our Policy:
> All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary 

Such reasons were not provided here:
> fabriciofx commented on Jan 19
@0crat waiting

Please, confirm that you'll follow this rule in future.

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/cactoos/issues/262#issuecomment-383724171); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by elenavolokhova** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
