### ISSUE TITLE
Eclipse cannot infer type arguments for ChainedFuncTest

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#267]
For a change...

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by fabriciofx** [comment]
@yegor256 Could you review this PR? Thanks!

**Comment by fabriciofx** [comment]
Closed #268.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#267` was not in scope
