### ISSUE TITLE
TextAsBytes

### ISSUE THREAD

**Issue by VsSekorin** [yegor256/cactoos#27]
Let's introduce new class TextAsBytes, together with test. This will help add a test https://github.com/yegor256/cactoos/pull/14

**Comment by 0crat** [comment]
@vssekorin I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@VsSekorin good idea, let's do it
