### ISSUE TITLE
Length of text

### ISSUE THREAD

**Issue by VsSekorin** [yegor256/cactoos#289]
Let's create `LengthOfText`

**Comment by yegor256** [comment]
@VsSekorin what's wrong with `.toString().length()`?

**Comment by andriyshevchenko** [comment]
It's too procedural.

**Comment by VsSekorin** [comment]
@yegor256 I think this is more object-oriented. I create an object Scalar that is the length of the text.
```
Scalar<Integer> length = new LengthOfText(
        new TextDcr(arg)
    );
```
or
```
Scalar<Integer> length = new LengthOfText(text);
```
Instead of taking the string from the text, then take its length, and then wrap the result in a scalar.
```
Scalar<Integer> length = new Scalar<>() {
        @Override
        public Integer value() throws Exception {
            return new TextDcr(
                arg
            ).asString().length();
        }
    };
```
or
```
Scalar<Integer> length = new Scalar<>() {
        @Override
        public Integer value() throws Exception {
            return text.asString().length();
        }
    };
```

Also I always use only primitive cactoos, and do not jump Scalar -> Integer -> Scalar.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#289` was not in scope
