### ISSUE TITLE
Not null text.

### ISSUE THREAD

**Issue by VsSekorin** [yegor256/cactoos#3]
@yegor256 can I create pull request with NotNullText? Or is it redundant?
`new UpperText(new StringAsText(null)).asString();`
`new UpperText(new NotNullText(new StringAsText(null))).asString();`

**Comment by 0crat** [comment]
@vssekorin I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@VsSekorin good thinking, but such a class won't prevent problems from happening. We don't know what's inside `StringAsText` when/if we provide `null` to its constructor. We can't guarantee that `asString()` will return the same `null`. Most likely it will crash somehow inside with NPE.

**Comment by fabriciofx** [comment]
@yegor256 

What do you think about implement two classes: `SafeText` and `StringAsTextSafe`? Both will ensure not null.

**Comment by yegor256** [comment]
@VsSekorin @fabriciofx I think we can introduce classes `Text.NotNull`, `Input.NotNull`, `Output.NotNull`, etc. They will behave exactly as `Text`, but won't accept `null` as a ctor argument and will throw if `asString` returns `null`.

**Comment by fabriciofx** [comment]
@yegor256 Are you saying to create these classes inside the `Text`, `Input` and `Output` interfaces, right? What do you think create these classes *outside* them? I believe interfaces should be more simpler possible, just with methods signature and (when necessary) some constant objects. WDYT?

**Comment by yegor256** [comment]
@fabriciofx let's keep them outside, on the package level.

**Comment by fabriciofx** [comment]
@yegor256 Ok. Could close this issue if you agree with the solution?
