### ISSUE TITLE
Predicate

### ISSUE THREAD

**Issue by VsSekorin** [yegor256/cactoos#30]
Let's introduce new interface Pred (extends Func<X, Boolean>) that could be used to FilteredIterable, for example. This will add declarativeness and readability.

**Comment by 0crat** [comment]
@vssekorin I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@VsSekorin wait for #31 please

**Comment by yegor256** [comment]
@VsSekorin check the code now

**Comment by englishman** [comment]
@VsSekorin why we can't use `java.util.function.Predicate`?
