### ISSUE TITLE
Update objects vs. their static methods table

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#310]
Lets's update objects vs. their static methods table. I'll handle it.

**Comment by yegor256** [comment]
@0crat assign @fabriciofx

**Comment by 0crat** [comment]
> @0crat assign @fabriciofx  ([here](https://github.com/yegor256/cactoos/issues/310#issuecomment-314757771))

@https://api.github.com/users/yegor256 Job `gh:yegor256/cactoos#310` assigned to @fabriciofx, please go ahead.

**Comment by fabriciofx** [comment]
Closed by #311.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#310` is out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @fabriciofx, total is +30
