### ISSUE TITLE
Immutable Collections

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#313]
Let's implement immutable collections in Cactoos. I'm thinking in something simple like [`Array`](https://github.com/jcabi/jcabi-immutable/blob/master/src/main/java/com/jcabi/immutable/Array.java) but I'm not sure if our collections should or shouldn't implements JDK `List`. I'm thinking just implement `Iterable`.

@yegor256 What do you think?

**Comment by yegor256** [comment]
@fabriciofx yes, it's a good idea, but we already have them in [jcabi-immutable](http://immutable.jcabi.com/index.html). Maybe we can make similar classes in Cactoos, but with some additional functionality?

**Comment by fabriciofx** [comment]
@yegor256 To be honest, I'd like to implement [Persistent Data Structures (PDS)](https://en.wikipedia.org/wiki/Persistent_data_structure) as immutable list, set, etc. But maybe it fit better in another library. WDYT?

**Comment by yegor256** [comment]
@fabriciofx but we have them already in jcabi, right? Or I miss the idea? Can you give a code example?

**Comment by fabriciofx** [comment]
@yegor256 I'll close this issue because it's out of scope at the moment. Maybe in a near future? 😄

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#313` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#313` was not in scope
