### ISSUE TITLE
bug in InputAsBytes

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#318]
There is a bug in `InputAsBytes`: big files are not read properly.

Watch this video too: https://www.youtube.com/watch?v=Mj1gA5mEk68

**Comment by yegor256** [comment]
fixed in #319

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#318` was not in scope

**Comment by yegor256** [comment]
@rultor release, tag is `0.11.1`
