### ISSUE TITLE
AsyncFunc spawns new thread for each apply() call

### ISSUE THREAD

**Issue by g4s8** [yegor256/cactoos#324]
Creating new threads is expensive operation because it allocates a lot of memory, performs system-calls and register descriptors.
It would be better to create `Executors.newCachedThreadPool()` for async task (or maybe accept Executor as constructor argument) and submit tasks to it:
```java
private final Executor exec = Executors.newCachedThreadPool();

@Override
public Future<Y> apply(final X input) {
    return this.exec.submit(
        () -> this.func.apply(input)
    );
}
```

**Comment by g4s8** [comment]
Looks like it was partially fixed in #330

**Comment by yegor256** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/324#issuecomment-316656241))

@yegor256 Job `gh:yegor256/cactoos#324` is in scope.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#324` assigned to @fabriciofx, please go ahead.

**Comment by yegor256** [comment]
@rultor release, tag is `0.11.7`

**Comment by yegor256** [comment]
@g4s8 the problem seem to be fixed?

**Comment by g4s8** [comment]
@yegor256 sure, thanks

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#324` is out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @fabriciofx, total is +60
