### ISSUE TITLE
ReaderAsInput

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#333]
Let's create `ReaderAsInput` in order to convert `Reader` to `Input`. See http://www.baeldung.com/java-convert-reader-to-inputstream and https://stackoverflow.com/questions/62241/how-to-convert-a-reader-to-inputstream-and-a-writer-to-outputstream

**Comment by yegor256** [comment]
@rultor release, tag is `0.11.6`

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#333` was not in scope
