### ISSUE TITLE
ReaderAsBytes instead of ReaderAsInput

### ISSUE THREAD

**Issue by ixmanuel** [yegor256/cactoos#346]
@yegor256 It could be more reusable ReaderAsBytes than ReaderAsInput because it could be consumed by InputOf, BytesOf and TextOf.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#346` was not in scope

**Comment by ixmanuel** [comment]
#347

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#346` was not in scope
