### ISSUE TITLE
StickyMap ctor with another map

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#348]
Let's make it possible to extend a map via a ctor.

**Comment by yegor256** [comment]
@0crat assign me

**Comment by yegor256** [comment]
@rultor release, tag is `0.11.9`

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/cactoos/issues/348#issuecomment-317784928))

@yegor256 Job `gh:yegor256/cactoos#348` assigned to @yegor256, please go ahead.

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+510](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#348` is out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+540](http://www.0crat.com/u/yegor256).
