### ISSUE TITLE
Some predicates.

### ISSUE THREAD

**Issue by VsSekorin** [yegor256/cactoos#36]
Let's introduce predicates:
`Neg (Negative)`
`LogConj (Logical conjunction)` with iterable
`LogDisj (Logical disjunction)` with iterable
and may be
`True`
`False`

This will allow you to use complex conditions.

**Comment by 0crat** [comment]
@vssekorin I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by englishman** [comment]
Such predicates have to have the same common API. What is this? Shouldn't it extends `Scalar<Boolean>`? The next question is how such predicates interconnect with standard java `boolean` statements: `if`, `while` etc.?

**Comment by VsSekorin** [comment]
Now I propose `interface Pred<X> extends Func<X, Boolean>` (https://github.com/yegor256/cactoos/issues/30). May be `extends Func<X, Scalar<Boolean>>` is better, need to discuss.
What's the problem with `boolean`?

**Comment by englishman** [comment]
@VsSekorin not problem but issue
```
if (new IsBlank(new StringToText("some text")).asValue()) {
...
}
```
Is too cumbersome for me.

**Comment by yegor256** [comment]
@VsSekorin good idea, let's do them one by one in separate PRs and see how they fit.
