### ISSUE TITLE
InputAsBytes must be private

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#360]
We have `new BytesOf(Input)` and `InputAsBytes`. Looks like duplication to me. The user won't know which one to use. I believe, we have to make most of our classes private (visible only in the package), if they are accessible via `InputOf` or similar classes.

**Comment by yegor256** [comment]
@0crat assign @ixmanuel

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+630](http://www.0crat.com/u/yegor256).

**Comment by ixmanuel** [comment]
@yegor256 Done. See [update](https://github.com/yegor256/cactoos/pull/356#commits-pushed-83342d2).

**Comment by yegor256** [comment]
@ixmanuel thanks

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#360` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @ixmanuel, total is [+60](http://www.0crat.com/u/ixmanuel).
