### ISSUE TITLE
SortedOf, RepeatOf, ReducedOf, MappedOf, etc.

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#361]
I don't like the names we have for iterable/iterator decorators. I think we should rename them to `Sorted`, `Mapped`, `Reduced`, etc. and break our `org.cactoos.list` package to two:

  * `org.cactoos.iterable`
  * `org.cactoos.iterator`

We'll have `org.cactoos.iterable.Mapped` and `org.cactoos.iterator.Mapped`, etc.

**Comment by yegor256** [comment]
@0crat assign @ixmanuel

**Comment by 0crat** [comment]
> @0crat assign @ixmanuel  ([here](https://github.com/yegor256/cactoos/issues/361#issuecomment-318894068))

@yegor256 Job `gh:yegor256/cactoos#361` assigned to @ixmanuel, please go ahead.

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+645](http://www.0crat.com/u/yegor256).

**Comment by ixmanuel** [comment]
@yegor256 Done. See [update](https://github.com/yegor256/cactoos/pull/356#commits-pushed-83342d2).

**Comment by yegor256** [comment]
@ixmanuel thanks, merging now

**Comment by ixmanuel** [comment]
@yegor256 thanks to you too. I really appreciate all what I have learned since your Good Objects. I'm happy to contribute a little in return.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#361` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @ixmanuel, total is [+30](http://www.0crat.com/u/ixmanuel).
