### ISSUE TITLE
Interaction with JDK entities

### ISSUE THREAD

**Issue by englishman** [yegor256/cactoos#37]
**Cactoos** intention, AFAIU, is to be a library (not a framework). So we have an issue with standard JDK entities interaction (strings, java statements, JDK functions etc.)

Here are 2 points: consuming some JDK entity and producing an entity to JDK.

The way for entity consuming shows [StringAsText.java](https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/text/StringAsText.java) adapter. It adapts `java.lang.String` into `org.cactoos.Text`. So if we wanna use `org.cactoos.text.UpperText` we have to write
```
new UpperText(new StringAsText("java string"))
```

The way for producing shows [Scalar.java](https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/Scalar.java) interface with it's `asValue` method. E.g. `LengthOfIterable` implements `Scalar<Integer>` and should be used as
```
int length = new LengthOfIterable(...).asValue();
```
or
```
if (new IsBlank(new StringAsText("java string")).asValue()) {
...
}
```
_For me the both producing and consuming look a bit cumbersome and verbose. Is there any way to make JDK interaction smoothly?_ 

E.g. `java.lang.CharSequence` interface might be used instead of `org.cactoos.Text` and then string consuming might be looks like 
```
new UpperText("some java literal")
```
as `java.lang.String` already implements `java.lang.CharSequence` interface.

Also, `java.lang.Number` can be used as superclass of scalar values.  However, instead of `CharSequence` interface `Number` is an abstract class and, thus, less helpful.

WDYT?

**Comment by 0crat** [comment]
@englishman I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by VsSekorin** [comment]
>if (new IsBlank(new StringAsText("java string")).asValue()) {
...
}
For me the both producing and consuming look a bit cumbersome and verbose. Is there any way to make JDK interaction smoothly?

It looks like part of the procedure.
My suggestion:
```
new CondProc<>(
    conditional,
    firstProcedure,
    secondProcedure
).apply(...);
```
and
```
Type object = new Ternary<>(
    conditional,
    firstFunction, //Func<Something1, Type>
    secondFuntion //Func<Something2, Type>
).apply(...);
```

But I'm not sure about this completely. We had to wait for @yegor256 reply.

**Comment by englishman** [comment]
@VsSekorin yes, I thought about the such approach but you suggestion is a substitute of Java lang `if` statement. So **Cactoos** will be kind of a framework but not a library then.

BTW here
```
new CondProc<>(
    conditional,
    firstProcedure,
    secondProcedure
).apply(...);
```
what are `apply` method params?

**Comment by VsSekorin** [comment]
It's OO primitives library, I have proposed OO analog `if`.

> what are apply method params?

```
Type object = new Ternary<>(
    conditional, //Func.Pred<Some1>
    first, //Func<Some2, Type>
    second //Func<Some3, Type>
).apply(Some1 arg1, Some2 arg2, Some3 arg3);
```

**Comment by englishman** [comment]
@yegor256 WDYT? Pls, share you strategical opinion here.

**Comment by yegor256** [comment]
@englishman I think we should try to stay as far away from JDK "things" as we can. Otherwise, we will just create another Guava. That's why that `Scalar` and others. Of course, we can add `implements Number` to, say, `LengthOfIterable`, for extra convenience. Feel free to submit a PR.

**Comment by fabriciofx** [comment]
> E.g. java.lang.CharSequence interface might be used instead of org.cactoos.Text and then string consuming might be looks like
> new UpperText("some java literal")
as java.lang.String already implements java.lang.CharSequence interface.

@englishman What do you think to use a secondary constructor to it? Like:

```java
public final class UpperText implements Text {
  public UpperText(final String string) {
    this(new StringAsText(string));
  }
  public UpperText(final Text origin) {
    this.origin = origin;
  }
}
```

**Comment by VsSekorin** [comment]
@fabriciofx What about [Constructors Must Be Code-Free](http://www.yegor256.com/2015/05/07/ctors-must-be-code-free.html)? I'm not sure that this is the right solution.

**Comment by fabriciofx** [comment]
@VsSekorin The main constructor *is* code-free. But the secondary constructor can instanciate objects. Pay attention that instantiation doesn't execute any action (method executing or something like that). This will be performed later.

**Comment by englishman** [comment]
@fabriciofx like your idea! At least, we'll have a cheap one-way of JDK interaction.

**Comment by englishman** [comment]
@VsSekorin @fabriciofx but look on this discussion. 
https://github.com/yegor256/cactoos/pull/20#discussion_r118560886
It's not about `new` in ctors. It's about some code. WDYT?

**Comment by englishman** [comment]
Added separate issue #62 for this

**Comment by llorllale** [comment]
@englishman I believe this issue no longer applies. We now have `TextOf(CharSequence)`; we can also do `new UpperText(Text)` or `new UpperText(() -> "your string")`. Can we close this?

**Comment by llorllale** [comment]
@englishman can we close this?

**Comment by llorllale** [comment]
@englishman closing

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
