### ISSUE TITLE
Bug: endless Joined

### ISSUE THREAD

**Issue by alekseysotnikov** [yegor256/cactoos#370]
Cactoos v0.12 - endless iterator!
````java
Iterator<String> iterator = new Joined<>(
                new Mapped<>(
                        new ArrayOf<>("a"),
                        x -> new ArrayOf<>(x)))
                .iterator();
        while (iterator.hasNext()) {// endless iterator!
            iterator.next();
        }
````

Java 8 - works fine

````java
Iterator<String> iterator = Stream.of("a")
                .flatMap(x -> Stream.of(x))
                .iterator();
        while (iterator.hasNext()) {// works once
            iterator.next();
        }
````

**Comment by memoyil** [comment]
i will investigating

**Comment by memoyil** [comment]
First of all the code stub is like that in 0.13 :  

`        final Iterator<String> iterator = new org.cactoos.iterable.Joined<>(
            new Mapped<>(
                new IterableOf<>("a", "e", "d", "c", "b"),
                x -> new IterableOf<>(x)
            )
        ).iterator();
        while (iterator.hasNext()) {
            System.out.println(iterator.next());
        }`
And bug also occurs on 0.13 version

@yegor256 Yegor the problem here is that StickyFunc could not determine the dynamcally created IterableOf object so it could not move on the next element therefore it will be in infinite loop.
We should add hashcode in oder to determine the both objects are equal.
WDYT?

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#370` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by yegor256** [comment]
@alekseysotnikov this is the code that reproduces the problem in 0.13:

```java
@Test
    public void joinsIterables() {
        MatcherAssert.assertThat(
            "Can't concatenate iterables together",
            new Joined<>(
                new Mapped<>(
                    new IterableOf<>("a", "e", "d", "c", "b"),
                    (Func<String, Iterable<String>>) IterableOf::new
                )
            ),
            Matchers.iterableWithSize(5)
        );
    }
```

Checking what's going on...

**Comment by yegor256** [comment]
@alekseysotnikov reproduced and fixed in 5780a08

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.4`

**Comment by yegor256** [comment]
@alekseysotnikov should be fine now, try 0.13.4 please

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#370` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+3210](http://www.0crat.com/u/yegor256).
