### ISSUE TITLE
RepeatedFuncTest does not test multiple runs

### ISSUE THREAD

**Issue by HDouss** [yegor256/cactoos#375]
Despite of its purpose (and its name), the method `runsFuncMultipleTimes` in `RepeatedFuncTest` does not test if the function runs multiple times. Instead, it is testing if it is giving a different output in each call (in other words, if it is giving a random number each time).
Another way to look at the bug is that modifying the test such as not using `RepeatedFunc` at all, will succeed anyway.
```java
    @Test
    public void runsFuncMultipleTimes() throws Exception {
        final Func<Boolean, Integer> func = (
            input -> {
                return new SecureRandom().nextInt();
            }
        );
        MatcherAssert.assertThat(
            func.apply(true),
            Matchers.not(Matchers.equalTo(func.apply(true)))
        );
    }
```
I expect the test to check if the "origin" function was actually executed as many times as wanted.

**Comment by memoyil** [comment]
@yegor256 I think we should close this issue.

**Comment by yegor256** [comment]
@memoyil where was it fixed?

**Comment by memoyil** [comment]
[https://github.com/ixmanuel/cactoos/commit/1b0be72e07c094ea0f776d559425029fde9c7170](url)

**Comment by memoyil** [comment]
https://github.com/ixmanuel/cactoos/commit/1b0be72e07c094ea0f776d559425029fde9c7170

**Comment by alex-semenyuk** [comment]
@memoyil Actually this pull request https://github.com/yegor256/cactoos/pull/381/files was rewritten and the changes on which your referenced were not included in it.  This one was approved https://github.com/yegor256/cactoos/pull/383 , I suppose with it, we test the "origin" function was actually executed as many times as wanted too.

@yegor256 @HDouss 
Can we close it https://github.com/yegor256/cactoos/pull/383?

**Comment by HDouss** [comment]
@alex-semenyuk It is good for me

**Comment by HDouss** [comment]
@yegor256 Should I close it or wait for something else ?

**Comment by yegor256** [comment]
@HDouss yes, just close if the problem was fixed

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#375` was not in scope
