### ISSUE TITLE
ReaderOf, InputStreamOf, OutpuStreamOf

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#378]
Let's create that decorators.

**Comment by yegor256** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/cactoos/issues/378#issuecomment-320248213))

@yegor256 Job `gh:yegor256/cactoos#378` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+1065](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.13`

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#378` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+1110](http://www.0crat.com/u/yegor256).
