### ISSUE TITLE
Add Text Compare test cases

### ISSUE THREAD

**Issue by memoyil** [yegor256/cactoos#395]
Let's Add Text Compare test cases

**Comment by ashtonhogan** [comment]
@memoyil can you please clarify the requirement?

**Comment by llorllale** [comment]
@memoyil please close this issue. As I [said](https://github.com/yegor256/cactoos/pull/396#issuecomment-382081200) in your PR, this was fixed in #353

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
