### ISSUE TITLE
UncheckedBiFunc

### ISSUE THREAD

**Issue by Timmeey** [yegor256/cactoos#399]
We already have UncheckedFunc, lets implement UncheckedBiFunc

**Comment by memoyil** [comment]
@Timmeey @yegor256 This issue was solved. You can close it.

**Comment by yegor256** [comment]
@Timmeey @memoyil thanks all

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/cactoos#399`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#399` is not in scope.
