### ISSUE TITLE
Exceptions are not composable

### ISSUE THREAD

**Issue by nbardiuk** [yegor256/cactoos#4]
I like how code examples look declarative. But there is a hidden issue with exceptions. Exceptions are goto statements to error handling block which is not composable and not object oriented.

The library does not give a way to declare how to handle errors. In some cases, it is good to terminate whole computation as soon as error occur, but other need some error handler that produces default value in place of failure.

This code will fail with  [`IllegalStateException`](https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/list/TransformedIterator.java#L73) if there is an IO problem with any file.

    List<String> linesFromFiles = 
    new IterableAsList(
        new ConcatenatedIterable(
            new TransformedIterable<>(
                new ArrayAsIterable<>("/tmp/a.txt", "/tmp/b.txt", "/tmp/c.txt"),
                fileName ->
                    new TextAsLines(
                        new InputAsText(
                            new FileAsInput(
                                new File(fileName)
                            )
                        )
                    )
            )
        )
    );

In order to change error handling strategy, in this specific example, I will need to write my custom implementation of `InputAsText` that instead of throwing exception produce some default text. This approach is not scalable because it requires reimplementing every class that can throw an exception.

FP languages have a way to declare a function that produces either result or error without throwing exceptions using interface [Either<ERROR, RESULT>](https://github.com/vavr-io/vavr/blob/master/vavr/src/main/java/io/vavr/control/Either.java). 

What approach cactoos user should use for custom error handling?

**Comment by 0crat** [comment]
@nbardiuk I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by Timmeey** [comment]
In case you would want to intercept an exception on its way up the stack, you in this instance implement something like DefaultTextOnError class, which fulfills the text interface, and in the asString() method catch the IOException and instead return your default text. That way you would not have to reimplement all Classes, but only one class that fulfills a certain interface and provides a default value on error. in this case it could look like

```
List<String> linesFromFiles = 
new IterableAsList(
    new ConcatenatedIterable(
        new TransformedIterable<>(
            new ArrayAsIterable<>("/tmp/a.txt", "/tmp/b.txt", "/tmp/c.txt"),
            fileName ->
                new TextAsLines(
                   new DefaultTextOnError(
                      new InputAsText(
                          new FileAsInput(
                              new File(fileName)
                          )
                      )
                  )
             )
        )
    )
);
```

Or maybe we could put together something more general that takes a function, which somehow fulfills all "simple" interfaces and takes the function output if an exception is thrown. Not sure how to do that though.

**Comment by fabriciofx** [comment]
@nbardiuk Do you agree with this solution? If yes, could you please close this issue? If not, could you explain why not? Thanks for your attention!

**Comment by nbardiuk** [comment]
I am looking for more universal way to handle exceptions. @Timmeey example is good for specified problem. 

So for now it looks like users of library need to write specific decorator for every case they are going to handle exceptions.
