### ISSUE TITLE
StickyBiFunction

### ISSUE THREAD

**Issue by Timmeey** [yegor256/cactoos#400]
We already have StickyFunc, lets implement StickyBiFunc

**Comment by yegor256** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/400#issuecomment-322766042))

@yegor256 Job `gh:yegor256/cactoos#400` is in scope.

**Comment by memoyil** [comment]
@yegor256 You can close this issue

**Comment by yegor256** [comment]
@Timmeey it's yours, what do you think?

**Comment by Timmeey** [comment]
@yegor256 i like the idea of using a map as the "tuple" key. After the minor changes that i requested in the PR are done, this can be closed after merging.

**Comment by memoyil** [comment]
@yegor256 @timmeey Thank you for your comments. As we discussed in pr, no changes need to be done. Thank you

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#400` is now out of scope.
