### ISSUE TITLE
InputStreamOf() doesn't return available() correctly

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#408]
This one fails:

```
    @Test
    public void makesDataAvailable() throws IOException {
        final String content = "Hello,חבר!";
        MatcherAssert.assertThat(
            "Can't show that data is available",
            new InputStreamOf(content).available(),
            Matchers.greaterThan(0)
        );
    }

```

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#408` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+2070](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.5`

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#408` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+2100](http://www.0crat.com/u/yegor256).
