### ISSUE TITLE
SubText must ignore out of bound problems

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#409]
`SubText` must ignore out of bound problems

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#409` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+2115](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.6`

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#409` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+2145](http://www.0crat.com/u/yegor256).
