### ISSUE TITLE
toString() for key wrappers

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#410]
Let's add `toString() to them.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#410` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
+15 points just awarded to @yegor256, total is [+2160](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.7`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.7`

**Comment by yegor256** [comment]
@rultor release, tag is `0.13.7`

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#410` is now out of scope.

**Comment by 0crat** [comment]
+30 points just awarded to @yegor256, total is [+2190](http://www.0crat.com/u/yegor256).
