### ISSUE TITLE
Non-blocking io

### ISSUE THREAD

**Issue by Guseyn** [yegor256/cactoos#414]
Do you have an intention to introduce the non-blocking io in cactoos?

**Comment by yegor256** [comment]
@Guseyn sure, why not. Would you be interested to contribute? Or at least give an example of what you may need or what exists in Guava or Apache.

**Comment by Guseyn** [comment]
@yegor256 I am interested to contribute, but I don't know yet what is best approach for cactoos. I experimented with Guava approach, and actually I am not impressed because if you use it with multi-threaded servers(connection per thread), it shows bad performance for concurrency. I prefer use single-threaded server with non-blocking io as Vert.x(or node.js) implemented, for example. By non-blocking I mean that all operation with disk(file system, db), network does'n block thread and running in thread pool(at least) till result arrives, and then we work with the result in the main thread. Probably this approach is good http://rox-xmlrpc.sourceforge.net/niotut/. Or maybe integration with frameworks like Vert.x is more suitable. I will see which is approach is the best and show some examples when I write them in true oop style.

**Comment by yegor256** [comment]
@Guseyn great, waiting for your code...

**Comment by ashtonhogan** [comment]
@Guseyn this seems like quite a large task for one issue but it sounds like there is interest in it as well - for this issue can we define the scope as introducing one class in particular and if so, which class would you like to start with?

**Comment by Guseyn** [comment]
@ashtonhogan actually it is. I have been making a lot of experiments and investigation in code design. As a result, I invented the conception of async tree. Although OOP in Java is more mature than it's designed in any other language, I am focused on Node because async environment there is much better. You can read here more about this stuff: http://guseyn.com/post-reconsidering-async-object-with-cutie#intro
I think it's quite applicable for Java too, what do yo think?

**Comment by llorllale** [comment]
@Guseyn do you have any specific requirement for this issue so that we may take action?

**Comment by ashtonhogan** [comment]
@Guseyn Good one, I like it. I think @yegor256 would be lucky to have a Java implementation of this. It might be worth giving the naming some thought because `WriteFile` sounds more like a task than an object.

**Comment by Guseyn** [comment]
@ashtonhogan I am glad that you liked it. Actually, it's WrittenFile (file that has been read - sounds like an object), and it represent itself like content from the file for other async objects. 

> multithreading is difficult
You are right. But also it's not effective(gives bad performance) for I/O operations. Non-blocking I/O is right solution for this problem. I'll try to finish writing async objects for async calls from Node modules like fs and some other modules as soon as possible. And then I'll probably start doing the same things for Java. I think it's better to have different repository, and use it as dependency for cactoos (I don't like the idea of big repositories).

**Comment by Guseyn** [comment]
@llorllale Actually, this issue is more about investigation. We can close this issue for now. And then we can create another one about integration with libs that will be created (I hope so).

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@5cd4ab5f-5e31-4b63-9cb2-8ef2ba630d54, thread: BkParallel-1
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
