### ISSUE TITLE
Ternary

### ISSUE THREAD

**Issue by VsSekorin** [yegor256/cactoos#43]
Let's introduce new class Ternary. This will help in issue https://github.com/yegor256/cactoos/issues/36, for example.

**Comment by 0crat** [comment]
@vssekorin I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by VsSekorin** [comment]
https://github.com/yegor256/cactoos/pull/15

**Comment by yegor256** [comment]
@VsSekorin I'm not sure what you mean. Please, give an example.

**Comment by yegor256** [comment]
@VsSekorin maybe this one:

```
int age = new Ternary<Integer>(
  user.name().equals("Jeff"),
  55,
  18
).asValue();
```

I'd actually love to have that class in Cactoos.

**Comment by VsSekorin** [comment]
@yegor256 Yes, that's what I meant. But with Scalar<Boolean> as the first argument.
