### ISSUE TITLE
And with BiFunc

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#432]
Let's create new ctor for `And` to accept `BiFunc` with index.

**Comment by yegor256** [comment]
@rultor release, tag is `0.20`

**Comment by yegor256** [comment]
@rultor stop

**Comment by yegor256** [comment]
@rultor release, tag is `0.20`

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#432` was not in scope
