### ISSUE TITLE
Constructors inconsistency 

### ISSUE THREAD

**Issue by funivan** [yegor256/cactoos#436]
We have `Filtered`  and `Sorted` iterable. 
They both have similar behavior:
1. Accept input `Iterator<T>`
2. Accept function, that will be applied to input (`Func<X, Boolean>`,`Comparator<T>`)
3. Apply this function to the input

I think they are very similar because they both change input according to the passed function
But initializing process is different.
```java
new Filtered(dealers, new ActiveFilter());
new Sorted(new ActiveComparator(), dealers)
```

My suggestion is to make constructors more similar.
Here is two ways how to do that:
1. input first
```java
new Filtered(dealers, new ActiveFilter());
new Sorted(dealers, new ActiveComparator())
```
2. Input last
```java
new Filtered(new ActiveFilter(), dealers);
new Sorted(new ActiveComparator(), dealers)
```
Do not know what is the better one, maybe input first is ok. 

p.s. Thanks for the great library

**Comment by yegor256** [comment]
@funivan input last. Please, contribute with a PR. Thanks for the ticket!

**Comment by funivan** [comment]
@yegor256 after investigation library found some other similar issues:
I think we should change signatures in this classes
```java
package org.cactoos.iterable;
    Limited(final Iterable<T> itr, final int lmt);
    Mapped(final Iterable<X> src, final Func<X, Y> fnc);
    Reduced(final Iterable<T> list, final X ipt, final BiFunc<X, T, X> fnc);
    Repeated(final T elm, final int total);
    Skipped(final Iterable<T> iterable, final int skip)

package org.cactoos.iterator;
    Limited(final Iterator<T> iterator, final int limit)
    Mapped(final Iterator<X> iterator, final Func<X, Y> func)
    Repeated(final UncheckedScalar<T> scalar, final int max)
    Skipped(final Iterator<T> iterator, final int skip)
```
In all this cases input should be moved to the end.

But the most interesting part is `ItemAt`
`ItemAt(final Iterable<T> source, final T fallback)` - Do not know if it is a good idea to swap `source`  with `fallback`
Same here `ItemAt(final Iterable<T> source, final int position) 
I suggest to leave fallback at the end in `ItemAt` constructor. But definitely swap `source` with `position`.

If all is ok i will submit PR. I think this changes should be placed in one commit.

**Comment by yegor256** [comment]
@funivan let's put sources last, everywhere, including `ItemAt`.

**Comment by Zefick** [comment]
Majority of classes from Cactoos followed first convension from the very beginning (especially `Mapped` and `Filtered` as one of the main classes) and still follow them. It is more habitually to write decorators this way. If you change all of them it will be a very bad news for users.

**Comment by funivan** [comment]
@Zefick write decorator to change parameters order is simply strange. I`m from Php world and having tons of functions that accept input parameter in different place is very very bad. And no one want to change order according to BC.

**Comment by yegor256** [comment]
@funivan are we good now?

**Comment by funivan** [comment]
@yegor256 yep.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/cactoos#436`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#436` is not in scope.
