### ISSUE TITLE
Or. More ctors

### ISSUE THREAD

**Issue by VsSekorin** [yegor256/cactoos#439]
Let's add ctors to `org.cactoos.scalar.Or` similar to `org.cactoos.scalar.And`
- Or(final Proc<X> proc, final X... src) - controversial point
- Or(final Func<X, Boolean> func, final X... src)
- Or(final Iterable<X> src, final Proc<X> proc) - controversial point
- Or(final Iterable<X> src, final Func<X, Boolean> func)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@VsSekorin sure, let's do it.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#439` was not in scope
