### ISSUE TITLE
two sonar bugs

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#443]
Let's try to fix these two bugs Sonar is reporting: https://sonarcloud.io/project/issues?id=org.cactoos%3Acactoos&resolved=false&types=BUG

**Comment by allanws** [comment]
@yegor256 , as per the link above, I don't see any bugs on the list. This can be closed.

**Comment by yegor256** [comment]
@allanws thanks

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#443` is not assigned, can't get start time

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#443` was not in scope
