### ISSUE TITLE
SplitText mistakes

### ISSUE THREAD

**Issue by VsSekorin** [yegor256/cactoos#445]
1. `SplitText implements Iterable<String>` I think this is a serious mistake. We need to work with Cactoos primitives, rather than making transitions Cactoos - Java - Cactoos. Correction: `SplitText implements Iterable<Text>`
2. `!input.isEmpty()` Why does the `SplitText` decide whether I need empty elements? If they are superfluous, then I can decorate it with `Filtered`, but if they are needed, now I have to rewrite the `SplitText`.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#445` is not in scope.
