### ISSUE TITLE
Throwing Exception will cause the user of Cactoos an IllegalCatchCheck violation

### ISSUE THREAD

**Issue by filfreire** [yegor256/cactoos#449]
There are classes in Cactoos that have methods that are defined to throw `Exception`.

Example:

```
org.cactoos.scalar.Max.value() throws Exception
org.cactoos.scalar.Min.value() throws Exception
org.cactoos.scalar.Not.value() throws Exception
...
```

among others.

When the user needs to call this method the user has two chances, either change the signature of the method or, for example, catch the `Exception` and throw it as another type of exception.
If the user picks the former, it may imply a lot of refactoring. If the user picks the latter, he gets an IllegalCatchCheck on [checkstyle](http://checkstyle.sourceforge.net/apidocs/com/puppycrawl/tools/checkstyle/checks/coding/IllegalCatchCheck.html).

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@filfreire the third option, which I'm using always, is to use `UncheckedScalar`. Maybe we should add that to the Javadocs of these methods?

**Comment by rafamizes** [comment]
What if were created a RuntimeScalar class that would catch any Exception and rethrows it as a RuntimeException? Would the user get an IllegalCatchCheck on checkstyle by using RuntimeScalar?

Example of RuntimeScalar value method body:
<pre>
@Override
public T value() {
    try {
        return this.scalar.value();
    }  catch (final RuntimeException e) {
        throw e;
    } catch (final Exception e) {
        throw new RuntimeException(e);
    }
}
</pre>

**Comment by filfreire** [comment]
@yegor256 please read @rafamizes above comment

@rafamizes I'd suggest opening a new issue for the idea you're proposing, and you could submit a PR.

**Comment by rafamizes** [comment]
@filfreire 
If Yegor agree, I will submit a PR fot the RuntimeScalar and RuntimeFunc classes.

**Comment by yegor256** [comment]
@filfreire I think we just have to improve the `UncheckedScalar`. I agree that it should __not__ touch the `RuntimeException`.

**Comment by yegor256** [comment]
@rultor release, tag is `0.22.1`

**Comment by yegor256** [comment]
@filfreire @rafamizes I fixed the problem, try version 0.22.1

**Comment by rafamizes** [comment]
Ok, I'm going to ry version 0.22.1

**Comment by llorllale** [comment]
@filfreire can we close this?

**Comment by llorllale** [comment]
@filfreire can we close this?

**Comment by filfreire** [comment]
@llorllale apologies for the late response. We can close this. If there are any similar issues, I'll open another ticket.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
