### ISSUE TITLE
accept iterators, not only iterables

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#453]
Let's accept them.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#453` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @yegor256, total is [+4325](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @yegor256, total is [+4325](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.20.2`

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#453` is already assigned to @yegor256.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#453` is already assigned to @yegor256.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#453` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256, total is [+5230](http://www.0crat.com/u/yegor256).
