### ISSUE TITLE
TeeInput class should not close the OutputStream.

### ISSUE THREAD

**Issue by rafamizes** [yegor256/cactoos#454]
After analyzing the TeeInputStream code, I noticed that it closes both streams: "input" and "output".
Shouldn't TeeInput -- being a "Input" -- close only its inputStream attribute? In my opinion, there should be a kind of "TeeInputClosesOutput" decorator that closes both streams. On the other hand, TeeInput should only close its InputStream.
The code below will not work properly, because the Standard OutputStream got closed by TeeInput:
<pre>
new LengthOfInput(
      new TeeInput(
         "Cactoos Log test.",
          new OutputStreamAsOutput(System.out) // OutputStream is going to be closed.
      )
  ).value(); 
System.out.println("This message won't be output to the Console.");
</pre>
ps: original discussion here: https://disqus.com/home/discussion/yegor256/object_oriented_declarative_inputoutput_in_cactoos/#comment-3589035469

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@rafamizes would you be interested to contribute with a pull request (with a unit test that reproduces this problem)?

**Comment by rafamizes** [comment]
Yes, I'm interested.
How should I proceed? Do I need just to clone the Cactoos project and do the unit test?

**Comment by yegor256** [comment]
@rafamizes yes, please, fork the repo, create a unit test to reproduce the issue, then make a fix and submit a pull request.

**Comment by rafamizes** [comment]
Ok, I'm going to contribute.

**Comment by fabriciofx** [comment]
@rafamizes Did you submit the PR? Do you need any help?

**Comment by rafamizes** [comment]
Not Yet. i'll do it as soon as possible.

2018-01-03 14:39 GMT-02:00 Fabricio Cabral <notifications@github.com>:

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/454#issuecomment-382497772))

@llorllale Job [#454](https://github.com/yegor256/cactoos/issues/454) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/454#issuecomment-382497772))

@llorllale Thanks for your contribution, @rafamizes[/z](https://www.0crat.com/u/rafamizes)! If you would be a member of [the project](https://www.0crat.com/p/C63314D6Z), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
The job [#454](https://github.com/yegor256/cactoos/issues/454) assigned to @sharpler[/z](https://www.0crat.com/u/sharpler), here is [why](https://www.0crat.com/footprint/C63314D6Z/1222222356); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@sharpler[/z](https://www.0crat.com/u/sharpler) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by SharplEr** [comment]
@rafamizes PR was merged. You can close the issue.

**Comment by SharplEr** [comment]
@0crat waiting
Waiting for author reaction.

**Comment by SharplEr** [comment]
@rafamizes ping

**Comment by 0crat** [comment]
> @0crat waiting Waiting for author reaction. ([here](https://github.com/yegor256/cactoos/issues/454#issuecomment-388518931))

@SharplEr The impediment for [#454](https://github.com/yegor256/cactoos/issues/454) was registered successfully by @sharpler[/z](https://www.0crat.com/u/sharpler)

**Comment by llorllale** [comment]
@rafamizes ping

@SharplEr let's wait a little more please

**Comment by rafamizes** [comment]
Sorry to have kept you waiting.
Issue closed.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @sharpler[/z](https://www.0crat.com/u/sharpler), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by elenavolokhova** [comment]
@SharplEr According to our Policy:
>Some of ticket messages must mention all pull requests where the problem was actually fixed;

There is no direct message with the link to corresponding PR.
Please, confirm that you will follow this rule in future.

**Comment by elenavolokhova** [comment]
@rafamizes According to our [Policy](http://www.zerocracy.com/policy.html#42):
> Messages in a job always start with a name of a user they are addressed to;

Please, address all your messages in future tickets. Thanks!

**Comment by rafamizes** [comment]
@elenavolokhova
I got it. Thanks.

**Comment by elenavolokhova** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/454#issuecomment-389887571))

@elenavolokhova This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#454](https://github.com/yegor256/cactoos/issues/454) is not in scope
  * The job is waiting quality review verdict by @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) for 20hr
  * @sharpler[/z](https://www.0crat.com/u/sharpler) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%23454%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by SharplEr** [comment]
@elenavolokhova  confirm
PR was #820

**Comment by elenavolokhova** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @sharpler[/z](https://www.0crat.com/u/sharpler)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
