### ISSUE TITLE
MaxOf and MinOf

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#460]
Let's rename `Max` to `MaxOf`, `Min` to `MinOf` and make it possible to provide a list of primitives there, just like SumOf works. Also, I think we need to implement them the way `SumOf` works.

**Comment by bedward70** [comment]
Hi, Yegor!
I think it is impossible to support primitive arrays (like `SumOf`) in the `MaxOf` and `MinOf` classes:
1) We can't set the `Comparable` generic type in bodies of the constructors;
2) If `MaxOf` and `MinOf` are final classes,  we will not extend the classes with `Comparable` generic type;
3) If `MaxOf` and `MinOf` are rewritten with `Comparable` (without generics),  the input class type of the values will be lose. So, we will not get a result with origin class type.

In current time:
a) We can write implementations of `MaxOf` and `MinOf` for each primitive;
b) We can transform primitive arrays to an `Iterable` then  use `MaxOf` and `MinOf` constructors:
```
        final Iterable<Scalar<Long>> iterable = new Mapped<>(
            input -> () -> input,
            new ListOf<>(
                LongStream.of(10000000000L, 20000000000L, lvalue)
                    .boxed()
                    .collect(Collectors.toList()).iterator()
            )
        );
        final Long result = new MinOf<>(iterable).value();
```

**Comment by yegor256** [comment]
@bedward70 please, take a look at how `SumOf` is implemented. Can't we do the same with `MaxOf`? Can you give code example that doesn't work with `SumOf`?

**Comment by bedward70** [comment]
@yegor256 
Sorry for your time, but I will try to explain.

I consider the MaxOf must return generic original type.
For example:
```
public class App {
    public static void main(String[] args) throws Exception {
       final String max = new MaxOf<>(() -> "A",() -> "B").value();
    }
}
```

> please, take a look at how SumOf is implemented. Can't we do the same with MaxOf?

In current implementation if we add public 'MaxOf(final int... src)' constructor (no generic types in the constructor declaration), we can't set generic members.

If we do MaxOf like SumOf, we will get the Comparable interface only. So, we will have to use casting a result. I think it is terrible.
Example:
```
public final class MaxOf implements Scalar<Comparable> {

    private final Scalar<Comparable> result;

    public MaxOf(final int... src) {
        this(new Mapped<>(
            input -> () -> input,
            IntStream.of(src).boxed().collect(Collectors.toList())
        ));
    }

    public MaxOf(final Iterable<Scalar<Comparable>> iterable) {
        this.result = new Folded<>(
            new MaxFunc<>(),
            iterable
        );
    }

    @Override
    public Comparable value() throws Exception {
        return this.result.value();
    }
}

```
```
public class App {

    public static void main(String[] args) throws Exception {
       final MaxOf maxOf = new MaxOf(1, 2, 3, 15);
        Integer result = (Integer) maxOf.value();
        System.out.println(result);
    }
}
```
> Can you give code example that doesn't work with SumOf?

I can't give any example code. 
If java let to create new primitive type, I can't use new primitive type as result from SumOf.
The SumOf class declaration does not generic types. The SumOf is very limited and  we perform casting by Number methods.

**Comment by yegor256** [comment]
@bedward70 please, see the changes I made in https://github.com/yegor256/cactoos/commit/25dc45d7302c36cbe3f1eef4e7673f1597bcde32 What do you think about these `MinOf` and `MaxOf` classes? They are in version 0.24 already.

**Comment by bedward70** [comment]
@yegor256 the `MinOf` and `MaxOf` is OK with primitive types and their classes only. 
After this commit we lost the opportunity to use `Comparable` implementations:
```
public class App {
    public static void main(String[] args) throws Exception {
       final String max = new MaxOf<>(() -> "A",() -> "B").value();
    }
}
```
So, we also need the old `MinOf` and `MaxOf` implementations for all other [Comparable](https://docs.oracle.com/javase/8/docs/api/java/lang/Comparable.html) implementations. There are a lot of them, here are the famous ones:  `Calendar`, `Date`,  `Character`, `String`, `Timestamp`. 
An user can implement `Comparable` interface for his classes and can use `MinOf` and `MaxOf` classes.

**Comment by yegor256** [comment]
@bedward70 I guess we just need two new classes `HighestOf` and `LowestOf`  in order to work with `Comparable`s... What do you think?

**Comment by bedward70** [comment]
@yegor256 it is great. If we take `Max` and `Min`(with tests) before [25dc45d](https://github.com/yegor256/cactoos/commit/25dc45d7302c36cbe3f1eef4e7673f1597bcde32) commit and rename to `HighestOf` and `LowestOf`, we will able to do it easily.
Should I help?

**Comment by yegor256** [comment]
@bedward70 yes, please, go ahead. Thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.25.3`

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/cactoos#460`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#460` is not in scope.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/cactoos#460`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#460` is not in scope.
