### ISSUE TITLE
we need more Javadoc examples for scalars

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#461]
We need to add more usage examples to our classes Javadoc blocks. These classes need them very much:

  * `And`
  * `AndWithIndex`
  * `Folded`
  * `Max`, `Min`, `SumOf`, `NumberOf`
  * `RetryScalar`
  * `StickyScalar`, `SyncScalar` (mention my blog post there: http://www.yegor256.com/2017/10/17/lazy-loading-caching-sticky-cactoos.html )
  * `Ternary`

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#461` is in scope.

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @yegor256, total is [+5275](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#461` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@kkamkou this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [par.8](http://datum.zerocracy.com/pages/policy.html#8).

**Comment by 0crat** [comment]
@kkamkou this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [par.8](http://datum.zerocracy.com/pages/policy.html#8).

**Comment by kkamkou** [comment]
@yegor256 could you reset my profile the way I know what I can start.

**Comment by 0crat** [comment]
@kkamkou resigned from `gh:yegor256/cactoos#461`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#461` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by yegor256** [comment]
@kkamkou I guess you're good to go now, you have just 5 tasks in your agenda and it's the maximum you will get.

**Comment by 0crat** [comment]
@kkamkou resigned from `gh:yegor256/cactoos#461`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#461` assigned to @kkamkou, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment]
@kkamkou resigned from `gh:yegor256/cactoos#461`, please stop working.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#461` assigned to @kkamkou. The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read the [Policy](http://datum.zerocracy.com/pages/policy.html) and go ahead.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#461` assigned to @kkamkou  ([profile](http://www.0crat.com/u/kkamkou})). The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read the [Policy](http://datum.zerocracy.com/pages/policy.html) and go ahead.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#461` assigned to [@amihaiemil](http://www.0crat.com/u/amihaiemil}) (`DEV`). The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read [§4](http://datum.zerocracy.com/pages/policy.html#4), [§8](http://datum.zerocracy.com/pages/policy.html#8), and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by amihaiemil** [comment]
@0crat I refuse this one, not enough knowledge about the library in order to write Javadocs

**Comment by 0crat** [comment]
> @0crat I refuse this one, not enough knowledge about the library in order to write Javadocs  ([here](https://github.com/yegor256/cactoos/issues/461#issuecomment-359353962))

@amihaiemil Can't understand "I", try one of these:
  - `assign` Assign a performer to this issue
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Remove this issue from scope (WBS)
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `waiting` Register an impediment for a job

**Comment by amihaiemil** [comment]
@0crat resign

**Comment by 0crat** [comment]
> @0crat resign ([here](https://github.com/yegor256/cactoos/issues/461#issuecomment-359354130))

@amihaiemil The user @amihaiemil[/z](https://www.0crat.com/u/amihaiemil) resigned from [#461](https://github.com/yegor256/cactoos/issues/461), please stop working

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://datum.zerocracy.com/pages/policy.html#6): -15 points just awarded to @amihaiemil[/z](https://www.0crat.com/u/amihaiemil), total is [+30](https://www.0crat.com/u/amihaiemil)

**Comment by 0crat** [comment]
The job [#461](https://github.com/yegor256/cactoos/issues/461) assigned to @neonailol[/z](https://www.0crat.com/u/neonailol). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by neonailol** [comment]
@0crat waiting

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/cactoos/issues/461#issuecomment-361368846). You must always start your message with my name if you want to address it to me, see [§1](http://datum.zerocracy.com/pages/policy.html#1).

**Comment by neonailol** [comment]
@0crat waiting

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/cactoos/issues/461#issuecomment-361376877). You must always start your message with my name if you want to address it to me, see [§1](http://datum.zerocracy.com/pages/policy.html#1).

**Comment by neonailol** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/461#issuecomment-361667675))

@neonailol The impediment for [#461](https://github.com/yegor256/cactoos/issues/461) was registered successfully by @neonailol[/z](https://www.0crat.com/u/neonailol)

**Comment by amihaiemil** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/461#issuecomment-361848286))

@amihaiemil This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#461](https://github.com/yegor256/cactoos/issues/461) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 3mon
  * The role is `DEV`
  * The job is assigned to @neonailol[/z](https://www.0crat.com/u/neonailol) for [8days](http://datum.zerocracy.com/pages/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://datum.zerocracy.com/pages/policy.html#2) job
  * The job has an [impediment](http://datum.zerocracy.com/pages/policy.html#9)
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 30 minutes
  * These users are banned and won't be assigned:
    * @yegor256[/z](https://www.0crat.com/u/yegor256): This user reported the ticket
    * @kkamkou[/z](https://www.0crat.com/u/kkamkou): User was resigned from the ticket
    * @amihaiemil[/z](https://www.0crat.com/u/amihaiemil): User was resigned from the ticket

**Comment by neonailol** [comment]
@yegor256 PR #589 has been merged, task is done

**Comment by yegor256** [comment]
@neonailol thanks

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol), total is [+270](https://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment]
The job [#461](https://github.com/yegor256/cactoos/issues/461) is now out of scope
