### ISSUE TITLE
Mapped issue upgrading from 0.20.1 to 0.23

### ISSUE THREAD

**Issue by filfreire** [yegor256/cactoos#466]
When I upgrade from Cactoos 0.20.1 to 0.23, all the usages I had for
``` new Mapped<>( ...```
stopped being valid. 
Same happens for similar classes like Limited<>, Filtered<>, and others where arguments stopped being inferred and constructors cannot be resolved.

@yegor256 how do I fix my code to be compatible with newer version of Cactoos?

(related issue, where I found the problem, https://github.com/yegor256/rultor/issues/1199 )

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@filfreire you just change the order of arguments. Pay attention to the signatures of Map and other constructors - they are changed.

**Comment by filfreire** [comment]
@yegor256 thanks! I see now.
Closing this issue.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/cactoos#466`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#466` is not in scope.
