### ISSUE TITLE
README.md: Sprintf is obsolete

### ISSUE THREAD

**Issue by DronMDF** [yegor256/cactoos#47]
in this chapter: https://github.com/yegor256/cactoos#textstrings

This class renamed by #38 to FormattedText

**Comment by 0crat** [comment]
@dronmdf I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@DronMDF would be great if you can submit pull requests with these small changes :) Would be easier and faster.

**Comment by DronMDF** [comment]
Pull request without a issue is that good? In zerocracy will you pay me for this? :)

**Comment by DronMDF** [comment]
Fixed

**Comment by englishman** [comment]
Thank you!
