### ISSUE TITLE
Replace com.google.common.io.Files usage with Cactoos equivalent

### ISSUE THREAD

**Issue by filfreire** [yegor256/cactoos#470]
I'm working on https://github.com/yegor256/rultor/issues/1199

How do we replace with the equivalent Cactoos classes the following Guava calls:
On [ReleaseBinariesTest.java](https://github.com/yegor256/rultor/blob/7120bc52dc80e0e9b1d7e8816f2f74a519d0e6f4/src/test/java/com/rultor/agents/github/ReleaseBinariesTest.java):
```
Files.createParentDirs(bin) 
Files.write(content, bin)
```

On [Talks.java](https://github.com/yegor256/rultor/blob/5f2e7fa8f6fee577719239933068fb048a175fc9/src/main/java/com/rultor/spi/Talks.java):
```
Files.createTempDir().getAbsolutePath()
```

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@filfreire something like this:

```
bin.mkdirs();
new LengthOf(new TeeInput(content, bin)).value();
```

`Files.createTempDir()` can be replaced with `Files.createTempDirectory()` from JDK 7, I believe.

**Comment by filfreire** [comment]
@yegor256 thanks, your suggestions seem to work ok.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/cactoos#470`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#470` is not in scope.
