### ISSUE TITLE
Replace Predicate and Iterables with Cactoos equivalent

### ISSUE THREAD

**Issue by filfreire** [yegor256/cactoos#471]
I'm working on https://github.com/yegor256/rultor/issues/1199

How do we replace with the equivalent Cactoos classes the following Guava classes/calls:

[RqUser.java](https://github.com/yegor256/rultor/blob/5f2e7fa8f6fee577719239933068fb048a175fc9/src/main/java/com/rultor/web/RqUser.java)  (`Iterables.any(...)` and `Predicate`):
```
final boolean granted;
// ...
final Identity identity = this.identity();
granted = Iterables.any(
    readers,
    new Predicate<String>() {
        @Override
        public boolean apply(final String input) {
            return !identity.equals(Identity.ANONYMOUS)
                && input.trim().equals(identity.urn());
        }
    }
);
```

(edit: removed second question into new issue https://github.com/yegor256/cactoos/issues/476)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@filfreire I would kindly ask you to submit one problem per ticket, to avoid confusion and noise. Here, I will answer the first question only. You should use `Or`:

```java
final boolean granted;
// ...
final Identity identity = this.identity();
granted = new Or(
  r -> !identity.equals(Identity.ANONYMOUS) && r.trim().equals(identity.urn()),
  readers
);
```

**Comment by filfreire** [comment]
@yegor256 thanks, Moved second question into a new issue https://github.com/yegor256/cactoos/issues/476. I'm closing this issue, seems to work with your suggestion.

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/cactoos#471`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#471` is not in scope.
