### ISSUE TITLE
Replace EvictingQueue with Cactoos equivalent

### ISSUE THREAD

**Issue by filfreire** [yegor256/cactoos#472]
I'm working on https://github.com/yegor256/rultor/issues/1199

How do we replace with the equivalent Cactoos classes the following Guava class:
[Entry.java](https://github.com/yegor256/rultor/blob/master/src/main/java/com/rultor/Entry.java)
```
final Collection<Tick> ticks = Collections.synchronizedCollection(
    EvictingQueue.<Tick>create((int) TimeUnit.HOURS.toMinutes(1L))
);
```

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@filfreire we don't have that in Cactoos

**Comment by filfreire** [comment]
@yegor256 any tips/pointers on how I can implement it even without Cactoos to remove the dependency?

**Comment by yegor256** [comment]
@filfreire that's a difficult question. I don't even remember what that `EvictingQueue` is doing... :(

**Comment by llorllale** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/472#issuecomment-383213637))

@llorllale GitHub issue is still open, won't close

**Comment by llorllale** [comment]
@filfreire sorry, just realized that our [principles](http://www.elegantobjects.org/#principles) are incompatible with mutable objects, which a `Queue` necessarily needs to be if it is to be of any use.

**Comment by llorllale** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/472#issuecomment-383214304))

@llorllale The job [#472](https://github.com/yegor256/cactoos/issues/472) is now out of scope

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
