### ISSUE TITLE
AndInThreads

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#473]
Let's create a new version of `And` that works in multiple threads.

**Comment by yegor256** [comment]
@rultor release, tag is `0.25`

**Comment by yegor256** [comment]
@rultor release, tag is `0.25.1`

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/cactoos#473`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#473` is not in scope.
