### ISSUE TITLE
Replace Guava Iterables.removeIf with Cactoos equivalent

### ISSUE THREAD

**Issue by filfreire** [yegor256/cactoos#476]
I'm working on https://github.com/yegor256/rultor/issues/1199

How do we replace with the equivalent Cactoos class the following Guava class/call:

[DyTalks.java](https://github.com/yegor256/rultor/blob/5f2e7fa8f6fee577719239933068fb048a175fc9/src/main/java/com/rultor/dynamo/DyTalks.java)  (`Iterables.removeIf(...)`):
```
Iterables.removeIf(
    this.region.table(DyTalks.TBL)
        .frame()
        .through(new QueryValve().withLimit(1))
        .where(DyTalks.HASH, name),
    item -> true
);
```

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by filfreire** [comment]
@yegor256 FYI

**Comment by yegor256** [comment]
@filfreire we don't have this in Cactoos yet...

**Comment by filfreire** [comment]
@yegor256 do we have an issue to account for it's development?

**Comment by yegor256** [comment]
@filfreire please feel free to submit one

**Comment by filfreire** [comment]
@llorllale I remember I had tried to use a `Filtered` approach but was unable to come with a working solution similar to the `Iterables.removeIf(...)`

But I believe this is still a valid "feature" request.

**Comment by llorllale** [comment]
@filfreire yeah, I think we currently don't have anything like this. Do you have any suggestions?

From what I see, what we need is to *consume* the `Iterator`/`Iterable`, not the elements contained therein.

Perhaps a special-purpose `BiProc`? Something like (excuse the generic mess):

```java
public final class Consume<T> implements BiProc<Proc<Iterator<T>>, Iterator<T>> {
   ....
}
```

Performing all initialization through a ctor (like eg. if we would implement `Scalar`) would look more elegant, but there is nothing to return here. This is all about triggering side effects.

WDYT?

**Comment by llorllale** [comment]
@filfreire another idea: let's have a scalar called `RemoveIf`. WDYT?

```java
public final class RemoveIf extends NumberEnvelope {
    // ctor
    public <T> RemoveIf(Iterator<T>, Func<T, Boolean> predicate) {}
}

new RemoveIf(
    iterator,  //assuming Iterator<String>
    i -> i.startsWith("filfreire")
).value();  //returns number of removed elements
```

**Comment by llorllale** [comment]
@filfreire ping

**Comment by filfreire** [comment]
@llorllale I like the idea! Do you think that in our case the `RemoveIf` would be the best name for the class?

**Comment by llorllale** [comment]
@filfreire I'm not too comfortable with that name to be honest. But, we'll be calling `Iterator.remove()`, so there's that. Do you have a better suggestion?

**Comment by Vatavuk** [comment]
@llorllale @filfreire 
We can do this with `iterator.LengthOf` and `iterator.Filtered`:
If we want to delete each element in the list:
```java
new LengthOf(
    new Filtered<>(
        input -> { iterator.remove() ; return true;},
        iterator
    )
).intValue();
```
If we want to delete specific elements:
```java
new LengthOf(
    new Mapped<>(
        input -> { iterator.remove(); return iterator; },
        new Filtered<>(
            input -> input.equals("someStr"),
            iterator
        )
    )
).intValue();
```
In both cases the result is equal to number of removed elements

**Comment by llorllale** [comment]
@Vatavuk ok, I suppose adding a specialized `RemoveIf` would be too much.

@filfreire would you be satisfied combining these primitives like @Vatavuk showed?

**Comment by filfreire** [comment]
@llorllale I'll give it a try and then I'll follow-up and hopefully we can close this issue.

**Comment by llorllale** [comment]
@filfreire ping

**Comment by llorllale** [comment]
@filfreire can we close this?

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#476` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
