### ISSUE TITLE
RangeOf Comparable<T>

### ISSUE THREAD

**Issue by svendiedrichsen** [yegor256/cactoos#478]
@yegor256 Would it be interesting to have a `RangeOf` implementation for `Comparable<T>` instances? Example PR follows.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@svendiedrichsen good idea, would be great to have these ctors too:

```java
new RangeOf(1, 10);
new RangeOf(1L, 10L);
new RangeOf('a', 'z');
```

**Comment by yegor256** [comment]
@svendiedrichsen maybe we have to delete `NaturalNumbers`...

**Comment by svendiedrichsen** [comment]
@yegor256 I have removed NULL handling and added convenience classes/constructors
`new RangeOf.Integer(int,int)`
`new RangeOf.Long(long,long)`
`new RangeOf.Character(char,char)`
Would you like me to remove now obsolete classes `NaturalNumbers` etc. ?

**Comment by yegor256** [comment]
@svendiedrichsen yes, `NaturalNumbers` is not required anymore, let's delete it.

**Comment by svendiedrichsen** [comment]
@yegor256 done.

**Comment by svendiedrichsen** [comment]
Changes merged.
