### ISSUE TITLE
SyncIterator<T>

### ISSUE THREAD

**Issue by svendiedrichsen** [yegor256/cactoos#482]
@yegor256 How about a `SyncIterator<T>` which uses a `ReentrantReadWriteLock`?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@svendiedrichsen good idea, please make changes to `SyncIterator` and submit a PR, if you can.

**Comment by svendiedrichsen** [comment]
Sorry, my fault, you created a `SyncIterable`. I will create a `SyncIterator` as proposed.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#482` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#482](https://github.com/yegor256/cactoos/issues/482) was not in scope
