### ISSUE TITLE
StringUtils methods into org.cactoos.text

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#49]
Let's create classes for all methods from Apache `StringUtils`.

**Comment by fabriciofx** [comment]
@yegor256 Are you doing it or anyone could try it?

**Comment by englishman** [comment]
@fabriciofx I think we should start from adding some issues with specific class names for new functionality to split work then between developers.

**Comment by fabriciofx** [comment]
@englishman I agree. Could you start? :)

**Comment by yegor256** [comment]
@fabriciofx @englishman go ahead guys, I'm not touching this.

**Comment by englishman** [comment]
@fabriciofx i'm on a small vacation. Will come back on this on Monday.

**Comment by fabriciofx** [comment]
@englishman Ok. Do you mind if I advance with some code? And have a nice vacation! :)

**Comment by englishman** [comment]
@fabriciofx absolutely no :+1: go ahead!

**Comment by fabriciofx** [comment]
@englishman 👍

**Comment by fabriciofx** [comment]
@yegor256 I think you can close this issue, because these commits have been opened as individual issues. WDYT?

**Comment by yegor256** [comment]
@fabriciofx right, closing
