### ISSUE TITLE
MapEntry support for functions

### ISSUE THREAD

**Issue by ashtonhogan** [yegor256/cactoos#490]
Currently it is not possible to create `MapOf` and add `MapEntry` objects that contain `Enum` and `Function` respectively. For example, the following:

```
                    new MapOf<>(
                            new MapEntry<>(
                                    John_Doe_Enum,
                                    () -> {
                                             return new Foo("John Doe").printName();
                                    }
                            )
                    )
```

Will issue this error:

> incompatible types: cannot infer type arguments for MapEntry<>
>     reason: cannot infer type-variable(s) K,V
>       (argument mismatch; Object is not a functional interface)
>   where K,V are type-variables:
>     K extends Object declared in class MapEntry
>     V extends Object declared in class MapEntry

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@ashtonhogan works for me, see e57d946

**Comment by ashtonhogan** [comment]
@yegor256 I read the conversation, it contains many good points. I see that you have reached a conclusion historically already. My reason for doing this is that I think it tightly couples NoNull to other classes and makes it difficult to remember and even more difficult for a new user to understand.

Should classes ever be nested? Assuming no static...

1. public/protected nested class: Either migrate it to the parent class or move it into its own class. Why would a famous celebrity live in their mothers basement? This is being used publicly, it should be independent

2. private nested class: I guess you could use this to organise some of your methods but I can't think of any good reason to use it...

**Comment by yegor256** [comment]
@ashtonhogan it seems that this comment is made to the wrong ticket...

**Comment by ashtonhogan** [comment]
@yegor256 not sure if it's possible or not but another point worth mentioning here is that it would be beneficial to have the ability to pass exceptions thrown from functions added to a `MapEntry`

**Comment by yegor256** [comment]
@ashtonhogan I don't understand the problem. Please, submit a new ticket, if the original one is fixed. Please, keep one ticket per problem. Thanks.

**Comment by ashtonhogan** [comment]
@yegor256 This is part of the same feature, in the above example, this part won't work:

```
() -> {
    return new Foo("John Doe").printName();
}
```

If the `printName()` method throws an Exception you will have to change the above to:

```
try {
    () -> {
        return new Foo("John Doe").printName();
    }
} catch (Exception ex) {
    ...
}
```

**Comment by yegor256** [comment]
@ashtonhogan works for me, see 70eda3c

**Comment by ashtonhogan** [comment]
@yegor256 I played around with it. It took me a while to wrap my head around `Scalar` but now that I have this no longer makes sense.

PS: https://twitter.com/TheAshtonHogan/status/950726849331679233

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#490` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#490` was not in scope
