### ISSUE TITLE
Remove all @SafeVarargs usages

### ISSUE THREAD

**Issue by ashtonhogan** [yegor256/cactoos#494]
We could remove all `@SafeVarargs` since the fewer annotations we need the better.

For example, https://github.com/yegor256/cactoos/blob/e57d9462adac0a9131135877e4e202a5082d0294/src/main/java/org/cactoos/map/MapOf.java#L60

If you remove this, you get the warning:

> [unchecked] Possible heap pollution from parameterized vararg type Entry<X,Y>

An alternative could be to change the constructor to something like:

```
public MapOf(final Map<K, V> map) {
  this.putAll(...);
}
```

The usage of `MapOf` for instantiation with values will then look something like:

`new MapOf(Map.of(...));`

Or you could implement your own `Map.of` if so inclined

**Comment by fabriciofx** [comment]
@ashtonhogan If we do that we'll add execution code into constructors just what we want avoid. Is it `Map.of` a kind of static factory? If yes, it's another thing we want avoid. To more details why, please read [here](http://www.yegor256.com/2015/05/07/ctors-must-be-code-free.html) and [here](http://www.yegor256.com/2017/11/14/static-factory-methods.html).

**Comment by ashtonhogan** [comment]
@fabriciofx I guess `Scalar<Map<K, V>> map` looks a bit ugly?

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
