### ISSUE TITLE
NoNulls for Iterable, Iterator, List, Collection, Map

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#498]
Let's create a set of decorators that prevent NULL from appearing in `Iterable`, `Iterator`, `List`, `Collection`, and `Map`.

**Comment by yegor256** [comment]
@rultor release, tag is `0.27`

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:yegor256/cactoos#498`.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#498` is not in scope.

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see par.19: -5 points just awarded to @yegor256, total is [+6390](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256, total is [+6420](http://www.0crat.com/u/yegor256).
