### ISSUE TITLE
`FuncWithFallback` has too many constructors.

### ISSUE THREAD

**Issue by Zefick** [yegor256/cactoos#499]
It's hard to use `FuncWithFallback` class with lambdas because plenty of constructors cause ambiguities.
There is a total of 20 constructors which is too many. And only three of them have individual tests.

Instead of using the direct constructor
`FuncWithFallback(Proc<X> proc, Proc<Throwable> fbk)` 
someone can just write 
`new FuncWithFallback(new FuncOf<>(proc), new FuncOf<>(fbk))`. 

Please consider not to add extra constructors to other classes without the need.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@Zefick feel free to remove those who you think are not a good fit for this class.

**Comment by Zhiyuan-Amos** [comment]
This issue should be closed following #508

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#499` is not assigned, can't get start time

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#499` was not in scope
