### ISSUE TITLE
Why does Func.apply method have IOException in its declaration?

### ISSUE THREAD

**Issue by pistriak** [yegor256/cactoos#5]
It'd be better to replace IOException with Exception.
What do you think?

**Comment by 0crat** [comment]
@pistriak I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by englishman** [comment]
@pistriak what do you think to use only unchecked exceptions in the library?

**Comment by yegor256** [comment]
@pistriak I agree, feel free to submit a pull request

**Comment by yegor256** [comment]
@englishman we can, but there are many JDK classes that use `IOException` and other checked exceptions.

**Comment by yegor256** [comment]
@pistriak it's fixed, please close the ticket

**Comment by fabriciofx** [comment]
@yegor256 Have been past 21 days. What do you think to close this issue? Thanks for your attention!
