### ISSUE TITLE
GzipInput and GzipOutput

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#502]
Let's implement a way to encode and decode `Bytes` using `Gzip` compress algorithm. I'll handle it.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by fabriciofx** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/502#issuecomment-356503302))

@fabriciofx You can't do that, unless you have one of these roles: ARC, PO. Your current roles are: REV.

**Comment by fabriciofx** [comment]
@yegor256 Could you assing this issue to me? I've already submited a PR. Thanks in advance!

**Comment by yegor256** [comment]
@0crat assign @fabriciofx

**Comment by 0crat** [comment]
> @0crat assign @fabriciofx  ([here](https://github.com/yegor256/cactoos/issues/502#issuecomment-356587683))

@yegor256 The job [#502](https://github.com/yegor256/cactoos/issues/502) assigned to fabriciofx. The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Bug was reported, see [[§29](http://datum.zerocracy.com/pages/policy.html#29)](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to [@fabriciofx](http://www.0crat.com/u/fabriciofx), total is [+120](http://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [[§19](http://datum.zerocracy.com/pages/policy.html#19)](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to [@yegor256](http://www.0crat.com/u/yegor256), total is [+6715](http://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
[@fabriciofx](http://www.0crat.com/u/fabriciofx) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by fabriciofx** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/502#issuecomment-358112017))

@fabriciofx This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#502](https://github.com/yegor256/cactoos/issues/502) is in scope
  * The job is assigned to @fabriciofx[/z](http://www.0crat.com/u/fabriciofx)
  * These users are banned: @fabriciofx[/z](http://www.0crat.com/u/fabriciofx)[/z](http://www.0crat.com/u/fabriciofx): This user reported the ticket

**Comment by 0crat** [comment]
@fabriciofx[/z](http://www.0crat.com/u/fabriciofx) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#502](https://github.com/yegor256/cactoos/issues/502), please stop working

**Comment by 0crat** [comment]
The job [#502](https://github.com/yegor256/cactoos/issues/502) assigned to @rexim[/z](https://www.0crat.com/u/rexim). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by rexim** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/502#issuecomment-361884829))

@rexim The impediment for [#502](https://github.com/yegor256/cactoos/issues/502) was registered successfully by @rexim[/z](https://www.0crat.com/u/rexim)

**Comment by 0crat** [comment]
Job [#502](https://github.com/yegor256/cactoos/issues/502) is already in scope

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @rexim[/z](https://www.0crat.com/u/rexim), total is [+135](https://www.0crat.com/u/rexim)

**Comment by 0crat** [comment]
The job [#502](https://github.com/yegor256/cactoos/issues/502) is now out of scope
