### ISSUE TITLE
ZipInput and ZipOutput

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#506]
Let's implement a way to encode and decode `Bytes` using Zip compression algorithm. I'll handle it.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by fabriciofx** [comment]
@0crat assign to me

**Comment by 0crat** [comment]
You need to ask somebody to invite you: https://github.com/zerocracy/datum#invite-only

**Comment by fabriciofx** [comment]
@yegor256 Could you assing this issue to me? Thanks in advance.

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/506#issuecomment-357191866))

@fabriciofx This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#506](https://github.com/yegor256/cactoos/issues/506) is not in scope

**Comment by fabriciofx** [comment]
@0crat status

**Comment by 0crat** [comment]
Are you speaking to me or about me? You must always start your message with my name if you want to address it to me, see [§1](http://datum.zerocracy.com/pages/policy.html#1).

**Comment by fabriciofx** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/506#issuecomment-357820640))

@fabriciofx This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#506](https://github.com/yegor256/cactoos/issues/506) is not in scope

**Comment by ashtonhogan** [comment]
@fabriciofx are you still working on this?

**Comment by llorllale** [comment]
@fabriciofx can you provide a use case?

**Comment by llorllale** [comment]
@fabriciofx ping

**Comment by llorllale** [comment]
@fabriciofx closed due to inactivity.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
