### ISSUE TITLE
Let's update Copyright notice to 2018

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#512]
Let's update Copyright notice to 2018. I'll handle it.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by fabriciofx** [comment]
Closed by #513 .

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#512` is not assigned, can't get start time

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#512` was not in scope
