### ISSUE TITLE
Async event functionality

### ISSUE THREAD

**Issue by svendiedrichsen** [yegor256/cactoos#514]
@yegor256 What do you think about some async event handling? Something like Guava `EventBus` but perhaps more like usual listeners and not using reflection.
There is the ticket #414 that handles non-blocking IO which in some way or another also needs to tackle async event handling.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@svendiedrichsen how much of "good OOP" we can add there? It seems Guava is doing fine as is. Or not?

**Comment by svendiedrichsen** [comment]
sure.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#514` is not assigned, can't get start time

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#514` was not in scope
