### ISSUE TITLE
DigestOf (MD5, SHA-1 and SHA-256)

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#515]
Implements the MD5, SHA-1 and SHA-256 message digest checksums. I'll handle it.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by fabriciofx** [comment]
@yegor256 Could you assing this issue to me? Thanks in advance.

**Comment by fabriciofx** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/515#issuecomment-357195308))

@fabriciofx This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#515](https://github.com/yegor256/cactoos/issues/515) is not in scope

**Comment by fabriciofx** [comment]
@yegor256 As the PR #516 was merged, I'll close this issue.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#515` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#515](https://github.com/yegor256/cactoos/issues/515) was not in scope
