### ISSUE TITLE
Same exception type for basic classes

### ISSUE THREAD

**Issue by martin-robo** [yegor256/cactoos#518]
`Scalar` throws `Exception` on access, `Text` throws `IOException`. This enforces exception handling on simple conversion of numbers to text. I think it would be handy to have all basic classes throw the same type of exception.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@martin-robo I agree, let's use `Exception` everywhere. Please, submit a pull request, if you can.

**Comment by martin-robo** [comment]
@yegor256 Though, I'd like to, I am afraid I won't find the time to do this. It would be my first productive work on Github and I have never worked with Git before. So I think I'd need some time to get it all working. Could you please assign the task to another developer? Thank you and keep up the good work.

**Comment by yegor256** [comment]
@martin-robo sure, no worries. Thanks!

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/518#issuecomment-382083549))

@llorllale Job [#518](https://github.com/yegor256/cactoos/issues/518) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/518#issuecomment-382083549))

@llorllale Thanks for your contribution, @martin-robo[/z](https://www.0crat.com/u/martin-robo)! If you would be a member of [the project](https://www.0crat.com/p/C63314D6Z), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
The job [#518](https://github.com/yegor256/cactoos/issues/518) assigned to @pbenety[/z](https://www.0crat.com/u/pbenety), here is [why](https://www.0crat.com/footprint/C63314D6Z/1222145145); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@pbenety[/z](https://www.0crat.com/u/pbenety) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by pbenety** [comment]
@0crat waiting review #835

**Comment by pbenety** [comment]
@martin-robo please close this issue. The PR #835 was merged.

**Comment by llorllale** [comment]
@martin-robo ping

**Comment by martin-robo** [comment]
Thank you all!

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @pbenety[/z](https://www.0crat.com/u/pbenety), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#518](https://github.com/yegor256/cactoos/issues/518) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/cactoos/issues/518#issuecomment-389573530))

@elenavolokhova Thanks, but quality review is not required in this job

**Comment by pbenety** [comment]
@llorllale in this issue, @0crat is in a inconsistent state.

**Comment by llorllale** [comment]
@pbenety see zerocracy/farm#1018
