### ISSUE TITLE
LengthOf must be a Number

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#519]
Let's make it extend `Number`

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#519` assigned to @yegor256  ([profile](http://www.0crat.com/u/yegor256})). The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read the [Policy](http://datum.zerocracy.com/pages/policy.html) and go ahead.

**Comment by 0crat** [comment]
Bug was reported: +15 points just awarded to @yegor256, total is [+6560](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [par.19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256, total is [+6560](http://www.0crat.com/u/yegor256).

**Comment by yegor256** [comment]
@rultor release, tag is `0.28`

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#519` is now out of scope.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @yegor256, total is [+6590](http://www.0crat.com/u/yegor256).
