### ISSUE TITLE
LengthOf must also implement Scalar

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#520]
In order to throw `IOException`

**Comment by yegor256** [comment]
@rultor release, tag is `0.28.1`

**Comment by yegor256** [comment]
@rultor release, tag is `0.28.1`

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#520` is not assigned, can't get start time

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#520` was not in scope
