### ISSUE TITLE
Question: next() in Endless iterator seems overly complicated

### ISSUE THREAD

**Issue by Timmeey** [yegor256/cactoos#523]
```
  @Override
  public T next() {
    return new IterableOf<T>(this.origin.value()).iterator().next();
  }
```

in [Iterator/endless.java](https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/iterator/Endless.java)

Seems overly complicated and "slow".

Why do we need to wrap the contained value in a new Iterable and iterator EVERY time we call next? This doesn't help against a mutable value (since it does not create a copy of the contained value (neither should it))

Why can't we just return the contained scalar.value()? It is an endlessiterator which always returns the same value

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@Timmeey I agree, please submit a pull request

**Comment by 0crat** [comment]
The job [#523](https://github.com/yegor256/cactoos/issues/523) assigned to @vssekorin[/z](https://www.0crat.com/u/vssekorin), here is [why](https://www.0crat.com/footprint/C63314D6Z/1231433168); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by VsSekorin** [comment]
@0crat wait #810

**Comment by 0crat** [comment]
> @0crat wait #810  ([here](https://github.com/yegor256/cactoos/issues/523#issuecomment-386420467))

@VsSekorin The impediment for [#523](https://github.com/yegor256/cactoos/issues/523) was registered successfully by @vssekorin[/z](https://www.0crat.com/u/vssekorin)

**Comment by VsSekorin** [comment]
@Timmeey PR was merged.

**Comment by llorllale** [comment]
@Timmeey ping

**Comment by VsSekorin** [comment]
@llorllale Can you close this PR?

**Comment by llorllale** [comment]
@VsSekorin ok, thanks.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @vssekorin[/z](https://www.0crat.com/u/vssekorin), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#523](https://github.com/yegor256/cactoos/issues/523) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
