### ISSUE TITLE
Question: Should we remove or not "No implementation  inheritance" principle?

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#524]
@yegor256 One of Cactoos' principles is *No implementation inheritance* but we're using it (like in Decorating Envelopes). So, I think we should review this principle and, if makes sense, remove it from principles list. WDYT?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by alex-semenyuk** [comment]
I think envelop decorating it's a different thing then implementation inheritance, looks here http://www.yegor256.com/2017/01/31/decorating-envelopes.html compare with http://www.yegor256.com/2016/09/13/inheritance-is-procedural.html. Yeah, it will be nice to have the keyword decorates.

**Comment by fabriciofx** [comment]
@alex-semenyuk I agree with you, but the principle is clear: "No implementation inheritance". So, if "envelop decorating" is fine, I think we should change this principle to something like "Inheritance only for envelop decorating". WDYT?

**Comment by yegor256** [comment]
@fabriciofx yes, I agree, let's modify it and explicitly mention that we are OK with decorating envelopes and nothing else. Please, submit a PR.

**Comment by fabriciofx** [comment]
@yegor256 Could you assing this issue to me? Thanks in advance.

**Comment by fabriciofx** [comment]
@yegor256 As the PR #527 was merged, I'll close this issue.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#524` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#524](https://github.com/yegor256/cactoos/issues/524) was not in scope
