### ISSUE TITLE
Question: All *Envelope classes should not  be abstract?

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#525]
@yegor256 I think all *Envelope classes should be abstract to avoid instantiation, because not make sense these classes make instances. WDYT?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@fabriciofx yes, I agree, let's do it. Please, submit a PR.

**Comment by fabriciofx** [comment]
@0crat apply

**Comment by 0crat** [comment]
> @0crat apply ([here](https://github.com/yegor256/cactoos/issues/525#issuecomment-356287657))

@fabriciofx Can't understand "apply", try one of these:
  - `assign` Assign a performer to this issue
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Remove this issue from scope (WBS)
  - `resign` Resign from this issue
  - `version` Print current version of the bot
  - `waiting` Register an impediment for a job

**Comment by fabriciofx** [comment]
@0crat assign to me

**Comment by 0crat** [comment]
> @0crat assign to me ([here](https://github.com/yegor256/cactoos/issues/525#issuecomment-356287947))

@fabriciofx Argument "to" doesn't match regex "me|@[a-zA-Z0-9\-]+"

**Comment by fabriciofx** [comment]
@0crat assign @fabriciofx

**Comment by 0crat** [comment]
> @0crat assign @fabriciofx ([here](https://github.com/yegor256/cactoos/issues/525#issuecomment-356288119))

@fabriciofx You need to have one of these roles in order to do what you're trying to do: ARC, PO. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "fabriciofx").

**Comment by fabriciofx** [comment]
@yegor256 Could you assign this issue to me? Thanks!

**Comment by yegor256** [comment]
@fabriciofx it's against our principles, we should not assign jobs to their reporters.

**Comment by fabriciofx** [comment]
@yegor256 Good question: why not? I think interesting to have a kind of *priority* who reporter a issue, solve it. I think it will motivate the reporter to find and fix the bugs. What do you think? If you are against, I'd like to know, just for information.

**Comment by yegor256** [comment]
@fabriciofx Here is the reason: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#1-keep-it-one-on-one

**Comment by fabriciofx** [comment]
@yegor256 As the PR #528 was merged, I'll close this issue.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#525` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#525](https://github.com/yegor256/cactoos/issues/525) was not in scope
