### ISSUE TITLE
Document PR workflow

### ISSUE THREAD

**Issue by allanws** [yegor256/cactoos#526]
As a 
   PROJECT MEMBER 
I want to 
   HAVE DOCUMENTATION ABOUT THE PR WORKFLOW 
so 
   I CAN PERFORM MY TASKS PROPERLY

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by fabriciofx** [comment]
@allanws I used the same workflow in another project. If you've interested, you can borrow the steps from [here](https://github.com/ifpe-cti/saudegaranhuns) and adapt to english (the original document is in pt_BR).

**Comment by allanws** [comment]
@fabriciofx, the documentation from the link above just covers the forking/PR submission. I'd like to have covered also the rest of the revision process (approval/comments/re-assignment of tasks/etc).
I'm happy to do it if that's the case. @yegor256, do you need to approve that?

**Comment by allanws** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/526#issuecomment-355800922))

@allanws Can't understand "waiting", try one of these:
  - `assign` Assign a performer to this issue
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Remove this issue from scope (WBS)
  - `resign` Resign from this issue
  - `version` Print current version of the bot

**Comment by yegor256** [comment]
@allanws check the policy: http://datum.zerocracy.com/pages/policy.html It's not enough? See the new section for "Reviewers"

**Comment by allanws** [comment]
@yegor256 now it's fine by me. Short and sharp.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#526` is not assigned, can't get start time

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/cactoos#526` was not in scope
