### ISSUE TITLE
IterableAsList.java:56-58: Needs cached `LengthOfIterable`...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#53]
The puzzle `39-e7c34bd5` in [`src/main/java/org/cactoos/list/IterableAsList.java`](https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/list/IterableAsList.java) (lines 56-58) has to be resolved: "Needs cached `LengthOfIterable` version to improve `IterableAsList` performance. Now each call to `size()` goes through all iterable to calculate the size."

The puzzle was created by g4s8 on 27-May-17. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and
[about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by 0pdd** [comment]
> @0pdd I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/...

I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by englishman** [comment]
@g4s8 how to work with pazzles? Could you, pls, explain or, better, add some quick manual somwhere.

**Comment by g4s8** [comment]
@englishman here posts about it:
http://www.yegor256.com/2017/04/05/pdd-in-action.html
http://www.yegor256.com/2009/03/04/pdd.html

here syntax reference: https://github.com/yegor256/pdd#how-to-format

I'd suggest to create test repo and play with pdd bot to understand how it works

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved
