### ISSUE TITLE
Is there any sort of prioritization?

### ISSUE THREAD

**Issue by allanwsilva** [yegor256/cactoos#530]
Or just pick anything randomly?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@allanws what are you talking about?

**Comment by allanws** [comment]
Sorry, I'll add a bit more of verbosity to my comments. I mean is there any sort of priority to the opened issues? Who decides what is a priority or not?

**Comment by llorllale** [comment]
@allanwsilva this project is being managed via [Zerocracy](http://www.zerocracy.com/). 

As per our policy, when we include a ticket in the [scope](http://www.zerocracy.com/policy.html#14) it is automatically assigned by [0crat](www.0crat.com) to a DEV (depending on some variables).

The architect is responsible for managing the scope.

Does this answer your question?

You can read more on how all this works via the policy page I linked to.

**Comment by llorllale** [comment]
@allanwsilva feel free to open another ticket with any other question you may have

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
