### ISSUE TITLE
Partitioned Iterable and Iterator

### ISSUE THREAD

**Issue by svendiedrichsen** [yegor256/cactoos#531]
@yegor256 How about a partitioned Iterable and Iterator? See http://google.github.io/guava/releases/snapshot/api/docs/com/google/common/collect/Iterables.html#partition-java.lang.Iterable-int-

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@svendiedrichsen I don't know what it's for, but have nothing against it. Please, contribute with a pull request.

**Comment by svendiedrichsen** [comment]
Guava Javadoc
> Divides an iterable into unmodifiable sublists of the given size (the final iterable may be smaller).

**Comment by fabriciofx** [comment]
@svendiedrichsen What's the difference between your `Partitioned`  and the `Limited` class? Is not enough add more constructors in `Limited` instead of make a new `Partitioned` class?

**Comment by svendiedrichsen** [comment]
@fabriciofx `Limited` limits the number of elements returned by the underlying iterator. `Partitioned` returns _all_ of the elements of the underlying iterator partitioned into lists.

**Comment by svendiedrichsen** [comment]
PR is merged. Closing this ticket now.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#531` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#531](https://github.com/yegor256/cactoos/issues/531) was not in scope
