### ISSUE TITLE
AvgOf produces overflow for large values

### ISSUE THREAD

**Issue by vmotsak** [yegor256/cactoos#532]
```
new AvgOf(
          new ListOf<>(Double.MAX_VALUE, Double.MAX_VALUE).toArray(new Double[2])
).doubleValue();
``` 
returns an `Infinity` but should be `Double.MAX_VALUE`

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@vmotsak definitely a bug, thanks for reporting (although, I have no idea how this can be fixed)

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#532` is now in scope, role is `DEV`.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#532` assigned to [@allanws](http://www.0crat.com/u/allanws}) (`DEV`). The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read [§4](http://datum.zerocracy.com/pages/policy.html#4), [§8](http://datum.zerocracy.com/pages/policy.html#8), and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by svendiedrichsen** [comment]
@yegor256 i suppose you will have to use BigInteger BigDecimal for your computations. Having the usual performance impact surely.

**Comment by vmotsak** [comment]
This can be fixed by calculating the mean value, something like
```
double mean(Double[] ary) {
        double avg = 0;
        int t = 1;
        for (double x : ary) {
            avg += (x - avg) / t;
            ++t;
        }
        return avg;
    }
```

**Comment by svendiedrichsen** [comment]
You might run into strange double precision problems though. Probably not with your example but to have AvgOf work consistently correct you may.
See for i.e. http://bloodredsun.com/2011/06/22/doubles-financial-calculations/ about this.

**Comment by svendiedrichsen** [comment]
Please see the average of `new Double[]{100.0, 100.266}` using the above mentioned `mean` method. Should be `100.133` of course. But it isn't.

**Comment by svendiedrichsen** [comment]
I have refactored the AvgOf code to fix number overflow, fix precision problem and cut code repetition. Please have a look here: https://github.com/svendiedrichsen/cactoos/commit/358b7f19469669df00eeea4c2ec3c5fbffd5ac8e

**Comment by 0crat** [comment]
[@allanws](http://www.0crat.com/u/allanws) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@allanws[/z](http://www.0crat.com/u/allanws) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by allanws** [comment]
@yegor256 please have a look at my [latest comment](https://github.com/yegor256/cactoos/pull/543#issuecomment-358869573) on this issue.

**Comment by allanws** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/532#issuecomment-359209285))

@allanws The impediment was registered successfully

**Comment by yegor256** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/532#issuecomment-359552318))

@yegor256 Job [#532](https://github.com/yegor256/cactoos/issues/532) is not assigned, can't put it on hold

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
Are you speaking to me or about me? You must always start your message with my name if you want to address it to me, see [§1](http://datum.zerocracy.com/pages/policy.html#1).

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/532#issuecomment-359553447))

@yegor256 This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#532](https://github.com/yegor256/cactoos/issues/532) is in scope
  * The job is not assigned to anyone
  * These users are banned: @vmotsak[/z](https://www.0crat.com/u/vmotsak): This user reported the ticket; @allanws[/z](https://www.0crat.com/u/allanws): User was resigned from the ticket

**Comment by yegor256** [comment]
@0crat assign @allanws

**Comment by 0crat** [comment]
> @0crat assign @allanws  ([here](https://github.com/yegor256/cactoos/issues/532#issuecomment-359555302))

@yegor256 The job [#532](https://github.com/yegor256/cactoos/issues/532) assigned to @allanws[/z](https://www.0crat.com/u/allanws). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html). @allanws[/z](https://www.0crat.com/u/allanws) is not a member of this project yet, but they can request to join. Check your [profile](https://www.0crat.com/u/allanws) and follow the instructions.

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+7780](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/532#issuecomment-359560797))

@yegor256 The impediment for [#532](https://github.com/yegor256/cactoos/issues/532) was registered successfully by @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by fabriciofx** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/532#issuecomment-360322501))

@fabriciofx This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#532](https://github.com/yegor256/cactoos/issues/532) is in scope for 16days
  * The role is `DEV`
  * The job is not assigned to anyone
  * These users are banned: @vmotsak[/z](https://www.0crat.com/u/vmotsak): This user reported the ticket; @allanws[/z](https://www.0crat.com/u/allanws): User was resigned from the ticket; @allanws[/z](https://www.0crat.com/u/allanws): User was resigned from the ticket

**Comment by 0crat** [comment]
The job [#532](https://github.com/yegor256/cactoos/issues/532) assigned to @rexim[/z](https://www.0crat.com/u/rexim). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @rexim[/z](https://www.0crat.com/u/rexim), total is [+45](https://www.0crat.com/u/rexim)

**Comment by 0crat** [comment]
The job [#532](https://github.com/yegor256/cactoos/issues/532) is now out of scope

**Comment by g4s8** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/532#issuecomment-367223579))

@g4s8 This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#532](https://github.com/yegor256/cactoos/issues/532) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%23532%27%7D) (restricted area)
