### ISSUE TITLE
TextOf additional ctors for InputStream

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#533]
Would be convenient to have an ability to do `new TextOf(inputStream)`.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#533` is now in scope, role is `DEV`.

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256, total is [+6680](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
The job [#533](https://github.com/yegor256/cactoos/issues/533) assigned to icok. The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by iCok** [comment]
@yegor256 the issue is implemented by my pr #553, so let's close it

**Comment by yegor256** [comment]
@iCok thanks!

**Comment by iCok** [comment]
@yegor256 How to make the job done for 0crat? On my boar agenta I still see this issue.

**Comment by 0crat** [comment]
@icok[/z](http://www.0crat.com/u/icok) resigned from [#533](https://github.com/yegor256/cactoos/issues/533), since the job is not in scope anymore

**Comment by 0crat** [comment]
The job [#533](https://github.com/yegor256/cactoos/issues/533) is now out of scope

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#533` is not assigned, can't get start time

**Comment by iCok** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/533#issuecomment-358078450))

@iCok This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#533](https://github.com/yegor256/cactoos/issues/533) is not in scope
