### ISSUE TITLE
ReplacedText empower with regex replacements

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#534]
Let's make it possible to do this:

```java
String text = new ReplacedText(
  "Hello, my DEAR friend!",
  Pattern.compile("[A-Z]+"),
  matcher -> Integer.toString(matcher.group(1).length())
).asString();
```

It should produce:

```
"1ello, my 4 friend!"
```

Internally it should something like [this](https://stackoverflow.com/a/9606141/187141).

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#534` is now in scope, role is `DEV`.

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @yegor256, total is [+6725](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#534` assigned to [@llorllale](http://www.0crat.com/u/llorllale}) (`DEV`). The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read [§4](http://datum.zerocracy.com/pages/policy.html#4), [§8](http://datum.zerocracy.com/pages/policy.html#8), and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
[@llorllale](http://www.0crat.com/u/llorllale) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by llorllale** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/534#issuecomment-357715196))

@llorllale The impediment was registered successfully

**Comment by 0crat** [comment]
@llorllale[/z](http://www.0crat.com/u/llorllale) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @llorllale[/z](http://www.0crat.com/u/llorllale), total is [+105](http://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#534](https://github.com/yegor256/cactoos/issues/534) is now out of scope
