### ISSUE TITLE
InputWithFallbackTest.readsAlternativeInputUri has an environmental dependency

### ISSUE THREAD

**Issue by llorllale** [yegor256/cactoos#537]
This test depends on the environment on which it is being run. Where I am running this, we have a proxy that filters out certain sites and returns an HTTP OK response with a text that this test is not expecting, hence it fails.

To make it more consistent and predictable, and since the requirement (#255) is to capture any `IOException`, we could perhaps refactor like this:

```java
    @Test
    public void readsAlternativeInputUri() {
        MatcherAssert.assertThat(
            "Can't read alternative source from URI",
            new TextOf(
                new InputWithFallback(
                    () -> { throw new IOException("Always fails!"); },
                    new InputOf("it works!")
                )
            ),
            new TextHasString(Matchers.endsWith("works!"))
        );
    }
```

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#537](https://github.com/yegor256/cactoos/issues/537) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to [@llorllale](http://www.0crat.com/u/llorllale), total is [+15](http://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#537](https://github.com/yegor256/cactoos/issues/537) assigned to @icok[/z](http://www.0crat.com/u/icok). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@icok[/z](https://www.0crat.com/u/icok) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@icok[/z](https://www.0crat.com/u/icok) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @icok[/z](https://www.0crat.com/u/icok) resigned from [#537](https://github.com/yegor256/cactoos/issues/537), please stop working

**Comment by 0crat** [comment]
The job [#537](https://github.com/yegor256/cactoos/issues/537) assigned to @driver733[/z](https://www.0crat.com/u/driver733). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by driver733** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/537#issuecomment-361285893))

@driver733 This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#537](https://github.com/yegor256/cactoos/issues/537) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 19days
  * The role is `DEV`
  * The job is assigned to @driver733[/z](https://www.0crat.com/u/driver733) for [2days](http://datum.zerocracy.com/pages/policy.html#8)
  * There is a monetary reward attached
  * @driver733[/z](https://www.0crat.com/u/driver733) will get 0.00 of their hourly rate for this job
  * The job doesn't have any [impediments](http://datum.zerocracy.com/pages/policy.html#9)
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 30 minutes
  * These users are banned and won't be assigned:
    * @llorllale[/z](https://www.0crat.com/u/llorllale): This user reported the ticket
    * @icok[/z](https://www.0crat.com/u/icok): User was resigned from the ticket

**Comment by driver733** [comment]
@llorllale
@yegor256
This issue should be closed since the PR has been merged.

**Comment by driver733** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/537#issuecomment-361290645))

@driver733 The impediment for [#537](https://github.com/yegor256/cactoos/issues/537) was registered successfully by @driver733[/z](https://www.0crat.com/u/driver733)

**Comment by llorllale** [comment]
@driver733 indeed, thank you

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @driver733[/z](https://www.0crat.com/u/driver733), total is [+60](https://www.0crat.com/u/driver733)

**Comment by 0crat** [comment]
The job [#537](https://github.com/yegor256/cactoos/issues/537) is now out of scope
