### ISSUE TITLE
Problem with travis ci building

### ISSUE THREAD

**Issue by nick318** [yegor256/cactoos#539]
I have a problem with building cactoos in travis ci with problems which are not related to changes in pull request. Can someone solve that problem? [pull request here](https://github.com/yegor256/cactoos/pull/536)

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@iCok it's all clean: https://travis-ci.org/yegor256/cactoos What is the problem?

**Comment by iCok** [comment]
https://travis-ci.org/yegor256/cactoos/builds/326830368 here there is a problem with antrun-plugin. It is passed locally without problems

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#539` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#539](https://github.com/yegor256/cactoos/issues/539) was not in scope
