### ISSUE TITLE
Rename open() method in Input interface

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#54]
@yegor256 According to EO Vol. 1, page 53:

> I call a manipulator a method that makes modifications to the real-world entity being abstracted by an object.  It always returns void, and its names are always verbs.

So my sugestion is change the method's name from `open()` to `stream()`. I think it makes sense, because the method is returning an `InputStream`.

What do you think?

**Comment by 0crat** [comment]
@fabriciofx I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@fabriciofx totally agree, let's do it. Please, submit a PR.
