### ISSUE TITLE
Thread-safety guarantee

### ISSUE THREAD

**Issue by ashtonhogan** [yegor256/cactoos#540]
Why do most, if not all of the classes not provide this guarantee?

I'm assuming it's a good thing to be thread-safe so what are the blockers?

Performance? Technical knowledge? Contributions?

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@ashtonhogan here is the philosophy: http://www.yegor256.com/2017/01/17/synchronized-decorators.html

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#540` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#540` was not in scope

**Comment by ashtonhogan** [comment]
@yegor256 Is there anything on deadlocks and all those other thread-related painful issues?
