### ISSUE TITLE
How can I get checkstyle config file?

### ISSUE THREAD

**Issue by allanws** [yegor256/cactoos#544]
So I can have my IDE doing the crap job of formatting code... (@yegor256)

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@allanws there is no such thing, you have to do it manually, for educational purposes mainly.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#544` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#544](https://github.com/yegor256/cactoos/issues/544) was not in scope

**Comment by allanws** [comment]
@yegor256 I disagree. 

If a computer is better than a human doing something, I let it do it for me. Code formatting is one of them... we as humans have to write code that other humans can read.

**Comment by allanws** [comment]
@yegor256 if you still disagree, it would be interesting to add that to the policy (or wherever it makes sense to you).
