### ISSUE TITLE
Introduce ScalarMapOf

### ISSUE THREAD

**Issue by ashtonhogan** [yegor256/cactoos#546]
In order to achieve a `ScalarMapOf` at the moment you have to declare, i.e.:

```
private final MapOf<Scalar<String>, Scalar<String>> spreadsheet;
```

This would look a lot cleaner if it were declared like this instead, i.e.:

```
private final ScalarMapOf<String, String> spreadsheet;
```

Is this possible? Does something better already exist?

I'm guessing it might be a matter of introducing a secondary constructor, i.e.:

```
public ScalarMapOf(MapEntry<String, String>... mapEntries) {
   this(()->stringA, ()->stringB);
}

public ScalarMapOf(MapEntry<Scalar<String>, Scalar<String>>... mapEntries) {
      //Primary ctor
}
```

If there is demand for this, I can open a new issue for `ScalarListOf`

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue
