### ISSUE TITLE
LengthOf test

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#547]
Let's implement a test for `LengthOf` class. Note the declared code in the constructor it has not been tested.

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by fabriciofx** [comment]
@yegor256 ping!

**Comment by 0crat** [comment]
Job [#547](https://github.com/yegor256/cactoos/issues/547) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), total is [+360](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
The job [#547](https://github.com/yegor256/cactoos/issues/547) assigned to @icok[/z](https://www.0crat.com/u/icok). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@icok[/z](https://www.0crat.com/u/icok) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@icok[/z](https://www.0crat.com/u/icok) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by nick318** [comment]
@fabriciofx close the issue please, since PR #597 is merged

**Comment by nick318** [comment]
@fabriciofx take a look please

**Comment by nick318** [comment]
@fabriciofx take a look please2

**Comment by nick318** [comment]
@fabriciofx take a look please3

**Comment by nick318** [comment]
@yegor256 if the issue owner does not respond, what I have to do to close the issue?

**Comment by 0crat** [comment]
The user @icok[/z](https://www.0crat.com/u/icok) resigned from [#547](https://github.com/yegor256/cactoos/issues/547), please stop working

**Comment by yegor256** [comment]
@nick318 if the original ticket report doesn't reply, you ask project architect to help you out.

**Comment by nick318** [comment]
@yegor256 Got it, take a look and close the issue, since it's done. But I was resigned because of that issue.

**Comment by yegor256** [comment]
@

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#547` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#547](https://github.com/yegor256/cactoos/issues/547) is now out of scope
