### ISSUE TITLE
Base64Bytes and BytesBase64 as Base64Input and Base64Output

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#548]
Let's change `Base64Bytes` and `BytesBase64` to `Base64Input` and `Base64Output`.

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by fabriciofx** [comment]
@yegor256 ping!

**Comment by yegor256** [comment]
@fabriciofx see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#5-report-when-it-is-broken

**Comment by ashtonhogan** [comment]
@fabriciofx are you still interested in making this change? if not, can you please close this issue?

**Comment by llorllale** [comment]
@fabriciofx this would lead to confusion with the `Input` interface.

**Comment by llorllale** [comment]
@fabriciofx ping

**Comment by llorllale** [comment]
@fabriciofx closed due to inactivity.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
