### ISSUE TITLE
Move *Bytes classes to org.cactoos.bytes package

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#549]
Let's move the `BytesOf`, `EmptyBytes`, `InputAsBytes`, `ReaderAsBytes` and `UncheckedBytes` to package `org.cactoos.bytes`.

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by fabriciofx** [comment]
@yegor256 ping!

**Comment by yegor256** [comment]
@fabriciofx see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#5-report-when-it-is-broken

**Comment by llorllale** [comment]
@fabriciofx what Yegor said. I also do not see what the issue is here.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
