### ISSUE TITLE
Extract TeeInput.Stream class from TeeInput

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#55]
@yegor256 Usually, I don't like classes big classes and private methods, classes and constants. Why? Because without them, our classes are smaller and more cohesive. So, to achieve this goal, I suggest extract the `TeeInput.Stream` class to a public `TeeInputStream` class.

What do you think?

**Comment by 0crat** [comment]
@fabriciofx I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256
