### ISSUE TITLE
Move DateAsText to org.cactoos.text package

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#550]
Let's move the `DateAsText` class to `org.cactoos.text` package.

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by svendiedrichsen** [comment]
@yegor256 @fabriciofx This could be fixed together with #560. Should I do this?

**Comment by fabriciofx** [comment]
@svendiedrichsen To me it's ok... but it depends on @yegor256, if he will agree with this move.

**Comment by yegor256** [comment]
@fabriciofx I don't think it's a good idea. It's better to keep all date-related classes together, in the `org.cactoos.date` package.

**Comment by svendiedrichsen** [comment]
@yegor256 `org.cactoos.time`?

**Comment by fabriciofx** [comment]
@yegor256 WDYT `org.cactoos.scalar.time`?

**Comment by yegor256** [comment]
@fabriciofx @svendiedrichsen let's leave it where it is now

**Comment by svendiedrichsen** [comment]
Ok, I did in my PR. This can be closed then.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#550` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#550](https://github.com/yegor256/cactoos/issues/550) was not in scope
