### ISSUE TITLE
Twitter support

### ISSUE THREAD

**Issue by ashtonhogan** [yegor256/cactoos#552]
It would be really nice to have some objects that make twitter api tasks easier. Not sure if this is possible or the appropriate repo but ideally if convenient, elegant objects could be used to interact with twitter api instead of direct over http

**Comment by 0crat** [comment]
[@yegor256](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by amihaiemil** [comment]
@ashtonhogan I guess you should start a project, then. ``twitter-java-eo``, which would implement such an elegant Java SDK. :)

**Comment by ashtonhogan** [comment]
@amihaiemil maybe you're right

**Comment by ashtonhogan** [comment]
@amihaiemil so the README says:

"Motivation. We are not happy with JDK, Guava, and Apache Commons because they are procedural and not object-oriented. They do their job, but mostly through static methods. Cactoos is suggesting to do almost exactly the same, but through objects."

So unless we change the scope of cactoos, it sounds like social integrations won't fit in here because afaik there's no social stuff in jdk, guava, commons...

However, creating a new repository is likely to look identical to this one as it adopts the exact same conventions so I'm not entirely sure...

What are your thoughts here @yegor256?

same repo?
new repo by you?
new repo by me?

**Comment by amihaiemil** [comment]
@ashtonhogan I would definetely go with a new repository. It would look ideantical to ``jcabi-github`` if you ask me. That linear architecture, with 100% encapsulation, seems best to me :) And it could also provide a mock implementation of Twitter, for unit testing. 

I think you should create a repo since it's your idea. I would use ``jcabi-http`` -- it is perfectfor such an OOP api client acrhitecture, but has one major flaw: no support for file-upload... so those parts of the api we will have to implement manually, by implementing the multiform RFC basically :)

**Comment by amihaiemil** [comment]
@ashtonhogan cactoos is just for primitive stuff, I believe. Social media integrations is not something primitive at all. I don't think anyone wants to make a swiss knife out of cactoos haha

**Comment by ashtonhogan** [comment]
@amihaiemil but then again, imagine how clean your `pom.xml` will be with just one dependency :smile:

**Comment by amihaiemil** [comment]
@ashtonhogan I don't know what you have in mind, but such an API client will be bigger than the original cactoos itself :)) look at jcabi-github, it's a big project, no more a Java Cabinet Component :D

**Comment by ashtonhogan** [comment]
@amihaiemil it's a good point. I think when things get too big it deters people away. Somehow cactoos has managed to remain quite loosely coupled so far as well, so you can use one thing without needing a million other things...

**Comment by yegor256** [comment]
@ashtonhogan I like the idea, but it's outside of Cactoos scope :)

**Comment by fabriciofx** [comment]
@yegor256 @ashtonhogan WDYT create a cactoos-twitter framework?

**Comment by yegor256** [comment]
@fabriciofx go for it, why not.

**Comment by fabriciofx** [comment]
@yegor256 I'm sorry, but I'm busy closing my issues... :) @ashtonhogan WDYT? Would you like create a cactoos-twitter?

**Comment by ashtonhogan** [comment]
@fabriciofx I would love to but I would need to figure out how to set up a repo like this one with all the build scripts and stuff and then I'd need to go learn the twitter API itself. 

Given the way competitors are doing business, I'm highly motivated to put out a social version of cactoos as well to win over that market but I'm still trying to decide if it's the best use of my time...

**Comment by amihaiemil** [comment]
@ashtonhogan If you apply PDD, even if you work alone on that repo, you will manage just fine. PDD gives you the ability to solve tasks in those 20min between meetings (or while waiting for an email reply) at your fulltime job. That's how I develop all my projects. 

And setting up a repo + rultor is very easy. What will take you half an hour more is setup the release scripts, with the encrypted keys and so on, but it's also very easy if you have Linux :) 

Expanding beyond twitter... don't worry, that is a different repo already. Have you seen that comedy sketch about the tech world? "I like to think how could I scale my business 100x before I even managed to scale it 2x" :))

**Comment by ashtonhogan** [comment]
@amihaiemil I think it would be a good strategic move for cactoos to have this but I don't think it's the best use of my time right now, I wouldn't mind contributing to a crowdfund for it though...
