### ISSUE TITLE
Can't configure encoder/decoder for Base64Bytes and BytesBase64

### ISSUE THREAD

**Issue by neonailol** [yegor256/cactoos#555]
`Base64Bytes` does not have parameter for using another type of `Base64.Decoder`
`BytesBase64` does not have parameter for using another type of `Base64.Encoder`

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@neonailol it's important to always formulate tickets as bugs, saying what is broken. In this case, you can say "I can't configure decoder/encoder, etc.."

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @neonailol[/z](http://www.0crat.com/u/neonailol), total is [+75](http://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment]
The job [#555](https://github.com/yegor256/cactoos/issues/555) assigned to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by svendiedrichsen** [comment]
This can be closed. The PR has been merged.

**Comment by neonailol** [comment]
@yegor256 task is done

**Comment by yegor256** [comment]
@neonailol thanks

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc), total is [+30](https://www.0crat.com/u/flslkxtc)

**Comment by 0crat** [comment]
The job [#555](https://github.com/yegor256/cactoos/issues/555) is now out of scope
