### ISSUE TITLE
Should we stop enforcing "Abstract Class Name" rules on this project?

### ISSUE THREAD

**Issue by llorllale** [yegor256/cactoos#557]
(This ticket could perhaps belong in [teamed/qulice](https://github.com/teamed/qulice).)

Let's consider whether we should remove the `PMD.TooManyMethods`  and `AbstractClassName` checks from this project, and if so, *how* to remove.

As per the changes being brought in with #528 following the [webinar](https://www.youtube.com/watch?v=Wcy53ZSF78o) on [Decorating Envelopes](http://www.yegor256.com/2017/01/31/decorating-envelopes.html), I agree with @fabriciofx that having these envelopes named *Abstract&lt;noun&gt;Envelope* just adds a lot of unnecessary noise. From what I understand correctly, Envelopes have to be abstract *by definition* in Java.

I vote we remove this check.

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by fabriciofx** [comment]
@llorllale @yegor256 +1 to remove too.

**Comment by yegor256** [comment]
@llorllale I agree, but this ticket belongs to Qulice project
