### ISSUE TITLE
TransactionalFile

### ISSUE THREAD

**Issue by ashtonhogan** [yegor256/cactoos#559]
It would be great to be able to write to a file in a fail-safe way so that if a write operation is interrupted, the data is not lost

Process would be:

1. If original file and temp file exist then delete the temp file, recreate it and write to it. Once done, delete the original, rename the temp.
2. If just the original file exists then create a temp file, write to the temp file. Once done, delete the original, rename the temp.
3. If just the temp file exists then rename it to the original filename and do step 2.

One caveat is around concurrency, if two or more instances of this object are instantiated and used separately, there are going to be some issues around multiple temp files being created and the original file being deleted prematurely and so on. Here are some options:

1. Use unique filenames for the original file and temp files and then merge the originals in the order they were created. (Bad idea imo)
2. Halt all writes so that only one can be done at a time via `synchronized`. (I like this option)
3. Another option could be to pass around a `Queue` and then use the same instance of `TransactionalFile` to process items in the queue in a FIFO fashion (This may pass a bigger burden to the cactoos user though)

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ashtonhogan can you give code example of how you would use this "thing"?

**Comment by ashtonhogan** [comment]
@yegor256 exactly the same as a regular `File` - this just makes sure that writes are done in an "all or nothing" way

**Comment by ashtonhogan** [comment]
@yegor256 actually, I think this would be best placed as a decorator. I see that cactoos already has a number of classes available for writing to `File`. So either add secondary constructors or make `TransactionalFile` a type of `File` I guess...

**Comment by ashtonhogan** [comment]
@yegor256 I did a prototype, it has all kinds of issues but it shows the concept at least
