### ISSUE TITLE
DateAsText doesn't support LocalDateTime or LocalDate

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#560]
I can't convert `LocalDateTime` or `LocalDate` to string using `DateAsText`. For example, the above doesn't work:
```
new DateAsText(LocalDateTime.now()).asString();
```
Exception:
```
java.time.temporal.UnsupportedTemporalTypeException: Unsupported field: OffsetSeconds

	at java.time.LocalDate.get0(LocalDate.java:680)
	at java.time.LocalDate.getLong(LocalDate.java:659)
	at java.time.LocalDateTime.getLong(LocalDateTime.java:720)
	at java.time.format.DateTimePrintContext.getValue(DateTimePrintContext.java:298)
	at java.time.format.DateTimeFormatterBuilder$OffsetIdPrinterParser.format(DateTimeFormatterBuilder.java:3335)
	at java.time.format.DateTimeFormatterBuilder$CompositePrinterParser.format(DateTimeFormatterBuilder.java:2179)
	at java.time.format.DateTimeFormatter.formatTo(DateTimeFormatter.java:1746)
	at java.time.format.DateTimeFormatter.format(DateTimeFormatter.java:1720)
	at org.cactoos.time.DateAsText.lambda$new$0(DateAsText.java:180)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.time.DateAsText.asString(DateAsText.java:186)
	at org.cactoos.time.DateAsTextTest.local(DateAsTextTest.java:180)
```
And a similar thing happens to `new DateAsText(LocalDate.now()).asString()`.

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#560](https://github.com/yegor256/cactoos/issues/560) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @fabriciofx[/z](http://www.0crat.com/u/fabriciofx), total is [+225](http://www.0crat.com/u/fabriciofx)

**Comment by svendiedrichsen** [comment]
@yegor256 , @fabriciofx  I would like to contribute by splitting into LocalDateTimeAsText, LocalDateAsText, OffsetDateTimeAsText etc.

**Comment by yegor256** [comment]
@0crat assign @svendiedrichsen

**Comment by 0crat** [comment]
> @0crat assign @svendiedrichsen ([here](https://github.com/yegor256/cactoos/issues/560#issuecomment-358457969))

@yegor256 The job [#560](https://github.com/yegor256/cactoos/issues/560) assigned to @svendiedrichsen[/z](http://www.0crat.com/u/svendiedrichsen). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html). @svendiedrichsen[/z](http://www.0crat.com/u/svendiedrichsen) is not a member of this project yet, but they can request to join. Check your [profile](http://www.0crat.com/u/svendiedrichsen) and follow the instructions.

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](http://www.0crat.com/u/yegor256), total is [+7590](http://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
@svendiedrichsen[/z](https://www.0crat.com/u/svendiedrichsen) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by svendiedrichsen** [comment]
@yegor256 How am I supposed to react to this last comment? The PR is waiting for review.

**Comment by svendiedrichsen** [comment]
@yegor256 The PR has been merged. This ticket can be closed then or can't it?

**Comment by yegor256** [comment]
@svendiedrichsen ask ticket reporter, it's his ticket/problem

**Comment by svendiedrichsen** [comment]
@fabriciofx ?

**Comment by 0crat** [comment]
@svendiedrichsen[/z](https://www.0crat.com/u/svendiedrichsen) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by fabriciofx** [comment]
@svendiedrichsen @yegor256 The PR has been merged, so I'll close this issue. Thanks!

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @svendiedrichsen[/z](https://www.0crat.com/u/svendiedrichsen), total is [+30](https://www.0crat.com/u/svendiedrichsen)

**Comment by 0crat** [comment]
The job [#560](https://github.com/yegor256/cactoos/issues/560) is now out of scope
