### ISSUE TITLE
ReaderAsBytes not closing the enclosed Reader

### ISSUE THREAD

**Issue by llorllale** [yegor256/cactoos#563]
`ReaderAsBytes.asBytes()` consumes the enclosed reader but does not close it. This does not make any sense because there is nothing more to read from the Reader, and also will result in some unexpected behavior in some environments.

For example, in Windows, attempt to read the bytes of a text file and then delete:
```java
final Path file = ...;
final byte[] contents = new ReaderAsBytes(new ReaderOf(file)).asBytes();
Files.delete(file);    //IOException "file is being used by another process"
```

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#563](https://github.com/yegor256/cactoos/issues/563) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @llorllale[/z](http://www.0crat.com/u/llorllale), total is [+135](http://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#563](https://github.com/yegor256/cactoos/issues/563) assigned to @rexim[/z](https://www.0crat.com/u/rexim). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by alex-semenyuk** [comment]
@0crat assign to me

**Comment by 0crat** [comment]
You need to ask somebody to invite you: https://github.com/zerocracy/datum#invite-only

**Comment by alex-semenyuk** [comment]
@0crat assign to me

**Comment by 0crat** [comment]
> @0crat assign to me ([here](https://github.com/yegor256/cactoos/issues/563#issuecomment-362797939))

@alex-semenyuk Argument "to" doesn't match regex `me|@[a-zA-Z0-9\-]+`

**Comment by alex-semenyuk** [comment]
@0crat assign @alex-semenyuk

**Comment by 0crat** [comment]
> @0crat assign @alex-semenyuk ([here](https://github.com/yegor256/cactoos/issues/563#issuecomment-362798239))

@alex-semenyuk You need to have one of these roles in order to do what you're trying to do: `ARC`, `PO`. I'm sorry to say this, but at the moment you've got no roles in this project (your GitHub login is "alex-semenyuk").

**Comment by 0crat** [comment]
@rexim[/z](https://www.0crat.com/u/rexim) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @rexim[/z](https://www.0crat.com/u/rexim), total is [+75](https://www.0crat.com/u/rexim)

**Comment by 0crat** [comment]
The job [#563](https://github.com/yegor256/cactoos/issues/563) is now out of scope
