### ISSUE TITLE
Build failure - PMD violations in /master? (18JAN2018)

### ISSUE THREAD

**Issue by allanws** [yegor256/cactoos#568]
Just got a fresh copy from /master and ran the build and got the log errors below:

log4j:WARN No appenders could be found for logger (com.puppycrawl.tools.checkstyle.ConfigurationLoader).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[INFO] Starting PMD validator
[INFO] No PMD violations found in 380 files
[INFO] Finishing PMD validator
[INFO] Starting FindBugs validator
[INFO] >> M D INT: Vacuous ixor operation on hash in org.cactoos.map.MapEntry.hashCode()  At MapEntry.java:[line 98]
[INFO] >> H I Dm: Found reliance on default encoding in new org.cactoos.text.TextOf(InputStream): new java.io.InputStreamReader(InputStream)  At TextOf.java:[line 302]
[INFO] >> M B Se: Class org.cactoos.scalar.NumberOf defines non-transient non-serializable instance field lnum  In NumberOf.java
[INFO] >> M B Se: Class org.cactoos.scalar.NumberOf defines non-transient non-serializable instance field inum  In NumberOf.java
[INFO] >> M B Se: Class org.cactoos.scalar.NumberOf defines non-transient non-serializable instance field fnum  In NumberOf.java
[INFO] >> M B Se: Class org.cactoos.scalar.NumberOf defines non-transient non-serializable instance field dnum  In NumberOf.java
[INFO] >> M B Se: org.cactoos.scalar.StickyScalar stored into non-transient field NumberOf.lnum  At NumberOf.java:[line 87]
[INFO] >> M B Se: org.cactoos.scalar.StickyScalar stored into non-transient field NumberOf.inum  At NumberOf.java:[line 90]
[INFO] >> M B Se: org.cactoos.scalar.StickyScalar stored into non-transient field NumberOf.fnum  At NumberOf.java:[line 93]
[INFO] >> M B Se: org.cactoos.scalar.StickyScalar stored into non-transient field NumberOf.dnum  At NumberOf.java:[line 96]
[INFO] >> M B Eq: org.cactoos.text.ComparableText defines compareTo(Object) and uses Object.equals()  At ComparableText.java:[line 48]
[INFO] >> L D UwF: Cycled.iterator not initialized in constructor and dereferenced in org.cactoos.iterator.Cycled.next()  At Cycled.java:[line 75]
[WARNING] FindBugs: M D INT: Vacuous ixor operation on hash in org.cactoos.map.MapEntry.hashCode()  At MapEntry.java:[line 98]
[WARNING] FindBugs: H I Dm: Found reliance on default encoding in new org.cactoos.text.TextOf(InputStream): new java.io.InputStreamReader(InputStream)  At TextOf.java:[line 302]
[WARNING] FindBugs: M B Se: Class org.cactoos.scalar.NumberOf defines non-transient non-serializable instance field lnum  In NumberOf.java
[WARNING] FindBugs: M B Se: Class org.cactoos.scalar.NumberOf defines non-transient non-serializable instance field inum  In NumberOf.java
[WARNING] FindBugs: M B Se: Class org.cactoos.scalar.NumberOf defines non-transient non-serializable instance field fnum  In NumberOf.java
[WARNING] FindBugs: M B Se: Class org.cactoos.scalar.NumberOf defines non-transient non-serializable instance field dnum  In NumberOf.java
[WARNING] FindBugs: M B Se: org.cactoos.scalar.StickyScalar stored into non-transient field NumberOf.lnum  At NumberOf.java:[line 87]
[WARNING] FindBugs: M B Se: org.cactoos.scalar.StickyScalar stored into non-transient field NumberOf.inum  At NumberOf.java:[line 90]
[WARNING] FindBugs: M B Se: org.cactoos.scalar.StickyScalar stored into non-transient field NumberOf.fnum  At NumberOf.java:[line 93]
[WARNING] FindBugs: M B Se: org.cactoos.scalar.StickyScalar stored into non-transient field NumberOf.dnum  At NumberOf.java:[line 96]
[WARNING] FindBugs: M B Eq: org.cactoos.text.ComparableText defines compareTo(Object) and uses Object.equals()  At ComparableText.java:[line 48]
[WARNING] FindBugs: L D UwF: Cycled.iterator not initialized in constructor and dereferenced in org.cactoos.iterator.Cycled.next()  At Cycled.java:[line 75]
[INFO] Read our quality policy: http://www.qulice.com/quality.html
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 37.645 s
[INFO] Finished at: 2018-01-19T09:53:06+11:00
[INFO] Final Memory: 44M/1349M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.qulice:qulice-maven-plugin:0.17.1:check (default-cli) on project cactoos: Failure: 12 FindBugs violations (see log above) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

@yegor256 Please confirm the issue and proceed accordingly.

**Comment by allanws** [comment]
@yegor256 , please disregard the issue. I was running quilice plugin directly (mvn qulice:check). When running (mvn clean install -Pqulice) it works fine...

**Comment by allanws** [comment]
@yegor256 not sure if would that be part of the project scope, but running the qulice plugin goal should work well, right? I was doing that a few days ago but in the last couple of days I was getting this error...

Anyway, up to you to do further investigation or just close the ticket.

**Comment by yegor256** [comment]
@allanws `mvn clean install -Pqulice` is how you should run it
