### ISSUE TITLE
Maven pom.xml problems shown by the versions plugin

### ISSUE THREAD

**Issue by svendiedrichsen** [yegor256/cactoos#570]
The maven versions plugin shows some problems with the projects pom
```
[INFO] 
[INFO] All plugins with a version specified are using the latest versions.
[INFO] 
[WARNING] The following plugins do not have their version specified:
[WARNING]   com.qulice:qulice-maven-plugin ............................ 0.17.1
[WARNING]   maven-compiler-plugin ..................... (from super-pom) 3.6.0
[INFO] 
[WARNING] Project does not define minimum Maven version, default is: 2.0
[INFO] Plugins require minimum Maven version of: 3.0.4
[INFO] Note: the super-pom from Maven 3.3.3 defines some of the plugin
[INFO]       versions and may be influencing the plugins required minimum Maven
[INFO]       version.
[INFO] 
[ERROR] Project does not define required minimum version of Maven.
[ERROR] Update the pom.xml to contain
[ERROR]     <prerequisites>
[ERROR]       <maven>3.0.4</maven>
[ERROR]     </prerequisites>
[INFO] 
[INFO] Require Maven 2.0.6 to use the following plugin updates:
[INFO]   maven-verifier-plugin ........................................... 1.0
[INFO] 
[INFO] Require Maven 2.0.7 to use the following plugin updates:
[INFO]   org.codehaus.mojo:sonar-maven-plugin ............................ 1.0
[INFO] 
[INFO] Require Maven 2.0.9 to use the following plugin updates:
[INFO]   maven-compiler-plugin ........................................... 3.1
[INFO] 
[INFO] Require Maven 2.1.0 to use the following plugin updates:
[INFO]   org.jacoco:jacoco-maven-plugin ................... 0.6.3.201306030806
[INFO] 
[INFO] Require Maven 2.2.1 to use the following plugin updates:
[INFO]   maven-compiler-plugin ........................................... 3.3
[INFO]   maven-verifier-plugin ........................................... 1.1
[INFO]   org.jacoco:jacoco-maven-plugin ................... 0.7.6.201602180812
[INFO] 
[INFO] Require Maven 3.0 to use the following plugin updates:
[INFO]   com.qulice:qulice-maven-plugin ............................... 0.14.1
[INFO]   maven-compiler-plugin ......................................... 3.7.0
[INFO]   org.codehaus.mojo:sonar-maven-plugin ...................... 3.4.0.905
[INFO]   org.jacoco:jacoco-maven-plugin ................................ 0.8.0
[INFO] 
[INFO] Require Maven 3.0.4 to use the following plugin updates:
[INFO]   com.qulice:qulice-maven-plugin ............................... 0.17.1
```

**Comment by 0crat** [comment]
Job [#570](https://github.com/yegor256/cactoos/issues/570) is now in scope, role is `DEV`

**Comment by svendiedrichsen** [comment]
It gets down to these two problems:
1) There are two plugins without their `<version>` specified explicitly.
```
[WARNING] The following plugins do not have their version specified:
[WARNING]   com.qulice:qulice-maven-plugin ............................ 0.17.1
```
2) The project does not define the minimum version of maven to run.
```
[ERROR] Project does not define required minimum version of Maven.
[ERROR] Update the pom.xml to contain
[ERROR]     <prerequisites>
[ERROR]       <maven>3.0.4</maven>
[ERROR]     </prerequisites>
```

**Comment by 0crat** [comment]
The job [#570](https://github.com/yegor256/cactoos/issues/570) assigned to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by flslkxtc** [comment]
@svendiedrichsen I've specified and updated plugins versions in pull request, but second issue about undefined maven version and missing prerequisites is a bug in versions-maven-plugin and its already has been reported multiple times, here's some more information on this issue: https://github.com/mojohaus/versions-maven-plugin/issues/48, https://github.com/mojohaus/versions-maven-plugin/issues/173

**Comment by 0crat** [comment]
@flslkxtc[/z](https://www.0crat.com/u/flslkxtc) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by svendiedrichsen** [comment]
@flslkxtc You can achieve the same as the `prerequisites` by using the maven enforcer plugin. I think it would be nice to have a proper error message if someone tried to build the project with the wrong maven version.

**Comment by flslkxtc** [comment]
@svendiedrichsen it's already taken care of: cactoos pom.xml contains parent pom from jcabi, where maven-enforcer-plugin specifies maven version as ``<version>[3.2.5,)</version>``

**Comment by svendiedrichsen** [comment]
@flslkxtc Then IMO its fine.

**Comment by 0crat** [comment]
@flslkxtc[/z](https://www.0crat.com/u/flslkxtc) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by flslkxtc** [comment]
@yegor256 pull request https://github.com/yegor256/cactoos/pull/596 is ready to merge

**Comment by svendiedrichsen** [comment]
PR has been merged.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc), total is [+90](https://www.0crat.com/u/flslkxtc)

**Comment by 0crat** [comment]
The job [#570](https://github.com/yegor256/cactoos/issues/570) is now out of scope
