### ISSUE TITLE
IsBlank - stream api

### ISSUE THREAD

**Issue by VsSekorin** [yegor256/cactoos#573]
IsBlank#value contains inefficient use of Stream API, there is a simpler and more readable version.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#573` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#573](https://github.com/yegor256/cactoos/issues/573) was not in scope
