### ISSUE TITLE
Create a package for matchers.

### ISSUE THREAD

**Issue by Zefick** [yegor256/cactoos#578]
There are four matchers at the moment in the main package. Is it better to move them to separate package `org.cactoos.matcher`?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by Zefick** [comment]
I also noticed that these matchers used only in tests. Technically speaking, they are not part of the library. There is the matcher `RunInThreads` and it lies in `test` folder. I see an inconsistency here.

**Comment by yegor256** [comment]
@Zefick that's exactly why we decided not to create a special package -- because these matchers are for tests only, we don't ship them with the library. That's why we don't want to make a package. See?

**Comment by svendiedrichsen** [comment]
@yegor256 Shouldn't those matchers reside under `src/test` then? They test supporting code.

**Comment by yegor256** [comment]
@svendiedrichsen that's right, it's a bug. Let's move them to `src/test`.

**Comment by 0crat** [comment]
Job [#578](https://github.com/yegor256/cactoos/issues/578) is now in scope, role is `DEV`

**Comment by svendiedrichsen** [comment]
@Zefick This can be closed then.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#578` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#578](https://github.com/yegor256/cactoos/issues/578) is now out of scope

**Comment by 0crat** [comment]
Job [#578](https://github.com/yegor256/cactoos/issues/578) was not in scope
