### ISSUE TITLE
Remove usage of new keyword in method

### ISSUE THREAD

**Issue by ashtonhogan** [yegor256/cactoos#579]
https://github.com/yegor256/cactoos/blob/a36445346bec4abc74cfd18a2057694ceb5ccf14/src/main/java/org/cactoos/text/ReversedText.java#L54

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ashtonhogan I don't think it's possible or necessary to remove it. We are trying to use `new` as little as possible in methods, but thanks to Java, we have to it sometimes.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#579` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#579](https://github.com/yegor256/cactoos/issues/579) was not in scope

**Comment by ashtonhogan** [comment]
@yegor256 What about this

```
public final class ReversedText implements Text {

    /**
     * The text.
     */
    private final Text origin;

    /**
     * The text.
     */
    private final Scalar<Text> output;

    /**
     * Ctor.
     *
     * @param text The text
     */
    public ReversedText(final Text text) {
        this(
             text,
             () -> new StringBuilder(this.origin.asString()).reverse().toString()
        );
    }

    /**
     * Ctor.
     *
     * @param text The text
     * @param output The output text
     */
    public ReversedText(final Text origin, final Scalar<Text> output) {
        this.origin = origin;
        this.output = output;
    }

    @Override
    public String asString() throws IOException {
        return this.output.asString();
    }

}
```

**Comment by ashtonhogan** [comment]
@0crat reopen

**Comment by 0crat** [comment]
You need to ask somebody to invite you: https://github.com/zerocracy/datum#invite-only

**Comment by ashtonhogan** [comment]
@fabriciofx it looks like @yegor256 doesn't get notified after closing issues, could you possibly comment on my above solution?

**Comment by fabriciofx** [comment]
@ashtonhogan I'm sorry, but I didn't see any real gain in your solution, because:
1. You're using two attributes (`origin` and `output`) when just one is enough;
2. `new` keywork is still used *inside* the constructor. The *perfect* scenario is use it *outside* constructors and methods, because you can change the composition easier.

**Comment by ashtonhogan** [comment]
@fabriciofx thanks for replying

**Comment by ashtonhogan** [comment]
@fabriciofx I like the idea of printers only referencing existing data because it helps steer clear of factory design pattern.

1. Otherwise, what is the rule behind printers? ctors for input, printers for output?
2. I thought the idea was to have printers call things as and when they're needed. Some objects are already instantiated in ctors, some are lazy loaded with scalars in ctors, some are instantiated with printers but the ones in printers aren't supposed to make up the composition of any objects, they're just supposed to be used as utilities?
