### ISSUE TITLE
*DigestOfTests that work on files are failing on Windows

### ISSUE THREAD

**Issue by llorllale** [yegor256/cactoos#580]
The build is broken on Windows on the following tests:

* Md5DigestOfTest.checksumFromFile
* Sha1DigestOfTest.checksumFromFile
* Sha256DigestOfTest.checksumFromFile

The file checksums simply don't match the expected value.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#580](https://github.com/yegor256/cactoos/issues/580) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale), total is [+330](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#580](https://github.com/yegor256/cactoos/issues/580) assigned to @icok[/z](https://www.0crat.com/u/icok). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@icok[/z](https://www.0crat.com/u/icok) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by nick318** [comment]
@yegor256 the issue can be closed since #617 is merged

**Comment by llorllale** [comment]
@nick318 thanks! Tests work now on windows

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @icok[/z](https://www.0crat.com/u/icok), total is [+45](https://www.0crat.com/u/icok)

**Comment by 0crat** [comment]
The job [#580](https://github.com/yegor256/cactoos/issues/580) is now out of scope
