### ISSUE TITLE
Support for semantic versioning

### ISSUE THREAD

**Issue by svendiedrichsen** [yegor256/cactoos#582]
@yegor256 How about creating some classes for supporting [semantic versioning](https://semver.org/)? Something like:
* Parsing and constructing version strings
* Comparing version objects
* Version arithmetic like increasing to next major/minor/bugfix version

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@svendiedrichsen but there is a library for that: https://github.com/zafarkhaja/jsemver

**Comment by svendiedrichsen** [comment]
Oh, I had a failure in search somehow. Sorry.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#582` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#582](https://github.com/yegor256/cactoos/issues/582) was not in scope
