### ISSUE TITLE
SyncIteratorTest.java:33-35: add multi-threaded tests...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#585]
The puzzle `482-5994e3af` from #482 has to be resolved:

https://github.com/yegor256/cactoos/blob/bfccf2f79d2d6c5f40b6ade6ff2124d5895a05bf/src/test/java/org/cactoos/iterator/SyncIteratorTest.java#L33-L35

The puzzle was created by Sven Diedrichsen on 25-Jan-18. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#585](https://github.com/yegor256/cactoos/issues/585) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#585](https://github.com/yegor256/cactoos/issues/585) assigned to @icok[/z](https://www.0crat.com/u/icok). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@icok[/z](https://www.0crat.com/u/icok) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by nick318** [comment]
@svendiedrichsen To follow the discussion we had in #607, how my test for `hasNext` should look like, if such tests it is all about percentage of failure. As you said from 40% to 4.8%. How can we assert such percents? 

So far I wrote one test for `next` method: https://gist.github.com/nick318/543bf5e2aea11c7050a3286d6f4f24ee

And another one for `hasNext`:
https://gist.github.com/nick318/fd41d239dd02222f1ac851db680aa3a9

My question is, what assert can I use to verify `hasNext` method?

**Comment by svendiedrichsen** [comment]
@nick318 Sorry, but the discussion on #607 was about the necessaty of synchronizing the `hasNext` call. My suggestion to you was about how you can proof that it is useful.

The tests we need are totally different. We need to proof that
1) calls to the `next` method block calls to the `hasNext` and `next` from another thread.
2) call to the `hasNext` method block only calls from the `next` and not calls to the `hasNext` from another thread.
Simply speaking. We need to test that the synchronization really does do the job that it is supposed to do and not calculate any kind of failure ratio.

**Comment by nick318** [comment]
@svendiedrichsen Thanks for the fast response. Do I go in a right direction with first method?

**Comment by svendiedrichsen** [comment]
@nick318 Not quiet. You can't really tell from the result of your test if it worked by accident. 
Maybe you pass in a Lock into the iterator, call writeLock, spawn one extra thread to call `next`, call next in the test and than release the lock. That way you could see that the test gets the first value and the extra thread gets the second.
I couldn't do in proper OOP style myself. Thats why I left the puzzle in the code.

**Comment by nick318** [comment]
@svendiedrichsen But inside, iterator will unlock my lock which I made in the test. Since there is code:
`this.lock.writeLock().unlock();`

**Comment by svendiedrichsen** [comment]
@nick318 It won't. Because you should have called `writelock().lock()` outside the iterator first which will the call `writelock().lock()` inside the iterator to block until you have unlocked outside.

**Comment by 0crat** [comment]
@icok[/z](https://www.0crat.com/u/icok) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by nick318** [comment]
@0crat refuse

**Comment by 0crat** [comment]
You need to ask somebody to invite you: https://github.com/zerocracy/datum#invite-only

**Comment by nick318** [comment]
@0crat waiting

**Comment by 0crat** [comment]
You need to ask somebody to invite you: https://github.com/zerocracy/datum#invite-only

**Comment by 0crat** [comment]
The user @icok[/z](https://www.0crat.com/u/icok) resigned from [#585](https://github.com/yegor256/cactoos/issues/585), please stop working

**Comment by 0crat** [comment]
The job [#585](https://github.com/yegor256/cactoos/issues/585) assigned to @driver733[/z](https://www.0crat.com/u/driver733), here is [why](https://www.0crat.com/footprint/C63314D6Z/440644226). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by driver733** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/585#issuecomment-366086646))

@driver733 The impediment for [#585](https://github.com/yegor256/cactoos/issues/585) was registered successfully by @driver733[/z](https://www.0crat.com/u/driver733)

**Comment by 0pdd** [comment]
The puzzle `482-5994e3af` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@driver733 According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>Some of ticket messages must mention all pull requests where the problem was actually fixed.

Please provide a link to corresponding PR in any of your messages.

**Comment by driver733** [comment]
@ypshenychka 
It has been mentioned here.
 https://github.com/yegor256/cactoos/issues/585#ref-pullrequest-296938129

**Comment by ypshenychka** [comment]
@nick318 This reference is not enough. It can be hard to find the real PR among other references on commits, different referenced issues etc.
So please stick to the [rules](http://datum.zerocracy.com/pages/policy.html#42) and provide a link in any of your messages, so we could finish with this job.

**Comment by driver733** [comment]
@ypshenychka Fixed.
PR - #639.

**Comment by ypshenychka** [comment]
@driver733 Thanks.

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
QA review completed: +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+435](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/cactoos/issues/585#issuecomment-367072988))

@ypshenychka There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/make_payment.groovy
sun.reflect.GeneratedMethodAccessor61[-1] java.lang.reflect.InvocationTargetException: null
com.zerocracy.pmo.banks.Paypal[122] java.io.IOException: Failed to pay $8.00 to driver733@me.com with memo "Payment for gh:yegor256/cactoos#585 (30 minutes): Order was finished, quality was "acceptable"": java.io.IOException Failed to pay through PayPal: [ERROR APPLICATION The payment can not be processed because no payment source is available]
com.zerocracy.pmo.banks.Paypal[202] java.io.IOException: Failed to pay through PayPal: [ERROR APPLICATION The payment can not be processed because no payment source is available]
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @driver733[/z](https://www.0crat.com/u/driver733), total is [+290](https://www.0crat.com/u/driver733)

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved
