### ISSUE TITLE
Can't read properies file 

### ISSUE THREAD

**Issue by neonailol** [yegor256/cactoos#587]
Cactoos is lacking some abstraction around java.properties
i want to have ability to run code like this

```java
new PropertiesOf(new ResourceOf("file.properties"))
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by svendiedrichsen** [comment]
`PropertiesOf` is located in package `iterable` but shouldn't it be in package `scalar`?

**Comment by neonailol** [comment]
was on the phone, did not notice it already exists :c

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#587` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#587](https://github.com/yegor256/cactoos/issues/587) was not in scope
