### ISSUE TITLE
PropertiesOf in wrong package iterable

### ISSUE THREAD

**Issue by svendiedrichsen** [yegor256/cactoos#590]
Class `PropertiesOf` implements interface `Scalar` and is located in package `iterable`. This seems to be the wrong package for this class.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#590](https://github.com/yegor256/cactoos/issues/590) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#590` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#590](https://github.com/yegor256/cactoos/issues/590) is now out of scope
