### ISSUE TITLE
TextOf(StackTraceElement[])

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#592]
Let's make it possible to convert an array of `StackTraceElement` into `Text`. Now it's not possible.

**Comment by yegor256** [comment]
@rultor release, tag is `0.29`

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#592` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#592](https://github.com/yegor256/cactoos/issues/592) was not in scope
