### ISSUE TITLE
Merge Cactoos and jcabi-immutable 

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#594]
Let's merge Cactoos framework with [jcabi-immutable](https://github.com/jcabi/jcabi-immutable). jcabi-immutable has useful immutable classes that IMHO makes sense belongs to Cactoos. Besides, we will decrease the number of dependencies which projects use Cactoos *and* jcabi-immutable. @yegor256 WDYT?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@fabriciofx sounds like a good idea. All we need to do is to add `.with(*)` methods to `ListOf`, `MapOf`, `IterableOf`, etc. Am I right?

**Comment by llorllale** [comment]
@fabriciofx @yegor256 I'm wondering about the use cases for those `with()` and `without*()` methods. Can't we do the same with some combinations of `Filtered` and `Joined`, considering they extend `CollectionEnvelope` which is immutable (except for its `iterator()`, which can be fixed)?

**Comment by llorllale** [comment]
@fabriciofx I believe the use of `Filtered` and `Joined`, combined with the improvements to be done in #804, #805, and #806, would pretty much cover use cases for `jcabi-immutable`, no?

**Comment by llorllale** [comment]
@fabriciofx ping

**Comment by llorllale** [comment]
@fabriciofx ping

**Comment by llorllale** [comment]
@fabriciofx closing

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
