### ISSUE TITLE
Grouping iterables

### ISSUE THREAD

**Issue by aliceice** [yegor256/cactoos#595]
Hi,

I think it would be convenient to have something like `Grouped` as a `Map<K, Iterable<V>>` which can be constructed from an Iterable<T> with two Functions for Keys and Values.

I'm imagining something like this:

```
new Grouped<>(
    (Iterable<Text> it) -> new ItemAt<>(0, it).value(),
    (Iterable<Text> it) -> new ItemAt<>(1, it).value(),
    iterables
);
```

This  should construct a `Map<Text, Iterable<Text>>`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@aliceice do you know something similar in Guava or Apache Commons?

**Comment by aliceice** [comment]
@yegor256 There is something similar in the Java 8 Stream-API.

`list.stream()
     .collect(Collectors.groupingBy(item->item.get("companyName"),
                Collectors.mapping(item->item.get("firstName"), Collectors.toList())));`

**Comment by 0crat** [comment]
Job [#595](https://github.com/yegor256/cactoos/issues/595) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#595](https://github.com/yegor256/cactoos/issues/595) assigned to @alex-semenyuk[/z](https://www.0crat.com/u/alex-semenyuk). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by alex-semenyuk** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/595#issuecomment-364647886))

@alex-semenyuk The user @alex-semenyuk[/z](https://www.0crat.com/u/alex-semenyuk) resigned from [#595](https://github.com/yegor256/cactoos/issues/595), please stop working

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://datum.zerocracy.com/pages/policy.html#6): -15 points just awarded to @alex-semenyuk[/z](https://www.0crat.com/u/alex-semenyuk), total is [+60](https://www.0crat.com/u/alex-semenyuk)

**Comment by 0crat** [comment]
The job [#595](https://github.com/yegor256/cactoos/issues/595) assigned to @nick318[/z](https://www.0crat.com/u/nick318), here is [why](https://www.0crat.com/footprint/C63314D6Z/441704775). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by nick318** [comment]
@aliceice Am I right saying that functions for keys and values should get instance of `Text` instead of `Iterable<Text>` because in your case, you will get the same value for each call your function. Then it does not make sense.

So I suppose to use next functions:

`(Text it) -> it.asString,
(Text it2) -> it2`

It is just an example, but it will group text objects by their values, if some texts have the same values, they will be grouped.

**Comment by aliceice** [comment]
@nick318 The `Iterable<Text>` is just an example. I think it would be way more useful to just use a generic type definition `T` Which is converted to `K` and `V` by those functions.

**Comment by nick318** [comment]
@aliceice ok, I have got it, thank you.

**Comment by amihaiemil** [comment]
@nick318  @svendiedrichsen You both made PRs here, although none of you has been assigned to this issue by 0crat. Next time, please don't work on an issue if it hasn't been assigned to you ;) 

@aliceice The PRs are a bit different, can you maybe have a look and see which one fixes this ticket best? 

https://github.com/yegor256/cactoos/pull/642 and https://github.com/yegor256/cactoos/pull/647

Then, I will finish the review for one of them.

**Comment by amihaiemil** [comment]
@nick318 My bad, I see you were assigned here. I will look over your PR today.

**Comment by aliceice** [comment]
@amihaiemil I had a look at both PRs. I think the one from @nick318 fixes this, as the one from @svendiedrichsen does not create a `Map<K, Iterable<V>` but an `Iterable<Iterable<T>>`.

**Comment by nick318** [comment]
@aliceice close the issue please, since pr #647 is merged

**Comment by 0crat** [comment]
Job [#595](https://github.com/yegor256/cactoos/issues/595) is already in scope

**Comment by 0crat** [comment]
@nick318[/z](https://www.0crat.com/u/nick318) resigned from [#595](https://github.com/yegor256/cactoos/issues/595), since the job is not in scope anymore

**Comment by 0crat** [comment]
The job [#595](https://github.com/yegor256/cactoos/issues/595) is now out of scope
