### ISSUE TITLE
Apache Commons StringUtils analog implementation

### ISSUE THREAD

**Issue by englishman** [yegor256/cactoos#6]
Apache Commons has [org.apache.commons.lang.StringUtils](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html) class with a set of helpful string static functions. 

How such functions should be implemented in Cactoos? I see some approaches
1. each of static functions has to be as a separate class. E.g. for [StringUtils#isBlank](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#isBlank-java.lang.CharSequence-) new class `BlankText` should be implemented with only one method `boolean is()`. The development of this idea is introducing predicate interface.
2. The same idea with `BlankText` class but it has to implement `BooleanStatement` or `Binary` interface with the single method `boolean asBoolean()`
3. such helpful functions should be put into `Text` interface definition. Thus we can speak about smart java `String` analog implementation.

I don't like all of these approaches but the example is practical.

WDYT?

**Comment by 0crat** [comment]
@englishman I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by englishman** [comment]
What do you think about `Is*` name pattern for any `Scalar<Boolean>` implementations?

**Comment by dusan-rychnovsky** [comment]
I like `IsBlankText` as class name much better. It conveys the fact that such objects will represent is-blank-text? predicates.

**Comment by englishman** [comment]
@dusan-rychnovsky renamed to `IsIsBlankText` as other classes in `org.cactoos.text` have `*Text` postfix

**Comment by dusan-rychnovsky** [comment]
Isn't that because the other classes represent a *text*, whereas this one represents a predicate?

**Comment by englishman** [comment]
@dusan-rychnovsky not sure: predicate is a function without any state but with a method consumes some data (see Java 8 `Predicate` impl). `IsBlankText` here is a boolean value.

**Comment by dusan-rychnovsky** [comment]
True. My point was `IsBlankText` does not represent a text, so in my opinion does not necessarily have to have the word `Text` in the class name. Anyway the choice is yours not mine :)

**Comment by yegor256** [comment]
@englishman @dusan-rychnovsky I believe that `IsBlank` is a good name. I would also rename `LengthOfIterable` to `LengthOf`. Feel free to contribute with a PR.

**Comment by englishman** [comment]
@yegor256 renamed to `IsBlank`

**Comment by fabriciofx** [comment]
@englishman `IsBlank` was accepted and we're opening an issue for each `StringUtils` method implementation.  So, do you agree with this solution? If yes, could you please close this issue? If not, could you explain why not? Thanks for your attention!

**Comment by ashtonhogan** [comment]
@yegor256 Please close this issue

**Comment by yegor256** [comment]
@ashtonhogan why me?

**Comment by llorllale** [comment]
@englishman please close this issue. Your PR #8 was merged

**Comment by llorllale** [comment]
@englishman can we close this?

**Comment by llorllale** [comment]
@englishman closing

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
