### ISSUE TITLE
SumOf doesn't protect from overflow

### ISSUE THREAD

**Issue by SharplEr** [yegor256/cactoos#600]
If we run such code:

```Java
System.out.println(new SumOf((Integer.MAX_VALUE+1L)*2L, 10L).intValue());
System.out.println(new SumOf((Integer.MAX_VALUE+1L)*2L, 10L).floatValue());
System.out.println(new SumOf((Integer.MAX_VALUE+1L)*2L, 10L).doubleValue());
System.out.println(new SumOf((Integer.MAX_VALUE+1L)*2L, 10L).longValue());
```

We will get

```Text
10
4.2949673E9
4.294967306E9
4294967306
```

All methods, except one, return the exact or approximate (in float case) values. But the result of intValue() can be a source of hidden bugs in code.

Java trying to approximate exact values (by using MAX_VALUE) in simple case by itself, for example:

```Java
new SumOf(Double.MAX_VALUE).longValue() == Long.MAX_VALUE
```

I think it will be nice to apply such approach on SumOf because cyclic addition too rare used (like hash algorithms), but often produce bugs.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by SharplEr** [comment]
I've been thinking a bit about the problem. The right solution is not so obvious, as it looks at first view. For example `System.out.println(new SumOf((Integer.MAX_VALUE+1L)*2L, 10L, -(Integer.MAX_VALUE+1L)*2L).intValue())` should return `10`, not a `Integer.MAX_VALUE`. The same overflow can happen with other types, so using `long` for summing ints is not scale solution. I think we can use two variables: one where the sum is, and another one with a number of overflows (can be negative which means overflow in a negative direction, `int` is enough). Then at the end of the calculation, there is very easy to make a decision about final result: should it be `MAX_VALUE`, `MIN_VALUE` or something else.

**Comment by svendiedrichsen** [comment]
@SharplEr I have added a test to show that you don't run into overflow during summation of values. I have picked up your example from above.

**Comment by yegor256** [comment]
@0crat assign @svendiedrichsen

**Comment by 0crat** [comment]
> @0crat assign @svendiedrichsen ([here](https://github.com/yegor256/cactoos/issues/600#issuecomment-363100179))

@yegor256 The job [#600](https://github.com/yegor256/cactoos/issues/600) assigned to @svendiedrichsen[/z](https://www.0crat.com/u/svendiedrichsen). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html). @svendiedrichsen[/z](https://www.0crat.com/u/svendiedrichsen) is not a member of this project yet, but they can request to join. Check your [profile](https://www.0crat.com/u/svendiedrichsen) and follow the instructions.

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @sharpler[/z](https://www.0crat.com/u/sharpler), total is [+15](https://www.0crat.com/u/sharpler)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9290](https://www.0crat.com/u/yegor256)

**Comment by svendiedrichsen** [comment]
@0crat Status

**Comment by 0crat** [comment]
You need to ask somebody to invite you: https://github.com/zerocracy/datum#invite-only

**Comment by svendiedrichsen** [comment]
@SharplEr I think you can close this. The PR is merged.

**Comment by 0crat** [comment]
@svendiedrichsen[/z](https://www.0crat.com/u/svendiedrichsen) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @svendiedrichsen[/z](https://www.0crat.com/u/svendiedrichsen), total is [+60](https://www.0crat.com/u/svendiedrichsen)

**Comment by 0crat** [comment]
The job [#600](https://github.com/yegor256/cactoos/issues/600) is now out of scope
