### ISSUE TITLE
Is sync iterator hasNext synchronization necessary? 

### ISSUE THREAD

**Issue by nick318** [yegor256/cactoos#607]
According with issue #482 we have `SyncIterator`. It has a `readLock` for `hasNext` method. I think it is not necessary because change method `next` has its own lock, it means the state will be actual. The question actually coming from the purpose of testing. I have an issue #585 and I have written test for checking `next` method and I think there is no situation when `hasNext ` can return different values in multiple threads. 

@yegor256 @svendiedrichsen WDYT?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by svendiedrichsen** [comment]
@nick318 Sure the `next`method uses a write-lock but it will only lock if the read uses the same lock for reading and it will run into an exhausted iterator more often. I see that it won't prevent from calling `next` on an exhausted iterator at all but it will be less frequent.

**Comment by svendiedrichsen** [comment]
@nick318 I have just done some quick test with a loop of 1000 runs. 
* Without synchronizing the `hasNext` method around 20% of the calls ran into an exception. 
* With synchronizing the `hasNext`call around 3% of the calls ran into an exception. 

The chances of getting an exception were about 7 times higher without sync.

**Comment by yegor256** [comment]
@nick318 we need a test to prove your claims above.

**Comment by nick318** [comment]
@svendiedrichsen I wrote a test to follow your case. Is it correct usage of SyncIterator? Do you want to iterate through one iterator in multiple threads?

`int exceptionCount = 0;
        for (int i = 0; i <5000; i++) {
            Iterator<Integer> syncIterator = new SyncIterator<Integer>(
                Stream.iterate(0, j -> j + 1).limit(200)
                    .collect(toList())
                    .iterator());
            CountDownLatch startSignal = new CountDownLatch(1);
            ExecutorService executors = Executors.newFixedThreadPool(2);
            Future<Boolean> hasNext = executors.submit(() -> {
                startSignal.await();
                while (syncIterator.hasNext()) {
                    syncIterator.next();
                } return true;
            });
            Future<Boolean> hasNext2 = executors.submit(() -> {
                startSignal.await();
                while (syncIterator.hasNext()) {
                    syncIterator.next();
                } return true;
            });
            startSignal.countDown();
            try {
                MatcherAssert.assertThat(
                    "Error",
                    hasNext.get(),
                    Matchers.equalTo(hasNext2.get()));
            } catch (ExecutionException e) {
                exceptionCount++;
            }
        }
        System.out.println(exceptionCount);`

**Comment by svendiedrichsen** [comment]
@nick318 Well, thats the purpose of synchronization. To allow for usage in a multithreaded environment. If we could guarantee single threaded access we would never need to sync.

Your test will will create exceptions. There are less than without locking the read call but there will be some.

**Comment by nick318** [comment]
@svendiedrichsen What about make a copy of iterator and use it independently? Is it a bad idea?

**Comment by svendiedrichsen** [comment]
@nick318 In order to make a copy of it you'd have to iterate over it and you are back where you started unless you are blocking all access during copying. And thats a bottleneck is in multi-threaded environments.

**Comment by nick318** [comment]
@svendiedrichsen I've got your points thank you. And take a look please at #585

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#607` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#607](https://github.com/yegor256/cactoos/issues/607) was not in scope
