### ISSUE TITLE
Remove code duplication in Reversed

### ISSUE THREAD

**Issue by nikialeksey** [yegor256/cactoos#608]
There is duplication in `collection\Reversed` and `iterable\Reversed`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#608](https://github.com/yegor256/cactoos/issues/608) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @nikialeksey[/z](https://www.0crat.com/u/nikialeksey), total is [+30](https://www.0crat.com/u/nikialeksey)

**Comment by nick318** [comment]
@yegor256 Can I handle it?

**Comment by 0crat** [comment]
The job [#608](https://github.com/yegor256/cactoos/issues/608) assigned to @nick318[/z](https://www.0crat.com/u/nick318), here is [why](https://www.0crat.com/footprint/C63314D6Z/450653775). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by nick318** [comment]
@nikialeksey please close the issue since PR #649 is merged

**Comment by nikialeksey** [comment]
Nice!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30)

**Comment by nick318** [comment]
@ypshenychka take a look please

**Comment by 0crat** [comment]
@nick318[/z](https://www.0crat.com/u/nick318) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by nick318** [comment]
@yegor256 take a look please, help me out to close the job.

**Comment by ypshenychka** [comment]
@nick318 Don't worry, I will review once issue https://github.com/zerocracy/farm/issues/592 is resolved. And BTW I can review closed issues. So that's not an issue.

**Comment by yegor256** [comment]
@ypshenychka it is an issue, the job is not closed until you give your verdict. The ticket may be closed already, but the job is still in the open state:

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/608#issuecomment-366641336))

@yegor256 This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#608](https://github.com/yegor256/cactoos/issues/608) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 13days
  * The role is `DEV`
  * The job is assigned to @nick318[/z](https://www.0crat.com/u/nick318) for [5days](http://datum.zerocracy.com/pages/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://datum.zerocracy.com/pages/policy.html#2) job
  * The job doesn't have any [impediments](http://datum.zerocracy.com/pages/policy.html#9)
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @nikialeksey[/z](https://www.0crat.com/u/nikialeksey): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%23608%27%7D) (restricted area)

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/608#issuecomment-366641336))

@yegor256 This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#608](https://github.com/yegor256/cactoos/issues/608) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 13days
  * The role is `DEV`
  * The job is assigned to @nick318[/z](https://www.0crat.com/u/nick318) for [5days](http://datum.zerocracy.com/pages/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://datum.zerocracy.com/pages/policy.html#2) job
  * The job doesn't have any [impediments](http://datum.zerocracy.com/pages/policy.html#9)
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @nikialeksey[/z](https://www.0crat.com/u/nikialeksey): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%23608%27%7D) (restricted area)

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
QA review completed: +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+90](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was successfully finished: +35 points just awarded to @nick318[/z](https://www.0crat.com/u/nick318), total is [+200](https://www.0crat.com/u/nick318)

**Comment by yegor256** [comment]
@ypshenychka very strange... can you please try again?
