### ISSUE TITLE
Scalar for constants

### ISSUE THREAD

**Issue by nikialeksey** [yegor256/cactoos#609]
Now if I want to create scalar from variable I write:
```java
new StickyScalar<>(() -> object)
```
Instead, we need something like:
```java
new ConstScalar(object)
```
without any lambds.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#609](https://github.com/yegor256/cactoos/issues/609) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @nikialeksey[/z](https://www.0crat.com/u/nikialeksey), total is [+15](https://www.0crat.com/u/nikialeksey)

**Comment by aliceice** [comment]
Hi @yegor256 @nikialeksey,

I think this could be handled by adding a secondary constructor to `StickyScalar`.
If that's okay for you, could I do this issue?

**Comment by nikialeksey** [comment]
@aliceice `StickyScalar` is not about const values, it is about cashed. ConstScalar must not have any execution I mean

**Comment by aliceice** [comment]
@nikialeksey When you're creating it like this `new StickyScalar<>(() -> object);` there is no execution as it will return a pre-computed value `object` every time  it's called.

Isn't a `Constant` effectively the same as a value which is cached forever?

Well, nontheless. I'd be fine with implementing a `Constant` scalar, too :)

@yegor256  What do you think?

**Comment by nikialeksey** [comment]
Yes, there is no execution while object creating, but there is execution for the first time getting the value. Sure, constant and cached forever are similar things :)

**Comment by yegor256** [comment]
@0crat assign @aliceice

**Comment by 0crat** [comment]
> @0crat assign @aliceice  ([here](https://github.com/yegor256/cactoos/issues/609#issuecomment-364402889))

@yegor256 The job [#609](https://github.com/yegor256/cactoos/issues/609) assigned to @aliceice[/z](https://www.0crat.com/u/aliceice). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html). @aliceice[/z](https://www.0crat.com/u/aliceice) is not a member of this project yet, but they can request to join. Check your [profile](https://www.0crat.com/u/aliceice) and follow the instructions.

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://datum.zerocracy.com/pages/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256), total is [+9425](https://www.0crat.com/u/yegor256)

**Comment by aliceice** [comment]
@0crat waiting

Qulice is not accepting my name as a valid `@author` text:
https://github.com/teamed/qulice/issues/866

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/cactoos/issues/609#issuecomment-364485448). You must always start your message with my name if you want to address it to me, see [§1](http://datum.zerocracy.com/pages/policy.html#1).

**Comment by aliceice** [comment]
@0crat waiting

**Comment by 0crat** [comment]
You need to ask somebody to invite you: https://github.com/zerocracy/datum#invite-only

**Comment by 0crat** [comment]
@aliceice[/z](https://www.0crat.com/u/aliceice) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by aliceice** [comment]
@nikialeksey My PR is now merged: #637 

Please check the class `Constant` and close this issue if it fit's your needs :)

**Comment by nikialeksey** [comment]
Nice!

**Comment by 0crat** [comment]
Job [#609](https://github.com/yegor256/cactoos/issues/609) is already in scope

**Comment by 0crat** [comment]
@aliceice[/z](https://www.0crat.com/u/aliceice) resigned from [#609](https://github.com/yegor256/cactoos/issues/609), since the job is not in scope anymore

**Comment by 0crat** [comment]
The job [#609](https://github.com/yegor256/cactoos/issues/609) is now out of scope
