### ISSUE TITLE
Remove static methods from TeeOutputStreamTest and TeeInputStreamTest

### ISSUE THREAD

**Issue by alex-semenyuk** [yegor256/cactoos#610]
Remove `org.cactoos.io.TeeOutputStreamTest#asString` and `org.cactoos.io.TeeInputStreamTest#asString` which are static

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#610](https://github.com/yegor256/cactoos/issues/610) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @alex-semenyuk[/z](https://www.0crat.com/u/alex-semenyuk), total is [+45](https://www.0crat.com/u/alex-semenyuk)

**Comment by 0crat** [comment]
The job [#610](https://github.com/yegor256/cactoos/issues/610) assigned to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@flslkxtc[/z](https://www.0crat.com/u/flslkxtc) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by flslkxtc** [comment]
@yegor256 @alex-semenyuk  pull request https://github.com/yegor256/cactoos/pull/624 is merged, we can close this issue.

**Comment by 0crat** [comment]
The job [#610](https://github.com/yegor256/cactoos/issues/610) is now out of scope
