### ISSUE TITLE
Lets create org.cactoos.proc package

### ISSUE THREAD

**Issue by nikialeksey** [yegor256/cactoos#611]
Lets create `proc` package and move into him:
```java
IoCheckedBiProc
IoCheckedProc
UncheckedBiProc
UncheckedProc
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@nikialeksey well, maybe it's not a bad idea, but we will have to create `bifunc` package too? And `runnable`? I don't think it's needed at this point.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#611` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#611](https://github.com/yegor256/cactoos/issues/611) was not in scope

**Comment by nikialeksey** [comment]
Yes, I understand, thanks
