### ISSUE TITLE
Remove untruth doc

### ISSUE THREAD

**Issue by nikialeksey** [yegor256/cactoos#612]
`org.cactoos.scalar.True` contains this untruth int class doc:
``` java
/**
 * ...
 * <p>There is no thread-safety guarantee.
 * ...
 */
```
But no, there is thread-safety guarantee.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@nikialeksey fixed in 27221f0 thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#612` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#612](https://github.com/yegor256/cactoos/issues/612) was not in scope
