### ISSUE TITLE
Redunant method reference

### ISSUE THREAD

**Issue by nikialeksey** [yegor256/cactoos#613]
In `UncheckedScalar`:
```java
return new IoCheckedScalar<>(this.origin::value).value();
```
can be replaced with:
```java
return new IoCheckedScalar<>(this.origin).value();
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@nikialeksey fixed in af8e9e8 thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#613` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#613](https://github.com/yegor256/cactoos/issues/613) was not in scope
