### ISSUE TITLE
Redunant assert statement org.cactoos.time.Iso

### ISSUE THREAD

**Issue by nikialeksey** [yegor256/cactoos#614]
There is always true condition in method `org.cactoos.time.Iso#get`:
```java
assert this != null;
```
Need to be removed

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@nikialeksey this is done in order to fool static analysis. Explained in 539c684

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#614` is not assigned, can't get start time

**Comment by nikialeksey** [comment]
Great! Thanks

**Comment by 0crat** [comment]
Job [#614](https://github.com/yegor256/cactoos/issues/614) was not in scope
