### ISSUE TITLE
Field must be final

### ISSUE THREAD

**Issue by nikialeksey** [yegor256/cactoos#615]
Field `org.cactoos.scalar.PropertiesOf` must be `final`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@nikialeksey thanks, fixed in 5d3e45b

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#615` is not assigned, can't get start time

**Comment by nikialeksey** [comment]
Thanks!

**Comment by 0crat** [comment]
Job [#615](https://github.com/yegor256/cactoos/issues/615) was not in scope
