### ISSUE TITLE
Double call asBytes throw an Exception of Stream is closed

### ISSUE THREAD

**Issue by nick318** [yegor256/cactoos#616]
If you call `asBytes` twice on any nested classes of `DigestInvelope `you will get `java.io.IOException: Stream closed`

The reason of throwing an exception is using:
`try (final InputStream stream = this.source.stream()) {`  inside `DigestInvelope.class`. Once you call `asBytes` it closes the stream and breaks all next calls. I think there is something wrong here.

Here is a simple test, which reproduce the error:
https://gist.github.com/nick318/525eeacb3a0f1a4874ec3a306fdb312a

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@nick318 it's a predictable behavior, since `Input` is not a constant. It doesn't guarantee that `stream()` will re-open the stream. So, in order to fix that, decorate `InputOf` with `StickyInput`.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#616` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#616](https://github.com/yegor256/cactoos/issues/616) was not in scope
