### ISSUE TITLE
Some examples are outdated

### ISSUE THREAD

**Issue by alex-semenyuk** [yegor256/cactoos#618]
Instead `intValue()` should be `value()` here:

```
new LengthOf(
  new TeeInput(
    "Hello, world!",
    new File("/code/a.txt")
  )
).intValue();
```
and here:

```
int total = new LengthOf(
  "how", "are", "you"
).intValue();
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@alex-semenyuk but `intValue()` works too... or I'm wrong?

**Comment by alex-semenyuk** [comment]
@yegor256 yes, closed

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#618` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#618](https://github.com/yegor256/cactoos/issues/618) was not in scope
