### ISSUE TITLE
SumOf for scalars

### ISSUE THREAD

**Issue by nikialeksey** [yegor256/cactoos#619]
In my project, who use cactoos, I wrote similar constructor:
```java
class Point {
...
    public Point(Scalar<Int> x, Scalar<Int> width) {
        this(() -> x.value() + width.value());
    }

    public Point(Scalar<Int>) {
        ...
    }
```

It would be convenient way:
```java
public Point(Scalar<Int> x, Scalar<Int> width) {
    this(new SumOf(x, width));
}
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@nikialeksey please, report bugs, not tasks: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html#5-report-when-it-is-broken

**Comment by nikialeksey** [comment]
@yegor256 Thanks! I updated description

**Comment by 0crat** [comment]
Job [#619](https://github.com/yegor256/cactoos/issues/619) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @nikialeksey[/z](https://www.0crat.com/u/nikialeksey), total is [+45](https://www.0crat.com/u/nikialeksey)

**Comment by nick318** [comment]
@yegor256 can I handle it?

**Comment by 0crat** [comment]
The job [#619](https://github.com/yegor256/cactoos/issues/619) assigned to @nick318[/z](https://www.0crat.com/u/nick318), here is [why](https://www.0crat.com/footprint/C63314D6Z/460045609). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by nick318** [comment]
@nikialeksey since there is already a class `scalar/SumOf.java`, but it's implement `Scalar<Double>`, what do you expect:
1 Implement one more constructor in `SumOf.java`, usage will be `() -> new SumOf(x, with).intValue()`
2 Create new class which will be generic? usage will be `new SumOfScalar(x, with)`

**Comment by nikialeksey** [comment]
@nick318 There is need to implement few constructors for eash type: `Long, Integer, Float, Double`, I think.

**Comment by 0crat** [comment]
@nick318[/z](https://www.0crat.com/u/nick318) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by nick318** [comment]
@nikialeksey close the issue please, since PR is merged

**Comment by nikialeksey** [comment]
@nick318 oh, `SumOfDoubleScalar` - it's not oop, because `SumOf` already exists. So, in description of this issue I wanted:
```java
public Point(Scalar<Int> x, Scalar<Int> width) {
    this(new SumOf(x, width));
}
```

but now I only can this:
```java
public Point(Scalar<Int> x, Scalar<Int> width) {
    this(new SumOfIntScalar(x, width));
}
```

or:

```java
public Point(Scalar<Int> x, Scalar<Int> width) {
    this(new SumOfScalar(x, width).value());
}
```

@yegor256 what do you think?

**Comment by nick318** [comment]
@nikialeksey I will think about. Probably I can make an interface SumOfScalar<T extends Number> what do you think?

**Comment by nikialeksey** [comment]
@nick318 I think it's good idea, but why not [create](https://github.com/yegor256/cactoos/issues/619#issuecomment-366017339) few constructors in `SomOf`? Then I can do this thing from the description:
```java
public Point(Scalar<Int> x, Scalar<Int> width) {
    this(new SumOf(x, width));
}
```

**Comment by nick318** [comment]
@nikialeksey simply add constuctors will not work since `SumOf `extends `NumberInverope ` which implements `Scalar<Double>`, so in your case usage will be:
```
public Point(Scalar<Int> x, Scalar<Int> width) {
    this(() -> new SumOf(x, width).intValue());
}
```
If you like it, I can create ctors for `SumOf`

**Comment by nick318** [comment]
@nikialeksey It is not oop too, since you should say what exactly type of number you wanna get

**Comment by nikialeksey** [comment]
`SumOf:`
```java
    public SumOf(final Scalar<Integer>... src) {
        this(
            new IterableOf<>(
                new CollectionOf<>(src)
                    .stream()
                    .map(
                        scalar -> new UncheckedScalar<>(scalar).value()
                    ).collect(Collectors.toList())
            )
        );
    }
```

`SumOfTest`:
```java
    @Test
    public void sumOfScalars() {
        MatcherAssert.assertThat(
            new SumOf(new Constant<>(1), new Constant<>(2)).intValue(),
            new IsEqual<>(3)
        );
    }
```

**Comment by nikialeksey** [comment]
@nick318 I just copied from `SumOfScalar.java`

**Comment by nick318** [comment]
@nikialeksey take a look carefully at `new SumOf(new Constant<>(1), new Constant<>(2)).intValue()`
Do you want to use it like:
```
public Point(Scalar<Int> x, Scalar<Int> width) {
    this(new SumOf(x, width).intValue());
}
```
There is not OOP here also.

**Comment by nikialeksey** [comment]
@nick318 oh, you are right! So, as a result:
`SumOf` is `Scalar<Double>` and we can not do this:
```java
public Point(Scalar<Int> x, Scalar<Int> width) {
    this(new SumOf(x, width));
}
```

But, this look like copy-paste: 
- `SumOfDoubleScalar`
- `SumOfFloatScalar`
- `SumOfIntScalar`
- `SumOfLongScalar`

Actually It is enough for my purposes! Thanks, @nick318

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@nick318 According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>Some of ticket messages must mention all pull requests where the problem was actually fixed.

Please provide a link to corresponding PR in any of your messages.

**Comment by nick318** [comment]
@ypshenychka just updated, thanks

**Comment by ypshenychka** [comment]
@nick318 Great! Thank you

**Comment by ypshenychka** [comment]
@0crat Quality acceptable

**Comment by 0crat** [comment]
QA review completed: +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+360](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @nick318[/z](https://www.0crat.com/u/nick318), total is [+290](https://www.0crat.com/u/nick318)
