### ISSUE TITLE
Misprint in iterator.Partitioned `sze`

### ISSUE THREAD

**Issue by SharplEr** [yegor256/cactoos#620]
`org.cactoos.iterator.Partitioned` only one class in all project where use word `sze`, in all other classes used `size`. Looks like a simple misprint.

P.S.
I know it's not a serious problem, but still.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@SharplEr it looks OK to me, we don't want to use similar names as ctor arguments and class attributes

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#620` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#620](https://github.com/yegor256/cactoos/issues/620) was not in scope
