### ISSUE TITLE
There are no simple way for split collection on values and exceptions

### ISSUE THREAD

**Issue by SharplEr** [yegor256/cactoos#621]
Imagine you have something like that:

```Java
Collection<IoCheckedScalar<String>> full = new CollectionOf(
            new IoCheckedScalar<>(()-> "cool"),
            new IoCheckedScalar<>(()-> { throw new IOException("not cool");}),
            new IoCheckedScalar<>(()-> "okay"),
            new IoCheckedScalar<>(()-> { throw new IOException("not okay");}));
```
But you want to get two collections:
```Java
Collection<String> values;
Collection<IOException> errors;
```
Now we have to write something like that (in case if we want to call every scalar only once):

```Java
// Say goodbye to type-safety
Collection<Object> data = new Mapped<IoCheckedScalar<String>, Object>(
            x -> {
                try {
                    return x.value();
                } catch (IOException e) {
                    return e;
                }
            },
            full
);

// Say hello to instanceof
Collection<String> values = new Filtered(x -> x instanceof String, data);
Collection<IOException> errors = new Filtered(x -> x instanceof IOException, data);
```
Or we can do the same with two `Filtered` calls. But then we will call to each `IoCheckedScalar` two times.

But I think we can introduce two new classes to do it better:

```Java
SplitResult<String> values = new SplitOf(full).value();
CollectionEnvelope<IOException> errors = values.errors();
```
Where `SplitResult<T> extends CollectionEnvelope<T> and SplitOf<T> extends Scalar<SplitResult<T>>`

There is no calculation in the constructor, but when you call `SplitOf.value()` errors calculate too (and put both in a new object), so when you call `SplitResult.errors()` it has already been founded.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@SharplEr interesting idea... have you seen something similar in Guava or Apache Commons? Also, have you seen this: #595

**Comment by SharplEr** [comment]
@yegor256  I'm not a frequent user of Guava or Apache Commons. Fast googling doesn't give me information about something similar in there.
But the problem is real. In another open source project in which I participate, such putting in `Object` and extract with `instanceof` or some other mechanism occur frequently. Just look at this nightmare in `get` methods: [tuple approach](https://github.com/apache/ignite/blob/beb242bc22aa7ca6c068fd59a09965fa5967177e/modules/core/src/main/java/org/apache/ignite/internal/processors/cache/CacheInvokeResult.java) or [Object + flag approach](https://github.com/apache/ignite/blob/e922dda6e9230ff7715f83c7b81e5656e8e856a0/modules/core/src/main/java/org/apache/ignite/internal/util/future/GridFinishedFuture.java).

The `Grouped` do the similar thing, but it groups by values. But I told about grouping by types. You can do the same with `Grouped`+`instanceof`, and in general case, there is no any other way to do that.

But in case if you don't violate type-safety all your functions can return a result of reasonable type or an exception. So it's enough to have only this special case of grouping by two types.

**Comment by yegor256** [comment]
@SharplEr can you give me a practical example of where this design is required? I think that it's wrong in the first place. Creating some tools to support bad design is a wrong idea for Cactoos, I believe.

**Comment by SharplEr** [comment]
@yegor256 it's required when you have collections of lambdas or futures which you gonna process in the same manner. After you get this two collections with values and exceptions you can map both (like send results to users and log exceptions to file). Collections of futures can appear when you are trying to ask about information a lot of nodes (in a distributed system for example). Example of using (I'm trying to mimic your OOP style):

```Java
public final class RequesOf<T> implements Scalar<SplitResult<T>> {
   private final Message m;
   private final CollectionEnvelope<Node> nodes;

   public RequesBase(Message m, CollectionEnvelope<Node> nodes) {
      this.m = m;
      this.nodes = nodes;
   }

   public SplitResult<T> value() {
      return new SplitOf(new Mapped(n->new SendOf(n, m), nodes)).value();
   }
}

public final class ResultOf<T> implements Scalar<CollectionEnvelope<T>> {
   priate final Scalar<SplitResult<T>> origin;
   private final Proc<IOException> errorProcess;

   public RequestOf(Scalar<SplitResult<T>> origin, Proc<IOException> errorProcess) {
       this.origin = origin;
       this.errorProcess = errorProcess;
   }

   public CollectionEnvelope<T> value() {
       SplitResult<T> results = origin.value();
       errorProcess.exec(result.errors())
       return results;
   }
}
```

Does such design is wrong?

**Comment by yegor256** [comment]
@SharplEr keeping objects __and__ exceptions in the same list sounds like a bad idea... Even though we will split them to two lists. Why can't you use good old try/catch?

**Comment by SharplEr** [comment]
@yegor256 It is helpful when you want to process all exceptions together. Like that:

```Java
/** Return true if we get result more than from half of the cluster. */
public boolean isResultConsistent() {
    return errors.size() < values.size()
}
```

**Comment by yegor256** [comment]
@SharplEr I think it's possible to do what you are looking for using existing Cactoos primitives:

```java
Collection<Scalar<String>> list = new CollectionOf<Scalar<String>>(
  ()-> "cool",
  ()-> { throw new IOException("not cool"); },
  ()-> "okay",
  ()-> { throw new IOException("not okay"); }
);
ExecutorService svc = Executors.newFixedThreadPool(1);
Collection<Future<String>> futures = new Mapped<>(
  scalar -> svc.submit(new CallableOf<>(scalar))
);
int success = new Filtered<>(future -> future.isDone(), futures);
int failures = new Filtered<>(future -> !future.isDone(), futures);
```

WDYT?

**Comment by SharplEr** [comment]
@yegor256 looks okay for me.
