### ISSUE TITLE
Javadoc of Sync... classes are broken

### ISSUE THREAD

**Issue by Maratori** [yegor256/cactoos#622]
1. `SyncText` and `SyncOutput` has irrelevant statement `There is no thread-safety guarantee.` in javadoc.
1. There is missing statement `Objects of this class are thread-safe.` in javadoc of `SyncScalar` and `SyncIterator`.
3. `SyncInput` is the single class that has statement `This class is thread-safe.` in javadoc. All other classes have `Objects of this class are thread-safe.`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#622` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#622](https://github.com/yegor256/cactoos/issues/622) was not in scope
