### ISSUE TITLE
Usage of String.format() is a bug?

### ISSUE THREAD

**Issue by Maratori** [yegor256/cactoos#629]
Should we replace all `String.format(...)` to `new FormattedText(...).asString()`?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@Maratori we can, but tomorrow someone else will use `String.format()` again. How can we prevent this from happening? Any ideas?

**Comment by Maratori** [comment]
@yegor256 I'm not ready now to answer that question. Let's return to this when I have the answer.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30)

**Comment by ypshenychka** [comment]
@yegor256 I assume I should report bad quality here since no job was actually done, right?

**Comment by 0crat** [comment]
The job [#629](https://github.com/yegor256/cactoos/issues/629) assigned to @sharpler[/z](https://www.0crat.com/u/sharpler), here is [why](https://www.0crat.com/footprint/C63314D6Z/462300185). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by yegor256** [comment]
@ypshenychka it was a bug, let us fix it...

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/629#issuecomment-366264500))

@yegor256 This is what I know about this job, as in [§32](http://datum.zerocracy.com/pages/policy.html#32):

  * The job [#629](https://github.com/yegor256/cactoos/issues/629) is [in scope](http://datum.zerocracy.com/pages/policy.html#14) for 18hr
  * The role is `DEV`
  * The job is assigned to @sharpler[/z](https://www.0crat.com/u/sharpler) for [16hr](http://datum.zerocracy.com/pages/policy.html#8)
  * There is a monetary reward attached
  * @sharpler[/z](https://www.0crat.com/u/sharpler) will get 50% of their hourly rate for this job
  * The job doesn't have any [impediments](http://datum.zerocracy.com/pages/policy.html#9)
  * The [budget](http://datum.zerocracy.com/pages/policy.html#4) is 30 minutes/points
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%23629%27%7D) (restricted area)

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/629#issuecomment-366269541))

@yegor256 The user @sharpler[/z](https://www.0crat.com/u/sharpler) resigned from [#629](https://github.com/yegor256/cactoos/issues/629), please stop working

**Comment by ypshenychka** [comment]
@yegor256 Then I think it should be reopened and I will review it after completion.

**Comment by yegor256** [comment]
@ypshenychka this job is not in scope. It was closed without become a real "job". Zerocrat asked you to review it by mistake. Ignore it.

**Comment by 0crat** [comment]
The job [#629](https://github.com/yegor256/cactoos/issues/629) assigned to @rexim[/z](https://www.0crat.com/u/rexim), here is [why](https://www.0crat.com/footprint/C63314D6Z/480724927). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by rexim** [comment]
@yegor256 please resign my from this job. See https://github.com/zerocracy/farm/issues/588. Thanks.

**Comment by rexim** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/629#issuecomment-366544197))

@rexim The impediment for [#629](https://github.com/yegor256/cactoos/issues/629) was registered successfully by @rexim[/z](https://www.0crat.com/u/rexim)

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/629#issuecomment-366692093))

@yegor256 The user @rexim[/z](https://www.0crat.com/u/rexim) resigned from [#629](https://github.com/yegor256/cactoos/issues/629), please stop working

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/629#issuecomment-366692104))

@yegor256 The job [#629](https://github.com/yegor256/cactoos/issues/629) is now out of scope

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/629#issuecomment-366692104))

@yegor256 Job [#629](https://github.com/yegor256/cactoos/issues/629) was not in scope
