### ISSUE TITLE
Let's do a not procedural temporary file creation/deletion

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#63]
This [kind of code](https://github.com/yegor256/cactoos/blob/c4f228d1eeef7e165a670b5a5536b398dc2fb5a5/src/test/java/org/cactoos/io/FileAsInputTest.java#L51-L52) is very procedural:
```java
final File temp = File.createTempFile("cactoos-1", "txt-1");
temp.deleteOnExit();
```
So, let's do a not procedural temporary file creation/deletion.

**Comment by 0crat** [comment]
@fabriciofx I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by englishman** [comment]
We can use [TemporaryFolder](http://junit.org/junit4/javadoc/4.12/org/junit/rules/TemporaryFolder.html) JUnit rule for this. Specifically, [newFile](http://junit.org/junit4/javadoc/4.12/org/junit/rules/TemporaryFolder.html#newFile(java.lang.String)) method.

**Comment by fabriciofx** [comment]
@englishman Do we **must** declare `TemporaryFolder` as a `@Rule`? If yes, I don't like it a good solution, because [tests methods must share nothing](http://www.yegor256.com/2016/05/03/test-methods-must-share-nothing.html).

**Comment by englishman** [comment]
@fabriciofx yes, I know (actually, I'm fighting against this sharing in my current project). Rules are the standard JUnit way to do smth BEFORE and AFTER a test method (grant/free resource etc.).

Otherwise, we have to impl smth like this
```
@Test void testMethod() {
    try(File tmp = new TempFile(...)) {
      ...do testing...
    }
}
```
Might be it's good idea to implement our own `TempFile` class impl.

**Comment by fabriciofx** [comment]
@yegor256 WDYT about this issue? Should I close it or continue? If I should continue, could you assign it to me?

**Comment by yegor256** [comment]
@fabriciofx let's keep it open, we'll find someone to solve it

**Comment by 0crat** [comment]
Job [#63](https://github.com/yegor256/cactoos/issues/63) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#63](https://github.com/yegor256/cactoos/issues/63) assigned to llorllale. The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#63` already assigned to @llorllale, can't assign to @llorllale

**Comment by llorllale** [comment]
@yegor256 0crat assigned this job to me despite there already being a PR for this (#345)

**Comment by llorllale** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/63#issuecomment-357301250))

@llorllale The impediment was registered successfully

**Comment by yegor256** [comment]
@llorllale something it happens. You can just copy the PR or implement it your own way.

**Comment by 0crat** [comment]
@llorllale[/z](http://www.0crat.com/u/llorllale) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by llorllale** [comment]
@fabriciofx can we close this?

**Comment by fabriciofx** [comment]
@llorllale I think so. @yegor256 I'll close this issue because I accept the code and it was already merged.

**Comment by 0crat** [comment]
Order was successfully finished: +30 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale), total is [+225](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#63](https://github.com/yegor256/cactoos/issues/63) is now out of scope
