### ISSUE TITLE
TeeInput test class is incomplete

### ISSUE THREAD

**Issue by driver733** [yegor256/cactoos#631]
The TeeInput class has very low test coverage. (6%) We should all of it's constructors and achieve higher test coverage level by doing that.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#631](https://github.com/yegor256/cactoos/issues/631) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @driver733[/z](https://www.0crat.com/u/driver733), total is [+75](https://www.0crat.com/u/driver733)

**Comment by 0crat** [comment]
The job [#631](https://github.com/yegor256/cactoos/issues/631) assigned to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), here is [why](https://www.0crat.com/footprint/C63314D6Z/461922355). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@proshin-roman[/z](https://www.0crat.com/u/proshin-roman) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@proshin-roman[/z](https://www.0crat.com/u/proshin-roman) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by proshin-roman** [comment]
@0crat waiting for pull request merging (it's already approved by CR)

**Comment by 0crat** [comment]
> @0crat waiting for pull request merging (it's already approved by CR) ([here](https://github.com/yegor256/cactoos/issues/631#issuecomment-368244332))

@proshin-roman The impediment for [#631](https://github.com/yegor256/cactoos/issues/631) was registered successfully by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by proshin-roman** [comment]
@driver733 the issue was fixed in pull request https://github.com/yegor256/cactoos/pull/698 - please check if the issue can be closed now.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality was "good": +35 points just awarded to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/cactoos/issues/631#issuecomment-369512708))

@ypshenychka The job [#631](https://github.com/yegor256/cactoos/issues/631) is now out of scope

**Comment by 0pdd** [comment]
@driver733 the puzzle [#720](https://github.com/yegor256/cactoos/issues/720) is still not solved; solved: [#721](https://github.com/yegor256/cactoos/issues/721).

**Comment by 0pdd** [comment]
@driver733 all 2 puzzles are solved here: [#720](https://github.com/yegor256/cactoos/issues/720), [#721](https://github.com/yegor256/cactoos/issues/721).

**Comment by 0pdd** [comment]
@driver733 the puzzle [#794](https://github.com/yegor256/cactoos/issues/794) is still not solved; solved: [#720](https://github.com/yegor256/cactoos/issues/720), [#721](https://github.com/yegor256/cactoos/issues/721).
