### ISSUE TITLE
Extend Directory class functionality 

### ISSUE THREAD

**Issue by driver733** [yegor256/cactoos#632]
I think that we could extend the functionality of the `Directory` class. Right now it only encapsulates the file path and allows the user to walk through the files in the directory. However, it would be useful to have some more advanced features, such as an ability to have a decorator for the `Directory` class that would extract all files with a certain extension. I believe that we should create an interface for the `Directory` class that would enable us to create us decorating classes, that add convenience features to the work with directories. 

The first step would be to create an interface for the `Directory` class and to create a first decorating class that returns files from the directory with the provided extension.

p.s. Here is a real-life [example](https://github.com/driver733/VKMusicUploader/blob/master/src/main/java/com/driver733/vkmusicuploader/audio/AudiosBasic.java) of usage of the aforementioned functionality.

**Comment by yegor256** [comment]
@driver733 but `Directory` is an `Iterable`, you can decorate it with `Filtered`, just like any other iterable. Or I'm missing something? Show the code you want to implement and can't do now, please.

**Comment by driver733** [comment]
@yegor256 There many different things that can be implemented. Here is one idea. 
```
new DirectoryZipped( // Zip the directory
	new DirectoryWithFiles( // Copy files to the directory
		new DirectoryBasic( // Create if does not exist
			"~/Users/admin/dir1"
			),
		"~/Users/admin/texts/data.txt"	
	)
).asPath()
//.asFile()
```

**Comment by yegor256** [comment]
@driver733 if you just want to deal with a directory, you already have `Path` or `File` from JDK. The only purpose of `Directory` is to iterate files. Then, you can add decorators, to do something with them.

**Comment by driver733** [comment]
@yegor256 Could we then create classes that, for example, zip files and directories in OOP way?
The JDK (java.util.zip) provides functionality that is very procedural.
Here is one [library](https://github.com/zeroturnaround/zt-zip) with the functionality that would be useful to have in cactoos.

**Comment by yegor256** [comment]
@driver733 yes, we can create something to zip a list of files:

```
Input input = new Zip(new Directory("/tmp/my-files"));
```

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#632` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#632](https://github.com/yegor256/cactoos/issues/632) was not in scope
