### ISSUE TITLE
Using inheritance not for Decorating Envelopes

### ISSUE THREAD

**Issue by alex-semenyuk** [yegor256/cactoos#634]
In the following classes are used inheritance (not for Decorating Envelopes):
` org.cactoos.io.TeeReader`, `org.cactoos.io.TeeInputStream`, `org.cactoos.scalar.NumberEnvelope`, `org.cactoos.io.TeeOutputStream`, `org.cactoos.scalar.NumberOf`, `org.cactoos.io.WriterAsOutputStream`, `org.cactoos.io.ReaderOf`, `org.cactoos.io.InputStreamOf`, `org.cactoos.io.WriterTo`, `org.cactoos.io.OutputStreamTo` This breaks the principle "Inheritance implementation only for Decorating Envelopes"

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@alex-semenyuk we can't do anything in this case, since JDK gives us classes (`Number`, `InputStream`, etc.) instead of interface. That's why we have to use `extends' instead of `implements'.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#634` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#634](https://github.com/yegor256/cactoos/issues/634) was not in scope
