### ISSUE TITLE
Attention message in README.md is outdated

### ISSUE THREAD

**Issue by t-izbassar** [yegor256/cactoos#635]
The message from [README.md](https://github.com/yegor256/cactoos/blob/master/README.md) is now:
> ATTENTION: We're still in a very early alpha version, the API may and will change frequently. Please, use it at your own risk, until we release version 1.0 (July August December 2017).

Which is obviously outdated and should be fixed.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@t-izbassar fixed, thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#635` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job [#635](https://github.com/yegor256/cactoos/issues/635) was not in scope
