### ISSUE TITLE
LengthOfTest.java:89-91: Fix calculation of length for...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#636]
The puzzle `547-eacac169` from #547 has to be resolved:

https://github.com/yegor256/cactoos/blob/eff4166619b68780d963d807d29fb751ed2a4e33/src/test/java/org/cactoos/io/LengthOfTest.java#L89-L91

The puzzle was created by Yegor Bugayenko on 12-Feb-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#636](https://github.com/yegor256/cactoos/issues/636) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#636](https://github.com/yegor256/cactoos/issues/636) assigned to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), here is [why](https://www.0crat.com/footprint/C63314D6Z/462028057). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@proshin-roman[/z](https://www.0crat.com/u/proshin-roman) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0pdd** [comment]
@0pdd all puzzles are solved

**Comment by 0crat** [comment]
@proshin-roman[/z](https://www.0crat.com/u/proshin-roman) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by proshin-roman** [comment]
@0crat waiting (the issue is waiting for pull request review)

**Comment by 0crat** [comment]
> @0crat waiting (the issue is waiting for pull request review) ([here](https://github.com/yegor256/cactoos/issues/636#issuecomment-368220060))

@proshin-roman The impediment for [#636](https://github.com/yegor256/cactoos/issues/636) was registered successfully by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by 0pdd** [comment]
The puzzle `547-eacac169` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@proshin-roman According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Some of ticket messages must mention all pull requests where the problem was actually fixed.

Please provide a link to corresponding PR in any of your messages.

**Comment by proshin-roman** [comment]
@ypshenychka This issue was fixed in pull request https://github.com/yegor256/cactoos/pull/701

**Comment by ypshenychka** [comment]
@proshin-roman Thank you.

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+734](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
The job [#636](https://github.com/yegor256/cactoos/issues/636) assigned to @nick318[/z](https://www.0crat.com/u/nick318), here is [why](https://www.0crat.com/footprint/C63314D6Z/591819778). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/636#issuecomment-369356858))

@yegor256 The user @nick318[/z](https://www.0crat.com/u/nick318) resigned from [#636](https://github.com/yegor256/cactoos/issues/636), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/636#issuecomment-369356886))

@yegor256 The job [#636](https://github.com/yegor256/cactoos/issues/636) is now out of scope

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/636#issuecomment-369356886))

@yegor256 Job [#636](https://github.com/yegor256/cactoos/issues/636) was not in scope
