### ISSUE TITLE
Drop takes framework dependency 

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#64]
In README.md we can read:

> How to use. The library has no dependencies. All you need is this (get the latest version here):

So, `cactoos` depends on [takes](http://www.takes.org) framework (in `pom.xml` and `UrlAsInputTest.java`) and this dependency should be removed.

**Comment by 0crat** [comment]
@fabriciofx I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by englishman** [comment]
@fabriciofx I guess README statement is about absents only PROD dependency.

**Comment by fabriciofx** [comment]
@englishman Yeah, I noticed that after opened the issue! So, should I close it or it's interesting change the README to be explicit about absence of dependencies its just  in production?

**Comment by yegor256** [comment]
@fabriciofx just close the issue. We don't have `runtime` or `compile` dependencies. `provided` and `test` are harmless.
