### ISSUE TITLE
Some constructors of SolidMap are not covered by unit tests 

### ISSUE THREAD

**Issue by nick318** [yegor256/cactoos#640]
Following constructors in `SolidMap.java` are not covered by unit tests.

`public SolidMap(final Map<X, Y> map, final Map.Entry<X, Y>... list)`
`public <Z> SolidMap(final Func<Z, X> key,
        final Func<Z, Y> value, final Map<X, Y> map,
        final Iterable<Z> list)`
`public <Z> SolidMap(final Func<Z, X> key,
        final Func<Z, Y> value, final Iterable<Z> list)`
`public SolidMap(final Iterator<Map.Entry<X, Y>> list)`

Expected:
All code in constructors is covered.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#640](https://github.com/yegor256/cactoos/issues/640) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @nick318[/z](https://www.0crat.com/u/nick318), total is [+15](https://www.0crat.com/u/nick318)

**Comment by 0crat** [comment]
The job [#640](https://github.com/yegor256/cactoos/issues/640) assigned to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc), here is [why](https://www.0crat.com/footprint/C63314D6Z/462053743). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by flslkxtc** [comment]
@nick318 ctor `publicSolidMap(final Iterator<Map.Entry<X, Y>> list)`  doesn't work properly for now, this behavior was already described in issues https://github.com/yegor256/cactoos/issues/625 and https://github.com/yegor256/cactoos/issues/659. I've ignored this ctor in my pull request for this issue: https://github.com/yegor256/cactoos/pull/669.

**Comment by 0crat** [comment]
@flslkxtc[/z](https://www.0crat.com/u/flslkxtc) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@flslkxtc[/z](https://www.0crat.com/u/flslkxtc) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by flslkxtc** [comment]
@nick318 pull request https://github.com/yegor256/cactoos/pull/669 with test for SolidMap has been merged, can we close this issue now?

**Comment by flslkxtc** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/640#issuecomment-368297560))

@flslkxtc The impediment for [#640](https://github.com/yegor256/cactoos/issues/640) was registered successfully by @flslkxtc[/z](https://www.0crat.com/u/flslkxtc)

**Comment by flslkxtc** [comment]
@nick318 @yegor256, we can close this issue now.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+813](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality was "good": +35 points just awarded to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc), total is [+125](https://www.0crat.com/u/flslkxtc)

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/cactoos/issues/640#issuecomment-368788617))

@ypshenychka The job [#640](https://github.com/yegor256/cactoos/issues/640) is now out of scope
