### ISSUE TITLE
StickyIterator must be replaced with IteratorOf

### ISSUE THREAD

**Issue by Maratori** [yegor256/cactoos#641]
1. "Sticky" means "cached". But there is nothing to cache in the `Iterator`. It always supply a new value calling `next()`.
1. `StickyIterator` has the primary ctor with `Iterator<X>` as parameter. So it is a decorator of any `Iterator`. But that decoration doesn't bring new functionality. So it must be deleted.
1. There is also secondary ctor with varargs `X...` in `StickyIterator`. It creates an iterator from list of objects. And it must be renamed to `IteratorOf`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@Maratori well, I disagree. We do cache the iterator inside, since we fetch it entirely and then use the cached iterable over and over again.

**Comment by Maratori** [comment]
@yegor256 What do you mean "over and over again"? Iterator is a something that can be used once.
Do you talking about `StickyIterable` or `StickyIterator`?

**Comment by yegor256** [comment]
@Maratori right, my bad. You are right, we should rename it to `IteratorOf`

**Comment by 0crat** [comment]
Job [#641](https://github.com/yegor256/cactoos/issues/641) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Job [#641](https://github.com/yegor256/cactoos/issues/641) is already in scope

**Comment by 0crat** [comment]
The job [#641](https://github.com/yegor256/cactoos/issues/641) assigned to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc), here is [why](https://www.0crat.com/footprint/C63314D6Z/462145063). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by flslkxtc** [comment]
@yegor256 can you remove this assignment from me? This issue was closed before @0crat assigned it.

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/cactoos/issues/641#issuecomment-366434615). You must always start your message with my name if you want to address it to me, see [§1](http://datum.zerocracy.com/pages/policy.html#1).

**Comment by 0crat** [comment]
@flslkxtc[/z](https://www.0crat.com/u/flslkxtc) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by flslkxtc** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/641#issuecomment-367242170))

@flslkxtc The impediment for [#641](https://github.com/yegor256/cactoos/issues/641) was registered successfully by @flslkxtc[/z](https://www.0crat.com/u/flslkxtc)

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/641#issuecomment-369356776))

@yegor256 The user @flslkxtc[/z](https://www.0crat.com/u/flslkxtc) resigned from [#641](https://github.com/yegor256/cactoos/issues/641), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/641#issuecomment-369356786))

@yegor256 The job [#641](https://github.com/yegor256/cactoos/issues/641) is now out of scope
