### ISSUE TITLE
Calling ItemAt.value() twice doesn't work

### ISSUE THREAD

**Issue by aliceice** [yegor256/cactoos#643]
If I want to reuse an `ItemAt` it currently throws an IOException.

```
final ItemAt<Integer> item = new ItemAt<>(new IterableOf<>(1));
item.value(); // returns 1
item.value(); // throws IOException
```

I get following Stacktrace:

```
java.io.IOException: The iterable is empty
	at org.cactoos.scalar.ItemAt.lambda$new$0(ItemAt.java:69)
	at org.cactoos.scalar.ItemAt.value(ItemAt.java:253)
```

I'd expect it to return the same object again.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#643](https://github.com/yegor256/cactoos/issues/643) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#643](https://github.com/yegor256/cactoos/issues/643) assigned to @driver733[/z](https://www.0crat.com/u/driver733), here is [why](https://www.0crat.com/footprint/C63314D6Z/462240122). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by driver733** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/643#issuecomment-366125663))

@driver733 The impediment for [#643](https://github.com/yegor256/cactoos/issues/643) was registered successfully by @driver733[/z](https://www.0crat.com/u/driver733)

**Comment by svendiedrichsen** [comment]
@aliceice I think you can close this. The PR has been merged.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30)

**Comment by ypshenychka** [comment]
@0crat Quality good

**Comment by 0crat** [comment]
QA review completed: +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+120](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality was "good": +35 points just awarded to @driver733[/z](https://www.0crat.com/u/driver733), total is [+200](https://www.0crat.com/u/driver733)
