### ISSUE TITLE
Using LoggingInput without providing a Logger does not work

### ISSUE THREAD

**Issue by aliceice** [yegor256/cactoos#644]
When doing this:

```
new LengthOf(
    new LoggingInput(
        new InputOf("Hi there"),
        "my source"
    )
).intValue();
```

I'm getting following Exception:

```
java.lang.NullPointerException
	at org.cactoos.io.LoggingInputStream.read(LoggingInputStream.java:130)
	at org.cactoos.io.LoggingInputStream.read(LoggingInputStream.java:108)
	at org.cactoos.io.LengthOf.lambda$new$0(LengthOf.java:72)
	at org.cactoos.scalar.NumberEnvelope.lambda$new$1(NumberEnvelope.java:73)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:70)
	at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
	at org.cactoos.scalar.NumberEnvelope.intValue(NumberEnvelope.java:98)
```

I'd expect it to log to a generated `java.util.logging.Logger`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#644](https://github.com/yegor256/cactoos/issues/644) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#644](https://github.com/yegor256/cactoos/issues/644) assigned to @nikialeksey[/z](https://www.0crat.com/u/nikialeksey), here is [why](https://www.0crat.com/footprint/C63314D6Z/491962292). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@nikialeksey[/z](https://www.0crat.com/u/nikialeksey) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@nikialeksey[/z](https://www.0crat.com/u/nikialeksey) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by nikialeksey** [comment]
@0crat waiting

**Comment by 0crat** [comment]
The user @nikialeksey[/z](https://www.0crat.com/u/nikialeksey) resigned from [#644](https://github.com/yegor256/cactoos/issues/644), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 points just awarded to @nikialeksey[/z](https://www.0crat.com/u/nikialeksey)

**Comment by 0crat** [comment]
The job [#644](https://github.com/yegor256/cactoos/issues/644) assigned to @nick318[/z](https://www.0crat.com/u/nick318), here is [why](https://www.0crat.com/footprint/C63314D6Z/591957929). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by nikialeksey** [comment]
@yegor256 why 0crat resigned me? I told him "waiting"

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/644#issuecomment-368729877))

@nikialeksey The impediment for [#644](https://github.com/yegor256/cactoos/issues/644) was registered successfully by @nikialeksey[/z](https://www.0crat.com/u/nikialeksey)

**Comment by yegor256** [comment]
@nikialeksey looks like it was a bug. Zerocrat didn't reply to you, which meant that he didn't see your message. Sorry.

**Comment by nikialeksey** [comment]
@yegor256 Created. What can we do with this issue? I have opened pull request on it

**Comment by yegor256** [comment]
@0crat assign @nikialeksey

**Comment by 0crat** [comment]
> @0crat assign @nikialeksey  ([here](https://github.com/yegor256/cactoos/issues/644#issuecomment-369835360))

@yegor256 The job [#644](https://github.com/yegor256/cactoos/issues/644) assigned to @nikialeksey[/z](https://www.0crat.com/u/nikialeksey), here is [why](https://www.0crat.com/footprint/C63314D6Z/610651518). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by nikialeksey** [comment]
@aliceice Request was merged

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/start_order.groovy
sun.reflect.GeneratedMethodAccessor767[-1] java.lang.reflect.InvocationTargetException: null
org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation[582] groovy.lang.GroovyRuntimeException: Cannot compare com.jcabi.xml.ListWrapper with value '[gh:yegor256/cactoos#726, gh:yegor256/cactoos#638]' and java.lang.Integer with value '32'
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/start_order.groovy
sun.reflect.GeneratedMethodAccessor767[-1] java.lang.reflect.InvocationTargetException: null
org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation[582] groovy.lang.GroovyRuntimeException: Cannot compare com.jcabi.xml.ListWrapper with value '[gh:yegor256/cactoos#726, gh:yegor256/cactoos#638]' and java.lang.Integer with value '32'
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/start_order.groovy
sun.reflect.GeneratedMethodAccessor780[-1] java.lang.reflect.InvocationTargetException: null
org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation[582] groovy.lang.GroovyRuntimeException: Cannot compare com.jcabi.xml.ListWrapper with value '[gh:yegor256/cactoos#726, gh:yegor256/cactoos#638]' and java.lang.Integer with value '32'
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/start_order.groovy
sun.reflect.GeneratedMethodAccessor767[-1] java.lang.reflect.InvocationTargetException: null
org.codehaus.groovy.runtime.typehandling.DefaultTypeTransformation[582] groovy.lang.GroovyRuntimeException: Cannot compare com.jcabi.xml.ListWrapper with value '[gh:yegor256/cactoos#726, gh:yegor256/cactoos#638]' and java.lang.Integer with value '32'
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by SharplEr** [comment]
@nikialeksey 
For some reason this task in my `Agenda` in 0crat site O_o

**Comment by 0crat** [comment]
> @0crat waiting  ([here](https://github.com/yegor256/cactoos/issues/644#issuecomment-373461313))

@SharplEr The impediment for [#644](https://github.com/yegor256/cactoos/issues/644) was registered successfully by @sharpler[/z](https://www.0crat.com/u/sharpler)

**Comment by nikialeksey** [comment]
@SharplEr hah, 0crat is broken. But anyway, @aliceice ping, request was merged for this issue

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @sharpler[/z](https://www.0crat.com/u/sharpler), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#644](https://github.com/yegor256/cactoos/issues/644) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/644#issuecomment-375337790))

@elenavolokhova This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#644](https://github.com/yegor256/cactoos/issues/644) is not in scope
  * The job is waiting quality review verdict by @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) for 6hr
  * @sharpler[/z](https://www.0crat.com/u/sharpler) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%23644%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by elenavolokhova** [comment]
@nikialeksey Why did you ask to close this issue? Do you agree to not be paid?

**Comment by elenavolokhova** [comment]
@0crat Quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
