### ISSUE TITLE
MapOf and MapEnvelope do not have pretty toString method

### ISSUE THREAD

**Issue by nick318** [yegor256/cactoos#646]
Class `MapOf.java` and its parent `MapEnvelope.java` do not have pretty `toString` method as `HashMap.java` has.
In my opinion developers used to use `toString` for some debug purposes.  

Expected:
`mapOf.toString returns "{key=value, key2=value2}"`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#646](https://github.com/yegor256/cactoos/issues/646) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @nick318[/z](https://www.0crat.com/u/nick318), total is [+30](https://www.0crat.com/u/nick318)

**Comment by 0crat** [comment]
The job [#646](https://github.com/yegor256/cactoos/issues/646) assigned to @sharpler[/z](https://www.0crat.com/u/sharpler), here is [why](https://www.0crat.com/footprint/C63314D6Z/462214752). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@sharpler[/z](https://www.0crat.com/u/sharpler) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://datum.zerocracy.com/pages/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by SharplEr** [comment]
@nick318 PR was merged, please close the issue )

**Comment by nick318** [comment]
@SharplEr thanks!

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@SharplEr According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>Some of ticket messages must mention all pull requests where the problem was actually fixed.

Please mention link to PR in any of your messages.

**Comment by 0crat** [comment]
@sharpler[/z](https://www.0crat.com/u/sharpler) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by SharplEr** [comment]
@ypshenychka [done](https://github.com/yegor256/cactoos/issues/646#issuecomment-368051707)

**Comment by ypshenychka** [comment]
@SharplEr thanks

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/cactoos/issues/646#issuecomment-368207529))

@ypshenychka There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/make_payment.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '//*[@id='45.share']/text()' not found in '<?xml version="1.0" encoding="UTF-8"?><html xmlns=..35780..</script>\uA      </body>\uA   \uA</html>': Index (0) is out of bounds (size=0)
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+678](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/cactoos/issues/646#issuecomment-368207529))

@ypshenychka There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/cost/make_payment.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.jcabi.xml.ListWrapper[162] com.jcabi.xml.ListWrapper$NodeNotFoundException: XPath '//*[@id='45.share']/text()' not found in '<?xml version="1.0" encoding="UTF-8"?><html xmlns=..35780..</script>\uA      </body>\uA   \uA</html>': Index (0) is out of bounds (size=0)
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @sharpler[/z](https://www.0crat.com/u/sharpler), total is [+140](https://www.0crat.com/u/sharpler)

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/cactoos/issues/646#issuecomment-368207529))

@ypshenychka You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `QA`.

**Comment by 0crat** [comment]
The job [#646](https://github.com/yegor256/cactoos/issues/646) assigned to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc), here is [why](https://www.0crat.com/footprint/C63314D6Z/591826990). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/646#issuecomment-369356690))

@yegor256 The user @flslkxtc[/z](https://www.0crat.com/u/flslkxtc) resigned from [#646](https://github.com/yegor256/cactoos/issues/646), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/646#issuecomment-369356690))

@yegor256 Job `gh:yegor256/cactoos#646` is not assigned, can't get performer

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/646#issuecomment-369356711))

@yegor256 The job [#646](https://github.com/yegor256/cactoos/issues/646) is now out of scope

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/646#issuecomment-369356711))

@yegor256 Job [#646](https://github.com/yegor256/cactoos/issues/646) was not in scope

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/646#issuecomment-369356711))

@yegor256 Job [#646](https://github.com/yegor256/cactoos/issues/646) was not in scope
