### ISSUE TITLE
ListEnvelope<T> does not implement equals()

### ISSUE THREAD

**Issue by svendiedrichsen** [yegor256/cactoos#648]
Thus you can't compare extending classes of ListEnvelope like you can with JDK lists.
i.e.: `new ListOf<>(1,2).equals(new ListOf<>(1,2))` results in `false` but should be `true`
That is also why all cactoos tests which use any ListEnvelope derived class have to compare the results of the `toArray`method.

JDK List.equals Javadoc: https://docs.oracle.com/javase/8/docs/api/java/util/List.html#equals-java.lang.Object-

BTW: additionally an implementation of the `toString` method would also allow for better logging of instances of derived ListEnvelope classes especially in test results.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#648](https://github.com/yegor256/cactoos/issues/648) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#648](https://github.com/yegor256/cactoos/issues/648) assigned to @nikialeksey[/z](https://www.0crat.com/u/nikialeksey), here is [why](https://www.0crat.com/footprint/C63314D6Z/491960229). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by svendiedrichsen** [comment]
PR has been merged.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30)

**Comment by ypshenychka** [comment]
@svendiedrichsen Looks like the job was not assigned to you. Why did you proceed with this? And also you  can't be both problem reporter and problem solver as per [QA rules](http://datum.zerocracy.com/pages/policy.html#42)

**Comment by ypshenychka** [comment]
@svendiedrichsen ping

**Comment by svendiedrichsen** [comment]
@ypshenychka Because the ticket wasn't assigned automatically and I was interested to contribute.

**Comment by ypshenychka** [comment]
@yegor256 Please advise how should I evaluate this ticket? To my mind, it should be bad quality.

**Comment by 0crat** [comment]
@nikialeksey[/z](https://www.0crat.com/u/nikialeksey) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by ypshenychka** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@ypshenychka yes, it's "bad"

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+686](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
> @0crat quality bad ([here](https://github.com/yegor256/cactoos/issues/648#issuecomment-368437811))

@ypshenychka You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `QA`.

**Comment by 0crat** [comment]
The job [#648](https://github.com/yegor256/cactoos/issues/648) assigned to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc), here is [why](https://www.0crat.com/footprint/C63314D6Z/591831085). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/648#issuecomment-369356637))

@yegor256 The user @flslkxtc[/z](https://www.0crat.com/u/flslkxtc) resigned from [#648](https://github.com/yegor256/cactoos/issues/648), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/648#issuecomment-369356659))

@yegor256 The job [#648](https://github.com/yegor256/cactoos/issues/648) is now out of scope

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/648#issuecomment-369356659))

@yegor256 Job [#648](https://github.com/yegor256/cactoos/issues/648) was not in scope
