### ISSUE TITLE
NullPointerException vs IllegalArgumentException

### ISSUE THREAD

**Issue by Maratori** [yegor256/cactoos#650]
Let's say we have such code.
```java
new UncheckedScalar<>(null).value();
```
It throws `NullPointerException`. Should we throw `IllegalArgumentException` instead?
> This is not about `UncheckedScalar` but about all cactoos classes.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@Maratori we are not checking for `null` anywhere. We are not "defensive" in this aspect. If `null` is provided, the code just breaks at __some__ point. That's how we are designed at the moment.

**Comment by Maratori** [comment]
@yegor256 Thank you for clarification.

**Comment by yegor256** [comment]
@Maratori I also explained it in the documentation: 0af9e4f

**Comment by 0crat** [comment]
The job [#650](https://github.com/yegor256/cactoos/issues/650) is now out of scope
