### ISSUE TITLE
Some constructors of MapOf are not covered by unit tests

### ISSUE THREAD

**Issue by nick318** [yegor256/cactoos#652]
Following code in constructors is not covered by unit tests:
```
@SafeVarargs
    public MapOf(final Map<X, Y> src, final Map.Entry<X, Y>... list) {
        this(src, new IterableOf<>(list));
    }
 public <Z> MapOf(final Func<Z, X> key,
        final Func<Z, Y> value, final Iterable<Z> list) {
        this(item -> new MapEntry<>(key.apply(item), value.apply(item)), list);
    }
public <Z> MapOf(final Func<Z, X> key,
        final Func<Z, Y> value, final Map<X, Y> src,
        final Iterable<Z> list) {
        this(
            item -> new MapEntry<>(key.apply(item), value.apply(item)),
            src, list
        );
    }
public MapOf(final Iterator<Map.Entry<X, Y>> entries) {
        this(() -> entries);
    }

```

Expected:
all code in constructors is covered

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#652](https://github.com/yegor256/cactoos/issues/652) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @nick318[/z](https://www.0crat.com/u/nick318), total is [+45](https://www.0crat.com/u/nick318)

**Comment by 0crat** [comment]
The job [#652](https://github.com/yegor256/cactoos/issues/652) assigned to @driver733[/z](https://www.0crat.com/u/driver733), here is [why](https://www.0crat.com/footprint/C63314D6Z/462254052). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by driver733** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/652#issuecomment-366137672))

@driver733 The impediment for [#652](https://github.com/yegor256/cactoos/issues/652) was registered successfully by @driver733[/z](https://www.0crat.com/u/driver733)

**Comment by driver733** [comment]
@nick318 Please close this issue.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@driver733 According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>Some of ticket messages must mention all pull requests where the problem was actually fixed.

Please provide a link to PR in any of your messages.

**Comment by driver733** [comment]
@ypshenychka Fixed.
PR - #660

**Comment by ypshenychka** [comment]
@driver733 Thank you.

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
QA review completed: +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+450](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @driver733[/z](https://www.0crat.com/u/driver733), total is [+320](https://www.0crat.com/u/driver733)
