### ISSUE TITLE
Usage of Boolean parameter of Ternary class is bad

### ISSUE THREAD

**Issue by nick318** [yegor256/cactoos#653]
In the following class `Ternary.java` there is a constructor with boolean flag:
```
public Ternary(final boolean cnd, final T cons, final T alter) {
        this(() -> cnd, cons, alter);
    }
```
That is wrong practice, I suggest to change it to special class `Condition` which will encapsulate the state.
Why booleans are wrong you can read [here](https://martinfowler.com/bliki/FlagArgument.html)

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@nick318 but in this case it's not a flag argument, it's the trigger of the core class logic.

**Comment by nick318** [comment]
@yegor256 agree

**Comment by 0crat** [comment]
The job [#653](https://github.com/yegor256/cactoos/issues/653) is now out of scope
