### ISSUE TITLE
Some constructors of AndInThreads are not covered in unit tests

### ISSUE THREAD

**Issue by nick318** [yegor256/cactoos#654]
Following constructors are not covered in unit tests:
```
public <X> AndInThreads(final Proc<X> proc, final Iterator<X> src) {
        this(new FuncOf<>(proc, true), src);
    }
public <X> AndInThreads(final Proc<X> proc, final Iterable<X> src) {
        this(new FuncOf<>(proc, true), src);
    }
public AndInThreads(final Iterator<Scalar<Boolean>> src) {
        this(new IterableOf<>(src));
    }
 @SafeVarargs
    public <X> AndInThreads(final ExecutorService svc,
        final Proc<X> proc, final X... src) {
        this(svc, new FuncOf<>(proc, true), src);
    }
public <X> AndInThreads(final ExecutorService svc,
        final Proc<X> proc, final Iterator<X> src) {
        this(svc, new FuncOf<>(proc, true), src);
    }
public <X> AndInThreads(final ExecutorService svc,
        final Proc<X> proc, final Iterable<X> src) {
        this(svc, new FuncOf<>(proc, true), src);
    }
@SafeVarargs
    public AndInThreads(final ExecutorService svc,
        final Scalar<Boolean>... src) {
        this(svc, new IterableOf<>(src));
    }
public AndInThreads(final ExecutorService svc,
        final Iterator<Scalar<Boolean>> src) {
        this(svc, new IterableOf<>(src));
    }
```
Expected:
should be covered by unit tests

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#654](https://github.com/yegor256/cactoos/issues/654) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @nick318[/z](https://www.0crat.com/u/nick318), total is [+60](https://www.0crat.com/u/nick318)

**Comment by 0crat** [comment]
The job [#654](https://github.com/yegor256/cactoos/issues/654) assigned to @driver733[/z](https://www.0crat.com/u/driver733), here is [why](https://www.0crat.com/footprint/C63314D6Z/501942009). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by driver733** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/654#issuecomment-366849674))

@driver733 The impediment for [#654](https://github.com/yegor256/cactoos/issues/654) was registered successfully by @driver733[/z](https://www.0crat.com/u/driver733)

**Comment by driver733** [comment]
PR - #687

**Comment by driver733** [comment]
@nick318 Please close this issue. The PR has been merged.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://datum.zerocracy.com/pages/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@driver733 According to our [QA Rules](http://datum.zerocracy.com/pages/policy.html#42):
>Messages in a ticket always start with a name of a user they are addressed to.

Please correct your [message](https://github.com/yegor256/cactoos/issues/654#issuecomment-367086132) by indicating an addressee in the beginning.

**Comment by driver733** [comment]
@ypshenychka Done.

**Comment by ypshenychka** [comment]
@driver733 Thanks.

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
QA review completed: +15 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+525](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @driver733[/z](https://www.0crat.com/u/driver733), total is [+365](https://www.0crat.com/u/driver733)

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/cactoos/issues/654#issuecomment-367464382))

@ypshenychka You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: QA.

**Comment by 0crat** [comment]
The job [#654](https://github.com/yegor256/cactoos/issues/654) assigned to @sharpler[/z](https://www.0crat.com/u/sharpler), here is [why](https://www.0crat.com/footprint/C63314D6Z/591834180). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by SharplEr** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/yegor256/cactoos/issues/654#issuecomment-370133962))

@SharplEr Can't understand "wait", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Remove this issue from scope (WBS)
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `waiting` Register an impediment for a job

**Comment by SharplEr** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/654#issuecomment-370134008))

@SharplEr The impediment for [#654](https://github.com/yegor256/cactoos/issues/654) was registered successfully by @sharpler[/z](https://www.0crat.com/u/sharpler)

**Comment by SharplEr** [comment]
@nick318 @driver733 @ypshenychka @yegor256  0crat assigned the closed issue to me. Looks like a bug. Or I should do something?

**Comment by SharplEr** [comment]
@nick318 @driver733 @yegor256 ping)

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @sharpler[/z](https://www.0crat.com/u/sharpler), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#654](https://github.com/yegor256/cactoos/issues/654) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/654#issuecomment-372045452))

@elenavolokhova This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#654](https://github.com/yegor256/cactoos/issues/654) is not in scope
  * The job is waiting quality review verdict by @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%23654%27%7D) (restricted area)

**Comment by elenavolokhova** [comment]
@yegor256 Looks like a bug with 0crat. It is the second issue assigned to dev and then to qa after it was closed already. Please, take a look at this. Thanks!

**Comment by elenavolokhova** [comment]
@0crat quality bad for this reopening of the ticket

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/654#issuecomment-372442851))

@yegor256 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#654](https://github.com/yegor256/cactoos/issues/654) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%23654%27%7D) (restricted area)
