### ISSUE TITLE
CollectionOf and its parent CollectionEvelope do not have pretty toString

### ISSUE THREAD

**Issue by nick318** [yegor256/cactoos#655]
`CollectionOf .java`and its parent `CollectionEvelope.java` do not have pretty toString as `AbstractCollection.java` has.

Expected:
[1,2,3,4]

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#655](https://github.com/yegor256/cactoos/issues/655) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @nick318[/z](https://www.0crat.com/u/nick318), total is [+120](https://www.0crat.com/u/nick318)

**Comment by 0crat** [comment]
The job [#655](https://github.com/yegor256/cactoos/issues/655) assigned to @driver733[/z](https://www.0crat.com/u/driver733), here is [why](https://www.0crat.com/footprint/C63314D6Z/511920135). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by driver733** [comment]
PR - #697.

**Comment by driver733** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/655#issuecomment-367146036))

@driver733 The impediment for [#655](https://github.com/yegor256/cactoos/issues/655) was registered successfully by @driver733[/z](https://www.0crat.com/u/driver733)

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+718](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality was "good": +35 points just awarded to @driver733[/z](https://www.0crat.com/u/driver733), total is [+475](https://www.0crat.com/u/driver733)

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/cactoos/issues/655#issuecomment-368482878))

@ypshenychka You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `QA`.

**Comment by 0crat** [comment]
The job [#655](https://github.com/yegor256/cactoos/issues/655) assigned to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc), here is [why](https://www.0crat.com/footprint/C63314D6Z/591952785). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@flslkxtc[/z](https://www.0crat.com/u/flslkxtc) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by flslkxtc** [comment]
@0crat waiting

**Comment by flslkxtc** [comment]
@yegor256 this issue is already closed

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/655#issuecomment-370551532))

@flslkxtc You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `DEV`.

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/655#issuecomment-370551532))

@flslkxtc The impediment for [#655](https://github.com/yegor256/cactoos/issues/655) was registered successfully by @flslkxtc[/z](https://www.0crat.com/u/flslkxtc)

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/655#issuecomment-370817292))

@yegor256 @flslkxtc[/z](https://www.0crat.com/u/flslkxtc) resigned from [#655](https://github.com/yegor256/cactoos/issues/655), since the job is not in scope anymore

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/655#issuecomment-370817292))

@yegor256 The job [#655](https://github.com/yegor256/cactoos/issues/655) is now out of scope
