### ISSUE TITLE
Handle Exceptions in object oriented style

### ISSUE THREAD

**Issue by Vatavuk** [yegor256/cactoos#656]
I've created a small library that represents try/catch/finally statements in a form of reusable objects
and I thought it would be nice to include it in cactoos.

One example of using objects instead of statements could be refactoring IoCheckedScalar:
```java
public T value() throws IOException {
        try {
            return this.origin.value();
            // @checkstyle IllegalCatchCheck (1 line)
        } catch (final IOException | RuntimeException ex) {
            throw ex;
        } catch (final InterruptedException ex) {
            Thread.currentThread().interrupt();
            throw new IOException(ex);
            // @checkstyle IllegalCatchCheck (1 line)
        } catch (final Exception ex) {
            throw new IOException(ex);
        }
    }
```

To this:
```java
public T value() throws IOException {
        return
            new Try(
                new Catch(
                    InterruptedException.class,
                    exp -> Thread.currentThread().interrupt()
                )
            ).with(new Throws<>(IOException::new)
            ).exec(this.origin::value);
    }
```

There are more examples and details [here](https://github.com/Vatavuk/vgv-exceptions). (The library follows OOP style from cactoos)
If you find this usable and appropriate to be included in cactoos I can create a pull request and merge it in a new package (eg. exceptions).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by svendiedrichsen** [comment]
@Vatavuk You could extend this with classes for `if/then/else` and `for/forEach` and you almost have created a complete class based language.

**Comment by Vatavuk** [comment]
Definitely, if I'm not mistaken cactoos has equivalent for forEach statement -> And object.
I'm looking on cactoos as an OOP layer above Java, an abstraction close to EO language.
However, Try/Catch/Finally objects cannot replace every exception control scenarios due to 
language limitations. But it could be nice step towards EO style. 
I will check out transformation of if/then/else to objects (maybe it is overkill?).
I the meantime I will send pull request if you guys agree.

**Comment by svendiedrichsen** [comment]
@Vatavuk I'm sorry If i made the wrong impression but i don't run this project. I'm just some contributer. You need to talk to Yegor who owns this project.

**Comment by Vatavuk** [comment]
@yegor256 what do you think?

**Comment by yegor256** [comment]
@Vatavuk I like the idea, but I don't like the design. I think we should call it `ScalarWithFallback` (we have other similar classes already) and make it implement `Scalar`. WDYT?

**Comment by Vatavuk** [comment]
@yegor256  O I like it! I based my design on throwing specific exception but ScalarWithFallback would throw general Exception and we can use a decorator to transform it to some other exception type. In our case we can use IoCheckedScalar decorator. 

We could have ScalarWithFallback (implements Scalar) and ProcWithFallback (implements Proc).

I would remove Throws and Finally functionality completly.

The above example could then look like:
```java
 public T value() throws IOException {
    return
        new IoCheckedScalar<>(
            new ScalarWithFallback<>(
                new FallbackFrom(
                    new ListOf<>(IOException.class, RuntimeException.class),
                    exp -> { throw exp; }
                ),
                new FallbackFrom(
                    new ListOf<>(InterruptedException .class),
                    exp -> {
                        Thread.currentThread().interrupt();
                        throw new IOException(exp);
                    }
                ),
                new FallbackFrom(Exception.class,
                    exp -> { throw new IOException(exp); }
                )
            )
        ).exec(this.origin::value);
}       
```
What do you think?

**Comment by yegor256** [comment]
@Vatavuk what is `exec()`? We don't have that in `Scalar`.

**Comment by Vatavuk** [comment]
sry wrong copy-paste. It should be value

**Comment by Vatavuk** [comment]
Updated example:
```java
 public T value() throws IOException {
    return
        new IoCheckedScalar<>(
            new ScalarWithFallback<>(
               this.origin::value,
                new FallbackFrom(
                    new ListOf<>(IOException.class, RuntimeException.class),
                    exp -> { throw exp; }
                ),
                new FallbackFrom(
                    InterruptedException.class,
                    exp -> {
                        Thread.currentThread().interrupt();
                        throw new IOException(exp);
                    }
                ),
                new FallbackFrom(Exception.class,
                    exp -> { throw new IOException(exp); }
                )
            )
        ).value();
}       
```

**Comment by Vatavuk** [comment]
I can create new pull request that will contain ScalarWithFallback which will take a list of fallback options 
and choose the most suitable one depending on thrown exception. 
It will be similar to FuncWithFallback. The main difference is that it will take a list of options rather than a single fallback function.
@yegor256 Do you agree?

**Comment by yegor256** [comment]
@Vatavuk how about simple `MapEntry<Throwable, Func<Throwable, T>>` instead of `FallbackFrom` you are suggesting?

**Comment by Vatavuk** [comment]
@yegor256 I tought about using MapEntry, but I concluded that usgae of FallbackFrom (I'm not sure about the name completly) would be more readable.

The above example using MapEntry would look like:
```java
new IoCheckedScalar<>(
    new ScalarWithFallback<>(
        this.origin::value,
        new MapEntry<>(
            IOException.class,
            new FuncOf<Exception, T>(
                exp -> {
                    throw exp;
                }
            )),
        new MapEntry<>(
            RuntimeException.class,
            new FuncOf<Exception, T>(
                exp -> {
                    throw exp;
                }
            )),
        new MapEntry<>(
            InterruptedException.class,
            new FuncOf<Exception, T>(
                exp -> {
                    Thread.currentThread().interrupt();
                    throw new IOException(exp);
                }
            )),
        new MapEntry<>(
            Exception.class,
            new FuncOf<Exception, T>(
                exp -> {
                    throw new IOException(exp);
                }
            ))
    )
).value();
```
We have to specify the same fun (exp -> {throw exp}) twice, for IOException and for Runtime exception. We can move it to a variable but still...

Example with FallbackFrom using Func:
```java
new IoCheckedScalar<>(
    new ScalarWithFallback<>(
        this.origin::value,
        new FallbackFrom(
            new ListOf<>(IOException.class, RuntimeException.class),
            new FuncOf<Exception, T>(
                exp -> {
                    throw exp;
                }
            )
        ),
        new FallbackFrom(
            InterruptedException.class,
            new FuncOf<Exception, T>(
                exp -> {
                    Thread.currentThread().interrupt();
                    throw new IOException(exp);
                }
        ),
        new FallbackFrom(Exception.class,
            new FuncOf<Exception, T>(
                exp -> {
                    throw new IOException(exp);
                }
            )
        )
    )
).value();
```
However usage of MapEntry would simplify implementation of ScalarWithFallback due to more simpler structure and no additional objects to communicate with.
WDYT?

**Comment by yegor256** [comment]
@Vatavuk other `*WithFallback` classes don't have these multiple exception handlers. They just have one. We will have to modify them too?

**Comment by Vatavuk** [comment]
@yegor256 
```InputWithFallback``` -> I wouldn't modify it because it provides fallback from specific ```InputStream``` exceptions. Maybe we can modify implementation to use ScalarWithFallback instead of try/catch statements.

```FuncWithFallback ```  -> I think extending it would be a good thing. We can leave current ctors as they are and introduce new ones that take a list of fallback options.
The implementation would also use ScalarWithFallback.

**Comment by yegor256** [comment]
@Vatavuk to be honest, I'm a bit concerned about these different exception types. We will have to use `instanceof` in order to implement them, but we promise to our users that we never do that... WDYT?

**Comment by Vatavuk** [comment]
@yegor256 I'm not using instanceof, I'm calculating inheritance distance.
Take a look at this class [CompareClasses.java](https://github.com/Vatavuk/vgv-exceptions/blob/master/src/main/java/com/vgv/exceptions/CompareClasses.java)

**Comment by Vatavuk** [comment]
@yegor256 Forgot that the example is using reflection method, however I don't see other way to deal with this.

Maybe the question is what is more valuable to the users; the fact that the library is not using reflections or that they could make their exception control design more readable, maintainable and testable. I'm not pushing the solution, just thinking out loud.

**Comment by yegor256** [comment]
@Vatavuk OK, I agree, let's use `getSuperclass()` as in your `CompareClasses` example. The only question I still have -- what about `finally` block?

**Comment by Vatavuk** [comment]
@yegor256 We could create a decorator `DeterminateScalar`/`DeterminateFunc` that handles try/finally. WDYT?

What about throwing specific exceptions? If user wants to wrap Exception to CustomCheckedException. Maybe we could introduce `CheckedScalar<T, E extends Exception>`  decorator. Something like:
```java
private static final class CheckedScalar<T, E extends Exception> 
    implements Scalar<T> {
     //...fields and ctors
    @Override
    public T value() throws E {
        //...
    }
}
```
Complete try/catch/finally controll would be:
```java
new CheckedScalar<>(
    new DeterminateScalar<>(
        new ScalarWithFallback<>(
        //...
        ),
        input -> doFinally(input),
    ),
    exp -> new CustomCheckedException(exp)
)
```
I think that in the end we could clean cactoos from all try/catch statements using these objects.

**Comment by Vatavuk** [comment]
@yegor256 Or instead of using CheckedScalar maybe we could expand `ScalarWithFallback`:
```java
class ScalarWithFallback <T, E extends Exception> implements Scalar<T> {
     //...fields and ctors
    @Override
    public T value() throws E {
        //...
    }
}
```

**Comment by yegor256** [comment]
@Vatavuk I like the idea of `CheckedScalar`! We can create a separate ticket for it and implement it. It will be useful anyway, no matter what will be the decision in this ticket. Also, `CheckedInput`, `CheckedFunc`, `CheckedProc`, `CheckedBiFunc`, and `CheckedBytes`.

**Comment by yegor256** [comment]
@Vatavuk I like the concept of `DeterminateScalar`, I just don't like the name. Any other ideas?

**Comment by Vatavuk** [comment]
@yegor256 How about ``ScalarWithCleanup``?

**Comment by yegor256** [comment]
@Vatavuk not really. It's better to prepend it with an adjective

**Comment by Vatavuk** [comment]
@yegor256 
How about we implement "try with resources" functionality instead of finally:
```java
CloseableScalar<T, C extends AutoCloseable> implements Scalar<T> 
```
Usage:
```java
new CloseableScalar<>(
    () -> new BufferedReader(new FileReader("path")),
    input -> input.readLine()
).value();
```
WDYT?

**Comment by yegor256** [comment]
@Vatavuk let's solve one problem at a time) I like `FinalizedScalar`. But I don't see a lot of usability in this new class. The code we put into the "finally" scalar will not have access to the variables that exists inside the scalar, right?

**Comment by Vatavuk** [comment]
@yegor256 Exactly. We can solve this by introducing another parameter to the ctor but I think it would make the object too complex. That is why I started to think about try with resource. Maybe we can wrap up the exception handling and postpone further discussion about try with resource

**Comment by Vatavuk** [comment]
@yegor256 Just to elaborate previous post. We could expand `FinalizedScalar` ctor to provide "finally" access to specific resource:
```java
new FinalizedScalar(
    () -> new BufferedReader(new FileReader("path")),
    input -> input.readLine(),
    input -> input.close()
).value();
```
Now that I wrote it down it doesn't look that complex. I'm not sure... wdyt?

**Comment by yegor256** [comment]
@Vatavuk but only one resource in this case, right? We can't have multiple resources.

**Comment by Vatavuk** [comment]
@yegor256 Unfortunately only one resource in this case.

**Comment by Vatavuk** [comment]
@yegor256 Should I create tickets for:
`ScalarWithFallback`/`FuncWithFallback` -> can be implemented
`FinalizedScalar`  -> further discussion needed          
 ?

**Comment by yegor256** [comment]
@Vatavuk let's do `ScalarWithFallback` first and then will see

**Comment by Vatavuk** [comment]
This issue was resolved in following issues:
#735 #736 #759 #821

I give up from `FinalizedScalar` and `CloseableScalar` since the usability of this classes is questionable.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
