### ISSUE TITLE
Properties in OO style

### ISSUE THREAD

**Issue by driver733** [yegor256/cactoos#657]
The `Properties` class in JDK is very procedural. It relies on` load()` and `save()` methods which does not adhere to OO style. I suggest that we create an alternative to that class in OO way. It would be very convenient, for instance, to have the properties come preloaded without using the `load()` method.

```
// create and load default properties
Properties defaultProps = new Properties();
FileInputStream in = new FileInputStream("defaultProperties");
defaultProps.load(in);
in.close();

// create application properties with default
Properties applicationProps = new Properties(defaultProps);

// now load properties 
// from last invocation
in = new FileInputStream("appProperties");
applicationProps.load(in);
in.close();
. . .
```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by svendiedrichsen** [comment]
@driver733 Can the `PropertiesOf` class be used and adapted for this purpose?

**Comment by driver733** [comment]
@svendiedrichsen I believe so. We can use this class as a base class and build other Properties classes around it.

**Comment by yegor256** [comment]
@driver733 but we already have `PropertiesOf`, have you seen it?

**Comment by driver733** [comment]
@yegor256, Yes I have checked this file. I think that `PropertiesOf` does encapsulate properties well, however, this class does not solve the problem of procedural logic of the `Properties` class.
Even if I use the `PropertiesOf` class, I will still end up with this kind of code
```
props.load()
...
props.save()
```
Sometimes, you want to simply serve the properties to a certain class, so that it could read some information from it. (You do not want to have `props.load()` in your class that receives properties)

In other instances, you simply want the class you pass the properties to save some information in it.

That is the kind of functionality that would be useful to have.

**Comment by yegor256** [comment]
@driver733 you don't need to `load`, just use `new PropertiesOf(new InputOf(new File("a.props")))`

**Comment by driver733** [comment]
@yegor256 Thank you for clarification.
