### ISSUE TITLE
Ctor of StickyCollection is not covered

### ISSUE THREAD

**Issue by nick318** [yegor256/cactoos#664]
Ctor of StickyCollection is not covered by unit tests
   ```
 public StickyCollection(final Iterator<E> items) {
        this(new IterableOf<>(items));
    }
```
Expected:
ctor should be covered by unit test

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#664](https://github.com/yegor256/cactoos/issues/664) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @nick318[/z](https://www.0crat.com/u/nick318), total is [+135](https://www.0crat.com/u/nick318)

**Comment by 0crat** [comment]
The job [#664](https://github.com/yegor256/cactoos/issues/664) assigned to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc), here is [why](https://www.0crat.com/footprint/C63314D6Z/591959997). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by flslkxtc** [comment]
@nick318 Iterator ctors  are not working properly and will be removed, see this comment and discussion: https://github.com/yegor256/cactoos/issues/677#issuecomment-366687957.
We should close this isssue, it doesn't make sense currently.

**Comment by nick318** [comment]
@flslkxtc sure

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
> @0crat quality bad ([here](https://github.com/yegor256/cactoos/issues/664#issuecomment-369521578))

@ypshenychka The job [#664](https://github.com/yegor256/cactoos/issues/664) is now out of scope
