### ISSUE TITLE
Some constructors of AsyncFunc are not covered

### ISSUE THREAD

**Issue by nick318** [yegor256/cactoos#665]
Following constructors of AsyncFunc are not covered
```
 public AsyncFunc(final Proc<X> proc, final ThreadFactory fct) {
        this(new FuncOf<>(proc), fct);
    }
public AsyncFunc(final Proc<X> proc, final ExecutorService exec) {
        this(new FuncOf<>(proc), exec);
    }

```
Expected:
all ctors of AsyncFunc are covered by unit tests

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#665](https://github.com/yegor256/cactoos/issues/665) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @nick318[/z](https://www.0crat.com/u/nick318), total is [+90](https://www.0crat.com/u/nick318)

**Comment by 0crat** [comment]
The job [#665](https://github.com/yegor256/cactoos/issues/665) assigned to @sharpler[/z](https://www.0crat.com/u/sharpler), here is [why](https://www.0crat.com/footprint/C63314D6Z/502048039). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@sharpler[/z](https://www.0crat.com/u/sharpler) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@sharpler[/z](https://www.0crat.com/u/sharpler) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @sharpler[/z](https://www.0crat.com/u/sharpler) resigned from [#665](https://github.com/yegor256/cactoos/issues/665), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 points just awarded to @sharpler[/z](https://www.0crat.com/u/sharpler)

**Comment by 0crat** [comment]
The job [#665](https://github.com/yegor256/cactoos/issues/665) assigned to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), here is [why](https://www.0crat.com/footprint/C63314D6Z/610924621). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by SharplEr** [comment]
@yegor256 Wow, quite unfair. My PR was ready for review 5 days before 0crat had chosen reviewer on it. Should I use `wait` command to avoid such problem in future?

**Comment by proshin-roman** [comment]
@yegor256 what should we do with this task? Will it be returned to the previous developer since he already created a pull request, or should I "steal" his changes and create my own pull request (which is wrong IMO)? I would prefer the first option.

**Comment by proshin-roman** [comment]
@0crat wait for @yegor256's reaction on a problem with this ticket

**Comment by 0crat** [comment]
> @0crat wait for @yegor256's reaction on a problem with this ticket ([here](https://github.com/yegor256/cactoos/issues/665#issuecomment-370233898))

@proshin-roman Can't understand "wait", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Remove this issue from scope (WBS)
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `waiting` Register an impediment for a job

**Comment by proshin-roman** [comment]
damn :) @0crat waiting for @yegor256's reaction to a problem with this ticket.

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/cactoos/issues/665#issuecomment-370234029). You must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1).

**Comment by proshin-roman** [comment]
@0crat waiting !!!

**Comment by 0crat** [comment]
> @0crat waiting !!! ([here](https://github.com/yegor256/cactoos/issues/665#issuecomment-370234095))

@proshin-roman The impediment for [#665](https://github.com/yegor256/cactoos/issues/665) was registered successfully by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by yegor256** [comment]
@0crat assign @SharplEr

**Comment by 0crat** [comment]
> @0crat assign @SharplEr  ([here](https://github.com/yegor256/cactoos/issues/665#issuecomment-370336536))

@yegor256 The job [#665](https://github.com/yegor256/cactoos/issues/665) assigned to @sharpler[/z](https://www.0crat.com/u/sharpler), here is [why](https://www.0crat.com/footprint/C63314D6Z/640754081). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by SharplEr** [comment]
@nick318 PR #713  was merged, please close the issue.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @sharpler[/z](https://www.0crat.com/u/sharpler), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#665](https://github.com/yegor256/cactoos/issues/665) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +30 points just awarded to @sharpler[/z](https://www.0crat.com/u/sharpler)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
