### ISSUE TITLE
Ctor of CallableOf is not covered by unit test

### ISSUE THREAD

**Issue by nick318** [yegor256/cactoos#666]
Following ctor is not covered by unit test
```
public CallableOf(final Proc<X> proc) {
        this(new FuncOf<>(proc));
    }
```
Expected:
all ctors of `CallableOf ` are covered by unit tests

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#666](https://github.com/yegor256/cactoos/issues/666) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @nick318[/z](https://www.0crat.com/u/nick318), total is [+90](https://www.0crat.com/u/nick318)

**Comment by 0crat** [comment]
The job [#666](https://github.com/yegor256/cactoos/issues/666) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C63314D6Z/511157068). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by llorllale** [comment]
@nick318 hi,
This was fixed in PR #691 

Can we close this?

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by ypshenychka** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/cactoos/issues/666#issuecomment-367948480))

@ypshenychka Job `gh:yegor256/cactoos#666` is not assigned, can't get start time

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+646](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/cactoos/issues/666#issuecomment-367948480))

@ypshenychka Job `gh:yegor256/cactoos#666` is not assigned, can't get start time

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+662](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka), total is [+662](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality was "good": +35 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale), total is [+830](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/cactoos/issues/666#issuecomment-367927383))

@ypshenychka You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `QA`.

**Comment by 0crat** [comment]
The job [#666](https://github.com/yegor256/cactoos/issues/666) assigned to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), here is [why](https://www.0crat.com/footprint/C63314D6Z/591837269). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by proshin-roman** [comment]
@0crat waiting until https://github.com/zerocracy/farm/issues/557 is fixed

**Comment by 0crat** [comment]
> @0crat waiting until https://github.com/zerocracy/farm/issues/557 is fixed ([here](https://github.com/yegor256/cactoos/issues/666#issuecomment-369830583))

@proshin-roman The impediment for [#666](https://github.com/yegor256/cactoos/issues/666) was registered successfully by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by proshin-roman** [comment]
@0crat resign as the ticket is already closed (goodbye points)

**Comment by 0crat** [comment]
> @0crat resign as the ticket is already closed (goodbye points) ([here](https://github.com/yegor256/cactoos/issues/666#issuecomment-370234416))

@proshin-roman The user @proshin-roman[/z](https://www.0crat.com/u/proshin-roman) resigned from [#666](https://github.com/yegor256/cactoos/issues/666), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by 0crat** [comment]
The job [#666](https://github.com/yegor256/cactoos/issues/666) assigned to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc), here is [why](https://www.0crat.com/footprint/C63314D6Z/651531069). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by flslkxtc** [comment]
@yegor256 this issue is already closed, please remove assignment

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/666#issuecomment-371533718))

@yegor256 The user @flslkxtc[/z](https://www.0crat.com/u/flslkxtc) resigned from [#666](https://github.com/yegor256/cactoos/issues/666), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/666#issuecomment-371533731))

@yegor256 The job [#666](https://github.com/yegor256/cactoos/issues/666) is now out of scope
