### ISSUE TITLE
Ctors of RetryFunc are not covered by unit tests

### ISSUE THREAD

**Issue by nick318** [yegor256/cactoos#670]
Following ctors of `RetryFunc.java` are not covered:
```
public RetryFunc(final Proc<X> proc) {
        this(new FuncOf<>(proc));
    }
public RetryFunc(final Proc<X> proc, final int attempts) {
        this(new FuncOf<>(proc), attempts);
    }
public RetryFunc(final Proc<X> proc, final Func<Integer, Boolean> ext) {
        this(new FuncOf<>(proc), ext);
    }
```
Expected:
All ctors of `RetryFunc.java` are covered

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm/tree/1.0-SNAPSHOT) /cc @yegor256

**Comment by 0crat** [comment]
Job [#670](https://github.com/yegor256/cactoos/issues/670) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @nick318[/z](https://www.0crat.com/u/nick318), total is [+230](https://www.0crat.com/u/nick318)

**Comment by 0crat** [comment]
Job [#670](https://github.com/yegor256/cactoos/issues/670) is already in scope

**Comment by 0crat** [comment]
The job [#670](https://github.com/yegor256/cactoos/issues/670) assigned to @sharpler[/z](https://www.0crat.com/u/sharpler), here is [why](https://www.0crat.com/footprint/C63314D6Z/602053297). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by SharplEr** [comment]
@nick318 #722 PR was merged, please close the issue.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job, as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
@sharpler[/z](https://www.0crat.com/u/sharpler) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/cactoos/issues/670#issuecomment-371022133))

@elenavolokhova You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `QA`.

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/cactoos/issues/670#issuecomment-371022133))

@elenavolokhova I didn't understand what is "good"

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/cactoos/issues/670#issuecomment-371022616))

@elenavolokhova You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `QA`.

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/cactoos/issues/670#issuecomment-371022616))

@elenavolokhova I didn't understand what is "good"

**Comment by elenavolokhova** [comment]
@yegor256 0crat doesn't understand quality marks any more. Could you please pay attention to this?

**Comment by yegor256** [comment]
@elenavolokhova should be fine now, please try again

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/cactoos/issues/670#issuecomment-371412304))

@elenavolokhova Thanks, but quality review is not required in this job

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/cactoos/issues/670#issuecomment-371556742))

@elenavolokhova Thanks, but quality review is not required in this job

**Comment by elenavolokhova** [comment]
@yegor256 0crat doesn't want my review here any more. Could you please take a look at this again?

**Comment by yegor256** [comment]
@0crat out

**Comment by yegor256** [comment]
@0crat pay 8min @elenavolokhova

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @sharpler[/z](https://www.0crat.com/u/sharpler), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Direct payment from @yegor256[/z](https://www.0crat.com/u/yegor256): +8 points just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Comment by 0crat** [comment]
Direct payment to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) in #670, which is discouraged, see [§49](http://www.zerocracy.com/policy.html#49): -60 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/670#issuecomment-371750177))

@yegor256 The job [#670](https://github.com/yegor256/cactoos/issues/670) is now out of scope

**Comment by yegor256** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 points just awarded to @sharpler[/z](https://www.0crat.com/u/sharpler)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
