### ISSUE TITLE
Some ctors of RunnableOf are not covered

### ISSUE THREAD

**Issue by nick318** [yegor256/cactoos#671]
Following ctors of `RunnableOf.java` are not covered:
```
public RunnableOf(final Callable<X> proc) {
        this(new FuncOf<>(proc));
    }
public RunnableOf(final Proc<X> proc) {
        this(new FuncOf<>(proc));
    }
```
Expected:
All ctors of `RunnableOf.java` are covered by unit tests

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#671](https://github.com/yegor256/cactoos/issues/671) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @nick318[/z](https://www.0crat.com/u/nick318), total is [+150](https://www.0crat.com/u/nick318)

**Comment by 0crat** [comment]
The job [#671](https://github.com/yegor256/cactoos/issues/671) assigned to @nikialeksey[/z](https://www.0crat.com/u/nikialeksey), here is [why](https://www.0crat.com/footprint/C63314D6Z/592003092). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@nikialeksey[/z](https://www.0crat.com/u/nikialeksey) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@nikialeksey[/z](https://www.0crat.com/u/nikialeksey) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @nikialeksey[/z](https://www.0crat.com/u/nikialeksey) resigned from [#671](https://github.com/yegor256/cactoos/issues/671), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 points just awarded to @nikialeksey[/z](https://www.0crat.com/u/nikialeksey)

**Comment by 0crat** [comment]
The job [#671](https://github.com/yegor256/cactoos/issues/671) assigned to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc), here is [why](https://www.0crat.com/footprint/C63314D6Z/692010364). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by flslkxtc** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/671#issuecomment-372909723))

@flslkxtc The impediment for [#671](https://github.com/yegor256/cactoos/issues/671) was registered successfully by @flslkxtc[/z](https://www.0crat.com/u/flslkxtc)

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/671#issuecomment-372909723))

@flslkxtc Job [#671](https://github.com/yegor256/cactoos/issues/671) is already on hold

**Comment by flslkxtc** [comment]
@nick318 @yegor256  pull request https://github.com/yegor256/cactoos/pull/733 is merged, we can close this issue now.

**Comment by flslkxtc** [comment]
@nick318 @yegor256 this issue can be closed,  pull request #733 was merged

**Comment by llorllale** [comment]
@nick318 ping

**Comment by nick318** [comment]
@flslkxtc the best thing I can do is to ignore the thread and watch how the so called "30 min" issue is still not closed during 3 month. If you do not like that situation, vote up here https://github.com/zerocracy/datum/issues/326

**Comment by llorllale** [comment]
@nick318 please help us out and consider closing this issue if the PR #733 fixed it.

Disclaimer: I helped draft the text for zerocracy/datum#326.

**Comment by llorllale** [comment]
@nick318 unfortunately I am closing this ticket for you. 

Thanks for your contribution.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @flslkxtc[/z](https://www.0crat.com/u/flslkxtc), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#671](https://github.com/yegor256/cactoos/issues/671) is now out of scope

**Comment by elenavolokhova** [comment]
@flslkxtc According to our Policy:
> All impediments registered in the ticket have explanations of the reasons and links to related tickets, if necessary

This impediment has no explanation:
> @0crat waiting

Please, confirm that you'll follow this rule in future.

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/cactoos/issues/671#issuecomment-386890849); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by flslkxtc** [comment]
@elenavolokhova ok, i will specify waiting reason in my further tickets.

**Comment by elenavolokhova** [comment]
@flslkxtc Thank you!

**Comment by elenavolokhova** [comment]
@0crat quality aceptable

**Comment by 0crat** [comment]
> @0crat quality aceptable ([here](https://github.com/yegor256/cactoos/issues/671#issuecomment-387001264))

@elenavolokhova Argument "aceptable" doesn't match regex `good|bad|acceptable`

**Comment by elenavolokhova** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
