### ISSUE TITLE
A whole class SolidBiFunc is not covered by unit tests

### ISSUE THREAD

**Issue by nick318** [yegor256/cactoos#672]
A whole class `SolidBiFunc.java` is not covered by unit tests
Expected:
The class `SolidBiFunc.java` is covered

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#672](https://github.com/yegor256/cactoos/issues/672) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @nick318[/z](https://www.0crat.com/u/nick318), total is [+260](https://www.0crat.com/u/nick318)

**Comment by 0crat** [comment]
The job [#672](https://github.com/yegor256/cactoos/issues/672) assigned to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), here is [why](https://www.0crat.com/footprint/C63314D6Z/640756181). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by proshin-roman** [comment]
@neonailol I've created a pull request #727 for this ticket - please review it. Thanks.

**Comment by proshin-roman** [comment]
@nick318 This ticket has been fixed in pull request #727 that is already merged. Please close the ticket.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#672](https://github.com/yegor256/cactoos/issues/672) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +30 points just awarded to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
