### ISSUE TITLE
Remove usage of Iterator as parameter passed to ctors

### ISSUE THREAD

**Issue by svendiedrichsen** [yegor256/cactoos#677]
As outlined by @SharplEr in #659 the usage of `Iterator` as a parameter to ctors leads to side effects as for the nature of `Iterator` is stateful. So with this ticket the usage of `Iterator` as a parameter should be removed and in cases where this is not already the case replaced with usage of `Iterable`.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@svendiedrichsen I agree, let's remove all `Iterator`s from constructors, everywhere

**Comment by 0crat** [comment]
Job [#677](https://github.com/yegor256/cactoos/issues/677) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#677](https://github.com/yegor256/cactoos/issues/677) assigned to @nick318[/z](https://www.0crat.com/u/nick318), here is [why](https://www.0crat.com/footprint/C63314D6Z/501309630). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by nick318** [comment]
@yegor256 how can I handle it in 30 min window? Should I fix it one class and create a puzzle for next class?

**Comment by yegor256** [comment]
@nick318 it's up to you. You can try to fix in 30 mins or you can use PDD.

**Comment by 0crat** [comment]
@nick318[/z](https://www.0crat.com/u/nick318) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by nick318** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/677#issuecomment-368322915))

@nick318 The user @nick318[/z](https://www.0crat.com/u/nick318) resigned from [#677](https://github.com/yegor256/cactoos/issues/677), please stop working

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @nick318[/z](https://www.0crat.com/u/nick318), total is [+275](https://www.0crat.com/u/nick318)

**Comment by 0crat** [comment]
The job [#677](https://github.com/yegor256/cactoos/issues/677) assigned to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc), here is [why](https://www.0crat.com/footprint/C63314D6Z/601554547). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by flslkxtc** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/677#issuecomment-370860571))

@flslkxtc You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `DEV`.

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/677#issuecomment-370860571))

@flslkxtc The user @flslkxtc[/z](https://www.0crat.com/u/flslkxtc) resigned from [#677](https://github.com/yegor256/cactoos/issues/677), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc)

**Comment by 0crat** [comment]
The job [#677](https://github.com/yegor256/cactoos/issues/677) assigned to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), here is [why](https://www.0crat.com/footprint/C63314D6Z/671448898). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by proshin-roman** [comment]
@yegor256 please stop this farm of lost points - take the ticket out of scope.

**Comment by yegor256** [comment]
@0crat refuse

**Comment by yegor256** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/677#issuecomment-371606395))

@yegor256 The user @proshin-roman[/z](https://www.0crat.com/u/proshin-roman) resigned from [#677](https://github.com/yegor256/cactoos/issues/677), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/677#issuecomment-371606405))

@yegor256 GitHub issue is still open, won't close

**Comment by 0crat** [comment]
The job [#677](https://github.com/yegor256/cactoos/issues/677) assigned to @sharpler[/z](https://www.0crat.com/u/sharpler), here is [why](https://www.0crat.com/footprint/C63314D6Z/680849235). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by proshin-roman** [comment]
@yegor256 you have no power here xD
![image](https://user-images.githubusercontent.com/3031372/37198770-7302bd84-2390-11e8-993a-fe8c22d78f81.png)

**Comment by yegor256** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/677#issuecomment-371791558))

@yegor256 The user @sharpler[/z](https://www.0crat.com/u/sharpler) resigned from [#677](https://github.com/yegor256/cactoos/issues/677), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#677](https://github.com/yegor256/cactoos/issues/677) is now out of scope
