### ISSUE TITLE
MapNoNulls class is not fully tested

### ISSUE THREAD

**Issue by driver733** [yegor256/cactoos#679]
Currently, the `MapNoNulls` class has very low test coverage (13%).
I believe that we should write tests for it to reach 100% test coverage.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @driver733[/z](https://www.0crat.com/u/driver733), total is [+245](https://www.0crat.com/u/driver733)

**Comment by 0crat** [comment]
The job [#679](https://github.com/yegor256/cactoos/issues/679) assigned to @nick318[/z](https://www.0crat.com/u/nick318), here is [why](https://www.0crat.com/footprint/C63314D6Z/610655640). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by nick318** [comment]
@0crat waiting for PR #724 is merged

**Comment by 0crat** [comment]
> @0crat waiting for PR #724 is merged ([here](https://github.com/yegor256/cactoos/issues/679#issuecomment-370240522))

@nick318 The impediment for [#679](https://github.com/yegor256/cactoos/issues/679) was registered successfully by @nick318[/z](https://www.0crat.com/u/nick318)

**Comment by nick318** [comment]
@driver733 @yegor256 please close the issue, since PR was perged

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @nick318[/z](https://www.0crat.com/u/nick318), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#679](https://github.com/yegor256/cactoos/issues/679) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 points just awarded to @nick318[/z](https://www.0crat.com/u/nick318)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
