### ISSUE TITLE
MapEnvelope class is not fully tested

### ISSUE THREAD

**Issue by driver733** [yegor256/cactoos#681]
Currently, the `MapEnvelope` class has only half of its methods tested.
I believe that we should write tests for it to reach 100% test coverage.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#681](https://github.com/yegor256/cactoos/issues/681) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @driver733[/z](https://www.0crat.com/u/driver733), total is [+230](https://www.0crat.com/u/driver733)

**Comment by 0crat** [comment]
The job [#681](https://github.com/yegor256/cactoos/issues/681) assigned to @nick318[/z](https://www.0crat.com/u/nick318), here is [why](https://www.0crat.com/footprint/C63314D6Z/511639999). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
@nick318[/z](https://www.0crat.com/u/nick318) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by nick318** [comment]
@0crat waiting https://github.com/yegor256/cactoos/pull/717

**Comment by 0crat** [comment]
> @0crat waiting https://github.com/yegor256/cactoos/pull/717 ([here](https://github.com/yegor256/cactoos/issues/681#issuecomment-368824752))

@nick318 The impediment for [#681](https://github.com/yegor256/cactoos/issues/681) was registered successfully by @nick318[/z](https://www.0crat.com/u/nick318)

**Comment by nick318** [comment]
@driver733 close the issue please since [PR](https://github.com/yegor256/cactoos/pull/717) is merged

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job, as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/cactoos/issues/681#issuecomment-370687597))

@elenavolokhova You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `QA`.

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Comment by 0crat** [comment]
Order was finished, quality was "good": +35 points just awarded to @nick318[/z](https://www.0crat.com/u/nick318)

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/cactoos/issues/681#issuecomment-370687597))

@elenavolokhova The job [#681](https://github.com/yegor256/cactoos/issues/681) is now out of scope
