### ISSUE TITLE
OutputStreamTo class is not fully tested 

### ISSUE THREAD

**Issue by driver733** [yegor256/cactoos#682]
Currently, the `OutputStreamTo` has very low test coverage (35%).
I believe that we should write tests for it to reach 100% test coverage.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@driver733 see https://github.com/yegor256/cactoos/issues/685#issuecomment-367004244
