### ISSUE TITLE
TeeInputStream class is not fully tested

### ISSUE THREAD

**Issue by driver733** [yegor256/cactoos#685]
Currently, the `TeeInputStream ` has only half of its methods tested.
I believe that we should write tests for it to reach 100% test coverage.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@driver733 I don't think it's a good strategy to raise coverage class by class. We will fix it once, but later someone will add new ctors or methods and the coverage will go down. We should increase the threshold in `pom.xml` instead.
