### ISSUE TITLE
JavaDoc for the AndInThreads needs to be expanded

### ISSUE THREAD

**Issue by driver733** [yegor256/cactoos#692]
As per
https://github.com/yegor256/cactoos/pull/687#discussion_r169244282
https://github.com/yegor256/cactoos/pull/687#discussion_r169345396
https://github.com/yegor256/cactoos/pull/687#discussion_r169408286
https://github.com/yegor256/cactoos/pull/687#discussion_r169345396

I think that the java doc of the `AndInThreads` class needs to be updated to include information on how the class works with various inputs. For example, it would be better if it would have a number of examples with different inputs and showing what kind of results they produce. The java doc should outline the difference between the input of, for instance, integers and booleans and in which cases would it be useful to have such inputs.

**Comment by ashtonhogan** [comment]
@driver733 from what I've seen, cactoos tends to not be too verbose with javadocs, can you please update your requirement to state exactly what test cases should be added?

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/692#issuecomment-382519236))

@llorllale Job [#692](https://github.com/yegor256/cactoos/issues/692) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @driver733[/z](https://www.0crat.com/u/driver733)

**Comment by 0crat** [comment]
The job [#692](https://github.com/yegor256/cactoos/issues/692) assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/C63314D6Z/1240946893); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by Vatavuk** [comment]
@driver733 Please close this issue, it was solved in #817

**Comment by Vatavuk** [comment]
@llorllale Can you close this issue, since @driver733 is on a vacation

**Comment by Vatavuk** [comment]
@llorllale ping

**Comment by 0crat** [comment]
@vatavuk[/z](https://www.0crat.com/u/vatavuk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by llorllale** [comment]
@Vatavuk I agree, @driver733 is on vacation. Thanks

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@96383270-894f-4caa-b159-8adc6321d5ef, thread: AsyncFlush-6
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/close_job.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): CID: 1291738138, Type: 'Close job', Author: llorllale

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#692](https://github.com/yegor256/cactoos/issues/692) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
