### ISSUE TITLE
JavaDoc for org.cactoos.scalar.SumOfLongScalar should be updated

### ISSUE THREAD

**Issue by alex-semenyuk** [yegor256/cactoos#695]
JavaDoc for `org.cactoos.scalar.SumOfLongScalar` doesn't compile:

`long sum = new SumOfLongScalar(() -> 1,() -> 2, () -> 3).value();`

with error

`Error:(44, 21) java: constructor SumOfLongScalar in class org.cactoos.scalar.SumOfLongScalar cannot be applied to given types;`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by alex-semenyuk** [comment]
@yegor256 ping

**Comment by llorllale** [comment]
@yegor256 this is the kind of stuff I would fix straight into `master`, WDYT?

**Comment by llorllale** [comment]
@alex-semenyuk let's re-open this if the build breaks. 

I believe it won't, because `mvn -Pcactoos -Psonar -Pqulice --errors clean install` generates the javadocs just fine.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
