### ISSUE TITLE
org.cactoos.func.IoCheckedBiProc is not covered by unit tests

### ISSUE THREAD

**Issue by alex-semenyuk** [yegor256/cactoos#696]
org.cactoos.func.IoCheckedBiProc is not covered by unit tests
Expected:
The class org.cactoos.func.IoCheckedBiProc is covered

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@alex-semenyuk see https://github.com/yegor256/cactoos/issues/685#issuecomment-367004244
