### ISSUE TITLE
SumOf imlementation is too procedural

### ISSUE THREAD

**Issue by rexim** [yegor256/cactoos#699]
See [SumOf.java][SumOf.java]. This particular loop can be rewritten in declarative style using [Reduced.java][Reduced.java] like in [AvgOf.java][AvgOf.java].

[SumOf.java]: https://github.com/yegor256/cactoos/blob/29819e46450ca50e81bf3c07d61f460a93b84eab/src/main/java/org/cactoos/scalar/SumOf.java#L110
[AvgOf.java]: https://github.com/yegor256/cactoos/blob/29819e46450ca50e81bf3c07d61f460a93b84eab/src/main/java/org/cactoos/scalar/AvgOf.java#L143
[Reduced.java]: https://github.com/yegor256/cactoos/blob/29819e46450ca50e81bf3c07d61f460a93b84eab/src/main/java/org/cactoos/scalar/Reduced.java

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#699](https://github.com/yegor256/cactoos/issues/699) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @rexim[/z](https://www.0crat.com/u/rexim), total is [+185](https://www.0crat.com/u/rexim)

**Comment by svendiedrichsen** [comment]
@yegor256 May I contribute to this?

**Comment by yegor256** [comment]
@0crat assign @svendiedrichsen

**Comment by 0crat** [comment]
> @0crat assign @svendiedrichsen  ([here](https://github.com/yegor256/cactoos/issues/699#issuecomment-368606114))

@yegor256 The job [#699](https://github.com/yegor256/cactoos/issues/699) assigned to @svendiedrichsen[/z](https://www.0crat.com/u/svendiedrichsen), here is [why](https://www.0crat.com/footprint/C63314D6Z/571855446). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html). @svendiedrichsen[/z](https://www.0crat.com/u/svendiedrichsen) is not a member of this project yet, but they can request to join. Check your [profile](https://www.0crat.com/u/svendiedrichsen) and follow the instructions.

**Comment by svendiedrichsen** [comment]
@yegor256 How can I request to join the project?

**Comment by 0crat** [comment]
@svendiedrichsen[/z](https://www.0crat.com/u/svendiedrichsen) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by svendiedrichsen** [comment]
@yegor256 The PR is ready to merge. Please do.

**Comment by svendiedrichsen** [comment]
@rexim The PR has been merged. Do you mind closing this ticket?

**Comment by rexim** [comment]
@svendiedrichsen sure.

**Comment by 0crat** [comment]
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job, as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by ypshenychka** [comment]
@svendiedrichsen According to our [QA Rules](http://www.zerocracy.com/policy.html#42):
>Some of ticket messages must mention all pull requests where the problem was actually fixed.

Please provide a link to corresponding PR in any of your messages.

**Comment by svendiedrichsen** [comment]
@ypshenychka done.

**Comment by ypshenychka** [comment]
@svendiedrichsen Thank you!

**Comment by ypshenychka** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/cactoos/issues/699#issuecomment-370425565))

@ypshenychka You can't do that, unless you have one of these roles: `ARC`, `PO`. Your current roles are: `QA`.

**Comment by 0crat** [comment]
`QA` review completed: +8 points just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by 0crat** [comment]
Order was finished, quality was "acceptable": +30 points just awarded to @svendiedrichsen[/z](https://www.0crat.com/u/svendiedrichsen)

**Comment by 0crat** [comment]
> @0crat quality acceptable ([here](https://github.com/yegor256/cactoos/issues/699#issuecomment-370425565))

@ypshenychka The job [#699](https://github.com/yegor256/cactoos/issues/699) is now out of scope
