### ISSUE TITLE
Minimal Java version for the library 

### ISSUE THREAD

**Issue by englishman** [yegor256/cactoos#7]
What java version is the library based?
In pom.xml I see
```
<artifactId>maven-compiler-plugin</artifactId>
<configuration>
<source>1.8</source>
<target>1.8</target>
</configuration>
```
Does it mean the library isn't support java version less then 8?
If yes, why `Func` interface was introduced than reuse `java.util.function.Function`? Is it possible to use Java 8 streams in the library class implementations?

**Comment by 0crat** [comment]
@englishman I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@englishman it's 1.8. Feel free to submit a bug about `Func`

**Comment by englishman** [comment]
@yegor256 do you have appropriate GitHub label for bugs?

**Comment by yegor256** [comment]
@englishman yes, we have them. I will try to use them. Please, close this ticket if it's solved.

**Comment by yegor256** [comment]
@englishman ping

**Comment by englishman** [comment]
@yegor256 if we don't want to use standard `java.util.function.Function` instead of custom `Func` we can close this issue. WDYT?

**Comment by yegor256** [comment]
@englishman yes, let's close it
