### ISSUE TITLE
Tests don't remove temporary files (if created)

### ISSUE THREAD

**Issue by proshin-roman** [yegor256/cactoos#702]
Currently, no tests in the project care about removing temporary files. As an example, see this class: https://github.com/yegor256/cactoos/blob/c235a774cb57d253cfe59d77b45985ddf4f53fa1/src/test/java/org/cactoos/io/WriterAsOutputTest.java#L59
It means all temporary files stay forever in the OS temp directory until OS removes them itself.

How it should be done:
- tests should either call method [deleteOnExit](https://docs.oracle.com/javase/7/docs/api/java/io/File.html#deleteOnExit%28%29) for each temp file or should delete temp file manually

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@proshin-roman definitely a bug, thanks for reporting

**Comment by 0crat** [comment]
Job [#702](https://github.com/yegor256/cactoos/issues/702) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), total is [+15](https://www.0crat.com/u/proshin-roman)

**Comment by msarhan** [comment]
Using JUnit's [TemporaryFolder Rule](https://junit.org/junit4/javadoc/4.12/org/junit/rules/TemporaryFolder.html) instead of `Files.createTempFile()` will solve the issue.

**Comment by proshin-roman** [comment]
@msarhan good idea! I've already applied it in two my pull requests: [#698](https://github.com/yegor256/cactoos/pull/698) and [#676](https://github.com/yegor256/cactoos/pull/676)

**Comment by 0crat** [comment]
The job [#702](https://github.com/yegor256/cactoos/issues/702) assigned to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc), here is [why](https://www.0crat.com/footprint/C63314D6Z/651533181). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by flslkxtc** [comment]
@0crat waiting

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/702#issuecomment-372909287))

@flslkxtc The impediment for [#702](https://github.com/yegor256/cactoos/issues/702) was registered successfully by @flslkxtc[/z](https://www.0crat.com/u/flslkxtc)

**Comment by llorllale** [comment]
@0crat resign @flslkxtc

**Comment by 0crat** [comment]
> @0crat resign @flslkxtc  ([here](https://github.com/yegor256/cactoos/issues/702#issuecomment-383125076))

@llorllale The user @flslkxtc[/z](https://www.0crat.com/u/flslkxtc) resigned from [#702](https://github.com/yegor256/cactoos/issues/702), please stop working. Reason for job resignation: Order was cancelled

**Comment by llorllale** [comment]
@flslkxtc you were resigned because you're currently on vacation

**Comment by krzyk** [comment]
@proshin-roman please see PR #779

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@0crat waiting for review

**Comment by 0crat** [comment]
> @0crat waiting for review ([here](https://github.com/yegor256/cactoos/issues/702#issuecomment-384369379))

@krzyk The impediment for [#702](https://github.com/yegor256/cactoos/issues/702) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment]
@proshin-roman please close this issue, fix has been merged to master

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#702](https://github.com/yegor256/cactoos/issues/702) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
