### ISSUE TITLE
Enforce failure reasons in tests

### ISSUE THREAD

**Issue by driver733** [yegor256/cactoos#704]
I think that it would be great if we could enforce the usage of failure reasons in tests. If a test uses a test method that can have a failure reason and it does not use it,  then the build should fail.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@driver733 how is it technically possible?

**Comment by driver733** [comment]
@yegor256 We could, for instance, ban this method
`<T> void assertThat(T actual, Matcher<? super T> matcher) `
then, you would be directed to use one of these methods instead
`<T> void assertThat(java.lang.String reason, boolean assertion) `
`<T> void assertThat(java.lang.String reason, T actual, Matcher<? super T> matcher) `

**Comment by yegor256** [comment]
@driver733 "ban" how?

**Comment by driver733** [comment]
@yegor256 Could we use Checkstyle's [RegexpMultiline](http://checkstyle.sourceforge.net/config_regexp.html#RegexpSinglelineJava#RegexpMultiline)?

**Comment by yegor256** [comment]
@driver733 I doubt it will work... can you try?

**Comment by driver733** [comment]
@yegor256 Sure, I will see what I can do.

**Comment by driver733** [comment]
@yegor256 Actually, we could use this
```
<module name="com.github.sevntu.checkstyle.checks.coding.ForbidCertainMethodCheck">
      <property name="methodName" value="assert(True|False)"/>
      <property name="argumentCount" value="1"/>
    </module>
```

**Comment by yegor256** [comment]
@driver733 yes, that will work, thanks

**Comment by 0crat** [comment]
Job [#704](https://github.com/yegor256/cactoos/issues/704) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://datum.zerocracy.com/pages/policy.html#29): +15 points just awarded to @driver733[/z](https://www.0crat.com/u/driver733), total is [+335](https://www.0crat.com/u/driver733)

**Comment by 0crat** [comment]
The job [#704](https://github.com/yegor256/cactoos/issues/704) assigned to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc), here is [why](https://www.0crat.com/footprint/C63314D6Z/651731396). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by flslkxtc** [comment]
@driver733 @yegor256 Cactoos project uses Qulice checkstyle rules, i think it more of a Qulice project issue than cactoos.

**Comment by 0crat** [comment]
@flslkxtc[/z](https://www.0crat.com/u/flslkxtc) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @flslkxtc[/z](https://www.0crat.com/u/flslkxtc) resigned from [#704](https://github.com/yegor256/cactoos/issues/704), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 points just awarded to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc)

**Comment by 0crat** [comment]
The job [#704](https://github.com/yegor256/cactoos/issues/704) assigned to @neonailol[/z](https://www.0crat.com/u/neonailol), here is [why](https://www.0crat.com/footprint/C63314D6Z/771337724). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by neonailol** [comment]
@0crat waiting

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
com.zerocracy.radars.github.ReSafe[76] java.io.IOException: com.amazonaws.SdkClientException: Unable to execute HTTP request: null
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
> @0crat waiting ([here](https://github.com/yegor256/cactoos/issues/704#issuecomment-376400892))

@neonailol The impediment for [#704](https://github.com/yegor256/cactoos/issues/704) was registered successfully by @neonailol[/z](https://www.0crat.com/u/neonailol)

**Comment by llorllale** [comment]
@neonailol ping

**Comment by neonailol** [comment]
@llorllale i have no idea what happened with this pr

**Comment by llorllale** [comment]
@neonailol are you still interested in completing this task?

**Comment by llorllale** [comment]
@neonailol please move forward with this task

**Comment by neonailol** [comment]
@llorllale submitted #899

**Comment by llorllale** [comment]
@driver733 this was implemented in PR #899

**Comment by 0crat** [comment]
Job [#704](https://github.com/yegor256/cactoos/issues/704) is not in the agenda of @neonailol[/z](https://www.0crat.com/u/neonailol), can't retrieve data and time of add

**Comment by 0crat** [comment]
The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
The job [#704](https://github.com/yegor256/cactoos/issues/704) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol)
