### ISSUE TITLE
How do you instantiate JoinedText with generated Text instances?

### ISSUE THREAD

**Issue by ashtonhogan** [yegor256/cactoos#705]
Which object can take a new `TextOf("...")` function and an `Integer` count and repeat execution of the function as per the count and then place all instances inside an instance of `JoinedText`?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by svendiedrichsen** [comment]
@ashtonhogan You could use `new JoinedText(new Repeated(5, new TextOf("text")));` to get the text repeated 5 times joined together into one string.

**Comment by ashtonhogan** [comment]
@svendiedrichsen failed at first, worked after adding the delimiter

`new JoinedText(new TextOf(""), new Repeated(5, new TextOf("text")));`
