### ISSUE TITLE
How do you instantiate Base64Text with a byte array?

### ISSUE THREAD

**Issue by ashtonhogan** [yegor256/cactoos#707]
It appears that there is only a `String` constructor and a `Text` constructor. How can I compose an object that can accept `byte[]` as input and provide `Base64Text` as output?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by svendiedrichsen** [comment]
@ashtonhogan You could do `new Base64Text(new TextOf(new byte[]{}));`.

**Comment by yegor256** [comment]
@ashtonhogan yes, @svendiedrichsen is right

**Comment by ashtonhogan** [comment]
Thank you @svendiedrichsen @yegor256
