### ISSUE TITLE
How do you check if an iterator contains all the elements of another iterator?

### ISSUE THREAD

**Issue by ashtonhogan** [yegor256/cactoos#708]
Which object can take two `Iterator` instances and return a `Boolean` `TRUE` when all the elements in one `Iterator` are found in the other?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by svendiedrichsen** [comment]
@ashtonhogan You should not rely on Iterators. #677  aims to remove usage as parameters passed to instances via ctors.

If you are using `Iterable`s you can do `new ListOf(iterable1).containsAll(new ListOf(iterable2));`

**Comment by ashtonhogan** [comment]
@yegor256 Can you let me add labels to these questions?
