### ISSUE TITLE
NormalizedText.asString() is too procedural.

### ISSUE THREAD

**Issue by aliceice** [yegor256/cactoos#711]
The method `asString()` of `NormalizedText` currently looks like this:

```
@Override
public String asString() throws Exception {
    return new TrimmedText(this.origin).asString().replaceAll("\\s+", " ");
}
```

Instead of calling `.replaceAll(...)` it should use `ReplacedText` to build a bigger object and make it more declarative.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by svendiedrichsen** [comment]
@yegor256 May I contribute to this?

**Comment by memoyil** [comment]
@aliceice you can check the pr.

**Comment by memoyil** [comment]
@0crat assign

**Comment by 0crat** [comment]
You need to ask somebody to invite you: https://github.com/zerocracy/datum#invite-only

**Comment by llorllale** [comment]
@aliceice #743 was merged, can we close this?

**Comment by llorllale** [comment]
@aliceice can we close this issue?

**Comment by llorllale** [comment]
@aliceice I'm closing this

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
