### ISSUE TITLE
Commercial license

### ISSUE THREAD

**Issue by ashtonhogan** [yegor256/cactoos#718]
Is there or will there ever be a commercial license available?

I understand MIT is the most permissive but with commercial, the transaction is more transparent and everyone knows what their "fair share" is upfront...

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ashtonhogan it's a free product, you can use it any way you want. No need to have any other licenses.
