### ISSUE TITLE
TeeInput.java:48-50: This class needs more test cases....

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#720]
The puzzle `631-6c33e53a` from #631 has to be resolved:

https://github.com/yegor256/cactoos/blob/2bcee98bf2583b5123670f66ad65e72ae3e30cd1/src/main/java/org/cactoos/io/TeeInput.java#L48-L50

The puzzle was created by Roman Proshin on 26-Feb-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#720](https://github.com/yegor256/cactoos/issues/720) is now in scope, role is `DEV`

**Comment by proshin-roman** [comment]
I've already implemented all required test cases but had to delete them. You can find it [here](https://gist.github.com/proshin-roman/876f0b4dcd31954e42fb26e5147ecd04) (if you need, of course).

**Comment by 0crat** [comment]
The job [#720](https://github.com/yegor256/cactoos/issues/720) assigned to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), here is [why](https://www.0crat.com/footprint/C63314D6Z/671450972). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by proshin-roman** [comment]
@neonailol I've created a pull request #732 for this ticket - please review it.

**Comment by proshin-roman** [comment]
@neonailol ping

**Comment by proshin-roman** [comment]
@0crat wait until pull request #731 is merged

**Comment by 0crat** [comment]
> @0crat wait until pull request #731 is merged ([here](https://github.com/yegor256/cactoos/issues/720#issuecomment-373036086))

@proshin-roman The impediment for [#720](https://github.com/yegor256/cactoos/issues/720) was registered successfully by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by 0pdd** [comment]
The puzzle `631-6c33e53a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#720](https://github.com/yegor256/cactoos/issues/720) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#794](https://github.com/yegor256/cactoos/issues/794) is still not solved.

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#794](https://github.com/yegor256/cactoos/issues/794) is solved here.
