### ISSUE TITLE
TeeInputFromBytesTest.java:41-43: Create a new Matcher...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#721]
The puzzle `631-845093d4` from #631 has to be resolved:

https://github.com/yegor256/cactoos/blob/2bcee98bf2583b5123670f66ad65e72ae3e30cd1/src/test/java/org/cactoos/io/TeeInputFromBytesTest.java#L41-L43

The puzzle was created by Roman Proshin on 26-Feb-18. 

Estimate: 30 minutes, role: DEV.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#721](https://github.com/yegor256/cactoos/issues/721) is now in scope, role is `DEV`

**Comment by proshin-roman** [comment]
I've already implemented this matcher but had to delete that. I've published my work [here](https://gist.github.com/proshin-roman/67c90dfc03038d1245796f338b289e7a) so you - whoever will fix this bug - can use it (if it's still acceptable).

**Comment by 0crat** [comment]
The job [#721](https://github.com/yegor256/cactoos/issues/721) assigned to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), here is [why](https://www.0crat.com/footprint/C63314D6Z/671454040). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by proshin-roman** [comment]
@neonailol I've created a pull request #731 for this ticket - please review it.

**Comment by proshin-roman** [comment]
@neonailol ping

**Comment by 0crat** [comment]
@proshin-roman[/z](https://www.0crat.com/u/proshin-roman) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @proshin-roman[/z](https://www.0crat.com/u/proshin-roman) resigned from [#721](https://github.com/yegor256/cactoos/issues/721), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 points just awarded to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by 0crat** [comment]
The job [#721](https://github.com/yegor256/cactoos/issues/721) assigned to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc), here is [why](https://www.0crat.com/footprint/C63314D6Z/771481428). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0pdd** [comment]
The puzzle `631-845093d4` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @flslkxtc[/z](https://www.0crat.com/u/flslkxtc), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#721](https://github.com/yegor256/cactoos/issues/721) is now out of scope

**Comment by proshin-roman** [comment]
@yegor256 the issue was fixed by my pull request #731 but the tissue itself was already assigned to another developer. Can it be assigned back to me now (as an author of the fix)? Or what's the correct solution according to [Policy](http://www.zerocracy.com/policy.html)?

**Comment by yegor256** [comment]
@proshin-roman according to the policy, you lost this job two days ago, because of delay. Also, the quality here will be bad, since the new assignee didn't do the job -- QA will spot this.

**Comment by elenavolokhova** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
Quality review completed: +8 points just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
