### ISSUE TITLE
Bytes from hex missed

### ISSUE THREAD

**Issue by g4s8** [yegor256/cactoos#726]
There is `HexOf(Bytes bytes)` text implementation to represent bytes as a hex string but no `Bytes` implementation for parsing hex string.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#726](https://github.com/yegor256/cactoos/issues/726) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
The job [#726](https://github.com/yegor256/cactoos/issues/726) assigned to @sharpler[/z](https://www.0crat.com/u/sharpler), here is [why](https://www.0crat.com/footprint/C63314D6Z/671545137). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
> @0crat waiting Waiting for any reviewer reaction (except `refusing` of course). ([here](https://github.com/yegor256/cactoos/issues/726#issuecomment-372350059))

@SharplEr The impediment for [#726](https://github.com/yegor256/cactoos/issues/726) was registered successfully by @sharpler[/z](https://www.0crat.com/u/sharpler)

**Comment by SharplEr** [comment]
@g4s8 PR #750 was merged. Please close the issue.

**Comment by g4s8** [comment]
@SharplEr thanks

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @sharpler[/z](https://www.0crat.com/u/sharpler), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#726](https://github.com/yegor256/cactoos/issues/726) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @sharpler[/z](https://www.0crat.com/u/sharpler)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
