### ISSUE TITLE
More ctors for Or

### ISSUE THREAD

**Issue by llorllale** [yegor256/cactoos#737]
Let's add this constructor to `Or`:

```java
public <X> Or(final X subject, final Func<X, Boolean>... conditions)
```

This would allow us to reduce noise in code and also produces more readable code (to me anyways).

**Without ctor**:
```java
private boolean check(String text) {
    final Text sts = new TrimmedText(new LowerText(new TextOf(text)));
    return new Or(
        () -> "blah".equals(sts.asString()),
        () -> sts.asString().startsWith("test"),
        () -> sts.asString().endsWith("code")
    ).value();
}
```

**With ctor**:
```java
private boolean check(String text) {
    return new Or(
        new TrimmedText(new LowerText(new TextOf(text))),
        txt -> "blah".equals(txt.asString()),
        txt -> txt.asString().startsWith("test"),
        txt -> txt.asString().endsWith("code")
    ).value();
}

```

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#737](https://github.com/yegor256/cactoos/issues/737) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 points just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#737](https://github.com/yegor256/cactoos/issues/737) assigned to @nikialeksey[/z](https://www.0crat.com/u/nikialeksey), here is [why](https://www.0crat.com/footprint/C63314D6Z/712122797). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by 0crat** [comment]
The job [#737](https://github.com/yegor256/cactoos/issues/737) assigned to @nick318[/z](https://www.0crat.com/u/nick318), here is [why](https://www.0crat.com/footprint/C63314D6Z/750820685). The budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4). Please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by memoyil** [comment]
@llorllale @yegor256 you can check the pr.

**Comment by 0crat** [comment]
@nick318[/z](https://www.0crat.com/u/nick318) this job was assigned to you 5 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by nick318** [comment]
@0crat refuse

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 points just awarded to @nick318[/z](https://www.0crat.com/u/nick318)

**Comment by 0crat** [comment]
The job [#737](https://github.com/yegor256/cactoos/issues/737) assigned to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc), here is [why](https://www.0crat.com/footprint/C63314D6Z/801522388); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@flslkxtc[/z](https://www.0crat.com/u/flslkxtc) this job was assigned to you 8 days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@flslkxtc[/z](https://www.0crat.com/u/flslkxtc) this job was assigned to you 9days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
@flslkxtc[/z](https://www.0crat.com/u/flslkxtc) this job was assigned to you 9days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @flslkxtc[/z](https://www.0crat.com/u/flslkxtc) resigned from [#737](https://github.com/yegor256/cactoos/issues/737), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment]
The job [#737](https://github.com/yegor256/cactoos/issues/737) assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/C63314D6Z/901550210); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by Vatavuk** [comment]
@yegor256 Could you please assign @memoyil to this job. His PR #742 is reviewed and ready to be merged.

**Comment by yegor256** [comment]
@0crat assign @memoyil

**Comment by 0crat** [comment]
> @0crat assign @memoyil  ([here](https://github.com/yegor256/cactoos/issues/737#issuecomment-378949598))

@yegor256 The job [#737](https://github.com/yegor256/cactoos/issues/737) assigned to @memoyil[/z](https://www.0crat.com/u/memoyil), here is [why](https://www.0crat.com/footprint/C63314D6Z/951417155); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) @memoyil[/z](https://www.0crat.com/u/memoyil) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by memoyil** [comment]
@yegor256 Could you please invite me to 0crat?

**Comment by yegor256** [comment]
@memoyil just fill this form and someone will help you: https://www.0crat.com/join

**Comment by 0crat** [comment]
@memoyil[/z](https://www.0crat.com/u/memoyil) this job was assigned to you 7days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by memoyil** [comment]
@0crat apply

**Comment by 0crat** [comment]
> @0crat apply ([here](https://github.com/yegor256/cactoos/issues/737#issuecomment-380820898))

@memoyil Can't understand "apply", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by memoyil** [comment]
@yegor256 You can close this issue.

**Comment by yegor256** [comment]
@memoyil why me?

**Comment by memoyil** [comment]
@yegor256 sorry :) 

@llorllale you can close this issue.

**Comment by llorllale** [comment]
@memoyil where's the PR?

**Comment by memoyil** [comment]
@llorllale https://github.com/yegor256/cactoos/pull/742

**Comment by llorllale** [comment]
@memoyil thanks!

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @memoyil[/z](https://www.0crat.com/u/memoyil), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#737](https://github.com/yegor256/cactoos/issues/737) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @memoyil[/z](https://www.0crat.com/u/memoyil)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
