### ISSUE TITLE
RangeOf is not final

### ISSUE THREAD

**Issue by VsSekorin** [yegor256/cactoos#746]
`org.cactoos.iterable.RangeOf` is not final. If I'm not mistaken, all classes should be final or abstract, except decarating envelopes. But because of Decorating Envelopes, `mvn clean install -Pqulice` is unable to warn this (no methods - no warning).

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@VsSekorin fixed in 7177dd4 thanks!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
