### ISSUE TITLE
Align And and Or ctors

### ISSUE THREAD

**Issue by Vatavuk** [yegor256/cactoos#754]
`And` is missing some ctors that `Or` has. 
I think those classes should reflect their ctors because they are practically the same just inverted.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/754#issuecomment-382105593))

@llorllale Job [#754](https://github.com/yegor256/cactoos/issues/754) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0crat** [comment]
The job [#754](https://github.com/yegor256/cactoos/issues/754) assigned to @pbenety[/z](https://www.0crat.com/u/pbenety), here is [why](https://www.0crat.com/footprint/C63314D6Z/1222155518); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@pbenety[/z](https://www.0crat.com/u/pbenety) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by pbenety** [comment]
@0crat waiting review #851

**Comment by 0crat** [comment]
> @0crat waiting review #851  ([here](https://github.com/yegor256/cactoos/issues/754#issuecomment-387914953))

@pbenety The impediment for [#754](https://github.com/yegor256/cactoos/issues/754) was registered successfully by @pbenety[/z](https://www.0crat.com/u/pbenety)

**Comment by pbenety** [comment]
@Vatavuk please close this issue. The PR #851 was merged.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @pbenety[/z](https://www.0crat.com/u/pbenety), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#754](https://github.com/yegor256/cactoos/issues/754) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
