### ISSUE TITLE
ScalarWithFallback

### ISSUE THREAD

**Issue by Vatavuk** [yegor256/cactoos#759]
Let's create `ScalarWithFallback` which will be similar to `FuncWithFallback ` but will support fallback from
multiple types of exceptions.

EDIT: see comments below

More information can be found in this [discussion](https://github.com/yegor256/cactoos/issues/656#issuecomment-366724517).

@yegor256 I would like to create PR for this issue if possible.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@Vatavuk let's do a single Exception type first.

**Comment by 0crat** [comment]
Job [#759](https://github.com/yegor256/cactoos/issues/759) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by Vatavuk** [comment]
@yegor256 I agree. 
Just a note to whoever gets this job to think of refactoring `FuncWithFallback` to use newly created `ScalarWithFallback` in the same PR.

**Comment by 0crat** [comment]
The job [#759](https://github.com/yegor256/cactoos/issues/759) assigned to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), here is [why](https://www.0crat.com/footprint/C63314D6Z/1131955444); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by proshin-roman** [comment]
@0crat wait until pull request #800 is reviewed

**Comment by 0crat** [comment]
> @0crat wait until pull request #800 is reviewed ([here](https://github.com/yegor256/cactoos/issues/759#issuecomment-385624910))

@proshin-roman The impediment for [#759](https://github.com/yegor256/cactoos/issues/759) was registered successfully by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by Vatavuk** [comment]
@proshin-roman Great PR #800, thanks!

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#759](https://github.com/yegor256/cactoos/issues/759) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Comment by 0pdd** [comment]
@Vatavuk the only puzzle [#821](https://github.com/yegor256/cactoos/issues/821) is solved here.
