### ISSUE TITLE
TimedFunc

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#761]
We need a `TimedFunc` decorator for `Func` that gets interrupted after a certain time has passed.

Maybe something similar to `AsyncFunc`, I'm not sure.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#761](https://github.com/yegor256/cactoos/issues/761) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
The job [#761](https://github.com/yegor256/cactoos/issues/761) assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/C63314D6Z/980509275); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@vatavuk[/z](https://www.0crat.com/u/vatavuk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by Vatavuk** [comment]
@0crat wait for review #762

**Comment by 0crat** [comment]
> @0crat wait for review #762  ([here](https://github.com/yegor256/cactoos/issues/761#issuecomment-381044305))

@Vatavuk The impediment for [#761](https://github.com/yegor256/cactoos/issues/761) was registered successfully by @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by Vatavuk** [comment]
@victornoel please close this issue. It was solved in #762

**Comment by victornoel** [comment]
@Vatavuk thanks

**Comment by victornoel** [comment]
@llorllale could we get a new release of cactoos? I need this for yegor256/cactoos-http#10

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#761](https://github.com/yegor256/cactoos/issues/761) is now out of scope

**Comment by llorllale** [comment]
@victornoel `0.30` has been [released](https://github.com/yegor256/cactoos/issues/782)

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
