### ISSUE TITLE
HeadInput

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#764]
Let's create `HeadInput` class which will behave like an `Input`, but only showing the first N bytes of the stream:

```java
new HeadInput(new InputOf(new File("very-log-file.bin")));
```

**Comment by 0crat** [comment]
Job [#764](https://github.com/yegor256/cactoos/issues/764) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
The job [#764](https://github.com/yegor256/cactoos/issues/764) assigned to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc), here is [why](https://www.0crat.com/footprint/C63314D6Z/1041260450); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by flslkxtc** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/764#issuecomment-383328303))

@flslkxtc The user @flslkxtc[/z](https://www.0crat.com/u/flslkxtc) resigned from [#764](https://github.com/yegor256/cactoos/issues/764), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @flslkxtc[/z](https://www.0crat.com/u/flslkxtc)

**Comment by 0crat** [comment]
@proshin-roman[/z](https://www.0crat.com/u/proshin-roman) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by proshin-roman** [comment]
@memoyil why didn't you submit a pull request with your changes? It seems I've already implemented this ticket in your branch, isn't it?

**Comment by memoyil** [comment]
@proshin-roman I will create a new pull request after refactoring my code.

**Comment by proshin-roman** [comment]
@memoyil The thing is that the ticket is assigned to me, so I have to submit some fix for it. I don't want to steal your work, but I have to implement something similar. The questions are why didn't you assign the ticket to yourself, and why did you start working on a ticket that is not assigned to you?

**Comment by proshin-roman** [comment]
@memoyil ok, I'm going to submit some minimal solution that will fit the requirements of the ticket, but you still can submit your constructors and tests later. I think it should be ok.

**Comment by proshin-roman** [comment]
@0crat wait until pull request #801 is reviewed

**Comment by 0crat** [comment]
> @0crat wait until pull request #801 is reviewed ([here](https://github.com/yegor256/cactoos/issues/764#issuecomment-385647984))

@proshin-roman The impediment for [#764](https://github.com/yegor256/cactoos/issues/764) was registered successfully by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by proshin-roman** [comment]
@yegor256 The feature has been implemented in #801 that is already merged into the master branch. Please, check if the ticket can be closed.

**Comment by yegor256** [comment]
@proshin-roman thanks!

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#764](https://github.com/yegor256/cactoos/issues/764) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
