### ISSUE TITLE
TailInput

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#765]
Let's create `TailInput` class which will behave like an `Input`, but only showing the last N bytes of the stream:

```java
new TailInput(new InputOf(new File("very-log-file.bin")));
```

**Comment by 0crat** [comment]
Job [#765](https://github.com/yegor256/cactoos/issues/765) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by memoyil** [comment]
@yegor256 I think it is very inefficent to read all of the data first and show the last N bytes of them. WDYT?

**Comment by yegor256** [comment]
@memoyil we can use `skip()`

**Comment by memoyil** [comment]
In order to do that we need to know the size of the content. But available method says that "Note that while some implementations of {@code InputStream} will return the total number of bytes in the stream, many will not. "

**Comment by 0crat** [comment]
The job [#765](https://github.com/yegor256/cactoos/issues/765) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/1041815169); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by victornoel** [comment]
Reminder for myself: As a starter let's make a `TailInput` that takes a number of bytes to skip.

**Comment by 0crat** [comment]
@victornoel[/z](https://www.0crat.com/u/victornoel) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by victornoel** [comment]
@0crat refuse, already spent too much time thinking about this

**Comment by 0crat** [comment]
> @0crat refuse, already spent too much time thinking about this ([here](https://github.com/yegor256/cactoos/issues/765#issuecomment-383118283))

@victornoel Can't understand "refuse,", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/765#issuecomment-383121383))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#765](https://github.com/yegor256/cactoos/issues/765), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/765#issuecomment-383121400))

@victornoel Job `gh:yegor256/cactoos#765` is not assigned, can't get performer

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
The job [#765](https://github.com/yegor256/cactoos/issues/765) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C63314D6Z/1131556115); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by krzyk** [comment]
@yegor256 Changes were merged into master in #784, please close this issue

**Comment by krzyk** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@krzyk thanks!

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#765](https://github.com/yegor256/cactoos/issues/765) is now out of scope

**Comment by elenavolokhova** [comment]
@memoyil According to our Policy:
> Messages in a job always start with a name of a user they are addressed to;

This comment is not addressed to anyone:
> In order to do that we need to know the size of the content. But available method says that "Note that while some implementations of {@code InputStream} will return the total number of bytes in the stream, many will not. "

Please, confirm that you'll address all comments in future.

**Comment by elenavolokhova** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
