### ISSUE TITLE
IoCheckedScalar duplicates functionality from CheckedScalar

### ISSUE THREAD

**Issue by Vatavuk** [yegor256/cactoos#766]
`IoCheckedScalar` should use `CheckedScalar` instead of try/catch statements 
to avoid code duplication.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@9c0ff7e3-e0b9-4bc8-930d-80f60a6be371, thread: BkParallel-8
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
The job [#766](https://github.com/yegor256/cactoos/issues/766) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C63314D6Z/1241411709); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by paulodamaso** [comment]
@Vatavuk  please close this issue. The PR #819 was merged.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@cd641315-a9a0-4de4-9ea0-5692ea93df59, thread: BkParallel-3
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: yegor256/cactoos#766, Action: closed

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@cd641315-a9a0-4de4-9ea0-5692ea93df59, thread: BkParallel-6
com.zerocracy.pm.Claims[112] java.lang.IllegalStateException: Duplicate claims are not allowed in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), can't add this XML to 2 existing ones:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1251858967">
   <created>2018-05-05T18:44:36.758Z</created>
   <type>Close job</type>
   <token>github;yegor256/cactoos;766</token>
   <author>vatavuk</author>
   <params>
      <param name="job">gh:yegor256/cactoos#766</param>
      <param name="reason">GitHub issue was closed</param>
   </params>
   <until>2018-05-05T18:59:36.759Z</until>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: yegor256/cactoos#766, Action: closed

**Comment by Vatavuk** [comment]
@llorllale Can you please help here. When I closed this issue 0crat failed to submit action. 
Then I closed and reopened again but it failed again...

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#766](https://github.com/yegor256/cactoos/issues/766) is now out of scope

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@cd641315-a9a0-4de4-9ea0-5692ea93df59, thread: BkParallel-7
com.zerocracy.pm.Claims[112] java.lang.IllegalStateException: Duplicate claims are not allowed in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), can't add this XML to 2 existing ones:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1251961751">
   <created>2018-05-05T19:45:19.659Z</created>
   <type>Close job</type>
   <token>github;yegor256/cactoos;766</token>
   <author>vatavuk</author>
   <params>
      <param name="job">gh:yegor256/cactoos#766</param>
      <param name="reason">GitHub issue was closed</param>
   </params>
   <until>2018-05-05T20:00:19.66Z</until>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: yegor256/cactoos#766, Action: closed

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by llorllale** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/766#issuecomment-386832574))

@llorllale This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#766](https://github.com/yegor256/cactoos/issues/766) is not in scope
  * The job is waiting quality review verdict by @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) for 1hr
  * @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) will receive 30 minutes after quality review
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%23766%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@cd641315-a9a0-4de4-9ea0-5692ea93df59, thread: BkParallel-9
com.amazonaws.http.AmazonHttpClient$RequestExecutor[1113] com.amazonaws.SdkClientException: Unable to execute HTTP request: null
sun.nio.ch.FileChannelImpl[110] java.nio.channels.ClosedChannelException: null
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: yegor256/cactoos#766, Action: closed

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
