### ISSUE TITLE
introduce class for Locale.getDefault

### ISSUE THREAD

**Issue by ashtonhogan** [yegor256/cactoos#768]
This issue is a child of https://github.com/yegor256/cactoos/issues/62 and should address calls like those seen [here](https://github.com/yegor256/cactoos/blob/b4223ce3e096424397e33058568b587844d93b24/src/main/java/org/cactoos/text/FormattedText.java#L117) with a non-static alternative

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ashtonhogan[/z](https://www.0crat.com/u/ashtonhogan) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@ashtonhogan how do you propose we fix this?

**Comment by llorllale** [comment]
@ashtonhogan ping

How should we fix this? `Locale` is a final class.

**Comment by ashtonhogan** [comment]
@llorllale Someone has to introduce a new class

**Comment by llorllale** [comment]
@ashtonhogan do you have any idea on how that would look like?

**Comment by ashtonhogan** [comment]
@llorllale Not right now

**Comment by llorllale** [comment]
@ashtonhogan I'm closing this because I don't see how we can avoid the call to `Locale.getDefault`.

Thanks for your contribution.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ab56d234-9c5a-4a94-9bc9-5e54c14be93d, thread: BkParallel-9
com.mongodb.MongoCollectionImpl[558] com.mongodb.MongoWriteException: quota exceeded
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ab56d234-9c5a-4a94-9bc9-5e54c14be93d, thread: BkParallel-7
com.mongodb.MongoCollectionImpl[558] com.mongodb.MongoWriteException: quota exceeded
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
