### ISSUE TITLE
update 61 usages of Collections...

### ISSUE THREAD

**Issue by ashtonhogan** [yegor256/cactoos#770]
This issue is a child of https://github.com/yegor256/cactoos/issues/62 and should address calls like those seen [here](https://github.com/yegor256/cactoos/blob/b4223ce3e096424397e33058568b587844d93b24/src/main/java/org/cactoos/collection/StickyCollection.java#L81) with a non-static alternative

This issue itself is a parent issue, these `61` calls need to be broken down further into more separate issues/PR's.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by yegor256** [comment]
@ashtonhogan we don't want to re-implement `Collections.unmodifiableCollection`, since it's pointless, JDK works file and we are using all that only internally. Any other cases?

**Comment by llorllale** [comment]
@ashtonhogan tip: we use [Puzzle Driven Development](http://www.yegor256.com/2010/03/04/pdd.html) and hence there's no need to create "parent/child issues". You just provide work for the allotted time (30mins) and leave a puzzle for the rest.

**Comment by llorllale** [comment]
@ashtonhogan if you look closely, `CollectionEnvelope` already enforces the contract for `Collections.unmodifiable`.

I do think there are other calls being made to `Collections` that can definitely be substituted for our own types.

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/770#issuecomment-382513133))

@llorllale Job [#770](https://github.com/yegor256/cactoos/issues/770) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ashtonhogan[/z](https://www.0crat.com/u/ashtonhogan)

**Comment by llorllale** [comment]
@ashtonhogan these are just a few examples of the ones I saw that can definitely be substituted, there are probably more:

* `Collections.emptyList`
* `Collections.emptyIterator`
* `Collections.singleton`
* `Collections.singletonList`
* `Collections.synchronized*`
* `Collections.reverse`

**Comment by 0crat** [comment]
The job [#770](https://github.com/yegor256/cactoos/issues/770) assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/C63314D6Z/1231959717); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by ashtonhogan** [comment]
> @ashtonhogan we don't want to re-implement Collections.unmodifiableCollection, since it's pointless, JDK works file and we are using all that only internally. Any other cases?

Okay

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#770](https://github.com/yegor256/cactoos/issues/770) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality bad

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@dda423bf-f743-481b-8efe-d9b489cae20a, thread: BkParallel-5
com.zerocracy.pm.Claims[112] java.lang.IllegalStateException: Duplicate claims are not allowed in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), can't add this XML to 12 existing ones:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1241026091">
   <created>2018-05-04T10:26:08.683Z</created>
   <type>Complete `QA` review</type>
   <params>
      <param name="quality">bad</param>
      <param name="job">gh:yegor256/cactoos#770</param>
      <param name="repo">yegor256/cactoos</param>
      <param name="issue">770</param>
      <param name="comment">386561333</param>
   </params>
   <token>github;yegor256/cactoos;770;386561333</token>
   <author>elenavolokhova</author>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment]
> @0crat quality bad ([here](https://github.com/yegor256/cactoos/issues/770#issuecomment-386561333))

@elenavolokhova Thanks, but quality review is not required in this job

**Comment by elenavolokhova** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/770#issuecomment-387041216))

@elenavolokhova This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#770](https://github.com/yegor256/cactoos/issues/770) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%23770%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)
