### ISSUE TITLE
Update Array.asList in IterableOf

### ISSUE THREAD

**Issue by ashtonhogan** [yegor256/cactoos#773]
Child of https://github.com/yegor256/cactoos/issues/769

This [line](https://github.com/yegor256/cactoos/blob/b4223ce3e096424397e33058568b587844d93b24/src/main/java/org/cactoos/iterable/IterableOf.java#L50) has to be replaced with `new ListOf<>()`. When you do so, you'll get a StackOverflow exception, indicating there's a design flaw somewhere.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@ashtonhogan[/z](https://www.0crat.com/u/ashtonhogan) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/773#issuecomment-382506857))

@llorllale Job [#773](https://github.com/yegor256/cactoos/issues/773) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @ashtonhogan[/z](https://www.0crat.com/u/ashtonhogan)

**Comment by Zefick** [comment]
What about `new IteratorOf<>(items)`?

**Comment by llorllale** [comment]
@ashtonhogan fixed in #783 

Thank you @Zefick !

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@ashtonhogan[/z](https://www.0crat.com/u/ashtonhogan) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@ashtonhogan can we close this? Fix was merged in #783

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@346df6c8-40cd-4f70-ba65-5999eead80a1, thread: BkParallel-6
com.zerocracy.pm.Claims[112] java.lang.IllegalStateException: Duplicate claims are not allowed in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), can't add this XML to 3 existing ones:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1141468376">
   <created>2018-04-24T14:58:16.451Z</created>
   <type>Close job</type>
   <token>github;yegor256/cactoos;773</token>
   <author>ashtonhogan</author>
   <params>
      <param name="job">gh:yegor256/cactoos#773</param>
      <param name="reason">GitHub issue was closed</param>
   </params>
   <until>2018-04-24T15:13:16.452Z</until>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
The job [#773](https://github.com/yegor256/cactoos/issues/773) is now out of scope

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@346df6c8-40cd-4f70-ba65-5999eead80a1, thread: BkParallel-0
com.mongodb.connection.InternalStreamConnection[457] com.mongodb.MongoSocketReadTimeoutException: Timeout while receiving message
java.net.SocketInputStream[-2] java.net.SocketTimeoutException: Read timed out
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
