### ISSUE TITLE
SplitText is not efficient enough

### ISSUE THREAD

**Issue by krzyk** [yegor256/cactoos#780]
Current implementation of `SplitTest` uses `String.split()`, which in some cases (e.g. something longer than 1 char or in case of 2 chars a regex escape) does a Pattern.compile on the text. This is not efficient if the same regex is used multiple times and can give quote unpredictable performance differences when using a single char or a multiple char split text.

Because of that I propose to create a more efficient `SplitText` called `PatternSplitText` that will accept a `Pattern`(maybe `Scalar<Pattern>`), and modify the existing `SplitText` to do splitting by *not* using a String.split().

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@krzyk so instead of a new class `PatternSplitText`, we could just do internal refactor of `SplitText`. WDYT?

**Comment by krzyk** [comment]
@llorllale Yes it is possible, I proposed two classes because sometimes it might be good to have a pure and simple split by char or few chars - using simple iteration over the chars and splitting where appropriate.

And if there is a more complicated case (e.g. where we have to simple by multiple chars) one would want to use a regexp.

So if we leave only a single class, which one would it be, a regexp split or a multi-char split?

**Comment by krzyk** [comment]
@llorllale So what's your decision on this one?

**Comment by llorllale** [comment]
@krzyk I think at most we could refactor the existing `SplitText` by substituting that `UncheckedText regex` with `StickyScalar<Pattern> regex`. But I'm not sure it's worth it. Can you provide some measurements?

I'm not sure there is anything broken here. Our guiding [principles](http://www.elegantobjects.org/#principles) are there for us to remain faithful to the goal of providing a library of *elegant* objects, not necessarily *performant* ones. There's also the fact that we have finite resources while having other more pressing issues.

**Comment by krzyk** [comment]
@llorllale Fair enough, I tested it and for simple most common regexp patterns Pattern.split and String.split are quite comparable, so I'll close this issue.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@346df6c8-40cd-4f70-ba65-5999eead80a1, thread: BkParallel-2
com.zerocracy.pm.Claims[112] java.lang.IllegalStateException: Duplicate claims are not allowed in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), can't add this XML to 4 existing ones:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1141468386">
   <created>2018-04-24T14:58:41.293Z</created>
   <type>Close job</type>
   <token>github;yegor256/cactoos;780</token>
   <author>krzyk</author>
   <params>
      <param name="job">gh:yegor256/cactoos#780</param>
      <param name="reason">GitHub issue was closed</param>
   </params>
   <until>2018-04-24T15:13:41.299Z</until>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
