### ISSUE TITLE
Few code issues

### ISSUE THREAD

**Issue by krzyk** [yegor256/cactoos#781]
I found few small code issues so I grouped them into one:
1. `InputStreamReader` without the `Charset` param will use platform depended one, this constructor should  add `StandardCharsets.UTF-8` to `InputStreamReader` like it is done in other constructors in this class (alternative is to allow user to provide the Charset).
https://github.com/yegor256/cactoos/blob/288d1120989f494c33b1312d59f032e218522807/src/main/java/org/cactoos/text/TextOf.java#L350-L352

2. Below two `try` should be merged into one (making nested try if it is not needed is a bad style):
https://github.com/yegor256/cactoos/blob/769f5498b92893746a78bae16906b9125152da65/src/main/java/org/cactoos/io/DigestEnvelope.java#L90-L92

3. The javadoc link in `Text` class doesn't work, this link should either use fully-qualified name of `UncheckedText` or do an import of it:
https://github.com/yegor256/cactoos/blob/6c1f41952bf0b3a69ad6f81d58411e578dfc8a50/src/main/java/org/cactoos/Text.java#L33

4. Use of `Collection.toArray(new Something[1234])` is discouraged since Java 6, and can be slower then the `Collection.toArray(new Something[0])` version, so replace the `new Object[this.args.size()]` with `new Object[0]`
https://github.com/yegor256/cactoos/blob/6c1f41952bf0b3a69ad6f81d58411e578dfc8a50/src/main/java/org/cactoos/text/FormattedText.java#L168

5. `serialVersionUID` should be removed from lasses that are not serializable: `SumOfDoubleScalar`, `SumOfFloatScalar`, `SumOfIntScalar`, `SumOfLongScalar` and `SumOfScalar`

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by krzyk** [comment]
@proshin-roman thanks

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#781](https://github.com/yegor256/cactoos/issues/781) is now out of scope

**Comment by elenavolokhova** [comment]
@proshin-roman According to our Policy:
> Some of ticket messages must mention all pull requests where the problem was actually fixed

Please, confirm that you will follow this rule in future.

**Comment by proshin-roman** [comment]
@elenavolokhova Do you mean that I should always write something like "The issue has been fixed in pull request <PR number here>"? If so - I confirm.
