### ISSUE TITLE
Release 0.30

### ISSUE THREAD

**Issue by llorllale** [yegor256/cactoos#782]
As per [request](https://github.com/yegor256/cactoos/issues/761#issuecomment-383638621).

We have a few merged bugs and features:

* #737 
* #711 
* #686 
* #761

**Comment by llorllale** [comment]
@rultor release, tag is `0.30`

**Comment by llorllale** [comment]
@0crat out

**Comment by 0crat** [comment]
The job [#782](https://github.com/yegor256/cactoos/issues/782) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C63314D6Z/1131751670); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#782` already assigned to @llorllale, can't assign to @llorllale

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/782#issuecomment-383660341))

@llorllale GitHub issue is still open, won't close

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) I see that you unassigned this issue; the order is still assigned to @llorllale[/z](https://www.0crat.com/u/llorllale) though; to cancel the order use `refuse`, as in [§6](http://www.zerocracy.com/policy.html#6)

**Comment by llorllale** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/782#issuecomment-383661935))

@llorllale The user @llorllale[/z](https://www.0crat.com/u/llorllale) resigned from [#782](https://github.com/yegor256/cactoos/issues/782), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by llorllale** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/782#issuecomment-383665600))

@llorllale This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#782](https://github.com/yegor256/cactoos/issues/782) is [in scope](http://www.zerocracy.com/policy.html#14) for 16min
  * The role is `DEV`
  * The job is not assigned to anyone
  * The [budget](http://www.zerocracy.com/policy.html#4) is not set yet
  * These users are banned and won't be assigned:
    * @llorllale[/z](https://www.0crat.com/u/llorllale): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%23782%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by llorllale** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/782#issuecomment-383665729))

@llorllale GitHub issue is still open, won't close

**Comment by llorllale** [comment]
@0crat out

**Comment by 0crat** [comment]
> @0crat out ([here](https://github.com/yegor256/cactoos/issues/782#issuecomment-383666071))

@llorllale The job [#782](https://github.com/yegor256/cactoos/issues/782) is now out of scope

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
