### ISSUE TITLE
README.md should give examples for time and scalar packages

### ISSUE THREAD

**Issue by krzyk** [yegor256/cactoos#787]
Right now we have examples for almost all major parts of the library except the `org.cactoos.time`.
And we have a very small example of `org.cactoos.scalar` all over the place (`And` mostly)

Both of those need to mentioned and given an example in the README.md, this will help newcomers and potential users of this library see the benefits of cactoos.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by krzyk** [comment]
@llorllale OK, for Scalar it is hard, because its range is much wider than in other cases so I don't have any examples.

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
