### ISSUE TITLE
Create RandomText

### ISSUE THREAD

**Issue by krzyk** [yegor256/cactoos#790]
Random strings are quite common in unit tests where one has to produce some kind of a string into `TextOf`, that is not important in itself.

E.g.:
```
    new InputOf(
        new BytesOf(
            new TextOf("Hello, друг!")
        )
    )
```
Could be replaced with:

```
    new InputOf(
        new BytesOf(
            new RandomText()
        )
    )
```

`RandomText` should have two consructors:
- no-arg - producing random text from ASCII printable characters
- accepting List<Character> - will produce a random text from given list of characters

Each of the above should optionally accept an integer that will be the length of the text generated, without this number `RandomText` should generate the text with random number of characters.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@krzyk good idea, but why have ASCII-only versions?

**Comment by krzyk** [comment]
@llorllale Well, yeah, I'm just not sure how to limit the number of chars, to make it usefull, there are very limited cases when one would want control characters, so I would limit it to printable ones (`new PrintableRndText`?) and make `new RandomText` include all UTF chars?

**Comment by llorllale** [comment]
@krzyk aren't all utf chars printable?

**Comment by krzyk** [comment]
@llorllale so what's your decision?

**Comment by krzyk** [comment]
@llorllale Yes it makes sense, I'm only wondering if we want `Iterable`, choosing a number at random requires ... random access which is given only by `List`. So either we will be reading the whole `Iterable` into a `List` or we could force users to provide a `List` already.

**Comment by krzyk** [comment]
@llorllale done, I also added info about the length of the generated text, we didn't discuss that. It is quite common to limit the length of the text.

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ab56d234-9c5a-4a94-9bc9-5e54c14be93d, thread: BkParallel-7
com.mongodb.MongoCollectionImpl[558] com.mongodb.MongoWriteException: quota exceeded
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ab56d234-9c5a-4a94-9bc9-5e54c14be93d, thread: BkParallel-7
com.zerocracy.radars.github.ReSafe[76] java.io.IOException: com.mongodb.MongoWriteException: quota exceeded
com.mongodb.MongoCollectionImpl[558] com.mongodb.MongoWriteException: quota exceeded
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/790#issuecomment-385965245))

@llorllale Job [#790](https://github.com/yegor256/cactoos/issues/790) is now in scope, role is `DEV`

**Comment by proshin-roman** [comment]
@krzyk The issue has been fixed by pull request #830 that is already merged. Please, close the ticket.

**Comment by krzyk** [comment]
@proshin-roman thanks

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#790](https://github.com/yegor256/cactoos/issues/790) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@061d9217-0663-479c-8054-de2e25653967, thread: BkParallel-6
com.zerocracy.pm.Claims[112] java.lang.IllegalStateException: Duplicate claims are not allowed in [C63314D6Z](https://www.0crat.com/p/C63314D6Z), can't add this XML to 9 existing ones:
<?xml version="1.0" encoding="UTF-8"?>
<claim id="1290872388">
   <created>2018-05-09T08:54:06.978Z</created>
   <type>Complete `QA` review</type>
   <params>
      <param name="quality">good</param>
      <param name="job">gh:yegor256/cactoos#790</param>
      <param name="repo">yegor256/cactoos</param>
      <param name="issue">790</param>
      <param name="comment">387669592</param>
   </params>
   <token>github;yegor256/cactoos;790;387669592</token>
   <author>elenavolokhova</author>
</claim>

```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): Issue: yegor256/cactoos#790, Comment: 387669592

**Comment by 0crat** [comment]
> @0crat quality good ([here](https://github.com/yegor256/cactoos/issues/790#issuecomment-387669592))

@elenavolokhova Thanks, but quality review is not required in this job

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by yegor256** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/790#issuecomment-390688469))

@yegor256 This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#790](https://github.com/yegor256/cactoos/issues/790) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%23790%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)
