### ISSUE TITLE
FirstOf

### ISSUE THREAD

**Issue by Vatavuk** [yegor256/cactoos#793]
Let's create `FirstOf` that will find first element in a list that satisfies specified condition.
It should:
       -> implement `Scalar<T>`
       -> take arguments: `Func<T, Boolean> condition,  Iterable<T> src, Scalar<T> fallback`
       -> return fallback value if element is not found

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/793#issuecomment-385702506))

@llorllale Job [#793](https://github.com/yegor256/cactoos/issues/793) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by memoyil** [comment]
@Vatavuk @llorllale I will do that feature

**Comment by llorllale** [comment]
@memoyil let @0crat assign tasks

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/cactoos/issues/793#issuecomment-386879382); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by krzyk** [comment]
@Vatavuk Fixes in #840 were merged to master, please close this issue.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#793](https://github.com/yegor256/cactoos/issues/793) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
