### ISSUE TITLE
pom.xml:86-88: When...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#794]
The puzzle `720-dcdb33c9` from #720 has to be resolved:

https://github.com/yegor256/cactoos/blob/eab18ef93f9628b3f2f4296a0f652a1637f464ee/pom.xml#L86-L88

The puzzle was created by rultor on 28-Apr-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#794](https://github.com/yegor256/cactoos/issues/794) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#794](https://github.com/yegor256/cactoos/issues/794) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C63314D6Z/1251826966); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by krzyk** [comment]
@0pdd fixed in #834

**Comment by 0pdd** [comment]
The puzzle `720-dcdb33c9` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#794](https://github.com/yegor256/cactoos/issues/794) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good
