### ISSUE TITLE
BiFuncOf constructor with Scalar

### ISSUE THREAD

**Issue by VsSekorin** [yegor256/cactoos#796]
Let's add ctor for `BiFuncOf`: `public BiFuncOf(final Scalar<Z> result)`

If I have `Scalar<T> scl`, then I should be able to `new BiFuncOf<>(scl)`. Now I have to do `new BiFuncOf<>(scl.value())` or `new BiFuncOf<>(new UncheckedScalar<>(scl).value())`.

This

- is less readable
- kills the lazy loading

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/796#issuecomment-385414069))

@llorllale Job [#796](https://github.com/yegor256/cactoos/issues/796) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @vssekorin[/z](https://www.0crat.com/u/vssekorin)

**Comment by 0crat** [comment]
The job [#796](https://github.com/yegor256/cactoos/issues/796) assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/C63314D6Z/1252060348); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)
