### ISSUE TITLE
IterableOfFloats.java:35-40: Introduce IteratorOfFloats,...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#802]
The puzzle `748-cb897b68` from #748 has to be resolved:

https://github.com/yegor256/cactoos/blob/70e9b53f21481b08ec7563a04c1fe990b57c12c7/src/main/java/org/cactoos/iterable/IterableOfFloats.java#L35-L40

The puzzle was created by Vedran on 01-May-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#802](https://github.com/yegor256/cactoos/issues/802) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#802](https://github.com/yegor256/cactoos/issues/802) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C63314D6Z/1271347460); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0pdd** [comment]
The puzzle `748-cb897b68` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#838](https://github.com/yegor256/cactoos/issues/838) is still not solved.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by krzyk** [comment]
@0pdd fixed in #832

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#838](https://github.com/yegor256/cactoos/issues/838) is solved here.
