### ISSUE TITLE
ListEnvelope has mutable ListIterator

### ISSUE THREAD

**Issue by Vatavuk** [yegor256/cactoos#805]
`ListEnvelope` is read only but returns mutable `ListIterator` through which user can modify a list.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ab56d234-9c5a-4a94-9bc9-5e54c14be93d, thread: BkParallel-8
com.mongodb.MongoCollectionImpl[558] com.mongodb.MongoWriteException: quota exceeded
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by 0crat** [comment]
Job [#805](https://github.com/yegor256/cactoos/issues/805) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@ab56d234-9c5a-4a94-9bc9-5e54c14be93d, thread: BkParallel-2
com.mongodb.MongoCollectionImpl[558] com.mongodb.MongoWriteException: quota exceeded
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm)

**Comment by Vatavuk** [comment]
Closed due to 0crat failure and reopened it in a new issue #814

**Comment by 0crat** [comment]
The job [#805](https://github.com/yegor256/cactoos/issues/805) is now out of scope

**Comment by llorllale** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/805#issuecomment-386810512))

@llorllale This is what I know about this job, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#805](https://github.com/yegor256/cactoos/issues/805) is not in scope
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%23805%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)
