### ISSUE TITLE
Simplify usage of Joined classes

### ISSUE THREAD

**Issue by Vatavuk** [yegor256/cactoos#806]
In order to expand existing immutable list with a single element, user has to create a new 
list in a following way:
```java
new Joined<>(
     new IterableOf<>(element),
     elements
)
```
Let's simplify this usage by introducing new ctor in `Joined` classes

`org.cactoos.iterable`
```java
public Joined(final T item, final Iterable<T> items)
```
`org.cactoos.list`
```java
public Joined(final T item, final List<T> items)
```

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
The job [#806](https://github.com/yegor256/cactoos/issues/806) assigned to @vssekorin[/z](https://www.0crat.com/u/vssekorin), here is [why](https://www.0crat.com/footprint/C63314D6Z/1300649028); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by VsSekorin** [comment]
@0crat wait #853

**Comment by 0crat** [comment]
> @0crat wait #853  ([here](https://github.com/yegor256/cactoos/issues/806#issuecomment-387998762))

@VsSekorin The impediment for [#806](https://github.com/yegor256/cactoos/issues/806) was registered successfully by @vssekorin[/z](https://www.0crat.com/u/vssekorin)

**Comment by VsSekorin** [comment]
@Vatavuk #853 was merged.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @vssekorin[/z](https://www.0crat.com/u/vssekorin), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#806](https://github.com/yegor256/cactoos/issues/806) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vssekorin[/z](https://www.0crat.com/u/vssekorin)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
