### ISSUE TITLE
InheritanceLevel for unreleated classes should be negative

### ISSUE THREAD

**Issue by krzyk** [yegor256/cactoos#811]
Current `InheritanceLevel` implementation provides a `Integer.MAX_VALUE` for unrelated classes, which is not correct and at first I was puzzled why someone is checking for MAX_VALUE.

For me the natural way would be MIN_VALUE (or anything < 0), which is obviously not a correct inheritance level for related classes, while MAX_VALUE in very very very rare case might be.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/811#issuecomment-386430381))

@llorllale Job [#811](https://github.com/yegor256/cactoos/issues/811) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#811](https://github.com/yegor256/cactoos/issues/811) assigned to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), here is [why](https://www.0crat.com/footprint/C63314D6Z/1271635597); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by proshin-roman** [comment]
@krzyk The issue has been fixed in #833 - please, close the ticket.

**Comment by krzyk** [comment]
@proshin-roman thanks

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#811](https://github.com/yegor256/cactoos/issues/811) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
