### ISSUE TITLE
FuncOf constructor with Scalar

### ISSUE THREAD

**Issue by VsSekorin** [yegor256/cactoos#812]
Let's add ctor for `FuncOf`: `public FuncOf(final Scalar<Z> result)` similar to #796 
If I have `Scalar<T> scl`, then I should be able to `new FuncOf<>(scl)`. Now I have to do `new FuncOf<>(scl.value())` or `new FuncOf<>(new UncheckedScalar<>(scl).value())`. This is contrary to lazy loading principle.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by memoyil** [comment]
@0crat assign

**Comment by 0crat** [comment]
> @0crat assign ([here](https://github.com/yegor256/cactoos/issues/812#issuecomment-386557034))

@memoyil Option `<login>` is missing in `assign <login>`:
  \* `<login>`: "me" or GitHub login of the person to assign

**Comment by Vatavuk** [comment]
@llorllale @VsSekorin I've implemented this issue in PR #822 for #796

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/812#issuecomment-386883269))

@llorllale Job [#812](https://github.com/yegor256/cactoos/issues/812) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @vssekorin[/z](https://www.0crat.com/u/vssekorin)

**Comment by 0crat** [comment]
The job [#812](https://github.com/yegor256/cactoos/issues/812) assigned to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), here is [why](https://www.0crat.com/footprint/C63314D6Z/1302117576); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@proshin-roman[/z](https://www.0crat.com/u/proshin-roman) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by VsSekorin** [comment]
As I understand, PR for this task was merged. I close this issue.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#812](https://github.com/yegor256/cactoos/issues/812) is now out of scope

**Comment by elenavolokhova** [comment]
@proshin-roman According to our Policy:
> Some of ticket messages must mention all pull requests where the problem was actually fixed;

Please, confirm that you'll include such links in future tickets. Thanks!

**Comment by VsSekorin** [comment]
@elenavolokhova confirm. Thanks
