### ISSUE TITLE
ListEnvelope has mutable ListIterator

### ISSUE THREAD

**Issue by Vatavuk** [yegor256/cactoos#814]
ListEnvelope is read-only but returns mutable ListIterator through which user can modify a list.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/814#issuecomment-386810568))

@llorllale Job [#814](https://github.com/yegor256/cactoos/issues/814) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0pdd** [comment]
@Vatavuk the puzzle [#857](https://github.com/yegor256/cactoos/issues/857) is still not solved.

**Comment by krzyk** [comment]
@Vatavuk changes in #845 were merged to master, please close this issue

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#814](https://github.com/yegor256/cactoos/issues/814) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Comment by 0pdd** [comment]
@Vatavuk the only puzzle [#857](https://github.com/yegor256/cactoos/issues/857) is solved here.
