### ISSUE TITLE
Few configuration issues

### ISSUE THREAD

**Issue by krzyk** [yegor256/cactoos#815]
1. `.travis.yml`:
- we don't need `gem install est`  (and do we need xcop?, I don't see it used anywhere)
- script should have `pdd --source=$(pwd) --verbose --file=/dev/null` (just like in .rultor.yml) to catch PDD errors early
- ` mvn clean site -Psite --errors --batch-mode` should be after `mvn clean install ...`

2. `.rultor.yml`:
- `-XX:MaxPermSize=256m` should be removed (it is not used by java 8)
- architects section should have llorllale first (so he will asked by rultor after reviewer does `@rultor merge`)
- `pdd --source=$(pwd) --verbose --file=/dev/null` should be first in the `merge` part (to catch PDD errors early without doing long maven build)
- do we need `sudo gem install --no-rdoc --no-ri xcop`?

And general question, do we deploy the result of `mvn site` anywhere? It is build in both rultor and travis, but I don't know if there is a point in doing two almost full maven builds if we don't put the site anywhere.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/815#issuecomment-386884164))

@llorllale Job [#815](https://github.com/yegor256/cactoos/issues/815) is now in scope, role is `DEV`

**Comment by llorllale** [comment]
@0crat assign @llorllale

**Comment by 0crat** [comment]
The job [#815](https://github.com/yegor256/cactoos/issues/815) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C63314D6Z/1261439134); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/815#issuecomment-386884164))

@llorllale Job `gh:yegor256/cactoos#815` already assigned to @llorllale, can't assign to @llorllale

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
> @0crat assign @llorllale ([here](https://github.com/yegor256/cactoos/issues/815#issuecomment-386884337))

@llorllale Job [#815](https://github.com/yegor256/cactoos/issues/815) is already assigned to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by llorllale** [comment]
@krzyk 
`.travis.yml`:
1. `xcop` is being invoked via `jcabi-parent`. It's not obvious, but look for example in [this](http://www.rultor.com/t/14444-386820002) build log for the string "looks good"
2. `est`: I agree, we aren't using it. `pdd` does not list it as a [runtime dependency](https://rubygems.org/gems/pdd/versions/0.15.4).
3. Why should `mvn clean site` be after `mvn clea install`?
4. I will add `pdd` to the travis build

`.rultor.yml`
1. Will remove `-XX:MaxPermSize=256m`
2. Will rearrange list of architects
3. Will make `pdd` run first
4. `xcop` is required for the same reasons as in the travis build

**Comment by krzyk** [comment]
@llorllale just ignore the `clean site` comment

**Comment by llorllale** [comment]
@krzyk fixed in f9315fe740be3661e7edf6218f20584d3a1ece15

I think we can close this?

**Comment by krzyk** [comment]
@llorllale thanks

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#815](https://github.com/yegor256/cactoos/issues/815) is now out of scope
