### ISSUE TITLE
Matcher ScalarHasValue has to override describeMismatchSafely for better output

### ISSUE THREAD

**Issue by proshin-roman** [yegor256/cactoos#816]
Currently, `ScalarHasValue` doesn't override method `describeMismatchSafely` that leads to the next problem:
```java
final ScalarHasValue<String> matcher =
    new ScalarHasValue<>(new IsEqual<>("expected"));
final Scalar<String> scalar = new UncheckedScalar<>(() -> "actual");
final StringDescription description = new StringDescription();
matcher.describeMismatch(scalar, description);
System.out.println(description.toString());
// the out is:
// was <org.cactoos.scalar.UncheckedScalar@368239c8>
// how it should look like:
// was "actual"
```
so it prints an actual version incorrectly: default toString method is called for the Scalar.

**Expected:**
- the value of scalar is printed as an actual value of matching.

**What should be fixed**
- class `ScalarHasValue` has to override method `describeMismatchSafely` and convert Scalar to String properly.

**Comment by llorllale** [comment]
@proshin-roman let's put this on hold while #751 is sorted out

**Comment by llorllale** [comment]
@proshin-roman let's park this one while #751 is sorted out

**Comment by proshin-roman** [comment]
@llorllale yeah, ok, let's wait

**Comment by llorllale** [comment]
@proshin-roman matchers were moved to `llorllale/cactoos-matchers` as per #751. Please open this issue [here](https://github.com/llorllale/cactoos-matchers/issues)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@25988aaf-ee2f-4146-a0f5-fd10756db4a7, thread: AsyncFlush-4
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/close_job.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.zerocracy.farm.strict.StrictProject[111] java.lang.IllegalArgumentException: File "blanks/proshin-roman.xml" is not accessible in "PMO"
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): CID: 1321938267, Type: 'Close job', Author: llorllale
