### ISSUE TITLE
Javadoc issues

### ISSUE THREAD

**Issue by krzyk** [yegor256/cactoos#818]
When I tried to generate javadoc for the project I got many errors: 
[javadoc-errors.txt](https://github.com/yegor256/cactoos/files/1975668/javadoc-errors.txt).

Please fix them and to safeguard the fixes add to travis and rultor javadoc generation phase:
```
mvn javadoc:javadoc
```
(this will require configuring the javadoc plugin in project)

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@krzyk our release process is generating javadocs without issues it seems. For example, this error in your file:

> [ERROR] /home/kkrason/dev/tpc2/cactoos/src/main/java/org/cactoos/scalar/And.java:43: error: bad use of '>'
> [ERROR]  *    new ProcOf&lt;&gt;(input -> System.out.printf("\'%s\' ", input) ),

We could still generate and public javadoc for `And` just fine [here](https://static.javadoc.io/org.cactoos/cactoos/0.31/org/cactoos/scalar/And.html)

**Comment by krzyk** [comment]
@llorllale We just got lucky that we don't have any generic parameters inside `<>`, and browsers just display those cases as they appear. But if you check with html validator it will display those as errors.

**Comment by llorllale** [comment]
@krzyk are there use cases for running an html validator on the javadocs?

**Comment by llorllale** [comment]
@krzyk I suppose javadoc linting in `jcabi-parent` is too lax, yeah. If we fix this in `cactoos`, it would be only for cases where a user would want to generate it for themselves, is that it?

**Comment by krzyk** [comment]
@llorllale No, it will be incorrect also if we publish it, like it is here: https://static.javadoc.io/org.cactoos/cactoos/0.31/org/cactoos/scalar/Constant.html - incorrect entity used in the example section.

And in case they use browser that is not so lenient and would parse HTML more strictly.

**Comment by 0crat** [comment]
The job [#818](https://github.com/yegor256/cactoos/issues/818) assigned to @isammoc[/z](https://www.0crat.com/u/isammoc), here is [why](https://www.0crat.com/footprint/C63314D6Z/1361312188); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by Isammoc** [comment]
@krzyk @llorllale Please, close this issue as #877 was merged. Thanks ^^

**Comment by krzyk** [comment]
@Isammoc thanks

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @isammoc[/z](https://www.0crat.com/u/isammoc), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#818](https://github.com/yegor256/cactoos/issues/818) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @isammoc[/z](https://www.0crat.com/u/isammoc)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
