### ISSUE TITLE
FuncWithFallback.java:38-42: Refactor FuncWithFallback...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#821]
The puzzle `759-294de7ab` from #759 has to be resolved:

https://github.com/yegor256/cactoos/blob/859cecbfe9bfd12f869f0b7d5106cd9ad92892d6/src/main/java/org/cactoos/func/FuncWithFallback.java#L38-L42

The puzzle was created by Roman Proshin on 01-May-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by Vatavuk** [comment]
@victornoel Granular level of `fallback` feature is essentially a `Scalar`. And we are building greater objects from it (`FuncWithFallback`...). In case of `Sticky` feature granular level is `StickyBiFunc`. I see no problems with that.
Maybe this discussion can help: https://github.com/yegor256/cactoos/issues/656#issuecomment-366724517

**Comment by victornoel** [comment]
@Vatavuk good point, thanks for the feedback, the example helped me to understand how I can use `ScalarWithFallback` I think.

**Comment by victornoel** [comment]
@llorllale I'm good in the end, sorry for the noise :)

**Comment by victornoel** [comment]
@0crat waiting for #856 to be merged

**Comment by 0crat** [comment]
> @0crat waiting for #856 to be merged ([here](https://github.com/yegor256/cactoos/issues/821#issuecomment-388030507))

@victornoel Job [#821](https://github.com/yegor256/cactoos/issues/821) is already on hold

**Comment by 0pdd** [comment]
The puzzle `759-294de7ab` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#821](https://github.com/yegor256/cactoos/issues/821) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
