### ISSUE TITLE
Binary

### ISSUE THREAD

**Issue by Vatavuk** [yegor256/cactoos#825]
We currently have `Ternary` which is equivalent to `if then else`. 
I propose to create `Binary` that would be equivalent to `if then` for
situations when a user needs to execute a specific action for given condition.

`Binary` should:
     - implement `Scalar<Boolean>`
     -  provide two ctors: `(Scalar<Boolean> condition, Scalar<T> scalar)` and `(Scalar<Boolean> condition,  Runnable runnable)`
     - return true if condition is met and action is triggered

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@Vatavuk seems like overkill to me. Why not simple `if(...){...}` ?

**Comment by llorllale** [comment]
@Vatavuk btw, I believe you can currently do something similar using `And`

**Comment by Vatavuk** [comment]
@llorllale I don't see how can we do this with `And`. 
My reasoning is following:
I am looking at cactoos as a layer above java that provide us pure OOP approach. No `if,else,for,while,try/catch...` statements, nothing but objects. I'm currently working on a cactoos powered project with nothing but objects (few thousand lines so far) and this really started to look like a different language. Very close to EO language. But this argument is mainly subjective.

Although, one `if` statement is probably overkill I think it would be useful for multiple conditional statements.
 One concrete example I can think of is `if elseif` statments. When we don't want to execute second 
conditional test if we don't need to:
```java
if (condition1.test()) {
   action1.trigger();  
}
else if(condition2.test()) {
   action2.trigger();
}
```
This can be rewritten using `Or` and `Binary` combo:
```java
new Or(
   new Binary(() -> condition1.test(), () -> action1.trigger()),
   new Binary(() -> condition2.test(), () -> action2.trigger())
).value();
```

**Comment by llorllale** [comment]
@Vatavuk one of the ctors you proposed was `(Scalar<Boolean> condition, Scalar<T> scalar)`. How does that fit with what you're trying to achieve?

**Comment by Vatavuk** [comment]
@llorllale just to provide more usage options, the result of `Scalar<T> scalar` will  be ignored

**Comment by llorllale** [comment]
@Vatavuk I don't see a reason to provide that ctor with scalar that will be ignored..

Everything else you've said sounds great though.

**Comment by Vatavuk** [comment]
@llorllale you are right, we can drop that ctor. I thought I have an example of such a usage but nothing rational comes in to my mind.

**Comment by Vatavuk** [comment]
@llorllale I remembered now, we need scalar in ctor if we want to throw exceptions.
For instance:
 ```java
new Binary(
    condition,
    () -> {throw new IOException(msg);}
)
```

**Comment by 0crat** [comment]
The job [#825](https://github.com/yegor256/cactoos/issues/825) assigned to @borysfan[/z](https://www.0crat.com/u/borysfan), here is [why](https://www.0crat.com/footprint/C63314D6Z/7e64540c-90f0-4529-8260-16d4a6775384); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by borysfan** [comment]
@llorllale Hej. This issue has been covered in PR #1054. Could you please close this issue?

**Comment by 0crat** [comment]
The job [#825](https://github.com/yegor256/cactoos/issues/825) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @borysfan[/z](https://www.0crat.com/u/borysfan)
