### ISSUE TITLE
ScalarEnvelope and FuncEnvelope

### ISSUE THREAD

**Issue by Vatavuk** [yegor256/cactoos#826]
Although `Scalar` and `Func` interfaces consist of only one method I think that it would be valuable for a user to be able to use envelopes for them.
One use case would be when the user wants to create a custom fallback plan (via `ScalarWithFallback/FuncWithFallback`) and reuse it throughout a codebase. He should not need to implement `Scalar`, just extend `ScalarEnvelope`

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@Vatavuk but that's what `ScalarWithFallback` and `FuncWithFallback` are for, isn't it? I don't quite understand your use-case, could you please elaborate more?

**Comment by Vatavuk** [comment]
@llorllale I meant something like this:
```java
public class CustomFallback extends ScalarEnvelope<Integer> {

    public CustomFallback(final Scalar<Integer> origin, final String message) {
        super(
            new ScalarWithFallback<>(
                origin,
                new FallbackFrom(
                    new IterableOf<>(IOException.class, ThirdPartyException.class)
                    exp -> {
                        LOGGER.error(message, exp);
                        throw new CustomException(exp);
                    }
                )
            )
        );
    }
}
```
If I need such implementation of `ScalarWithFallback` in multiple places in my code I simply use `CustomFallback`. And to simplify `CustomFallback` and other custom scalar creations I suggest to implement `ScalarEnvelope` as well as `FuncEnvelope`

**Comment by llorllale** [comment]
@Vatavuk what would be the use, then, of `ScalarWithFallback`? If I understand correctly, you want to re-implement `ScalarWithFallback` in a new `ScalarEnvelope`

**Comment by Vatavuk** [comment]
@llorllale I want to create specific instance of `ScalarWithFallback` so I can reuse it without creating/specifying `ScalarWithFallback` all over again.
Lets say that we are communicating with some third party pieces of software that throw their own types of checked exceptions and our system understands only its type of exception.
We can create new class for exception handling `CustomFallback` through `ScalarEnvelope` and whenever we want to touch that third party methods we can 
do it like this `new CustomFallback(() -> thirdPartyMethod(), "error message")`

This is just an example where `ScalarEnvelope` might come in handy.

**Comment by Vatavuk** [comment]
@llorllale without envelope I would have to implement `Scalar` which is ok but could be simplified

**Comment by llorllale** [comment]
@Vatavuk ok. 

Both `Scalar` and `Func` are simple interfaces with just one abstract method. But, let's do this to promote this elegant pattern among our users and also to align these two interfaces with the other envelopes we have

**Comment by llorllale** [comment]
@0crat in

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/826#issuecomment-391018562))

@llorllale Job [#826](https://github.com/yegor256/cactoos/issues/826) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/826#issuecomment-401827461))

@llorllale Job [#826](https://github.com/yegor256/cactoos/issues/826) is already in scope

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0crat** [comment]
The job [#826](https://github.com/yegor256/cactoos/issues/826) assigned to @golyalpha[/z](https://www.0crat.com/u/golyalpha), here is [why](https://www.0crat.com/footprint/C63314D6Z/c6cadf50-08cc-4375-b6d7-bcb143085d94); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The job [#826](https://github.com/yegor256/cactoos/issues/826) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/746e75a8-dcfc-49b5-88c8-efc66bc72aba); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@llorllale can I use [eo-envelopes](https://github.com/victornoel/eo-envelopes) for this? We already are using it in zold-java-api and it seemed to be appreciated. I have been using it at work for some times without any problem.

**Comment by victornoel** [comment]
@llorllale any answer for the above question?

**Comment by llorllale** [comment]
@victornoel `cactoos` envelopes tend to implement `equals()` and `hashcode()` so I'm not too sure about using eo-envelopes.

**Comment by victornoel** [comment]
@llorllale yes I agree in some case (for example `CollectionEnvelope`), but here:
- we are talking of `Scalar` and `Func`, I don't think objects implementing them should implement either `hashCode` or `equals`.
- eo-envelope is only used when generating envelopes for interfaces we do define ourselves (so not for the case similar to `CollectionEnvelope`) and we should thrive for object oriented interfaces, i.e., not needing to implement `equals` and `hashCode`.
- so if `equals` and `hashCode` do need to be delegated to the enveloped object, this is not a problem, we just need to explicitly declares them in the interface for them to be delegated and it makes the contract even more explicit in the interface as a byproduct.

Actually the last point is a bit of a fallacy because `equals` won't work as expected with an envelope, but to me this is because we shouldn't be relying on something like `equals` in EO :)

I'm ok not to use it, but I exposed above reason to do so, I will let you decide :)

**Comment by llorllale** [comment]
@victornoel I am more concerned with the uniformity of the envelope implementations. 

I agree that `Scalar` and `Func` probably don't require envelopes, and I also agree that EO code should avoid `equals` when possible.

And then we have `TextEnvelope`.

In the end, I'm not sure what the ROI for this will be, if any. On one hand, we would add this special rule of "use eo-envelopes for cactoos interfaces except for TextEnvelope, otherwise manually roll our own" (additional mental overhead). On the other hand, our interfaces are small, so manually rolling our own Envelopes should not be a big issue.

Where eo-envelopes seems to shine is in generating envelopes for big interfaces, but already that presupposes a design that doesn't respect EO principles.

**Comment by victornoel** [comment]
@llorllale yep, good points, I will do it without eo-envelopes then

**Comment by victornoel** [comment]
@0crat wait for #1091 to be merged

**Comment by victornoel** [comment]
@Vatavuk can you confirm that #1091 answers your needs? :)

**Comment by 0crat** [comment]
> @0crat wait for #1091 to be merged ([here](https://github.com/yegor256/cactoos/issues/826#issuecomment-478273520))

@victornoel The impediment for [#826](https://github.com/yegor256/cactoos/issues/826) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by Vatavuk** [comment]
@victornoel it does:)

**Comment by victornoel** [comment]
@Vatavuk this was merged, can you close the issue?

**Comment by Vatavuk** [comment]
@victornoel thx

**Comment by 0crat** [comment]
Job [#826](https://github.com/yegor256/cactoos/issues/826) is not in the agenda of @victornoel[/z](https://www.0crat.com/u/victornoel), can't inspect

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#826](https://github.com/yegor256/cactoos/issues/826) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
