### ISSUE TITLE
Expand ctors for ScalarWithFallback and FallbackFrom

### ISSUE THREAD

**Issue by Vatavuk** [yegor256/cactoos#827]
Currently, if we want to use `ScalarWithFallback` user needs to provide follow up function as well as an iterable for fallback options. Furthermore, for each fallback option user needs to provide an iterable of exception types.
Example:
```java
new ScalarWithFallback<>(
    () -> {
        throw new IOException("Failure with IOException");
    },
    new IterableOf<>(
        new FallbackFrom<>(
            new IterableOf<>(IOException.class),
            exp -> message
        )),
    input -> input
)
```
This is to verbose and could be simplified by adding two ctors to `ScalarWithFallback:`
```java 
ScalarWithFallback(final Scalar<T> origin, final FallbackFrom<T>... fbks)
ScalarWithFallback(final Scalar<T> origin, final Iterable<FallbackFrom<T>> fbks)
```
And one to `FallbackFrom`:
```java
FallbackFrom(final Class<? extends Throwable> exp, final Func<Throwable, T> func)
```
End result:
```java
new ScalarWithFallback<>(
    () -> {
        throw new IOException("Failure with IOException");
    },
    new FallbackFrom<>(
        IOException.class,
        exp -> message
    )
)
```

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by Vatavuk** [comment]
First two ctors won't work since there will be a collision with `followup` function arguments.

The third ctor is implemented so I'm closing this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@c416a035-d354-4b2e-aacb-5a72c205a144, thread: AsyncFlush-2
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/close_job.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.zerocracy.farm.strict.StrictProject[111] java.lang.IllegalArgumentException: File "blanks/vatavuk.xml" is not accessible in "PMO"
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): CID: 1311854204, Type: 'Close job', Author: vatavuk
