### ISSUE TITLE
Tests for AndInThreads are not stable

### ISSUE THREAD

**Issue by Vatavuk** [yegor256/cactoos#829]
AndInThreadsTest is not stable: https://github.com/yegor256/cactoos/pull/817#issuecomment-386880040

They fail randomly on my local machine too.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/829#issuecomment-387108040))

@llorllale Job [#829](https://github.com/yegor256/cactoos/issues/829) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0crat** [comment]
The job [#829](https://github.com/yegor256/cactoos/issues/829) assigned to @pbenety[/z](https://www.0crat.com/u/pbenety), here is [why](https://www.0crat.com/footprint/C63314D6Z/1301343646); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by pbenety** [comment]
@0crat waiting for review #874

**Comment by 0crat** [comment]
> @0crat waiting for review #874 ([here](https://github.com/yegor256/cactoos/issues/829#issuecomment-389360736))

@pbenety The impediment for [#829](https://github.com/yegor256/cactoos/issues/829) was registered successfully by @pbenety[/z](https://www.0crat.com/u/pbenety)

**Comment by 0pdd** [comment]
@Vatavuk the puzzle [#898](https://github.com/yegor256/cactoos/issues/898) is still not solved.

**Comment by pbenety** [comment]
@Vatavuk please close this issue. PR #874 was merged.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @pbenety[/z](https://www.0crat.com/u/pbenety), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#829](https://github.com/yegor256/cactoos/issues/829) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @pbenety[/z](https://www.0crat.com/u/pbenety)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Comment by 0pdd** [comment]
@Vatavuk 5 puzzles [#1217](https://github.com/yegor256/cactoos/issues/1217), [#1218](https://github.com/yegor256/cactoos/issues/1218), [#1219](https://github.com/yegor256/cactoos/issues/1219), [#1220](https://github.com/yegor256/cactoos/issues/1220), [#1221](https://github.com/yegor256/cactoos/issues/1221) are still not solved; solved: [#898](https://github.com/yegor256/cactoos/issues/898).

**Comment by 0pdd** [comment]
@Vatavuk 5 puzzles [#1217](https://github.com/yegor256/cactoos/issues/1217), [#1218](https://github.com/yegor256/cactoos/issues/1218), [#1220](https://github.com/yegor256/cactoos/issues/1220), [#1221](https://github.com/yegor256/cactoos/issues/1221), [#1230](https://github.com/yegor256/cactoos/issues/1230) are still not solved; solved: [#1219](https://github.com/yegor256/cactoos/issues/1219), [#898](https://github.com/yegor256/cactoos/issues/898).

**Comment by 0pdd** [comment]
@Vatavuk 5 puzzles [#1217](https://github.com/yegor256/cactoos/issues/1217), [#1218](https://github.com/yegor256/cactoos/issues/1218), [#1220](https://github.com/yegor256/cactoos/issues/1220), [#1221](https://github.com/yegor256/cactoos/issues/1221), [#1233](https://github.com/yegor256/cactoos/issues/1233) are still not solved; solved: [#1219](https://github.com/yegor256/cactoos/issues/1219), [#1230](https://github.com/yegor256/cactoos/issues/1230), [#898](https://github.com/yegor256/cactoos/issues/898).

**Comment by 0pdd** [comment]
@Vatavuk 4 puzzles [#1217](https://github.com/yegor256/cactoos/issues/1217), [#1220](https://github.com/yegor256/cactoos/issues/1220), [#1221](https://github.com/yegor256/cactoos/issues/1221), [#1233](https://github.com/yegor256/cactoos/issues/1233) are still not solved; solved: [#1218](https://github.com/yegor256/cactoos/issues/1218), [#1219](https://github.com/yegor256/cactoos/issues/1219), [#1230](https://github.com/yegor256/cactoos/issues/1230), [#898](https://github.com/yegor256/cactoos/issues/898).

**Comment by 0pdd** [comment]
@Vatavuk 4 puzzles [#1217](https://github.com/yegor256/cactoos/issues/1217), [#1220](https://github.com/yegor256/cactoos/issues/1220), [#1221](https://github.com/yegor256/cactoos/issues/1221), [#1291](https://github.com/yegor256/cactoos/issues/1291) are still not solved; solved: [#1218](https://github.com/yegor256/cactoos/issues/1218), [#1219](https://github.com/yegor256/cactoos/issues/1219), [#1230](https://github.com/yegor256/cactoos/issues/1230), [#1233](https://github.com/yegor256/cactoos/issues/1233), [#898](https://github.com/yegor256/cactoos/issues/898).

**Comment by 0pdd** [comment]
@Vatavuk 3 puzzles [#1217](https://github.com/yegor256/cactoos/issues/1217), [#1220](https://github.com/yegor256/cactoos/issues/1220), [#1221](https://github.com/yegor256/cactoos/issues/1221) are still not solved; solved: [#1218](https://github.com/yegor256/cactoos/issues/1218), [#1219](https://github.com/yegor256/cactoos/issues/1219), [#1230](https://github.com/yegor256/cactoos/issues/1230), [#1233](https://github.com/yegor256/cactoos/issues/1233), [#1291](https://github.com/yegor256/cactoos/issues/1291), [#898](https://github.com/yegor256/cactoos/issues/898).

**Comment by 0pdd** [comment]
@Vatavuk 2 puzzles [#1217](https://github.com/yegor256/cactoos/issues/1217), [#1221](https://github.com/yegor256/cactoos/issues/1221) are still not solved; solved: [#1218](https://github.com/yegor256/cactoos/issues/1218), [#1219](https://github.com/yegor256/cactoos/issues/1219), [#1220](https://github.com/yegor256/cactoos/issues/1220), [#1230](https://github.com/yegor256/cactoos/issues/1230), [#1233](https://github.com/yegor256/cactoos/issues/1233), [#1291](https://github.com/yegor256/cactoos/issues/1291), [#898](https://github.com/yegor256/cactoos/issues/898).

**Comment by 0pdd** [comment]
@Vatavuk the puzzle [#1221](https://github.com/yegor256/cactoos/issues/1221) is still not solved; solved: [#1217](https://github.com/yegor256/cactoos/issues/1217), [#1218](https://github.com/yegor256/cactoos/issues/1218), [#1219](https://github.com/yegor256/cactoos/issues/1219), [#1220](https://github.com/yegor256/cactoos/issues/1220), [#1230](https://github.com/yegor256/cactoos/issues/1230), [#1233](https://github.com/yegor256/cactoos/issues/1233), [#1291](https://github.com/yegor256/cactoos/issues/1291), [#898](https://github.com/yegor256/cactoos/issues/898).

**Comment by 0pdd** [comment]
@Vatavuk the puzzle [#unknown]() is still not solved; solved: [#1217](https://github.com/yegor256/cactoos/issues/1217), [#1218](https://github.com/yegor256/cactoos/issues/1218), [#1219](https://github.com/yegor256/cactoos/issues/1219), [#1220](https://github.com/yegor256/cactoos/issues/1220), [#1221](https://github.com/yegor256/cactoos/issues/1221), [#1230](https://github.com/yegor256/cactoos/issues/1230), [#1233](https://github.com/yegor256/cactoos/issues/1233), [#1291](https://github.com/yegor256/cactoos/issues/1291), [#898](https://github.com/yegor256/cactoos/issues/898).

**Comment by 0pdd** [comment]
@Vatavuk the puzzle [#1730](https://github.com/yegor256/cactoos/issues/1730) is still not solved; solved: [#1217](https://github.com/yegor256/cactoos/issues/1217), [#1218](https://github.com/yegor256/cactoos/issues/1218), [#1219](https://github.com/yegor256/cactoos/issues/1219), [#1220](https://github.com/yegor256/cactoos/issues/1220), [#1221](https://github.com/yegor256/cactoos/issues/1221), [#1230](https://github.com/yegor256/cactoos/issues/1230), [#1233](https://github.com/yegor256/cactoos/issues/1233), [#1291](https://github.com/yegor256/cactoos/issues/1291), [#898](https://github.com/yegor256/cactoos/issues/898).

**Comment by 0pdd** [comment]
@Vatavuk all 10 puzzles are solved here: [#1217](https://github.com/yegor256/cactoos/issues/1217), [#1218](https://github.com/yegor256/cactoos/issues/1218), [#1219](https://github.com/yegor256/cactoos/issues/1219), [#1220](https://github.com/yegor256/cactoos/issues/1220), [#1221](https://github.com/yegor256/cactoos/issues/1221), [#1230](https://github.com/yegor256/cactoos/issues/1230), [#1233](https://github.com/yegor256/cactoos/issues/1233), [#1291](https://github.com/yegor256/cactoos/issues/1291), [#1730](https://github.com/yegor256/cactoos/issues/1730), [#898](https://github.com/yegor256/cactoos/issues/898).
