### ISSUE TITLE
Incorrect implementation for FuncApplies.describeTo

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#837]
`FuncApplies.describeTo` refers to `Scalar` instead of `Func`

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@victornoel let's park this one while #751 is sorted out

**Comment by llorllale** [comment]
@victornoel matchers were moved to `llorllale/cactoos-matchers` as per #751. Please open this issue [here](https://github.com/llorllale/cactoos-matchers/issues)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@25988aaf-ee2f-4146-a0f5-fd10756db4a7, thread: AsyncFlush-3
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/close_job.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.zerocracy.farm.strict.StrictProject[111] java.lang.IllegalArgumentException: File "blanks/victornoel.xml" is not accessible in "PMO"
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): CID: 1321938255, Type: 'Close job', Author: llorllale
