### ISSUE TITLE
IteratorOfXXX are marked as not being thread-safe but seem to be...

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#841]
Looking at https://github.com/yegor256/cactoos/blob/57a3c18175ef35e79a1bd1c35284be7db1c228b5/src/main/java/org/cactoos/iterator/IteratorOf.java#L33, we can see that this class and other similar are marked as not being thread safe.

But the thing is that they seem to be: they are implemented using an `AtomicBoolean`  to track the iteration. They are as thread-safe as they can be.

I am asking because I am working on #838 and I don't want to repeat the same mistake (if there is) and need clarification on this.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@victornoel well... it looks like it *accidentally* may have ended up as thread-safe, but it certainly is *not* required to be. That's what `SyncIterator` is for.

Looks like `IteratorOf` was previously known as `StickyIterator` (see #641).

I believe there is no issue here: `IteratorOf` makes no guarantees as to thread-safety and is thus free to refactor this implementation detail in the future. WDYT?

**Comment by victornoel** [comment]
@llorllale seems good to me yes. I didn't think to look at `SyncIterator` indeed, thanks for the clarification!

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@38e2c9bb-8f57-4fb1-8558-17fff4f33af4, thread: AsyncFlush-6
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/close_job.groovy
sun.reflect.GeneratedMethodAccessor1422[-1] java.lang.reflect.InvocationTargetException: null
com.zerocracy.farm.strict.StrictProject[111] java.lang.IllegalArgumentException: File "blanks/victornoel.xml" is not accessible in "PMO"
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): CID: 1300955807, Type: 'Close job', Author: victornoel
