### ISSUE TITLE
TextEnvelope.java:38-40: Refactor all classes in text...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#849]
The puzzle `788-d4bcd092` from #788 has to be resolved:

https://github.com/yegor256/cactoos/blob/0314515f133f4ac8b1be143fcbb7cc6c0c5ad40a/src/main/java/org/cactoos/text/TextEnvelope.java#L38-L40

The puzzle was created by Paulo Lobo on 08-May-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#849](https://github.com/yegor256/cactoos/issues/849) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#849](https://github.com/yegor256/cactoos/issues/849) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C63314D6Z/1302021514); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by krzyk** [comment]
@0pdd PR created - #860

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0pdd** [comment]
The puzzle `788-d4bcd092` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @krzyk[/z](https://www.0crat.com/u/krzyk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#849](https://github.com/yegor256/cactoos/issues/849) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#897](https://github.com/yegor256/cactoos/issues/897) is still not solved; solved: [#878](https://github.com/yegor256/cactoos/issues/878).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#929](https://github.com/yegor256/cactoos/issues/929) is still not solved; solved: [#878](https://github.com/yegor256/cactoos/issues/878), [#897](https://github.com/yegor256/cactoos/issues/897).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1063](https://github.com/yegor256/cactoos/issues/1063) is still not solved; solved: [#878](https://github.com/yegor256/cactoos/issues/878), [#897](https://github.com/yegor256/cactoos/issues/897), [#929](https://github.com/yegor256/cactoos/issues/929).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1116](https://github.com/yegor256/cactoos/issues/1116) is still not solved; solved: [#1063](https://github.com/yegor256/cactoos/issues/1063), [#878](https://github.com/yegor256/cactoos/issues/878), [#897](https://github.com/yegor256/cactoos/issues/897), [#929](https://github.com/yegor256/cactoos/issues/929).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1135](https://github.com/yegor256/cactoos/issues/1135) is still not solved; solved: [#1063](https://github.com/yegor256/cactoos/issues/1063), [#1116](https://github.com/yegor256/cactoos/issues/1116), [#878](https://github.com/yegor256/cactoos/issues/878), [#897](https://github.com/yegor256/cactoos/issues/897), [#929](https://github.com/yegor256/cactoos/issues/929).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1135](https://github.com/yegor256/cactoos/issues/1135), [#1261](https://github.com/yegor256/cactoos/issues/1261) are still not solved; solved: [#1063](https://github.com/yegor256/cactoos/issues/1063), [#1116](https://github.com/yegor256/cactoos/issues/1116), [#878](https://github.com/yegor256/cactoos/issues/878), [#897](https://github.com/yegor256/cactoos/issues/897), [#929](https://github.com/yegor256/cactoos/issues/929).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1261](https://github.com/yegor256/cactoos/issues/1261) is still not solved; solved: [#1063](https://github.com/yegor256/cactoos/issues/1063), [#1116](https://github.com/yegor256/cactoos/issues/1116), [#1135](https://github.com/yegor256/cactoos/issues/1135), [#878](https://github.com/yegor256/cactoos/issues/878), [#897](https://github.com/yegor256/cactoos/issues/897), [#929](https://github.com/yegor256/cactoos/issues/929).

**Comment by 0pdd** [comment]
@0pdd all 7 puzzles are solved here: [#1063](https://github.com/yegor256/cactoos/issues/1063), [#1116](https://github.com/yegor256/cactoos/issues/1116), [#1135](https://github.com/yegor256/cactoos/issues/1135), [#1261](https://github.com/yegor256/cactoos/issues/1261), [#878](https://github.com/yegor256/cactoos/issues/878), [#897](https://github.com/yegor256/cactoos/issues/897), [#929](https://github.com/yegor256/cactoos/issues/929).
