### ISSUE TITLE
Resurrect Skipped Iterable

### ISSUE THREAD

**Issue by jimkast** [yegor256/cactoos#850]
Can we restore Skipped iterable decorator wich was removed after solving #185 ? HeadOf and TailOf decorate in a different way and cannot replace the recently removed Skipped iterable (which omits a number of head elements from an iterable)

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@jimkast[/z](https://www.0crat.com/u/jimkast) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/850#issuecomment-387870336))

@llorllale Job [#850](https://github.com/yegor256/cactoos/issues/850) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/850#issuecomment-387870336))

@llorllale Thanks for your contribution, @jimkast[/z](https://www.0crat.com/u/jimkast)! If you would be a member of [the project](https://www.0crat.com/p/C63314D6Z), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
The job [#850](https://github.com/yegor256/cactoos/issues/850) assigned to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), here is [why](https://www.0crat.com/footprint/C63314D6Z/1302120688); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by 0crat** [comment]
@proshin-roman[/z](https://www.0crat.com/u/proshin-roman) this job was assigned to you 6days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by proshin-roman** [comment]
@jimkast the issue has been fixed in #869 - please, close the ticket.

**Comment by jimkast** [comment]
Sure, Skipped has been restored, thank you very much.
By the way Skipped is very useful when you use yegor's [takes](https://github.com/yegor256/takes). When you need to decorate request/response headers, you need to skip head() the first line, and the easiest and best way is using Skipped iterable.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @proshin-roman[/z](https://www.0crat.com/u/proshin-roman), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#850](https://github.com/yegor256/cactoos/issues/850) is now out of scope

**Comment by elenavolokhova** [comment]
@jimkast According to our [Policy](http://www.zerocracy.com/policy.html#42):
> Messages in a job always start with a name of a user they are addressed to;

Please, confirm that you will address all your messages in future tickets. Thanks!

**Comment by llorllale** [comment]
@rultor release, tag is `0.34`

**Comment by elenavolokhova** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
