### ISSUE TITLE
NoNulls classes API inconsistency

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#852]
We have these following `*NoNulls` files/classes:
```
CollectionNoNulls.java
IterableNoNulls.java
IteratorNoNulls.java
ListNoNulls.java
MapNoNulls.java
```
And these classes declared *inside* of interfaces:
```
BiFunc.NoNulls
BiProc.NoNulls
Bytes.NoNulls
Func.NoNulls
Input.NoNulls
Output.NoNulls
Proc.NoNulls
Scalar.NoNulls
Text.NoNulls
```
So, we should refactor the `Interface.NoNulls` classes to extract these classes from interfaces. This will get some advantages:
- Correct API inconsistency, because all `NoNulls` classes will be files *outside* of interfaces
- Correct API *name* inconsistency (all `NoNulls`don't have a dot (.) in their names)
- Correct API classes location: all classes will be in the respective packages and not declared inside interfaces
- It's easier to read and understand the API (cleaner interfaces)
- It's easier to find all `NoNulls` classes (by command line shell or using an IDE)

**Comment by llorllale** [comment]
@fabriciofx I'm on the fence on this one. 

Perhaps rename the outer classes to `NoNulls`, and extract the inner classes to outer. 

Maybe, I don't know. WDYT?

**Comment by llorllale** [comment]
@fabriciofx also, off topic: you're unresponsive in other issues/PRs. What's up?

**Comment by llorllale** [comment]
@fabriciofx nevermind, I agree

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/852#issuecomment-391020774))

@llorllale Job [#852](https://github.com/yegor256/cactoos/issues/852) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by neonailol** [comment]
@llorllale one of the core principles of EO is `no nulls`, so why `no nulls` is not the default behaviour, and this classes is not used internally to decorate everything?

**Comment by llorllale** [comment]
@neonailol the `*NoNulls` classes also check *internal* if there are `null` positions *inside* the container

**Comment by 0crat** [comment]
The job [#852](https://github.com/yegor256/cactoos/issues/852) assigned to @dgroup[/z](https://www.0crat.com/u/dgroup), here is [why](https://www.0crat.com/footprint/C63314D6Z/776028c9-7076-45c8-bf31-dcbc863151a0); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by dgroup** [comment]
@0crat wait as #990 is raised.

**Comment by 0crat** [comment]
> @0crat wait as #990 is raised. ([here](https://github.com/yegor256/cactoos/issues/852#issuecomment-451252249))

@dgroup The impediment for [#852](https://github.com/yegor256/cactoos/issues/852) was registered successfully by @dgroup[/z](https://www.0crat.com/u/dgroup)

**Comment by 0pdd** [comment]
@fabriciofx 3 puzzles [#1015](https://github.com/yegor256/cactoos/issues/1015), [#1016](https://github.com/yegor256/cactoos/issues/1016), [#1017](https://github.com/yegor256/cactoos/issues/1017) are still not solved.

**Comment by 0pdd** [comment]
@fabriciofx 2 puzzles [#1015](https://github.com/yegor256/cactoos/issues/1015), [#1016](https://github.com/yegor256/cactoos/issues/1016) are still not solved; solved: [#1017](https://github.com/yegor256/cactoos/issues/1017).

**Comment by llorllale** [comment]
@fabriciofx PR #990 was merged, can we close this?

**Comment by llorllale** [comment]
@fabriciofx ping

**Comment by 0pdd** [comment]
@fabriciofx the puzzle [#1016](https://github.com/yegor256/cactoos/issues/1016) is still not solved; solved: [#1015](https://github.com/yegor256/cactoos/issues/1015), [#1017](https://github.com/yegor256/cactoos/issues/1017).

**Comment by 0pdd** [comment]
@fabriciofx all 3 puzzles are solved here: [#1015](https://github.com/yegor256/cactoos/issues/1015), [#1016](https://github.com/yegor256/cactoos/issues/1016), [#1017](https://github.com/yegor256/cactoos/issues/1017).

**Comment by 0crat** [comment]
The architect of the project has changed; @llorllale[/z](https://www.0crat.com/u/llorllale) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by sereshqua** [comment]
@paulodamaso hi, i believe this can be closed :) just helping to get rid of opened issues

**Comment by paulodamaso** [comment]
@sereshqua Thank you!

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @dgroup[/z](https://www.0crat.com/u/dgroup), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @dgroup[/z](https://www.0crat.com/u/dgroup)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
