### ISSUE TITLE
Introduce Flatten

### ISSUE THREAD

**Issue by krzyk** [yegor256/cactoos#859]
Create `Flatten` that would take a `Iterable` of `Iterable` and produce an `Iterable` with all the data.
**When I write `Iterable` I mean also `Iterator`, `Collection` and `List`.**

Example usage:
```
MatcherAssert.assertThat(
    new Flatten<>(
        new IterableOf<>(new IterableOf<>("one", "two"), new Iterable<>("three"))
    ),
    Matchers.hasItems("one", "two", "three")
);
```

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@krzyk why not `Joined`?

**Comment by krzyk** [comment]
@llorllale Oh, I wasn't able to guess the name :)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@c416a035-d354-4b2e-aacb-5a72c205a144, thread: AsyncFlush-8
com.zerocracy.farm.reactive.StkGroovy[125] java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/in/orders/close_job.groovy
sun.reflect.NativeMethodAccessorImpl[-2] java.lang.reflect.InvocationTargetException: null
com.zerocracy.farm.strict.StrictProject[111] java.lang.IllegalArgumentException: File "blanks/krzyk.xml" is not accessible in "PMO"
```

[1.0-SNAPSHOT](https://github.com/zerocracy/farm): CID: 1311742920, Type: 'Close job', Author: krzyk
