### ISSUE TITLE
CollectionEnvelopeTest.java:35-37: IterableEnvelope...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#862]
The puzzle `813-8130ed5b` from #813 has to be resolved:

https://github.com/yegor256/cactoos/blob/c19e8a9b0d528fa2408453ef4dcf3605c791ea15/src/test/java/org/cactoos/collection/CollectionEnvelopeTest.java#L35-L37

The puzzle was created by Krzysztof Krason on 09-May-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@0pdd[/z](https://www.0crat.com/u/0pdd) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment]
Job [#862](https://github.com/yegor256/cactoos/issues/862) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#862](https://github.com/yegor256/cactoos/issues/862) assigned to @isammoc[/z](https://www.0crat.com/u/isammoc), here is [why](https://www.0crat.com/footprint/C63314D6Z/1361315231); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by Isammoc** [comment]
@0crat wait for #890

**Comment by 0crat** [comment]
> @0crat wait for #890  ([here](https://github.com/yegor256/cactoos/issues/862#issuecomment-390786619))

@Isammoc The impediment for [#862](https://github.com/yegor256/cactoos/issues/862) was registered successfully by @isammoc[/z](https://www.0crat.com/u/isammoc)

**Comment by 0pdd** [comment]
The puzzle `813-8130ed5b` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#862](https://github.com/yegor256/cactoos/issues/862) is now out of scope
