### ISSUE TITLE
Implement a new scalar: MultiplicationOf 

### ISSUE THREAD

**Issue by proshin-roman** [yegor256/cactoos#864]
As we already have [SumOf](https://github.com/yegor256/cactoos/blob/635ff72b524f88a76f7d14100d9b977fc60aeec1/src/main/java/org/cactoos/scalar/SumOf.java) class, why shouldn't we have all math operations implemented as scalars? Substraction can be done via sum, so we just need two new classes:

**TODO:**
- implement a new scalar MultiplicationOf that does multiplication of input parameters
- implement a new scalar DivisionOf that receives two arguments

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @proshin-roman[/z](https://www.0crat.com/u/proshin-roman)

**Comment by llorllale** [comment]
@0crat assign @Iprogrammerr

**Comment by 0crat** [comment]
> @0crat assign @Iprogrammerr ([here](https://github.com/yegor256/cactoos/issues/864#issuecomment-446028146))

@llorllale The job [#864](https://github.com/yegor256/cactoos/issues/864) assigned to @iprogrammerr[/z](https://www.0crat.com/u/iprogrammerr), here is [why](https://www.0crat.com/footprint/C63314D6Z/702bf9d9-a7e1-4583-bfc1-0ff6b660cd84); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); @iprogrammerr[/z](https://www.0crat.com/u/iprogrammerr) is not a member of this project yet, but they can request to join, as [§1](http://www.zerocracy.com/policy.html#1) explains; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
The job [#864](https://github.com/yegor256/cactoos/issues/864) assigned to @tomascury[/z](https://www.0crat.com/u/tomascury), here is [why](https://www.0crat.com/footprint/C63314D6Z/4181917a-f8e9-42d7-92ae-04d18c6e36dc); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by tomascury** [comment]
@0crat done in 7152ee3ef3df70a803a5577d895d20a09fb3eb11

**Comment by 0crat** [comment]
> @0crat done in 7152ee3ef3df70a803a5577d895d20a09fb3eb11 ([here](https://github.com/yegor256/cactoos/issues/864#issuecomment-462090750))

@tomascury Can't understand "done", try one of these:
  - `assign` Assign a performer to this issue
  - `boost` Set a boost for the job
  - `continue` Remove a job's impediment
  - `hello` Just say hello
  - `in` Register this issue in scope (WBS)
  - `out` Close the order and remove this job from scope
  - `pay` Pay a user some extra cash
  - `quality` Review a task
  - `resign` Resign from this issue
  - `status` Check the status of the job
  - `version` Print current version of the bot
  - `wait` Register an impediment for a job

**Comment by tomascury** [comment]
@llorllale done in 7152ee3ef3df70a803a5577d895d20a09fb3eb11

**Comment by llorllale** [comment]
@tomascury that's right

@proshin-roman can we close this? (merged in PR #973)

**Comment by 0crat** [comment]
Job was finished in 46 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#864](https://github.com/yegor256/cactoos/issues/864) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @tomascury[/z](https://www.0crat.com/u/tomascury)
