### ISSUE TITLE
TextHasString describeMismatch is not implemented

### ISSUE THREAD

**Issue by g4s8** [yegor256/cactoos#870]
If assertion of custom `Text` implementation failed, `TextHasString` shows object address instead of `asString()`:
```java
MatcherAssert.assertThat(
    new ReversedText(new TextOf("123")),
    new TextHasString("abc")
);
```
> java.lang.AssertionError: 
Expected: Text with "abc"
     but: was <org.cactoos.text.ReversedText@5479e3f>

to fix it `describeMismatch` method can be implemented in `TextHasString`.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@g4s8 please open an issue about this in `llorllale/cactoos-matchers`, thanks

**Comment by g4s8** [comment]
@llorllale it's working fine in llorllale/cactoos-matchers will use this dependency.
