### ISSUE TITLE
Confusing docs about unchecked exceptions decorators

### ISSUE THREAD

**Issue by neonailol** [yegor256/cactoos#871]
In the documentation of some classes, there this copied and pasted paragraph

```
 * <p>This class implements {@link Scalar}, which throws a checked
 * {@link Exception}. This may not be convenient in many cases. To make
 * it more convenient and get rid of the checked exception you can
 * use {@link UncheckedScalar} or {@link IoCheckedScalar} decorators.</p>
```

Which tells that to get rid of checked exception I can use `IoCheckedScalar` class,
but `IoCheckedScalar` throws a checked `IOException`, so maybe this text should be rephrased

Some examples:
https://github.com/yegor256/cactoos/blob/80ed872cec2c9e9a5e3e1738b97d71fa97ed6e11/src/main/java/org/cactoos/scalar/HighestOf.java#L46-L49
https://github.com/yegor256/cactoos/blob/80ed872cec2c9e9a5e3e1738b97d71fa97ed6e11/src/main/java/org/cactoos/scalar/Equals.java#L33-L36
https://github.com/yegor256/cactoos/blob/80ed872cec2c9e9a5e3e1738b97d71fa97ed6e11/src/main/java/org/cactoos/scalar/And.java#L69-L72

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@neonailol[/z](https://www.0crat.com/u/neonailol) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!
