### ISSUE TITLE
Iso class should be Scalar or Constant

### ISSUE THREAD

**Issue by neonailol** [yegor256/cactoos#872]
https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/time/Iso.java

This class inconsistent with library code, and probably should implement `Scalar`

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@neonailol[/z](https://www.0crat.com/u/neonailol) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@neonailol let's make it a `Scalar<DateTimeFormatter` and also fix its class-level javadoc

**Comment by DanielPalafox** [comment]
@0crat wait for reviewer

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/872#issuecomment-391030402))

@llorllale Job [#872](https://github.com/yegor256/cactoos/issues/872) is already in scope

**Comment by 0crat** [comment]
> @0crat wait for reviewer ([here](https://github.com/yegor256/cactoos/issues/872#issuecomment-403668739))

@DanielPalafox The impediment for [#872](https://github.com/yegor256/cactoos/issues/872) was registered successfully by @danielpalafox[/z](https://www.0crat.com/u/danielpalafox)

**Comment by neonailol** [comment]
@llorllale yes, this issue can be closed

**Comment by 0crat** [comment]
The project doesn't have enough funds, can't make a payment

**Comment by 0crat** [comment]
The job [#872](https://github.com/yegor256/cactoos/issues/872) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @danielpalafox[/z](https://www.0crat.com/u/danielpalafox)

**Comment by 0crat** [comment]
The project doesn't have enough funds, can't make a payment
