### ISSUE TITLE
Cactoos version 0.33 contains 0.32 source code

### ISSUE THREAD

**Issue by Vatavuk** [yegor256/cactoos#873]
It looks like newly released version 0.33 contains 0.32 source code. I've downloaded code from maven and as zip file, there are no 0.33 changes there...

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@Vatavuk that's because `0.33` was about *removing* code (matchers are now in project llorllale/cactoos-matchers), not about adding anything new.

cactoos-matchers is now just a test dependency for cactoos

**Comment by Vatavuk** [comment]
@llorllale I'm total idiot, I was looking at commits since master.
