### ISSUE TITLE
CollectionEnvelope.java:39-42: Implement methods equals...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#881]
The puzzle `844-c2e67e6a` from #844 has to be resolved:

https://github.com/yegor256/cactoos/blob/7775a67e7a6ce47f8a6a54309a21221147cb0328/src/main/java/org/cactoos/collection/CollectionEnvelope.java#L39-L42

The puzzle was created by Roman Proshin on 13-May-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#881](https://github.com/yegor256/cactoos/issues/881) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#881](https://github.com/yegor256/cactoos/issues/881) assigned to @vatavuk[/z](https://www.0crat.com/u/vatavuk), here is [why](https://www.0crat.com/footprint/C63314D6Z/1381569500); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html)

**Comment by Vatavuk** [comment]
@0crat wait for reviewer

**Comment by 0crat** [comment]
> @0crat wait for reviewer ([here](https://github.com/yegor256/cactoos/issues/881#issuecomment-390954000))

@Vatavuk The impediment for [#881](https://github.com/yegor256/cactoos/issues/881) was registered successfully by @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0pdd** [comment]
The puzzle `844-c2e67e6a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#904](https://github.com/yegor256/cactoos/issues/904) is still not solved.

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @vatavuk[/z](https://www.0crat.com/u/vatavuk), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#881](https://github.com/yegor256/cactoos/issues/881) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)

**Comment by 0pdd** [comment]
@0pdd the only puzzle [#904](https://github.com/yegor256/cactoos/issues/904) is solved here.
