### ISSUE TITLE
SyncIteratorTest takes way too long to execute

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#889]
On travis, the test takes 2 minutes 30 seconds:
```
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 148.965 sec - in org.cactoos.iterator.SyncIteratorTest
```

On my computer, it takes 20 seconds more or less.

This is way too much time lost waiting for tests to be executed.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@victornoel on mine it only takes about ~6.5 seconds.

Still though, your problem is most likely in `correctValuesForConcurrentNextNext` and `correctValuesForConcurrentNextHasNext`. I don't know how they determined that `5000` was an acceptable number of iterations for these tests.

**Comment by victornoel** [comment]
@llorllale I have a typical recent 4 core (or hyperthread...) computer

If it's not the case for others than it's ok, maybe you could just reduce a bit the number of loops? I don't think it makes a concurrent test more reliable to do more loops in general :)

**Comment by llorllale** [comment]
@victornoel I'm closing this for now - feel free to open a new issue for it again if it's still a problem for you.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#889` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
