### ISSUE TITLE
findbugs should be enabled in qulice

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#891]
Findbugs is disabled in qulice. When enable it shows a number of potential bugs that should better be fixed.

We should reenable it and fix all the problems instead of ignoring them.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/891#issuecomment-390422010))

@llorllale Job [#891](https://github.com/yegor256/cactoos/issues/891) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
The job [#891](https://github.com/yegor256/cactoos/issues/891) assigned to @jonathanihm[/z](https://www.0crat.com/u/jonathanihm), here is [why](https://www.0crat.com/footprint/C63314D6Z/1810151633); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment]
@jonathanihm[/z](https://www.0crat.com/u/jonathanihm) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment]
The user @jonathanihm[/z](https://www.0crat.com/u/jonathanihm) resigned from [#891](https://github.com/yegor256/cactoos/issues/891), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by paulodamaso** [comment]
@llorllale As a suggestion, maybe it's a better idea to update qulice version in this issue too. There are some dangerous code in cactoos that would fail in new qulice version checks (for example, https://pmd.github.io/latest/pmd_rules_java_performance.html#avoidfilestream).

**Comment by 0crat** [comment]
The job [#891](https://github.com/yegor256/cactoos/issues/891) assigned to @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov), here is [why](https://www.0crat.com/footprint/C63314D6Z/bd9419c4-2d6b-493d-aa65-c810fcdaecf3); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by ilyakharlamov** [comment]
@victornoel ping, everything is merged

**Comment by victornoel** [comment]
@llorllale so we are happy with not fixing all those issues? If you are good with it I will close this, if not I would expect some `@todo` to be added to the code base for this issue to be closed :)

**Comment by llorllale** [comment]
@victornoel 

Huh, I should've looked at them myself back then. Below are the warnings - there is only one very minor issue that interests me. Do you see more?

```
[WARNING] FindBugs: M D Eq: org.cactoos.map.MapEnvelope.equals(Object) is unusual  At MapEnvelope.java:[line 148]
[WARNING] FindBugs: M D Eq: org.cactoos.text.TextEnvelope.equals(Object) is unusual  At TextEnvelope.java:[line 80]
[WARNING] FindBugs: M D Eq: org.cactoos.collection.CollectionEnvelope.equals(Object) is unusual  At CollectionEnvelope.java:[line 150]
[WARNING] FindBugs: M D INT: Vacuous ixor operation on hash in org.cactoos.map.MapEntry.hashCode()  At MapEntry.java:[line 104]                //FIXME
[WARNING] FindBugs: L B It: org.cactoos.iterator.Endless.next() can't throw NoSuchElementException  At Endless.java:[line 77]
[WARNING] FindBugs: M B Se: Class org.cactoos.scalar.NumberOf defines non-transient non-serializable instance field lnum  In NumberOf.java
[WARNING] FindBugs: M B Se: Class org.cactoos.scalar.NumberOf defines non-transient non-serializable instance field inum  In NumberOf.java
[WARNING] FindBugs: M B Se: Class org.cactoos.scalar.NumberOf defines non-transient non-serializable instance field fnum  In NumberOf.java
[WARNING] FindBugs: M B Se: Class org.cactoos.scalar.NumberOf defines non-transient non-serializable instance field dnum  In NumberOf.java
[WARNING] FindBugs: M B Se: org.cactoos.scalar.Sticky stored into non-transient field NumberOf.lnum  At NumberOf.java:[line 92]
[WARNING] FindBugs: M B Se: org.cactoos.scalar.Sticky stored into non-transient field NumberOf.inum  At NumberOf.java:[line 95]
[WARNING] FindBugs: M B Se: org.cactoos.scalar.Sticky stored into non-transient field NumberOf.fnum  At NumberOf.java:[line 98]
[WARNING] FindBugs: M B Se: org.cactoos.scalar.Sticky stored into non-transient field NumberOf.dnum  At NumberOf.java:[line 101]
[WARNING] FindBugs: L D UwF: Cycled.iterator not initialized in constructor and dereferenced in org.cactoos.iterator.Cycled.next()  At Cycled.java:[line 73]
```

**Comment by victornoel** [comment]
@llorllale yep, maybe there is something to do for the last one, the rest is indeed not real problems. Maybe the transient one could also be fixed just to reduce some noise (even though this whole transient thing is a bit of a trap since if you just mark a field transient, it doesn't make your class serialized still).

**Comment by llorllale** [comment]
@victornoel you can open a new issue and earn sweet ZC points

Let's close this one.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
Job [#891](https://github.com/yegor256/cactoos/issues/891) is not in the agenda of @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov), can't inspect

**Comment by 0crat** [comment]
The job [#891](https://github.com/yegor256/cactoos/issues/891) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
