### ISSUE TITLE
Multiple return statements in MapEnvelope

### ISSUE THREAD

**Issue by Vatavuk** [yegor256/cactoos#892]
`Equals` method of `MapEnvelope` class has 5 return statements, there should be only one.

https://www.yegor256.com/2015/08/18/multiple-return-statements-in-oop.html

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/892#issuecomment-390671883))

@llorllale Job [#892](https://github.com/yegor256/cactoos/issues/892) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by 0crat** [comment]
The job [#892](https://github.com/yegor256/cactoos/issues/892) assigned to @butenkos[/z](https://www.0crat.com/u/butenkos), here is [why](https://www.0crat.com/footprint/C63314D6Z/1830018194); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by butenkos** [comment]
@Vatavuk the pull request was merged, kindly close the ticket. Thank you

**Comment by 0crat** [comment]
@elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova) please review this job completed by @butenkos[/z](https://www.0crat.com/u/butenkos), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#892](https://github.com/yegor256/cactoos/issues/892) is now out of scope

**Comment by elenavolokhova** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +38 point(s) just awarded to @butenkos[/z](https://www.0crat.com/u/butenkos)

**Comment by 0crat** [comment]
Quality review completed: +8 point(s) just awarded to @elenavolokhova[/z](https://www.0crat.com/u/elenavolokhova)
