### ISSUE TITLE
Simplify usage of ScalarWithFallback

### ISSUE THREAD

**Issue by Vatavuk** [yegor256/cactoos#895]
Currently, in order to use `ScalarWithFallback` user needs to provide follow up function as well as an iterable for fallback options.

I propose to add following ctors (just like those we have in `FuncWithFallback`) to simplify usage:
```java
ScalarWithFallback(final Scalar<X> scalar, final FallbackFrom<X> fbk)
ScalarWithFallback(final Scalar<X> scalar, final FallbackFrom<X> fbk, final Func<X, X> flw)
ScalarWithFallback(final Scalar<X> scalar, final Iterable<FallbackFrom<X>> fbks)
```

**Comment by llorllale** [comment]
@Vatavuk let's modify your first one:

```java
ScalarWithFallback(final Scalar<X> scalar, final FallbackFrom<X>... fbks)
```

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/895#issuecomment-390683472))

@llorllale Job [#895](https://github.com/yegor256/cactoos/issues/895) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @vatavuk[/z](https://www.0crat.com/u/vatavuk)

**Comment by Vatavuk** [comment]
@llorllale unfortunately we cannot add varargs due to collision with followup function. Code won't compile. See https://github.com/yegor256/cactoos/pull/856#pullrequestreview-119371145

**Comment by llorllale** [comment]
@Vatavuk I see, OK

**Comment by 0crat** [comment]
The job [#895](https://github.com/yegor256/cactoos/issues/895) assigned to @scratchboom[/z](https://www.0crat.com/u/scratchboom), here is [why](https://www.0crat.com/footprint/C63314D6Z/9e3b940e-cfc0-4d04-a365-a9a42e2e25aa); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by Vatavuk** [comment]
@scratchboom That is just a follow up function that will be executed after the main functionallity from ScalarWihFallback is executed.

**Comment by scratchboom** [comment]
@Vatavuk flw should be called only for main flow or for fallback flow too?

Should I store flw as a field of ScalarWithFallback and call it in on result variable in org.cactoos.scalar.ScalarWithFallback#value?

**Comment by llorllale** [comment]
@scratchboom @Vatavuk please see #965 - we removed these "follow" Funcs

**Comment by llorllale** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/895#issuecomment-474141230))

@llorllale The user @scratchboom[/z](https://www.0crat.com/u/scratchboom) resigned from [#895](https://github.com/yegor256/cactoos/issues/895), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#895](https://github.com/yegor256/cactoos/issues/895) assigned to @borysfan[/z](https://www.0crat.com/u/borysfan), here is [why](https://www.0crat.com/footprint/C63314D6Z/99eb6140-a9f2-4c83-accf-0fad29a36d61); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The architect of the project has changed; @llorllale[/z](https://www.0crat.com/u/llorllale) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by andreoss** [comment]
@paulodamaso 
`FallbackFrom` [1] seems to be in violation of  "no public methods without `@Override`" principle (Maybe it was indented as a "smart" class?). 
The reason for that is to provide an ability to rank an exception by its inheritance level.
This would be unnecessary if the nearest matching exception were always selected, in accordance with the semantics of catch-blocks, execution of which depends on their order [2].

Like so, this renders `FallbackFrom` unnecessary
```java
ScalarWithFallback(
   final Scalar<X> scalar, 
   final Map.Entry<Class<? extends Throwable>, Func<Throwable, X>>... fbks
)
```

Alternatively, a special interface can be extracted
```java
interface Fallback extends Func<Throwable, X> {
      int support(Class<? exdend Throwable> exception)
}
```

[1]: https://github.com/yegor256/cactoos/blob/88bffb47f35271909eb0b0b7f663464c6c4a5527/src/main/java/org/cactoos/scalar/FallbackFrom.java#L85

[2]: https://docs.oracle.com/javase/specs/jls/se14/html/jls-11.html#jls-11.3

**Comment by victornoel** [comment]
@andreoss see also #1170

**Comment by 0crat** [comment]
The architect of the project has changed; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is not at this role anymore; @victornoel[/z](https://www.0crat.com/u/victornoel) is the architect now

**Comment by victornoel** [comment]
@Vatavuk @andreoss I propose this, WDYT?

```java
ScalarWithFallback(
   final Scalar<X> scalar, 
   final Fallback<X, ?>... fbks
)
interface Fallback<X> extends Func<Throwable, X> {
      boolean support(Throwable exception);
}
```

With the implementation iterating in order through the fallbacks available and use the first one that supports the exception.

with one current implementation for `Fallback` being `FallbackFrom` as it is currently defined (maybe it could be moved as an inner static class of `Fallback` too). Other implementation could be based on the message of the execution, or whatever.

**Comment by victornoel** [comment]
@0crat in

**Comment by 0crat** [comment]
The job [#895](https://github.com/yegor256/cactoos/issues/895) assigned to @aivinog1[/z](https://www.0crat.com/u/aivinog1), here is [why](https://www.0crat.com/footprint/C63314D6Z/b254e017-6c86-4e44-b6e1-1f636a4f4d34); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/895#issuecomment-699608731))

@victornoel The user @aivinog1[/z](https://www.0crat.com/u/aivinog1) resigned from [#895](https://github.com/yegor256/cactoos/issues/895), please stop working. Reason for job resignation: Order was cancelled

**Comment by victornoel** [comment]
@0crat status

**Comment by 0crat** [comment]
> @0crat status ([here](https://github.com/yegor256/cactoos/issues/895#issuecomment-711167092))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#895](https://github.com/yegor256/cactoos/issues/895) is [in scope](http://www.zerocracy.com/policy.html#14) for 1mon
  * The role is `DEV`
  * The job is assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) for [17days](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 30 minutes/points
  * These users are banned and won't be assigned:
    * @vatavuk[/z](https://www.0crat.com/u/vatavuk): This user reported the ticket
    * @aivinog1[/z](https://www.0crat.com/u/aivinog1): User was resigned from the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Ayegor256%2Fcactoos%23895%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/895#issuecomment-751455681))

@victornoel The user @fabriciofx[/z](https://www.0crat.com/u/fabriciofx) resigned from [#895](https://github.com/yegor256/cactoos/issues/895), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
The job [#895](https://github.com/yegor256/cactoos/issues/895) assigned to @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), here is [why](https://www.0crat.com/footprint/C63314D6Z/7e55ef07-d191-44b9-bbf6-c579da865bb4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@baudoliver7 thx

**Comment by baudoliver7** [comment]
@victornoel Happy to contribute !

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good
