### ISSUE TITLE
Simplify usage of fallback functionality

### ISSUE THREAD

**Issue by Vatavuk** [yegor256/cactoos#896]
Let's imagine a case when we want to handle specific types of exceptions and map them to our custom exception object.
This could be done using `CheckedScalar` and `ScalarWithFallback`:
```java
public T safeMethod() throws CustomCheckedException {
    return new CheckedScalar<>(
        new ScalarWithFallback<>(
            () -> output.value(),
            new IterableOf<>(
                new FallbackFrom<>(
                    IOException.class,
                    exp -> {
                        // handle exception...
                        throw new CustomCheckedException(exp); 
                    }
                ),
                new FallbackFrom<>(
                    ThirdPartyException.class,
                    exp -> {
                        // handle exception...
                        throw new CustomCheckedException(exp);
                    }
                )
            )
        ),
        CustomCheckedException::new
    ).value();
}
```
We have to declare wrapping of exceptions 3 times. One for each fallback option and one in `CheckedScalar` in order to be able to compile the method with throws clause.

I propose to add new ctor to `FallbackFrom` which will take `proc<X>` and rethrow exception.
Something like:
```java
public FallbackFrom(final Class<? extends Throwable> exp, final Proc<Throwable> proc) {
    this(exp, (Throwable input) -> {
        proc.exec(input);
        throw new Exception(input);
    });
}
```
In that way we could simplify the above example and decouple `ScalarWithFallback` 
from wrapping of exceptions. 
```java
public T safeMethod() throws CustomCheckedException {
    return new CheckedScalar<>(
        new ScalarWithFallback<>(
            () -> output.value(),
            new IterableOf<>(
                new FallbackFrom<>(
                    IOException.class,
                    exp -> {
                        // handle exception...
                    }
                ),
                new FallbackFrom<>(
                    ThirdPartyException.class,
                    exp -> {
                        // handle exception...
                    }
                )
            )
        ),
        CustomCheckedException::new
    ).value();
}
```

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@Vatavuk sounds like you don't want to "fallback" at all - you want side effects (do something on error condition) and then rethrow the (wrapped) exception. 

Based on that I think some other than `*Fallback` is what you need (I'm reminded of #825).

**Comment by llorllale** [comment]
@Vatavuk ping

**Comment by Vatavuk** [comment]
@llorllale I agree, this functionality does not belong to `*Fallback` classes.
I will close this issue and reopen a new if I come up with a better approach to this.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@42035a22-4829-4612-bc0a-71dc95f86d80, thread: AsyncFlush-5
com.zerocracy.farm.sync.SyncProject[77] java.lang.IllegalStateException: Failed to acquire "blanks/vatavuk.xml" in "PMO" in 2min: c206822b11f7/5min/0/6/true/false by QuartzScheduler_Worker-1
```

[0.22.23](https://github.com/zerocracy/farm): CID: [1720815002](https://www.0crat.com/C63314D6Z/1720815002), Type: "Close job", Author: "vatavuk"

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#896` is not assigned, can't get performer
