### ISSUE TITLE
Replace org.cactoos.Func to Java 8 analog

### ISSUE THREAD

**Issue by englishman** [yegor256/cactoos#9]
Replace hand-made `org.cactoos.Func` using everywhere to standard Java 8 `java.util.function.Function` interface.

**Comment by 0crat** [comment]
@englishman I'm not managing this repo, remove the [webhook](https://github.com/yegor256/cactoos/settings/hooks) or contact me in [Slack](http://www.zerocracy.com) //cc @yegor256

**Comment by yegor256** [comment]
@englishman I agree, can you help with a pull request? Also, pay attention to #15

**Comment by yegor256** [comment]
@englishman stop, I disagree. They don't have `throws Exception`.

**Comment by englishman** [comment]
@yegor256 I can do this but... there was a suggestion to use only unchecked exceptions anywhere. WDYT? If you are agree to use only  unchecked exceptions in Cactoos then we can use Java 8 Function

**Comment by yegor256** [comment]
@englishman yes, we can use them, but what about hundreds of JDK methods that still throw `IOException` and others?

**Comment by englishman** [comment]
@yegor256 can't we simply wrap them with JDK `RuntimeException`?

**Comment by yegor256** [comment]
@englishman we can, but the code becomes verbose. I'm talking about the code in applications.
