### ISSUE TITLE
UrlAsString and StringAsUrl

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#90]
Let's create two new classes, which will replace `URLEncoder` and `URLDecoder` from JDK. We will still use JDK, but these wrappers will be very helpful. At least they won't throw checked exceptions.

**Comment by yegor256** [comment]
@fabriciofx interested in contributing?

**Comment by fabriciofx** [comment]
@yegor256 Of course! 😄

**Comment by fabriciofx** [comment]
@yegor256 Should `StringAsUrl` converts a `String` into a `URL`, or just a `String` to a `String` coded as url? The same to `UrlAsString`: a `String` to `URL`?

**Comment by yegor256** [comment]
@fabriciofx I think we need this:

```
assert new UrlAsString("%D0%B0%20%D1%8F").asValue().equals("а я");
assert new StringAsUrl("друг").asValue().equals("%D0%B4%D1%80%D1%83%D0%B3");
```

**Comment by yegor256** [comment]
@fabriciofx thanks!
