### ISSUE TITLE
ListIterator instances returned must be null-free

### ISSUE THREAD

**Issue by paulodamaso** [yegor256/cactoos#901]
In `ListNotNulls`, there are two methods that returns `ListIterators` of the list decorated; these methods return simple `ListIterator`s (which accepts `null` values) when they should be returning a `ListIterator` type or `Iterator` implementor which does not accept `null` values. This could be achieved by:
- Add `ListIteratorNotNulls` class, which implements `IteratorNotNulls`, and use this type in that methods returns;
- Wrap returned `ListIterator`s in with an `IteratorNotNull`.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@paulodamaso it is up to the users to wrap iterables/iterators in `*NoNulls`.

What I believe we should definitely be doing though is wrapping those iterators with `org.cactoos.list.ListIterator` in order to make the immutable.

**Comment by paulodamaso** [comment]
@llorllale But shouldn't a `ListIterator` returned by a `ListNotNulls` be prohibited to return `null` values? Remember, it is representing a null-free list, so we must guarantee that this ListIterator won't have any nulls, and we could do this by returning an `InteratornotNull` implementation.
About wrapping them in `org.cactoos.list.ListIterator` and make them immutable, I totally agree with you.

**Comment by llorllale** [comment]
@paulodamaso gotcha regarding your point about not nulls. Let's do that as well.

**Comment by llorllale** [comment]
@paulodamaso so to be clear, there are two parts to this:

* `ListNoNulls` should ensure that the iterators it returns also do not allow nulls
* `ListNoNulls` should also return immutable iterators

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/901#issuecomment-391702373))

@llorllale Job [#901](https://github.com/yegor256/cactoos/issues/901) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
The job [#901](https://github.com/yegor256/cactoos/issues/901) assigned to @danielpalafox[/z](https://www.0crat.com/u/danielpalafox), here is [why](https://www.0crat.com/footprint/C63314D6Z/1851840263); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by DanielPalafox** [comment]
@0crat wait for reviewer

**Comment by 0crat** [comment]
> @0crat wait for reviewer ([here](https://github.com/yegor256/cactoos/issues/901#issuecomment-404753643))

@DanielPalafox The impediment for [#901](https://github.com/yegor256/cactoos/issues/901) was registered successfully by @danielpalafox[/z](https://www.0crat.com/u/danielpalafox)

**Comment by llorllale** [comment]
@0crat refuse

**Comment by 0crat** [comment]
The job [#901](https://github.com/yegor256/cactoos/issues/901) assigned to @tomascury[/z](https://www.0crat.com/u/tomascury), here is [why](https://www.0crat.com/footprint/C63314D6Z/b9540821-2916-490f-a188-c5eb4f363bca); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by tomascury** [comment]
> @paulodamaso so to be clear, there are two parts to this:
> 
> * `ListNoNulls` should ensure that the iterators it returns also do not allow nulls
> * `ListNoNulls` should also return immutable iterators

Class name was changed to `NoNulls` in be02845a55f191007cd60770a455b59d7320446d

**Comment by tomascury** [comment]
@llorllale it is done in https://github.com/yegor256/cactoos/pull/1071

**Comment by tomascury** [comment]
@0crat wait

**Comment by 0crat** [comment]
> @0crat wait  ([here](https://github.com/yegor256/cactoos/issues/901#issuecomment-464434880))

@tomascury The impediment for [#901](https://github.com/yegor256/cactoos/issues/901) was registered successfully by @tomascury[/z](https://www.0crat.com/u/tomascury)

**Comment by tomascury** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/901#issuecomment-466767679))

@tomascury The user @tomascury[/z](https://www.0crat.com/u/tomascury) resigned from [#901](https://github.com/yegor256/cactoos/issues/901), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @tomascury[/z](https://www.0crat.com/u/tomascury)

**Comment by 0crat** [comment]
The job [#901](https://github.com/yegor256/cactoos/issues/901) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/1fa07d81-8299-41db-8179-7e4234d8050f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #1078 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #1078 to be merged ([here](https://github.com/yegor256/cactoos/issues/901#issuecomment-468942928))

@victornoel The impediment for [#901](https://github.com/yegor256/cactoos/issues/901) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@paulodamaso the PR was merged, I think this can be closed :)

**Comment by victornoel** [comment]
@paulodamaso ping?

**Comment by victornoel** [comment]
@llorllale any way to get this closed, @paulodamaso doesn't seem to be responding :)

**Comment by llorllale** [comment]
@paulodamaso closed because PR #1078 was merged

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#901](https://github.com/yegor256/cactoos/issues/901) is now out of scope

**Comment by sereshqua** [comment]
quality good

**Comment by victornoel** [comment]
@sereshqua you need to tell that to 0crat (`@0crat quality good`)

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/cactoos/issues/901#issuecomment-475600737); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)
