### ISSUE TITLE
CollectionEnvelope.java:42-48: CollectionEnvelope equals...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#904]
The puzzle `881-d152950a` from #881 has to be resolved:

https://github.com/yegor256/cactoos/blob/c6ca6d183ee5d0ca7dd76701231333af611a6439/src/main/java/org/cactoos/collection/CollectionEnvelope.java#L42-L48

The puzzle was created by rultor on 04-Jun-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#904](https://github.com/yegor256/cactoos/issues/904) is now in scope, role is `DEV`

**Comment by dfrau32** [comment]
@0crat resign

**Comment by 0crat** [comment]
> @0crat resign  ([here](https://github.com/yegor256/cactoos/issues/904#issuecomment-405080585))

@dfrau32 The user @dfrau32[/z](https://www.0crat.com/u/dfrau32) resigned from [#904](https://github.com/yegor256/cactoos/issues/904), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @dfrau32[/z](https://www.0crat.com/u/dfrau32)

**Comment by 0crat** [comment]
The job [#904](https://github.com/yegor256/cactoos/issues/904) assigned to @scratchboom[/z](https://www.0crat.com/u/scratchboom), here is [why](https://www.0crat.com/footprint/C63314D6Z/2b9f4a3f-098b-4a29-be56-fa386ae34a11); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
The puzzle `881-d152950a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#904](https://github.com/yegor256/cactoos/issues/904) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @scratchboom[/z](https://www.0crat.com/u/scratchboom)
