### ISSUE TITLE
Ctor for UpperText and LowerText

### ISSUE THREAD

**Issue by llorllale** [yegor256/cactoos#907]
Let's add a ctor to `UpperText` and to `LowerText` that accepts a String.

**Comment by llorllale** [comment]
Fixed in d13c9cc8108c5aee1845eb6c23a5d2a5c916f5d9

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#907` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
