### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by llorllale** [yegor256/cactoos#908]
@yegor256 the `README` has a date listed for the release of `1.0`. Where is the roadmap that leads to this release?

**Comment by llorllale** [comment]
@yegor256 ping

**Comment by 0crat** [comment]
The job [#908](https://github.com/yegor256/cactoos/issues/908) assigned to @yegor256[/z](https://www.0crat.com/u/yegor256), here is [why](https://www.0crat.com/footprint/C63314D6Z/1701931307); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @yegor256[/z](https://www.0crat.com/u/yegor256) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#908` already assigned to @yegor256, can't assign to @yegor256

**Comment by yegor256** [comment]
@llorllale we don't have such a roadmap. Feel free to create one.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) not enough funds available in the project, can't set budget of job [#908](https://github.com/yegor256/cactoos/issues/908), see [§21](http://www.zerocracy.com/policy.html#21); @llorllale[/z](https://www.0crat.com/u/llorllale) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by llorllale** [comment]
@yegor256 I created milestone [`1.0'](https://github.com/yegor256/cactoos/milestone/1) for our initial release. `1.0` will be released once those issues - and all puzzles derived from them - are complete.

I have updated the `README` with a link pointing to the milestone.

**Comment by yegor256** [comment]
@llorllale cool!

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) resigned from [#908](https://github.com/yegor256/cactoos/issues/908), since the job is not in scope anymore

**Comment by 0crat** [comment]
The job [#908](https://github.com/yegor256/cactoos/issues/908) is now out of scope
