### ISSUE TITLE
RetryFunc with timeout between attempts

### ISSUE THREAD

**Issue by neonailol** [yegor256/cactoos#909]
As the title says, it would be nice if RetryFunc had an option to sleep for a certain amount of time, between attempts, using, for example, [TimeUnit](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/TimeUnit.html) from JDK. Or maybe provide another abstraction to do this.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@neonailol[/z](https://www.0crat.com/u/neonailol) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@neonailol let's have it accept [`Duration`](https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html), WDYT?

**Comment by neonailol** [comment]
@llorllale Duration is also a good option, just keep in mind that it can have a negative value.

**Comment by llorllale** [comment]
@neonailol right

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/909#issuecomment-397430922))

@llorllale Job [#909](https://github.com/yegor256/cactoos/issues/909) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment]
The job [#909](https://github.com/yegor256/cactoos/issues/909) assigned to @longstone[/z](https://www.0crat.com/u/longstone), here is [why](https://www.0crat.com/footprint/C63314D6Z/2644636b-911c-4b42-8cab-d2dc2d117401); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by longstone** [comment]
hi @llorllale , `RetryFunc` was renamed to `Func`, but I'm missing the `@puzzle` in the code, 
Am I missing something?

**Comment by llorllale** [comment]
@longstone this task was opened by @neonailol - it's not a puzzle

**Comment by 0pdd** [comment]
@neonailol the puzzle [#1088](https://github.com/yegor256/cactoos/issues/1088) is still not solved.

**Comment by longstone** [comment]
@neonailol as there is now a Option zo wait between attempt, i think this is resolved.

**Comment by longstone** [comment]
@llorllale & @neonailol push

**Comment by llorllale** [comment]
@neonailol PR #1079 was merged. Closing due to unresponsiveness.

**Comment by 0crat** [comment]
Job [#909](https://github.com/yegor256/cactoos/issues/909) is not in the agenda of @longstone[/z](https://www.0crat.com/u/longstone), can't inspect

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @longstone[/z](https://www.0crat.com/u/longstone), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#909](https://github.com/yegor256/cactoos/issues/909) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @longstone[/z](https://www.0crat.com/u/longstone)

**Comment by 0pdd** [comment]
@neonailol the only puzzle [#1088](https://github.com/yegor256/cactoos/issues/1088) is solved here.
