### ISSUE TITLE
Consolidate LengthOf classes

### ISSUE THREAD

**Issue by neonailol** [yegor256/cactoos#910]
As the title says, why there are multiple LengthOf classes when one of the points of elegant objects is to provide rich constructors for the object? Each current implementation of LengthOf can be merged into a single class, and I don't see why it should not be that way.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@neonailol[/z](https://www.0crat.com/u/neonailol) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@neonailol where would we put this `LengthOf`?

**Comment by neonailol** [comment]
@llorllale all of the implementations are `NumberEnvelope` so probably it belongs to `scalar`, but I think numbers should be in their own package

**Comment by llorllale** [comment]
@neonailol agreed

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/910#issuecomment-397646312))

@llorllale Job [#910](https://github.com/yegor256/cactoos/issues/910) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol)

**Comment by llorllale** [comment]
@neonailol FYI, when I agreed [here](https://github.com/yegor256/cactoos/issues/910#issuecomment-397646288) I meant it probably should belong to `org.cactoos.scalar`, not to create a new package for numbers.

**Comment by neonailol** [comment]
@llorllale I am ok with that

**Comment by 0crat** [comment]
The job [#910](https://github.com/yegor256/cactoos/issues/910) assigned to @dgroup[/z](https://www.0crat.com/u/dgroup), here is [why](https://www.0crat.com/footprint/C63314D6Z/9ddc4cb4-d900-4c57-8a10-1a0b8dde14ed); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by dgroup** [comment]
@0crat wait as #987 raised.

**Comment by 0crat** [comment]
> @0crat wait as #987 raised. ([here](https://github.com/yegor256/cactoos/issues/910#issuecomment-451146685))

@dgroup The impediment for [#910](https://github.com/yegor256/cactoos/issues/910) was registered successfully by @dgroup[/z](https://www.0crat.com/u/dgroup)

**Comment by dgroup** [comment]
@neonailol, the PR was merged.
Could you please check the results? 
Can we close the ticket?

**Comment by neonailol** [comment]
@dgroup yes, this issue can be closed

**Comment by dgroup** [comment]
@llorllale please close the ticket as requestor approved the fix.

**Comment by 0crat** [comment]
The job [#910](https://github.com/yegor256/cactoos/issues/910) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @dgroup[/z](https://www.0crat.com/u/dgroup)
