### ISSUE TITLE
Substitute all usages of Iterator with usage of Iterable in ctors

### ISSUE THREAD

**Issue by svendiedrichsen** [yegor256/cactoos#911]
The discussion from #906 lead to the conclusion to avoid the usage of Iterators and replace all of their occurrences in ctors with Iterables where applicable. This aspect has also been discussed in #677 .

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@699dad38-11e0-4927-b0e8-65c95cb08d43, thread: pool-35-thread-1
com.zerocracy.farm.sync.SyncProject[70] java.lang.IllegalStateException: Failed to acquire "catalog.xml" in "PMO" in 2min: 266bf5224b6f/32min/0/2/true/false by AsyncFlush-2
```

[0.22.16](https://github.com/zerocracy/farm): Issue: yegor256/cactoos#911, Action: `opened`

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/911#issuecomment-399082089))

@llorllale Job [#911](https://github.com/yegor256/cactoos/issues/911) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @svendiedrichsen[/z](https://www.0crat.com/u/svendiedrichsen)

**Comment by 0crat** [comment]
The job [#911](https://github.com/yegor256/cactoos/issues/911) assigned to @verkhovin[/z](https://www.0crat.com/u/verkhovin), here is [why](https://www.0crat.com/footprint/C63314D6Z/8c0ad291-2db2-48f2-b939-59ee953120a2); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by verkhovin** [comment]
@llorllale does this ticket assume that I should remove all ctors with Iterator parameters as it made in #677?

**Comment by verkhovin** [comment]
@0crat wait for #1001 review

**Comment by 0crat** [comment]
> @0crat wait for #1001 review ([here](https://github.com/yegor256/cactoos/issues/911#issuecomment-453790061))

@verkhovin The impediment for [#911](https://github.com/yegor256/cactoos/issues/911) was registered successfully by @verkhovin[/z](https://www.0crat.com/u/verkhovin)

**Comment by llorllale** [comment]
@verkhovin 

> does this ticket assume that I should remove all ctors with Iterator parameters as it was made in #677?

Yes.

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/911#issuecomment-456953060))

@verkhovin The user @verkhovin[/z](https://www.0crat.com/u/verkhovin) resigned from [#911](https://github.com/yegor256/cactoos/issues/911), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @verkhovin[/z](https://www.0crat.com/u/verkhovin)

**Comment by 0crat** [comment]
The job [#911](https://github.com/yegor256/cactoos/issues/911) assigned to @mazdack[/z](https://www.0crat.com/u/mazdack), here is [why](https://www.0crat.com/footprint/C63314D6Z/e3052b1e-b1f3-4080-932c-d63c619b0160); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0pdd** [comment]
@svendiedrichsen the puzzle [#1104](https://github.com/yegor256/cactoos/issues/1104) is still not solved.

**Comment by 0pdd** [comment]
@svendiedrichsen the only puzzle [#1104](https://github.com/yegor256/cactoos/issues/1104) is solved here.

**Comment by svendiedrichsen** [comment]
@llorllale What am I expected to do here? Close the ticket?

**Comment by llorllale** [comment]
@svendiedrichsen yeah (PR #1059 merged for this)

**Comment by svendiedrichsen** [comment]
Ok, closing as PR #1059 has been merged.

**Comment by 0crat** [comment]
Job [#911](https://github.com/yegor256/cactoos/issues/911) is not in the agenda of @mazdack[/z](https://www.0crat.com/u/mazdack), can't inspect

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @mazdack[/z](https://www.0crat.com/u/mazdack), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#911](https://github.com/yegor256/cactoos/issues/911) is now out of scope

**Comment by sereshqua** [comment]
@svendiedrichsen can you please edit your [comment](https://github.com/yegor256/cactoos/issues/911#issuecomment-499783767)  that it start with the user' name it is referred to? otherwise quality is acceptable here

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @mazdack[/z](https://www.0crat.com/u/mazdack)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
