### ISSUE TITLE
Typos in the CollectionEnvelope

### ISSUE THREAD

**Issue by olenagerasimova** [yegor256/cactoos#912]
I believe there are typos in the description of each `UnsupportedOperationException` in the `CollectionEnvelope` class: exceptions messages say 
"the collection is ready only"
instead of 
"the collection is read only".

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@olenagerasimova[/z](https://www.0crat.com/u/olenagerasimova) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@olenagerasimova fixed in 92b77ed9e2d34ddec1722393c36d3659c7bd1780, thanks!
