### ISSUE TITLE
Joined Input

### ISSUE THREAD

**Issue by llorllale** [yegor256/cactoos#919]
`cactoos-http` works mostly at the byte-stream level and needs an `Input` analogous to Java's [SequenceInputStream](https://docs.oracle.com/javase/8/docs/api/java/io/SequenceInputStream.html) in order to implement decorators, such as in yegor256/cactoos-http#21.

I believe we should create a new `Joined` input. 

Note: Providing an overloaded ctor for `InputStreamOf` would not reveal intention as clearly as `Joined`.

**Comment by llorllale** [comment]
Done in 63ac287f80901636bb04610850f700a2b900e9f6

**Comment by llorllale** [comment]
@rultor release, tag is `0.36`

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#919` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
