### ISSUE TITLE
equals() and hashCode() of MapEnvelope should be tolerant to nulls

### ISSUE THREAD

**Issue by butenkos** [yegor256/cactoos#922]
Methods `equals()` and `hashCode()` of abstract class `MapEnvelope` fail with `NullPointerException` when enveloped `Map` contains `null` values.
There are unit-tests covering this behaviour: test case `MapEnvelopeTest`, methods `hashCodeFailsOnNull()` and `equalFailsOnNull()`. 
Is it really a desired behaviour? A lot of `Map` implementations (including standard implementations from jdk)  support `null` keys or/and values. With the current implementation we cannot compare instances of `MapEnvelope` which incapsulate `Map`s with `null`s and store them in collections.

`equals()` and `hashCode()` of `MapEnvelope` should be tolerant to `null`s in order to be able to work correctly with enveloped `Map`s which may contain `null` keys or/and values, and to be able to be stored in collections

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@butenkos thanks, you're right.

We have `MapNoNulls` decorator that users can use if `null` is not tolerated.

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/922#issuecomment-402881189))

@llorllale Job [#922](https://github.com/yegor256/cactoos/issues/922) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @butenkos[/z](https://www.0crat.com/u/butenkos)

**Comment by 0crat** [comment]
The job [#922](https://github.com/yegor256/cactoos/issues/922) assigned to @dennis00010011b[/z](https://www.0crat.com/u/dennis00010011b), here is [why](https://www.0crat.com/footprint/C63314D6Z/4a5ef52e-4992-450e-8156-5383eb5edc20); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
The job [#922](https://github.com/yegor256/cactoos/issues/922) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/a948e16d-04de-4c52-be0b-c63afcebbc9f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/922#issuecomment-478269733))

@victornoel The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#922](https://github.com/yegor256/cactoos/issues/922), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
The job [#922](https://github.com/yegor256/cactoos/issues/922) assigned to @umbrah[/z](https://www.0crat.com/u/umbrah), here is [why](https://www.0crat.com/footprint/C63314D6Z/eed4149d-1929-4842-85b7-9631f6fbda62); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by Umbrah** [comment]
@llorllale Can we close it? PR was merged

**Comment by llorllale** [comment]
@Umbrah always as the ticket reporter first

**Comment by Umbrah** [comment]
@butenkos Can we close it?

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @umbrah[/z](https://www.0crat.com/u/umbrah), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#922](https://github.com/yegor256/cactoos/issues/922) is now out of scope

**Comment by 0crat** [comment]
Job [#922](https://github.com/yegor256/cactoos/issues/922) is not in the agenda of @umbrah[/z](https://www.0crat.com/u/umbrah), can't inspect

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @umbrah[/z](https://www.0crat.com/u/umbrah)
