### ISSUE TITLE
Sets package

### ISSUE THREAD

**Issue by neonailol** [yegor256/cactoos#923]
Currently, there are no decorators over sets in a library. Are they planned for the future?

**Comment by llorllale** [comment]
@neonailol no plans. I feel we'll likely end up removing `List` decorators in #915.

**Comment by llorllale** [comment]
@neonailol I agree with having `SetEnvelope` and `SetOf`

**Comment by victornoel** [comment]
@neonailol those classes seems to exists, I'm closing this ticket thus :)

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#923` is not assigned, can't get performer
