### ISSUE TITLE
Skipped constructors API inconsistency

### ISSUE THREAD

**Issue by neonailol** [yegor256/cactoos#930]
Skipped decorators constructors have inconsistency it parameters order, I expect that every constructor takes the first parameter to be a number elements to skip, like in `HeadOf` and `TailOf`, but in constructors, they are in wrong order, this is true for collection, iterable and iterator decorators.

https://github.com/yegor256/cactoos/blob/504649dc80f245fc656ddac3f381c7f5028a4483/src/main/java/org/cactoos/collection/Skipped.java#L45-L47

https://github.com/yegor256/cactoos/blob/504649dc80f245fc656ddac3f381c7f5028a4483/src/main/java/org/cactoos/collection/Skipped.java#L54-L56

https://github.com/yegor256/cactoos/blob/504649dc80f245fc656ddac3f381c7f5028a4483/src/main/java/org/cactoos/collection/Skipped.java#L63-L67

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@neonailol[/z](https://www.0crat.com/u/neonailol) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@0crat in

**Comment by llorllale** [comment]
@neonailol let's have the `int` arg first. WDYT?

**Comment by 0crat** [comment]
Job [#930](https://github.com/yegor256/cactoos/issues/930) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/930#issuecomment-403486779))

@llorllale Job [#930](https://github.com/yegor256/cactoos/issues/930) is already in scope

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol)

**Comment by neonailol** [comment]
@llorllale as long as it consistent across the project, I am good with that.

**Comment by 0crat** [comment]
The job [#930](https://github.com/yegor256/cactoos/issues/930) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/2549b065-6823-4ab5-8cb0-96b065fe8439); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #1092 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #1092 to be merged ([here](https://github.com/yegor256/cactoos/issues/930#issuecomment-478368103))

@victornoel The impediment for [#930](https://github.com/yegor256/cactoos/issues/930) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0pdd** [comment]
@neonailol the puzzle [#1095](https://github.com/yegor256/cactoos/issues/1095) is still not solved.

**Comment by victornoel** [comment]
@neonailol this was merged, can you close the issue?

**Comment by victornoel** [comment]
@llorllale reporter doesn't seem to respond, you think you can close it? thanks :)

**Comment by llorllale** [comment]
@neonailol PR #1092 merged. Closing this.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#930](https://github.com/yegor256/cactoos/issues/930) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0pdd** [comment]
@neonailol the only puzzle [#1095](https://github.com/yegor256/cactoos/issues/1095) is solved here.
