### ISSUE TITLE
Let's make CheckedScalar wrap runtime exceptions as well

### ISSUE THREAD

**Issue by llorllale** [yegor256/cactoos#933]
It's the behavior I expected and I don't see a reason not to.

**CC** @Vatavuk

**Comment by Vatavuk** [comment]
@llorllale Although it is uncommon to wrap `NullPointerException, IllegalStateException`  etc, I don't see any negative side to this. The plus side is that it will make user easier to transform all sorts of runtime exceptions provided by various libraries to checked ones.

**Comment by llorllale** [comment]
@Vatavuk I'm going to backtrack from this for now.

My original requirement was to wrap a specific runtime exception into a specific checked exception, not to wrap *all* exceptions. I realize I can hack a "solution" using `ScalarWithFallback` but it isn't ideal.

I guess more thought needs to be put before changing `CheckedScalar`.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#933` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
