### ISSUE TITLE
Let's move FakeLogger and FakeHandler to public scope or to cactoos-matchers

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#935]
It's usual test a library that logs. So, to achieve this, we could use `FakeLogger` and `FakeHandler`. But they aren't in a public scope to allow it. So, let's move them to a public scope in Cactoos or move them to [cactoos-matchers](https://github.com/llorllale/cactoos-matchers). IMHO, I think the second option better...

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by fabriciofx** [comment]
@llorllale The problem is very often we need validate some log messages. Thus, a `FakeLogger` is necessary. Should I reimplement a new `FakeLogger` for each application/library? Cactoos already has one...

**Comment by llorllale** [comment]
@fabriciofx neither cactoos nor cactoos-matchers are focused on providing "fake" objects.

**Comment by fabriciofx** [comment]
@llorllale Just out of curiosity: why not?

**Comment by llorllale** [comment]
@fabriciofx I think the answer is in the README

> Cactoos is a collection of object-oriented Java primitives.

> Motivation. We are not happy with JDK, Guava, and Apache Commons because they are procedural and not object-oriented. They do their job, but mostly through static methods. Cactoos is suggesting to do almost exactly the same, but through objects.

**Comment by llorllale** [comment]
@fabriciofx can we close this?

**Comment by fabriciofx** [comment]
@llorllale I agree. I'll close it.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#935` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
