### ISSUE TITLE
It is needed to add the `ForEach` class to use for iteration instead of `And` class.

### ISSUE THREAD

**Issue by vizotov** [yegor256/cactoos#936]
Using `And` class to iterate through a collection is hard to understand.

```
new And(
  (String input) - > System.out.printf ("Item: %s\n", input),
  "how", "are", " you"
).value();
```

Here, the class name does not match the purpose with which it is used. For such use, even added constructors that take parameters of type `Proc`, although it is clear that `Proc` can't have a result of type `Boolean`.

In order to correct this situation, I propose:
1. For the purpose of iteration is to create a `ForEach` class.
2. In the `ForEach` class, create constructors that take `Proc` as parameters, similar to existing constructors of the `And` class.
3. In the `And` class, remove constructors that take `Proc` as parameters as not corresponding to its purpose.
4. Make sure that the `And` class does allow you to specify as parameters only functions that return `Boolean`, not `void`.

Example of using the `ForEach` class:

```
new ForEach(
  (String input) - > System.out.printf ("Item: %s\n", input),
  "how", "are", " you"
).do();
```

Thus, the class used for two different purposes will be divided into two classes, each of which implements one purpose.

It is needed also correct example using `And` in the README.MD.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@vizotov[/z](https://www.0crat.com/u/vizotov) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by wladyan** [comment]
I think implementation should be like this:

```java
public final class ForEach<T> implements Proc<Proc<T>> {
    
    private final Iterable<T> iterable;

    public ForEach(final Iterable<T> items) {
        this.iterable = items;
    }

    @Override
    public void exec(final Proc<T> proc) throws Exception {
        for (final T item : this.iterable) {
            proc.exec(item);
        }
    }

}
```

**Comment by vizotov** [comment]
@wladyan, an idea about implementing interface `Proc` is good. But it must be `Proc<X>` instead of `Proc<Proc<X>>`.

Then a usage of `ForEach` will be:
```
new ForEach(
  (String input) - > System.out.printf ("Item: %s\n", input),
  "how", "are", " you"
).exec();
```

PS In your implementation it is needed to remove parameter of `exec` method and put it into constructor.

**Comment by vizotov** [comment]
@wladyan, this implementation will prevent lazy evaluations.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@vizotov the problems I'm having with your proposal are:

* the name `ForEach` does not reflect a "living thing" (you'd understand this term if you've read Yegor's books/blogs).
* "ForEach" is made of two words, which is already a code smell

For the "iterate collection and do side-effects" use-case I'd suggest a `Proc` implementation named `Loop` that would accept as arguments a collection and another `Proc` to act on each item of this collection. Cactoos already provides the building blocks for you to do this in your code, I'm not sure if I want to add it in cactoos itself.

**Comment by llorllale** [comment]
@vizotov `And` == logical `And` and therefore we consider it a "thing".

I don't agree with `Vectorized`. Like I said, cactoos provides the building blocks (even the interface `Proc`) to do what you want.

Regarding the examples in the README, perhaps they could be improved somehow. We'll see.

Closing this.
