### ISSUE TITLE
Copy/paste footprints in Javadoc

### ISSUE THREAD

**Issue by vizotov** [yegor256/cactoos#937]
1. JavaDoc for class `org.cactoos.collection.Shuffled` contains description from class `Sorted`:

```
public final class Shuffled<T>
extends CollectionEnvelope<T>
Sorted collection.
Pay attention that sorting will happen...
```

2. Interface `Output` contains wrong return type and description in the method Javadoc:
```
/**
     * Get write access to it.
     * @return InputStream to read from
     * @throws Exception If something goes wrong
     */
OutputStream stream() throws Exception;
```

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@vizotov[/z](https://www.0crat.com/u/vizotov) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@vizotov see a2a51f4df592e7543b729e5a7d57f3ef050dd14b. Is that better?

**Comment by vizotov** [comment]
@llorllale, yes.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#937` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
