### ISSUE TITLE
Add an AppendOutputTo or equivalent

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#939]
`OutputTo` represents an `Output` that outputs somewhere else, in particular `File`s.

There should be something to append to a file, not only write over it. Without this, one is forced to use `FileOutputStream` or `FileWriter` itself instead of an `Output`.

I propose to introduce a separated class, ~~`AppendOutputTo`~~ `AppendTo` to represent this concept. This will prevent having a bunch of boolean parameters passed to `OutputTo` constructor.

It should implement the `Output` interface and accepts the types `File`, `Path`, etc as parameters, but not the type `Output`.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by vizotov** [comment]
@victornoel,
According to issue #913, the class name must be different. I propose a class `Appendable` that implements the `Output` interface and accepts the types `File`, `Path`, etc as parameters, but not the type `Output`. Therefore, the `Appendable` class can be used as the lowest level wrapper and will be transparent for external wrappers to decide whether we append to a file or overwrite it.

**Comment by llorllale** [comment]
@victornoel I agree with @vizotov but I would name this class `AppendTo`.

**Comment by victornoel** [comment]
@vizotov @llorllale seems good to me, I will update the description.

**Comment by vizotov** [comment]
@llorllale, I agree.

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/939#issuecomment-408679182))

@llorllale Job [#939](https://github.com/yegor256/cactoos/issues/939) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
The job [#939](https://github.com/yegor256/cactoos/issues/939) assigned to @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov), here is [why](https://www.0crat.com/footprint/C63314D6Z/ec944bb8-b629-4bcc-8712-1615c7006464); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by ilyakharlamov** [comment]
@llorllale The class org.cactoos.io.AppendTo in master, @Iprogrammerr did it and it seems to be working, unit tests are also fine. 
Is there anything else that needs to be coded here?

**Comment by llorllale** [comment]
@ilyakharlamov apparently @Iprogrammerr never bothered to ask the ticket's reporter to close this issue.

Go ahead and claim the ZC points yourself (ask the reporter to close the issue). :)

**Comment by ilyakharlamov** [comment]
@victornoel Even though it doesn't look fair to @Iprogrammerr, we don't have much of a choice. The ticket is fixed and can't stay in limbo state, so please close the ticket.

**Comment by victornoel** [comment]
@ilyakharlamov yep, no problem

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#939](https://github.com/yegor256/cactoos/issues/939) is now out of scope

**Comment by sereshqua** [comment]
@0pdd quality good

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @ilyakharlamov[/z](https://www.0crat.com/u/ilyakharlamov)
