### ISSUE TITLE
We need the Cactoos' way to write to an Output.

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#940]
After doing my research on the available classes in Cactoos, I couldn't find a way to nicely write to a file or any other `Output`.

Or more precisely to write from an `Input` to an `Output`.

I am expecting to be able to write something like:
```java
new InOutProc(new OutputTo(/* some output */)).exec(new InputOf(/* some input */);
```

I used an implementation of `Proc` in this example because this is a clearly a procedural problem.

I named it `InOutProc` but I'm not very happy with this name though, something better should/could be found.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by victornoel** [comment]
@vizotov you are right, thank you :)

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#940` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
