### ISSUE TITLE
Add a new Text implementation named Strict that validates a regex of a Text.

### ISSUE THREAD

**Issue by victornoel** [yegor256/cactoos#941]
In zold-io/java-api we have a lot of text matching to do (see zold-io/java-api#44, zold-io/java-api#45, zold-io/java-api#47), and the same pattern is present again and again:

```java
private static final Pattern PAT = Pattern.compile(/* some pattern */);

String pat() {
  String str = /* some string */;
  if (!PAT.matcher(str).matches()) {
    throw new IOException(
      new UncheckedText(
        new FormattedText(
          "Invalid details string '%s', does not match pattern '%s'", dtls, PAT)
        ).asString()
     );
  }
  return str;
}
```

I think Cactoos should provide `Strict` class implementing `Text`, similar to `Text.NoNulls` but in its own class file, validating a wrapped Text, for this behaviour:
```java
new Strict(PAT, new TextOf(str)).asString();
```

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@victornoel sounds like something that would belong to llorllale/cactoos-matchers...

**Comment by victornoel** [comment]
@llorllale not a matcher as in hamcrest matcher, I mean something that encapsulates a `Pattern`, see my example. It's not for tests, it's for building behaviour of objects.

**Comment by llorllale** [comment]
@victornoel I understand. The problem is I'm having trouble picturing this functionality in cactoos because it would be unique in the sense that it's "testing something", rather than enhancing an existing functionality...

**Comment by victornoel** [comment]
@llorllale it is a bit similar to the various `NonNull` implementations of some of the cactoos interfaces: they are testing something but do not enhance an existing functionality.

**Comment by victornoel** [comment]
@llorllale yep, that seems better, I agree `Matched` is not very clear actually. I will update the description

**Comment by victornoel** [comment]
@llorllale ok, description updated!

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/941#issuecomment-408700063))

@llorllale Job [#941](https://github.com/yegor256/cactoos/issues/941) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by llorllale** [comment]
@victornoel btw, `Strict` should be in its own class file

**Comment by victornoel** [comment]
@llorllale right, I updated the description to avoid ambiguity.

**Comment by victornoel** [comment]
@llorllale by the way this could take also a `Predicate` and other ways to test for something and not only a regex. The new naming made me think of that.

**Comment by llorllale** [comment]
@victornoel sure, but we use `Func<?, Boolean>` here in cactoos

**Comment by 0crat** [comment]
The job [#941](https://github.com/yegor256/cactoos/issues/941) assigned to @atapin[/z](https://www.0crat.com/u/atapin), here is [why](https://www.0crat.com/footprint/C63314D6Z/8249f7c5-ba0c-4a80-b928-09fb2e1c3e91); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by atapin** [comment]
@llorllale @victornoel we already have `org.cactoos.text.Strict`

**Comment by atapin** [comment]
@0crat wait for zerocracy/farm#1980

**Comment by 0crat** [comment]
> @0crat wait for zerocracy/farm#1980 ([here](https://github.com/yegor256/cactoos/issues/941#issuecomment-480204602))

@atapin The impediment for [#941](https://github.com/yegor256/cactoos/issues/941) was registered successfully by @atapin[/z](https://www.0crat.com/u/atapin)

**Comment by victornoel** [comment]
@atapin yep sorry, I didn't know this was already merged,, @Iprogrammerr forgot to notify me, good for you you get the points ;)

**Comment by 0crat** [comment]
Job was finished in 35 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @atapin[/z](https://www.0crat.com/u/atapin), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#941](https://github.com/yegor256/cactoos/issues/941) is now out of scope

**Comment by sereshqua** [comment]
@0pdd quality good

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +40 point(s) just awarded to @atapin[/z](https://www.0crat.com/u/atapin)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
