### ISSUE TITLE
Finish MkHook implementation

### ISSUE THREAD

**Issue by paulodamaso** [yegor256/cactoos#943]
`MkHook` does not implement all `Hook` interface methods; it throws an `UnsupportedOperationException` when this method is called. Please implement this method acordingly and cover `MkHook` with tests.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!
