### ISSUE TITLE
Upgrade qulice to 0.18

### ISSUE THREAD

**Issue by krzyk** [yegor256/cactoos#946]
There have been few changes in it (so it might be easier to do upgrade in steps -> 0.17.5, 0.17.6, 0.18):
- removal of AvoidInstantiatingObjectsInLoops (so each suppression of that should be removed)
- add of EmptyLinesCheck (each class member should have a single line between itself and another class member) - https://github.com/teamed/qulice/issues/576
- threaded checkstyle and PMD execution (should speed up qulice for larger projects)
- fixes in ProtectedMethodInFinalClassCheck (suppresions might be not needed - https://github.com/teamed/qulice/issues/901)
- new Checkstyle (8.11) and PMD (6.6.0) version - fixes for checks

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@krzyk I'm going to delay doing this until some future point past the 1.0 release

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#946` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
