### ISSUE TITLE
The design of envelope classes

### ISSUE THREAD

**Issue by wladyan** [yegor256/cactoos#947]
I think the design of `IterableEnvelope`, `CollectionEnvelope`, `ListEnvelope` is wrong. I gess, it would be better to delegate all method calls to encapsulated object, instead to define of method implementation. Envelopes must don't care about mutability protection, for this goal we have decorators. For example, `ListOf` class use `Collections.unmodifiableList` decorator. May be I'm wrong. Help me.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@wladyan[/z](https://www.0crat.com/u/wladyan) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@wladyan I think you're reporting two separate issues?

1) *Envelopes should delegate all calls to the enveloped object*
You may have a point. Envelopes' purpose is to provide the interface implementations. These are doing that *and* providing immutability. Immutability is part of our principles, but then again, immutability could be provided by a decorator. Will have to think about it a little bit...

2) *`ListOf` uses `Collections.unmodifiableList`*
I think this is just a small implementation detail arising from the fact that `ListOf` is eagerly copying that whole input into a new list.

**Comment by wladyan** [comment]
@llorllale I talking only about envelope classes. Implemetation of `ListOf` class is absolutely correct for me.

Immutability is one of the main principles in this library, but another principle is "avoid nulls". Why envelopes don't protect me against nulls? For this purporse we have `NoNulls` decorators and envelopes don't care about nulls.

Envelopes should delegate all calls to the enveloped object, and this object make decision about immutability(to be immutable or to be mutable), and about nulls(support null values or not).

What if I need to create my own **mutable** implementation of a `List.` Unfortunately I can't use `ListEnvelope,` because it works as decorator sometimes.

**Comment by llorllale** [comment]
@wladyan yes, I agree. We will resume this after [1.0](https://github.com/yegor256/cactoos/milestone/1) is released

**Comment by llorllale** [comment]
@wladyan we're still not at `1.0` yet but we'll start work on this

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/947#issuecomment-504246394))

@llorllale Job [#947](https://github.com/yegor256/cactoos/issues/947) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/947#issuecomment-504246394))

@llorllale Thanks for your contribution, @wladyan[/z](https://www.0crat.com/u/wladyan)! If you would be a member of [the project](https://www.0crat.com/p/C63314D6Z), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by 0crat** [comment]
The job [#947](https://github.com/yegor256/cactoos/issues/947) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/335d07a6-0458-4ea3-8aa6-e945547de575); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@llorllale so is the objective here to make envelopes directly delegate to enveloped object and removing specific behaviour there? Or do you have something else in mind, I'm not clear following the discussion you had with @wladyan :)

**Comment by scristalli** [comment]
@llorllale @victornoel I'm interested too, since this issue is crucial for deciding how to solve #898.
From what I understood following the discussion (see also #1008), the removal of immutability from envelopes seems a good option, otherwise we would have to create a specific envelope/decorator just for providing mutability.

**Comment by llorllale** [comment]
@victornoel envelopes will delegate to enveloped object; we will also create `Immutable` decorators

**Comment by victornoel** [comment]
@0crat wait for #1154 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #1154 to be merged ([here](https://github.com/yegor256/cactoos/issues/947#issuecomment-507064462))

@victornoel The impediment for [#947](https://github.com/yegor256/cactoos/issues/947) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
The architect of the project has changed; @llorllale[/z](https://www.0crat.com/u/llorllale) is not at this role anymore; @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) is the architect now

**Comment by 0pdd** [comment]
@wladyan 3 puzzles [#1183](https://github.com/yegor256/cactoos/issues/1183), [#1184](https://github.com/yegor256/cactoos/issues/1184), [#1185](https://github.com/yegor256/cactoos/issues/1185) are still not solved.

**Comment by victornoel** [comment]
@wladyan the job was done and merged in #1154, can you close this issue?

**Comment by wladyan** [comment]
@victornoel I can close this, but puzzles #1184, #1185 are still not solved...

**Comment by victornoel** [comment]
@wladyan in zerocracy, a job encompasses working on the ticket and writing other tickets and todos to finish the job if it wasn't possible in 30mn. While this is done, the job is done, and new tickets are created for the rest of the job.

What you can do as the reporter is to:
1. verify the work in the PR actually corresponds to what you wanted
2. verify that the todos created are in line with what was requested

If it's not the case, raise you concern here (to me and ARC, it's our fault for not asking you for clarification), and if it's the case, then you can just close this and life can continue.

If we keep this open, then because one job usually creates many todos, very quickly, all the DEV would have their agenda full (we have a limit on the number of job we can have at  a time) and the system would be deadlocked :)

**Comment by wladyan** [comment]
@victornoel ok, thanks.

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) all `QA`s are on vacation. Please handle that.

**Comment by 0crat** [comment]
The job [#947](https://github.com/yegor256/cactoos/issues/947) is now out of scope

**Comment by 0pdd** [comment]
@wladyan 3 puzzles [#1183](https://github.com/yegor256/cactoos/issues/1183), [#1185](https://github.com/yegor256/cactoos/issues/1185), [#1242](https://github.com/yegor256/cactoos/issues/1242) are still not solved; solved: [#1184](https://github.com/yegor256/cactoos/issues/1184).

**Comment by 0pdd** [comment]
@wladyan 4 puzzles [#1183](https://github.com/yegor256/cactoos/issues/1183), [#1185](https://github.com/yegor256/cactoos/issues/1185), [#1242](https://github.com/yegor256/cactoos/issues/1242), [#1262](https://github.com/yegor256/cactoos/issues/1262) are still not solved; solved: [#1184](https://github.com/yegor256/cactoos/issues/1184).

**Comment by 0pdd** [comment]
@wladyan 3 puzzles [#1183](https://github.com/yegor256/cactoos/issues/1183), [#1185](https://github.com/yegor256/cactoos/issues/1185), [#1242](https://github.com/yegor256/cactoos/issues/1242) are still not solved; solved: [#1184](https://github.com/yegor256/cactoos/issues/1184), [#1262](https://github.com/yegor256/cactoos/issues/1262).

**Comment by 0pdd** [comment]
@wladyan 2 puzzles [#1183](https://github.com/yegor256/cactoos/issues/1183), [#1242](https://github.com/yegor256/cactoos/issues/1242) are still not solved; solved: [#1184](https://github.com/yegor256/cactoos/issues/1184), [#1185](https://github.com/yegor256/cactoos/issues/1185), [#1262](https://github.com/yegor256/cactoos/issues/1262).

**Comment by 0pdd** [comment]
@wladyan 15 puzzles [#1183](https://github.com/yegor256/cactoos/issues/1183), [#1292](https://github.com/yegor256/cactoos/issues/1292), [#1293](https://github.com/yegor256/cactoos/issues/1293), [#1294](https://github.com/yegor256/cactoos/issues/1294), [#1295](https://github.com/yegor256/cactoos/issues/1295), [#1296](https://github.com/yegor256/cactoos/issues/1296), [#1297](https://github.com/yegor256/cactoos/issues/1297), [#1298](https://github.com/yegor256/cactoos/issues/1298), [#1299](https://github.com/yegor256/cactoos/issues/1299), [#1300](https://github.com/yegor256/cactoos/issues/1300), [#1301](https://github.com/yegor256/cactoos/issues/1301), [#1302](https://github.com/yegor256/cactoos/issues/1302), [#1303](https://github.com/yegor256/cactoos/issues/1303), [#1304](https://github.com/yegor256/cactoos/issues/1304), [#1305](https://github.com/yegor256/cactoos/issues/1305) are still not solved; solved: [#1184](https://github.com/yegor256/cactoos/issues/1184), [#1185](https://github.com/yegor256/cactoos/issues/1185), [#1242](https://github.com/yegor256/cactoos/issues/1242), [#1262](https://github.com/yegor256/cactoos/issues/1262).

**Comment by 0pdd** [comment]
@wladyan 14 puzzles [#1183](https://github.com/yegor256/cactoos/issues/1183), [#1292](https://github.com/yegor256/cactoos/issues/1292), [#1293](https://github.com/yegor256/cactoos/issues/1293), [#1295](https://github.com/yegor256/cactoos/issues/1295), [#1296](https://github.com/yegor256/cactoos/issues/1296), [#1297](https://github.com/yegor256/cactoos/issues/1297), [#1298](https://github.com/yegor256/cactoos/issues/1298), [#1299](https://github.com/yegor256/cactoos/issues/1299), [#1300](https://github.com/yegor256/cactoos/issues/1300), [#1301](https://github.com/yegor256/cactoos/issues/1301), [#1302](https://github.com/yegor256/cactoos/issues/1302), [#1303](https://github.com/yegor256/cactoos/issues/1303), [#1304](https://github.com/yegor256/cactoos/issues/1304), [#1305](https://github.com/yegor256/cactoos/issues/1305) are still not solved; solved: [#1184](https://github.com/yegor256/cactoos/issues/1184), [#1185](https://github.com/yegor256/cactoos/issues/1185), [#1242](https://github.com/yegor256/cactoos/issues/1242), [#1262](https://github.com/yegor256/cactoos/issues/1262), [#1294](https://github.com/yegor256/cactoos/issues/1294).

**Comment by 0pdd** [comment]
@wladyan 11 puzzles [#1183](https://github.com/yegor256/cactoos/issues/1183), [#1292](https://github.com/yegor256/cactoos/issues/1292), [#1293](https://github.com/yegor256/cactoos/issues/1293), [#1295](https://github.com/yegor256/cactoos/issues/1295), [#1298](https://github.com/yegor256/cactoos/issues/1298), [#1299](https://github.com/yegor256/cactoos/issues/1299), [#1300](https://github.com/yegor256/cactoos/issues/1300), [#1301](https://github.com/yegor256/cactoos/issues/1301), [#1302](https://github.com/yegor256/cactoos/issues/1302), [#1304](https://github.com/yegor256/cactoos/issues/1304), [#1305](https://github.com/yegor256/cactoos/issues/1305) are still not solved; solved: [#1184](https://github.com/yegor256/cactoos/issues/1184), [#1185](https://github.com/yegor256/cactoos/issues/1185), [#1242](https://github.com/yegor256/cactoos/issues/1242), [#1262](https://github.com/yegor256/cactoos/issues/1262), [#1294](https://github.com/yegor256/cactoos/issues/1294), [#1296](https://github.com/yegor256/cactoos/issues/1296), [#1297](https://github.com/yegor256/cactoos/issues/1297), [#1303](https://github.com/yegor256/cactoos/issues/1303).

**Comment by 0pdd** [comment]
@wladyan 11 puzzles [#1183](https://github.com/yegor256/cactoos/issues/1183), [#1292](https://github.com/yegor256/cactoos/issues/1292), [#1295](https://github.com/yegor256/cactoos/issues/1295), [#1298](https://github.com/yegor256/cactoos/issues/1298), [#1299](https://github.com/yegor256/cactoos/issues/1299), [#1300](https://github.com/yegor256/cactoos/issues/1300), [#1301](https://github.com/yegor256/cactoos/issues/1301), [#1302](https://github.com/yegor256/cactoos/issues/1302), [#1304](https://github.com/yegor256/cactoos/issues/1304), [#1305](https://github.com/yegor256/cactoos/issues/1305), [#1320](https://github.com/yegor256/cactoos/issues/1320) are still not solved; solved: [#1184](https://github.com/yegor256/cactoos/issues/1184), [#1185](https://github.com/yegor256/cactoos/issues/1185), [#1242](https://github.com/yegor256/cactoos/issues/1242), [#1262](https://github.com/yegor256/cactoos/issues/1262), [#1293](https://github.com/yegor256/cactoos/issues/1293), [#1294](https://github.com/yegor256/cactoos/issues/1294), [#1296](https://github.com/yegor256/cactoos/issues/1296), [#1297](https://github.com/yegor256/cactoos/issues/1297), [#1303](https://github.com/yegor256/cactoos/issues/1303).

**Comment by 0pdd** [comment]
@wladyan 11 puzzles [#1183](https://github.com/yegor256/cactoos/issues/1183), [#1295](https://github.com/yegor256/cactoos/issues/1295), [#1298](https://github.com/yegor256/cactoos/issues/1298), [#1299](https://github.com/yegor256/cactoos/issues/1299), [#1300](https://github.com/yegor256/cactoos/issues/1300), [#1301](https://github.com/yegor256/cactoos/issues/1301), [#1302](https://github.com/yegor256/cactoos/issues/1302), [#1304](https://github.com/yegor256/cactoos/issues/1304), [#1305](https://github.com/yegor256/cactoos/issues/1305), [#1320](https://github.com/yegor256/cactoos/issues/1320), [#1325](https://github.com/yegor256/cactoos/issues/1325) are still not solved; solved: [#1184](https://github.com/yegor256/cactoos/issues/1184), [#1185](https://github.com/yegor256/cactoos/issues/1185), [#1242](https://github.com/yegor256/cactoos/issues/1242), [#1262](https://github.com/yegor256/cactoos/issues/1262), [#1292](https://github.com/yegor256/cactoos/issues/1292), [#1293](https://github.com/yegor256/cactoos/issues/1293), [#1294](https://github.com/yegor256/cactoos/issues/1294), [#1296](https://github.com/yegor256/cactoos/issues/1296), [#1297](https://github.com/yegor256/cactoos/issues/1297), [#1303](https://github.com/yegor256/cactoos/issues/1303).

**Comment by 0pdd** [comment]
@wladyan 10 puzzles [#1183](https://github.com/yegor256/cactoos/issues/1183), [#1295](https://github.com/yegor256/cactoos/issues/1295), [#1298](https://github.com/yegor256/cactoos/issues/1298), [#1300](https://github.com/yegor256/cactoos/issues/1300), [#1301](https://github.com/yegor256/cactoos/issues/1301), [#1302](https://github.com/yegor256/cactoos/issues/1302), [#1305](https://github.com/yegor256/cactoos/issues/1305), [#1320](https://github.com/yegor256/cactoos/issues/1320), [#1325](https://github.com/yegor256/cactoos/issues/1325), [#1326](https://github.com/yegor256/cactoos/issues/1326) are still not solved; solved: [#1184](https://github.com/yegor256/cactoos/issues/1184), [#1185](https://github.com/yegor256/cactoos/issues/1185), [#1242](https://github.com/yegor256/cactoos/issues/1242), [#1262](https://github.com/yegor256/cactoos/issues/1262), [#1292](https://github.com/yegor256/cactoos/issues/1292), [#1293](https://github.com/yegor256/cactoos/issues/1293), [#1294](https://github.com/yegor256/cactoos/issues/1294), [#1296](https://github.com/yegor256/cactoos/issues/1296), [#1297](https://github.com/yegor256/cactoos/issues/1297), [#1299](https://github.com/yegor256/cactoos/issues/1299), [#1303](https://github.com/yegor256/cactoos/issues/1303), [#1304](https://github.com/yegor256/cactoos/issues/1304).

**Comment by 0pdd** [comment]
@wladyan 9 puzzles [#1183](https://github.com/yegor256/cactoos/issues/1183), [#1295](https://github.com/yegor256/cactoos/issues/1295), [#1298](https://github.com/yegor256/cactoos/issues/1298), [#1300](https://github.com/yegor256/cactoos/issues/1300), [#1301](https://github.com/yegor256/cactoos/issues/1301), [#1302](https://github.com/yegor256/cactoos/issues/1302), [#1305](https://github.com/yegor256/cactoos/issues/1305), [#1320](https://github.com/yegor256/cactoos/issues/1320), [#1325](https://github.com/yegor256/cactoos/issues/1325) are still not solved; solved: [#1184](https://github.com/yegor256/cactoos/issues/1184), [#1185](https://github.com/yegor256/cactoos/issues/1185), [#1242](https://github.com/yegor256/cactoos/issues/1242), [#1262](https://github.com/yegor256/cactoos/issues/1262), [#1292](https://github.com/yegor256/cactoos/issues/1292), [#1293](https://github.com/yegor256/cactoos/issues/1293), [#1294](https://github.com/yegor256/cactoos/issues/1294), [#1296](https://github.com/yegor256/cactoos/issues/1296), [#1297](https://github.com/yegor256/cactoos/issues/1297), [#1299](https://github.com/yegor256/cactoos/issues/1299), [#1303](https://github.com/yegor256/cactoos/issues/1303), [#1304](https://github.com/yegor256/cactoos/issues/1304), [#1326](https://github.com/yegor256/cactoos/issues/1326).

**Comment by 0pdd** [comment]
@wladyan 8 puzzles [#1183](https://github.com/yegor256/cactoos/issues/1183), [#1295](https://github.com/yegor256/cactoos/issues/1295), [#1298](https://github.com/yegor256/cactoos/issues/1298), [#1300](https://github.com/yegor256/cactoos/issues/1300), [#1301](https://github.com/yegor256/cactoos/issues/1301), [#1302](https://github.com/yegor256/cactoos/issues/1302), [#1305](https://github.com/yegor256/cactoos/issues/1305), [#1320](https://github.com/yegor256/cactoos/issues/1320) are still not solved; solved: [#1184](https://github.com/yegor256/cactoos/issues/1184), [#1185](https://github.com/yegor256/cactoos/issues/1185), [#1242](https://github.com/yegor256/cactoos/issues/1242), [#1262](https://github.com/yegor256/cactoos/issues/1262), [#1292](https://github.com/yegor256/cactoos/issues/1292), [#1293](https://github.com/yegor256/cactoos/issues/1293), [#1294](https://github.com/yegor256/cactoos/issues/1294), [#1296](https://github.com/yegor256/cactoos/issues/1296), [#1297](https://github.com/yegor256/cactoos/issues/1297), [#1299](https://github.com/yegor256/cactoos/issues/1299), [#1303](https://github.com/yegor256/cactoos/issues/1303), [#1304](https://github.com/yegor256/cactoos/issues/1304), [#1325](https://github.com/yegor256/cactoos/issues/1325), [#1326](https://github.com/yegor256/cactoos/issues/1326).

**Comment by 0pdd** [comment]
@wladyan 5 puzzles [#1183](https://github.com/yegor256/cactoos/issues/1183), [#1295](https://github.com/yegor256/cactoos/issues/1295), [#1300](https://github.com/yegor256/cactoos/issues/1300), [#1302](https://github.com/yegor256/cactoos/issues/1302), [#1320](https://github.com/yegor256/cactoos/issues/1320) are still not solved; solved: [#1184](https://github.com/yegor256/cactoos/issues/1184), [#1185](https://github.com/yegor256/cactoos/issues/1185), [#1242](https://github.com/yegor256/cactoos/issues/1242), [#1262](https://github.com/yegor256/cactoos/issues/1262), [#1292](https://github.com/yegor256/cactoos/issues/1292), [#1293](https://github.com/yegor256/cactoos/issues/1293), [#1294](https://github.com/yegor256/cactoos/issues/1294), [#1296](https://github.com/yegor256/cactoos/issues/1296), [#1297](https://github.com/yegor256/cactoos/issues/1297), [#1298](https://github.com/yegor256/cactoos/issues/1298), [#1299](https://github.com/yegor256/cactoos/issues/1299), [#1301](https://github.com/yegor256/cactoos/issues/1301), [#1303](https://github.com/yegor256/cactoos/issues/1303), [#1304](https://github.com/yegor256/cactoos/issues/1304), [#1305](https://github.com/yegor256/cactoos/issues/1305), [#1325](https://github.com/yegor256/cactoos/issues/1325), [#1326](https://github.com/yegor256/cactoos/issues/1326).

**Comment by 0pdd** [comment]
@wladyan 5 puzzles [#1183](https://github.com/yegor256/cactoos/issues/1183), [#1295](https://github.com/yegor256/cactoos/issues/1295), [#1302](https://github.com/yegor256/cactoos/issues/1302), [#1320](https://github.com/yegor256/cactoos/issues/1320), [#1337](https://github.com/yegor256/cactoos/issues/1337) are still not solved; solved: [#1184](https://github.com/yegor256/cactoos/issues/1184), [#1185](https://github.com/yegor256/cactoos/issues/1185), [#1242](https://github.com/yegor256/cactoos/issues/1242), [#1262](https://github.com/yegor256/cactoos/issues/1262), [#1292](https://github.com/yegor256/cactoos/issues/1292), [#1293](https://github.com/yegor256/cactoos/issues/1293), [#1294](https://github.com/yegor256/cactoos/issues/1294), [#1296](https://github.com/yegor256/cactoos/issues/1296), [#1297](https://github.com/yegor256/cactoos/issues/1297), [#1298](https://github.com/yegor256/cactoos/issues/1298), [#1299](https://github.com/yegor256/cactoos/issues/1299), [#1300](https://github.com/yegor256/cactoos/issues/1300), [#1301](https://github.com/yegor256/cactoos/issues/1301), [#1303](https://github.com/yegor256/cactoos/issues/1303), [#1304](https://github.com/yegor256/cactoos/issues/1304), [#1305](https://github.com/yegor256/cactoos/issues/1305), [#1325](https://github.com/yegor256/cactoos/issues/1325), [#1326](https://github.com/yegor256/cactoos/issues/1326).

**Comment by 0pdd** [comment]
@wladyan 3 puzzles [#1183](https://github.com/yegor256/cactoos/issues/1183), [#1320](https://github.com/yegor256/cactoos/issues/1320), [#1337](https://github.com/yegor256/cactoos/issues/1337) are still not solved; solved: [#1184](https://github.com/yegor256/cactoos/issues/1184), [#1185](https://github.com/yegor256/cactoos/issues/1185), [#1242](https://github.com/yegor256/cactoos/issues/1242), [#1262](https://github.com/yegor256/cactoos/issues/1262), [#1292](https://github.com/yegor256/cactoos/issues/1292), [#1293](https://github.com/yegor256/cactoos/issues/1293), [#1294](https://github.com/yegor256/cactoos/issues/1294), [#1295](https://github.com/yegor256/cactoos/issues/1295), [#1296](https://github.com/yegor256/cactoos/issues/1296), [#1297](https://github.com/yegor256/cactoos/issues/1297), [#1298](https://github.com/yegor256/cactoos/issues/1298), [#1299](https://github.com/yegor256/cactoos/issues/1299), [#1300](https://github.com/yegor256/cactoos/issues/1300), [#1301](https://github.com/yegor256/cactoos/issues/1301), [#1302](https://github.com/yegor256/cactoos/issues/1302), [#1303](https://github.com/yegor256/cactoos/issues/1303), [#1304](https://github.com/yegor256/cactoos/issues/1304), [#1305](https://github.com/yegor256/cactoos/issues/1305), [#1325](https://github.com/yegor256/cactoos/issues/1325), [#1326](https://github.com/yegor256/cactoos/issues/1326).

**Comment by 0pdd** [comment]
@wladyan 3 puzzles [#1183](https://github.com/yegor256/cactoos/issues/1183), [#1337](https://github.com/yegor256/cactoos/issues/1337), [#1349](https://github.com/yegor256/cactoos/issues/1349) are still not solved; solved: [#1184](https://github.com/yegor256/cactoos/issues/1184), [#1185](https://github.com/yegor256/cactoos/issues/1185), [#1242](https://github.com/yegor256/cactoos/issues/1242), [#1262](https://github.com/yegor256/cactoos/issues/1262), [#1292](https://github.com/yegor256/cactoos/issues/1292), [#1293](https://github.com/yegor256/cactoos/issues/1293), [#1294](https://github.com/yegor256/cactoos/issues/1294), [#1295](https://github.com/yegor256/cactoos/issues/1295), [#1296](https://github.com/yegor256/cactoos/issues/1296), [#1297](https://github.com/yegor256/cactoos/issues/1297), [#1298](https://github.com/yegor256/cactoos/issues/1298), [#1299](https://github.com/yegor256/cactoos/issues/1299), [#1300](https://github.com/yegor256/cactoos/issues/1300), [#1301](https://github.com/yegor256/cactoos/issues/1301), [#1302](https://github.com/yegor256/cactoos/issues/1302), [#1303](https://github.com/yegor256/cactoos/issues/1303), [#1304](https://github.com/yegor256/cactoos/issues/1304), [#1305](https://github.com/yegor256/cactoos/issues/1305), [#1320](https://github.com/yegor256/cactoos/issues/1320), [#1325](https://github.com/yegor256/cactoos/issues/1325), [#1326](https://github.com/yegor256/cactoos/issues/1326).

**Comment by 0pdd** [comment]
@wladyan 2 puzzles [#1183](https://github.com/yegor256/cactoos/issues/1183), [#1349](https://github.com/yegor256/cactoos/issues/1349) are still not solved; solved: [#1184](https://github.com/yegor256/cactoos/issues/1184), [#1185](https://github.com/yegor256/cactoos/issues/1185), [#1242](https://github.com/yegor256/cactoos/issues/1242), [#1262](https://github.com/yegor256/cactoos/issues/1262), [#1292](https://github.com/yegor256/cactoos/issues/1292), [#1293](https://github.com/yegor256/cactoos/issues/1293), [#1294](https://github.com/yegor256/cactoos/issues/1294), [#1295](https://github.com/yegor256/cactoos/issues/1295), [#1296](https://github.com/yegor256/cactoos/issues/1296), [#1297](https://github.com/yegor256/cactoos/issues/1297), [#1298](https://github.com/yegor256/cactoos/issues/1298), [#1299](https://github.com/yegor256/cactoos/issues/1299), [#1300](https://github.com/yegor256/cactoos/issues/1300), [#1301](https://github.com/yegor256/cactoos/issues/1301), [#1302](https://github.com/yegor256/cactoos/issues/1302), [#1303](https://github.com/yegor256/cactoos/issues/1303), [#1304](https://github.com/yegor256/cactoos/issues/1304), [#1305](https://github.com/yegor256/cactoos/issues/1305), [#1320](https://github.com/yegor256/cactoos/issues/1320), [#1325](https://github.com/yegor256/cactoos/issues/1325), [#1326](https://github.com/yegor256/cactoos/issues/1326), [#1337](https://github.com/yegor256/cactoos/issues/1337).

**Comment by 0pdd** [comment]
@wladyan the puzzle [#1183](https://github.com/yegor256/cactoos/issues/1183) is still not solved; solved: [#1184](https://github.com/yegor256/cactoos/issues/1184), [#1185](https://github.com/yegor256/cactoos/issues/1185), [#1242](https://github.com/yegor256/cactoos/issues/1242), [#1262](https://github.com/yegor256/cactoos/issues/1262), [#1292](https://github.com/yegor256/cactoos/issues/1292), [#1293](https://github.com/yegor256/cactoos/issues/1293), [#1294](https://github.com/yegor256/cactoos/issues/1294), [#1295](https://github.com/yegor256/cactoos/issues/1295), [#1296](https://github.com/yegor256/cactoos/issues/1296), [#1297](https://github.com/yegor256/cactoos/issues/1297), [#1298](https://github.com/yegor256/cactoos/issues/1298), [#1299](https://github.com/yegor256/cactoos/issues/1299), [#1300](https://github.com/yegor256/cactoos/issues/1300), [#1301](https://github.com/yegor256/cactoos/issues/1301), [#1302](https://github.com/yegor256/cactoos/issues/1302), [#1303](https://github.com/yegor256/cactoos/issues/1303), [#1304](https://github.com/yegor256/cactoos/issues/1304), [#1305](https://github.com/yegor256/cactoos/issues/1305), [#1320](https://github.com/yegor256/cactoos/issues/1320), [#1325](https://github.com/yegor256/cactoos/issues/1325), [#1326](https://github.com/yegor256/cactoos/issues/1326), [#1337](https://github.com/yegor256/cactoos/issues/1337), [#1349](https://github.com/yegor256/cactoos/issues/1349).

**Comment by 0pdd** [comment]
@wladyan the puzzle [#1464](https://github.com/yegor256/cactoos/issues/1464) is still not solved; solved: [#1183](https://github.com/yegor256/cactoos/issues/1183), [#1184](https://github.com/yegor256/cactoos/issues/1184), [#1185](https://github.com/yegor256/cactoos/issues/1185), [#1242](https://github.com/yegor256/cactoos/issues/1242), [#1262](https://github.com/yegor256/cactoos/issues/1262), [#1292](https://github.com/yegor256/cactoos/issues/1292), [#1293](https://github.com/yegor256/cactoos/issues/1293), [#1294](https://github.com/yegor256/cactoos/issues/1294), [#1295](https://github.com/yegor256/cactoos/issues/1295), [#1296](https://github.com/yegor256/cactoos/issues/1296), [#1297](https://github.com/yegor256/cactoos/issues/1297), [#1298](https://github.com/yegor256/cactoos/issues/1298), [#1299](https://github.com/yegor256/cactoos/issues/1299), [#1300](https://github.com/yegor256/cactoos/issues/1300), [#1301](https://github.com/yegor256/cactoos/issues/1301), [#1302](https://github.com/yegor256/cactoos/issues/1302), [#1303](https://github.com/yegor256/cactoos/issues/1303), [#1304](https://github.com/yegor256/cactoos/issues/1304), [#1305](https://github.com/yegor256/cactoos/issues/1305), [#1320](https://github.com/yegor256/cactoos/issues/1320), [#1325](https://github.com/yegor256/cactoos/issues/1325), [#1326](https://github.com/yegor256/cactoos/issues/1326), [#1337](https://github.com/yegor256/cactoos/issues/1337), [#1349](https://github.com/yegor256/cactoos/issues/1349).

**Comment by 0pdd** [comment]
@wladyan 2 puzzles [#1537](https://github.com/yegor256/cactoos/issues/1537), [#1538](https://github.com/yegor256/cactoos/issues/1538) are still not solved; solved: [#1183](https://github.com/yegor256/cactoos/issues/1183), [#1184](https://github.com/yegor256/cactoos/issues/1184), [#1185](https://github.com/yegor256/cactoos/issues/1185), [#1242](https://github.com/yegor256/cactoos/issues/1242), [#1262](https://github.com/yegor256/cactoos/issues/1262), [#1292](https://github.com/yegor256/cactoos/issues/1292), [#1293](https://github.com/yegor256/cactoos/issues/1293), [#1294](https://github.com/yegor256/cactoos/issues/1294), [#1295](https://github.com/yegor256/cactoos/issues/1295), [#1296](https://github.com/yegor256/cactoos/issues/1296), [#1297](https://github.com/yegor256/cactoos/issues/1297), [#1298](https://github.com/yegor256/cactoos/issues/1298), [#1299](https://github.com/yegor256/cactoos/issues/1299), [#1300](https://github.com/yegor256/cactoos/issues/1300), [#1301](https://github.com/yegor256/cactoos/issues/1301), [#1302](https://github.com/yegor256/cactoos/issues/1302), [#1303](https://github.com/yegor256/cactoos/issues/1303), [#1304](https://github.com/yegor256/cactoos/issues/1304), [#1305](https://github.com/yegor256/cactoos/issues/1305), [#1320](https://github.com/yegor256/cactoos/issues/1320), [#1325](https://github.com/yegor256/cactoos/issues/1325), [#1326](https://github.com/yegor256/cactoos/issues/1326), [#1337](https://github.com/yegor256/cactoos/issues/1337), [#1349](https://github.com/yegor256/cactoos/issues/1349), [#1464](https://github.com/yegor256/cactoos/issues/1464).

**Comment by 0pdd** [comment]
@wladyan all 27 puzzles are solved here: [#1183](https://github.com/yegor256/cactoos/issues/1183), [#1184](https://github.com/yegor256/cactoos/issues/1184), [#1185](https://github.com/yegor256/cactoos/issues/1185), [#1242](https://github.com/yegor256/cactoos/issues/1242), [#1262](https://github.com/yegor256/cactoos/issues/1262), [#1292](https://github.com/yegor256/cactoos/issues/1292), [#1293](https://github.com/yegor256/cactoos/issues/1293), [#1294](https://github.com/yegor256/cactoos/issues/1294), [#1295](https://github.com/yegor256/cactoos/issues/1295), [#1296](https://github.com/yegor256/cactoos/issues/1296), [#1297](https://github.com/yegor256/cactoos/issues/1297), [#1298](https://github.com/yegor256/cactoos/issues/1298), [#1299](https://github.com/yegor256/cactoos/issues/1299), [#1300](https://github.com/yegor256/cactoos/issues/1300), [#1301](https://github.com/yegor256/cactoos/issues/1301), [#1302](https://github.com/yegor256/cactoos/issues/1302), [#1303](https://github.com/yegor256/cactoos/issues/1303), [#1304](https://github.com/yegor256/cactoos/issues/1304), [#1305](https://github.com/yegor256/cactoos/issues/1305), [#1320](https://github.com/yegor256/cactoos/issues/1320), [#1325](https://github.com/yegor256/cactoos/issues/1325), [#1326](https://github.com/yegor256/cactoos/issues/1326), [#1337](https://github.com/yegor256/cactoos/issues/1337), [#1349](https://github.com/yegor256/cactoos/issues/1349), [#1464](https://github.com/yegor256/cactoos/issues/1464), [#1537](https://github.com/yegor256/cactoos/issues/1537), [#1538](https://github.com/yegor256/cactoos/issues/1538).
