### ISSUE TITLE
DateOf 

### ISSUE THREAD

**Issue by mborra** [yegor256/cactoos#949]
Hi,

I have a problem with the conversion using the DateOf () class. I have this snippet:

`new DateOf("2018-01-01", "yyyy-MM-dd").value().`

And the code raise the exception:

`java.time.DateTimeException: Unable to obtain LocalTime from TemporalAccessor: {},ISO resolved to 2018-01-01 of type java.time.format.Parsed`

I have see the code:

`LocalDateTime.from(
                    formatter.parse(date)
                ).toInstant(ZoneOffset.UTC)
`

How I can to fix the problema? We should use the LocalDate() instead?

Thanks.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@mborra[/z](https://www.0crat.com/u/mborra) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@mborra you want to contribute? Feel free to submit a PR for this.

In this case, I think the solution would be to just use the old fashioned `SimpleDateFormat`. After all, the purpose of `DateOf` is to provide an instance of the old fashioned `Date`.

**Comment by 0crat** [comment]
Job [#949](https://github.com/yegor256/cactoos/issues/949) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Thanks for your contribution, @mborra[/z](https://www.0crat.com/u/mborra)! If you would be a member of [the project](https://www.0crat.com/p/C63314D6Z), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by strokyl** [comment]
@llorllale I tried to `SimpleDateFormat` but it would break the contract because pattern language does not seems the same than `DateTimeFormatter`.
So here is my proposal: https://github.com/yegor256/cactoos/pull/960.
I think maybe I should rename parsed in DateOf, if we keep my solution this parsed won't be accurate anymore (because of conversion directly from TemporalAccessor)

**Comment by 0crat** [comment]
The job [#949](https://github.com/yegor256/cactoos/issues/949) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/4b750bc9-4d50-409c-9e1c-1c7033217084); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #1093 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #1093 to be merged ([here](https://github.com/yegor256/cactoos/issues/949#issuecomment-478371149))

@victornoel The impediment for [#949](https://github.com/yegor256/cactoos/issues/949) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by victornoel** [comment]
@mborra the PR has been merged, I think you can close this issue now :)

**Comment by victornoel** [comment]
@llorllale reporter does not seem to answer anymore, could you close this please?

**Comment by llorllale** [comment]
@mborra PR #1093 was merged for this.

Closing this issue due to unresponsiveness.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#949](https://github.com/yegor256/cactoos/issues/949) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)
