### ISSUE TITLE
SumOf does not work on Iterable<Integer>

### ISSUE THREAD

**Issue by piotrkot** [yegor256/cactoos#950]
SumOf does not use bounded type parameters. For that it doesn't work when called
```
new Collection<Integer> ints;
new SumOf(ints); // doesn't compile
```
If SumOf was implemented like:
```
    public <T extends Number> SumOf(final Iterable<T> src)
```
instead of
```
    public SumOf(final Iterable<Number> src)
```
that would compile.
Please, fix it.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@piotrkot[/z](https://www.0crat.com/u/piotrkot) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@piotrkot fixed in 32c96d908d850eac9380200c16c6ee71a2e7514c. Can we close this issue?

**Comment by 0crat** [comment]
Job [#950](https://github.com/yegor256/cactoos/issues/950) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Thanks for your contribution, @piotrkot[/z](https://www.0crat.com/u/piotrkot)! If you would be a member of [the project](https://www.0crat.com/p/C63314D6Z), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by piotrkot** [comment]
@llorllale Thanks for the fix.
@0crat Thanks for the invitation to join but I prefer to work for you for free.

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/cactoos/issues/950#issuecomment-423450138); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#950` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#950](https://github.com/yegor256/cactoos/issues/950) is now out of scope

**Comment by llorllale** [comment]
@piotrkot let me know if you need this released

**Comment by piotrkot** [comment]
@llorllale Definitely. Please, release it. But now I wonder if you make a fix to the _Latest release_ version (0.11) or to the latest _Pre-release_ version (0.36). And by the way, can you explain the difference between the two?

**Comment by llorllale** [comment]
@piotrkot this will be a pre release (pre 1.0)

**Comment by llorllale** [comment]
@rultor release, tag is `0.37`
