### ISSUE TITLE
Add how to add Cactoos as a gradle dependency to README

### ISSUE THREAD

**Issue by filfreire** [yegor256/cactoos#953]
I've recently had to add Cactoos to a few Gradle-based projects. 
@yegor256 let's add the info on how to include it to the README.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@filfreire[/z](https://www.0crat.com/u/filfreire) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by filfreire** [comment]
@llorllale closing this one since it's merged and released.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#953` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
