### ISSUE TITLE
TextEnvelope.java:76-79: Refactor TextEnvelope.equals()....

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#955]
The puzzle `942-9caf1821` from #942 has to be resolved:

https://github.com/yegor256/cactoos/blob/dd6967d772e6e581c58189119207056305fd716f/src/main/java/org/cactoos/text/TextEnvelope.java#L76-L79

The puzzle was created by Paulo Lobo on 24-Sep-18. 

Estimate: 30 minutes,     

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#955](https://github.com/yegor256/cactoos/issues/955) is now in scope, role is `DEV`

**Comment by strokyl** [comment]
Here is my PR: https://github.com/yegor256/cactoos/pull/959

**Comment by 0pdd** [comment]
The puzzle `942-9caf1821` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#955` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#955](https://github.com/yegor256/cactoos/issues/955) is now out of scope
