### ISSUE TITLE
package-info.java:38-40: There is a new class naming...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#958]
The puzzle `913-d63f0d4a` from #913 has to be resolved: 

https://github.com/yegor256/cactoos/blob/1dfd0766c34fe3c3255b1a8cbba318cf383d08c8/src/main/java/org/cactoos/package-info.java#L38-L40

The puzzle was created by George Aristy on 21-Oct-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#958](https://github.com/yegor256/cactoos/issues/958) is now in scope, role is `DEV`

**Comment by llorllale** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/yegor256/cactoos/issues/958#issuecomment-439721993))

@llorllale @llorllale[/z](https://www.0crat.com/u/llorllale) not enough funds available in the project, can't set budget of job [#958](https://github.com/yegor256/cactoos/issues/958), see [§21](http://www.zerocracy.com/policy.html#21); @llorllale[/z](https://www.0crat.com/u/llorllale) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
The puzzle `913-d63f0d4a` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#964](https://github.com/yegor256/cactoos/issues/964) is still not solved.

**Comment by 0crat** [comment]
Job [#958](https://github.com/yegor256/cactoos/issues/958) is not in the agenda of @llorllale[/z](https://www.0crat.com/u/llorllale), can't retrieve data and time of add

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#958](https://github.com/yegor256/cactoos/issues/958) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#980](https://github.com/yegor256/cactoos/issues/980) is still not solved; solved: [#964](https://github.com/yegor256/cactoos/issues/964).

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#1003](https://github.com/yegor256/cactoos/issues/1003), [#1004](https://github.com/yegor256/cactoos/issues/1004), [#1005](https://github.com/yegor256/cactoos/issues/1005), [#1006](https://github.com/yegor256/cactoos/issues/1006), [#1007](https://github.com/yegor256/cactoos/issues/1007) are still not solved; solved: [#964](https://github.com/yegor256/cactoos/issues/964), [#980](https://github.com/yegor256/cactoos/issues/980).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#1003](https://github.com/yegor256/cactoos/issues/1003), [#1005](https://github.com/yegor256/cactoos/issues/1005), [#1006](https://github.com/yegor256/cactoos/issues/1006), [#1025](https://github.com/yegor256/cactoos/issues/1025) are still not solved; solved: [#1004](https://github.com/yegor256/cactoos/issues/1004), [#1007](https://github.com/yegor256/cactoos/issues/1007), [#964](https://github.com/yegor256/cactoos/issues/964), [#980](https://github.com/yegor256/cactoos/issues/980).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#1003](https://github.com/yegor256/cactoos/issues/1003), [#1005](https://github.com/yegor256/cactoos/issues/1005), [#1025](https://github.com/yegor256/cactoos/issues/1025), [#1046](https://github.com/yegor256/cactoos/issues/1046) are still not solved; solved: [#1004](https://github.com/yegor256/cactoos/issues/1004), [#1006](https://github.com/yegor256/cactoos/issues/1006), [#1007](https://github.com/yegor256/cactoos/issues/1007), [#964](https://github.com/yegor256/cactoos/issues/964), [#980](https://github.com/yegor256/cactoos/issues/980).

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#1003](https://github.com/yegor256/cactoos/issues/1003), [#1025](https://github.com/yegor256/cactoos/issues/1025), [#1046](https://github.com/yegor256/cactoos/issues/1046), [#1064](https://github.com/yegor256/cactoos/issues/1064), [#1065](https://github.com/yegor256/cactoos/issues/1065) are still not solved; solved: [#1004](https://github.com/yegor256/cactoos/issues/1004), [#1005](https://github.com/yegor256/cactoos/issues/1005), [#1006](https://github.com/yegor256/cactoos/issues/1006), [#1007](https://github.com/yegor256/cactoos/issues/1007), [#964](https://github.com/yegor256/cactoos/issues/964), [#980](https://github.com/yegor256/cactoos/issues/980).

**Comment by 0pdd** [comment]
@0pdd 5 puzzles [#1003](https://github.com/yegor256/cactoos/issues/1003), [#1025](https://github.com/yegor256/cactoos/issues/1025), [#1046](https://github.com/yegor256/cactoos/issues/1046), [#1064](https://github.com/yegor256/cactoos/issues/1064), [#1074](https://github.com/yegor256/cactoos/issues/1074) are still not solved; solved: [#1004](https://github.com/yegor256/cactoos/issues/1004), [#1005](https://github.com/yegor256/cactoos/issues/1005), [#1006](https://github.com/yegor256/cactoos/issues/1006), [#1007](https://github.com/yegor256/cactoos/issues/1007), [#1065](https://github.com/yegor256/cactoos/issues/1065), [#964](https://github.com/yegor256/cactoos/issues/964), [#980](https://github.com/yegor256/cactoos/issues/980).

**Comment by 0pdd** [comment]
@0pdd 4 puzzles [#1003](https://github.com/yegor256/cactoos/issues/1003), [#1025](https://github.com/yegor256/cactoos/issues/1025), [#1046](https://github.com/yegor256/cactoos/issues/1046), [#1074](https://github.com/yegor256/cactoos/issues/1074) are still not solved; solved: [#1004](https://github.com/yegor256/cactoos/issues/1004), [#1005](https://github.com/yegor256/cactoos/issues/1005), [#1006](https://github.com/yegor256/cactoos/issues/1006), [#1007](https://github.com/yegor256/cactoos/issues/1007), [#1064](https://github.com/yegor256/cactoos/issues/1064), [#1065](https://github.com/yegor256/cactoos/issues/1065), [#964](https://github.com/yegor256/cactoos/issues/964), [#980](https://github.com/yegor256/cactoos/issues/980).

**Comment by 0pdd** [comment]
@0pdd 3 puzzles [#1003](https://github.com/yegor256/cactoos/issues/1003), [#1025](https://github.com/yegor256/cactoos/issues/1025), [#1046](https://github.com/yegor256/cactoos/issues/1046) are still not solved; solved: [#1004](https://github.com/yegor256/cactoos/issues/1004), [#1005](https://github.com/yegor256/cactoos/issues/1005), [#1006](https://github.com/yegor256/cactoos/issues/1006), [#1007](https://github.com/yegor256/cactoos/issues/1007), [#1064](https://github.com/yegor256/cactoos/issues/1064), [#1065](https://github.com/yegor256/cactoos/issues/1065), [#1074](https://github.com/yegor256/cactoos/issues/1074), [#964](https://github.com/yegor256/cactoos/issues/964), [#980](https://github.com/yegor256/cactoos/issues/980).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1046](https://github.com/yegor256/cactoos/issues/1046) is still not solved; solved: [#1003](https://github.com/yegor256/cactoos/issues/1003), [#1004](https://github.com/yegor256/cactoos/issues/1004), [#1005](https://github.com/yegor256/cactoos/issues/1005), [#1006](https://github.com/yegor256/cactoos/issues/1006), [#1007](https://github.com/yegor256/cactoos/issues/1007), [#1025](https://github.com/yegor256/cactoos/issues/1025), [#1064](https://github.com/yegor256/cactoos/issues/1064), [#1065](https://github.com/yegor256/cactoos/issues/1065), [#1074](https://github.com/yegor256/cactoos/issues/1074), [#964](https://github.com/yegor256/cactoos/issues/964), [#980](https://github.com/yegor256/cactoos/issues/980).

**Comment by 0pdd** [comment]
@0pdd all 12 puzzles are solved here: [#1003](https://github.com/yegor256/cactoos/issues/1003), [#1004](https://github.com/yegor256/cactoos/issues/1004), [#1005](https://github.com/yegor256/cactoos/issues/1005), [#1006](https://github.com/yegor256/cactoos/issues/1006), [#1007](https://github.com/yegor256/cactoos/issues/1007), [#1025](https://github.com/yegor256/cactoos/issues/1025), [#1046](https://github.com/yegor256/cactoos/issues/1046), [#1064](https://github.com/yegor256/cactoos/issues/1064), [#1065](https://github.com/yegor256/cactoos/issues/1065), [#1074](https://github.com/yegor256/cactoos/issues/1074), [#964](https://github.com/yegor256/cactoos/issues/964), [#980](https://github.com/yegor256/cactoos/issues/980).
