### ISSUE TITLE
FuncWithFallback javadoc is outdated / incomplete

### ISSUE THREAD

**Issue by paulodamaso** [yegor256/cactoos#965]
I am trying to use `FuncWithFallback` but documentation in this class is not enough to explain how to use it with `FallBackFrom`. Please improve this documentation explaining how these classes is supposed to work and what we should expect when using them.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@paulodamaso the javadoc needs to be improved, yes. I also think that `follow-up` arg needs to be removed. WDYT?

**Comment by paulodamaso** [comment]
@llorllale I did not get what's this `follow-up` is about, so it's hard to say if we should remove it or not. I've found it's rather strange to have this follow-up as a `Func<Y,Y>` instead of `Func<X,Y>`, but hopefully I think that once the documentation of this class (and related ones) is fixed `follow-up` arg role will be much more clearer. So I think that just fixing the docs would be enough for now; if after that `follow-up` still does not makes sense we should remove it. How about that?

**Comment by llorllale** [comment]
@paulodamaso `followup` is exactly what you think it is: it transforms the "final" value of the fallback before handing it off to you.

I share your concern regarding `Func<X, X>` vs `Func<X, Y>`, and also the fact that you can easily apply any further transformation by wrapping the entire `FuncWithFallback` in a `Func<X, Y>`, `Func<X, X>`, or whatever you want.

**Comment by llorllale** [comment]
@paulodamaso let's fix the javadoc and remove `followup`

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/965#issuecomment-443932005))

@llorllale Job [#965](https://github.com/yegor256/cactoos/issues/965) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by llorllale** [comment]
@0crat boost 2x

**Comment by llorllale** [comment]
@0crat boost 4x

**Comment by 0crat** [comment]
> @0crat boost 2x ([here](https://github.com/yegor256/cactoos/issues/965#issuecomment-445548002))

@llorllale Current boost factor of [#965](https://github.com/yegor256/cactoos/issues/965) is 2x, nothing changed

**Comment by 0crat** [comment]
Boosting tasks is against our principles, see [§15](http://www.zerocracy.com/policy.html#15): -10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
> @0crat boost 4x ([here](https://github.com/yegor256/cactoos/issues/965#issuecomment-445548221))

@llorllale @llorllale[/z](https://www.0crat.com/u/llorllale) not enough funds available in the project, can't set budget of job [#965](https://github.com/yegor256/cactoos/issues/965), see [§21](http://www.zerocracy.com/policy.html#21); @llorllale[/z](https://www.0crat.com/u/llorllale) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Boosting tasks is against our principles, see [§15](http://www.zerocracy.com/policy.html#15): -10 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by llorllale** [comment]
@paulodamaso please check out ee09e136ed0aacaded12f7afe75f138af2213c76. Can we close this?

**Comment by llorllale** [comment]
@paulodamaso ping

**Comment by paulodamaso** [comment]
@llorllale this is great, much better now, please just fix the commit title if possible, it points ti ticket #956

**Comment by paulodamaso** [comment]
@llorllale So sad,..

**Comment by 0crat** [comment]
The job [#965](https://github.com/yegor256/cactoos/issues/965) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)
