### ISSUE TITLE
Object to detect the root cause exception within the exception hierarchy

### ISSUE THREAD

**Issue by dgroup** [yegor256/cactoos#966]
https://github.com/llorllale/cactoos-matchers/issues/40

**Comment by llorllale** [comment]
@dgroup why `cactoos` and not `cactoos-matchers`?

**Comment by llorllale** [comment]
@dgroup I don't understand why this class would be required for `Threads`.

I'm closing this issue because I don't think implementing this provides much value.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#966` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
