### ISSUE TITLE
ListOf doesn't work with iterator

### ISSUE THREAD

**Issue by Vatavuk** [yegor256/cactoos#969]
`ListOf` doesn't work with `iterator` argument. The size of encapsualted `List` is always zero. Like in this example:
```java
Iterator<String> strings = new IteratorOf<>("str");
List<String> first = new ArrayList<>();
while (strings.hasNext()) {
    first.add(strings.next());
}
List<String> second = new ListOf<>(strings);
MatcherAssert.assertThat(
    first.isEmpty(),
    new IsEqual<>(false)
);
MatcherAssert.assertThat(
    second.isEmpty(),
    new IsEqual<>(true)
);       
```

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@vatavuk[/z](https://www.0crat.com/u/vatavuk) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@Vatavuk I haven't looked at the code, but I think the problem is that you've exhausted the iterator while populating `first`, so that by the time you want to populate `second`, `hasNext()` is `false`.

**Comment by llorllale** [comment]
@Vatavuk we're moving away from `Iterator` in most/all cases - see #911

**Comment by llorllale** [comment]
@Vatavuk can we close this?

**Comment by Vatavuk** [comment]
@llorllale uh, by bad yes the iterator is exhausted, I'm closing this.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#969` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
