### ISSUE TITLE
Iterable for pagination

### ISSUE THREAD

**Issue by g4s8** [yegor256/cactoos#971]
Cactoos doesn't have an `Iterable` implementation to wrap paged results with lazy page loading.
Many HTTP APIs provides pagination support, so it would be good to have generic `Iterable` implementation to use pagination.
 
It can be used like this:
```java
org.cactoos.Page<Item> nextPage(String token) {
   JsonObject json = http.load("/items?start="+token);
   Iterable<Item> items = toItems(json.getJsonObject("items")); 
   return new Page(items, json.getString("next_page"));
}

Iterable<Item> items = new Paged(last -> nextPage(last.token()));
```

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@g4s8 here's a quick sketch:

```java
public final class Pagination<T> implements Iterable<T> {
    /**
     * Ctor.
     * `page` transforms a page number (0-indexed) into an iterator of the target type.
     */
    public Pagination(final Func<Integer, Iterator<T>> page) {}
}
```

We leave https calls out of `cactoos` as they are out of scope.

**Comment by g4s8** [comment]
@g4s8 sure, http calls are here just for example. `last` is a last page which is needed to fetch next page. But I'd use generic `Func<P, Iterator<T>>` here because page number will not work for any case, e.g. some APIs may provide a token in response to load next page, some APIs uses `since=<last-id>` param to fetch next page.

**Comment by g4s8** [comment]
@llorllale it can be an argument in constructor:
```java
new Pagination<String>("initial-page", page -> load(page)); // string as page token
new Pagination<Integer>(0, num -> load(num)); // page number as page token
new Pagination<URI>(new URI("https://api/list"), uri -> load(uri)); // URL as page token
```

**Comment by llorllale** [comment]
@g4s8 ping

**Comment by llorllale** [comment]
@g4s8 ping

**Comment by g4s8** [comment]
@llorllale this is simple working prototype that can be used for implementation:
```java

public final class PagedIterable<T, P> implements Iterable<T> {

    /**
     * One page.
     * @param <T> Page items type
     * @param <P> Page token type
     */
    interface Page<T, P> extends Iterable<T> {

        /**
         * Next token if exist.
         * @return Optional with token if has next page or empty if no next page.
         */
        Optional<P> nextToken();
    }

    /**
     * Start page token.
     */
    private final P start;

    /**
     * Function to load page by token.
     */
    private final Func<P,Page<T,P>> loader;

    public PagedIterable(P start, Func<P, Page<T,P>> loader) {
        this.start = start;
        this.loader = loader;
    }

    @Override
    public Iterator<T> iterator() {
        return new PageIterator<>(this.start, this.loader);
    }

    private static final class PageIterator<T, P> implements Iterator<T> {

        private Optional<P> nextToken;
        private final Func<P,Page<T,P>> loader;
        private Iterator<T> page;

        PageIterator(P start, Func<P,Page<T,P>> loader) {
            this.nextToken = Optional.of(start);
            this.loader = loader;
            this.page = Collections.emptyIterator();
        }


        @Override
        public boolean hasNext() {
            return this.page.hasNext() || this.nextToken.isPresent();
        }

        @Override
        public T next() {
            if (!this.page.hasNext()) {
                final P token = this.nextToken.orElseThrow(() -> new NoSuchElementException("no next element"));
                final Page<T, P> page = new UncheckedFunc<>(this.loader).apply(token);
                this.nextToken = page.nextToken();
                this.page = page.iterator();
            }
            return this.page.next();
        }
    }
}

```

**Comment by llorllale** [comment]
@g4s8 I'm not fond of the design, mostly because of `Page`:

* new artificial type specifically for this functionality (ie 'special')
* hard to see how it can be meaningfully composed with our other primitives

I now also think this should ideally be implemented as an additional ctor of `IterableOf` or `IteratorOf`.

So perhaps a better solution would look something like this:
```java
    public <I extends Iterator<X>> IterableOf(Scalar<I> first, Func<I, I> next) {
        ...
    }
```

This completely abstracts cactoos from knowing anything about the user's special "Page", ie. the user would take care of tokens, etc. WDYT?

**Comment by g4s8** [comment]
@llorllale as I understand user has to implemente this `Page implements Iterable<T>` byself, right? 
I think it should work.

**Comment by llorllale** [comment]
@0crat wait because I submitted PR #1032 for this

**Comment by 0crat** [comment]
> @0crat wait because I submitted PR #1032 for this ([here](https://github.com/yegor256/cactoos/issues/971#issuecomment-455909185))

@llorllale Job [#971](https://github.com/yegor256/cactoos/issues/971) is not assigned, can't put it on hold

**Comment by 0crat** [comment]
The job [#971](https://github.com/yegor256/cactoos/issues/971) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C63314D6Z/2d2e124c-a5d2-483b-a307-bd87bd6dd1fc); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @llorllale[/z](https://www.0crat.com/u/llorllale) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#971` already assigned to @llorllale, can't assign to @llorllale

**Comment by llorllale** [comment]
@0crat wait because I submitted PR #1032 for this

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
> @0crat wait because I submitted PR #1032 for this ([here](https://github.com/yegor256/cactoos/issues/971#issuecomment-455910175))

@llorllale The impediment for [#971](https://github.com/yegor256/cactoos/issues/971) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by llorllale** [comment]
@g4s8 PR #1032 was merged, can we close this?

**Comment by g4s8** [comment]
@llorllale sure, thanks a lot

**Comment by 0crat** [comment]
The job [#971](https://github.com/yegor256/cactoos/issues/971) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#1037](https://github.com/yegor256/cactoos/issues/1037) is solved here.
