### ISSUE TITLE
ThreadsTest.java:51-55: o.c.experimental Design the...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#972]
The puzzle `962-d3b6c3c8` from #962 has to be resolved: 

https://github.com/yegor256/cactoos/blob/8a2f57b071cb34afcef8f0d125648ccbaa88dbca/src/test/java/org/cactoos/experimental/ThreadsTest.java#L51-L55

The puzzle was created by Yurii Dubinka on 08-Dec-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
Job [#972](https://github.com/yegor256/cactoos/issues/972) is now in scope, role is `DEV`

**Comment by dgroup** [comment]
@llorllale, I'm ok to implement this, please assign it to me.

**Comment by llorllale** [comment]
@0crat assign @dgroup

**Comment by 0crat** [comment]
> @0crat assign @dgroup  ([here](https://github.com/yegor256/cactoos/issues/972#issuecomment-445554145))

@llorllale The job [#972](https://github.com/yegor256/cactoos/issues/972) assigned to @dgroup[/z](https://www.0crat.com/u/dgroup), here is [why](https://www.0crat.com/footprint/C63314D6Z/d2b9d0db-67c9-4e08-be08-5ff49a975426); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by dgroup** [comment]
@0crat wait as #975 is raised.

**Comment by 0pdd** [comment]
The puzzle `962-d3b6c3c8` has disappeared from the source code, that's why I closed this issue.

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1000](https://github.com/yegor256/cactoos/issues/1000) is still not solved.

**Comment by 0crat** [comment]
The job [#972](https://github.com/yegor256/cactoos/issues/972) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @dgroup[/z](https://www.0crat.com/u/dgroup)

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1277](https://github.com/yegor256/cactoos/issues/1277) is still not solved; solved: [#1000](https://github.com/yegor256/cactoos/issues/1000).

**Comment by 0pdd** [comment]
@0pdd 2 puzzles [#1406](https://github.com/yegor256/cactoos/issues/1406), [#1407](https://github.com/yegor256/cactoos/issues/1407) are still not solved; solved: [#1000](https://github.com/yegor256/cactoos/issues/1000), [#1277](https://github.com/yegor256/cactoos/issues/1277).

**Comment by 0pdd** [comment]
@0pdd the puzzle [#1406](https://github.com/yegor256/cactoos/issues/1406) is still not solved; solved: [#1000](https://github.com/yegor256/cactoos/issues/1000), [#1277](https://github.com/yegor256/cactoos/issues/1277), [#1407](https://github.com/yegor256/cactoos/issues/1407).

**Comment by 0pdd** [comment]
@0pdd all 4 puzzles are solved here: [#1000](https://github.com/yegor256/cactoos/issues/1000), [#1277](https://github.com/yegor256/cactoos/issues/1277), [#1406](https://github.com/yegor256/cactoos/issues/1406), [#1407](https://github.com/yegor256/cactoos/issues/1407).
