### ISSUE TITLE
PathOf: New implementation of `o.c.Text` which supports repeatable arguments

### ISSUE THREAD

**Issue by dgroup** [yegor256/cactoos#976]
Very often we need the functionality like
```java
Message.format(
   "src{0}test{0}resources{0}yml{0}tests{0}{1}",
   File.separator, name
)
```
therefore i propose to wrap it into some Text implementation like
```java
MatcherAssert.assertThat(
   new PathOf("src{0}test{0}resources{0}yml{0}tests{0}{1}", name),
   new TextIs<>("src/test/resources/yml/tests/<name>")
)
// and
MatcherAssert.assertThat(
   new PathOf("src{0}test{0}resources{0}yml{0}tests{0}file.txt"),
   new TextIs<>("src/test/resources/yml/tests/file.txt")
)

```

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@dgroup I don't see much value in this. You want implementations to transparently handle the system's path separator? Sounds like you need [`Paths.get()`](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Paths.html#get-java.lang.String-java.lang.String...-), easily implemented as a scalar using `() -> Paths.get("you", "path", "to", "salvation")`.

**Comment by dgroup** [comment]
@llorllale, thank you for the idea, it looks nice, thus I've tried immediately and was a disappointed a bit.
For example, 
1. In order to receive path as String, i need to do the following
`Paths.get("your", "path", "to", "salvation").toAbsolutePath(),`
2. Moreover, it won't be just "your/path/to/salvation", it will be a
`/Users/yurii.dubinka/projects/xxx/yyyy/your/path/to/salvation` which is unexpected behaviour.

I want to control this process without unexpected behavior/consequences.

**Comment by llorllale** [comment]
@dgroup I do not understand.

`Paths.get()` may return a relative path depending on its inputs. `toAbsolutePath()` will obviously return the full, absolute path.

How is this unexpected?

**Comment by dgroup** [comment]
@llorllale, yes, that was mistake
```java
    @org.junit.Test
    public void test() {
        MatcherAssert.assertThat(
            Paths.get("a", "b", "c").toString(),
            Matchers.equalTo("a/b/c")
        );
    }
``` 
works fine, closing...

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#976` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
