### ISSUE TITLE
JoinedText: Accept Iterables with subtypes of Text

### ISSUE THREAD

**Issue by StuporHero** [yegor256/cactoos#977]
I've got an interface that extends `Text`, and I'd like to use a collection of objects implementing this interface in a `JoinedText` to produce a comma-separated list. Due to the constructor for `JoinedText` using an `Iterable<Text>` instead of `Iterable<? extends Text>`, I cannot without first wrapping it with a `Mapped<>` and either casting each member of the collection to a `Text` (which violates one of the guiding principles of this project) or instantiating a `TextOf` with the value returned by `asString()`, which is just a dumb thing to do. I had a look at the other `Text` classes to see if this applied to any others, and it looks like only `JoinedText` takes an `Iterable<Text>`, but I wanted to raise this as an issue to make sure I'm not wildly off-base instead of submitting a random PR (which I've never been totally comfortable with).

**Comment by llorllale** [comment]
@StuporHero I don't see the issue. The following compiles:

```java
public interface CustomText extends Text {

}

public class TestText implements CustomText {
    @Override
    public String asString() throws Exception {
      throw new UnsupportedOperationException("Not supported yet."); //TODO
    }
}

@Test
public void test() {
    new JoinedText(
      new TextOf(""),
      new IterableOf<>(
        new TestText()
      )
    );
}
```

**Comment by StuporHero** [comment]
@llorllale That compiles because the type of your `new IterableOf<>` is being inferred as `Text` which is valid. The code I have looks more like this:
```Java
Iterable<CustomText> texts = ...

@Test
public void test() {
    new JoinedText(
        new TextOf(""),
        texts
    );
}
```

I think you'll find that this will not compile since the generic parameter is hard-coded to a value other than `Text`. That collection is being assigned in the constructor which uses that subclass because of some other assumptions I need to make about the members of that collection which prevent me from simply using `Text`.

**Comment by llorllale** [comment]
@StuporHero so your problem is specifically with `JoinedText`? This issue's title refers to all `Text`s.

**Comment by llorllale** [comment]
@StuporHero seems like it is.

Let's change this issue's title: `JoinedText: Accept Iterables with subtypes of Text`

**Comment by llorllale** [comment]
@StuporHero fixed in d12d43bd9d8a26db527c8cc2eda3a109dd017d18. Can we close this issue? Do you need a release?

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#977` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
