### ISSUE TITLE
Let's implement a HashCode class

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#978]
Let's implement a HashCode class on the same way of Equality class. The idea is pass attributes/variables to the constructor and it returns a calculates the hash code of them.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@fabriciofx is what you require in essence some *hash* capability?

**Comment by fabriciofx** [comment]
@llorllale I'm thinking a way to add hash capability just using composition, instead of reimplement the content of `hashCode()` method to each class which need this feature (the same way of `Equals` or `Equality`). My ideia is if we've both functionalities (equals/hashcode) we can use reuse them and thus we can do the same lombok functionality does with `@EqualsAndHashCode`.

**Comment by llorllale** [comment]
@fabriciofx I don't see the value in this `HashCode` class.

I also do not like `Equality` at a fundamental level.

**Comment by fabriciofx** [comment]
@llorllale The ideia is implementing something like `Objects.hash()`.
@ilyakharlamov WDYT something like:
```
public final class HashCode implements Scalar<Integer> {
    public HashCode(final Object... objects) {}
    ...
}

@Override
 public int hashCode  {
    return new HashCode(this.privateField1, this.privateField2).value();
 }
```

**Comment by ilyakharlamov** [comment]
@fabriciofx Yes, your code is exactly what I meant. We provided pretty much the same syntax as an example.

**Comment by 0crat** [comment]
The job [#978](https://github.com/yegor256/cactoos/issues/978) assigned to @llorllale[/z](https://www.0crat.com/u/llorllale), here is [why](https://www.0crat.com/footprint/C63314D6Z/1ab0f6c5-a215-4fda-955d-e5059fff13fc); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); we should be aware that @llorllale[/z](https://www.0crat.com/u/llorllale) is on vacation; this ticket may be delayed; there will be no monetary reward for this job

**Comment by llorllale** [comment]
@0crat wait because I submitted PR #1036 for this

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#978` already assigned to @llorllale, can't assign to @llorllale

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
> @0crat wait because I submitted PR #1036 for this ([here](https://github.com/yegor256/cactoos/issues/978#issuecomment-456256569))

@llorllale The impediment for [#978](https://github.com/yegor256/cactoos/issues/978) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by llorllale** [comment]
@fabriciofx PR #1036 was merged. Can we close this?

**Comment by fabriciofx** [comment]
Closed by #1036.

**Comment by 0crat** [comment]
Job was finished in 10 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#978](https://github.com/yegor256/cactoos/issues/978) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)
