### ISSUE TITLE
TextBefore, TextAfter

### ISSUE THREAD

**Issue by dgroup** [yegor256/cactoos#981]
I've checked the https://github.com/yegor256/cactoos/tree/master/src/main/java/org/cactoos/text package but I couldn't find functionality to cut text without specifying of the position (SubText).

```java
new Assertion<>(
     new TextBefore("abc\n", "\n"),
     new TextIs("abc")
).affirm();
```
or
```java
new Assertion<>(
     new TextAfter("\ndef", "\n"),
     new TextIs("def")
).affirm();
```

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/981#issuecomment-450902326))

@llorllale Job [#981](https://github.com/yegor256/cactoos/issues/981) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @dgroup[/z](https://www.0crat.com/u/dgroup)

**Comment by 0crat** [comment]
The job [#981](https://github.com/yegor256/cactoos/issues/981) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/c9b8e94c-995f-4c76-ad69-cb211985ffd8); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@llorllale I believe this has already been solved

**Comment by llorllale** [comment]
@victornoel correct, @Iprogrammerr never informed @dgroup that this was merged in #1014

**Comment by llorllale** [comment]
@0crat refuse

**Comment by llorllale** [comment]
@dgroup can we close this? PR #1014 merged for this

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos/issues/981#issuecomment-478799997))

@llorllale The user @victornoel[/z](https://www.0crat.com/u/victornoel) resigned from [#981](https://github.com/yegor256/cactoos/issues/981), please stop working. Reason for job resignation: Order was cancelled

**Comment by dgroup** [comment]
@Iprogrammerr, @llorllale thank you.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#981` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#981](https://github.com/yegor256/cactoos/issues/981) is now out of scope
