### ISSUE TITLE
Can we add a 'BitwiseAnd' function 

### ISSUE THREAD

**Issue by shan7030** [yegor256/cactoos#982]
I want to add a 'BitwiseAnd' function that will return the result of Anding Bitwise every element of the array 

````javascript

const arr=[1,3,5]
const ans=BitwiseAnd(arr) // (1 & 3 & 5)=1
`````

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@shan7030[/z](https://www.0crat.com/u/shan7030) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by fabriciofx** [comment]
@shan7030 Just for curiosity: in which context is it useful?

**Comment by llorllale** [comment]
@shan7030 does Guava or Apache Commons provide this?

**Comment by llorllale** [comment]
@shan7030 ping

**Comment by shan7030** [comment]
Already merged this function .

**Comment by llorllale** [comment]
@shan7030 

> Already merged this function .

What does that mean?

**Comment by llorllale** [comment]
@shan7030 ping

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#982` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
