### ISSUE TITLE
FirstIn implements Scalar<T> - Do we have any functionality which allows us for iterable of scalars receive the first value, skipping scalars which throw the exception(s)?

### ISSUE THREAD

**Issue by dgroup** [yegor256/cactoos#983]
Do we have any functionality which allows us for iterable of scalars receive the first value, skipping scalars which throw the exception(s)?
For example
```java
MatcherAssert.assertThat(
      new FirstIn<>(
           () -> { throw new NPE; },
           () -> { throw new NPEAGAIN; },
           () -> 3
      ).value(),
      new IsEqual<>(3)
);
```
This is kind of `Or` statement where instead of `Boolean` we may receive particular <T>.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@dgroup not directly, no. You'd have to compose a solution using our existing primitives.

**Comment by dgroup** [comment]
@llorllale I've just found recently that https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/scalar/FirstOf.java has similar behavior, but it looks too complex for this solution.

I'll add this functionality to the project as non-cactoos class.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#983` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
