### ISSUE TITLE
Enumeration support

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#984]
Let's add `Enumeration` support, for example, in `ListOf` (a new constructor).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by fabriciofx** [comment]
@svendiedrichsen @llorllale I see two problems: 1) Unfortunately, there are some old APIs still use `Enumeration`, like ` HttpServletRequest` and others. 2) `Enumeration` does not extend` Iterable` or has any relation with ` Iterator`. So, to be usable as `Iterable` should do something like` ListOf <> (Collections.list (enumeration)) ` which means usage of static methods, what we would like avoid it.

**Comment by svendiedrichsen** [comment]
@fabriciofx 
1) there are always old APIs out there. I would not adapt the new Cactoos API to all the ancient stuff out there. Who ever uses these old APIs would have to provide the code to adapt. Something like `ListOf <> (Collections.list (enumeration))`
2) Leave it to the Cactoos user to handle old APIs with code like `ListOf <> (Collections.list (enumeration))`

**Comment by llorllale** [comment]
@fabriciofx we won't include `Enumeration` in scope for all reasons stated by @svendiedrichsen : a) it's a really ancient and deprecated API, and b) we decided to move away from iterators in #911

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#984` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
