### ISSUE TITLE
Let's update Copyright notice to 2019

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#985]
Let's update Copyright notice to 2019.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@yegor256 should we maintain a range of dates for the copyright notice?

As far as I am aware, the really important date is the one when the work was published (the start date). You *may* add a "revised date" to the notice if a file's contents changes "significantly", but do **we** really need to? Guava certainly doesn't do it. I'm guessing the hassle isn't worth it.

Sources:
* [Copyright.gov (PDF)](https://www.copyright.gov/circs/circ03.pdf)
* [StackOverflow](https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated)

**Comment by llorllale** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@llorllale let's do a years range, this is what we do in all other projects

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/985#issuecomment-491108859))

@llorllale Job [#985](https://github.com/yegor256/cactoos/issues/985) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx)

**Comment by 0crat** [comment]
The job [#985](https://github.com/yegor256/cactoos/issues/985) assigned to @aivinog1[/z](https://www.0crat.com/u/aivinog1), here is [why](https://www.0crat.com/footprint/C63314D6Z/784a14fd-3a0e-409b-943e-4c69f78cdb57); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by aivinog1** [comment]
I found out that dates already changed by @yegor256 in 100885a4638555d30fb56beefbb6691108b30d0f. But dates verification is not working and I add a new TODO.

**Comment by aivinog1** [comment]
@0crat wait #1148

**Comment by 0crat** [comment]
> @0crat wait #1148 ([here](https://github.com/yegor256/cactoos/issues/985#issuecomment-505414258))

@aivinog1 The impediment for [#985](https://github.com/yegor256/cactoos/issues/985) was registered successfully by @aivinog1[/z](https://www.0crat.com/u/aivinog1)

**Comment by aivinog1** [comment]
@0crat continue

**Comment by aivinog1** [comment]
@llorllale I assume that we can close this.

**Comment by 0crat** [comment]
> @0crat continue ([here](https://github.com/yegor256/cactoos/issues/985#issuecomment-505564794))

@aivinog1 @aivinog1[/z](https://www.0crat.com/u/aivinog1) continued working on job [#985](https://github.com/yegor256/cactoos/issues/985)

**Comment by llorllale** [comment]
@aivinog1 ask the ticket's reporter

**Comment by aivinog1** [comment]
@llorllale Thanks.

@fabriciofx Can you close this ticket?

**Comment by aivinog1** [comment]
@llorllale I remind you about #1148. Can you fix my reputation?

**Comment by fabriciofx** [comment]
@llorllale I'll close this issue now. @aivinog1 good work! Congratulations!

**Comment by 0crat** [comment]
Job [#985](https://github.com/yegor256/cactoos/issues/985) is not in the agenda of @aivinog1[/z](https://www.0crat.com/u/aivinog1), can't inspect

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @aivinog1[/z](https://www.0crat.com/u/aivinog1), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#985](https://github.com/yegor256/cactoos/issues/985) is now out of scope

**Comment by sereshqua** [comment]
@aivinog1 please make sure that you start all your message with the name of the user they are addressed to, [see](https://github.com/yegor256/cactoos/issues/985#issuecomment-504741928)

**Comment by aivinog1** [comment]
@sereshqua done, thanks.

**Comment by sereshqua** [comment]
@0crat quality acceptable

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "acceptable": +30 point(s) just awarded to @aivinog1[/z](https://www.0crat.com/u/aivinog1)
