### ISSUE TITLE
Fix the license link in the pom

### ISSUE THREAD

**Issue by Shryne** [yegor256/cactoos#986]
https://github.com/yegor256/cactoos/blob/be02845a55f191007cd60770a455b59d7320446d/pom.xml#L44-L50

This link is dead.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@shryne[/z](https://www.0crat.com/u/shryne) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@0crat in

**Comment by llorllale** [comment]
@yegor256 should we point to the repo's License file?

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/986#issuecomment-451131036))

@llorllale Job [#986](https://github.com/yegor256/cactoos/issues/986) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/986#issuecomment-451131036))

@llorllale Thanks for your contribution, @shryne[/z](https://www.0crat.com/u/shryne)! If you would be a member of [the project](https://www.0crat.com/p/C63314D6Z), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by llorllale** [comment]
@0crat wait

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) not enough funds available in the project, can't set budget of job [#986](https://github.com/yegor256/cactoos/issues/986), see [§21](http://www.zerocracy.com/policy.html#21); @llorllale[/z](https://www.0crat.com/u/llorllale) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/yegor256/cactoos/issues/986#issuecomment-451186759))

@llorllale The impediment for [#986](https://github.com/yegor256/cactoos/issues/986) was registered successfully by @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
> @0crat wait ([here](https://github.com/yegor256/cactoos/issues/986#issuecomment-451186759))

@llorllale Job [#986](https://github.com/yegor256/cactoos/issues/986) is not in the agenda of @llorllale[/z](https://www.0crat.com/u/llorllale), can't set impediment

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by yegor256** [comment]
@llorllale yes, I think so

**Comment by llorllale** [comment]
@Shryne fixed in 773f8e50fe2a5aeaf424b183b95ce8d978aa3edb

**Comment by 0crat** [comment]
Job [#986](https://github.com/yegor256/cactoos/issues/986) is not in the agenda of @llorllale[/z](https://www.0crat.com/u/llorllale), can't retrieve data and time of add

**Comment by 0crat** [comment]
The job [#986](https://github.com/yegor256/cactoos/issues/986) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)
