### ISSUE TITLE
Use @Rule Exception instead of @Test(expected=XxxException.class)

### ISSUE THREAD

**Issue by dgroup** [yegor256/cactoos#991]
Use in all unit-tests the
```java
@Rule
public final ExpectedException exception = ExpectedException.none();
```
in favor of 
```java
@Test(expected=XxxException.class)
```
as it allows to check the error messages also, not the only type of exception.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@dgroup actually I plan on using the newer features from `cactoos-matchers`

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#991` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
