### ISSUE TITLE
Gitlint doesn't work on Windows

### ISSUE THREAD

**Issue by fabriciofx** [yegor256/cactoos#992]
Gitlint doesn't work in Windows as you can see [here](https://github.com/jorisroovers/gitlint/issues/20) and affects the issue #988. So this bug doesn't permit run the entire build locally.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by fabriciofx** [comment]
@llorllale I think possible run correctly in "linux" environment on Windows 10, but the question is: should we use a tool can't run properly on main (Linux, macOS and Windows) OSes? See cactoos: it runs perfectly on Windows because we test it on Appveyor. So, I think all tools to build cactoos should run on all OSes that run cactoos too.

**Comment by llorllale** [comment]
@fabriciofx I'm working on this

**Comment by fabriciofx** [comment]
@llorllale Thanks! Just for curiosity: will you send some patch to gitlint project?

**Comment by llorllale** [comment]
@fabriciofx I plan on implementing this from scratch. Shouldn't be that hard.

**Comment by llorllale** [comment]
@fabriciofx in the meantime, I suggest you try some of the workarounds suggested

**Comment by fabriciofx** [comment]
@llorllale ok. Thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#992` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
