### ISSUE TITLE
FormattedText should extend TextEnvelope

### ISSUE THREAD

**Issue by dgroup** [yegor256/cactoos#994]
Now the `FormattedText` doesn't extend `TextEnvelope` thus such methods like `toString`, `hashCode`, `equals` have default implementation.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@dgroup this is a duplicate of #929

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#994` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by dgroup** [comment]
@llorllale, please ignore my comment, I've checked the wrong issue.
