### ISSUE TITLE
Make ListEnvelope public

### ISSUE THREAD

**Issue by Shryne** [yegor256/cactoos#996]
As the title says, make [ListEnvelope](https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/list/ListEnvelope.java) public so that I, as a user, can use it. I would prefer that instead of creating my own version of it. Similar classes (like [MapEnvelope](https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/map/MapEnvelope.java) or [CollectionEnvelope](https://github.com/yegor256/cactoos/blob/master/src/main/java/org/cactoos/collection/CollectionEnvelope.java)) are public so I don't see why ListEnvelope should be different.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
@shryne[/z](https://www.0crat.com/u/shryne) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C63314D6Z) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/996#issuecomment-452940381))

@llorllale Job [#996](https://github.com/yegor256/cactoos/issues/996) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/yegor256/cactoos/issues/996#issuecomment-452940381))

@llorllale Thanks for your contribution, @shryne[/z](https://www.0crat.com/u/shryne)! If you would be a member of [the project](https://www.0crat.com/p/C63314D6Z), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by piotrkot** [comment]
@llorllale Anyone working on it? Can I make a PR?

**Comment by piotrkot** [comment]
@llorllale PR https://github.com/yegor256/cactoos/pull/1073 is waiting to be reviewed (and merged).

**Comment by 0crat** [comment]
The job [#996](https://github.com/yegor256/cactoos/issues/996) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/73d413f7-9742-4b84-a372-6ee8bbc0f85b); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@0crat wait for #1096 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #1096 to be merged ([here](https://github.com/yegor256/cactoos/issues/996#issuecomment-480494311))

@victornoel The impediment for [#996](https://github.com/yegor256/cactoos/issues/996) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0pdd** [comment]
@Shryne the puzzle [#1109](https://github.com/yegor256/cactoos/issues/1109) is still not solved.

**Comment by victornoel** [comment]
@Shryne the PR was merged, this issue can be closed now :)

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment]
The job [#996](https://github.com/yegor256/cactoos/issues/996) is now out of scope

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0pdd** [comment]
@Shryne the only puzzle [#1109](https://github.com/yegor256/cactoos/issues/1109) is solved here.
