### ISSUE TITLE
`org.catoos.io`/`org.cactoos.func` vs compound names

### ISSUE THREAD

**Issue by dgroup** [yegor256/cactoos#999]
Let's continue our discussion from https://github.com/yegor256/cactoos/issues/980#issuecomment-451635074.

There are a lot of implementations of `Bytes` present in `*.io` package and these implementation has compound names, like `CheckedBytes`, `UncheckedBytes`, etc.
What should be done with them? 

I would like to highlight that in order to avoid the compound names all implementations of `Input`, `Output`, `Bytes`, `Func`, `BiFunc`, `Proc`, `BiProc`, `Scalar`, `Text` should have their own packages.
Now, the some of implementation of `Bytes`, `Input`, `Output` shuffled between packages `org.cactoos.io`, `org.cactoos.bytes`. 
We can fix that by changing our packages structure to
```bash
org.cactoos.io
|- bytes
|- input
|- output
```
@llorllale 
> The general rule is to avoid compound names, yes, but sometimes technical limitations force us to keep using them in some cases. For example, there are more than one classes with the Checked prefix in their names in the io package. Removing the suffix would create a naming conflict. If you see any remaining classes in the io package or anywhere else with compound names that can be simplified without causing conflicts, please go ahead and refactor.

` Removing the suffix would create a naming conflict`
This is an indicator that this package has a lot of classes which suppose to be split. For example, the implementations of `Input`, `Output`, `Bytes` should have their own package.

The similar situation with `Func`, `Proc`,`BiProc` and `BiFunc`. All their implementations are presents in `org.cactoos.func`.
`Func` is an object, `org.cactoos.func.Unchecked`  is an object which doesn't throw the checked exception. The `Proc` is an object, and it should has  `Unchecked`  implementation, but due to presense in the `wrong` package it was named as `UncheckedProc`. Its just indicator that each interface should have a single package with all implementations. How we organize these packages, is a question to the ARC, as it's his decision.

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@dgroup 

> There are a lot of implementations of Bytes present in *.io package and these implementation has compound names, like CheckedBytes, UncheckedBytes, etc.
What should be done with them?

Move them to the existing `org.cactoos.bytes` package.

> Its just indicator that each interface should have a single package with all implementations.

I would rather wait for #915 before determining whether this reshuffling is worth it.

**Comment by victornoel** [comment]
@dgroup I think this is superseded by #1199 and #1406 (I know this ticket is older, but I didn't see it earlier). If you think there are more things to do going that way, please open a new ticket.

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#999` is not assigned, can't get performer
